### ISSUE TITLE
 inactive sessions

### ISSUE THREAD

**Issue by flexsoluciones** [EvolutionAPI/evolution-api#10]
Terminate inactive sessions to prevent useless sessions to take up space and resources

**Comment by leobaldoneto** [comment]
@flexsoluciones you can use the follow env to config the cleaning behavior:

`# Determine how long the instance should be deleted from memory in case of no connection.
# Default time: 5 minutes
# If you don't even want an expiration, enter the value false
DEL_INSTANCE=false`
