### ISSUE TITLE
Send Status

### ISSUE THREAD

**Issue by clikalogo** [EvolutionAPI/evolution-api#100]
No postman ou de outra forma, alguém conseguiu **Enviar Status**

Postman:
Send Message Controller >> **Send Status**

Status : 400

{
    **"status": 400,**
    "error": "Bad Request",
    "response": {
        "message": [
            **"TypeError: Cannot read properties of undefined (reading 'contextInfo')"**
        ]
    }
}

![image](https://github.com/EvolutionAPI/evolution-api/assets/107278009/50217231-7728-47c8-b7b0-75d5d260a087)
![image](https://github.com/EvolutionAPI/evolution-api/assets/107278009/68363d5f-ef70-4c05-bd56-9c59e38a929a)

**Comment by Belkior** [comment]
Algum retorno sobre esse issue?
