### ISSUE TITLE
Chatwoot is disabled

### ISSUE THREAD

**Issue by alanfrigo** [EvolutionAPI/evolution-api#1011]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Estou tentando configurar uma instancia para integrar com o chatwoot, tentei pelo manager e pelo postman e ambos apresentam o mesmo erro

### What did you expect?

Integração concluida com chatwoot

### What did you observe instead of what you expected?

Erro: Chatwoot is disabled

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/17d98ec9-c65c-4a42-a55c-ccc519c6adb5)

### Which version of the API are you using?

2.2.0 homolog

### What is your environment?

Docker

### If applicable, paste the log output

[Evolution API]    v2.2.0  198   -  Mon Oct 28 2024 17:44:39     ERROR   [InstanceController]  [string]  Chatwoot is not enabled 

### Additional Notes

Testei também em todas as tags disponíveis da versão 2.0 para cima, todas apresentam o mesmo problema. Testei setar apenas dns na cloudflare, mas nada funcionou

**Comment by alanfrigo** [comment]
Para quem estiver com o mesmo problema, encontrei...

a variável do ambiente estava como false

o correto é CHATWOOT_ENABLED=true

**Comment by halie412** [comment]
Thank you very much, I spent a day on this and it didn't occur to me to look in the documentation for environment variables because previous versions didn't have this option.
