### ISSUE TITLE
Chatwoot não apresenta caixa de entrada criada pela API.

### ISSUE THREAD

**Issue by luiztonucci** [EvolutionAPI/evolution-api#104]
Boa tarde, não aparece a caixa de entrada no chatwoot, nem quando se cria via comando API, nem criada dentro do próprio chatwoot.

**Comment by fabiohenriquen** [comment]
Tive o mesmo problema. Só resolvi reinstalando tudo do zero na VPS. Tanto chatwoot quanto Evolution.

**Comment by luiztonucci** [comment]
Bom dia Fabio, no meu caso eu já fiz isso mais de 10x e nada. Não sei mais o que fazer.
