### ISSUE TITLE
Não consigo configurar RabbitMQ

### ISSUE THREAD

**Issue by eduardocodes** [EvolutionAPI/evolution-api#1059]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Estou tentando configurar o RabbitMQ na Evolution API, seguindo o passo a passo da documentação: https://doc.evolution-api.com/v2/pt/integrations/rabbitmq

## Meu `docker-compose.yaml` ficou assim:

    - RABBITMQ_ENABLED=true
    - RABBITMQ_URI=amqp://admin:senha@rabbit.chatconsulta.com.br:5672/default
    - RABBITMQ_EXCHANGE_NAME=evolution_exchange
    - RABBITMQ_GLOBAL_ENABLED=true
    - RABBITMQ_EVENTS_APPLICATION_STARTUP=true
    - RABBITMQ_EVENTS_INSTANCE_CREATE=true
    - RABBITMQ_EVENTS_INSTANCE_DELETE=true
    - RABBITMQ_EVENTS_QRCODE_UPDATED=true
    - RABBITMQ_EVENTS_MESSAGES_SET=true
    - RABBITMQ_EVENTS_MESSAGES_UPSERT=true
    - RABBITMQ_EVENTS_MESSAGES_EDITED=true
    - RABBITMQ_EVENTS_MESSAGES_UPDATE=true
    - RABBITMQ_EVENTS_MESSAGES_DELETE=true
    - RABBITMQ_EVENTS_SEND_MESSAGE=true
    - RABBITMQ_EVENTS_CONTACTS_SET=true
    - RABBITMQ_EVENTS_CONTACTS_UPSERT=true
    - RABBITMQ_EVENTS_CONTACTS_UPDATE=true
    - RABBITMQ_EVENTS_PRESENCE_UPDATE=true
    - RABBITMQ_EVENTS_CHATS_SET=true
    - RABBITMQ_EVENTS_CHATS_UPSERT=true
    - RABBITMQ_EVENTS_CHATS_UPDATE=true
    - RABBITMQ_EVENTS_CHATS_DELETE=true
    - RABBITMQ_EVENTS_GROUPS_UPSERT=true
    - RABBITMQ_EVENTS_GROUP_UPDATE=true
    - RABBITMQ_EVENTS_GROUP_PARTICIPANTS_UPDATE=true
    - RABBITMQ_EVENTS_CONNECTION_UPDATE=true
    - RABBITMQ_EVENTS_CALL=true
    - RABBITMQ_EVENTS_TYPEBOT_START=true
    - RABBITMQ_EVENTS_TYPEBOT_CHANGE_STATUS=true

Também ativei na interface de usuário:

![image](https://github.com/user-attachments/assets/1d1867e5-b612-4aac-b1e0-5bb4a9789955)

Entretanto não ficou claro se devo criar uma fila específica no RabbitMQ ou se a mesma é criada automaticamente.

Enviei uma mensagem para testar e nenhuma fila foi criada automaticamente, portanto presumo que devo configurar manualmente. 

## Também tentei:
- Colocar `RABBITMQ_URI=amqp://admin:senha@https://rabbit.chatconsulta.com.br:5672/default` no `docker-compose.yaml`
- Colocar `RABBITMQ_URI=amqp://admin:senha@http://[IP-SERVIDOR]:5672/default` no `docker-compose.yaml`
- Colocar `RABBITMQ_URI=amqp://admin:senha@[IP-SERVIDOR]:5672/default` no `docker-compose.yaml`

## Gostaria de saber:
1) Estou fazendo a configuração correta?
2) Devo criar uma fila manualmente? Se sim, quais devem ser as configurações dessa fila?
3) É necessário criar manualmente uma exchange também? Se sim, quais dever ser as configurações dessa exchange?

### What did you expect?

Era esperado receber a mensagem de teste no RabbitMQ via EvolutionAPI.

### What did you observe instead of what you expected?

Nenhuma mensagem foi recebida pelo RabbitMQ.

### Which version of the API are you using?

v2.1.1

### What is your environment?

Docker

**Comment by tiagolau** [comment]
Olá, estou com a mesma dúvida do nosso amigo.
está dando o segundo erro

`[Evolution API]    v2.2.0  186   -  Fri Nov 15 2024 11:32:23     ERROR   [unhandledRejection]  [object]   

{

  origin: Promise {

    <rejected> Error: getaddrinfo EAI_AGAIN rabbitmq

        at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {

      errno: -3001,

      code: 'EAI_AGAIN',

      syscall: 'getaddrinfo',

      hostname: 'rabbitmq'

    }

  },

  stderr: 2

} `

**Comment by eduardocodes** [comment]
Consegui resolver de 2 formas:

1) Se você tem o `traefik` instalado fora do portainer, você deve removê-lo e instalar via portainer e depois fazer o apontamento como consta na documentação. 

Detalhe é que em `localhost:5672` você deve colocar o exato nome da stack do RabbitMQ: 
```
RABBITMQ_ENABLED=true
RABBITMQ_URI=amqp://admin:admin@localhost:5672/default
RABBITMQ_EXCHANGE_NAME=evolution_exchange
RABBITMQ_GLOBAL_ENABLED=true
```

Logo se a stack do seu RabbitMQ está com o nome `rabbit_mq` (exemplo), você deve colocar:
```
RABBITMQ_ENABLED=true
RABBITMQ_URI=amqp://admin:admin@rabbit_mq/default
RABBITMQ_EXCHANGE_NAME=evolution_exchange
RABBITMQ_GLOBAL_ENABLED=true
```

2) Utilizar um auto-instalador chamado `oreo` e instalar a Evolution e RabbitMQ por ele e fazer as configurações acima. Para usar o auto-instalador via CLI: `bash <(curl -sSL setup.oriondesign.art.br)`

As filas serão criadas automaticamente no RabbitMQ.
