### ISSUE TITLE
Mensagem recebida em duplicidade 

### ISSUE THREAD

**Issue by jhker7** [EvolutionAPI/evolution-api#106]
Mensagem sendo enviada pela API em duplicidade para números novos. Estou usando o Typebot v2.17.1 e EvolutionAPI 1.5. 

Quando envio um oi para iniciar a mensagem a API esta enviando em duplicidade as mensagens iniciais.

Não sei se tem como resolver esse problema

Grande abraço

**Comment by devrafasilveira** [comment]
Estou com o mesmo problema, quem puder ajudar agradeço..

**Comment by fabiohenriquen** [comment]
Estou com mensagem em duplicidade quando mando mensagem pelo celular que está logado numa instancia do chatwoot. A segunda mensagem inclusive vem com o nome do agente em negrito como se tivesse sido mandada pelo chatwoot.

Evolution: v1.5.0
Chatwoot: v3.0.0ce

**Comment by clikalogo** [comment]
Também (evolution X Typebot). Duplica e algumas vezes triplica.

**Comment by DavidsonGomes** [comment]
resolvido na versao 1.5.1
