### ISSUE TITLE
Send Message - Error status: 400 Bad request

### ISSUE THREAD

**Issue by williamzzz1** [EvolutionAPI/evolution-api#109]
Erro status 400 ao enviar mensagem.

Api funciona normal durante alguns dias e logo depois para de enviar e receber de alguns contatos, o log do pm2 acusa esse erro da imagem abaixo.

![image](https://github.com/EvolutionAPI/evolution-api/assets/52936830/0b3289df-c919-4a71-b878-d6cccc545f26)

**Comment by ppimentelrj** [comment]
Acontecendo exatamente a mesma coisa comigo...
Conseguiu resolver?

**Comment by williamzzz1** [comment]
> Acontecendo exatamente a mesma coisa comigo... Conseguiu resolver?

Não... A solução é gerar uma nova caixa de entrada quando algum cliente reclama...

**Comment by DavidsonGomes** [comment]
Erro No Sessions resolve reiniciando o serviço

**Comment by jonesheckler** [comment]
Bom dia, estou com o mesmo problema... mas percebo que são apenas alguns números... outros funcionam a dias sem problemas. 

Alguma solução alternativa? Vi que reiniciando, as vezes algumas instancias não conectam... ai preciso reiniciar umas 2 ou 3 vezes pra tudo voltar ao "normal"

**Comment by williamzzz1** [comment]
> Bom dia, estou com o mesmo problema... mas percebo que são apenas alguns números... outros funcionam a dias sem problemas.
> 
> Alguma solução alternativa? Vi que reiniciando, as vezes algumas instancias não conectam... ai preciso reiniciar umas 2 ou 3 vezes pra tudo voltar ao "normal"

depois que mudei pra docker nunca mais tive problema com esse erro
