### ISSUE TITLE
Problema ao deletar instancia Cannot read properties of null (reading 'apikey')

### ISSUE THREAD

**Issue by RDX777** [EvolutionAPI/evolution-api#110]
Ao usar o endpoint /instance/delete/ recebo sucesso, porem após isso não é mais possível usar a API.

**Mensagem Após usar o delete:**
{
	"status": 500,
	"error": "Internal Server Error",
	"response": {
		"message": "Cannot read properties of null (reading 'apikey')"
	}
}

**Retorno após a delação da instância:**
{
	"status": "SUCCESS",
	"error": false,
	"response": {
		"message": "Instance deleted"
	}
}

**Comment by RDX777** [comment]
Realizado uns testes via docker, e as instancias estão sendo apagadas normalmente.

**Comment by allandesa** [comment]
@RDX777 boa tarde, você conseguiu resolver esse problema? Estou passando pelo o mesmo

**Comment by RDX777** [comment]
> @RDX777 boa tarde, você conseguiu resolver esse problema? Estou passando pelo o mesmo

@allandesa quando isso aconteceu, estava usando as versões 1.5.0 e a 1.5.1, usando com mongo db e se não me engano o redis também. Fiz uma nova instalação da versão 1.5.1 sem banco de dados e nenhum redirecionamento de porta externa, e parou de dar esse erro nas instancias. Ate hoje não sei se era o evolution ou o chatwoot que esta causando inconsistências aqui em meu ambiente. Atualmente estou usando a versão 1.5.4 da mesma forma, sem banco de dados ou redirecionamentos externos. esta funcionando perfeitamente! Lembrando que fiz as instalações usando docker em uma infra interna.

**Comment by allandesa** [comment]
Reinstalei aqui usando o instalador da promovaweb e está funcional tb... obrigado @RDX777
