### ISSUE TITLE
Edit function / função editar

### ISSUE THREAD

**Issue by andifilhohub** [EvolutionAPI/evolution-api#1104]
### Bem-vindo!

- [X] Sim, pesquisei solicitações semelhantes no [GitHub](https://github.com/code-chat-br/whatsapp-api/issues) e não encontrei nenhum.

### Qual tipo de recurso?

Funcionalidade

### Qual a motivação para a solicitação?

Primeiramente, parabéns aos criadores e contribuidores pelo projeto. 

Eu gostaria de saber se a evolution oferece a função de editar mensagens usando a baileys. Se não, fica como sugestão para o projeto.

Desde já agradeço!

**Comment by rafwell** [comment]
Seria isso aqui? Ten na v1 e na v2.
https://doc.evolution-api.com/v1/api-reference/chat-controller/update-message

**Comment by andifilhohub** [comment]
amigo, eu tentei por esse caminho da documentação. Não sei se por ter feito alguma coisa errada, nao funcionou pra mim. Mas eu consegui por outro caminho aqui, criando uma função edita do zero. Ai deu certo! Mas obrigado.
