### ISSUE TITLE
V.2 Envio de Mídias não ocorre

### ISSUE THREAD

**Issue by mavis-martins** [EvolutionAPI/evolution-api#1112]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Estou criando uma aplicação web utilizando a Evolution e Typebot, não há integração com o chatwoot, pois estou construindo o front-end. Acontece que consigo fazer o envio de mídia (audio gravado, imagem, documentos, vídeos e gifs) em instâncias Baileys, mas em instâncias usando o Whatsapp Business, não vai, ele retorna erros dois erros diferentes, um para áudio e outro para as demais (docs, img, video, gif). As requisições/payloads para a instância oficial são diferentes?

### What did you expect?

Conseguir enviar as mídias também usando uma instância Business.

### What did you observe instead of what you expected?

Apesar de seguir os mesmo moldes descrito na documentação da Evolution e conseguir enviar mídias com Bailyes, não consigo enviar mídias usando instância do Business.

### Which version of the API are you using?

2.2.0

### What is your environment?

Windows

**Comment by yuri12344** [comment]
Quais sao os erros que retorna?

**Comment by mavis-martins** [comment]
Este foi o payload:

> {
>     "number": "<>",
>     "mediatype": "image",
>     "mimetype": "image/png",
>     "caption": "salve",
>     "media": "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAApgAAAKYB3X3/OAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAANCSURBVEiJtZZPbBtFFMZ/M7ubXdtdb1xSFyeilBapySVU8h8OoFaooFSqiihIVIpQBKci6KEg9Q6H9kovIHoCIVQJJCKE1ENFjnAgcaSGC6rEnxBwA04Tx43t2FnvDAfjkNibxgHxnWb2e/u992bee7tCa00YFsffekFY+nUzFtjW0LrvjRXrCDIAaPLlW0nHL0SsZtVoaF98mLrx3pdhOqLtYPHChahZcYYO7KvPFxvRl5XPp1sN3adWiD1ZAqD6XYK1b/dvE5IWryTt2udLFedwc1+9kLp+vbbpoDh+6TklxBeAi9TL0taeWpdmZzQDry0AcO+jQ12RyohqqoYoo8RDwJrU+qXkjWtfi8Xxt58BdQuwQs9qC/afLwCw8tnQbqYAPsgxE1S6F3EAIXux2oQFKm0ihMsOF71dHYx+f3NND68ghCu1YIoePPQN1pGRABkJ6Bus96CutRZMydTl+TvuiRW1m3n0eDl0vRPcEysqdXn+jsQPsrHMquGeXEaY4Yk4wxWcY5V/9scqOMOVUFthatyTy8QyqwZ+kDURKoMWxNKr2EeqVKcTNOajqKoBgOE28U4tdQl5p5bwCw7BWquaZSzAPlwjlithJtp3pTImSqQRrb2Z8PHGigD4RZuNX6JYj6wj7O4TFLbCO/Mn/m8R+h6rYSUb3ekokRY6f/YukArN979jcW+V/S8g0eT/N3VN3kTqWbQ428m9/8k0P/1aIhF36PccEl6EhOcAUCrXKZXXWS3XKd2vc/TRBG9O5ELC17MmWubD2nKhUKZa26Ba2+D3P+4/MNCFwg59oWVeYhkzgN/JDR8deKBoD7Y+ljEjGZ0sosXVTvbc6RHirr2reNy1OXd6pJsQ+gqjk8VWFYmHrwBzW/n+uMPFiRwHB2I7ih8ciHFxIkd/3Omk5tCDV1t+2nNu5sxxpDFNx+huNhVT3/zMDz8usXC3ddaHBj1GHj/As08fwTS7Kt1HBTmyN29vdwAw+/wbwLVOJ3uAD1wi/dUH7Qei66PfyuRj4Ik9is+hglfbkbfR3cnZm7chlUWLdwmprtCohX4HUtlOcQjLYCu+fzGJH2QRKvP3UNz8bWk1qMxjGTOMThZ3kvgLI5AzFfo379UAAAAASUVORK5CYII=",
>     "fileName": "salve.png",
>     "delay": 5000
> }


Erro:

>  json
> {
>     "status": 500,
>     "error": "Internal Server Error",
>     "response": {
>         "message": [
>             "TypeError: Cannot read properties of undefined (reading 'name')"
>         ]
>     }
> }




> Bug ao enviar imagem-------------------------------------------------------
> 2024-12-13 21:07:07 TypeError: Cannot read properties of undefined (reading 'name')
> 2024-12-13 21:07:07     at FormData._getContentDisposition (/evolution/node_modules/form-data/lib/form_data.js:227:40)
> 2024-12-13 21:07:07     at FormData._multiPartHeader (/evolution/node_modules/form-data/lib/form_data.js:178:33)
> 2024-12-13 21:07:07     at FormData.append (/evolution/node_modules/form-data/lib/form_data.js:71:21)
> 2024-12-13 21:07:07     at ps.getIdMedia (/evolution/dist/main.js:241:1712)
> 2024-12-13 21:07:07     at ps.prepareMediaMessage (/evolution/dist/main.js:241:2446)
> 2024-12-13 21:07:07     at ps.mediaMessage (/evolution/dist/main.js:241:2662)
> 2024-12-13 21:07:07     at ts.sendMedia (/evolution/dist/main.js:2:21962)
> 2024-12-13 21:07:07     at execute (/evolution/dist/main.js:282:124001)
> 2024-12-13 21:07:07     at mn.dataValidate (/evolution/dist/main.js:282:61396)
> 2024-12-13 21:07:07     at /evolution/dist/main.js:282:123941 
> 
> Bug ao enviar audio--------------------------------------------------------------
> 
> 2024-12-13 21:05:26 TypeError: Cannot read properties of undefined (reading 'toString')
> 2024-12-13 21:05:26     at ps.messageHandle (/evolution/dist/main.js:236:2302)
> 2024-12-13 21:05:26     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
> 2024-12-13 21:05:26 
> 2024-12-13 21:06:18 El archivo no tiene buffer o file es undefined
> 2024-12-13 21:06:54 El archivo no tiene buffer o file es undefined

**Comment by yuri12344** [comment]
"number": "<>" vazio?

**Comment by mavis-martins** [comment]
Consegui enviar mídias como imagens, documentos e vídeos passando a URL do arquivo ao invés do Base64.
