### ISSUE TITLE
Tumb

### ISSUE THREAD

**Issue by gfmozzer** [EvolutionAPI/evolution-api#112]
Eu tenho percebido que quando envio um link de um video, do youtube por exemplo, normalmente a miniatura nao aparce no envio.

![image](https://github.com/EvolutionAPI/evolution-api/assets/66847492/24633823-77d9-4bfe-9c4c-0b007c673777)

**Comment by andrellsousa** [comment]
> Eu tenho percebido que quando envio um link de um video, do youtube por exemplo, normalmente a miniatura nao aparce no envio.
> 
> ![image](https://user-images.githubusercontent.com/66847492/268304358-24633823-77d9-4bfe-9c4c-0b007c673777.png)

Tenta mudar essa linha para "linkPreview": true e veja se funciona.

**Comment by DavidsonGomes** [comment]
Link compartilhado do youtube nao aparece mesmo, isso é da propria Baileys

**Comment by gbretas** [comment]
Errado, teste o link sem ser encurtado, que ai ele funciona.
