### ISSUE TITLE
Porque fazer o uso do seu próprio fork do Baileys?

### ISSUE THREAD

**Issue by leomeneguzzi** [EvolutionAPI/evolution-api#113]
Olá, eu estava rodando localmente e percebi que a dependência do `Baileys` é um fork de vocês:
- https://github.com/EvolutionAPI/Baileys

Também notei que nesse fork a única diferença é o uso da lib `libsignal-node`, que também é um fork de vocês:
- https://github.com/WhiskeySockets/Baileys/commit/580f0e586e0645151cc17900516dd5b204d21a77
- https://github.com/EvolutionAPI/libsignal-node

Gostaria de entender quais foram as necessidades que fizeram vocês tomarem essa decisão.

Desde já, obrigado a vocês 😄

**Comment by DavidsonGomes** [comment]
Estamos testando algumas configurações especificas
