### ISSUE TITLE
Fluxo não inicia com palavra chave

### ISSUE THREAD

**Issue by jeffsystem** [EvolutionAPI/evolution-api#115]
Prezado, quando o usuário vem através de anúncios e que o fluxo precisa ser iniciado por determinada palavra chave, o robô só inicia quando envia 2 vezes a mensagem assim como no print abaixo.

![WhatsApp Image 2023-09-17 at 23 15 30](https://github.com/EvolutionAPI/evolution-api/assets/39931647/6fef6597-f834-479d-825b-2be1a3ff42c2)

Segue o fluxo no typebot

![WhatsApp Image 2023-09-17 at 23 16 19](https://github.com/EvolutionAPI/evolution-api/assets/39931647/e153ce82-8e1a-4d3f-886f-3c5444845d8e)

**Comment by TonnDev** [comment]
Eu estava com esse mesmo problema, resolvi de alguma forma que eu não me recordo agora. Mas sei que o problema esta no bloco "Collect". Pois ele não coleta a primeira mensagem do fluxo, mas sim, ele coleta depois da primeira mensagem que no caso é a segunda.

Pois a primeira mensagem dispara apenas uma mensagem inicial no fluxo, para depois coletar a entrada do usuário na segunda mensagem com o bloco Collect.

**Comment by jeffsystem** [comment]
Preciso muito resolver isso para conseguir usar, se você puder me chama no whatsapp para tentarmos lembrar juntos dessa solução. (22) 99849-41474 

> Eu estava com esse mesmo problema, resolvi de alguma forma que eu não me recordo agora. Mas sei que o problema esta no bloco "Collect". Pois ele não coleta a primeira mensagem do fluxo, mas sim, ele coleta depois da primeira mensagem que no caso é a segunda.
> 
> Pois a primeira mensagem dispara apenas uma mensagem inicial no fluxo, para depois coletar a entrada do usuário na segunda mensagem com o bloco Collect.

**Comment by Danieloutliers** [comment]
opa amigo conseguiu resolver

**Comment by Nilbertocs** [comment]
Estou com o mesmo problema, conseguiu resolver?

**Comment by Termica** [comment]
Estou com o messmo problema, alguma sugestão?

**Comment by DavidsonGomes** [comment]
Esta cientes da questão já, vamos trabalhar para melhorar esse comportamento
