### ISSUE TITLE
Manager de instâncias 

### ISSUE THREAD

**Issue by devrafasilveira** [EvolutionAPI/evolution-api#116]
Não consigo criar instância para o typebot pela manager, na verdade ele até cria, mas acontece o seguinte: 
Obs: Também da para criar pelo **Create Instance With Typebot**

Fiz um **Fetch Instances** da api e nao carrega, da o seguinte erro:
"Cloud Agent Error: Request is taking longer than 30 seconds to fulfill. Use another agent to send a request without time limitations"

Fiz um **Instance Connect** e ate aparece o QR Code, mas ao ler o mesmo no whatsapp da uma mensagem:
"Não foi possível associar o dispositivo, volte a tentar mais tarde"

Alguma solução para isso?
Obrigado.

**Comment by clikalogo** [comment]
Problema v1.5.1

**Via Manager:**
1. Está criando uma nova instância, mas não exibe a instancia para conectar no painel;
2. Está exibindo o qrcode no terminal.
3. Trava a criação/consultas de instancias no postman;
4. Só exibe as instâncias no painel **após conectar via leitura do qrcode no terminal**;
5. Só libera a criação/consultas  no postman **após conectar a instancia lendo o qrcode no terminal;**

**Comment by ildo19** [comment]
Estou com mesmo problema, não cria instância e da erro na hora de criar,  ALGUÉM sabe como remover da VPS e instalar a versão antiga?vou então sabem como concertar esses bugs?

**Comment by DavidsonGomes** [comment]
Resolvido na versao 1.5.2
