### ISSUE TITLE
docker build - v1.5.1

### ISSUE THREAD

**Issue by clikalogo** [EvolutionAPI/evolution-api#117]
Olá @DavidsonGomes, utilizo arquitetura ARM por ser mais barata e ter o rendimento satisfatório. 
Na v1.5.0 conseguia compilar/executar o **docker build** localmente sem problema.
Na V1.5.1, está parado na 5/7(imagem erro). Não é possível finalizar o build, a biblioteca **puppeteer** e/ou **querystring**.

1. Possibilidade de ter a compilação ARM no HUB Docker (https://hub.docker.com/r/davidsongomes/evolution-api/tags) ?
ou
2. Modificar o "Dockerfile"?

![image](https://github.com/EvolutionAPI/evolution-api/assets/107278009/fb91745a-0568-4793-b026-87014afa287d)

**Comment by AndreGMeister** [comment]
> Olá @DavidsonGomes, utilizo arquitetura ARM por ser mais barata e ter o rendimento satisfatório. Na v1.5.0 conseguia compilar/executar o **docker build** localmente sem problema. Na V1.5.1, está parado na 5/7(imagem erro). Não é possível finalizar o build, a biblioteca **puppeteer** e/ou **querystring**.
> 
> 1. Possibilidade de ter a compilação ARM no HUB Docker (https://hub.docker.com/r/davidsongomes/evolution-api/tags) ?
>    ou
> 2. Modificar o "Dockerfile"?
> 
> ![image](https://user-images.githubusercontent.com/107278009/268664914-fb91745a-0568-4793-b026-87014afa287d.png)

Tambem utilizo ARM e ao atualizar ocorreu mesmo erro porem uso via PM2

**Comment by emersonbock** [comment]
Fiz umas modificações no Dockerfile, estou testando e aparentemente funcionou. Ajudem a testar...

Modificação no começo do Dockerfile você pode substituir ou baixar o arquivo online [Dockerfile]()

`FROM node:20.6.1-bullseye

LABEL version="1.5.1" description="Api to control whatsapp features through http requests."
LABEL maintainer="Davidson Gomes" git="https://github.com/DavidsonGomes"
LABEL contact="contato@agenciadgcode.com"

RUN apt-get update -y
RUN apt-get upgrade -y
# Installing git as it is commonly used for various build processes
RUN apt-get install -y git tzdata ffmpeg wget curl chromium

WORKDIR /evolution

COPY ./package.json .

RUN npm i -g npm@10`

**Comment by MattCarneiro** [comment]
Tb utilizo ARM e deu esse erro.
Mudei pra x64 pra consertar.
No geral, esse update 1.5.1 veio com dezenas de bugs.
O melhor por hora é todo mundo fazer o downgrade pro 1.5.0

**Comment by leandrofreires** [comment]
@emersonbock não tinha vista essa issue, acho que acabei criando uma duplicata  #125 
de qualquer forma, o pessoal vai aceitar subir uma pr ?

**Comment by clikalogo** [comment]
@emersonbock @leandrofreires 
No Dockerfile (original), apenas adicionar "chromium" ao final da linha 8.

de : apk add --no-cache git tzdata ffmpeg wget curl
para: apk add --no-cache git tzdata ffmpeg wget curl chromium

**Imagem:**
de: ~699 Mb
para: 1.2 Gb

Atualmente testando a v1.5.1 (Develop)

**Comment by emersonbock** [comment]
Versão nova liberada EvolutionApi 1.5.2, build realizado com sucesso, vamos testar a api...

Comando que pode facilitar pra vocês:

docker build -t evolutionapi:v1.5.2 https://github.com/EvolutionAPI/evolution-api.git#1.5.2

**Comment by DavidsonGomes** [comment]
resolvido na versao 1.5.2

**Comment by kleves** [comment]
eu consegui gerar criando um Dockerfile específico, funcionando em OCI - Arm64

**Comment by Rod-Gomes** [comment]
Pessoal, gostaria de retomar a discussão sobre a execução da EvolutionAPI em um Raspberry Pi, que utiliza sistema ARM. Até agora, ARM possui compatibilidade com várias ferramentas, como Typebot e Chatwoot, exceto para a EvolutionAPI.

A instalação em sistemas ARM é complicada, exigindo a construção manual e impedindo atualizações automáticas via Docker. Seria muito útil se pudessem disponibilizar uma imagem pré-compilada para sistemas ARM, servindo tanto para Macs quanto para Raspberry Pi e outros dispositivos com esse tipo de processador. Isso simplificaria o processo de instalação e atenderia a uma comunidade mais ampla.

**Comment by 4rielmendes** [comment]
> eu consegui gerar criando um Dockerfile específico, funcionando em OCI - Arm64

continua funcionando?

**Comment by 4rielmendes** [comment]
> resolvido na versao 1.5.2

Olá Davidson, no docker hub não tem suporte pra arm64?

**Comment by dilneiss** [comment]
pessoal, retornando a essa discussão, vi que é possível na hora de gerar a imagem já gerar para outras arquiteturas, poderiam já disponibilizar em arm64 também por favor? vai ajudar muito quem usa essa arquitetura, é mais barata e rendimento excelente

**Comment by itxtoledo** [comment]
é interessante que na pasta .github tem configurado o build e o pull pro docker hub da versão amd64 e arm64, mas eles nao estão sendo usados
