### ISSUE TITLE
Error creating instance

### ISSUE THREAD

**Issue by parlitoparlo** [EvolutionAPI/evolution-api#118]
Olá, estou tentando criar uma instancia no Evolution Api, porem esta dando erro

Hello, I'm trying to create an instance in Evolution Api, but it's giving me an error
![photo_2023-09-18_14-27-22](https://github.com/EvolutionAPI/evolution-api/assets/86086328/475abf26-4f20-4594-90ed-6f8a0f92930a)

**Comment by clikalogo** [comment]
Problema v1.5.1

**Via Manager:**
1. Está criando uma nova instância, mas não exibe a instancia para conectar no painel;
2. Está exibindo o qrcode no terminal.
3. Trava a criação/consultas de instancias no postman;
4. Só exibe as instâncias no painel após conectar via leitura do qrcode no terminal;
5. Só libera a criação/consultas  no postman após conectar a instancia lendo o qrcode no terminal;

**Comment by ildo19** [comment]
Estou com mesmo problema, não cria instância e da erro na hora de criar,  ALGUÉM sabe como remover da VPS e instalar a versão antiga?vou então sabem como concertar esses bugs?

**Comment by DavidsonGomes** [comment]
Resolvido na versao 1.5.2
