### ISSUE TITLE
Error creating instance

### ISSUE THREAD

**Issue by br55onze** [EvolutionAPI/evolution-api#119]
Tentei criar instancias, sem sucesso, e tambem da erro de restaurar poderiam me ajudar?

![image](https://github.com/EvolutionAPI/evolution-api/assets/145412384/c9d461c1-b2fc-40dd-a8c3-9bdf84160706)

**Comment by matheusfterra** [comment]
mesma coisa aqui. se crio a instancia pelo postman, ela nao aparece ai, e se crio com chatwoot, nao cria o inbox no chatwoot :/

**Comment by clikalogo** [comment]
Problema v1.5.1

**Via Manager:**
1. Está criando uma nova instância, mas não exibe a instancia para conectar no painel;
2. Está exibindo o qrcode no terminal.
3. Trava a criação/consultas de instancias no postman;
4. Só exibe as instâncias no painel após conectar via leitura do qrcode no terminal;


Só exibe as instâncias criadas via postman ou outra forma ex. Curl

**Comment by charlesab10** [comment]
Mesmo problema

**Comment by executivotelemed** [comment]
também estou com problema, antes estava criando instancia sem problema algum e do nada parou de criar sem nenhuma alteração.

**Comment by MattCarneiro** [comment]
Update totalmente bugado esse 1.5.1 
Não tá criando instancia
Alguém sabe alguma forma de reverter pro 1.5.0?

Aqui quando eu crio pelo n8n dá isso aqui

ERROR: Bad request - please check your parameters
400 - "{\"status\":400,\"error\":\"Bad Request\",\"response\":{\"message\":[\"C\"]}}"
 Details
Time
20/09/2023, 15:32:28
Item Index: 0
HTTP Code
400
Cause
Data below may contain sensitive information. Proceed with caution when sharing.
{
"status": 
"rejected",
"reason": 
{
"message": 
"400 - "{\"status\":400,\"error\":\"Bad Request\",\"response\":{\"message\":[\"C\"]}}"",
"name": 
"Error",
"stack": 
"Error: 400 - "{\"status\":400,\"error\":\"Bad Request\",\"response\":{\"message\":[\"C\"]}}" at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15) at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12) at RedirectableRequest.handleResponse (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:238:9) at RedirectableRequest.emit (node:events:526:35) at RedirectableRequest.emit (node:domain:489:12) at RedirectableRequest._processResponse (/usr/local/lib/node_modules/n8n/node_modules/follow-redirects/index.js:356:10) at ClientRequest.RedirectableRequest._onNativeResponse (/usr/local/lib/node_modules/n8n/node_modules/follow-redirects/index.js:62:10) at Object.onceWrapper (node:events:629:26) at ClientRequest.emit (node:events:514:28) at ClientRequest.emit (node:domain:489:12)"
}
}

**Comment by ildo19** [comment]
Estou com mesmo problema, não cria instância e da erro na hora de criar,  ALGUÉM sabe como remover da VPS e instalar a versão antiga?vou então sabem como concertar esses bugs?

**Comment by clikalogo** [comment]
@ildo19 
Até o momento, utilizar a v1.5.1 (develop).

**Comment by antoniorocha** [comment]
Estou com o mesmo erro, estou usando a {"status":200,"message":"Welcome to the Evolution API, it is working!","version":"1.5.1"}
Sabe o que posso fazer?

**Comment by antoniorocha** [comment]
E outra duvida, como fazer o downgrade caso precisar?
meu node é o 20.0

**Comment by antoniorocha** [comment]
voltei para 1.4.8 e deu certo.

pm2 flush
pm2 stop ApiEvolution
git checkout 1.4.8
rm -rf node_modules
npm i
pm2 start ApiEvolution
pm2 log ApiEvolution

**Comment by ildo19** [comment]
> voltei para 1.4.8 e deu certo.
> 
> pm2 flush pm2 stop ApiEvolution git checkout 1.4.8 rm -rf node_modules npm i pm2 start ApiEvolution pm2 log ApiEvolution

Quando executo o comando: Git checkout 1.4.8 ele me dá este erro: fatal: not a git repository (or any of the parent directories): .git   o que será que tá faltando? E como posso concertar?

**Comment by DavidsonGomes** [comment]
Problema resolvido na versao 1.5.2
