### ISSUE TITLE
Problema de Integração entre Evolution API e Chatwoot v3.0

### ISSUE THREAD

**Issue by figueredofx** [EvolutionAPI/evolution-api#120]
Contexto:

Eu tenho duas VPS separadas, uma executando a Evolution API e outra executando o Chatwoot v3.0.
A integração funciona perfeitamente quando a Evolution é conectada a qualquer versão abaixo da 3.0 do Chatwoot.
Problema:

Ao tentar instalar a Evolution API com o Chatwoot v3.0, enfrento o seguinte erro: Quando crio uma instância usando o super admin (ID da conta 1), tudo funciona bem.
No entanto, quando tento criar uma instância para um cliente, usando um token e o ID da conta 2, (para um cliente por exemplo) o sistema não funciona. Ele cria a caixa de chat, mas não envia a mensagem "init".
Ao tentar enviar manualmente a mensagem "init" para o contato da Evolution, recebo a mensagem de erro "Não foi possível enviar essa mensagem".

Passos para Reproduzir:

Instalar a Evolution API na mesma ou em outra VPS que o Chatwoot v3.0.
Criar uma instância usando o super admin (ID da conta 1) - Funciona.
Criar uma instância usando um token e o ID da conta 2 - Não funciona.
Tentar enviar manualmente a mensagem "init" na cont 2 - Receber a mensagem de erro.

**Comment by EriveltonThomaz** [comment]
Olá, bom dia @figueredofx, tudo tranquilo?
Tive com o mesmo problema por semanas, até encontrar a resposta na comunidade do chatwoot, lá encontrei que ao criar uma nova conta "empresa", a opção response_bot tem que ficar desativada, pelo menos por hora, pois estavam arrumando. Então, fui dar uma olhada de como é criada a primeira conta editando a mesma e me deparei com algumas outras opções desmarcadas e desde então só crio uma nova conta dessa maneira. 

![image](https://github.com/EvolutionAPI/evolution-api/assets/99447097/b1ef1e59-6fb8-47a5-9d70-518e62b40c8a)

**Comment by figueredofx** [comment]
Obrigado amigo, é uma  excelente solução até sair uma correção, muito obrigado funcionou.

**Comment by jayceadler** [comment]
eu estou com esse problema... to na versao 4.1... mas mesmo sem o response_bot nao envia.

**Comment by tech3br** [comment]
> eu estou com esse problema... to na versao 4.1... mas mesmo sem o response_bot nao envia.

desativa os outros que são business tbm. deixa igual ao print
