### ISSUE TITLE
Problemas ao enviar mídias para o Celular usando o Typebot ou Postman

### ISSUE THREAD

**Issue by ezequiel-moura** [EvolutionAPI/evolution-api#123]
Foi criado um webhook no Typebot para envio de midias, usando o método: /message/sendMedia/
Body:
{
    "number": "{{remoteJid}}",
    "options": {
        "delay": 1200,
        "presence": "composing"
    },
    "mediaMessage": {
        "mediatype": "image",
        "caption": "This is an example JPG image file sent by Evolution-API via URL.",
        "media": "https://evolution-api.com/files/evolution-api.jpg"
    }
}

A mídia é recebida apenas no Whatsapp Web. No celular ela não é apresentada.
Testei usando o Postman e o corre o mesmo problema.

**Comment by MattCarneiro** [comment]
A versão 1.5.1 está totalmente bugada. Você consegue me enviar essa versão 1.5.0 pra eu fazer o downgrade?

**Comment by ezequiel-moura** [comment]
@MattCarneiro https://github.com/EvolutionAPI/evolution-api/tree/530aec92a9c7790dd0fd0f37500b2e05d5784a32

**Comment by MattCarneiro** [comment]
> @MattCarneiro https://github.com/EvolutionAPI/evolution-api/tree/530aec92a9c7790dd0fd0f37500b2e05d5784a32

Obrigado my friend

**Comment by DavidsonGomes** [comment]
Problema resolvido na versao 1.5.2

**Comment by ernaneluis** [comment]
Reparei o mesmo problema na versao 1.60 -  a imagem so aparece na Web, no celular não
