### ISSUE TITLE
Chatwoot não manda msg para o whatsapp

### ISSUE THREAD

**Issue by executivotelemed** [EvolutionAPI/evolution-api#127]
Criei uma instancia usando integração da evolution api de whatsapp junto ao chatwoot. A instancia é criada e connecto meu numero pelo QRcode gerado, recebo todas as msg normalmente na minha inbox, porem quando vou responder usando o chatwoot a msg nunca chega ao destinatario.

Não recebo nenhuma msg de erro, nem tem log de erro no console também. Menor ideia por onde começar a debugar, se alguem tiver alguma ideia?

**Comment by figueredofx** [comment]
Se você está usando a versão 3.0 do Chatwoot só funciona se criar tudo pela conta principal é bug não se se da API ou do Chatwoot, mas eu informei isso na issue #120

**Comment by leomeneguzzi** [comment]
Quando eu rodei localmente o chatwoot com docker-compose e tive esse problema de não enviar a mensagem pelo chatwoot, só recebia as mensagens. Eu percebi que mesmo aparentemente tudo funcionando certinho, um dos containers não tava rodando. O container em questão é o `sidekiq`
![Screenshot 2023-09-22 at 18 56 39](https://github.com/EvolutionAPI/evolution-api/assets/7086176/1d79d500-1fdd-4bd6-bd44-8b4826e17b23)

Ele é responsável por fazer o processamento das `background tasks`. E como ele não tava rodando, a mensagem não era enviada.

A arquitetura do chatwoot no envio de mensagens é mais ou menos assim:
1. Você escreve a mensagem no chat e dá o comando pra "enviar"
2. Essa requisição vai pro servidor, o servidor então coloca esse `event` na fila (o chatwoot por padrão usa o redis como database da fila, acho que nem tem como mudar isso)
3. Dai esse evento fica lá esperando na fila pra ser processado
4. Dai o `sidekiq` fica esperando eventos novos chegarem, quando o evento da mensagem aparece, ele processa o evento

Ou seja, quem envia a mensagem de fato é o `sidekiq` como uma `background task`, por mais que a interface gráfica esteja carregando e funcionando, não é ela quem de FATO envia as mensagens.

**Comment by arturmpaiva** [comment]
Consertou isso como? Alguém ainda teve esse problema apenas para envio de mensagens?

**Comment by emanuelmarlon** [comment]
o meu chatwoot nao envia mensagem pelo painel so recebe
