### ISSUE TITLE
[ Typebot ] Alguma forma do Typebot escutar apenas as mensagens recebidas?

### ISSUE THREAD

**Issue by guilessa** [EvolutionAPI/evolution-api#128]
Olá, bom dia! Estou tendo um problema que está me deixando de cabelo em pé. 

O Typebot está lendo todas as mensagens, tanto a do transmissor quanto a do receptor, por isso, ele está iniciando o bot automaticamente quando tento conversar através do Whatsapp com qualquer número. 

Existe alguma forma de corrigir isso? Vi que a opção "listening_from_me" foi inserida, mas não sei se é referente a isso. 

Desde já agradeço! O trabalho de vocês é incrível! :rocket:

**Comment by MattCarneiro** [comment]
Essa versão atual está cheia de bugs. Pode ser que seja mais um. Vamos aguardar a nova versão

**Comment by figueredofx** [comment]
> Olá, bom dia! Estou tendo um problema que está me deixando de cabelo em pé.
> 
> O Typebot está lendo todas as mensagens, tanto a do transmissor quanto a do receptor, por isso, ele está iniciando o bot automaticamente quando tento conversar através do Whatsapp com qualquer número.
> 
> Existe alguma forma de corrigir isso? Vi que a opção "listening_from_me" foi inserida, mas não sei se é referente a isso.
> 
> Desde já agradeço! O trabalho de vocês é incrível! 🚀

Na última versão v1.5.1 tem a opção Listening From Me (Me ouvindo) que faz com que o Typebot não escute suas mensagens e não fique interceptando.


O ideal é no seu fluxo quando o atendimento chegar para o atendimento humano, enviar um POST para PAUSAR o bot.

**Comment by DavidsonGomes** [comment]
Na ultima versao temos a opção listening_from_me, basta definir como false

**Comment by luizfeliperc** [comment]
Pessoal, 

Conheci o Typebot ontem e estou testando os fluxos, porém estou com o mesmo problema que o amigo. Fiz a instalação toda, tudo está rodando a ultima versão porém ao adicionar a variável "listening_from_me" no criador de instancia não tenho sucesso.

![image](https://github.com/EvolutionAPI/evolution-api/assets/29809390/6dddf7ec-04da-4fad-928b-4b8210884f73)
![image](https://github.com/EvolutionAPI/evolution-api/assets/29809390/40db28c7-a417-4413-9f7b-e0f2af14a43a)

Continuo recebendo mensagens do bot quando eu mesmo envio.

**Comment by luizfeliperc** [comment]
Pessoal, depois de ver alguns vídeos consegui resolver fazendo a configuração toda via Postman e o BOT não responde mais quando eu envio resposta.

**Comment by zeroonend** [comment]
> Pessoal, depois de ver alguns vídeos consegui resolver fazendo a configuração toda via Postman e o BOT não responde mais quando eu envio resposta.

pode me ajudar?
