### ISSUE TITLE
[TYPEBOT] Não reconhece primeira mensagem

### ISSUE THREAD

**Issue by dronasci** [EvolutionAPI/evolution-api#129]
No vídeo https://www.youtube.com/watch?v=AUghhPqLSnk, a partir de 01:05:00, é exibido o recurso de pegar a primeira saudação do cliente e tomar uma ação de acordo com ela. Na pratica ele só começa a receber no input a partir da segunda e no vídeo não foi percebido o ocorrido.

Evolution 1.5.1

**Comment by Termica** [comment]
Estou com esse mesmo problema aqui, coloquei uma BUBBLE primeiro e ele respondeu ao primeiro chamado, mas agora estou na duvida de como eu faria o teste de palavra chave...

![image](https://github.com/EvolutionAPI/evolution-api/assets/33319531/4729ddc2-5567-4ba1-be53-65f3e79ac38d)

**Comment by MattCarneiro** [comment]
Essa versão está cheia de bugs. Esperar a próxima

**Comment by andrerds** [comment]
Fala amigos, tb estou com esse problema que está bem chato.
Tentei usar o N8n para interceptar as mensagens da api evo, e depois forçar o inicio no typeboty, passando uma 

queryparans , https://bot.typebot.....com.br?firstMsg="mensagemrecebidanon8n"
umas baita gambiarra e nada, o fantastico e usar somente o typebot + api evo .

Acho que toda comunidade esta com esse mesmo problema, e talvez quem resolveu isso não passa.

Tb segui alguns videos e dicas da comunidade para pegar a primeira mensagem. Mas o problema e que as vezes so inicia na segunda , ai quebra geral.

**Comment by Termica** [comment]
eu tava pensando em uma maneira de configurar uma forma de o typeboot pegar a mensagem do usuário e mandal-a novamente para o type

**Comment by Termica** [comment]
ou seja, duplicar a mensagem do usuário no evolution pra ele já reconhecer o segundo imput no typeboot

**Comment by andrerds** [comment]
> ou seja, duplicar a mensagem do usuário no evolution pra ele já reconhecer o segundo imput no typeboot

interessante, pode ser que dê bom. 
Eu tentei usar o n8n, forçar a iniciar o bot , mas não rolou. (pode ser que fiz errado) mas não deu certo. E tb acabei abandonando, pois usar + uma ferramenta. Pode ser que funcione, o problema e a manutenção futura.... até lembrar onde foi que mexeu para ajustar...

**Comment by brunorg12** [comment]
isso já foi solucionado ou permanece?
