### ISSUE TITLE
endpoint Read Messages não funciona

### ISSUE THREAD

**Issue by DRIMOL** [EvolutionAPI/evolution-api#130]
Evolution 1.5.0

O endpoint [PUT]{{baseUrl}}/chat/markMessageAsRead/{{instance}} não está funcionando.

sempre retorna um erro 400 -   "instance requires property \"read_messages\""

Funciona apenas na versão 1.4.2 para trás

**Comment by DavidsonGomes** [comment]
Ola tudo bem?

Na verdade é um erro no nosso postman, obrigado por reportar, para funcionar utilize dessa forma

<img width="190" alt="Captura de Tela 2023-09-30 às 07 00 01" src="https://github.com/EvolutionAPI/evolution-api/assets/24706726/9eae8882-296f-4404-a0b0-9953b2dfca84">

**Comment by allangdy** [comment]
Este problema está ocorrendo novamente na versão 2.0.

<img width="732" alt="Screenshot 2024-09-13 at 16 08 34" src="https://github.com/user-attachments/assets/c2f4a02c-62dd-4fa2-8396-c4be4e8e7260">

Quando quando utilizado o método POST retorna dizendo que precisa da propriedade "readMessages", quando passado os parâmetros como "readMessage" retorno 200 porém não marca como lido.
