### ISSUE TITLE
variaveis do chatwoot name_inbox e webhook_url

### ISSUE THREAD

**Issue by Clarck1** [EvolutionAPI/evolution-api#134]
Olá,
no endpoint create instance from chatwoot poderia haver a possibilidade de setar o name_inbox e webhook_url, assim como são as outras variáveis...

    "chatwoot_account_id": 1,
    "chatwoot_token": "token",
    "chatwoot_url": "https://app.chatwoot.com",
    "chatwoot_sign_msg": true,
    "chatwoot_reopen_conversation": true,
    "chatwoot_conversation_pending": false

se fosse possível acrescentar:
    "chatwoot_name_inbox": "Nome Diferente da Instância pra aparecer na caixa de entrada do chatwoot",
    "chatwoot_webhook_url": "pra gente poder acrescentar http ou https e tbm a porta 8080 ou outra que tenhamos definida"

posso estar falando alguma besteira, mas, acontece que se criamos uma instância com php time() pra não travar um nome de instância, lá no chatwoot se mudamos o nome da caixa de entrada, pára de funcionar a instância dentro do chatwoot.
E quando usamos um servidor contendo porta na url temos que editar nas config da caixa de entrada no chatwoot.

digo isso porque estou tentando criar algo escalável pra poder automatizar o uso pelos meus usuários que são leigos.
se isso der certo, todos ganham.

Como podem ver na imagem... se eu ajustar manualmente a url webhook passa funcionar tudo ok.
Se eu mudar o nome da caixa de entrada não funciona mais nada da EvolutionAPI dentro do chatwoot.
<img width="1615" alt="Captura de Tela 2023-09-27 às 00 57 14" src="https://github.com/EvolutionAPI/evolution-api/assets/20227825/334ce0dd-3ebf-4ded-b657-6afcdb2a0dfc">

será que há uma solução viável pra isso?

**Comment by eduardochaves1** [comment]
Nos testes que fiz (Evo=1.5.4, Chatwoot=3.1.1), se mudarmos o nome da caixa de entrada do Chatwoot ainda será possível enviar mensagem, porém a inbox no Chatwoot não mais receberá mensagens da api.

Pelo visto o Evo Api faz a conexão com o Chatwoot através do NOME da caixa de entrada ao invés de ser pelo ID da caixa de entrada, o que na minha opinião faria mais sentido, até para poder fazer essa troca do nome da caixa de entrada. Espero que isso mude futuramente, inclusive quando eu tiver mais tempo livre verei o código fonte pra ver se consigo fazer essa colaboração ou não.

Talvez haja um motivo específico de ser pelo nome ao invés de pelo id, mas isso não sei.

E sobre a URL do webhook isso vai depender de como você configurou o `env.yml` na sua aplicação e qual o nome você deu na hora da criação da instância. Se por exemplo vc quisesse colocar https ao invés de http e queria colocar num domínio/ip:porta diferente, para isso basta você alterar as primeiras linhas no arquivo env relacionada à estas questões.

**Comment by coffeverton** [comment]
Olá, estou enfrentando exatamente esse mesmo problema sobre a URL do webhook.
@eduardochaves1 você poderia detalhar quais são essas linhas do arquivo env que precisam ser ajustadas? Eu alterei a variável `SERVER_URL` informando a url externa, mas os webhooks estão sendo criados com a url localhost:8080.

**Comment by coffeverton** [comment]
> Olá, estou enfrentando exatamente esse mesmo problema sobre a URL do webhook. @eduardochaves1 você poderia detalhar quais são essas linhas do arquivo env que precisam ser ajustadas? Eu alterei a variável `SERVER_URL` informando a url externa, mas os webhooks estão sendo criados com a url localhost:8080.

Pode ignorar, o problema aparentemente era que eu precisava excluir e recriar a caixa de entrada.
Respondendo a minha própria pergunta, aparentemente só precisava definir a SERVER_URL mesmo.
