### ISSUE TITLE
EVOLUTION API NÃO CRIA INSTÂNCIA

### ISSUE THREAD

**Issue by ildo19** [EvolutionAPI/evolution-api#136]
alguem sabe como voltar para a versão anterior? a versão atual, não esta criando as instãncias, da failed ou error na hora de criar instâncias. alguèm sabe como voltar a versão enterior?

**Comment by DavidsonGomes** [comment]
Para tentar ajudar, preciso dos logs ou mensagem de erro para uma analise

**Comment by DavidsonGomes** [comment]
Topico ja criado #138
