### ISSUE TITLE
ERRO AO CRIAR INSTÂNCIA 1.5.2

### ISSUE THREAD

**Issue by ildo19** [EvolutionAPI/evolution-api#138]
NÃO CRIA INSTÂNCIA , DA ERRO NA HORA DE CRIAR.

**Comment by DavidsonGomes** [comment]
Opa, tudo bem? preciso dos logs ou mensagem de erro que ocorre

**Comment by ildo19** [comment]
Este é o erro que ele me dá quando crio uma instância através do manager: Error create estance. Tento reiniciar ou atualizar e ele me dá erro : error restart.

**Comment by DavidsonGomes** [comment]
Preciso de prints, logs, mensagem de erro da requisição, sem ver nada não consigo ajudar

**Comment by ildo19** [comment]
> Preciso de prints, logs, mensagem de erro da requisição, sem ver nada não consigo ajudar

estendi, porém, como que habilito para ver estes erros?

**Comment by ildo19** [comment]
{
    "responseMeta": {
        "status": 200,
        "success": true
    },
    "data": {
        "statusCode": "401 UNAUTHORIZED",
        "headers": {
            "Server": [
                "nginx/1.18.0 (Ubuntu)"
            ],
            "Date": [
                "Sun, 01 Oct 2023 00:09:57 GMT"
            ],
            "Content-Type": [
                "application/json; charset=utf-8"
            ],
            "Content-Length": [
                "75"
            ],
            "Connection": [
                "keep-alive"
            ],
            "X-Powered-By": [
                "Express"
            ],
            "Vary": [
                "Origin, Accept-Encoding"
            ],
            "Access-Control-Allow-Credentials": [
                "true"
            ],
            "ETag": [
                "W/\"4b-/cax6Lc/qf7t4ufEf8qFabwljtA\""
            ],
            "X-APPSMITH-DATATYPE": [
                "JSON"
            ]
        },
        "body": {
            "status": 401,
            "error": "Unauthorized",
            "response": {
                "message": "Unauthorized"
            }
        },
        "isExecutionSuccess": false,
        "messages": [],
        "dataTypes": [
            {
                "dataType": "JSON"
            },
            {
                "dataType": "RAW"
            }
        ]
    },
    "errorDisplay": ""
}

**Comment by ildo19** [comment]
este é o erro que apresenta

**Comment by DavidsonGomes** [comment]
Erro 401 quer dizer que a api key esta incorreta

**Comment by sergioodesigner** [comment]
está dando esse erro quando tento criar instancia no evoluiton 

{ "status": 500, "error": "Internal Server Error", "response": { "message": [ "MongoTopologyClosedError: Topology is closed" ] } }

Alguém me ajuda a corrigir
