### ISSUE TITLE
Algumas mensagens estão se perdendo e não chegam no chatwoot nem na API - Versao acima da 1.5.0

### ISSUE THREAD

**Issue by matheusfterra** [EvolutionAPI/evolution-api#140]
Olá pessoal,

fiz a atualização para V1.5.2 e tudo estava funcionando perfeitamente. Tenho a integração com o chatwoot, e estava funcionando, recebendo e enviando mensagens.

Porém com o passar do tempo, notei que algumas mensagens simplesmente não chegavam no chatwoot. É como se elas se perdessem no caminho.

Nada na configuração foi alterada, e a maioria das mensagens chegam  ( e eu consigo respondê-las).

Instalei o rabbitMQ para ver se evitava a perda de mensagens, mas continuou ocorrendo. Alguém passou por isso?

**Comment by ildo19** [comment]
Tá criando as instância normalmente pelo manager? Se sim, me diga como que vc instalou ele

**Comment by yagoylc** [comment]
Creio que voce esteja passando pelo mesmo problema que eu.

https://github.com/EvolutionAPI/evolution-api/issues/135

**Comment by matheusfterra** [comment]
Bom dia galera, meu erro persiste.

Habilitei  o RabbitMQ e tbm o webhook para verificar se as mensagens que nao chegam no chatwoot, estão chegando na fila ou no webhook, e não estão. É como se elas simplesmente não existissem.

Habilitei o webhook de erros tbm e nada aparece.

Nos logs do console, aparecem informações dos contatos que enviaram as mensagens que não chegam....

Também acontece com vocês?

**Comment by matheusfterra** [comment]
Na versão 1.5.3 ocorre bem menos, mas ainda algumas mensagens simplesmente não são registradas na API. É como se elas não chegassem na Evolution (consequentemente também nao chegam ao chatwoot).

Vi que o Davidson melhorou o processo de restart da API ( e coincidentemente esse comportamento diminuiu consideravelmente)

Meu palpite é que a api restarta e as mensagens se perdem nesse meio tempo (porem nos logs nao aparece nenhum sinal de restart).

Alguem passando por algo semelhante?

**Comment by jaison-x** [comment]
Pelo que vejo a minha também está perdendo mensagens, principalmente mensagens de grupos. Simplesmente algumas mensagens não chegam e não aparece nenhum erro nos logs.

**Comment by matheusfterra** [comment]
Exatamente o mesmo cenário,  principalmente mensagens de grupos (mensagens privadas também) e sem log de erros

**Comment by jayveloper** [comment]
Observamos este comportamento principalmente nas mensagens trocadas em grupos... Não conseguimos nem mesmo gerar log do sinal de recebimento da mensagem pela api, é como se não existissem.

**Comment by jaison-x** [comment]
Só para clarear um pouco mais, encontrei erros que acho que estão sendo enviados pela baileys. Acredito que o problema seja direto nela.

Vocês conseguem verificar se pode ser o mesmo caso de vocês? Segue um exemplo do que aparece aqui. O padrão parece ser a primeira mensagem de grupo, depois de um tempo de inatividade no grupo.

{"level":50,"time":1697466276886,"pid":6946,"hostname":"","key":{"remoteJid":"status@broadcast","fromMe":false,"id":"5A058124CE818DA4302FDE03C77A4F03","participant":""},"err":{"type":"Error","message":"No session found to decrypt message","stack":"Error: No session found to decrypt message\n    at status@broadcast::0 [as awaitable] (/home/chatwoot/evolution-api/node_modules/@whiskeysockets/baileys/WASignalGroup/group_cipher.js:54:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async _asyncQueueExecutor (/home/chatwoot/evolution-api/node_modules/@whiskeysockets/baileys/WASignalGroup/queue_job.js:20:29)"},"msg":"failed to decrypt message"}

**Comment by yagoylc** [comment]
> Só para clarear um pouco mais, encontrei erros que acho que estão sendo enviados pela baileys. Acredito que o problema seja direto nela.
> 
> Vocês conseguem verificar se pode ser o mesmo caso de vocês? Segue um exemplo do que aparece aqui. O padrão parece ser a primeira mensagem de grupo, depois de um tempo de inatividade no grupo.
> 
> {"level":50,"time":1697466276886,"pid":6946,"hostname":"","key":{"remoteJid":"status@broadcast","fromMe":false,"id":"5A058124CE818DA4302FDE03C77A4F03","participant":""},"err":{"type":"Error","message":"No session found to decrypt message","stack":"Error: No session found to decrypt message\n at status@broadcast::0 [as awaitable] (/home/chatwoot/evolution-api/node_modules/@whiskeysockets/baileys/WASignalGroup/group_cipher.js:54:15)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async _asyncQueueExecutor (/home/chatwoot/evolution-api/node_modules/@whiskeysockets/baileys/WASignalGroup/queue_job.js:20:29)"},"msg":"failed to decrypt message"}

Exatamente o que eu passei no log do issue: 
https://github.com/EvolutionAPI/evolution-api/issues/135

Creio que a adição de informação e unificação de issues seria o ideal. Em pesquisas, notei que pessoas abriram issue na baileys também com esse erro, mas por outro lado, aplicações como o whaticket que estão usando a baileys direto, não está recebendo esse erro (de sumiço de mensagens). Não por enquanto. É um caso a ser estudado.

**Comment by alexmsaraiva1** [comment]
Também estou passando pela mesma situação algumas mensagens não são recebidas no Chatwoot, usando Chatwoot 3.1.1 e Evo 1.5.4

**Comment by muriloorama** [comment]
Estou na mesma situação algumas mensagens não são recebidas no Chatwoot, usando Chatwoot 3.1.1 e Evo 1.5.4

**Comment by gabriel-quina** [comment]
Mesmo problema aqui
Chatwoot v3.2.0 Evo 1.5.4

**Comment by luizdevoper** [comment]
Estou na mesma situação algumas mensagens não são recebidas no Chatwoot e algumas mensagens enviadas pelo ChatWoot não chegam no grupo

**Comment by luizdevoper** [comment]
> Só para clarear um pouco mais, encontrei erros que acho que estão sendo enviados pela baileys. Acredito que o problema seja direto nela.
> 
> Vocês conseguem verificar se pode ser o mesmo caso de vocês? Segue um exemplo do que aparece aqui. O padrão parece ser a primeira mensagem de grupo, depois de um tempo de inatividade no grupo.
> 
> `{"level":50,"time":1697466276886,"pid":6946,"hostname":"","key":{"remoteJid":"status@broadcast","fromMe":false,"id":"5A058124CE818DA4302FDE03C77A4F03","participant":""},"err":{"type":"Error","message":"No session found to decrypt message","stack":"Error: No session found to decrypt message\n at status@broadcast::0 [as awaitable] (/home/chatwoot/evolution-api/node_modules/@whiskeysockets/baileys/WASignalGroup/group_cipher.js:54:15)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async _asyncQueueExecutor (/home/chatwoot/evolution-api/node_modules/@whiskeysockets/baileys/WASignalGroup/queue_job.js:20:29)"},"msg":"failed to decrypt message"}`

Será que é possível identificar se a mensagem deu erro e fazer um reenvio?

**Comment by dfares1987** [comment]
boa tarde estou na versao 1.5.4 a mensagem chega no chatwood porem nao vai para a caixa de entrada fica "presa" no chat do contato porem ano vai para a caixa de entrada e qnd pesquisa o cliente a msg esta la presa

**Comment by VonJdamian** [comment]
Mesmo problema. Quando muitas mensagens são recebidas simultaneamente algumas não chegam, quando verifico o log do pm2 vejo que a mensagem nunca chegou.

![image](https://github.com/EvolutionAPI/evolution-api/assets/142674805/791f82f4-5240-42b7-83b8-9b9351ef7813)
![image](https://github.com/EvolutionAPI/evolution-api/assets/142674805/71952ded-2835-415d-b8f1-195d247dc93d)

**Comment by gabriel-quina** [comment]
Rapaz ta complicado. Não é só com muitas mensagens não
Recebi 3 mensagens e só a ultima chegou. A conversa estava parada desde então

> Mesmo problema. Quando muitas mensagens são recebidas simultaneamente algumas não chegam, quando verifico o log do pm2 vejo que a mensagem nunca chegou.
> 
> ![image](https://user-images.githubusercontent.com/142674805/278146686-791f82f4-5240-42b7-83b8-9b9351ef7813.png) ![image](https://user-images.githubusercontent.com/142674805/278146796-71952ded-2835-415d-b8f1-195d247dc93d.png)

Rapaz ta complicado. Não é só com muitas mensagens não
Recebi 3 mensagens e só a ultima chegou. A conversa estava parada desde então

**Comment by jaison-x** [comment]
Este problema acontece por causa desta linha de código. Pelo que vi, ela serve para tratar um novo formato de mensagem lid que o WhatsApp está criando mas não entendo bem sobre isso.

Comentando esta linha vai receber normalmente todas as mensagens. Já estou testando essa solução faz alguns dias e parece estar tudo OK. Agora não sei se ela pode gerar algum outro tipo de problema. No meu caso de uso não gerou. Seria legal alguém com mais experiência analisar sobre.

Arquivo: `evolution-api\src\whatsapp\services\whatsapp.service.ts` Linha: `1651`

![image](https://github.com/EvolutionAPI/evolution-api/assets/5599142/f4911cea-7127-4c73-9838-c3dbd51aafc2)

**Comment by gabriel-quina** [comment]
> Este problema acontece por causa desta linha de código. Pelo que vi, ela serve para tratar um novo formato de mensagem lid que o WhatsApp está criando mas não entendo bem sobre isso.
> 
> Comentando esta linha vai receber normalmente todas as mensagens. Já estou testando essa solução faz alguns dias e parece estar tudo OK. Agora não sei se ela pode gerar algum outro tipo de problema. No meu caso de uso não gerou. Seria legal alguém com mais experiência analisar sobre.

Vou fazer um teste amanhã. Deixar rodando aqui na empresa e retorno com os resultados

**Comment by gabriel-quina** [comment]
Alteração feita. Sem sucesso
Ainda estou sem receber algumas mensagens e agora também não recebi algumas fotos

**Comment by marcio-andrade** [comment]
> Este problema acontece por causa desta linha de código. Pelo que vi, ela serve para tratar um novo formato de mensagem lid que o WhatsApp está criando mas não entendo bem sobre isso.
> 
> Comentando esta linha vai receber normalmente todas as mensagens. Já estou testando essa solução faz alguns dias e parece estar tudo OK. Agora não sei se ela pode gerar algum outro tipo de problema. No meu caso de uso não gerou. Seria legal alguém com mais experiência analisar sobre.
> 
> Arquivo: `evolution-api\src\whatsapp\services\whatsapp.service.ts` Linha: `1651`
> 
> `//received.message.senderKeyDistributionMessage ||`
> 
> ![image](https://user-images.githubusercontent.com/5599142/278825792-f4911cea-7127-4c73-9838-c3dbd51aafc2.png)

Seu teste contina promisso?

**Comment by executivotelemed** [comment]
alguma novidade? estou com mesmo problema, monitoro algumas conversa de grupos para pegar URL e vejo que algumas mensagens nunca chegam de determinado grupo

**Comment by matheusfterra** [comment]
Olá @DavidsonGomes tudo na paz? Cara, você conseguiu identificar a causa desse problema? Sei que deve ter outras prioridades, mas pergunto só pra poder ter visibilidade, porque ainda não pude sair da versão 1.5.0 por conta disso, e alguns bugs da 1.5.0 (inclusive que ja foram solucionadas em versões posteriores) tem impedido de liberar para o cliente.

Agradeço demais o apoio e parabéns pelo trabalho fantástico que tem feito com a Evolution. Abraços!

**Comment by MattCarneiro** [comment]
> Olá @DavidsonGomes tudo na paz? Cara, você conseguiu identificar a causa desse problema? Sei que deve ter outras prioridades, mas pergunto só pra poder ter visibilidade, porque ainda não pude sair da versão 1.5.0 por conta disso, e alguns bugs da 1.5.0 (inclusive que ja foram solucionadas em versões posteriores) tem impedido de liberar para o cliente.
> 
> Agradeço demais o apoio e parabéns pelo trabalho fantástico que tem feito com a Evolution. Abraços!

A versão 1.5.0 está sem esse bug?
Quais os bugs dessa versão que não tem agora?
Estou analisando voltar para a 1.5.0 se não tiver esse bug, já que estou tentando montar um serviço de mensagens e algumas simplesmente não chegam mesmo. Pra mim compensaria voltar, dependendo dos bugs que ainda existem nessa versão

**Comment by luiztonucci** [comment]
@DavidsonGomes, boa tarde, parabéns pelo seu trabalho. Informando que a v.1.5.4 ainda continua perdendo mensagens. Vi que o pessoal está comentando das versões 1.5.1, 1.5.2, 1.5.3 tbm com o mesmo problema. Infelizmente voltei para a v.1.5.0 para não ter mais problema. Quando puder por favor dar uma atenção para esse problema, sendo que é primordial não perder mensagens. Abraço.

**Comment by luizdevoper** [comment]
> @DavidsonGomes, boa tarde, parabéns pelo seu trabalho. Informando que a v.1.5.4 ainda continua perdendo mensagens. Vi que o pessoal está comentando das versões 1.5.1, 1.5.2, 1.5.3 tbm com o mesmo problema. Infelizmente voltei para a v.1.5.0 para não ter mais problema. As versões mais recente da EVO está mais integrada outros sistemas (typebot, n8n, entre outros), então voltando para a v.1.5.0, perdemos integrações importantes. Quando puder por favor dar uma atenção para esse problema, sendo que é primordial não perder mensagens ao receber e enviar. Abraço.

Como está seu teste na versão 1.5.0? Está estável?

**Comment by luiztonucci** [comment]
@luizdevoper, bom dia! Vi a issue **#223** que você postou. Entendo um pouco de programação, mas esse nicho de API de mensagem ainda é uma descoberta pra mim e estou aprendendo ainda. Se eu conseguir fazer essa alteração e testar, aviso você. Estou com um container montando uma pequena  solução de atendimento para a empresa que trabalho usado minio + type + evo + chatwoot. Meus testes em receber e enviar com a 1.5.0 está bem estável. Tem 2 dias, sei que é um período curto, mas não perdi msg. Infelizmente todas as **fixed** e **changes** após a 1.5.0 não temos. Estava montando um esquema no typebot, mas já era devido a essa fixed **( Chatwoot now receives messages sent via api and typebot ),** terei que pensar em uma solução. Enfim, por hora é isso. Ainda estou em teste pra ver se é isso mesmo e vou rodar em breve.

**Comment by DavidsonGomes** [comment]
Ja estamos ciente da questão, esse é um problema da lib Baileys, estamos estudando uma forma de melhorar isso

**Comment by AnxHall** [comment]
Mesmo problema aqui
Chatwoot v3.5.2(Enterprise SelfHosted) + Evo 1.6.1

Esse erro volta acontecer aqui nessa versão, mensagens aleatoriamente somem e se quer constam em algum erro de log, tentarei analisar a “lib” que deu erro anteriormente e aguardo possíveis soluções.

OBS:
constatei também um erro de time out para API, mas e corrigido em "{sua instância chatwoot}/lib/webhooks#25" (timeout 5>20)

**Comment by ailsoncgt** [comment]
@DavidsonGomes , só para entender mesmo. Pq a issue foi fechada se aparentemente não tem uma solução/não foi resolvida ? Tem alguma outra issue relatando o mesmo problema que a gente possa acompanhar a evolução ?

**Comment by hiagodeoliveiratv** [comment]
Boa tarde, foi resolvido? Mesmo problema aqui

**Comment by muriloorama** [comment]
> Boa tarde, foi resolvido? Mesmo problema aqui

Sim foi corrigido, atualize para versão 1.7.4

**Comment by andercrist** [comment]
Boa tarde, estou tendo problemas de algumas mensagens não chegarem na versão v2.2.0.

**Comment by AvicSistemas** [comment]
Bom dia!
Estou acompanhando a bastante tempo o trabalho da Evolution, e realmente é sensacional o que tem sido realizado.

Estamos usando a Api v:2.2.0 em um primeiro momento em um ambiente nosso para atendimento ao cliente, usando o Chatwoot como ferramenta de chat.

Temos sempre acompanhado as mensagens **recebidas** e não tem ocorrido perda de mensagem,  mas as mensagens enviadas tem ocorrido perda quando o intervalo entre as mensagens é menor que 10 segundos.

Se enviar a primeira mensagem e na sequência enviar outras em que o intervalo de envio for menor que 10 segundos, a segunda mensagem não é enviada. 
No Chatwoot tem o log do registro da conversa mas ela não chega na evolution api.

Se as mensagens forem enviadas com um intervalo maior que 10 segundos, elas chegam na evolution Api e são entregues ao destino normalmente.

**Comment by tech3br** [comment]
> Bom dia! Estou acompanhando a bastante tempo o trabalho da Evolution, e realmente é sensacional o que tem sido realizado.
> 
> Estamos usando a Api v:2.2.0 em um primeiro momento em um ambiente nosso para atendimento ao cliente, usando o Chatwoot como ferramenta de chat.
> 
> Temos sempre acompanhado as mensagens **recebidas** e não tem ocorrido perda de mensagem, mas as mensagens enviadas tem ocorrido perda quando o intervalo entre as mensagens é menor que 10 segundos.
> 
> Se enviar a primeira mensagem e na sequência enviar outras em que o intervalo de envio for menor que 10 segundos, a segunda mensagem não é enviada. No Chatwoot tem o log do registro da conversa mas ela não chega na evolution api.
> 
> Se as mensagens forem enviadas com um intervalo maior que 10 segundos, elas chegam na evolution Api e são entregues ao destino normalmente.

Alguma resolução para isso? Conseguiu resolver amigo?

**Comment by VittorPatricio** [comment]
Estou com um problema ao utilizar o chatwoot junto da evolution, minhas mensagens simplesmente somem após reiniciar a página, e não voltam a aparecer posteriormente, alguém já passou por isso?

Versão chatwoot: v4.0.1
Evolution: v2.2.3

**Comment by AvicSistemas** [comment]
> > Bom dia! Estou acompanhando a bastante tempo o trabalho da Evolution, e realmente é sensacional o que tem sido realizado.
> > Estamos usando a Api v:2.2.0 em um primeiro momento em um ambiente nosso para atendimento ao cliente, usando o Chatwoot como ferramenta de chat.
> > Temos sempre acompanhado as mensagens **recebidas** e não tem ocorrido perda de mensagem, mas as mensagens enviadas tem ocorrido perda quando o intervalo entre as mensagens é menor que 10 segundos.
> > Se enviar a primeira mensagem e na sequência enviar outras em que o intervalo de envio for menor que 10 segundos, a segunda mensagem não é enviada. No Chatwoot tem o log do registro da conversa mas ela não chega na evolution api.
> > Se as mensagens forem enviadas com um intervalo maior que 10 segundos, elas chegam na evolution Api e são entregues ao destino normalmente.
> 
> Alguma resolução para isso? Conseguiu resolver amigo?

Nós estamos usando uma VPS para o Banco de Dados e outra para as aplicações (Chatwoot, Evolution e outros).
Este problema foi resolvido quando reiniciei a VPS do Banco de dados.
Chegamos a reiniciar a VPS das aplicações, porem não resolveu o problema!

Se a sua aplicação e o banco de dados estiverem na mesma VPS, já resolveria também

**Comment by Tommendes** [comment]
Olá a todos. Continuamos perdendo mensagens. Aqui Evo 2.2.3 e CW 4.0.2 e outra Evo 2.2.1 e CW 4.0.1. Todas perdendo mensagens. Perdas principalmente se forem anexos como áudio, imagens e arquivos. Alguma solução dos devs?

**Comment by mcorreaedu** [comment]
Boa tarde! Aqui Evo 2.2.3 e CW testado nas versões V3.16 pra cima. Mesma coisa, porém as mensagens estão indo para o histórico de mensagens dos contatos e, mesmo sendo atribuídas automaticamente, não aparecem na caixa de entrada... Alguém com alguma solução ou workaround?

**Comment by icarocha** [comment]
Também com o mesmo problema Evo 2.2.3 e chatwoot v3.15

**Comment by help-corretora** [comment]
Fiz a burrada de mexer com quem estava quieto e agora ficou terrível, esse problema voltou e pra resolver tá um parto, tô usando a versão 4.0.1 do CW, tá osso.
