### ISSUE TITLE
Como atualizar versão

### ISSUE THREAD

**Issue by dualtecms** [EvolutionAPI/evolution-api#142]
Olá galera, grato pelo projeto é muito útil, e pe uma ótima referência nacional. Estou procurando uma forma correta para fazermos o update sem precisar desinstalar e instalar novamente.

**Comment by Nilbertocs** [comment]
Segue documentação oficial para atualização:

[Via NPM](https://doc.evolution-api.com/help-center/articles/9/npm-installation#updating-the-evolution-api)
[Via Docker](https://doc.evolution-api.com/help-center/articles/1/7/66/docker-installation#updating-the-evolution-api)

**Comment by DavidsonGomes** [comment]
Duvida respondida

**Comment by grupale** [comment]
Hi @DavidsonGomes! I'm looking for the update procedure of evolution-api an this link is no longer available

https://doc.evolution-api.com/help-center/articles/9/npm-installation#updating-the-evolution-api

Where should I take a look to now how to correctly update evolution api without loosing any instance and logged sessions? Thanks

**Comment by coffeverton** [comment]
> Hi @DavidsonGomes! I'm looking for the update procedure of evolution-api an this link is no longer available
> 
> https://doc.evolution-api.com/help-center/articles/9/npm-installation#updating-the-evolution-api
> 
> Where should I take a look to now how to correctly update evolution api without loosing any instance and logged sessions? Thanks

here: https://doc.evolution-api.com/docs/update
