### ISSUE TITLE
Envio de PDF com problemas 1.5.2

### ISSUE THREAD

**Issue by jeffsystem** [EvolutionAPI/evolution-api#146]
![Screenshot_20231001_123302_WhatsApp](https://github.com/EvolutionAPI/evolution-api/assets/39931647/64db37b6-cb2a-41e2-9cbd-c9fce245a609)

Pdf com problemas, versão 1.5.1 funcionando normal com mesmo código.

**Comment by DavidsonGomes** [comment]
Resolvida na 1.5.3
