### ISSUE TITLE
The end user does not receive images Whatsapp & Chatwoot

### ISSUE THREAD

**Issue by vonneumann23** [EvolutionAPI/evolution-api#152]
The end user is not receiving the images sent from chatwoot.

![image](https://github.com/EvolutionAPI/evolution-api/assets/146461599/31ad099b-395c-4b33-b8aa-f7b175e824d5)
![WhatsApp Image 2023-10-02 at 09 00 41](https://github.com/EvolutionAPI/evolution-api/assets/146461599/3e0624a4-c7e9-4139-b934-30cf1a0aa0ad)

Evolution Api 1.5.2 
Ubuntu 22.04 + Nginx
Chatwoot 3.1.0
Outra informação
No Whatsapp web você consegue ver a imagem, mas no aplicativo Mobile (androri/ios) você não vê a imagem.

**Comment by MattCarneiro** [comment]
Aconteceu comigo. Pelo que apurei, se a imagem que você envia por API tem final ".png ou .jpeg ou .jpg" você visualiza nos dois. Se não tem final, você visualiza apenas no WhatsApp Web
