### ISSUE TITLE
Mensagens de fora do chatwoot abre conversa.

### ISSUE THREAD

**Issue by Thander21** [EvolutionAPI/evolution-api#158]
Não existe nenhuma configuração para desativar que o chatwoot faça leitura de mensagens enviadas fora do chatwoot, pois mensagens automaticas enviadas direto pela api ou msg enviadas no chatwoot então criando chamados no chatwoot., impossibilitando o uso do mesmo numero para envio de informações, cobranças, noticias e outros assuntos que não requerem a abertura da conversa no chatwoot.

**Comment by matheusfterra** [comment]
Bom ponto, também gostaria de saber

**Comment by DavidsonGomes** [comment]
Não, se esta conectado ele vai manter a sincronia de tudo

**Comment by Lucasendlichgomes** [comment]
<img width="1092" height="783" alt="Image" src="https://github.com/user-attachments/assets/671a313e-e754-4704-a846-ffdd0ceb84ff" />

<img width="1227" height="373" alt="Image" src="https://github.com/user-attachments/assets/6284c26c-e129-4a95-b300-ed6ffecf9ff9" />

to Com problema contrario , as msg de fora não estão aparecendo,quando é enviado fora da api , estou na versao 2.3.7

**Comment by Lucasendlichgomes** [comment]
<img width="709" height="389" alt="Image" src="https://github.com/user-attachments/assets/cb063e4e-99a4-437b-af3c-7ef92342c5f6" />

[Evolution API]    v2.3.7  163   -  Wed Dec 10 2025 18:07:11     INFO   [ChatwootService]  [string]  [send.message] New message received - Instance: {

@DavidsonGomes  esta dand oesse erro quando a mensagem é enviada  "fromMe": true,
