### ISSUE TITLE
Imagem .jpg .png ou .gif não são enviados pelo Chatwoot, com a EVO 1.5.2

### ISSUE THREAD

**Issue by matheusfterra** [EvolutionAPI/evolution-api#159]
Olá pessoal, estou usando a versão 1.5.2 e estou tentando fazer envio de imagens pelo chatwoot (3.1.1). Imagens .jpg, .png ou .gif não estão sendo enviadas para o Whatsapp.

Mais alguem com esse problema?

**Comment by vonneumann23** [comment]
#152 Eu tenho o mesmo problema

**Comment by regueir0** [comment]
Aqui estou com dificuldade de envio de video / imagem tbm, ja fiz de tudo ate recriar instancias, rebootar servidor.. deletar caixa de msg e etc...

**Comment by regueir0** [comment]
Outro erro tbm é que nao mostra msg de que o qrcode foi lido com sucesso, a gente kle e pronto ele so nao gera masi, ai cliente nao sabe se leu ou nao..

**Comment by regueir0** [comment]
Voltei aqui pra versao 1.5.1 porem problema dela é que o manager fica travado enquando nao se le o qrcode de uma nova instancia fora isso, tudo ok ! aguardando correção para 1.5.3

**Comment by EliveltonSantiago** [comment]
Alguém conseguiu resolver esse problema?

**Comment by kiko123456** [comment]
Alguma solucao Galera PLiss ? pago pelo seu tempo

**Comment by facilrapido** [comment]
como resolver isso onde esta o problema so instalei o chatwoor e evolution será falta de configurar um storage ?

**Comment by meumouse** [comment]
SOLUÇÃO DO PROBLEMA:

Adicionar as variaveis de ambiente:

RAILS_ENV=production
FRONTEND_URL=https://url-do-chatwoot.com.br
ASSET_CDN_HOST=https://url-do-chatwoot.com.br

**Comment by RogerDLima** [comment]
AS envs de rails frontend  já estavam somente a sset_cdn que nao, mas ela nao ajudou.

**Comment by ricbn** [comment]
Aqui eu estou com erro quando contato envia primeira msg uma imagem..
Se ele já estiver conversando e enviar a img chega
