### ISSUE TITLE
Mensagem duplicada no ChatWoot v1.5.3

### ISSUE THREAD

**Issue by xNkee** [EvolutionAPI/evolution-api#165]
Prezados,

Quando enviamos a mensagem pelo ChatWoot ao chegar no WhatsApp, ela é duplicada mas somente na plataforma do ChatWoot.
Entrega corretamente no WhatsApp. Segue os prints:

Print ChatWoot
![image](https://github.com/EvolutionAPI/evolution-api/assets/133472902/3c29d093-5a50-4d07-ac12-f89760bfda20)

Print WhatsApp
![image](https://github.com/EvolutionAPI/evolution-api/assets/133472902/5e642845-97ca-48f1-943e-dd19063f5189)

**Comment by raphagamendes** [comment]
Estou com o mesmo problema.

**Comment by jaison-x** [comment]
Mesmo problema aqui também. Solução paliativa está no arquivo `src/whatsapp/services/chatwoot.service.ts` linha 1282. Reverter para `if (event === 'messages.upsert' || event === 'send.messages') {` mas isso deve gerar problema com a integração do typebot para quem usa.

**Comment by matheusfterra** [comment]
Idem por aqui.

**Comment by DavidsonGomes** [comment]
Estamos analisando a situação

**Comment by figueredofx** [comment]
Aqui  mesma coisa

**Comment by DavidsonGomes** [comment]
Problema resolvido na v1.5.4
