### ISSUE TITLE
MANAGER INSTANCIAS - Lei LGPD - *** VAZAMENTO DE INFORMAÇÕES

### ISSUE THREAD

**Issue by aarctb** [EvolutionAPI/evolution-api#168]
Gostaria de entender porque o gerenciador de instancias é um site externo que abre no IFRAME e pede a url da API e o token global

Será que é para ter acessos as instancias, contatos, chats, etc....  das pessoas que usam 🤔🤔🤔 

Lei LGPD vazamento de informações é crime.

**Comment by MattCarneiro** [comment]
Amigo, você não pode chegar aqui sem conhecer o projeto e levantar hipóteses fazendo acusações. Tá parecendo algum dono de API de WhatsApp que está desesperado porque fizeram um projeto open source que é bem melhor que qualquer API paga do mercado. Se você está incomodado, é só não usar e pagar $$ outras APIs por aí.

**Comment by aarctb** [comment]
@MattCarneiro não estou levantando hipóteses e nem fazendo acusações, o que estou falando é fato, está no código.

Por que será que só esse gerenciando é externo e precisa do url e token de acesso da API?

Ué, poe o código fonte do gerenciador ai no repositório, é simples e assunto encerrado.

Só estou relando algo que ná hora da "autenticação" o criador não está avisando quem utiliza essa API, não estou fazendo nada de errado meu Amigo.

**Comment by DavidsonGomes** [comment]
O site é meramente um frontend onde armazena seus dados via cookie no navegador, o site não roda localmente pois usa o AppSmith para isso, não tem nem 1 dado se quer sendo armazenado em lugar nenhum a nao ser em seu proprio navegador, disponibilizamos o json do appsmith para voce mesmo fazer sua instalação do painel! Não acuse sem saber!!

**Comment by aarctb** [comment]
Não estou acusando ninguém @DavidsonGomes , o que estou dizendo que por ser externo pode sim ter acesso.

Se puder disponibilizar o json enão a comunidade agradece.

Obrigado.

**Comment by DavidsonGomes** [comment]
Esta no repositorio na pasta extras
