### ISSUE TITLE
Bad request - No Session

### ISSUE THREAD

**Issue by DRIMOL** [EvolutionAPI/evolution-api#17]
hoje fiz uma instalação limpa como recomendado, fiz igual ao manual, escaneei 4 chips para testar dia 22/07 em volta de 15:00

estavam todos funcionando perfeitamente

No mesmo dia as 18:50 tornei a testar envio e recebimento de mensagem e em três dessas conexões estão estão chegando 3 webhooks![image](https://github.com/EvolutionAPI/evolution-api/assets/47779716/9fa1d508-829d-4fd6-9b02-842e23ecba8a) com mensagem vazia, e depois chega o correto.

uma dessas três está com NO SESSION, recebe, mas, não está enviando.![image](https://github.com/EvolutionAPI/evolution-api/assets/47779716/d439e085-afb3-4786-996a-7c5b584971ce)

**Comment by DavidsonGomes** [comment]
Erro de No Session é da propria Baileys, ate o momento a unica forma de solucionar é reiniando o processo, seja pm2 ou container

**Comment by lindenbergp** [comment]
Estou enfrentando o mesmo problema ao enviar em alguns grupos.

log pm2:
0|ApiEvolu | SessionError: No sessions
0|ApiEvolu |     at Object.558897094341:42.0 [as awaitable] (/home/evolution-api/node_modules/libsignal/src/session_cipher.js:71:23)
0|ApiEvolu |     at async _asyncQueueExecutor (/home/evolution-api/node_modules/libsignal/src/queue_job.js:20:29)
0|ApiEvolu |

**Comment by eduardochaves1** [comment]
![image](https://github.com/user-attachments/assets/842ef2fc-3d6a-4fbd-8ba7-e6727ef27bc8)

Eu percebi que quando dá o erro de No Sessions na instância, esses documentos aparecem no registro dessa instância do mongo. Simplesmente removê-los não resolve, pois voltam a aparecer.

**Comment by eduardochaves1** [comment]
Uma dúvida, vocês estão com o redis ativado para salvar instâncias?
