### ISSUE TITLE
Docker Build - v1.5.3 - ARM

### ISSUE THREAD

**Issue by clikalogo** [EvolutionAPI/evolution-api#170]
Olá @DavidsonGomes, erro ao tentar realizar o Build **(arquitetura ARM)** na versão **v1.5.3**.
Nas versões anteriores, build (ARM) normal.

![image](https://github.com/EvolutionAPI/evolution-api/assets/107278009/95b59da8-50ab-4b35-be62-bf0f08eab5a5)

**Comment by DavidsonGomes** [comment]
a imagem docker não tem suporte a arm no momento

**Comment by dualtecms** [comment]
![image](https://github.com/EvolutionAPI/evolution-api/assets/146224665/bf83866b-c034-4cca-92ca-a5dcdea8c3d6)
@DavidsonGomes, estou seguindo o install do site https://doc.evolution-api.com/help-center/articles/9/npm-installation.
Está dando esse erro da 1.5.0 adiante. Já alterei a versão do node para 20.5.3, não estou conseguindo entender porque esses módulos estão dando errado nesse momento

**Comment by dualtecms** [comment]
![image](https://github.com/EvolutionAPI/evolution-api/assets/146224665/f102c54c-4fce-4bf2-ad61-0e68601820d6)

**Comment by dualtecms** [comment]
Resolvido na versão 1.5.4
![image](https://github.com/EvolutionAPI/evolution-api/assets/146224665/b857accb-71f9-427f-961e-28be863c40ea)

**Comment by clikalogo** [comment]
Docker - Build (ARM) normalizado na v1.5.4 !
