### ISSUE TITLE
Esta dando erro ao acessar o /manager ?

### ISSUE THREAD

**Issue by ivanaszko** [EvolutionAPI/evolution-api#171]
ao acessar o manager através de qualquer domínio esta dando o erro no navegador : "A página https://app.smith.dgcode.com.br/app/evolutionapi-public/home-64ca60783615e270291978b4?embed=true pode estar temporariamente indisponível ou pode ter sido movida permanentemente para um novo endereço da Web."

**Comment by vonneumann23** [comment]
![image](https://github.com/EvolutionAPI/evolution-api/assets/146461599/d919f3f4-1f75-49bf-9a90-b676dcb2f5f0)

nano evolution-api/views/manager.hbs
replace whit this temp bk manager: https://app.appsmith.com/app/manager-bk/home-652433fb5012274cbc515724?embed=true

**Comment by DavidsonGomes** [comment]
manager hospedado por nos foi desabilitado por enquanto, pode utilizar o seu proprio manager na sua conta do app smith, so importar o json

https://github.com/EvolutionAPI/evolution-api/blob/main/Extras/appsmith/manager.json
