### ISSUE TITLE
Imagem não aparece no IOS

### ISSUE THREAD

**Issue by MatheusGatti** [EvolutionAPI/evolution-api#172]
O envio de imagem está sendo realizado com sucesso porém ela não aparece no WhatsApp do iPhone (IOS), a mensagem com a imagem aparece somente no WhatsApp Web.

**Comment by DavidsonGomes** [comment]
Qual a versao esta usando?

**Comment by MatheusGatti** [comment]
A versão 1.5.3

Em seg., 9 de out. de 2023 às 21:12, Davidson Gomes <
***@***.***> escreveu:

**Comment by MatheusGatti** [comment]
Atualizei e mesmo assim a mensagem da imagem não aparece no iOS, somente no
WhatsApp Web.

Em seg., 9 de out. de 2023 às 22:38, Usern4me ***@***.***>
escreveu:

**Comment by MateusAbade** [comment]
Estou enfrentando o mesmo problema, outras medias estão enviado normalmente

**Comment by DavidsonGomes** [comment]
Por inatividade essa issue sera fechada, caso necessario reabra!
