### ISSUE TITLE
Bearer Auth

### ISSUE THREAD

**Issue by maaper** [EvolutionAPI/evolution-api#175]
Hi all, can somebody help me to understand where to obtain code for Bearer Auth.

<img width="1235" alt="image" src="https://github.com/EvolutionAPI/evolution-api/assets/56989894/e11cb4f1-850f-4c51-8f87-28ec2452f008">

**Comment by oriondesign2015** [comment]
The "Bearer authentication" is the link to your Evolution API.

Example:
if I installed it with api.oriondesign.art.br

my Bearer authentication is:
https://api.oriondesign.art.br

Hope this helps.

**Comment by maaper** [comment]
Thanks a lot! I will look at it.

**Comment by luispimenta** [comment]
@oriondesign2015 Do you know if anything changed in version 1.7.1?

I'm sending:

Authorization: Bearer https://evolution.meusite.app

and always returns 401

Is it necessary to convert to base64 or something like that?

**Comment by phtisp** [comment]
Por favor, classifique esta conversa, https://apiv2.xphsolution.com.br/survey/responses/46c99194-35fe-4830-94c9-2ef6ef3adaa0
