### ISSUE TITLE
How to stay tuned for new messages

### ISSUE THREAD

**Issue by aluquerivas-dev** [EvolutionAPI/evolution-api#176]
I am looking at the documentation and internal code of evolutionAPI but I am not very clear if this is possible to do, I am implementing a chat manager within my CRM and for this I need that when a certain client enters to be listening in case they are received new messages in a certain chat, I have seen that there is the option to subscribe to the websocket which I have followed the same steps to connect as with other projects that I have used socket.io but I connect to the socket and I am not able to receive any data, At the same time, I don't know if this websocket would be used for what I'm looking for or what methods evolution maintains to do what I want. All the best.

**Comment by DavidsonGomes** [comment]
will be added to the documentation

https://doc.evolution-api.com/docs/01-Get%20Started/optional-resources
