### ISSUE TITLE
Qual o endereço do Manager?

### ISSUE THREAD

**Issue by MattCarneiro** [EvolutionAPI/evolution-api#177]
Aqui está redirecionando para a página principal. Era https://manager.evolution-api.com/

**Comment by matheusmaiberg** [comment]
Vai na pasta Extras aqui dos arquivos da Evolution e baixa o [manager.json](https://github.com/EvolutionAPI/evolution-api/blob/main/Extras/appsmith/manager.json).

Entra no appsmith, cria sua conta com seu Gmail, e importa o projeto pra la, ai clica em deploy.

Pronto você tem seu próprio manager, agora da meu like ai.

Aqui aonde voce importa o arquivo.
![image](https://github.com/EvolutionAPI/evolution-api/assets/119268809/4fd3d0dd-7f86-40e2-9cbe-1144993b2d76)

**Comment by MattCarneiro** [comment]
> O manager foi removido a grande quantidade de requisições sendo feitas por usuários, a alternativa é criar o seu proprio no AppSmith, com o json que esta na pasta extras aqui do repositório.
> 
> Vai na pasta Extras aqui dos arquivos da Evolution e baixa o [manager.json](https://github.com/EvolutionAPI/evolution-api/blob/main/Extras/appsmith/manager.json).
> 
> Entra no appsmith, cria sua conta com seu Gmail, e importa o projeto pra la, ai clica em deploy.
> 
> Pronto você tem seu próprio manager, agora da meu like ai.
> 
> Aqui aonde voce importa o arquivo. ![image](https://user-images.githubusercontent.com/119268809/275101276-4fd3d0dd-7f86-40e2-9cbe-1144993b2d76.png)

Fala Matheus, beleza?
No caso, eu preciso fazer isso com o mesmo manager.json que foi instalado na instância do evolution, né?
Depois de instalado, esse arquivo vai pra onde?

**Comment by matheusmaiberg** [comment]
> Fala Matheus, beleza? No caso, eu preciso fazer isso com o mesmo manager.json que foi instalado na instância do evolution, né? Depois de instalado, esse arquivo vai pra onde?

##Na verdade não

Você só precisa mandar para o appsmith o json, quando clicar em deploy ele vai pedir o endereco e apikey, entao voce tem seu proprio manager e pode conectar em qualquer servidor Evolution, desde que tenha os dados de autenticacao.

**Comment by lucianopiler** [comment]
o arquivo manager json foi removido

**Comment by wesmarcal-go** [comment]
Poxa, o arquivo JSON não existe mais :(

**Comment by maxvanderbiljr** [comment]
Se alguém ainda tiver o arquivo manager.json e puder compartilhar. Estou precisando dele.
