### ISSUE TITLE
As mensagens enviadas via ChatWoot não chegam ao destino

### ISSUE THREAD

**Issue by andresousapro** [EvolutionAPI/evolution-api#178]
Na configuração do endpoint "Create Instance From Chatwoot" ao passar o parâmetro "chatwoot_sign_msg" como "true" o mesmo não funciona.

Ao criar como "false" funciona normalmente.

Efetuei o testes duas vezes.

**Comment by jaison-x** [comment]
Olá Andre. Este parametro somente faz a mensagem ser assinada. Veja se o nome do atendente tem algo que possa interferir nisso. Para mim aqui na versão 1.5.4 está indo normalmente. Fiz um teste hoje a tarde mesmo.

**Comment by andresousapro** [comment]
> Olá Andre. Este parametro somente faz a mensagem ser assinada. Veja se o nome do atendente tem algo que possa interferir nisso. Para mim aqui na versão 1.5.4 está indo normalmente. Fiz um teste hoje a tarde mesmo.

Fiz novamente os testes alterando o nome do atendente e sem sucesso. Porém, setando essa referida configuração, funciona normalmente.

Pode ser que seja erro somente aqui, mas está se comportando dessa maneira.

**Comment by jaison-x** [comment]
> > Olá Andre. Este parametro somente faz a mensagem ser assinada. Veja se o nome do atendente tem algo que possa interferir nisso. Para mim aqui na versão 1.5.4 está indo normalmente. Fiz um teste hoje a tarde mesmo.
> 
> Fiz novamente os testes alterando o nome do atendente e sem sucesso. Porém, setando essa referida configuração, funciona normalmente.
> 
> Pode ser que seja erro somente aqui, mas está se comportando dessa maneira.

Nos logs não aparece nenhum erro?

**Comment by andresousapro** [comment]
> > > Olá Andre. Este parametro somente faz a mensagem ser assinada. Veja se o nome do atendente tem algo que possa interferir nisso. Para mim aqui na versão 1.5.4 está indo normalmente. Fiz um teste hoje a tarde mesmo.
> > 
> > 
> > Fiz novamente os testes alterando o nome do atendente e sem sucesso. Porém, setando essa referida configuração, funciona normalmente.
> > Pode ser que seja erro somente aqui, mas está se comportando dessa maneira.
> 
> Nos logs não aparece nenhum erro?

Consegui resolver com mais detalhes. Graças ao nosso amigo da comunidade Serginho Felix, que descobriu que ao criar a instância, ele criava sem https nas configurações do WooChat. Agora voltou a funcionar com as duas opções com o nome do atendente ou sem!

Obrigado!
