### ISSUE TITLE
A primeira mensagem do grupo via ChatWoot não aparece na conversa

### ISSUE THREAD

**Issue by andresousatech** [EvolutionAPI/evolution-api#179]
Ao enviar mensagem via grupo no ChatWoot, a primeira mensagem não aparece.

Somente a segunda.

Porém, não consegui identificar se é um erro da API ou do ChatWoot.

**Comment by DavidsonGomes** [comment]
Esse é um problema da lib Baileys, ja estamos analisando isso e como podemos resolver
