### ISSUE TITLE
Chatwoot + Evolution com Mongo

### ISSUE THREAD

**Issue by jaison-x** [EvolutionAPI/evolution-api#180]
Estou tendo problemas com a Evolution configurada para utilizar o mongo como database.

Verificando nos logs, percebi que para algumas (a maioria delas no meu caso) mensagens de grupo este erro acontece: MongoServerError: a pipeline stage specification object must contain exactly one field.

![image](https://github.com/EvolutionAPI/evolution-api/assets/5599142/2c6b9985-8ccf-4d5d-bb58-3d6db215d90d)

Alguém já passou por isso? Já tentei utilizar o Redis como database mas tive alguns problemas e preferia manter o Mongo. Alguém poderia ajudar? 

Estou utilizando a Evo 1.5.4 com Mongo 7.0.2.

**Comment by jaison-x** [comment]
Outro coisa que percebi é que este erro não dispara o evento `ERRORS_WEBHOOK`. Deveria ter esse comportamento realmente?

**Comment by DavidsonGomes** [comment]
Estamos validando esse problema com o mongo, obrigado!

**Comment by jaison-x** [comment]
Olá @DavidsonGomes 

Obrigado. Este erro acontece neste arquivo: \chatwoot\evolution-api\src\utils\use-multi-file-auth-state-db.ts na linha 28.

Resolvi de forma temporária com este código mas como não entendo muito bem, provavelmente pode gerar algum problema de inconsistência: 

`try {
      await client.connect();
      const msgParsed = JSON.parse(JSON.stringify(data, BufferJSON.replacer));
      if (msgParsed[0]) {
        return false;
      }
      return await collection.replaceOne({ _id: key }, msgParsed, {
        upsert: true,
      });
    } catch (error) {
      logger.error(error);
    }
`

**Comment by jaison-x** [comment]
@DavidsonGomes 

Criei este PR que acredito que resolve este problema: #224 

Poderia analisar se isso resolve a questão definitivamente?
