### ISSUE TITLE
Chatwoot: Quando CSAT está ativo e reopen desativado, ao resolver uma conversa, é criada uma nova com uma mensagem no Chatwoot

### ISSUE THREAD

**Issue by francisbreit** [EvolutionAPI/evolution-api#181]
Evolution 1.5.4 e ChatWoot 3.1.1. Quando CSAT está ativo e reopen desativado, ao resolver uma conversa, é criada uma nova com uma mensagem no Chatwoot, repetindo a informação:
Por favor, classifique esta conversa. Essa nova conversa criada erroneamente , chega por API. Provavelmente, esse erro surge depois da liberação de espelhamento de mensagens que chegam por API, no Chatwoot. 
![Captura de Tela 2023-10-14 às 15 55 50](https://github.com/EvolutionAPI/evolution-api/assets/5285287/f5cc9eb4-e32b-4d2c-b57d-7328b5731863)

![Captura de Tela 2023-10-14 às 15 56 13](https://github.com/EvolutionAPI/evolution-api/assets/5285287/8c09202a-7847-40e3-a3e7-98b2e0b51ed3)

**Comment by DavidsonGomes** [comment]
Vamos simular a questao para corrigir obrigado

**Comment by DavidsonGomes** [comment]
Problema resolvido na versao 1.6.0

**Comment by tmsdesarrollo3** [comment]
Olá, estou tendo o mesmo problema com a versão 2.2.1.
