### ISSUE TITLE
TYPEBOT + EVOLUTION API

### ISSUE THREAD

**Issue by MarecoX** [EvolutionAPI/evolution-api#183]
Evolution API + Typebot, última versão de ambos, ao criar um bot de atendimento no WhatsApp, o fluxo só está funciona se tiver output + input sucessivamente.

Ou seja, se for criado 2 blocos com mensagem no Typebot, só é enviado 1 no WhatsApp, o outro só irá aparecer se for enviado um input intermediando as 2 mensagens, elas não saem em sequência.

![image](https://github.com/EvolutionAPI/evolution-api/assets/136134660/afcd2a77-5248-48b7-ab9d-4de9c58ad026)

**Comment by data-vini** [comment]
Acho que se você ligar a linha direto na box da mensagem em si, e não no grupo, ele funciona, já ocorreu comigo.

**Comment by suissa** [comment]
Aqui a ordem está indo errada das mensagens de um mesmo grupo, em um bot q tenho tds os textos vem antes, depois images e depois audios. Parece um erro na hora de sequenciar as mensagens pq vi e chegam corretamente na API
