### ISSUE TITLE
Número oculto no WhatsApp Business quando respondem a anúncios.

### ISSUE THREAD

**Issue by VonJdamian** [EvolutionAPI/evolution-api#184]
Tenho um número no WhatsApp Business conectado à API Evolution que contém anúncios, quando um cliente nos escreve através de um anúncio seu número de telefone fica oculto por exemplo: "+51xxxxxxx32" então os chats não estão sendo criados no Chatwoot.

Haverá alguma solução?

![WhatsApp Image 2023-10-17 at 10 11 23 AM -mostrar](https://github.com/EvolutionAPI/evolution-api/assets/142674805/e25592ac-901c-4dac-aa2b-eb9c6ecf1ce8)

**Comment by DavidsonGomes** [comment]
Isso ja estamos cientes.
