### ISSUE TITLE
Controle de Listas de Transmissão como temos de grupos

### ISSUE THREAD

**Issue by luisjuniorj** [EvolutionAPI/evolution-api#185]
Olá, pessoal.

Primeiramente parabéns pelo excelente trabalho!

Gostaria de saber se ja temos  e eu que não sei como fazer, ou se teremos controle de Listas de Transmissão como temos de Grupos.

Muito obrigado.

**Comment by DavidsonGomes** [comment]
O Whatsapp Web não tem a função de listas de transmissão, portanto não é possivel manipular pela api
