### ISSUE TITLE
Evo perdendo instâncias com status close.

### ISSUE THREAD

**Issue by jaison-x** [EvolutionAPI/evolution-api#189]
Percebi que a Evo acaba perdendo instâncias que estão com o status de close quando a api é reiniciada. 

Pelo que percebi isso acontece porque quando uma instância é fechada, ela emite o evento `logout.instance` e este evento chama o método `cleaningUp` da instância, que acaba excluindo a instância do repositório, porém a instância ainda continua na memória. Quando a api é restartada, ela busca as instâncias no repositório, e esta instância não existe mais e acaba não sendo recarregada.

Uma solução que encontrei seria não chamar a função `cleaningUp` no evento de `logout.instance`. Nesse caso, ocorre um problema ao tentar reconectar a instância. Solução que encontrei seria aí sim chamar o `cleaningUp` antes de reconectar ao whatsapp caso o state da instância seja close.

Perder uma instância por ela estar com o state close é algo ruim. Pessoal que conhece melhor o projeto poderia dar uma ajuda? Não conheço muito a estrutura e ainda não sei ao certo o que pode acontecer no core com estas mudanças. 

`monitor.service.ts:`
![image](https://github.com/EvolutionAPI/evolution-api/assets/5599142/b629940c-6f18-48f7-8c42-f63e0188256c)

`chatwoot.service.ts:`
![image](https://github.com/EvolutionAPI/evolution-api/assets/5599142/11e0bac4-b692-476d-a722-b698efab31f9)

**Comment by DavidsonGomes** [comment]
Sim, essa é um comportamento da api mesmo, para evitar ficar guardando muita coisa desnecessaria
