### ISSUE TITLE
erro na variável serverUrl

### ISSUE THREAD

**Issue by rafaelbarrosNT** [EvolutionAPI/evolution-api#191]
Quando cria a instância é criada uma variável _serverUrl_, essa variável provavelmente é usada quando é chamada o **setChatwoot**.

Está adicionando um **s** no domínio. P. ex. https://api.domain.com (url evolution) -> https://api.sdomain.com (serverUrl / webhookUrl do chatwoot).

![serverUrl error](https://github.com/EvolutionAPI/evolution-api/assets/34277815/7cc20187-af34-476b-9def-9db58394dc54)

**Comment by rafaelbarrosNT** [comment]
Ops! Erro meu.

Erro na configuração do Docker.

**Comment by Aritan15** [comment]
O que preciso fazer?

Em sáb., 21 de out. de 2023 às 08:11, Rafael Luis de Barros Neto <
***@***.***> escreveu:

**Comment by Aritan15** [comment]
Bom dia!

Como acertar?

**Comment by rafaelbarrosNT** [comment]
> Bom dia!
> 
> Como acertar?

Crie uma stack no Portainer com o conteúdo abaixo

`version: "3.8"

services:
  evolution_api:
    image: davidsongomes/evolution-api:latest
    #ports:
    - 8080:8080
    command: ["node", "./dist/src/main.js"]
    volumes:
      - eapi_instances:/evolution/instances
      - eapi_store:/evolution/store
    environment:
      SERVER_URL: https://api.<SEU_DOMINIO_AQUI>.com.br
      CONFIG_SESSION_PHONE_CLIENT: EvolutionAPI
      AUTHENTICATION_TYPE: apikey
      AUTHENTICATION_API_KEY: <SUA_KEY_AQUI>
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
      placement:
        constraints:
          - node.role == manager
    networks:
      - agent_network

networks:
  agent_network:
    external: true

volumes:
  eapi_instances:
    external: true
  eapi_store:
    external: true`

Lembre-se de alterar SEU_DOMINIO_AQUI e SUA_KEY_AQUI. Nas suas configurações do Cloudflare crie o registro **api** do tipo A apontando para o ip do seu servidor.
