### ISSUE TITLE
Feature: Poder renomear a inbox do chatwoot sem quebrar a conexão com o Evo API

### ISSUE THREAD

**Issue by stgcompany** [EvolutionAPI/evolution-api#192]
Tentei renomear no Chatwoot a inbox criada pelo Evo API e continuei a conseguir enviar mensagens, porém o recebimento não chegava ao Chatwoot.

Pelo visto o recebimento de mensagens são feitas através do nome da inbox, mas na minha visão deveria ser feita através do ID do inbox, dessa forma podendo renomear o inbox.

Digo isso pois cada inbox do evo api tem que ter um nome único, e queria criar inboxes com o nome "Whatsapp" para todas as contas do meu Chatwoot.

Como podemos mudar isso?

**Comment by jaison-x** [comment]
A Evo inteira utiliza o nome da instância internamente. Entendo também que isso não seja bom mas muito difícil mudar isso neste momento.

**Comment by regueir0** [comment]
Acredito q seria muito bom para organização, pois acaba que no dia a dia acontece muito de cliente querer mudar a caixa, e fica muito ruim colocar nomes aleatorios.

**Comment by DavidsonGomes** [comment]
Vamos trabalhar nessa ideia ainda

**Comment by codephix** [comment]
Opa @DavidsonGomes eu fiz essa integração, posso subir direto pelo dev? tambem integrei a opção de chatgpt direto. com a evolution, e coloquei para setar direto pela api, como tambem desativar e ativar para um contato especifico.

Unica diferencia que o meu precisa do redis, para funcionar por causa do ChatGPT, ainda vou configurar para não ser obrigatorio.

**Comment by DavidsonGomes** [comment]
> Opa @DavidsonGomes eu fiz essa integração, posso subir direto pelo dev? tambem integrei a opção de chatgpt direto. com a evolution, e coloquei para setar direto pela api, como tambem desativar e ativar para um contato especifico.
> 
> Unica diferencia que o meu precisa do redis, para funcionar por causa do ChatGPT, ainda vou configurar para não ser obrigatorio.

Qualquer contribuição é bem vinda, suba uma pull request para develop
