### ISSUE TITLE
 Evolution crasha ao tentar criar nova instancia com Chatwoot

### ISSUE THREAD

**Issue by matheusmaiberg** [EvolutionAPI/evolution-api#193]
# Logs de erro abaixo
<details>

<summary> Expandir Logs de erro</summary>
2023-10-24T19:23:55.073742957Z         at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2023-10-24T19:23:55.073746617Z       url: 'https://crm.groufy.com.br/api/v1/accounts/2/conversations',
2023-10-24T19:23:55.073750278Z       status: 500,
2023-10-24T19:23:55.073753768Z       statusText: 'Internal Server Error',
2023-10-24T19:23:55.073781118Z       body: [Object],
2023-10-24T19:23:55.073784819Z       request: [Object]
2023-10-24T19:23:55.073788289Z     }
2023-10-24T19:23:55.073791819Z   },
2023-10-24T19:23:55.073795229Z   stderr: 2,
2023-10-24T19:23:55.073798619Z   error: ApiError: Internal Server Error
2023-10-24T19:23:55.073802269Z       at catchErrorCodes (/evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:226:15)
2023-10-24T19:23:55.073806079Z       at /evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:257:17
2023-10-24T19:23:55.073809819Z       at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2023-10-24T19:23:55.073813629Z     url: 'https://crm.groufy.com.br/api/v1/accounts/2/conversations',
2023-10-24T19:23:55.073817270Z     status: 500,
2023-10-24T19:23:55.073820820Z     statusText: 'Internal Server Error',
2023-10-24T19:23:55.073824340Z     body: { status: 500, error: 'Internal Server Error' },
2023-10-24T19:23:55.073827900Z     request: {
2023-10-24T19:23:55.073831380Z       method: 'POST',
2023-10-24T19:23:55.073834890Z       url: '/api/v1/accounts/{account_id}/conversations',
2023-10-24T19:23:55.073838580Z       path: [Object],
2023-10-24T19:23:55.073842250Z       body: [Object],
2023-10-24T19:23:55.073845730Z       errors: [Object]
2023-10-24T19:23:55.073849370Z     }
2023-10-24T19:23:55.073852951Z   }
2023-10-24T19:23:55.073856521Z } 
</details>

Chatwoot
v3.2.0

Mesmo criando a instancia manualmente e somente tentando vincular o Chatwoot depois, não gera conexão com a evolution API, nao envia nem a mensagem ao bot.

# Comportamentos
Caixa ainda é criada no chatwoot automaticamente (contato EvolutionAPI tambem)
Contatos ainda sendo recebidos da instancia
Mensagens não são recebidas nem enviadas, nem ao bot, nem a contatos inseridos manualmente
Caixas de entradas inseridas pré atualização continuam funcionando

**Comment by matheusmaiberg** [comment]
Update, na conta de ID numero 1, a instancia e criada normalmente, na conta de ID 2 o chatwoot não consegue se comunicar com a evolution API, então ao tentar criar instancia ele crasha.

Estou tentando solução com tokens diferentes pra ver se é algo relacionado a autorização

**Comment by tiagooliveira1** [comment]
Por aqui tendo o mesmo comportamento. Conseguiu evoluir aí @matheusmaiberg ?

**Comment by tiagooliveira1** [comment]
Por aqui tendo o mesmo comportamento. Conseguiu evoluir aí @matheusmaiberg ?

Aqui ao tentar criar a instãncia recebo a mensagem no log do pm2:

```
 [Evolution API]  v1.5.4  27319   -  Fri Nov 17 2023 18:02:51     ERROR   [unhandledRejection]  [object]
0|ApiEvolution  | {
0|ApiEvolution  |   origin: Promise {
0|ApiEvolution  |     <rejected> ApiError: Internal Server Error
0|ApiEvolution  |         at catchErrorCodes (/root/evolution-api/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:226:15)
0|ApiEvolution  |         at /root/evolution-api/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:257:17
0|ApiEvolution  |         at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
0|ApiEvolution  |       url: 'https://[dominio oculto ]/api/v1/accounts/2/conversations',
0|ApiEvolution  |       status: 500,
0|ApiEvolution  |       statusText: 'Internal Server Error',
0|ApiEvolution  |       body: [Object],
0|ApiEvolution  |       request: [Object]
0|ApiEvolution  |     }
0|ApiEvolution  |   },
0|ApiEvolution  |   stderr: 2,
0|ApiEvolution  |   error: ApiError: Internal Server Error
0|ApiEvolution  |       at catchErrorCodes (/root/evolution-api/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:226:15)
0|ApiEvolution  |       at /root/evolution-api/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:257:17
0|ApiEvolution  |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
0|ApiEvolution  |     url: 'https://[dominio oculto]/api/v1/accounts/2/conversations',
0|ApiEvolution  |     status: 500,
0|ApiEvolution  |     statusText: 'Internal Server Error',
0|ApiEvolution  |     body: { status: 500, error: 'Internal Server Error' },
0|ApiEvolution  |     request: {
0|ApiEvolution  |       method: 'POST',
0|ApiEvolution  |       url: '/api/v1/accounts/{account_id}/conversations',
0|ApiEvolution  |       path: [Object],
0|ApiEvolution  |       body: [Object],
0|ApiEvolution  |       errors: [Object]
0|ApiEvolution  |     }
0|ApiEvolution  |   }
0|ApiEvolution  | }
```

**Comment by matheusmaiberg** [comment]
Sim, resolvi, você tem que deixar desmarcado o response_bots quando criar uma nova conta.

Aqui!
![image](https://github.com/EvolutionAPI/evolution-api/assets/119268809/a0813bb7-c723-4087-ab2d-8260ea47f7f9)


Só acessar o endpoint
```
/super_admin/accounts/2/edit
```
Exemplo
```
chatwoot.seudominio.com.br/super_admin/accounts/2/edit
```

Ai desmarcar e salvar

**Comment by matheusmaiberg** [comment]
Outra solução é criar contas com o token do platform apps como por padrao o response bots vem desativado nas configs de criação de conta.

O endpoint é 
/platform/api/v1/accounts

Header 
"api_access_token": "token de app da sua conta"

Body
"name": "nome da nova conta"
"locale": "pt_BR"

Assim você cria uma conta nova via API e foi por isso que descobri.

![image](https://github.com/EvolutionAPI/evolution-api/assets/119268809/6ba2a8c0-da3c-43ec-9a18-629896e2ceda)

Eu mesmo criei um fluxo de dados de quando assinarem no meu Woocomerce ja cria uma conta nova no Chatwoot com o usuario com as autorizacoes corretas dentro e envia o login e senha pra pessoa.

PS: O token so funciona em contas criadas por ele mesmo, ele vai dar permission error se tentar acessar uma conta que não foi criada por ele.

**Comment by tiagooliveira1** [comment]
> Sim, resolvi, você tem que deixar desmarcado o response_bots quando criar uma nova conta.
> 
> Aqui! ![image](https://user-images.githubusercontent.com/119268809/283937982-a0813bb7-c723-4087-ab2d-8260ea47f7f9.png)
> 
> Só acessar o endpoint
> 
> ```
> /super_admin/accounts/2/edit
> ```
> 
> Exemplo
> 
> ```
> chatwoot.seudominio.com.br/super_admin/accounts/2/edit
> ```
> 
> Ai desmarcar e salvar

Perfeito! Agradeço a dica. Agora sim cadastrou corretamente. Ainda não vejo o  QR Code, mas agora está cadastrando a instância corretamente. 

Muito obrigado

**Comment by matheusmaiberg** [comment]
> Muito obrigado
De nada.

>Perfeito! Agradeço a dica. Agora sim cadastrou corretamente. Ainda não vejo o QR Code, mas agora está cadastrando a instância corretamente.
Então, normalmente acontece isso por que você colou a URL com o / no postman ou no manager na hora de vincular o chatwoot.

Normalmente é isso.

**Comment by DavidsonGomes** [comment]
Esse erro esta sendo gerado dentro do chatwoot, vou realizar os testes simulando essa situação

**Comment by DavidsonGomes** [comment]
Problema resolvido na versao 1.6.0
