### ISSUE TITLE
Não está sendo possível listar as intâncias 

### ISSUE THREAD

**Issue by gadonski** [EvolutionAPI/evolution-api#195]
Cadastrei duas instâncias como teste, porém após remover uma não está sendo possível listar as instâncias, conforme erro abaixo. No log também não encontrei erros

```
{
	"status": 500,
	"error": "Internal Server Error",
	"response": {
		"message": "Cannot read properties of null (reading 'apikey')"
	}
}
```

Log da aplicação
```
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [InstanceRouter]  [string]  request received in fetchInstances 
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [InstanceRouter]  [string]  request body:  
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [InstanceRouter]  [object]   
4|evolutionapi  | {} 
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [InstanceRouter]  [string]  request query:  
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [InstanceRouter]  [object]   
4|evolutionapi  | {} 
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [InstanceController]  [string]  requested fetchInstances (all instances) 
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [WAMonitoringService]  [string]  get instance info 
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [WAMonitoringService]  [string]  get instance info: teste01 
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [WAStartupService]  [string]  Finding chatwoot 
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [WAStartupService]  [string]  Getting instance name 
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [ChatwootRepository]  [string]  finding chatwoot 
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [ChatwootRepository]  [string]  finding chatwoot in db 
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [WAStartupService]  [string]  Chatwoot not found 
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [WAStartupService]  [string]  Getting connection status 
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [WAMonitoringService]  [string]  instance: teste01 - connectionStatus: open 
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [WAStartupService]  [string]  Getting remoteJid of instance 
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [WAStartupService]  [string]  Getting profile name 
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [WAStartupService]  [string]  Profile name: Teste da Silva 
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [WAStartupService]  [string]  Getting profile picture url 
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [WAStartupService]  [string]  Getting profile status 
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [WAStartupService]  [string]  Profile status: Teste da Silva 
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [WAStartupService]  [string]  Getting connection status 
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [AuthRepository]  [string]  finding auth 
4|evolutionapi  | [Evolution API]  v1.5.4  293314   -  Fri Oct 27 2023 12:21:34     VERBOSE   [AuthRepository]  [string]  finding auth in db 

```

Alguém sabe o que pode ser?

**Comment by Rafael-Deiro** [comment]
Tendo o mesmo problema aqui também.
Os únicos logs de erro que vejo aqui são referentes ao MongoDB.

Minha instalação usa o Docker dentro do AWS ECS, com base no arquivo .env original da aplicação, e o banco de dados é um MongoDB 6.0.11 hospedado no MongoDB Atlas

Erro 1
![image](https://github.com/EvolutionAPI/evolution-api/assets/40615781/4d32819d-6a11-405d-9de9-a6161b329810)

Erro 2
![image](https://github.com/EvolutionAPI/evolution-api/assets/40615781/20b88180-f0eb-40a4-9f52-eed4da6559a2)

**Comment by DavidsonGomes** [comment]
Basta ler o seu erro, voce não esta passando a apikey na header da requisição.

apikey: TOKEN

**Comment by Rafael-Deiro** [comment]
> Basta ler o seu erro, voce não esta passando a apikey na header da requisição.
> 
> apikey: TOKEN

O problema é exatamente que a api key estava sendo enviada corretamente na requisição, esse erro ocorre sempre que uma instância é removida.
Estranhamente o erro parou de acontecer quando desativei o uso do banco de dados no Evolution.

**Comment by gadonski** [comment]
> > Basta ler o seu erro, voce não esta passando a apikey na header da requisição.
> > apikey: TOKEN
> 
> O problema é exatamente que a api key estava sendo enviada corretamente na requisição, esse erro ocorre sempre que uma instância é removida. Estranhamente o erro parou de acontecer quando desativei o uso do banco de dados no Evolution.

o mesmo acontece aqui

**Comment by HerdneySantos** [comment]
> > Basta ler o seu erro, voce não esta passando a apikey na header da requisição.
> > apikey: TOKEN
> 
> O problema é exatamente que a api key estava sendo enviada corretamente na requisição, esse erro ocorre sempre que uma instância é removida. Estranhamente o erro parou de acontecer quando desativei o uso do banco de dados no Evolution.

O meu começou a aparecer esse erro, mas só no endpoint específico de "/instance/fetchInstances". Consigo criar as instâncias, usar outros endpoints. Apenas esse que aparece esse erro.

**Comment by Rafael-Deiro** [comment]
@gadonski @HerdneySantos o que resolveu esse bug pra mim foi deixar rodando sem Redis e sem MongoDB, salvando tudo em arquivos mesmo. Desde então, não testei novamente ativando o banco de dados.

**Comment by gadonski** [comment]
> @gadonski @HerdneySantos o que resolveu esse bug pra mim foi deixar rodando sem Redis e sem MongoDB, salvando tudo em arquivos mesmo. Desde então, não testei novamente ativando o banco de dados.

Pois é, aqui também se eu zerar o banco funciona. Acredito que algum registro está ficando inválido.

**Comment by AlexandreSoftway** [comment]
> > @gadonski @HerdneySantos o que resolveu esse bug pra mim foi deixar rodando sem Redis e sem MongoDB, salvando tudo em arquivos mesmo. Desde então, não testei novamente ativando o banco de dados.
> 
> Pois é, aqui também se eu zerar o banco funciona. Acredito que algum registro está ficando inválido.

como vc zerou o banco?
