### ISSUE TITLE
Error updating Typebot ao tentar conectar a Evolution API

### ISSUE THREAD

**Issue by IcaruuS22** [EvolutionAPI/evolution-api#196]
Boa tarde, estou tendo esse erro "Error updating Typebot" quando tento conectar o Tybebot a EvolutionAPI, alguém já passou por isso e sabe como resolver?

**Comment by suissa** [comment]
Vc está rodando do docker ou puro?

**Comment by jmpo** [comment]
pudiste resolver bro?

**Comment by IcaruuS22** [comment]
Sim, consegui resolver setando o bot através de fluxo pelo N8N.
