### ISSUE TITLE
Feature: Evitar Grupos no Typebot

### ISSUE THREAD

**Issue by stgcompany** [EvolutionAPI/evolution-api#199]
Tive que fazer um filtro no typebot para evitar de enviar mensagens em grupos, seria interessante ter essa opção nativa no Evolution na API de criação de uma instância Typebot.

**Comment by suissa** [comment]
Concordo, aliás como vc fez?

**Comment by stgcompany** [comment]
> Concordo, aliás como vc fez?

Pegando a variável remoteJId pra pegar o número e fazer uma condicional pra ver se no final tem "@g,us" que é a identificação de que aquele contato é um grupo

**Comment by suissa** [comment]
Entendi mas em qual arquivo você fez? Typebot.Service?

**Comment by stgcompany** [comment]
Não amigo, fiz isso no próprio workflow do typebot, com um filtro IF

**Comment by suissa** [comment]
Ah entendi!, mas o problema é que não envia o remoteJid pra api do typebot, só se tivesse uma palavra-chave q o typebot mandasse, a Evolution entendesse e dai retornava o remoteJid.

Dá pra pensar em fazer, antes estou tentando forçar a Evolution enviar as msgs do Tyepbot em ordem que chega mas não ta, tem coisa do final vindo antes, to nessa peleja

**Comment by stgcompany** [comment]
Somente agora que percebi que já existe essa funcionalidade na api de configuração (em `groups_ignore: true`), fiz um teste aqui e funcionou :+1:

![Screenshot from 2023-11-17 14-52-09](https://github.com/EvolutionAPI/evolution-api/assets/143809393/b7d543f1-d296-43a5-9513-5dff075317c8)
