### ISSUE TITLE
pairingCode incorreto 

### ISSUE THREAD

**Issue by traderpedroso** [EvolutionAPI/evolution-api#200]
Quando tento autenticar usando o código pering sem scaner QRcode me gera numero incorreto versão 1.5.4

**Comment by DavidsonGomes** [comment]
Iremos testar isso, obrigado

**Comment by DavidsonGomes** [comment]
Subimos uma correção pra isso na v1.6.1 atualmente em develop

**Comment by DRIMOL** [comment]
@DavidsonGomes tentei na 1.7.1 e agora na 1.8.1 e continua não funcionando, consegue testar ai ?

**Comment by eduardochaves1** [comment]
Comigo também na 1.8.1 não identifica o código como correto.

**Comment by MateusHBLima** [comment]
Olá, estou tendo esse erro na 2.2.3

**Comment by AnthonyKamers** [comment]
estou tendo este erro na 2.2.3
