### ISSUE TITLE
Erro ao conectar EvolutionAPI + Chatwott

### ISSUE THREAD

**Issue by jordaoluiz** [EvolutionAPI/evolution-api#201]
Pessoal, instalei o chatwoot ultima versão, evolution api 1.5.4 , é gerado o QR code, conectado com o número certinho, as mensagens enviadas para o numero caem no chatwoot mas as respostas do atendente não chegam a quem enviou a mensagem no número.

**Comment by srthiagofreitas** [comment]
Boa tarde!
Aproveitando a Issue, no meu caso estou com o evoapi 1.5.4, crio a instancia, aparece no chatwoot, mas não gera o qrcode.

**Comment by ederbatera** [comment]
> Boa tarde! Aproveitando a Issue, no meu caso estou com o evoapi 1.5.4, crio a instancia, aparece no chatwoot, mas não gera o qrcode.

Exatamente. Notei que se logar o QR pela api, e através do Chatwoot enviar a primeira mensagem, ele passa funcionar.

**Comment by srthiagofreitas** [comment]
> > Boa tarde! Aproveitando a Issue, no meu caso estou com o evoapi 1.5.4, crio a instancia, aparece no chatwoot, mas não gera o qrcode.
> 
> Exatamente. Notei que se logar o QR pela api, e através do Chatwoot enviar a primeira mensagem, ele passa funcionar.

Não sei se entendi bem, ederbatera. Você conectou o EvolutionApi com Chatwoot, recebeu o QRCODE?

**Comment by FabiolaBaani** [comment]
> Pessoal, instalei o chatwoot ultima versão, evolution api 1.5.4 , é gerado o QR code, conectado com o número certinho, as mensagens enviadas para o numero caem no chatwoot mas as respostas do atendente não chegam a quem enviou a mensagem no número.

Deixa eu te perguntar uma coisa? Vi que vc instalou o Typebot tb em outro issue, vc conseguiu resolver o problema de login no Google Sheets?

**Comment by ederbatera** [comment]
> > > Boa tarde! Aproveitando a Issue, no meu caso estou com o evoapi 1.5.4, crio a instancia, aparece no chatwoot, mas não gera o qrcode.
> > 
> > 
> > Exatamente. Notei que se logar o QR pela api, e através do Chatwoot enviar a primeira mensagem, ele passa funcionar.
> 
> Não sei se entendi bem, ederbatera. Você conectou o EvolutionApi com Chatwoot, recebeu o QRCODE?

Se vc logar com QR Direto na api, e enviar a mensagem pelo CW, ele funciona.
