### ISSUE TITLE
 Feature Request: 'Orders Support' for WhatsApp Business

### ISSUE THREAD

**Issue by Jorgelig** [EvolutionAPI/evolution-api#202]
Hello EvolutionAPI team,

I am writing to request the implementation of an 'Orders Support' feature for WhatsApp Business within the Evolution API. This feature would allow business owners to create and track orders, with event notifications for order processing, shipping, and completion, along with the ability to update payment status.

This functionality would be a valuable addition for managing business operations efficiently through WhatsApp. I believe many users would benefit from this feature. 

Reference: [WhatsApp Documentation](https://faq.whatsapp.com/491426289812695/?cms_platform=android)

Thank you for considering my request.

======================================================

Olá equipe da EvolutionAPI,

Estou escrevendo para solicitar a implementação de uma funcionalidade de 'Suporte a Pedidos' para WhatsApp Business dentro da Evolution API. Esta função permitiria aos proprietários de negócios criar e rastrear pedidos, com notificações de eventos para o processamento, envio e conclusão de pedidos, junto com a capacidade de atualizar o status do pagamento.

Esta funcionalidade seria uma valiosa adição para gerenciar operações empresariais de maneira eficiente através do WhatsApp. Acredito que muitos usuários se beneficiariam desta função.

Referência: [Documentação do WhatsApp](https://faq.whatsapp.com/491426289812695/?cms_platform=android)

Obrigado por considerar minha solicitação.

**Comment by DavidsonGomes** [comment]
As funcionalidades do whatsapp business serão disponibilizadas em breve obrigado pela sugestão
