### ISSUE TITLE
New ChatWoot reply function

### ISSUE THREAD

**Issue by ederbatera** [EvolutionAPI/evolution-api#204]
Poderia na próxima versão, incluir na API a nova funcionalidade de "Responder" do Chatwoot 3.2.0.

**Comment by dfares1987** [comment]
a funcao de responder funciona para o usurio master nao sei informar o porque porem para os outros usuario nao funcio chat 3,2 evo 1,54

**Comment by codephix** [comment]
para resposta do chatwoot 3.2.0 fiz o seguinte.
no arquivo

src/whatsapp/services/chatwoot.service.ts

Apos a linha 1047

        if (body.content_attributes.in_reply_to){
          var idResposta = (body.content_attributes.in_reply_to-1);
          var conversationId = body.conversation.contact_inbox.inbox_id;
          let config = {
            method: 'get',
            maxBodyLength: Infinity,
            url: `${this.provider.url}/api/v1/accounts/${this.provider.account_id}/conversations/${conversationId}/messages?after=` + idResposta,
            headers: {
              'api_access_token': this.provider.token
            }
          };
          try {
            const { data } = await axios.request(config);
            if (data.payload[0] && data.payload[0].id == body.content_attributes.in_reply_to) {
              formatText = formatText +`\n\nResposta à: \n` + data.payload[0].content + ``;
            }
            this.logger.verbose('data sent');
          } catch (error) {
            this.logger.error(error);
          }
        }

Ai ele adiciona como exemplo

Max Alex:
Tudo bem

Resposta à: 
olá

**Comment by ederbatera** [comment]
> para resposta do chatwoot 3.2.0 fiz o seguinte. no arquivo
> 
> src/whatsapp/services/chatwoot.service.ts
> 
> Apos a linha 1047
> 
> ```
>     if (body.content_attributes.in_reply_to){
>       var idResposta = (body.content_attributes.in_reply_to-1);
>       var conversationId = body.conversation.contact_inbox.inbox_id;
>       let config = {
>         method: 'get',
>         maxBodyLength: Infinity,
>         url: `${this.provider.url}/api/v1/accounts/${this.provider.account_id}/conversations/${conversationId}/messages?after=` + idResposta,
>         headers: {
>           'api_access_token': this.provider.token
>         }
>       };
>       try {
>         const { data } = await axios.request(config);
>         if (data.payload[0] && data.payload[0].id == body.content_attributes.in_reply_to) {
>           formatText = formatText +`\n\nResposta à: \n` + data.payload[0].content + ``;
>         }
>         this.logger.verbose('data sent');
>       } catch (error) {
>         this.logger.error(error);
>       }
>     }
> ```
> 
> Ai ele adiciona como exemplo
> 
> Max Alex: Tudo bem
> 
> Resposta à: olá
