### ISSUE TITLE
Não recebe mensagens de alguns grupos específicos 

### ISSUE THREAD

**Issue by executivotelemed** [EvolutionAPI/evolution-api#205]
Boa tarde, vi por aqui relato de não está recebendo todas msgs......comigo corre com alguns grupos específicos, onde nesse grupo simplesmente para de receber qualquer msg enviada nele, já tentei olhar a id do grupo para ver se era uma + antiga e não era todos normais......a msg chega em determinado grupo X, eu mesmo do foward para o grupo Y, no grupo Y a api recebe a msg no X não.....as vezes quando do um restart na API ela recebe no grupo Y mas por um certo tempo e depois para novamente. Alguem tem alguma ideia? já fiz diversos testes e validações e até agora nada. 

isso ocorre usando a versão 1.51 e 1.54

**Comment by regueir0** [comment]
Aqui tbm ocorre isso... funciona tudo normal porem alguns grupos especificos, nao conseguimos enviar mensagem de forma alguma, ja testei tbm resolver a conversa no chatwoot, logar  deslogar... algo estranho.

**Comment by IcaruuS22** [comment]
Estou com este mesmo problema... Infelizmente parece que não estão nem ai :(

**Comment by DavidsonGomes** [comment]
Problema ja conhecido, infelizmente isso vem da Baileys, a lib que usamos para manipular o whatsapp, estamos ainda trabalhando para melhorar essa situação
