### ISSUE TITLE
No Session on n8n when trying to send Message

### ISSUE THREAD

**Issue by MattCarneiro** [EvolutionAPI/evolution-api#206]
É exatamente o que o título diz. Depois de algum tempo, a instância logada não manda mais mensagem para aquele contato específico por requisição POST no n8n. Retornando erro 400 bad request no session. Só volta quando reinicia a API no docker.

**Comment by DavidsonGomes** [comment]
Problema ja conhecido, para resolver provisoriamente faça um processo de reiniciar o container da api ou utilização do mongodb ou redis se for uma conexao so. estamos trabalhando para melhorar essa questao
