### ISSUE TITLE
resposta de mensagem chatwoot

### ISSUE THREAD

**Issue by edcarlosm** [EvolutionAPI/evolution-api#21]
seria interessante coloca para mostrar as resposta, pois o assunto acaba ficando fora do contesto.
exemplo.
 Quando você está falando com alguém que está utilizando o aplicativo oficial e ele utiliza o recurso de responder o chatwoot acaba perdendo o contesto da conversa pois nele só vai mostrar a resposta não vai aparecer a pergunta junto.

**Comment by DavidsonGomes** [comment]
Chatwoot nao tem função de resposta, ate tentamos mostrar isso de alguma forma, mas fica muito confuso.

**Comment by edcarlosm** [comment]
Por sugestão do Edison vou está mandando mais informações dessa solicitação.
quando recebemos um evento de resposta temos a pergunta e resposta no mesmo evento, dessa forma poderia manda a pergunta novamente informando quem fez a pergunta e manda a resposta.
poderia até coloca algum icone sinalizando que é uma resposta.
sei que não da para responder mais só em receber essa informação vai fica bem legal
