### ISSUE TITLE
Typebot - API sending order messages

### ISSUE THREAD

**Issue by suissa** [EvolutionAPI/evolution-api#217]
I'm having issues with the sequence of message sends in Typebot, as it arrives in an array correctly but the API sends it wrongly. In one bot, it's always texts first, then images, and then audio. And in the typebot that comes with the repository, it even shows the image before some texts, but it displays all the texts in the wrong order.

Is it like this for anyone else?

**Comment by matheusmaiberg** [comment]
Actually not, set a delay between messages, 1 or 2 seconds should be enough and will not impact the user experience.

Let me know if the problem is solved.

**Comment by DavidsonGomes** [comment]
The synchronization problem happens for several reasons, sometimes messages are sent, but there is a delay in WhatsApp, to avoid this, always use wait in front of the message that you want to apply the delay to.
