### ISSUE TITLE
Projeto abandonado?

### ISSUE THREAD

**Issue by MattCarneiro** [EvolutionAPI/evolution-api#218]
Não vai sair mais atualizações pra consertar os Bugs dessa API? E não são poucos! Sinceramente! Pelo menos 15% das mensagens somem e não são enviadas pelo webhook. Isso sem contar em erro de No Session, e vários outros

**Comment by MattCarneiro** [comment]
Acho que não hein... Antes todo mundo comentava aqui. Agora tá vazio

**Comment by bee360** [comment]
E aiii? Foi abandonada mesmo??

**Comment by DavidsonGomes** [comment]
Projeto não foi abandonado, estamos trabalhando com mais cuidado nas proximas atualizações, devido a uma atualização na Baileys que é a lib de whatsapp usada no projeto
