### ISSUE TITLE
reagir a ligação no chatwoot

### ISSUE THREAD

**Issue by edcarlosm** [EvolutionAPI/evolution-api#22]
Hoje tenho vários clientes que fica ligando via whatsapp para meu numero conectado no chatwoot, queria saber se tem como criar um parâmetro para rejeitar essas ligações e manda uma mensagem para o cliente ou ativar esse evento para ele manda uma mensagem falando, olha não recebo ligação manda uma mensagem ou liga normal.
 eu sei que a codechat não tinha esse recurso, mais já testei outras apis que tem. teria como implementar?.
 Obrigado.

**Comment by DavidsonGomes** [comment]
Esta em desenvolvimento 😉
