### ISSUE TITLE
Após pausar o BOT, não é possivel encerrar o mesmo usando o comando #SAIR

### ISSUE THREAD

**Issue by luizfeliperc** [EvolutionAPI/evolution-api#220]
Pessoal

Em meu fluxo, tenho comando de closed, que funciona bem e outros 2 de paused. Em ambos os casos do paused não consigo encerrar o bot.

![image](https://github.com/EvolutionAPI/evolution-api/assets/29809390/2ee59da9-ad2e-46d4-8759-52bb673804d3)

O fluxo acima mostra de fato o que ocorre.
Cliente escolhe a opção de falar com atendente, uma mensagem é enviada e em seguida o webhook do comando "paused" é iniciado.

Após finalizar a conversa, mesmo o cliente digitando "#sair" nada acontece.
Se eu fizer o mesmo comando, nada acontece também. (acredito que isto se deve a a variavel "listening_from_me": false)

Entendo que este comando é geral e pode ser utilizado em qualquer chamada do bot, porém ao pausar a sessão ele não é encerrado.

Como fazer para de fato encerrar a conversa e dar a opção do cliente chamar o bot novamente?

**Comment by luizfeliperc** [comment]
Não sei se é um BUG da API ou se realmente é o comportamento.]
Alguém poderia dar uma luz?

**Comment by edgardjnr** [comment]
tenta criar um webhook para opened ...

**Comment by DavidsonGomes** [comment]
Uma vez que pausado o bot, as mensagens não são mais direcionadas para o mesmo, para funcionar precisa reabrir a sessão

**Comment by luizfeliperc** [comment]
> Uma vez que pausado o bot, as mensagens não são mais direcionadas para o mesmo, para funcionar precisa reabrir a sessão

Obrigdo por responder Davdson. Como essa sessão seria reaberta? Não é possivel fazer pelo typebot uma vez que é pausado.

Em conversa com um amigo, chegamos a essa conclusão: 

Quando está com status "paused", ele entra nessa condição e não cria o typebot, sem criar o typebot ele não entra na verificação da mensagem, se é #SAIR ou não, pois essa verificação acontece dentro do sendTypebot, pelo debug que eu fiz esse é o problema mesmo
![image](https://github.com/EvolutionAPI/evolution-api/assets/29809390/e0f184db-4b43-44a6-a034-54f126273d89)
![image](https://github.com/EvolutionAPI/evolution-api/assets/29809390/1defd5b1-04c8-4e09-a8ed-5db3701f22c5)

![image](https://github.com/EvolutionAPI/evolution-api/assets/29809390/6e9230b0-c6ba-4a67-9661-7608bf51f29f)

Coloquei a validação dentro dessa condição, caso seja o #SAIR ele encerra também 
Dessa forma, o comando funcionou mesmo com a API pausada.
