### ISSUE TITLE
SessionError: No sessions

### ISSUE THREAD

**Issue by MatheusGatti** [EvolutionAPI/evolution-api#221]
Estou enfrentando problemas ao enviar mensagem para grupos utilizando a API `{{baseUrl}}/message/sendText/{{instance}}`.

Como visto em outra thread (#17) a recomendação era de reiniciar o processo, no meu caso no Docker, e mesmo reiniciando o erro persiste.

Request POST Payload Body:
```json
{
    "number": "JID do grupo (não vou colocá-lo aqui)",
    "options": {
        "delay": 1200,
        "presence": "composing",
        "linkPreview": false
    },
    "textMessage": {
        "text": "Mensagem de exemplo"
    }
}
```

Response <400>:
```json
{
    "status": 400,
    "error": "Bad Request",
    "response": {
        "message": [
            "SessionError: No sessions"
        ]
    }
}
```

**Comment by MattCarneiro** [comment]
Tem que reiniciar a cada 3 horas pra evitar isso. Faz um cron

**Comment by lindenbergp** [comment]
Solução gambiarra é reiniciar a API.

**Comment by DavidsonGomes** [comment]
Problema ja conhecido, estamos trabalhando para resolver

**Comment by trojantm** [comment]
@DavidsonGomes alguma novidade sobre este problema?

**Comment by trojantm** [comment]
> Solução gambiarra é reiniciar a API.

@bergpinheiro seria reiniciar a instancia ou a API por completo?

**Comment by TiagoGouvea** [comment]
Apareceu aqui também esse erro..

**Comment by MegaAfonso** [comment]
Olá, pessoal! Tudo bem? Já teve solução para este erro?

**Comment by rmfoureaux** [comment]
aqui de vez enquando da isso, as vezes mesmo com erro envia a msg, as vezes não... vai entender, queria tratar os erros para tentar reenviar novamente, sendo que desse jeito não dá

**Comment by Aguilar2020** [comment]
alguem conseguiu solucionar o problema?

**Comment by eduardochaves1** [comment]
Já perdi duas instâncias na 1.8.2 por conta desse bug, não cheguei a testar a parada de reiniciar a API.

**Comment by mamedess** [comment]
> Já perdi duas instâncias na 1.8.2 por conta desse bug, não cheguei a testar a parada de reiniciar a API.

Funciona.

**Comment by eduardochaves1** [comment]
![image](https://github.com/user-attachments/assets/842ef2fc-3d6a-4fbd-8ba7-e6727ef27bc8)

Eu percebi que quando dá o erro de No Sessions na instância, esses documentos aparecem no registro dessa instância do mongo

**Comment by damuz91** [comment]
Acabei de instalar o evolution-api, sou novo nisso. Notei que tenho esse erro com apenas um chat, com os outros funciona perfeitamente. Cliquei no botão Restart na instância, mas ainda continua acontecendo. Como posso contribuir fornecendo informações para solucionar esse bug? Estou usando a versão 2.1.0 do Evolution Manager.

```
400 - "{\"status\":400,\"error\":\"Bad Request\",\"response\":{\"message\":[\"SessionError: No sessions\"]}}"
```

**Comment by rmfoureaux** [comment]
eu resolvo da seguinte maneira, excluo a instancia e crio ela novamente em seguida, ai resolve esse problema, fora isso ela fica presa agarrada

**Comment by jeffersonfelixdev** [comment]
Estou com esse problema para enviar mensagens em alguns grupos. Estou com cache do redis desativado e cache local ativado.

**Comment by Darras** [comment]
reparei que isso ocorre em grupos que foram criados ha muito tempo, grupos com mais de anos de existencia. Grupos novos o problema nao acontece. Tentei enviar mensagem em um grupo que possuia mais de 4 anos da data que foi criado. a mensagem simplesmente nao envia e retorna esse mesmo erro.

**Comment by jonathandebrito** [comment]
**O erro ainda persiste!** 

Pelo que percebi, esse problema não acontece em todos os grupos, apenas em alguns específicos, geralmente grupos mais antigos. Parece estar relacionado à criptografia ou ao armazenamento da sessão desses grupos. 

Já se passaram anos desde que esse bug foi reportado, e até agora a única "solução" encontrada continua sendo reiniciar a API ou recriar a instância. Existe alguma previsão real para corrigirem isso ou o Evolution API vai continuar dependendo de workarounds?

**Comment by TiagoGouvea** [comment]
Issue relacionada #554

**Comment by Feperson** [comment]
> **O erro ainda persiste!**
> 
> Pelo que percebi, esse problema não acontece em todos os grupos, apenas em alguns específicos, geralmente grupos mais antigos. Parece estar relacionado à criptografia ou ao armazenamento da sessão desses grupos.
> 
> Já se passaram anos desde que esse bug foi reportado, e até agora a única "solução" encontrada continua sendo reiniciar a API ou recriar a instância. Existe alguma previsão real para corrigirem isso ou o Evolution API vai continuar dependendo de workarounds?

O que quer dizer com "reiniciar a API"? seria reiniciar fazendo uma chamada API que tem no postman  tipo "{{baseUrl}}/instance/restart/{{instance}}" ou seria reiniciar o container no servidor?

**Comment by TiagoGouvea** [comment]
Pelo que tenho visto é reiniciar o servidor mesmo.. parar o docker e começar novamente.. tenso né.

**Comment by Iann-Monteiro** [comment]
> > **O erro ainda persiste!**
> > Pelo que percebi, esse problema não acontece em todos os grupos, apenas em alguns específicos, geralmente grupos mais antigos. Parece estar relacionado à criptografia ou ao armazenamento da sessão desses grupos.
> > Já se passaram anos desde que esse bug foi reportado, e até agora a única "solução" encontrada continua sendo reiniciar a API ou recriar a instância. Existe alguma previsão real para corrigirem isso ou o Evolution API vai continuar dependendo de workarounds?
> 
> O que quer dizer com "reiniciar a API"? seria reiniciar fazendo uma chamada API que tem no postman tipo "{{baseUrl}}/instance/restart/{{instance}}" ou seria reiniciar o container no servidor?

reiniciar o container mesmo

**Comment by DeeSouza** [comment]
Aqui aconteceu hoje. 
Rodei o docker novamente, funcionou.

Mas tem alguma causa raíz do porquê isso acontece?

**Comment by morrisseybr** [comment]
Acontecendo muito aqui... Alguém sabe dizer o motivo disso?

**Comment by giordano221** [comment]
Problema voltou na versão 2.2.3

**Comment by eduardoworrel** [comment]
@DavidsonGomes alguma novidade sobre este ponto ou uma versão estável que eu possa utilizar?

**Comment by TiberioBrasil** [comment]
O problema realmente voltou na versão `2.2.3`.

Como utilizo a evolution com o Portainer, entrei no `Portainer`, fui em `Services`, selecionei o serviço da evolution e executei o `Update the service`. Após isso resolveu o problema.

**Comment by leonardogrig** [comment]
Pra quem estiver usando pelo easypanel, só reiniciar o serviço que volta a funcionar.

**Comment by LucasPedrosoTI** [comment]
Up - Estou com esse problema. Mesmo reiniciando o container, o problema persiste

**Comment by LucasPedrosoTI** [comment]
> Up - Estou com esse problema. Mesmo reiniciando o container, o problema persiste

Alguém sabe se o problema está resolvido na nova versão 2.3.0? Rodo com docker e a imagem ainda não foi atualizada.
@DavidsonGomes

**Comment by Luucasgontijo** [comment]
já resolveram esse? @DavidsonGomes

**Comment by LaizaAlmeid** [comment]
Up - Estou com o mesmo problema

**Comment by Murilandrade** [comment]
up

**Comment by pycodebr** [comment]
Mesmo problema aqui, começou ontem (30/09/2025)

**Comment by staruck** [comment]
Mesma coisa por aqui... Alguém achou saída já??

**Comment by Joel-Irineu** [comment]
Problema começou final da semana passada pra mim, o mais curioso é que tem grupos que envia mensagem e outros que ele dá esse problema :(

**Comment by Joel-Irineu** [comment]
consegui resolver de uma forma não muito indicada, mudei a versão para homologação `evoapicloud/evolution-api:homolog `, resolveu meu problema... acredito que na próxima atualização da api esteja tudo ok!

Lembrando que é uma versão em desenvolvimento então pode ser que apareçam bugs quando usar ela, antes que eles atualizem pra versão estável.

**Comment by willzins** [comment]
Aqui com o mesmo problema na versão Versão: 2.2.3 instalado no portainer

Tenho dois Whatsapps no mesmo grupo e um continua funcionando e o outro dá erro do no session, então o problema não é o grupo. Esse whatsapp da erro em um grupo e em outros não, não está seguindo nem um padrão aparentemente. Todos estavam funcionando normalmente e do nada parou e começou a dar esse erro.

**Comment by Murilandrade** [comment]
atendai/evolution-api

> consegui resolver de uma forma não muito indicada, mudei a versão para homologação `evoapicloud/evolution-api:homolog `, resolveu meu problema... acredito que na próxima atualização da api esteja tudo ok!
> 
> Lembrando que é uma versão em desenvolvimento então pode ser que apareçam bugs quando usar ela, antes que eles atualizem pra versão estável.

Qual a melhor imagem?

evoapicloud/evolution-api
atendai/evolution-api (uso essa hoje e ainda não consegui resolver)

**Comment by pycodebr** [comment]
> atendai/evolution-api
> 
> > consegui resolver de uma forma não muito indicada, mudei a versão para homologação `evoapicloud/evolution-api:homolog `, resolveu meu problema... acredito que na próxima atualização da api esteja tudo ok!
> > 
> > Lembrando que é uma versão em desenvolvimento então pode ser que apareçam bugs quando usar ela, antes que eles atualizem pra versão estável.
> 
> Qual a melhor imagem?
> 
> evoapicloud/evolution-api
> atendai/evolution-api (uso essa hoje e ainda não consegui resolver)

As versões mais recentes ficam em evoapicloud/evolution-api.
Imagens da atendai/evolution-api pararam na versão 2.2.3, então mesmo usando latest, será sempre a versão 2.2.3.
Mudaram a conta do Docker Hub, então sugiro alterar para evoapicloud/evolution-api.

**Comment by pycodebr** [comment]
Problema resolvido atualizando para a versão 2.3.4.
Tag da imagem: evoapicloud/evolution-api:v2.3.4

Obs: a conta do docker hub mudou, então a imagem deve ser alterada para evoapicloud/evolution-api se quiser as versões mais recentes. 

atendai/evolution-api parou na versão 2.2.3.

**Comment by Joel-Irineu** [comment]
> Problema resolvido atualizando para a versão 2.3.4. Tag da imagem: evoapicloud/evolution-api:v2.3.4
> 
> Obs: a conta do docker hub mudou, então a imagem deve ser alterada para evoapicloud/evolution-api se quiser as versões mais recentes.
> 
> atendai/evolution-api parou na versão 2.2.3.

Então no caso posso mudar tranquliamente para a 2.3.4 e deixar de usar a de homologação né? Muito obrigado!

**Comment by Felipinhun** [comment]
@pycodebr Resolveu aqui! Obrigado

**Comment by igorsamaral** [comment]
> ersão 2.3.4.
> Tag da imagem: evoapicloud/evolution-api:v2.3.4

Salvou!!

**Comment by RobsonTrasel** [comment]
Salvaram aqui...doc está desatualizada ainda mostrando versões anteriores....

<img width="863" height="466" alt="Image" src="https://github.com/user-attachments/assets/7231471d-44e3-4551-b735-60cf65c949b7" />

**Comment by joselucasgcosta** [comment]
> evoapicloud/evolution-api:v2.3.4



> > atendai/evolution-api
> > > consegui resolver de uma forma não muito indicada, mudei a versão para homologação `evoapicloud/evolution-api:homolog `, resolveu meu problema... acredito que na próxima atualização da api esteja tudo ok!
> > > Lembrando que é uma versão em desenvolvimento então pode ser que apareçam bugs quando usar ela, antes que eles atualizem pra versão estável.
> > 
> > 
> > Qual a melhor imagem?
> > evoapicloud/evolution-api
> > atendai/evolution-api (uso essa hoje e ainda não consegui resolver)
> 
> As versões mais recentes ficam em evoapicloud/evolution-api. Imagens da atendai/evolution-api pararam na versão 2.2.3, então mesmo usando latest, será sempre a versão 2.2.3. Mudaram a conta do Docker Hub, então sugiro alterar para evoapicloud/evolution-api.

Meu Deus ademiro, até aqui vc me salvando hahaha. Obrigado. Deus abençoe!

**Comment by Guilhermehenriquecr** [comment]
> Mesma coisa por aqui... Alguém achou saída já??

um cron pra reiniciar e reiniciar tb

**Comment by renanfukagawa** [comment]
Found the root cause of SessionError: No sessions for LID groups.

The bug is in messages-send.js inside Baileys — the code assumes group 
participants always use @s.whatsapp.net, but accounts with LID architecture 
use @lid. The wrong encoding causes assertSessions to look for non-existent 
sessions.

Fix: detect if participantsList contains @lid entries and use the correct 
server when encoding JIDs in patchMessageBeforeSending and in the 
senderKeyJids loop.

Patch (tested and working): https://gist.github.com/renanfukagawa/6043c92877e9eaca9b230d6a35a44507

Tested on: Evolution API v1.8.2, Baileys v6.7.5, Mac Mini M1 (ARM).
