### ISSUE TITLE
Evolution retornando "sessions" em POST

### ISSUE THREAD

**Issue by matiasduartee** [EvolutionAPI/evolution-api#225]
Olá pessoal! 

 Estou com um pequeno detalhe no Evolution, sou novo aqui. 

Ao tentar fazer qualquer método de POST na API, que seja para setar um Typebot ou até mesmo inativar o Typebot para um numero, me retorna o resultado:
```
{
  "typebot": {
    "instanceName": "teste",
    "typebot": {
      "enabled": true,
      "url": "https://typebotapi.site.com.br",
      "typebot": "atendimento",
      "expire": 30,
      "keyword_finish": "#sair",
      "delay_message": 1500,
      "unknown_message": "Mensagem não suportada!",
      "listening_from_me": true,
      "sessions": [
        {
          "remoteJid": "551199991234@s.whatsapp.net",
          "sessionId": "201369419-clpfzrb6j0011qp17xip7ekos",
          "status": "opened",
          "createdAt": 1701034057842,
          "updateAt": 1701034057842,
          "prefilledVariables": {
            "remoteJid": "551199991234@s.whatsapp.net",
            "pushName": "Moises",
            "instanceName": "teste"
          }
        },
        {
          "remoteJid": "status@broadcast",
          "sessionId": "4366789457-clpg0jjq70012qp17jmxhc8ql",
          "status": "opened",
          "createdAt": 1701035375282,
          "updateAt": 1701035375282,
          "prefilledVariables": {
            "remoteJid": "status@broadcast",
            "pushName": "João",
            "instanceName": "teste"
          }
        }
      ]
    }
  }
}
```
![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/7cd21421-0a3e-4773-aadd-f77d03173263)

O correto seria ele apenas retornar:

```
{
  "typebot": {
    "instanceName": "teste",
    "typebot": {
      "enabled": true,
      "url": "https://typebotapi.site.com.br",
      "typebot": "atendimento",
      "expire": 30,
      "keyword_finish": "#sair",
      "delay_message": 1500,
      "unknown_message": "Mensagem não suportada!",
      "listening_from_me": true,
}

```
Não sem porque ele retorna sempre as "sessions". Pois esse retorno das "sessions" também acontece de dentro do flow do N8N e não seta o POST enviado. 

![Sem título](https://github.com/EvolutionAPI/evolution-api/assets/81826268/c8b41d71-8c19-4f0f-bdf0-880255a26e01)

Estou utilizando o a seguinte estrutura, VPS com Ubuntu 20.04 > Docker Swarm > EvolutionApi v1.5.4 > Chatwoot v3.1.1 > Typeboot v2.18.0

**Comment by matheusmaiberg** [comment]
Tenta setar uma mensagem sem caracteres especiais e retorna aqui o resultado.

Troca #sair

Para somente sair

Outra coisa interessante pode ser ver se sua versão do typebot nao tem algum problema que pode ser o causador disso, como ela e uma versão bem antiga, tem pelo menos 60 dias de lancamento ja, ocorreram inumeras correcoes.
https://github.com/baptisteArno/typebot.io/releases

**Comment by matiasduartee** [comment]
@matheusmaiberg obrigado!

Atualizei a versão do Typebot e o problema não ocorreu mais, pode ser algum bug de versão sim. 

Porem depois de vários testes da execução do fluxo que seria para pausar o bot de WhatsApp quando uma conversa for iniciado pelo agente isso sim não funciona de forma alguma, pelo fluxo do n8n tem que ser executado duas vezes para que de fato pause o bot, sendo que se eu fizer o POST direto para a EvolutionAPI o pause ocorre de primeira. 

Essa é minha dor, pausar esse bot do Typebot quando uma conversa for iniciado pelo agente/atendente do Chatwoot.

**Comment by matheusmaiberg** [comment]
A solução seria passar a responsabilidade para a evolution então.

1. Crie um flow que ficara responsável por isso no seu n8n e crie um webhook. 
2. Ative o webhook na sua config ou enviroments da sua instalação da evolution e cole o endereco do wehook do n8n.
3. Configure os filtros compativeis com o que voce precisa.

Seria a solução mais rapida que me vem em mente.

**Comment by matiasduartee** [comment]
@matheusmaiberg pelo que fiquei sabendo isso seria um bug mesmo na EvolutionAPI, em criar essa sessão e ficar travada e vazia, o que eu consegui fazer foi passar via POST o seguinte código. 

`{
    "remoteJid": "status@broadcast",
    "status": "closed"
}`

Assim essa sessão vazia é finalizada.
