### ISSUE TITLE
Não consigo tirar a opção todos da caixa de entrada.

### ISSUE THREAD

**Issue by EduardoAldrimf** [EvolutionAPI/evolution-api#226]
Como eu posso tirar a parte "Todos" da caixa de entrada do chatwoot? Não quero que todos tenham acesso às mensagens, quero que um setor não consiga ver as mensagens de outro setor.
![image](https://github.com/EvolutionAPI/evolution-api/assets/152108577/ca31da1a-3ae4-4f4e-ab68-2900698d190e)

**Comment by bee360** [comment]
Alguém já fez isso e tem disponível? Eu queria que agentes não tivessem acesso a aba todos.

**Comment by matheusmaiberg** [comment]
Infelizmente isso só será possivel personalizando a imagem você mesmo, ou pode solicitar a personalização via workana para um profissional.

**Comment by megalhoes** [comment]
> Infelizmente isso só será possivel personalizando a imagem você mesmo, ou pode solicitar a personalização via workana para um profissional.
> 
> Também há planos de mudanças na proxima atualização na forma que permissões funcionam no Chatwoot.
> 
> Porém esta atrasado o issue la no Repositorio do Chatwoot, a previsão era para ter um merge na ultima atualização mas parece que foi adiado, dessa forma você dependeria da implementação deles.

tem ideia de quando isso será alterado? preciso ocultar as conversas que não forem atribuidas ao agente mesmo que por gambiarra atualmente.

**Comment by dpaes** [comment]
Caso alguém pergunte novamente sobre isso, deixo a issue do chatwoot para pesquisarem que fala sobre permissões de visualização que é o assunto da issue: https://github.com/chatwoot/chatwoot/issues/4216
