### ISSUE TITLE
Opção de responder mensagem especifica viu chatwoot

### ISSUE THREAD

**Issue by edgardjnr** [EvolutionAPI/evolution-api#227]
Com a atualização do chatwoot, poderiam incluir a opção de responder mensagens.

**Comment by codephix** [comment]
Opa Edgar
para resposta do chatwoot 3.2.0 fiz o seguinte.

no arquivo
src/whatsapp/services/chatwoot.service.ts

Apos a linha 1047

        if (body.content_attributes.in_reply_to){
          var idResposta = (body.content_attributes.in_reply_to-1);
          var conversationId = body.conversation.contact_inbox.inbox_id;
          let config = {
            method: 'get',
            maxBodyLength: Infinity,
            url: `${this.provider.url}/api/v1/accounts/${this.provider.account_id}/conversations/${conversationId}/messages?after=` + idResposta,
            headers: {
              'api_access_token': this.provider.token
            }
          };
          try {
            const { data } = await axios.request(config);
            if (data.payload[0] && data.payload[0].id == body.content_attributes.in_reply_to) {
              formatText = formatText +`\n\nResposta à: \n` + data.payload[0].content + ``;
            }
            this.logger.verbose('data sent');
          } catch (error) {
            this.logger.error(error);
          }
        }

Ai ele adiciona como exemplo

Max Alex:
Tudo bem

Resposta à: 
olá

**Comment by ronnybrendo** [comment]
tentei dessa forma mas pra min não funcionou, teria algo a mais para tentar?

**Comment by DavidsonGomes** [comment]
Estamos estudando essa nova função!
