### ISSUE TITLE
Bug: Quando terceiro usa a função responder mensagem Chatwoot ignora a mensagem do terceiro

### ISSUE THREAD

**Issue by matheusmaiberg** [EvolutionAPI/evolution-api#229]
Tentei procurar se houve merge na develop para resolver o erro mas não sei dizer se houve correção já.

Mensagem vinda do Whatsapp usando a função responder:
![Imagem do WhatsApp de 2023-11-30 à(s) 11 19 35_81040608](https://github.com/EvolutionAPI/evolution-api/assets/119268809/572b54bb-1841-431a-abf4-6539e357c7d1)

Comportamento da mensagem nao refletido no Chatwoot e mensagem foi completamente ignorada:
![Imagem do WhatsApp de 2023-11-30 à(s) 11 20 24_7587bf9b](https://github.com/EvolutionAPI/evolution-api/assets/119268809/baa914a0-47f4-4f7b-8678-1861886cd8e8)

Aparentemente o Chatwoot ignora totalmente as mensagens relativas a resposta.

Nesse caso especifico ele ignorou a mensagem Autorizado, e somente prosseguiu a mostrar as mensagens que não foram provenientes da função resposta do WhatsApp.

**Comment by matheusmaiberg** [comment]
Ativei algumas funções e esta funcionando agora, vou deixar de referencia para pessoas com o mesmo problema no futuro:

### Chatwoot
[ x ] Reopen Conversation 

### Settings
[ x ] Always Online
[ x ] Read Status

Não sei se pode ter algo a ver ou era um bug da minha instancia, porem ela corre em Docker com a imagem v1.5.4 sem mudança nenhuma na imagem.

**Comment by MPteste** [comment]
@matheusmaiberg Onde você fez essas configurações?

**Comment by capssantos** [comment]
Olá boa tarde,

@matheusmaiberg
Consegue dar mais detalhes nessa configuração por favor? Também estou com a mesma dificuldade.

@MPteste
Conseguiu?

Obrigado.

**Comment by matheusmaiberg** [comment]
> Olá boa tarde,
> 
> @matheusmaiberg Consegue dar mais detalhes nessa configuração por favor? Também estou com a mesma dificuldade.
> 
> @MPteste Conseguiu?
> 
> Obrigado.

## Solução pra mim
Basicamente eu só ativei algumas opções na config da sessão, segue print.

![image](https://github.com/EvolutionAPI/evolution-api/assets/119268809/1097804a-0897-440b-9028-e9765a27d541)
