### ISSUE TITLE
Error 502 Bad Gateway

### ISSUE THREAD

**Issue by stgcompany** [EvolutionAPI/evolution-api#230]
De vez em quando a api do evolution ta caindo dando um erro 502 e com pouco tempo depois volta ao normal, mas ao passar de um tempo dá erro de novo. Não entendo porque e não vejo nenhum padrão, só sei que de vez em quando está dando isso e muitas vezes não está sendo enviado ou recebendo mensagens, o que é um problema crítico. Segue alguns exemplos de quando esse erro aconteceu:

![image](https://github.com/EvolutionAPI/evolution-api/assets/143809393/78de7e8d-7eac-457b-965f-110418f856cc)
![image](https://github.com/EvolutionAPI/evolution-api/assets/143809393/38f37f68-a002-4ff3-b36d-3360224c6854)
![Screenshot from 2023-11-30 15-23-21](https://github.com/EvolutionAPI/evolution-api/assets/143809393/a5770c3f-a93a-4ef9-b014-bf3d9d177052)

Segue abaixo algumas configs do env.yml:

![a](https://github.com/EvolutionAPI/evolution-api/assets/143809393/62cbd695-7b1f-4c67-965b-d6b2e4db4fa3)

Segue abaixo a forma como configurei o proxy reverso com nginx e certbot:

![image](https://github.com/EvolutionAPI/evolution-api/assets/143809393/876c1fa3-2956-4469-b021-62a300e19a87)

Já cheguei a desabilitar o proxy do cloudflare e já cheguei a reiniciar o processo no pm2 mas não mudou, inclusive depois disso começou a ficar mais frequente o erro. Estou usando a versão 1.5.4 numa vps ubuntu 20.04 e isso só começou a acontecer de uns dias atrás pra cá. Antes estava tudo normal. Alguém já passou por isso e sabe a solução? Ou terei que reinstalar o evolution pra ver se resolve?

**Comment by stgcompany** [comment]
Verifiquei aqui que quando eu faço um bad request com erro 400, por exemplo enviando um texto ao invés de um número do remoteJid, o processo do evolution cai e volta alguns segundos depois. Amanhã verei melhor os logs para tentar entender mais sobre este erro

**Comment by DavidsonGomes** [comment]
Esse erro acontece quando o container da evolution cai, passe prints do erro gerado no log da evolution para tratarmos isso

**Comment by stgcompany** [comment]
No meu caso eu subi o evolution com PM2 e vi que toda vez que dava um erro de um request o processo do evo era reiniciado e nesse meio tempo a api ficava off e perdia as mensagens e qualquer outro request na api. Acabei comentando as linhas de código que derrubavam o processo quando acontecia erro, e com isso a api não cai quando é feito um bad request. E até agora os poucos testes que fiz não tive esse problema mais.

![image](https://github.com/EvolutionAPI/evolution-api/assets/143809393/e4ae4978-7897-4eed-9631-22761219b532)

Porém teve uma segunda coisa que fiz que vi pelo `pm2 log`, que infelizmente não lembrei de tirar print pra mostrar aqui. Que era que ele mostrava uma mensagem de erro ao tentar iniciar uma sessão do typebot numa das minhas instâncias. E dava erro porque o typebot não foi configurado com URL e tudo mais. O mais estranho é que não lembro de ter ativado essa instância em específico para o typebot, então fui lá no postman e desabilitei. Creio que talvez isso possa ter sido o problema/solução.

**Comment by DavidsonGomes** [comment]
Entendi, vou fazer essa correção
