### ISSUE TITLE
sendMessage não retorna nada mas envia a mensagem

### ISSUE THREAD

**Issue by suissa** [EvolutionAPI/evolution-api#231]
Estou com um problema que não estou recebendo nada da rota sendMessage mas a msg é enviada pro WhatsApp

Alguém já teve esse problema e pode me dar uma luz?

**Comment by DavidsonGomes** [comment]
Se puder mostrar como as informações da requisição para simular aqui e tentar reproduzir

**Comment by DavidsonGomes** [comment]
Por inatividade essa issue sera fechada, se necessario reabra
