### ISSUE TITLE
API alterando nome de arquivos quando chega no Chatwoot e suporte para ZIP e RAR

### ISSUE THREAD

**Issue by luiztonucci** [EvolutionAPI/evolution-api#232]
@DavidsonGomes, bom dia. 

Teria como a API não alterar o nome dos arquivos? Entendo que seja um questão de tratamento do arquivo dentro da API, mas pra quem usa o CW e recebe esse tipo de arquivo fica meio complicado entender o conteúdo. E não sei se a API tem suporte pra enviar extensão ZIP e RAR para o chatwoot, mas pelos testes que fiz, parece que não, chega como extensão ".false", não sei se é devido a troca de nome que ocorre isso. 

![testes_tipo_arquivo](https://github.com/EvolutionAPI/evolution-api/assets/82972632/58ae5290-ef9a-41ff-b960-1d68c4c2ac8f)

Att.
Luiz

**Comment by DavidsonGomes** [comment]
Vamos analisar a possibilidade

**Comment by jaison-x** [comment]
@luiztonucci, estes problemas foram corrigidos neste PR #334. Favor testar e retornar para sabermos se está tudo OK.

**Comment by DavidsonGomes** [comment]
Resolvido na 1.6.2 atualmente em desenvolvimento

**Comment by luiztonucci** [comment]
Testado e resolvido na 1.6.2 homolog, manteve o nome e agora suporta ZIP e RAR, 

![test_name_file](https://github.com/EvolutionAPI/evolution-api/assets/82972632/2e6cc81d-dabd-4365-a5a7-04baff56e904)

obrigado.

**Comment by luiztonucci** [comment]
Olá, testado e resolvido na 1.6.2 homolog, manteve o nome e agora suporta ZIP/RAR.

![test_name_file](https://github.com/EvolutionAPI/evolution-api/assets/82972632/19c939e6-657e-4c5b-b24c-72c3a698cd12)

Obrigado.
