### ISSUE TITLE
Qual a versão mais estável?

### ISSUE THREAD

**Issue by MattCarneiro** [EvolutionAPI/evolution-api#235]
Fala galera, beleza?
Como essa última versão estou enfrentando muitos bugs. Alguém pode me dizer qual a versão mais estável da API?
Não precisa ter integração com Typebot nem Chatwoot. Desde que envie os webhooks, não suma as mensagens nem as duplique e não dê erro de No Sessions.

**Comment by jaison-x** [comment]
Na minha opinião o principal problema não é a api em si mas a estrutura que o pessoal coloca a api. Existem bugs sim, porém a maioria vai no formato mais simples e usa a api sem redis, ou então, sem usar o mongo. Com isso a api usa disco local para funcionar (salvar dados da sessão, mensagens, chats...) e a maioria dos problemas está relacionado com isso. E essa questão nem está relacionada com a api em si. São problemas que já vem da baileys.

 Tente ler e entender como a api funciona que você vai ter uma visão melhor da coisa.

**Comment by MattCarneiro** [comment]
Eu uso mongo + redis. Todo dia eu acho um bug novo. Como eu só uso integrado ao whatsapp mesmo, queria saber se as versões mais antigas são mais estáveis, pra eu voltar. Pq ultimamente tá impossível colocar qualquer versão do evolution em produção.

**Comment by matheusmaiberg** [comment]
O trabalho que o Davidson fez é sensacional, porém tem alguns problemas que dependem dele e acredito que ele não tem o tempo necessário pra lidar com o projeto no momento.

Então sua alternativa mais fácil seria ir migrar pelo menos momentaneamente, a Wpp Connect talvez seja a melhor opção já que você não usa Typebot.

Da forma que vejo talvez você tenha algumas alternativas:
1. Testar outras versões pra seu uso
2. Corrigir você mesmo os bugs 
3. Tentar outro projeto
4. Criar sua API usando o Wweb.js por exemplo

Eu tenho algumas ideias sobre o projeto, gostaria de ajudar a monetizar o projeto porem não consegui contato com o Davidson em nenhum canal disponivel.

Acredito que se ele não achar uma forma de monetizar o projeto (enquanto mantem uma versão free pra comunidade), não vai fazer sentido seguir o projeto.

**Comment by matheusmaiberg** [comment]
> Infelizmente, eu não tenho conhecimento técnico pra corrigir os bugs. Eu também ajudaria o projeto financeiramente sem problemas algum. Acredito que uma assinatura de 997/ano pra instâncias e WhatsApp ilimitados seria um preço justo, desde que seja estável.

Sim, minha ideia seria algo assim, montar a estrutura e gerenciar a comunidade, infelizmente sou Junior em Javascript e não tenho tanto conhecimento técnico em questão de Programação, porem tenho muito conhecimento em modelos de negocios e monetização e SEO com minha empresa de Marketing.

Então queria unir essa expertise com ele e fornecer a infra pros usuários, melhorar a documentação e fazer um MVP para quem quer usar a API e monetizar com uma Enterprise Edition mantendo o Core do projeto com a API aberta pra quem quer ter acesso.

Assim teria como o projeto contratar mais pessoas pra desenvolver varias melhorias e ferramentas e integrações nativas com varios servicos que precisam de manutenção e atualizações com frequência, sem perder a essência do open source.

Tentei contato por todos os meios mas nem enviados os e-mails foram.

**Comment by matheusmaiberg** [comment]
Pensei em eu mesmo em forkar ela e seguir com outra linha, tenho o dominio é só uma questao do registro de marca e outras coisas juridicas.

Inclusive vi que o repo do @jaison-x está 31 commits a frente do main banch, eu estava pensando em usar seu próprio repo e voltar aos estudos pra entender tudo, porem seria um trabalho muito grande todas as responsabilidades.

Fora o roadmap de implementar o projeto novamente, modificar o codigo, fornecer imagens do docker, versionamento, regras de comunidade, recriação da documentação e tudo mais que engloba o projeto.

Pegar um projeto andando e reformar ele leva muito mais tempo e menos decisões que criar tudo novamente do zero, fora a audiência perdida.

Porém se for a única alternativa eu penso em realmente fazer isso, esse projeto é maravilhoso pra ficar tanto tempo parado e cheio de bugs assim.

**Comment by DavidsonGomes** [comment]
A versao mais estavel é a latest
