### ISSUE TITLE
Ao receber reações na mensagem, bot dispara automaticamente (typebot connector)

### ISSUE THREAD

**Issue by andrelsjunior** [EvolutionAPI/evolution-api#236]
Boa noite!

Quando conecto minha evolution no typebot, ao receber reações nas mensagens do fluxo, o bot automaticamente dispara a mensagem configurada no "typebot_unknown_message".

Tem como desabilitar?

**Comment by DavidsonGomes** [comment]
Vamos corrigir isso obrigado!

**Comment by DavidsonGomes** [comment]
Corrigido na versao 1.6.0
