### ISSUE TITLE
Chatwoot Duplicação de Mensagem/Contato + Log do Portainer, na API Versão Homolog

### ISSUE THREAD

**Issue by tizum** [EvolutionAPI/evolution-api#238]
Fiz uma instalação zerada do Chatwoot com Evolution API na versão 1.6.0 (Homolog) Após a live de ontem junto a promovaweb.

Meu setup ficou com MongoDB e RabbitMQ e Chatwoot Habilitados. 

Percebi que teve um contato que **duplicou mensagem e Contato no Chatwoot** com número diferente, porém inexistente com mesmo nome de contato.

Conferi o Celular, e realmente a mensagem era de um contato que tenho aqui.

Fiz a Analise no portainer para ver o Log, e tinha um Erro, justamente com o Número do Contato que deu problema no Chatwoot.

Salvei o Log Completo e também o Log das últimas 4 horas para Analise.

`2023/12/06 07:43AM 50 pid=1 hostname=evolutionlosj3bq key={"remoteJid":"1677782286@broadcast","fromMe":false,"id":"3033A9200216D65197A35FFD0494FD1C","participant":"554491475026@s.whatsapp.net"} err={"type":"PreKeyError","message":"Invalid PreKey ID","stack":"PreKeyError: Invalid PreKey ID\n    at SessionBuilder.initIncoming (/evolution/node_modules/libsignal/src/session_builder.js:66:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async 554491475026.0 [as awaitable] (/evolution/node_modules/libsignal/src/session_cipher.js:205:30)\n    at async _asyncQueueExecutor (/evolution/node_modules/libsignal/src/queue_job.js:20:29)","name":"PreKeyError"} msg=failed to decrypt message
2023/12/06 07:43AM 50 pid=1 hostname=evolutionlosj3bq key={"remoteJid":"1677782286@broadcast","fromMe":false,"id":"3033A9200216D65197A35FFD0494FD1C","participant":"554491475026@s.whatsapp.net"} err={"type":"Error","message":"No SenderKeyRecord found for decryption","stack":"Error: No SenderKeyRecord found for decryption\n    at 1677782286@broadcast::554491475026::0 [as awaitable] (/evolution/node_modules/@whiskeysockets/baileys/WASignalGroup/group_cipher.js:49:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async _asyncQueueExecutor (/evolution/node_modules/@whiskeysockets/baileys/WASignalGroup/queue_job.js:20:29)"} msg=failed to decrypt message
2023/12/06 07:43AM 50 pid=1 hostname=evolutionlosj3bq key={"remoteJid":"1677782286@broadcast","fromMe":false,"id":"3033A9200216D65197A35FFD0494FD1C","participant":"554491475026@s.whatsapp.net"} err={"type":"PreKeyError","message":"Invalid PreKey ID","stack":"PreKeyError: Invalid PreKey ID\n    at SessionBuilder.initIncoming (/evolution/node_modules/libsignal/src/session_builder.js:66:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async 554491475026.0 [as awaitable] (/evolution/node_modules/libsignal/src/session_cipher.js:205:30)\n    at async _asyncQueueExecutor (/evolution/node_modules/libsignal/src/queue_job.js:20:29)","name":"PreKeyError"} msg=failed to decrypt message`

![Chatwoot - Duplicação Contato 1](https://github.com/EvolutionAPI/evolution-api/assets/6773491/de3ccf74-497e-4b4b-93f7-4eee2b54e7a2)
![Chatwoot - Duplicação Contato 2](https://github.com/EvolutionAPI/evolution-api/assets/6773491/40435277-a604-4959-8b44-2dc5a4890fbc)

O Número Real do contato que enviou mensagem é:  554491475026

Obs: é um mercado aqui da cidade, e provavelmente estou na lista de transmissão, recebendo as ofertas

Log Última 4 horas:
[_evolutionlosj3bq_evolutionlosj3bq.1.pl6b63cmvw2b9yjbilnw9udyw_logs.txt](https://github.com/EvolutionAPI/evolution-api/files/13581680/_evolutionlosj3bq_evolutionlosj3bq.1.pl6b63cmvw2b9yjbilnw9udyw_logs.txt)

Log Completo:
[_evolutionlosj3bq_evolutionlosj3bq.1.pl6b63cmvw2b9yjbilnw9udyw_logs_last4hours.txt](https://github.com/EvolutionAPI/evolution-api/files/13581679/_evolutionlosj3bq_evolutionlosj3bq.1.pl6b63cmvw2b9yjbilnw9udyw_logs_last4hours.txt)

**Comment by DavidsonGomes** [comment]
Vamos analisar, ao meu ver ja parece ser um dos casos do novo formato de whatsapp.

**Comment by tizum** [comment]
> Já cheguei a ver esse tipo de erro também. Parece que a baileys envia um formato de mensagem diferente quando você recebe um broadcast de alguém. Imagino que a pessoa esteja enviando a mensagem para uma lista de transmissão ou algo do tipo. A cada envio dela vai acontecer isso. Serão criados novos contatos com ids diferentes. Realmente parece ser um bug.

Exatamente, é uma lista de transmissão mesmo, vou acompanhar de outros, acredito que devo receber de mais de um durante o longo da semana.

**Comment by DavidsonGomes** [comment]
Problema ja resolvido na versao 1.6.0
