### ISSUE TITLE
Chatwoot - Detectado um Padrão de Perca de Mensagem em Grupo

### ISSUE THREAD

**Issue by tizum** [EvolutionAPI/evolution-api#239]
Estou analisando a fundo o que pode causar erro na Evolution com Chatwoot para colocaborar no Desenvolvimento, estou usando versão Homolog.

Analisando mensagem por mensagem em um Grupo, percebi que uma pessoa que está enviando mensagens com Assinatura do atendente, ela perde e não chega no Chatwoot conectado.

![Chatwoot 3 - Perca de Mensagem no Grupo ](https://github.com/EvolutionAPI/evolution-api/assets/6773491/ab001aa7-430b-42e7-a271-caba5b813dd9)

![Bug Mensagem Chatwoot](https://github.com/EvolutionAPI/evolution-api/assets/6773491/e9c101f1-a11e-4aa4-9a1d-76d2d58a05c3)

Ao ver o Log, constatei que há um erro pro mesmo número que enviou a mensagem assinada.

`2023/12/06 08:31AM 50 pid=1 hostname=evolutionlosj3bq key={"remoteJid":"120363148294224773@g.us","fromMe":false,"id":"36-61-601671","participant":"557998178275:53@s.whatsapp.net"} err={"type":"Error","message":"No SenderKeyRecord found for decryption","stack":"Error: No SenderKeyRecord found for decryption\n    at 120363148294224773@g.us::557998178275::53 [as awaitable] (/evolution/node_modules/@whiskeysockets/baileys/WASignalGroup/group_cipher.js:49:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async _asyncQueueExecutor (/evolution/node_modules/@whiskeysockets/baileys/WASignalGroup/queue_job.js:20:29)"} msg=failed to decrypt message
2023/12/06 08:32AM 50 pid=1 hostname=evolutionlosj3bq key={"remoteJid":"120363150229913250@g.us","fromMe":false,"id":"42198B5581DF7923B1","participant":"554799602241:8@s.whatsapp.net"} err={"type":"Error","message":"No SenderKeyRecord found for decryption","stack":"Error: No SenderKeyRecord found for decryption\n    at 120363150229913250@g.us::554799602241::8 [as awaitable] (/evolution/node_modules/@whiskeysockets/baileys/WASignalGroup/group_cipher.js:49:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async _asyncQueueExecutor (/evolution/node_modules/@whiskeysockets/baileys/WASignalGroup/queue_job.js:20:29)"} msg=failed to decrypt message
2023/12/06 08:34AM 50 pid=1 hostname=evolutionlosj3bq key={"remoteJid":"120363148294224773@g.us","fromMe":false,"id":"36-61-601695","participant":"557998178275:53@s.whatsapp.net"} err={"type":"Error","message":"No SenderKeyRecord found for decryption","stack":"Error: No SenderKeyRecord found for decryption\n    at 120363148294224773@g.us::557998178275::53 [as awaitable] (/evolution/node_modules/@whiskeysockets/baileys/WASignalGroup/group_cipher.js:49:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async _asyncQueueExecutor (/evolution/node_modules/@whiskeysockets/baileys/WASignalGroup/queue_job.js:20:29)"} msg=failed to decrypt message
2023/12/06 08:40AM 50 pid=1 hostname=evolutionlosj3bq key={"remoteJid":"120363148294224773@g.us","fromMe":false,"id":"36-61-601707","participant":"557998178275:53@s.whatsapp.net"} err={"type":"Error","message":"No SenderKeyRecord found for decryption","stack":"Error: No SenderKeyRecord found for decryption\n    at 120363148294224773@g.us::557998178275::53 [as awaitable] (/evolution/node_modules/@whiskeysockets/baileys/WASignalGroup/group_cipher.js:49:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async _asyncQueueExecutor (/evolution/node_modules/@whiskeysockets/baileys/WASignalGroup/queue_job.js:20:29)"} msg=failed to decrypt message`

**Comment by DavidsonGomes** [comment]
Foi falado isso em live ontem, estamos procurando uma solução para grupos
