### ISSUE TITLE
BUG: Ao criar instância com 'chatwoot_conversation_pending' o gerador de qr não funciona

### ISSUE THREAD

**Issue by stgcompany** [EvolutionAPI/evolution-api#243]
Tava lidando com um erro aqui onde o contato de Gerador de QR Code não tava funcionando e depois de um tempo descobri o que era.

Eu estava criando uma instância com Chatwoot onde as novas conversas eram criadas como pendentes (`chatwoot_conversation_pending: true`), e isso era realmente minha intenção, só que o problema é que quando a conversa com o gerador de qr code era criada, ela era criada como pendente e dessa forma o evolution não conseguia identificar a conversa pra tá enviando os qr codes e tudo mais.

Segue uma print do `pm2 log`:

![Screenshot from 2023-12-07 15-28-15](https://github.com/EvolutionAPI/evolution-api/assets/143809393/9ea36d2b-788d-44b2-9843-a33670fb98ea)

Acredito que seja importante modificar isto para que ele identifique mesmo quando a conversa esta pendente, OU sempre abrir a conversa com o gerador de qr como aberta independente da opção `chatwoot_conversation_pending` estiver ativa ou não, sendo apenas as outras conversas que virão da API que serão de acordo com esta config.

**Comment by DavidsonGomes** [comment]
Problema ja resolvido na versao 1.6.0
