### ISSUE TITLE
[bug] Versão develop (V1.6.0) , Não gera QrCode no Chatwoot. Tenho que gerar pelo manager/postman

### ISSUE THREAD

**Issue by francisbreit** [EvolutionAPI/evolution-api#246]
O Qrcode, não é gerado dentro do Chatwoot ao ser criada a caixa de entrada e instancia com o comando start:nome_da_caixa. A instancia é criada como closed (fechada) e para ler o qrcode só externamente ao Chatwoot, pois no Chatwoot o comando iniciar não é aceito

**Comment by DavidsonGomes** [comment]
Essa semana estarei testando o fluxo completo com o chatwoot

**Comment by DavidsonGomes** [comment]
Problema ja resolvido na versao 1.6.0

**Comment by lscorrea** [comment]
Problema continua na versão V1.6.1 e chatwoot v3.5.2 Build 608592db0c11db142c9a281d1d34b715ad33d6c0 hoje é 26/jan/24 quais versões recomendam que esteja estável tanto do EvolutionApi quanto do ChatWoot.

Obrigado!
