### ISSUE TITLE
[FEATURE] (Change Typebot Session Status: paused) não funciona quando a sessão não existe

### ISSUE THREAD

**Issue by stgcompany** [EvolutionAPI/evolution-api#251]
#### Situação Problema:
Quando uma nova conversa é criada no Chatwoot **pelo agente**, e vou tentar pausar o chatbot (Typebot) naquele contato através do n8n fazendo um POST `{{baseUrl}}/typebot/changeStatus/{{instance}}` como `paused`, nada muda - pelo fato de a sessão nem existir em primeiro lugar - visto que foi o usuário do Chatwoot que iniciou a conversa e não o contato que mandou uma mensagem.

#### Solução Gambiarra:
Tive que startar uma sessão do typebot naquele contato (onde a primeira etapa é pegar uma mensagem, então o chatbot não chega a interferir na conversa) para logo em seguida, através da sessão criada, poder pausar o chatbot / typebot.

#### Solução Ideal:
Poder criar uma sessão já com a definição do `status: "paused"` através da requesição POST já existente em `{{baseUrl}}/typebot/start/{{instance}}`, sendo apenas necessário a adição desta variável no body para realizar devida ação necessária visto a importância de o chatbot não interferir na conversa iniciada pela empresa ao contato.

**Comment by DavidsonGomes** [comment]
Não entendi muito bem o caso de uso, pq ja iniciar como paused e nao iniciar no momento correto ja diretamente?

**Comment by stgcompany** [comment]
A ideia é que quando um atendente iniciar a conversa com um contato pelo chatwoot, o typebot não deve ser ativado quando o contato responder a mensagem, porque dessa forma ele iria interferir na conversa já iniciada pelo atendimento humano da empresa, pulando a necessidade de ter um chatbot no início, para conversas iniciadas pela empresa claro.

No meu flow do typebot (conectado nessa instância) eu começo com um menu de escolha de qual setor o contato deseja falar, mas no caso de a própria empresa querer começar uma conversa com o contato, não faz sentido eu querer 'startar' esse flow no contato, já que o motivo da conversa veio da empresa e não do contato.

Espero ter passado bem o motivo da necessidade de pausar uma sessão que não existia para aquele contato.

**Comment by DavidsonGomes** [comment]
Messe caso voce pode usar o startTypebot quando precisar realmente iniciar o bot para aquele contato

**Comment by stgcompany** [comment]
Mas a questão é que eu PRECISO pausar o typebot pra aquele contato em específico (que não tem uma sessão iniciada), porque se eu não fizer isso o typebot vai interferir na conversa que foi iniciada pelo atendente da empresa e não pelo contato em si.

Ai por este motivo no momento estou dando o start typebot pra logo em seguida pausar, sendo uma gambiarra que funciona para mim por enquanto kk.

**Comment by DavidsonGomes** [comment]
Nao precisa ter o typebot setado para usar startTypebot.

**Comment by DavidsonGomes** [comment]
Por inatividade essa isseu sera fechada, caso necessario reabra

**Comment by klevys** [comment]
Olá. Estou com o mesmo problema. Consigo desligar. Mas quando ligo o bot novamente ele fica em loop na primeira frase do BOT. Como resolver?

**Comment by johnnysaito** [comment]
Fala pessoal bl, consegui fazer assim.

api: suaapievolution.com.br/typebot/changeStatus/suasessaodoevolution
precisa da sua autenticacao:

body:
{
    "remoteJid": "identifier ", 
    "status": "paused" 
}   

o Status pausado é para parar o bot, e tem o closed que é para fechar a sess!ao e inicar uma nova.
Ex:
identifier: 5541899888866@s.whatsapp.net numero neste formato

Espero ter ajudado.
