### ISSUE TITLE
erro com mongoBD

### ISSUE THREAD

**Issue by edgardjnr** [EvolutionAPI/evolution-api#252]
Não é possivel setar as configurações do chatwoot em mais de uma sessão pelo manager.

**Comment by edgardjnr** [comment]
evolution 1.5.4 .... chatwooot versão 3.3.1

**Comment by DavidsonGomes** [comment]
Detalhes ja estao sendo trabalhados com o novo manager e atualização para o chatwoot, ja esta disponivel para testes da branch develop ou na imagem do docker atendai/evolution-api:homolog
