### ISSUE TITLE
Após atualizar para v1.5.4 parou de enviar imagem no App do WhatsApp

### ISSUE THREAD

**Issue by makmortifera** [EvolutionAPI/evolution-api#254]
Estou utilizando a API Evolution v1.5.2 instalada junto com o Typebot Latest e está funcionando tudo certo, as mensagens de texto, imagem e vídeo são enviadas corretamente tanto no WhatsApp Web quando no App do WhatsApp.

Ao atualizar a Evolution API pra V1.5.4, as imagens e vídeos enviadas aparecem no WhatsApp Web, mas no aplicativo não aparece.

Percebi que ao utilizar a v1.5.2 a mensagem sai com (mimetype: 'image/png') e a v1.5.4 sai com (mimetype: 'application/octet-stream').

Obs1: Não cheguei a testar a v1.5.3, fui direto da v1.5.2 para a v1.5.4
Obs2: Acabei de atualizar para a v1.6.0 e continua o mesmo problema
Obs3: Só de voltar para a v1.5.2 volta a funcionar normalmente

```
[Evolution API]  v1.5.4  1   -  Tue Dec 12 2023 15:05:42     LOG   [WAStartupService]  [object]
{
  key: MessageKey {
    remoteJid: '55XXXXXXXXXX@s.whatsapp.net',
    fromMe: true,
    id: 'BAE5FFD8E30B2D31'
  },
  pushName: '',

  message: {
    imageMessage: ImageMessage {
      interactiveAnnotations: [],
      scanLengths: [],
      url: 'https://mmg.whatsapp.net/o1/v/t62.7118-24/f1/m232/up-oil-image-96844abc-03aa-4fd1-9017-c88e4c127e01?ccb=9-4&oh=01_AdSeva5v7Vw81ZuzmEp0ZYrWL4WI4osrDzdtOFjtgk-J3g&oe=65A00FEA&_nc_sid=000000&mms3=true',
      mimetype: 'application/octet-stream',
      fileSha256: <Buffer d6 7b 41 5a f2 91 16 bd 16 82 d9 cf 93 f4 14 1a 06 7b e7 d9 ad d7 64 42 ff 7f cc c7 56 6c 93 22>,
      fileLength: [Long],
      height: 549,
      width: 802,
      mediaKey: <Buffer ff 5d 41 d5 4a 76 77 61 6b c5 aa 0f 63 ff 6c d6 ac 72 1d c2 a1 46 7c 07 3e 60 1c 50 8e 45 70 fa>,
      fileEncSha256: <Buffer f2 41 a6 99 ed e5 67 7f 95 2b 6c f6 a7 0d 6b 0a 1f f8 0f 2f 29 65 f8 a7 1d 6c f2 86 04 5f eb 8a>,
      directPath: '/o1/v/t62.7118-24/f1/m232/up-oil-image-96844abc-03aa-4fd1-9017-c88e4c127e01?ccb=9-4&oh=01_AdSeva5v7Vw81ZuzmEp0ZYrWL4WI4osrDzdtOFjtgk-J3g&oe=65A00FEA&_nc_sid=000000',
      mediaKeyTimestamp: [Long],
      jpegThumbnail: <Buffer ff d8 ff db 00 43 00 10 0b 0c 0e 0c 0a 10 0e 0d 0e 12 11 10 13 18 28 1a 18 16 16 18 31 23 25 1d 28 3a 33 3d 3c 39 33 38 37 40 48 5c 4e 40 44 57 45 37 ... 458 more bytes>,
      contextInfo: {}
    }
  },
  messageType: 'imageMessage',
  messageTimestamp: Long { low: 1702404342, high: 0, unsigned: true },
  owner: 'LEADS-3M',
  source: 'web'
}
``` 
![1](https://github.com/EvolutionAPI/evolution-api/assets/80240659/04f24807-2993-4b55-aadf-31181fdb9ce5)
![2](https://github.com/EvolutionAPI/evolution-api/assets/80240659/482e99e0-e8a1-4d63-a783-4751bd0ef7d2)
![3](https://github.com/EvolutionAPI/evolution-api/assets/80240659/646d5bd7-ab86-4fde-899b-0be955931ed9)

**Comment by makmortifera** [comment]
Estou usando o minio para fazer o upload das mídias e o link não termina com .jpg ou .png

https://minioapi.dominio.com.br/typebot/public/workspaces/clorg99it0001pd1ceodqu2a7/typebots/clpimz1hf000bqv1ckd1u64ls/blocks/wmzxviwi9eo9icpb7nok2stm?v=1702404299340

![Screenshot_1](https://github.com/EvolutionAPI/evolution-api/assets/80240659/4ae84f0e-bab0-46ef-80c0-5c1232f1f758)

Ao colocar um link de uma imagem que termina com .jpg a imagem foi enviada tanto no WhatsApp Web, quanto no App do WhatsApp.

**Comment by DavidsonGomes** [comment]
Isso mesmo, o problema é que como o minio/s3 nao envia a url com o nome do arquivo a api nao consegue saber o mimetype, ja estamos vendo essa correção, na verao 1.5.2 era setado direto isso, mas gerou outros problemas por isso retiramos

**Comment by makmortifera** [comment]
Certo, vou alterar os links das minhas imagens.

Obrigado.

**Comment by williamzzz1** [comment]
@DavidsonGomes estou com a evolution 1.6.0 e acontecendo o mesmo problema. Resolvi colocando ".jpg" no final do arquivo!
