### ISSUE TITLE
v1.6.0 não está pegando o pushName, nem o remoteJid.

### ISSUE THREAD

**Issue by makmortifera** [EvolutionAPI/evolution-api#255]
v1.6.0 não está pegando o pushName, nem o remoteJid no meu sistema.

![Screenshot_4](https://github.com/EvolutionAPI/evolution-api/assets/80240659/b37be4fe-0fae-4154-a174-3164e11177c2)

msg: legal
```
[Evolution API]  v1.6.0  1   -  Tue Dec 12 2023 23:05:48     LOG   [WAStartupService]  [object]   
{
  key: MessageKey {
    remoteJid: '55XXXXXXXXX@s.whatsapp.net',
    fromMe: true,
    id: 'BAE50AD6D9EB9EC9'
  },
  pushName: '',
  message: { extendedTextMessage: ExtendedTextMessage { text: 'Legal' } },
  messageType: 'extendedTextMessage',
  messageTimestamp: Long { low: 1702433148, high: 0, unsigned: true },
  owner: 'LEADS-3M',
  source: 'web'
} 
```

Era pra retornar o pushName
```
[Evolution API]  v1.6.0  1   -  Tue Dec 12 2023 23:05:49     LOG   [WAStartupService]  [object]   
{
  key: MessageKey {
    remoteJid: '5514996505729@s.whatsapp.net',
    fromMe: true,
    id: 'BAE59909C18F4644'
  },
  pushName: '',
  message: { extendedTextMessage: { text: '', contextInfo: {} } },
  messageType: 'extendedTextMessage',
  messageTimestamp: Long { low: 1702433149, high: 0, unsigned: true },
  owner: 'LEADS-3M',
  source: 'web'
} 
 ```
 
 Era pra retornar o remoteJid
 ```
 [Evolution API]  v1.6.0  1   -  Tue Dec 12 2023 23:05:51     LOG   [WAStartupService]  [object]   
{
  key: MessageKey {
    remoteJid: '5514996505729@s.whatsapp.net',
    fromMe: true,
    id: 'BAE5CA8F0B65D48A'
  },
  pushName: '',
  message: { extendedTextMessage: { text: '', contextInfo: {} } },
  messageType: 'extendedTextMessage',
  messageTimestamp: Long { low: 1702433151, high: 0, unsigned: true },
  owner: 'LEADS-3M',
  source: 'web'
} 
  ```

**Comment by matiasduartee** [comment]
Está acontecendo comigo também exatamente a mesma coisa! 

Evolution Versão: 1.6.0
Typebot Versão: 2.19.1

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/434a0bba-3c80-4070-99ae-4fe97b1efeef)

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/095710f2-9be7-43e0-b097-5d274cc31627)

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/e9b86f07-50b7-4693-bbc9-2a51f1a9bb37)

Executei o teste na Evolution Versão: 1.5.4, e consegui capturar o remoteJid e a variável armazenada {{nome2}}, porém o {{pushName}} não veio. 

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/d482e006-5ffb-49a5-90cc-e254c9b1ef82)

**Comment by DavidsonGomes** [comment]
Estamos trabalhando para corrigir!

**Comment by matiasduartee** [comment]
@dersonbsb2022 tem relação sim amigo! O @DavidsonGomes já esta trabalhando na correção.

**Comment by daniloruizdasilva** [comment]
@DavidsonGomes, faltou adicionar esses parâmetros no arquivo ENV de exemplo.

    **- SERVER_TYPE=http
    - SERVER_PORT=8080**
Pessoal estavam reclamando que não conseguia subir a imagem, analisei as alterações no código, aí adicionei esses dois parâmetros e a imagem subiu.

**Comment by daniloruizdasilva** [comment]
> Consegui subir a homolog setando as variáveis:
> 
> * SERVER_TYPE=http
> * SERVER_PORT=8080
> * TYPEBOT_API_VERSION=latest
> * variáveis que o usuário digita (exemplo: digite o seu endereço) sendo repassadas OK!
> * remoteJid sendo repassado OK
> * pushName não esta sendo repassado.

No Typebot como está fazendo para colectar o que o usuário informou no WhatsApp?

**Comment by brunopinto123** [comment]
> > Consegui subir a homolog setando as variáveis:
> > 
> > * SERVER_TYPE=http
> > * SERVER_PORT=8080
> > * TYPEBOT_API_VERSION=latest
> > * variáveis que o usuário digita (exemplo: digite o seu endereço) sendo repassadas OK!
> > * remoteJid sendo repassado OK
> > * pushName não esta sendo repassado.
> 
> No Typebot como está fazendo para colectar o que o usuário informou no WhatsApp?

normal ué... rs
collect e nome da variavel... 
nada de diferente...

**Comment by brunopinto123** [comment]
> Consegui subir a homolog setando as variáveis:
> 
> * SERVER_TYPE=http
> * SERVER_PORT=8080
> * TYPEBOT_API_VERSION=latest
> * variáveis que o usuário digita (exemplo: digite o seu endereço) sendo repassadas OK!
> * remoteJid sendo repassado OK
> * pushName não esta sendo repassado.

atualização sobre o pushName:

se eu setar no fluxo do typebot uma variável "nome" = pushName e depois enviar a variável "nome", então realmente não funciona....

mas se eu não setar nenhuma variável, e simplesmente enviar um texto qualquer chamando a variável "pushName", então funciona...

Ou seja, não precisa setar nenhuma variável de pushName... Basta chamar ela no fluxo que funciona...

**Comment by daniloruizdasilva** [comment]
> > Consegui subir a homolog setando as variáveis:
> > 
> > * SERVER_TYPE=http
> > * SERVER_PORT=8080
> > * TYPEBOT_API_VERSION=latest
> > * variáveis que o usuário digita (exemplo: digite o seu endereço) sendo repassadas OK!
> > * remoteJid sendo repassado OK
> > * pushName não esta sendo repassado.
> 
> atualização sobre o pushName:
> 
> se eu setar no fluxo do typebot uma variável "nome" = pushName e depois enviar a variável "nome", então realmente não funciona....
> 
> mas se eu não setar nenhuma variável, e simplesmente enviar um texto qualquer chamando a variável "pushName", então funciona...
> 
> Ou seja, não precisa setar nenhuma variável de pushName... Basta chamar ela no fluxo que funciona...

Você está usando qual versão da EVO e do Typebot?

**Comment by matiasduartee** [comment]
> > Consegui subir a homolog setando as variáveis:
> > 
> > * SERVER_TYPE=http
> > * SERVER_PORT=8080
> > * TYPEBOT_API_VERSION=latest
> > * variáveis que o usuário digita (exemplo: digite o seu endereço) sendo repassadas OK!
> > * remoteJid sendo repassado OK
> > * pushName não esta sendo repassado.
> 
> atualização sobre o pushName:
> 
> se eu setar no fluxo do typebot uma variável "nome" = pushName e depois enviar a variável "nome", então realmente não funciona....
> 
> mas se eu não setar nenhuma variável, e simplesmente enviar um texto qualquer chamando a variável "pushName", então funciona...
> 
> Ou seja, não precisa setar nenhuma variável de pushName... Basta chamar ela no fluxo que funciona...


Repliquei o que nosso amigo @brunopinto123 disso e realmente funciona se passar simplesmente a variável {{pushName}}.

Lembrando que fiz o teste na versão homolog para Docker. 

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/c5ec10ed-71df-401c-b3a9-f74e4989e12f)

O fluxo de teste:

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/da140e16-f445-475a-afdd-8fd8e89c2720)

**Comment by fabianob1m** [comment]
Aqui também não buscou pushName e remoteJid . Também toda mensagem enviada só dá como mensagem não reconhecida. Ele só reconhece a primeira mensagem pra ativar o bot.
Fiz a ativação do typebot pelo novo manager. (ah, senti falta da opção de limpar a session do usuario).

![image](https://github.com/EvolutionAPI/evolution-api/assets/153868300/547e14fb-ec05-4fbb-ad03-7c9d58084d05)

**Comment by matiasduartee** [comment]
> Aqui também não buscou pushName e remoteJid . Também toda mensagem enviada só dá como mensagem não reconhecida. Ele só reconhece a primeira mensagem pra ativar o bot. Fiz a ativação do typebot pelo novo manager. (ah, senti falta da opção de limpar a session do usuario).
> 
> ![image](https://private-user-images.githubusercontent.com/153868300/290660361-547e14fb-ec05-4fbb-ad03-7c9d58084d05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1OTA5NjAsIm5iZiI6MTcwMjU5MDY2MCwicGF0aCI6Ii8xNTM4NjgzMDAvMjkwNjYwMzYxLTU0N2UxNGZiLWVjMDUtNGZiYi1hZDAzLTdjOWQ1ODA4NGQwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQyMTUxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTU3NDIxMDAwOGYzMWI3MThiNDBiMzFlMTFkODc5NmE5MTgyNWIzMWY1NzRiMzgzNWYzMDBmOTFkYWQxNmYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l1l1BMmwhpQgKLNfMgZjAvLMVI8yRwvkBd55nXE1xmQ)

@gabrielpastori1 será que em uma versão futura daria pra colocar ao set sessions no manager?

**Comment by dersonbsb2022** [comment]
onde que testa a versao homolog do docker, poderia me informar se possivel?

Grato.

**Comment by matiasduartee** [comment]
> onde que testa a versao homolog do docker, poderia me informar se possivel?
> 
> Grato.

https://hub.docker.com/r/atendai/evolution-api

**Comment by microprocessgit** [comment]
> > onde que testa a versão homóloga do docker, poderia me informar se possível?
> > Obrigado.
> 
> https://hub.docker.com/r/atendai/evolution-api

Eu estou utilizando essa imagem de homologação, porém está com um bug na citação de uma resposta via chatwoot.
![image](https://github.com/EvolutionAPI/evolution-api/assets/73668289/53b1116f-f375-4dc2-bd4d-fa5a5e503225)
![image](https://github.com/EvolutionAPI/evolution-api/assets/73668289/1f60b625-6724-4f54-aa32-c1f6a3256cb7)
![image](https://github.com/EvolutionAPI/evolution-api/assets/73668289/58e6f349-1318-44c0-9824-43a658f6ec20)

**Comment by wagnerra23** [comment]
{
  key: MessageKey {
    remoteJid: '554899872822@s.whatsapp.net',
    fromMe: true,
    id: 'BAE51E7B86B342B1'
  },
  pushName: '',

  message: {
    extendedTextMessage: ExtendedTextMessage { text: '*Wagner Rocha Araujo:*\ntabom' }
  },
  messageType: 'extendedTextMessage',
  messageTimestamp: Long { low: 1707565393, high: 0, unsigned: true },
  owner: '1Jana',
  source: 'web'
} 

O que é o Caractere de máquina depois do pushName ??? parece ser ele a causa do problema

**Comment by DAVIAMERICO242** [comment]
> v1.6.0 não está pegando o pushName, nem o remoteJid no meu sistema.
> 
> ![Screenshot_4](https://private-user-images.githubusercontent.com/80240659/290053612-b37be4fe-0fae-4154-a174-3164e11177c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5ODE1NDgsIm5iZiI6MTcxNTk4MTI0OCwicGF0aCI6Ii84MDI0MDY1OS8yOTAwNTM2MTItYjM3YmU0ZmUtMGZhZS00MTU0LWExNzQtMzE2NGUxMTE3N2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDIxMjcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZjUyMzQwMTg0Y2Q3ZTk1ODMyMjU4YWMxZWQ1MjNiNjc3YmFjN2VkMDE2YThiMDJjMjQwYTRkMmMzM2Y2ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OAF4kkH73NqXvFS9yYxsbsqPjzpnitRsAEU386lWPOY)
> 
> msg: legal
> 
> ```
> [Evolution API]  v1.6.0  1   -  Tue Dec 12 2023 23:05:48     LOG   [WAStartupService]  [object]   
> {
>   key: MessageKey {
>     remoteJid: '55XXXXXXXXX@s.whatsapp.net',
>     fromMe: true,
>     id: 'BAE50AD6D9EB9EC9'
>   },
>   pushName: '',
>   message: { extendedTextMessage: ExtendedTextMessage { text: 'Legal' } },
>   messageType: 'extendedTextMessage',
>   messageTimestamp: Long { low: 1702433148, high: 0, unsigned: true },
>   owner: 'LEADS-3M',
>   source: 'web'
> } 
> ```
> 
> Era pra retornar o pushName
> 
> ```
> [Evolution API]  v1.6.0  1   -  Tue Dec 12 2023 23:05:49     LOG   [WAStartupService]  [object]   
> {
>   key: MessageKey {
>     remoteJid: '5514996505729@s.whatsapp.net',
>     fromMe: true,
>     id: 'BAE59909C18F4644'
>   },
>   pushName: '',
>   message: { extendedTextMessage: { text: '', contextInfo: {} } },
>   messageType: 'extendedTextMessage',
>   messageTimestamp: Long { low: 1702433149, high: 0, unsigned: true },
>   owner: 'LEADS-3M',
>   source: 'web'
> } 
> ```
> 
> Era pra retornar o remoteJid
> 
> ```
> [Evolution API]  v1.6.0  1   -  Tue Dec 12 2023 23:05:51     LOG   [WAStartupService]  [object]   
> {
>  key: MessageKey {
>    remoteJid: '5514996505729@s.whatsapp.net',
>    fromMe: true,
>    id: 'BAE5CA8F0B65D48A'
>  },
>  pushName: '',
>  message: { extendedTextMessage: { text: '', contextInfo: {} } },
>  messageType: 'extendedTextMessage',
>  messageTimestamp: Long { low: 1702433151, high: 0, unsigned: true },
>  owner: 'LEADS-3M',
>  source: 'web'
> } 
> ```

eu corrigi um bug semelhante, você deve fazer as seguinte alterações no encapsulamento da variavel state:

![image](https://github.com/EvolutionAPI/evolution-api/assets/111699910/d0b4fa5d-3a04-43df-be5c-6c66df01408d)

**Comment by DAVIAMERICO242** [comment]
> > v1.6.0 não está pegando o pushName, nem o remoteJid no meu sistema.
> > ![Screenshot_4](https://private-user-images.githubusercontent.com/80240659/290053612-b37be4fe-0fae-4154-a174-3164e11177c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5ODE1NDgsIm5iZiI6MTcxNTk4MTI0OCwicGF0aCI6Ii84MDI0MDY1OS8yOTAwNTM2MTItYjM3YmU0ZmUtMGZhZS00MTU0LWExNzQtMzE2NGUxMTE3N2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDIxMjcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZjUyMzQwMTg0Y2Q3ZTk1ODMyMjU4YWMxZWQ1MjNiNjc3YmFjN2VkMDE2YThiMDJjMjQwYTRkMmMzM2Y2ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OAF4kkH73NqXvFS9yYxsbsqPjzpnitRsAEU386lWPOY)
> > msg: legal
> > ```
> > [Evolution API]  v1.6.0  1   -  Tue Dec 12 2023 23:05:48     LOG   [WAStartupService]  [object]   
> > {
> >   key: MessageKey {
> >     remoteJid: '55XXXXXXXXX@s.whatsapp.net',
> >     fromMe: true,
> >     id: 'BAE50AD6D9EB9EC9'
> >   },
> >   pushName: '',
> >   message: { extendedTextMessage: ExtendedTextMessage { text: 'Legal' } },
> >   messageType: 'extendedTextMessage',
> >   messageTimestamp: Long { low: 1702433148, high: 0, unsigned: true },
> >   owner: 'LEADS-3M',
> >   source: 'web'
> > } 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Era pra retornar o pushName
> > ```
> > [Evolution API]  v1.6.0  1   -  Tue Dec 12 2023 23:05:49     LOG   [WAStartupService]  [object]   
> > {
> >   key: MessageKey {
> >     remoteJid: '5514996505729@s.whatsapp.net',
> >     fromMe: true,
> >     id: 'BAE59909C18F4644'
> >   },
> >   pushName: '',
> >   message: { extendedTextMessage: { text: '', contextInfo: {} } },
> >   messageType: 'extendedTextMessage',
> >   messageTimestamp: Long { low: 1702433149, high: 0, unsigned: true },
> >   owner: 'LEADS-3M',
> >   source: 'web'
> > } 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Era pra retornar o remoteJid
> > ```
> > [Evolution API]  v1.6.0  1   -  Tue Dec 12 2023 23:05:51     LOG   [WAStartupService]  [object]   
> > {
> >  key: MessageKey {
> >    remoteJid: '5514996505729@s.whatsapp.net',
> >    fromMe: true,
> >    id: 'BAE5CA8F0B65D48A'
> >  },
> >  pushName: '',
> >  message: { extendedTextMessage: { text: '', contextInfo: {} } },
> >  messageType: 'extendedTextMessage',
> >  messageTimestamp: Long { low: 1702433151, high: 0, unsigned: true },
> >  owner: 'LEADS-3M',
> >  source: 'web'
> > } 
> > ```
> 
> eu corrigi um bug semelhante, você deve fazer as seguinte alterações no encapsulamento da variavel state:
> 
> ![image](https://private-user-images.githubusercontent.com/111699910/331734495-d0b4fa5d-3a04-43df-be5c-6c66df01408d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5ODE2MjUsIm5iZiI6MTcxNTk4MTMyNSwicGF0aCI6Ii8xMTE2OTk5MTAvMzMxNzM0NDk1LWQwYjRmYTVkLTNhMDQtNDNkZi1iZTVjLTZjNjZkZjAxNDA4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QyMTI4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTljOTRmOGIxNzk1MjQzMjhiNmVjOTg0MDBjZTNhMWQyMDQ2OTQ5NzZjYTBmOWEzYTgxNmNjZWI1OGVjMWRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yDdYMH_4Bw-Wx0fIuez1rIp_OgCpbfNaNUPfxNIupcQ)

voce pode usar nativamente o nome do contato e numero do contato no typebot com essa correção sem a gambiarra do pushName

**Comment by behappier-app** [comment]
to tendo esse problema, porem quero pegar id em vez de pushname para mandar essa id em um http request
