### ISSUE TITLE
Suporte para arquitetura arm64

### ISSUE THREAD

**Issue by hostsistemas** [EvolutionAPI/evolution-api#258]
Suporte para arquitetura arm64

**Comment by DavidsonGomes** [comment]
Estaremos trabalhando nisso

**Comment by Rod-Gomes** [comment]
Pessoal, gostaria de retomar a discussão sobre a execução da EvolutionAPI em um Raspberry Pi, que utiliza sistema ARM. Até agora, ARM possui compatibilidade com várias ferramentas, como Typebot e Chatwoot, exceto para a EvolutionAPI.

A instalação em sistemas ARM é complicada, exigindo a construção manual e impedindo atualizações automáticas via Docker. Seria muito útil se pudessem disponibilizar uma imagem pré-compilada para sistemas ARM, servindo tanto para Macs quanto para Raspberry Pi e outros dispositivos com esse tipo de processador. Isso simplificaria o processo de instalação e atenderia a uma comunidade mais ampla.

**Comment by marlonvaughan** [comment]
Estou animado para compartilhar que consegui recriar a imagem Docker originalmente projetada para processadores Intel/AMD para a plataforma ARM64! Agora, os usuários de dispositivos ARM64 também poderão aproveitar essa imagem incrível.
está no Docker Hub marlonvaughan/evolution-api.

**Comment by Rod-Gomes** [comment]
Obrigado @marlonvaughan! Você vai manter o fork sempre atualizado?

Ideal seria o próprio pessoal do projeto lançar a versão ARM oficial.

**Comment by marlonvaughan** [comment]
Vou sempre manter atualizado até sair a versão oficial do @DavidsonGomes.

**Comment by MarcioLacerda** [comment]
Estou testando a imagem oficial (linux/arm64) da 1.8.0 numa maquina na OCI e até agora só felicidade. Acho que o @marlonvaughan já pode descançar...rs
