### ISSUE TITLE
sendMedia POST

### ISSUE THREAD

**Issue by edgardjnr** [EvolutionAPI/evolution-api#259]
o envio de imagem via webhook nao está funcionando na versao 1.6 da Evo

**Comment by edgardjnr** [comment]
na versao 1.6.0 da Evo

**Comment by gabrielpastori1** [comment]
Pode dar mais informações? Como está fazendo a requisição? Qual erro retorna?

**Comment by edgardjnr** [comment]
estou enviando imagem por webwook via post conforme imagem abaixo, para a versao 1.5.4 da evo vai normalmente, para a versão 1.6.0 nao funciona.

<img width="757" alt="Captura de Tela 2023-12-13 às 13 14 54" src="https://github.com/EvolutionAPI/evolution-api/assets/152132143/3bf34842-8d26-44d5-a716-00e09ac92f21">
<img width="757" alt="Captura de Tela 2023-12-13 às 13 15 02" src="https://github.com/EvolutionAPI/evolution-api/assets/152132143/cc581675-36d2-4e3d-a7f5-4ed5ada58107">

**Comment by DavidsonGomes** [comment]
Preciso saber oq vem exatamente da sua sua variavel imagem_teste

**Comment by DavidsonGomes** [comment]
Nesse caso preciso dos logs que aparecem quando faz a requisição

**Comment by DavidsonGomes** [comment]
Todos os testes que fizemos aqui funcionaram, peço que reveja as suas variaveis e informações
