### ISSUE TITLE
erro usando typebot

### ISSUE THREAD

**Issue by mrfurquim** [EvolutionAPI/evolution-api#260]
3|ApiEvolution  | TypeError: Cannot read properties of undefined (reading 'API_VERSION')
3|ApiEvolution  |     at TypebotService.<anonymous> (/home/evolutionapi/dist/src/whatsapp/services/typebot.service.js:243:66)
3|ApiEvolution  |     at Generator.next (<anonymous>)
3|ApiEvolution  |     at /home/evolutionapi/dist/src/whatsapp/services/typebot.service.js:8:71
3|ApiEvolution  |     at new Promise (<anonymous>)
3|ApiEvolution  |     at __awaiter (/home/evolutionapi/dist/src/whatsapp/services/typebot.service.js:4:12)
3|ApiEvolution  |     at TypebotService.createNewSession (/home/evolutionapi/dist/src/whatsapp/services/typebot.service.js:232:16)
3|ApiEvolution  |     at TypebotService.<anonymous> (/home/evolutionapi/dist/src/whatsapp/services/typebot.service.js:533:45)
3|ApiEvolution  |     at Generator.next (<anonymous>)
3|ApiEvolution  |     at fulfilled (/home/evolutionapi/dist/src/whatsapp/services/typebot.service.js:5:58)
3|ApiEvolution  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
3|ApiEvolution  | [Evolution API]  v1.6.0  153799   -  Wed Dec 13 2023 14:51:35     ERROR   [TypebotService]  [object]
3|ApiEvolution  | TypeError: Cannot read properties of undefined (reading 'messages')
3|ApiEvolution  |     at TypebotService.<anonymous> (/home/evolutionapi/dist/src/whatsapp/services/typebot.service.js:546:72)
3|ApiEvolution  |     at Generator.next (<anonymous>)
3|ApiEvolution  |     at fulfilled (/home/evolutionapi/dist/src/whatsapp/services/typebot.service.js:5:58)
3|ApiEvolution  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by gabrielpastori1** [comment]
Precisa adicionar um novo valor no env

```
TYPEBOT:
  API_VERSION: 'old' # old | latest
```

**Comment by mrfurquim** [comment]
> Precisa adicionar um novo valor no env
> 
> ```
> TYPEBOT:
>   API_VERSION: 'old' # old | latest
> ```

Esse corrigiu, agora, outro

7|ApiEvolution  | [Evolution API]  v1.6.0  156368   -  Wed Dec 13 2023 17:12:23     ERROR   [TypebotService]  [object]
7|ApiEvolution  | AxiosError: Request failed with status code 400
7|ApiEvolution  |     at settle (/home/evolution-api/node_modules/axios/dist/node/axios.cjs:1967:12)
7|ApiEvolution  |     at IncomingMessage.handleStreamEnd (/home/evolution-api/node_modules/axios/dist/node/axios.cjs:3062:11)
7|ApiEvolution  |     at IncomingMessage.emit (node:events:526:35)
7|ApiEvolution  |     at IncomingMessage.emit (node:domain:489:12)
7|ApiEvolution  |     at endReadableNT (node:internal/streams/readable:1376:12)
7|ApiEvolution  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
7|ApiEvolution  |   code: 'ERR_BAD_REQUEST',
7|ApiEvolution  |   config: {
7|ApiEvolution  |     transitional: {
7|ApiEvolution  |       silentJSONParsing: true,
7|ApiEvolution  |       forcedJSONParsing: true,
7|ApiEvolution  |       clarifyTimeoutError: false
7|ApiEvolution  |     },
7|ApiEvolution  |     adapter: [ 'xhr', 'http' ],
7|ApiEvolution  |     transformRequest: [ [Function: transformRequest] ],
7|ApiEvolution  |     transformResponse: [ [Function: transformResponse] ],
7|ApiEvolution  |     timeout: 0,
7|ApiEvolution  |     xsrfCookieName: 'XSRF-TOKEN',
7|ApiEvolution  |     xsrfHeaderName: 'X-XSRF-TOKEN',
7|ApiEvolution  |     maxContentLength: -1,
7|ApiEvolution  |     maxBodyLength: -1,
7|ApiEvolution  |     env: { FormData: [Function], Blob: [class Blob] },
7|ApiEvolution  |     validateStatus: [Function: validateStatus],
7|ApiEvolution  |     headers: Object [AxiosHeaders] {
7|ApiEvolution  |       Accept: 'application/json, text/plain, */*',
7|ApiEvolution  |       'Content-Type': 'application/json',
7|ApiEvolution  |       'User-Agent': 'axios/1.6.2',
7|ApiEvolution  |       'Content-Length': '154',
7|ApiEvolution  |       'Accept-Encoding': 'gzip, compress, deflate, br'
7|ApiEvolution  |     },
7|ApiEvolution  |     method: 'post',
7|ApiEvolution  |     url: 'http://bot.agrovale.coop:3002/api/v1/sendMessage',
7|ApiEvolution  |     data: '{"startParams":{"publicId":"ura","prefilledVariables":{"remoteJid":"556496589675@s.whatsapp.net","pushName":"Leonardo Furquim","instanceName":"bot-cpd"}}}'
7|ApiEvolution  |   },
7|ApiEvolution  |   request: <ref *1> ClientRequest {
7|ApiEvolution  |     _events: [Object: null prototype] {
7|ApiEvolution  |       abort: [Function (anonymous)],
7|ApiEvolution  |       aborted: [Function (anonymous)],
7|ApiEvolution  |       connect: [Function (anonymous)],
7|ApiEvolution  |       error: [Function (anonymous)],
7|ApiEvolution  |       socket: [Function (anonymous)],
7|ApiEvolution  |       timeout: [Function (anonymous)],
7|ApiEvolution  |       finish: [Function: requestOnFinish]
7|ApiEvolution  |     },
7|ApiEvolution  |     _eventsCount: 7,
7|ApiEvolution  |     _maxListeners: undefined,
7|ApiEvolution  |     outputData: [],
7|ApiEvolution  |     outputSize: 0,
7|ApiEvolution  |     writable: true,
7|ApiEvolution  |     destroyed: true,
7|ApiEvolution  |     _last: false,
7|ApiEvolution  |     chunkedEncoding: false,
7|ApiEvolution  |     shouldKeepAlive: true,
7|ApiEvolution  |     maxRequestsOnConnectionReached: false,
7|ApiEvolution  |     _defaultKeepAlive: true,
7|ApiEvolution  |     useChunkedEncodingByDefault: true,
7|ApiEvolution  |     sendDate: false,
7|ApiEvolution  |     _removedConnection: false,
7|ApiEvolution  |     _removedContLen: false,
7|ApiEvolution  |     _removedTE: false,
7|ApiEvolution  |     strictContentLength: false,
7|ApiEvolution  |     _contentLength: '154',
7|ApiEvolution  |     _hasBody: true,
7|ApiEvolution  |     _trailer: '',
7|ApiEvolution  |     finished: true,
7|ApiEvolution  |     _headerSent: true,
7|ApiEvolution  |     _closed: true,
7|ApiEvolution  |     socket: Socket {
7|ApiEvolution  |       connecting: false,
7|ApiEvolution  |       _hadError: false,
7|ApiEvolution  |       _parent: null,
7|ApiEvolution  |       _host: 'bot.agrovale.coop',
7|ApiEvolution  |       _closeAfterHandlingError: false,
7|ApiEvolution  |       _readableState: [ReadableState],
7|ApiEvolution  |       _events: [Object: null prototype],
7|ApiEvolution  |       _eventsCount: 6,
7|ApiEvolution  |       _maxListeners: undefined,
7|ApiEvolution  |       _writableState: [WritableState],
7|ApiEvolution  |       allowHalfOpen: false,
7|ApiEvolution  |       _sockname: null,
7|ApiEvolution  |       _pendingData: null,
7|ApiEvolution  |       _pendingEncoding: '',
7|ApiEvolution  |       server: null,
7|ApiEvolution  |       _server: null,
7|ApiEvolution  |       timeout: 5000,
7|ApiEvolution  |       parser: null,
7|ApiEvolution  |       _httpMessage: null,
7|ApiEvolution  |       [Symbol(async_id_symbol)]: -1,
7|ApiEvolution  |       [Symbol(kHandle)]: [TCP],
7|ApiEvolution  |       [Symbol(lastWriteQueueSize)]: 0,
7|ApiEvolution  |       [Symbol(timeout)]: Timeout {
7|ApiEvolution  |         _idleTimeout: 5000,
7|ApiEvolution  |         _idlePrev: [TimersList],
7|ApiEvolution  |         _idleNext: [TimersList],
7|ApiEvolution  |         _idleStart: 469567,
7|ApiEvolution  |         _onTimeout: [Function: bound ],
7|ApiEvolution  |         _timerArgs: undefined,
7|ApiEvolution  |         _repeat: null,
7|ApiEvolution  |         _destroyed: false,
7|ApiEvolution  |         [Symbol(refed)]: false,
7|ApiEvolution  |         [Symbol(kHasPrimitive)]: false,
7|ApiEvolution  |         [Symbol(asyncId)]: 4839,
7|ApiEvolution  |         [Symbol(triggerId)]: 4837
7|ApiEvolution  |       },
7|ApiEvolution  |       [Symbol(kBuffer)]: null,
7|ApiEvolution  |       [Symbol(kBufferCb)]: null,
7|ApiEvolution  |       [Symbol(kBufferGen)]: null,
7|ApiEvolution  |       [Symbol(kCapture)]: false,
7|ApiEvolution  |       [Symbol(kSetNoDelay)]: true,
7|ApiEvolution  |       [Symbol(kSetKeepAlive)]: true,
7|ApiEvolution  |       [Symbol(kSetKeepAliveInitialDelay)]: 1,
7|ApiEvolution  |       [Symbol(kBytesRead)]: 0,
7|ApiEvolution  |       [Symbol(kBytesWritten)]: 0
7|ApiEvolution  |     },
7|ApiEvolution  |     _header: 'POST /api/v1/sendMessage HTTP/1.1\r\n' +
7|ApiEvolution  |       'Accept: application/json, text/plain, */*\r\n' +
7|ApiEvolution  |       'Content-Type: application/json\r\n' +
7|ApiEvolution  |       'User-Agent: axios/1.6.2\r\n' +
7|ApiEvolution  |       'Content-Length: 154\r\n' +
7|ApiEvolution  |       'Accept-Encoding: gzip, compress, deflate, br\r\n' +
7|ApiEvolution  |       'Host: bot.agrovale.coop:3002\r\n' +
7|ApiEvolution  |       'Connection: keep-alive\r\n' +
7|ApiEvolution  |       '\r\n',
7|ApiEvolution  |     _keepAliveTimeout: 0,
7|ApiEvolution  |     _onPendingData: [Function: nop],
7|ApiEvolution  |     agent: Agent {
7|ApiEvolution  |       _events: [Object: null prototype],
7|ApiEvolution  |       _eventsCount: 2,
7|ApiEvolution  |       _maxListeners: undefined,
7|ApiEvolution  |       defaultPort: 80,
7|ApiEvolution  |       protocol: 'http:',
7|ApiEvolution  |       options: [Object: null prototype],
7|ApiEvolution  |       requests: [Object: null prototype] {},
7|ApiEvolution  |       sockets: [Object: null prototype] {},
7|ApiEvolution  |       freeSockets: [Object: null prototype],
7|ApiEvolution  |       keepAliveMsecs: 1000,
7|ApiEvolution  |       keepAlive: true,
7|ApiEvolution  |       maxSockets: Infinity,
7|ApiEvolution  |       maxFreeSockets: 256,
7|ApiEvolution  |       scheduling: 'lifo',
7|ApiEvolution  |       maxTotalSockets: Infinity,
7|ApiEvolution  |       totalSocketCount: 1,
7|ApiEvolution  |       [Symbol(kCapture)]: false
7|ApiEvolution  |     },
7|ApiEvolution  |     socketPath: undefined,
7|ApiEvolution  |     method: 'POST',
7|ApiEvolution  |     maxHeaderSize: undefined,
7|ApiEvolution  |     insecureHTTPParser: undefined,
7|ApiEvolution  |     joinDuplicateHeaders: undefined,
7|ApiEvolution  |     path: '/api/v1/sendMessage',
7|ApiEvolution  |     _ended: true,
7|ApiEvolution  |     res: IncomingMessage {
7|ApiEvolution  |       _readableState: [ReadableState],
7|ApiEvolution  |       _events: [Object: null prototype],
7|ApiEvolution  |       _eventsCount: 4,
7|ApiEvolution  |       _maxListeners: undefined,
7|ApiEvolution  |       socket: null,
7|ApiEvolution  |       httpVersionMajor: 1,
7|ApiEvolution  |       httpVersionMinor: 1,
7|ApiEvolution  |       httpVersion: '1.1',
7|ApiEvolution  |       complete: true,
7|ApiEvolution  |       rawHeaders: [Array],
7|ApiEvolution  |       rawTrailers: [],
7|ApiEvolution  |       joinDuplicateHeaders: undefined,
7|ApiEvolution  |       aborted: false,
7|ApiEvolution  |       upgrade: false,
7|ApiEvolution  |       url: '',
7|ApiEvolution  |       method: null,
7|ApiEvolution  |       statusCode: 400,
7|ApiEvolution  |       statusMessage: 'Bad Request',
7|ApiEvolution  |       client: [Socket],
7|ApiEvolution  |       _consuming: false,
7|ApiEvolution  |       _dumped: false,
7|ApiEvolution  |       req: [Circular *1],
7|ApiEvolution  |       responseUrl: 'http://bot.agrovale.coop:3002/api/v1/sendMessage',
7|ApiEvolution  |       redirects: [],
7|ApiEvolution  |       [Symbol(kCapture)]: false,
7|ApiEvolution  |       [Symbol(kHeaders)]: [Object],
7|ApiEvolution  |       [Symbol(kHeadersCount)]: 14,
7|ApiEvolution  |       [Symbol(kTrailers)]: null,
7|ApiEvolution  |       [Symbol(kTrailersCount)]: 0
7|ApiEvolution  |     },
7|ApiEvolution  |     aborted: false,
7|ApiEvolution  |     timeoutCb: null,
7|ApiEvolution  |     upgradeOrConnect: false,
7|ApiEvolution  |     parser: null,
7|ApiEvolution  |     maxHeadersCount: null,
7|ApiEvolution  |     reusedSocket: false,
7|ApiEvolution  |     host: 'bot.agrovale.coop',
7|ApiEvolution  |     protocol: 'http:',
7|ApiEvolution  |     _redirectable: Writable {
7|ApiEvolution  |       _writableState: [WritableState],
7|ApiEvolution  |       _events: [Object: null prototype],
7|ApiEvolution  |       _eventsCount: 3,
7|ApiEvolution  |       _maxListeners: undefined,
7|ApiEvolution  |       _options: [Object],
7|ApiEvolution  |       _ended: true,
7|ApiEvolution  |       _ending: true,
7|ApiEvolution  |       _redirectCount: 0,
7|ApiEvolution  |       _redirects: [],
7|ApiEvolution  |       _requestBodyLength: 154,
7|ApiEvolution  |       _requestBodyBuffers: [],
7|ApiEvolution  |       _onNativeResponse: [Function (anonymous)],
7|ApiEvolution  |       _currentRequest: [Circular *1],
7|ApiEvolution  |       _currentUrl: 'http://bot.agrovale.coop:3002/api/v1/sendMessage',
7|ApiEvolution  |       [Symbol(kCapture)]: false
7|ApiEvolution  |     },
7|ApiEvolution  |     [Symbol(kCapture)]: false,
7|ApiEvolution  |     [Symbol(kBytesWritten)]: 0,
7|ApiEvolution  |     [Symbol(kNeedDrain)]: false,
7|ApiEvolution  |     [Symbol(corked)]: 0,
7|ApiEvolution  |     [Symbol(kOutHeaders)]: [Object: null prototype] {
7|ApiEvolution  |       accept: [Array],
7|ApiEvolution  |       'content-type': [Array],
7|ApiEvolution  |       'user-agent': [Array],
7|ApiEvolution  |       'content-length': [Array],
7|ApiEvolution  |       'accept-encoding': [Array],
7|ApiEvolution  |       host: [Array]
7|ApiEvolution  |     },
7|ApiEvolution  |     [Symbol(errored)]: null,
7|ApiEvolution  |     [Symbol(kHighWaterMark)]: 16384,
7|ApiEvolution  |     [Symbol(kRejectNonStandardBodyWrites)]: false,
7|ApiEvolution  |     [Symbol(kUniqueHeaders)]: null
7|ApiEvolution  |   },
7|ApiEvolution  |   response: {
7|ApiEvolution  |     status: 400,
7|ApiEvolution  |     statusText: 'Bad Request',
7|ApiEvolution  |     headers: Object [AxiosHeaders] {
7|ApiEvolution  |       'access-control-allow-origin': '*',
7|ApiEvolution  |       'content-type': 'application/json',
7|ApiEvolution  |       vary: 'Accept-Encoding',
7|ApiEvolution  |       date: 'Wed, 13 Dec 2023 17:12:23 GMT',
7|ApiEvolution  |       connection: 'keep-alive',
7|ApiEvolution  |       'keep-alive': 'timeout=5',
7|ApiEvolution  |       'transfer-encoding': 'chunked'
7|ApiEvolution  |     },
7|ApiEvolution  |     config: {
7|ApiEvolution  |       transitional: [Object],
7|ApiEvolution  |       adapter: [Array],
7|ApiEvolution  |       transformRequest: [Array],
7|ApiEvolution  |       transformResponse: [Array],
7|ApiEvolution  |       timeout: 0,
7|ApiEvolution  |       xsrfCookieName: 'XSRF-TOKEN',
7|ApiEvolution  |       xsrfHeaderName: 'X-XSRF-TOKEN',
7|ApiEvolution  |       maxContentLength: -1,
7|ApiEvolution  |       maxBodyLength: -1,
7|ApiEvolution  |       env: [Object],
7|ApiEvolution  |       validateStatus: [Function: validateStatus],
7|ApiEvolution  |       headers: [Object [AxiosHeaders]],
7|ApiEvolution  |       method: 'post',
7|ApiEvolution  |       url: 'http://bot.agrovale.coop:3002/api/v1/sendMessage',
7|ApiEvolution  |       data: '{"startParams":{"publicId":"ura","prefilledVariables":{"remoteJid":"556496589675@s.whatsapp.net","pushName":"Leonardo Furquim","instanceName":"bot-cpd"}}}'
7|ApiEvolution  |     },
7|ApiEvolution  |     request: <ref *1> ClientRequest {
7|ApiEvolution  |       _events: [Object: null prototype],
7|ApiEvolution  |       _eventsCount: 7,
7|ApiEvolution  |       _maxListeners: undefined,
7|ApiEvolution  |       outputData: [],
7|ApiEvolution  |       outputSize: 0,
7|ApiEvolution  |       writable: true,
7|ApiEvolution  |       destroyed: true,
7|ApiEvolution  |       _last: false,
7|ApiEvolution  |       chunkedEncoding: false,
7|ApiEvolution  |       shouldKeepAlive: true,
7|ApiEvolution  |       maxRequestsOnConnectionReached: false,
7|ApiEvolution  |       _defaultKeepAlive: true,
7|ApiEvolution  |       useChunkedEncodingByDefault: true,
7|ApiEvolution  |       sendDate: false,
7|ApiEvolution  |       _removedConnection: false,
7|ApiEvolution  |       _removedContLen: false,
7|ApiEvolution  |       _removedTE: false,
7|ApiEvolution  |       strictContentLength: false,
7|ApiEvolution  |       _contentLength: '154',
7|ApiEvolution  |       _hasBody: true,
7|ApiEvolution  |       _trailer: '',
7|ApiEvolution  |       finished: true,
7|ApiEvolution  |       _headerSent: true,
7|ApiEvolution  |       _closed: true,
7|ApiEvolution  |       socket: [Socket],
7|ApiEvolution  |       _header: 'POST /api/v1/sendMessage HTTP/1.1\r\n' +
7|ApiEvolution  |         'Accept: application/json, text/plain, */*\r\n' +
7|ApiEvolution  |         'Content-Type: application/json\r\n' +
7|ApiEvolution  |         'User-Agent: axios/1.6.2\r\n' +
7|ApiEvolution  |         'Content-Length: 154\r\n' +
7|ApiEvolution  |         'Accept-Encoding: gzip, compress, deflate, br\r\n' +
7|ApiEvolution  |         'Host: bot.agrovale.coop:3002\r\n' +
7|ApiEvolution  |         'Connection: keep-alive\r\n' +
7|ApiEvolution  |         '\r\n',
7|ApiEvolution  |       _keepAliveTimeout: 0,
7|ApiEvolution  |       _onPendingData: [Function: nop],
7|ApiEvolution  |       agent: [Agent],
7|ApiEvolution  |       socketPath: undefined,
7|ApiEvolution  |       method: 'POST',
7|ApiEvolution  |       maxHeaderSize: undefined,
7|ApiEvolution  |       insecureHTTPParser: undefined,
7|ApiEvolution  |       joinDuplicateHeaders: undefined,
7|ApiEvolution  |       path: '/api/v1/sendMessage',
7|ApiEvolution  |       _ended: true,
7|ApiEvolution  |       res: [IncomingMessage],
7|ApiEvolution  |       aborted: false,
7|ApiEvolution  |       timeoutCb: null,
7|ApiEvolution  |       upgradeOrConnect: false,
7|ApiEvolution  |       parser: null,
7|ApiEvolution  |       maxHeadersCount: null,
7|ApiEvolution  |       reusedSocket: false,
7|ApiEvolution  |       host: 'bot.agrovale.coop',
7|ApiEvolution  |       protocol: 'http:',
7|ApiEvolution  |       _redirectable: [Writable],
7|ApiEvolution  |       [Symbol(kCapture)]: false,
7|ApiEvolution  |       [Symbol(kBytesWritten)]: 0,
7|ApiEvolution  |       [Symbol(kNeedDrain)]: false,
7|ApiEvolution  |       [Symbol(corked)]: 0,
7|ApiEvolution  |       [Symbol(kOutHeaders)]: [Object: null prototype],
7|ApiEvolution  |       [Symbol(errored)]: null,
7|ApiEvolution  |       [Symbol(kHighWaterMark)]: 16384,
7|ApiEvolution  |       [Symbol(kRejectNonStandardBodyWrites)]: false,
7|ApiEvolution  |       [Symbol(kUniqueHeaders)]: null
7|ApiEvolution  |     },
7|ApiEvolution  |     data: {
7|ApiEvolution  |       message: 'Input validation failed',
7|ApiEvolution  |       code: 'BAD_REQUEST',
7|ApiEvolution  |       issues: [Array]
7|ApiEvolution  |     }
7|ApiEvolution  |   }
7|ApiEvolution  | }
7|ApiEvolution  | [Evolution API]  v1.6.0  156368   -  Wed Dec 13 2023 17:12:23     ERROR   [TypebotService]  [object]
7|ApiEvolution  | TypeError: Cannot read properties of undefined (reading 'messages')
7|ApiEvolution  |     at TypebotService.<anonymous> (/home/evolution-api/dist/src/whatsapp/services/typebot.service.js:546:72)
7|ApiEvolution  |     at Generator.next (<anonymous>)
7|ApiEvolution  |     at fulfilled (/home/evolution-api/dist/src/whatsapp/services/typebot.service.js:5:58)
7|ApiEvolution  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
7

**Comment by DavidsonGomes** [comment]
Estou tentando validar, mas parece ter algum problema com seu typebot

Testando via curl:
`curl --location 'http://bot.agrovale.coop:3002/api/v1/sendMessage' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ImbrQMowMwYMYILCaGeiHfcu' \
--data-raw '{
    "startParams": {
        "publicId": "ura",
        "prefilledVariables": {
            "remoteJid": "556496589675@s.whatsapp.net",
            "pushName": "Leonardo Furquim",
            "instanceName": "bot-cpd"
        }
    }
}'`

<img width="534" alt="Screenshot 2023-12-14 at 07 50 44" src="https://github.com/EvolutionAPI/evolution-api/assets/24706726/1e5af94c-a14e-4753-b551-6c2953f209c9">

**Comment by mrfurquim** [comment]
@DavidsonGomes, esse é um dns local, no caso ele não estaria disponível fora da minha rede.

Vou tentar novamente

**Comment by DavidsonGomes** [comment]
Verifique seu ambiente, pois é problema relacionado a comunicação entre a evolution e seu typebot

**Comment by fredericocmoreira** [comment]
@mrfurquim  Como resolveu o problema do BAD_REQUEST?

**Comment by grupale** [comment]
Hi @gabrielpastori1  @DavidsonGomes I'm having this error with TypeBot with 1.7.2 version and public Typebot (https://typebot.io) 

This is the error that Im getting
![image](https://github.com/EvolutionAPI/evolution-api/assets/10934794/5e9a594d-fd7b-4669-8e28-0aeea8231291)

this is my env file and typebot config
![image](https://github.com/EvolutionAPI/evolution-api/assets/10934794/8c46ff9a-6116-4eac-aa5c-c540ee4f418a)
![image](https://github.com/EvolutionAPI/evolution-api/assets/10934794/4df30126-d7b2-4429-9446-c2481b4f541a)

What am I missing? Can you help me please? Thanks
