### ISSUE TITLE
Messages getting lost

### ISSUE THREAD

**Issue by IcaruuS22** [EvolutionAPI/evolution-api#261]
After updating to 1.6.0 chatwoot messages are not transmitted, only voice messages
![Screenshot_3](https://github.com/EvolutionAPI/evolution-api/assets/88380824/3c243e98-d67a-4a2e-b1bd-3d4bfa7248a4)
![Screenshot_4](https://github.com/EvolutionAPI/evolution-api/assets/88380824/5c288436-9bfe-431b-adfb-d3cb4a5d1d98)

**Comment by gabrielpastori1** [comment]
Como está sendo enviado as mensagens?

**Comment by IcaruuS22** [comment]
Essas em específico é por um fluxo do N8N

**Comment by gabrielpastori1** [comment]
Consegue simular o erro e pegar os logs da api?

**Comment by IcaruuS22** [comment]
Obtenho esses dois logs:

![Screenshot_4](https://github.com/EvolutionAPI/evolution-api/assets/88380824/c8562dc9-481e-42e5-bcfb-58eee9a27443)
![Screenshot_5](https://github.com/EvolutionAPI/evolution-api/assets/88380824/4ff8171e-0336-4d92-8d0e-ff9b04707d7e)

**Comment by stgcompany** [comment]
Estou com o mesmo problema, pelos poucos testes que fiz após atualizar evolution pro 1.6 estou conseguindo enviar mensagens pelo chatwoot, mas não consigo receber:

![image](https://github.com/EvolutionAPI/evolution-api/assets/143809393/cc3b6f5b-38c2-4bd5-8273-ed1e6339900f)

Ele dá um erro 422 Unprocessable Content e diz: "String does not have #dig method"

**Comment by jaison-x** [comment]
Acredito que esse problema seja a versão do chatwoot. Vocês estão usando a versão mais recente? Precisa estar na versão 3.3.1.

**Comment by IcaruuS22** [comment]
> Acredito que esse problema seja a versão do chatwoot. Vocês estão usando a versão mais recente? Precisa estar na versão 3.3.1.

Estou utilizando a versão 3.2.0 ainda, a 3.3.1 está com alguns bugs de time out de mensagens

**Comment by DavidsonGomes** [comment]
A versao 1.6.0 esta 100% funcional com a versao 3.3.1 do chatwoot

**Comment by stgcompany** [comment]
Atualizei a versão para 3.3.1 e resolveu o problema :+1:
