### ISSUE TITLE
EvolutionAPI: v1.6.0 x Typebot: v2.20.0

### ISSUE THREAD

**Issue by wesleyareis** [EvolutionAPI/evolution-api#262]
Além de não estar pegando as variáveis {{pushName}} e {{remoteJid}} as respostas pelo integração ChatGPT não aparece no diálogo (vide print):

![image](https://github.com/EvolutionAPI/evolution-api/assets/127250944/d3cdd6c6-eb11-46aa-a7d6-5d3e31ee0c51)

**Comment by wesleyareis** [comment]
Em tempo:
Veja como aparece no Chatwoot: v3.3.1

![image](https://github.com/EvolutionAPI/evolution-api/assets/127250944/46bb588e-273e-423d-80fc-a3e9424ad0c8)

**Comment by matiasduartee** [comment]
Está acontecendo comigo também exatamente a mesma coisa! 

Evolution Versão: 1.6.0
Typebot Versão: 2.19.1

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/434a0bba-3c80-4070-99ae-4fe97b1efeef)

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/095710f2-9be7-43e0-b097-5d274cc31627)

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/e9b86f07-50b7-4693-bbc9-2a51f1a9bb37)

**Comment by brunopinto123** [comment]
Está acontecendo comigo também a mesma coisa.

Evolution Versão: 1.6.0
Typebot Versão: 2.20.0

![WhatsApp Image 2023-12-13 at 23 41 11](https://github.com/EvolutionAPI/evolution-api/assets/132612660/82daf523-562c-45e6-892a-6fd295e09003)
![WhatsApp Image 2023-12-13 at 23 41 37](https://github.com/EvolutionAPI/evolution-api/assets/132612660/84c673c1-86b3-4f20-b933-ef1c03a53a05)

**Comment by fredlisboa** [comment]
Após atualização Evolution 1.6 parte das respostas de meu bot aparecem "vazias" assim como indicado nos retângulos abaixo. 

Versões: Evo 1.6.0, Typebot 2.20.0. 

No preview do chat não acontece isso (indicado na próxima imagem). 

Estou tentando resolver mas sem sucesso ainda, já até reinstalei tudo e o erro persiste. 

tivei/desativei o MongoDB mas sem sucesso ainda.

![FOTO01](https://github.com/EvolutionAPI/evolution-api/assets/10284320/72a772e9-4b1c-4d84-a70e-a6f38da30c9b)
![FOTO02](https://github.com/EvolutionAPI/evolution-api/assets/10284320/9377f9c3-a5bb-4846-9eda-d2e88d024c29)

**Comment by DavidsonGomes** [comment]
issue ja aberta no #255 , favor nao duplicar
