### ISSUE TITLE
EVO 1.6.0 - Função de apagar mensagem só funciona para o agente do Chatwoot !?

### ISSUE THREAD

**Issue by luiztonucci** [EvolutionAPI/evolution-api#263]
@DavidsonGomes, fiz os testes de apagar a mensagem com a evo 1.6.0, mas parece que só funciona quando o agente do chatwoot apaga, se o cliente no whats apagar, não apaga no chatwoot. Estou utilizando o mongoDB como sugerido.

![apagar msg](https://github.com/EvolutionAPI/evolution-api/assets/82972632/7d02d5d0-fa13-41a8-a907-c1779ac129b9)
![stack da evo na config do mongoDB](https://github.com/EvolutionAPI/evolution-api/assets/82972632/b0bed3b3-9668-4b1a-bae8-ff909e283451)

**Comment by matiasduartee** [comment]
Fiz o teste aqui realmente, se o usuário do WhatsApp apagar a mensagem ela não apaga do Chatwoot.

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/34822360-c13a-46bf-802e-39a3281bf4fd)

**Comment by DavidsonGomes** [comment]
Sim por enquanto apenas pelo agente, em breve vamos melhorar isso

**Comment by viniciusdebruin** [comment]
eu to com problema nesse lance de apagar. Quando apago do chatwoot ele não apaga no whatsapp. Quando o cliente apaga no whatsapp, ele não mostra no chatwoot que foi removido. Estou testando com um cliente que pega pedidos e essa função para eles é crucial, uma vez que se o pedido for apagado, ele não vão faturar, mas como podemos identificar isso no chatwoot?
Estou usando a versão 1.6.0 da evolution, 3.3.1 do chatwoot em docker com mongo.

**Comment by DavidsonGomes** [comment]
Lembre se ativar a gravação de mensagens no mongodb, sem isso não funciona!

DATABASE_SAVE_DATA_INSTANCE=true
DATABASE_SAVE_DATA_NEW_MESSAGE=true

**Comment by viniciusdebruin** [comment]
Davidson seria possível na documentação você colocar tudo isso? Eu por exemplo estou fuçando no whatsapp e nos vídeos, mas esta complicado. Seria legal uma aba só sobre o chatwoot mostrando como instala o mongo, quais parâmetros ativar. Eu sei que a evolution ainda está em desenvolvimento, mas essa do  DATABASE_SAVE_DATA_NEW_MESSAGE=true eu nao vi em nenhum video. Você na live também mostrou as reações e respostas no chatwoot, aqui nenhuma das 2 funcionou, lógico que eu não estou sabendo fazer.

**Comment by Zeegfreet** [comment]
Não melhora não, pelo amor de Deus, melhor dos mundos é não apagar para o agente mesmo, ideal era só sinalizar, estamos falando de um modelo profissional onde o registro de tudo é importante.
