### ISSUE TITLE
Chatwoot não recebe as mensagens evolution 1.6

### ISSUE THREAD

**Issue by MoreiraTv** [EvolutionAPI/evolution-api#264]
Utilizando chatwoot v3.3.1
Evolution 1.6.0

E mesmo gerando a caixa do chatwoot manual não consigo imitir o qrcode pelo chatwoot, e se tento conectar o qr code pelo manager, ele não recebe as mensagens no chatwoot.

![image](https://github.com/EvolutionAPI/evolution-api/assets/54282051/e2e61608-4809-4124-9bb4-84992f113cdb)
![image](https://github.com/EvolutionAPI/evolution-api/assets/54282051/63d44dbd-ee5e-4187-ac5b-35ae3ff07a73)

![image](https://github.com/EvolutionAPI/evolution-api/assets/54282051/76cae93f-b15c-4422-adcc-2645c3a9e7c5)

**Comment by matiasduartee** [comment]
Estranho @MoreiraTv isso está funcionando corretamente! Eu mesmo já estou utilizando em produção.

Já vi acontecer isso quando colocar a / no final do link do chatwoot, ID da conta errada ou ate mesmo o tokem.

**Comment by DavidsonGomes** [comment]
Verifique se suas credenciais estao corretas e se nao ja tem uma caixa de entrada com mesmo nome da instancia no chatwoot

**Comment by MoreiraTv** [comment]
Eu apaguei todas as caixais de entradas, está zerado, apaguei ate o usuario antigo e criei um novo, estou colocando id do usuario correto, e tbm conferi a apitoken.

**Comment by DavidsonGomes** [comment]
Preciso do log de erro do inbox na evolution, nos logs enviados nao tem essa informação

**Comment by MoreiraTv** [comment]
No logs do container não apareceu nenhum erro, tem alguma outra forma de eu ver logs de erro ?
pelo que eu entendi o manager ta retornando oque o chatwoot retornou pra ele, mas como eu estou pedindo para evolution criar a caixa ela tinha que criar primeiro depois buscar, mas ela não esta criando, e dps tenta buscar.
Ai tentei criar manual, mas mesmo assim não tem a comunicação de um com outro da sessão.

**Comment by DavidsonGomes** [comment]
dificil ajudar sem saber oq acontece la dentro, faz seguinte comenta o log VERBOSE no seu env, força o erro e manda print dos logs.

**Comment by MoreiraTv** [comment]
Voltei na versão anterior da evolution e estou com mesmo erro:

![image](https://github.com/EvolutionAPI/evolution-api/assets/54282051/cb124e61-ae9a-4a3b-a565-f6e0f8e64ce1)

**Comment by DavidsonGomes** [comment]
Ele nao esta encontrando a inbox 9, pode conferir se esse é o id da inbox realmente?

**Comment by MoreiraTv** [comment]
9 é o usuario, ele não encontra inbox pq ela n foi criada, então o erro ta antes dela tentar encontrar, pq nem está sendo criado.

Encontrei mais um erro, quando criei a inbox manual no chatwoot e dps fui no manager registrar:


Como pode ver a inbox existe aqui no insonimia:
![image](https://github.com/EvolutionAPI/evolution-api/assets/54282051/294ba424-ef05-42fd-884a-0ec73f69bf13)

![image](https://github.com/EvolutionAPI/evolution-api/assets/54282051/3e1bc9c3-9bb9-45f7-85a1-33e7a5804655)

![image](https://github.com/EvolutionAPI/evolution-api/assets/54282051/8d0dbc50-cba8-4d30-8f49-1d847cb714b3)

Ele está dando erro na hora de buscar o contato que gera o qrcode

**Comment by MoreiraTv** [comment]
![image](https://github.com/EvolutionAPI/evolution-api/assets/54282051/f30b7dce-0a9c-4498-a167-5a722c622acb)
![image](https://github.com/EvolutionAPI/evolution-api/assets/54282051/e911a779-7fb3-4859-ae12-514c4ce8e297)

**Comment by MoreiraTv** [comment]
Utilizando a api antiga recebo a mensagens normalmente.

**Comment by matiasduartee** [comment]
@MoreiraTv verifica agora se as configs da sua env estão corretas, mais especificamente a `- SERVER_URL=` pois se estiver com o link errado ao criar a caixa de entrada automaticamente o webhook será enviado errado para a configuração.

**Comment by matiasduartee** [comment]
> Utilizando a api antiga recebo a mensagens normalmente.
Tenta mandar aqui sempre o log da api, por exemplo nessa caso de nao receber a mensagem no chatwoot.

**Comment by MoreiraTv** [comment]
Sim está correta, e tbm abri as configurações da caixa para conferir, e se tivesse errado acredito que nem consegueria enviar mensagens usando chatwoot e o envio das mensagens funciona, só que para receber não.

**Comment by matiasduartee** [comment]
> Sim está correto, e tbm abri as configurações da caixa para conferir, e se tivesse errado acreditar que nem conseguiria enviar mensagens usando chatwoot e o envio das mensagens funciona, só que para receber não.

Caramba que estranho, realmente não sei o que pode estar acontecendo no seu projeto. Eu posso dizer por mim aqui, tenho dois cenários, um produção e um de teste e ambos estão com o chatwoot 3.3.1 e a Evolution 1.6.0.

**Comment by MoreiraTv** [comment]
EHeh mais coisa ainda pra ficar mais estranho ainda kkkk,

Quando envio midia como, audio ou foto a api recebe, mas quando envio mensagem de texto o api não recebe:

![image](https://github.com/EvolutionAPI/evolution-api/assets/54282051/a7e39a6c-72a8-4e99-bf07-74b7fc78660f)

Esse é o erro que tenho quando recebo um texto:
![image](https://github.com/EvolutionAPI/evolution-api/assets/54282051/2eac867e-4288-4670-abe3-5b268481f15e)

**Comment by jaison-x** [comment]
> EHeh mais coisa ainda pra ficar mais estranho ainda kkkk,
> 
> Quando envio midia como, audio ou foto a api recebe, mas quando envio mensagem de texto o api não recebe:
> 
> ![image](https://private-user-images.githubusercontent.com/54282051/290613290-a7e39a6c-72a8-4e99-bf07-74b7fc78660f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NzcwMDQsIm5iZiI6MTcwMjU3NjcwNCwicGF0aCI6Ii81NDI4MjA1MS8yOTA2MTMyOTAtYTdlMzlhNmMtNzJhOC00ZTk5LWJmMDctNzRiN2ZjNzg2NjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE3NTgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZGFjZjZiMDA1ZTU3NDYxZjBjNzBmNDNmZGUxZDUyOWFiYzNkNGExODU5Zjk2NzYxZDcwMTk3MzI2YWZhNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FdC_2426MLsVhB8nNoZO2vJsT0WELvj0ybC9kEygg9I)
> 
> Esse é o erro que tenho quando recebo um texto: ![image](https://private-user-images.githubusercontent.com/54282051/290612930-2eac867e-4288-4670-abe3-5b268481f15e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NzcwMDQsIm5iZiI6MTcwMjU3NjcwNCwicGF0aCI6Ii81NDI4MjA1MS8yOTA2MTI5MzAtMmVhYzg2N2UtNDI4OC00NjcwLWFiZTMtNWIyNjg0ODFmMTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE3NTgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMzQxNTM2ZjcwNGU4NjUxNjZlODdhODM0M2QyMzdjMzg2NmQzNjJjOTI5MmNiY2U5ZDA3MWEwMjJjOTRkYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xynDK5rmpcj9EzBX9yF2Ga4qx2IBpFXYVBftmWKepms)

Você está usando a versão 3.3.1 do chatwoot? Vi que você voltou snapshot então acredito que seja uma versão anterior. Pela mensagem de erro acredito que seja problema entre sua versão do cw e a versão 1.6 da evo. Se possível use a versão 3.3.1 do cw.

**Comment by MoreiraTv** [comment]
Realmente volotu para 3.2.0, mas isso faria mensagem parar de funcionar e manter midias funcionando ?

**Comment by MoreiraTv** [comment]
Subi outra instancia com 3.3.1 funcionou amigo, vlw, mas o de vocês estão pegando o reply e os reactions ? o meu não está

**Comment by jaison-x** [comment]
> Subi outra instancia com 3.3.1 funcionou amigo, vlw, mas o de vocês estão pegando o reply e os reactions ? o meu não está

Sim, mas precisa estar usando o mongo e também ativar para salvar as mensagens e chats.

**Comment by matiasduartee** [comment]
> Subi outra instancia com 3.3.1 funcionou amigo, vlw, mas o de vocês estão pegando o reply e os reactions ? o meu não está


Esta de boa mano. Ativa isso aqui que é SUCESSO!

DATABASE_SAVE_DATA_NEW_MESSAGE=true # Habilita a nova função do Chatwoot 3.3.1 de responder a mensagem
DATABASE_SAVE_DATA_CHATS=true # Habilita a função de excluir a mensagem no chatwoot e mostrar como "Mensagem Apagada" no WhatsApp

**Comment by MoreiraTv** [comment]
Estou usando o mongo falta ativar para gravar as mensagens então

**Comment by MoreiraTv** [comment]
Opa deu certo agora, pft, para evitar falha de receber mensagens é bom usar o RabbitMQ e o redis ?

**Comment by ramilson27031980** [comment]
> ara evitar falha de receber mensagens é

Amigão, o que vc fez para resolver... 
Estou com mesmo problema...

**Comment by tvagenciariver** [comment]
o meu esta da mesma forma, parou do nada, ele ate cria a caixa quando coloco, mas não com o nome, fica sequencial
alguem conseguiu resolver?

**Comment by syncgrowai** [comment]
mesmo problema aqui

**Comment by syncgrowai** [comment]
resolvido, meu imbox estava errado, o id era 1 e eu estava ponto um novo, ou seja pra criar em uma conta nova voce tem primeiro que criar a conta e saber o id dela
