### ISSUE TITLE
can we change language to english 

### ISSUE THREAD

**Issue by drdaga** [EvolutionAPI/evolution-api#265]
Can we change language to english as i m based from india cannot understand Portuguese

**Comment by DavidsonGomes** [comment]
I understand, the documentation is already in English, what does it refer to?

**Comment by drdaga** [comment]
i mean the manager panel ( Evolution Panel Manager)

**Comment by DavidsonGomes** [comment]
Got it, let's adjust that, thanks for the suggestion

**Comment by gabrielpastori1** [comment]
The manager was 100% translated into English starting from version 0.4.8
![image](https://github.com/EvolutionAPI/evolution-api/assets/58153955/a4c881d8-15bf-4e3d-9cbc-41b309ea03cb)
