### ISSUE TITLE
[Feature-Request] Reply messages com reopen conversation desativado - Reply de mensagens antigas

### ISSUE THREAD

**Issue by francisbreit** [EvolutionAPI/evolution-api#266]
Cenário: Evolution 1.6.0 com chatwoot 3.3.1.. Reopen Conversation desativado
Em casos mais raros e específicos pode acontecer a situação de um contato reabrir um novo ticket e marcar mensagem mais antiga (respondida em outro ID de conversa, ou seja de uma conversa anterior resolvida).  
Seria o melhor dos mundos se  essa mensagem mais antiga marcada pelo contato aparecesse marcada no Chatwoot, na atual conversa reaberta. Ficando evidente para o agente atual.

**Comment by DavidsonGomes** [comment]
Isso é relacionado ao chatwoot, não tem oq fazer daqui
