### ISSUE TITLE
Imagem a versão de homologação v1.6.1 não sobe no docker.

### ISSUE THREAD

**Issue by daniloruizdasilva** [EvolutionAPI/evolution-api#267]
@DavidsonGomes, faltou adicionar esses parâmetros no arquivo ENV de exemplo.

- SERVER_TYPE=http
- SERVER_PORT=8080
Pessoal estavam reclamando que não conseguia subir a imagem da versão de homologação (v1.6.1), analisei as alterações no código, aí adicionei esses dois parâmetros e a imagem subiu.

**Comment by matiasduartee** [comment]
@DavidsonGomes esses parâmetros são mesmo obrigatório?

**Comment by williamzzz1** [comment]
Aqui estava dando conflito nas instancias depois que atualizei pra 1.6.0 e depois que adicionei os parametros resolveu!
