### ISSUE TITLE
Downgrade da v1.6.0 para v1.5.4 ou posterior (Cannot read properties off null (reading 'apikey'))

### ISSUE THREAD

**Issue by matiasduartee** [EvolutionAPI/evolution-api#268]
Levando em consideração a utilização da versão 1.6.0 conectado ao mongodb e ao tentar realizar o downgrade para a versão 1.5.4 o manager não permite mais o acesso ao gerenciamento das instancias, apresentando o seguinte erro:

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/8a8ab909-881a-4889-830b-5741b73c0888)

A solução que encontrei foi passar a env da Evolution um novo prefixo para o bando de dados mongo, pois com o banco zerado é possível se conectar ao manager, sem trocar apikey ou oque quer que seja. 

`- DATABASE_CONNECTION_DB_PREFIX_NAME=novo_Prefixo`

**Comment by PaivaRicard** [comment]
Tive o mesmo Problema, ao migrar para a versão 1.6.0 e depois fazer downgrade para 1.5.4 o manager não permitia mais acesso. fiz alguns passos, voltei minha stack para a versão 1.6.0, deletei a instancia que estava sem ID e voltei minha stack novamente para 1.5.4, consegui acessar, porem não demorou muito a instancia que ainda estava conectada perdeu seu ID e novamente o acesso ao manager foi prejudicado, a solução foi o que o Matias colocou acima, criar um novo banco com a versão 1.5.4

**Comment by DavidsonGomes** [comment]
Corrigido problema na v1.6.1 atualmente em develop
