### ISSUE TITLE
typebot 2.18 e evo homolog ou 1.6.0  para iniciar o bot, tem mandar a mensagem 2 vezes

### ISSUE THREAD

**Issue by linkincharles** [EvolutionAPI/evolution-api#269]
para iniciar o bot esta tendo que mandar 2 vezes a mensagem para começar o bot, tanto na 1.6.0 e na versao homolog 
![image](https://github.com/EvolutionAPI/evolution-api/assets/52577415/9b3adfdf-a8be-4f2a-808a-91f5d8f77d47)

**Comment by matiasduartee** [comment]
Up!

**Comment by DavidsonGomes** [comment]
Problema sendo discutido na issue #289
