### ISSUE TITLE
[BUG] Responder a Mensagem não funcionando corretamente [Woot 3.1.1 & Evo 1.6]

### ISSUE THREAD

**Issue by stgcompany** [EvolutionAPI/evolution-api#270]
A funcionalidade de responder a mensagens especificas não está funcionando corretamente. Pelos meus testes ele na grande maioria das vezes seleciona a mensagem errada para responder. Segue a seguir prints de exemplo...

## Conversa no Chatwoot 3.1.1:
![Screenshot from 2023-12-14 14-07-55](https://github.com/EvolutionAPI/evolution-api/assets/143809393/a6f17a8b-6a90-420f-be8e-6324ab8340b0)

## Conversa no Whatsapp conectado no evolution 1.6:
![image](https://github.com/EvolutionAPI/evolution-api/assets/143809393/ece91d2f-b2f1-4b78-bca8-7ec13b969947)

**Comment by lindenbergp** [comment]
Mongo ta ativado pra salvar as mensagens?

**Comment by stgcompany** [comment]
> Mongo ta ativado pra salvar as mensagens?

Não, no caso ele só funcionaria dessa forma?

**Comment by matiasduartee** [comment]
> > Mongo ta ativado pra salvar as mensagens?
> 
> Não, no caso ele só funcionaria dessa forma?


Você tem que ativar as seguintes opções: detalhe descobri isso só testando amigo, não achei lugar nenhum falando.
 - DATABASE_SAVE_DATA_NEW_MESSAGE=true # Habilita a nova função do Chatwoot 3.3.1 de responder a mensagem
 - DATABASE_SAVE_DATA_CHATS=true # Habilita a função de exluir a mensagem no chatwoot e mostrar como "Mensagem Apada" no WhatsApp

**Comment by stgcompany** [comment]
Valeu meu amigo! Problema solucionado! <3

**Comment by tiagoshark** [comment]
> > > Mongo ta ativado pra salvar as mensagens?
> > 
> > 
> > Não, no caso ele só funcionaria dessa forma?
> 
> Você tem que ativar as seguintes opções: detalhe descobri isso só testando amigo, não achei lugar nenhum falando.
> 
> * DATABASE_SAVE_DATA_NEW_MESSAGE=true # Habilita a nova função do Chatwoot 3.3.1 de responder a mensagem
> * DATABASE_SAVE_DATA_CHATS=true # Habilita a função de exluir a mensagem no chatwoot e mostrar como "Mensagem Apada" no WhatsApp

Onde eu acho esse arquivo para alterar?

**Comment by ImCylon** [comment]
> > > > Mongo ta ativado pra salvar as mensagens?
> > > 
> > > 
> > > Não, no caso ele só funcionaria dessa forma?
> > 
> > 
> > Você tem que ativar as seguintes opções: detalhe descobri isso só testando amigo, não achei lugar nenhum falando.
> > 
> > * DATABASE_SAVE_DATA_NEW_MESSAGE=true # Habilita a nova função do Chatwoot 3.3.1 de responder a mensagem
> > * DATABASE_SAVE_DATA_CHATS=true # Habilita a função de exluir a mensagem no chatwoot e mostrar como "Mensagem Apada" no WhatsApp
> 
> Onde eu acho esse arquivo para alterar?

No seu arquivo de configuração da evolution .yaml
