### ISSUE TITLE
Não é possível conectar uma instância que foi desconectada

### ISSUE THREAD

**Issue by dlc-letelier** [EvolutionAPI/evolution-api#271]
Tem algum problema pelo qual, quando uma instância é desconectada ou perde a conexão, quando se tenta conectar de novo, não gera o QR. Ou melhor, aparece no manager, mas não aparece no log. Pareceria que a conexão é fechada antes.

<img width="683" alt="image" src="https://github.com/EvolutionAPI/evolution-api/assets/60855725/7937f0bd-8ae7-4e33-af4c-237127e70810">

O único jeito é apagar a instancia e criar uma nova.

**Comment by lindenbergp** [comment]
Constatei o mesmo erro. Se desconectar uma instancia ela nao gera um novo qr code.
![image](https://github.com/EvolutionAPI/evolution-api/assets/24882737/6116ff57-5090-4198-9f3b-14c8d38a90c8)
A resposta vem vazio no postman. Versão 1.6.1 homolog.
tenho que apagar e criar novamente a instancia.

**Comment by matiasduartee** [comment]
Amigo, tenta excluir essa instancia e reconectar novamente, isso aconteceu comigo e só funcionou assim, ah e ela foi desconectada pois mudar o numero de whatsapp de aparelho.

**Comment by lindenbergp** [comment]
> Amigo, tenta excluir essa instancia e reconectar novamente, isso aconteceu comigo e só funcionou assim, ah e ela foi desconectada pois mudar o numero de whatsapp de aparelho.

Essa solução eu ja usei, so que nao era assim. Podia desconectar e conectar novamente.

**Comment by matiasduartee** [comment]
> > Amigo, tenta excluir essa instancia e reconectar novamente, isso aconteceu comigo e só funcionou assim, ah e ela foi desconectada pois mudar o numero de whatsapp de aparelho.
> 
> Essa solução eu ja usei, so que nao era assim. Podia desconectar e conectar novamente.


Então esse é um caso para o @DavidsonGomes analisar com calma!

**Comment by tiefighter** [comment]
Mesmo erro detectado aqui na v1.6.0
Alguma solução?

**Comment by stgcompany** [comment]
Mesmo problema aqui, vou ter que excluir e criar novamente, por enquanto.

Inclusive quando conecto aparece o seguinte erro no logger:

```bash
{"level":50,"time":1702934172054,"pid":832170,"hostname":"stagebot","node":{"tag":"stream:error","attrs":{"code":"515"}},"msg":"stream errored out"}
```

![image](https://github.com/EvolutionAPI/evolution-api/assets/143809393/97e9d697-f5c2-49eb-914a-31b2d6453111)

**Comment by matiasduartee** [comment]
> Mesmo problema aqui, vou ter que excluir e criar novamente, por enquanto.
> 
> Inclusive quando conecto aparece o seguinte erro no logger:
> 
> ```shell
> {"level":50,"time":1702934172054,"pid":832170,"hostname":"stagebot","node":{"tag":"stream:error","attrs":{"code":"515"}},"msg":"stream errored out"}
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/143809393/291410751-97e9d697-f5c2-49eb-914a-31b2d6453111.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MzQ2MTQsIm5iZiI6MTcwMjkzNDMxNCwicGF0aCI6Ii8xNDM4MDkzOTMvMjkxNDEwNzUxLTk3ZTlkNjk3LWY1YzItNDllYi05MTRhLTMxYjJkNjQ1MzExMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQyMTE4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmViYjUzOGRiOWU1MzA0MTI4NWNlMjhmM2ViMTNkNGE1NTM1ZjFkYTQ4NDdjYjc2ZjQxMjdjZDBmMTI4MmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FDGZnili_0pqAqxOh3GHgP8mTUt1-2UMuw83KDDVddo)

exatamente!

**Comment by stgcompany** [comment]
Testei aqui pelo contato no chatwoot e ao invés de conectar ele fica mostrando o status da instância.

![image](https://github.com/EvolutionAPI/evolution-api/assets/143809393/dbc452c4-a50a-4f26-bf6b-65f821725c12)

OBS.: As últimas duas mensagens foram pela api.

E no logger fica aparecendo ação de logout

![image](https://github.com/EvolutionAPI/evolution-api/assets/143809393/12baf93e-d9c0-424b-9014-077b4c7ce15b)

**Comment by DavidsonGomes** [comment]
Corrigido problema na v1.6.1 atualmente em develop

**Comment by JNNelson** [comment]
Vou comentar neste topico porque o [stgcompany](https://github.com/stgcompany) postou telas semelhantes.
Fiz a integracao da evolution api com chatwoot. O que ocorre é que nao é gerado o qrcode, so aparece a msg INIT.
No manager da api, o qrcode é gerado, o problema esta em recebe-la no chatwoot, mas acrescento que estou fazendo teste em localhost, assim a pergunta que faço é se no ambiente de localhost deveria funcionar ou nao.
