### ISSUE TITLE
API fica conectando e desconectando após mensagem de erro 

### ISSUE THREAD

**Issue by dlc-letelier** [EvolutionAPI/evolution-api#272]
Por algum motivo, a API entra num loop e fica reiniciando a conexão após a mensagem "stream errored out".

evolution_api                  | [Evolution API]  v1.6.0  1   -  Thu Dec 14 2023 14:45:59     INFO   [WAStartupService]  [string]  
evolution_api                  |   ┌──────────────────────────────┐
evolution_api                  |   │    CONNECTED TO WHATSAPP     │
evolution_api                  |   └──────────────────────────────┘ 
evolution_api                  | {"level":50,"time":1702575960477,"pid":1,"hostname":"aeaf6c64112e","node":{"tag":"stream:error","attrs":{},"content":[{"tag":"conflict","attrs":{"type":"replaced"}}]},"msg":"stream errored out"}
evolution_api                  | [Evolution

**Comment by dlc-letelier** [comment]
A solução foi criar uma nova instancia com um novo nome, e conectar o telefone novamente. Entretanto, acaba perdendo a organização no Inbox do Chatwoot, pois as conversas para o mesmo contacto ficam em inbox diferentes

**Comment by lindenbergp** [comment]
> A solução foi criar uma nova instancia com um novo nome, e conectar o telefone novamente. Entretanto, acaba perdendo a organização no Inbox do Chatwoot, pois as conversas para o mesmo contacto ficam em inbox diferentes

tentou apagar e criar com o mesmo nome?

**Comment by dlc-letelier** [comment]
Tentei sim. Ela conecta, mas após enviar algumas mensagens, entra em loop conforme descrito acima, sempre apresentando o mesmo erro.

**Comment by wesleyareis** [comment]
Veja aqui #267
Tem que habilitar estas variáveis de ambientes na sua STACK para conseguir subir a imagem: atendai/evolution-api:homolog

**Comment by dlc-letelier** [comment]
Tentei fazer conforme indicado #267 mas mesmo assim continua num loop perpétuo. Entretanto, descobri que reiniciando a instancia de Docker, ele volta ao normal e inclusive ele deixa registrar uma instancia desconectada, conforme discutido em #271

**Comment by dlc-letelier** [comment]
Consegui mais uma informação: o loop começa quando mexo numa destas configurações. Logo após salvar, começa o erro e só normaliza após reiniciar o container.

<img width="967" alt="image" src="https://github.com/EvolutionAPI/evolution-api/assets/60855725/32974c13-2d17-4e88-8d1f-85b313d2e1cc">

**Comment by DavidsonGomes** [comment]
vamos verificar esse problema

**Comment by andersondiaspereira25** [comment]
Boa tarde
Você conseguiu resolver esse problema ?
Estou passando pela mesma situação !

**Comment by muhbianco** [comment]
same?

![Image](https://github.com/user-attachments/assets/585fd4ca-d3d3-4414-ba63-d2df17477a47)
