### ISSUE TITLE
Reinício indevido ao final do fluxo do Typebot.

### ISSUE THREAD

**Issue by brunopinto123** [EvolutionAPI/evolution-api#273]
Ao chegar no final do fluxo do Typebot, antigamente a sessão permanecia opened. Ou seja, caso o usuário mandasse qualquer nova mensagem ao término do fluxo, nada acontecia...

Nesta nova versão da evolution (latest e homolog), ao chegar no final do fluxo, a sessão é fechada (closed). Ou seja, se o usuário enviar qualquer texto após o término do fluxo, o sistema reenvia o fluxo novamente para o usuário...

Isto nos gera muito problemas, no meu fluxo por exemplo, um delivery, ao final é normal o usuário mandar alguma mensagem, como por exemplo: quanto tempo de entrega...? está chegando...? Então neste meu exemplo, não faz sentido enviar um fluxo novamente pra ele do zero...

Na 1.5.4 não fechava a sessão ao término do fluxo...
Obrigado.

**Comment by matiasduartee** [comment]
Up!

**Comment by luiztonucci** [comment]
Up, testado e comprovado.

![iniciando fluxo novamente no final](https://github.com/EvolutionAPI/evolution-api/assets/82972632/3699a524-79c0-481a-8665-fbeac2450a40)

**Comment by Diglee147** [comment]
na verdade deveria terminar em paused...

**Comment by matiasduartee** [comment]
> na verdade deveria terminar em paused...

Não Não, opened já resolve, o que não pode e apagar a sessão

**Comment by matiasduartee** [comment]
Repliquei aqui o erro que o @brunopinto123 comentou e isso esta ocorrendo na versão homolog, 

Testei também na versão 1.6.0, onde não ocorre esse problema, chegando no final do fluxo o bot fica como "opened" e não responde mais. 

```
{
  "typebot": {
    "instanceName": "instanciatester",
    "typebot": {
      "enabled": true,
      "url": "https://typebotapi.br",
      "typebot": "testeachei-zb415yg",
      "expire": 15,
      "keyword_finish": "#sair",
      "delay_message": 1500,
      "unknown_message": "Mensagem não suportada!",
      "listening_from_me": false,
      "sessions": [
        {
          "prefilledVariables": {
            "remoteJid": "550000000000@s.whatsapp.net",
            "pushName": "Matias Duarte"
          },
          "remoteJid": "550000000000@s.whatsapp.net",
          "sessionId": "2311243579-clq5nznow000pp80fh0cybwuv",
          "status": "opened",
          "createdAt": 1702586412486,
          "updateAt": 1702586435253,
          "_id": "657b682c4cb92cf107d524c8"
        }
      ]
    }
  }
}
```

Já na versão homolog, o status da sessão tbm fica como "opened" porém o bot é acionado ao mandar qualquer mensagem. 

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/c9b424d2-4e3f-4a61-b860-895b3ee6e7bb)

**Comment by brunopinto123** [comment]
o correto é deixar como opened, porque existem vários cenários de fluxos, aonde é normal e esperado o cliente mandar alguma mensagem no final do fluxo... então precisa ser como era antes, ou sejam, terminar como "opened".... deixando o temporizador definido no manager, fechar a sessão...

**Comment by matiasduartee** [comment]
> o correto é deixar como opened, porque existem vários cenários de fluxos, aonde é normal e esperado o cliente mandar alguma mensagem no final do fluxo... então precisa ser como era antes, ou sejam, terminar como "opened".... deixando o temporizador definido no manager, fechar a sessão...

Concordo com você Bruno. Teria que ser como antes ao final do fluxo o bot suspende o envio das mensagens e passa a valer o temporizador.

**Comment by gabrielpastori1** [comment]
Esse comportamento foi adicionado na ultima versão da develop, a API por padrão irá fechar a sessão ao final da sessão, para alterar o comportamento e ela manter a conexão como `opened` é preciso adicionar um novo env `TYPEBOT_KEEP_OPEN=true`

**Comment by brunopinto123** [comment]
resolvido!
obrigado Gabriel e Davidson!!!
basta subir a nova homolog e adicionar a variável:

TYPEBOT_KEEP_OPEN=true

Top demais. Obrigado.

**Comment by matiasduartee** [comment]
> TYPEBOT_KEEP_OPEN=true

@gabrielpastori1 isso será definitivo a partir da versão 1.6.1?

**Comment by gabrielpastori1** [comment]
Sim, já foi adicionado na develop, será liberado na main quando a versão 1.6.1 for lançada

**Comment by joweste** [comment]
> > o correto é deixar como opened, porque existem vários cenários de fluxos, aonde é normal e esperado o cliente mandar alguma mensagem no final do fluxo... então precisa ser como era antes, ou sejam, terminar como "opened".... deixando o temporizador definido no manager, fechar a sessão...
> 
> Concordo com você Bruno. Teria que ser como antes ao final do fluxo o bot suspende o envio das mensagens e passa a valer o temporizador.

Pelo que entendo, o proprio typebot fecha a sessão quando não há mais blocos a seguir, quer o evolution ou outra api queira ou não.  Dai se um, usuario manda uma nova mensagem, ele responde com 404, (SESSION_NOT_FOUND).  O evolution e outras api que interagem com o typebot, se quiserem prosseguir com o fluxo do typebot, precisam detectar o 404, e só tem uma alternativa: Recriar a  sessão do typebot.   Agora, isso nao quer dizer que eles precisam fechar a sessão do whatsapp do  usuário. Talvez configurar uma mensagem no typebot a ser enviada ao usuario seja uma boa coisa. Por exemplo: 'Seu pedido foi realizado, se quiser fazer novo pedido por favor digite XXXX'.   Essse XXXX tambem precisaria ser configurado no evolution ou outra api.

**Comment by gabrielpastori1** [comment]
> Pelo que entendo, o proprio typebot fecha a sessão quando não há mais blocos a seguir, quer o evolution ou outra api queira ou não.

Não é o caso, a sessão quem faz o gerenciamento de sessão é a evolution e não o typebot, na ultima versão foi possível identificar o fim do fluxo e fechar automaticamente a sessão na evolution, o que foi feito na 1.6.1 da api é adicionar um env `TYPEBOT_KEEP_OPEN` que ao identificar o final do fluxo do typebot não encerra a sessão na API, mantendo ela com o status open porem sem interagir mais com o bot

**Comment by valmeidavr** [comment]
estou utilizando o easypanel onde coloco TYPEBOT_KEEP_OPEN=true

**Comment by valmeidavr** [comment]
Deu certo aqui. Alterei na evolution.

**Comment by zeroonend** [comment]
vc alterou no env. da evolution api ou do typebot ? tb uso o o easypanel.

**Comment by in5-alassis** [comment]
fala pessoal, tem como deletar a sessão via API postman ?
Meu caso, é que o lead so consegue voltar a falar com o bot se deleto a sessão dele, está estranho esse comportamento ?
versão 2.1.2

**Comment by tvagenciariver** [comment]
Vou falar como consegui resolver na evo 2 , antes o fluxo ou ficava off ou reiniciava quando falava depois de redirecionar para o atendimento, 

primeiro coisa a fazer é  um jumper ou loop no fluxo do typebot

![image](https://github.com/user-attachments/assets/c5217ad1-081b-4394-94d7-6a9de6576096)

e depois configurar normalmente na evo o tempo que vai expirar apos n haver interação nenhuma, 

Obs:  o problema é que ao inves de matar a sessão ele cria uma nova cada vez que passa o tempo e o cliente interage iniciando novamente o fluxo

![image](https://github.com/user-attachments/assets/4a1f5448-7b0a-4c2e-8c04-f82a1e00a13f)

mas......... pelo menos  funciona normalmente! 
depois vou ver se tem algum comando via N8N pra zerar os conexoes tipo  meia noite.

**Comment by in5-alassis** [comment]
Entendi, coloquei um loop aqui pra testar, mas continua mesma coisa.
Usuário novo chama o bot, depois que finaliza não consegue mais chamar, so excluindo a sessão na EVO.
pra ajudar não tem uma api para excluir sessão, se tivesse ja passava um http no fim do fluxo e resolvia isso.

![erro evo](https://github.com/user-attachments/assets/1e4577ad-998d-4c45-9305-745744b49808)


no whats pode chamar o bot a vontade que não responde mais
![image](https://github.com/user-attachments/assets/1dca0781-1e24-4fff-9b9f-1a46db7596f8)


agora se excluir a sessão vai funcionar
![image](https://github.com/user-attachments/assets/8f7ff104-ad7e-497e-a042-ac0d2504c439)

whats
![image](https://github.com/user-attachments/assets/4401d54b-0dd4-4e24-bafd-17bf950ce831)

**Comment by Kadu325** [comment]
> Entendi, coloquei um loop aqui pra testar, mas continua mesma coisa. Usuário novo chama o bot, depois que finaliza não consegue mais chamar, so excluindo a sessão na EVO. pra ajudar não tem uma api para excluir sessão, se tivesse ja passava um http no fim do fluxo e resolvia isso.
> 
> ![erro evo](https://private-user-images.githubusercontent.com/79283206/379775144-1e4577ad-998d-4c45-9305-745744b49808.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MTY5MDcsIm5iZiI6MTcyOTgxNjYwNywicGF0aCI6Ii83OTI4MzIwNi8zNzk3NzUxNDQtMWU0NTc3YWQtOTk4ZC00YzQ1LTkzMDUtNzQ1NzQ0YjQ5ODA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDAwMzY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkOGE2YTZiMzAzOTU0ZmNjNmJmMWI2ODI5ODk1ZGE2NWVhYTE5NjdhNGU0YTQ5MzQ2Yjk2MmVlMmNhNjEzYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5nN3SDes9bJmOsM7P8hec44I3z-US4Tk0jKlTis7pdc)
> 
> no whats pode chamar o bot a vontade que não responde mais ![image](https://private-user-images.githubusercontent.com/79283206/379775542-1dca0781-1e24-4fff-9b9f-1a46db7596f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MTY5MDcsIm5iZiI6MTcyOTgxNjYwNywicGF0aCI6Ii83OTI4MzIwNi8zNzk3NzU1NDItMWRjYTA3ODEtMWUyNC00ZmZmLTliOWYtMWE0NmRiNzU5NmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDAwMzY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNGNmYTJlMTRjNGI4Y2IxOGQ0YzgxNDk4Y2M0ZDJmMWE1YTVhYWYwNDhlMDE0Njg5MTg5YTM1MTU4ZmUzYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jpKZvsf-RC7NZUSAOkQK2ZMgLglfZsFMQ0r6yzni6XA)
> 
> agora se excluir a sessão vai funcionar ![image](https://private-user-images.githubusercontent.com/79283206/379775763-8f7ff104-ad7e-497e-a042-ac0d2504c439.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MTY5MDcsIm5iZiI6MTcyOTgxNjYwNywicGF0aCI6Ii83OTI4MzIwNi8zNzk3NzU3NjMtOGY3ZmYxMDQtYWQ3ZS00OTdlLWEwNDItYWMwZDI1MDRjNDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDAwMzY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNmY4MGEyMjgwYjc1ZTFlNTQwM2VkZDViYmM0NGZlMjU2ZWFmODU3Nzg2MDQ0MzJlMzY1ZDNjZjkxMDM2NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xguIjG9jK50deiNl8jzONdmV6flBNR-s8Cq1Po-J6Nc)
> 
> whats ![image](https://private-user-images.githubusercontent.com/79283206/379775988-4401d54b-0dd4-4e24-bafd-17bf950ce831.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MTY5MDcsIm5iZiI6MTcyOTgxNjYwNywicGF0aCI6Ii83OTI4MzIwNi8zNzk3NzU5ODgtNDQwMWQ1NGItMGRkNC00ZTI0LWJhZmQtMTdiZjk1MGNlODMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDAwMzY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxOGQyY2JiYWU0NWNhMDZlNWVlNzdjNWU5MGM1OTExMDc1MzExMTgyMzE1NzBhMmM3YzQ1NzRkYjM2Zjk4YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uDHM6WO4eIxMsGhwihJI654u4h68Owrx_MiV3xJzYpY)






Na verdade na mesma url de change status consegue mudar a sessão trocando no json "closed" por "delete", estou com esse problema também

**Comment by in5-alassis** [comment]
Então é bug mesmo ? será que os cara vai corrigir isso ?

**Comment by in5-alassis** [comment]
fiz esse esquema de deletar sessão via http e funcionou perfeitamente.
Obrigado pela dica

**Comment by pbrumoliver** [comment]
Meu typebot estava funcionando normalmente, faz uns 2 dias que parou, mesma questão acima quando um número de WhatsApp chama o bot pela primeira vez, o bot responde, aí depois não mais. Lembrando que criei um fluxo com ia, alguem sabe me dizer oq pode ser?
