### ISSUE TITLE
Problema ao tentar realizar qualquer consulta na parte de Chat Controller

### ISSUE THREAD

**Issue by MarksEliel** [EvolutionAPI/evolution-api#274]
Não consigo por exemplo, através do /docs/ ou postman trazer a lista de conversas da minha instancia:
![image](https://github.com/EvolutionAPI/evolution-api/assets/15361130/aebf60d0-3ce2-4e9b-9d66-7eef761c4c86)

**Comment by MarksEliel** [comment]
consegui realizar via postman, criando uma nova instancia e configurando CLEAR STORE CHATS como FALSE
outra questão que percebi é que só consigo puxar 500 conversas, existe alguma forma de puxar TODAS?

**Comment by DavidsonGomes** [comment]
Esse endpoint funciona melhor quando utilizado o mongodb
