### ISSUE TITLE
Responder mensagem especifica via chatwoot

### ISSUE THREAD

**Issue by williamzzz1** [EvolutionAPI/evolution-api#277]
Atualizei para ultima versão da Evolution 1.6.0 e estou usando chatwoot tbm na sua ultima versão 3.3.1.

Quando respondo uma mensagem lá no chatwoot, lá no whatsapp responde sempre a uma mesma mensagem até mesmo em chats diferentes... No caso um Survey.

Esse survey foi a primeira mensagem que o chatwoot enviou depois que atualizei a versão da Evo, no caso eu finalizei a conversa pra iniciar uma nova e testar a função de responder.

No Chatwoot:
![image](https://github.com/EvolutionAPI/evolution-api/assets/52936830/6dce91f6-2710-4639-bcef-d5262dcbe92a)

No Whatsapp:
![image](https://github.com/EvolutionAPI/evolution-api/assets/52936830/d87469bd-59a0-45f9-a26e-02a6fba1276f)

Log: 
![image](https://github.com/EvolutionAPI/evolution-api/assets/52936830/89c47c1d-b414-40bf-9d12-21a6771cbc9a)

Fiz o teste em outra instância, e o problema é diferente, ele simplesmente responde uma mensagem que nem foi conversada, no caso responde a um status de não faço ideia de quem.

Chatwoot:
![image](https://github.com/EvolutionAPI/evolution-api/assets/52936830/963e45ff-23cc-448c-859d-f331abe29474)

Whatsapp:
![image](https://github.com/EvolutionAPI/evolution-api/assets/52936830/aa27e8ff-5525-4683-94ba-1debea60f53f)

Log: 
![image](https://github.com/EvolutionAPI/evolution-api/assets/52936830/c30da0a7-b7ca-464b-a53c-86170ba1024b)

**Comment by stgcompany** [comment]
Tive esse problema e um rapaz me deu a solução nesta issue: https://github.com/EvolutionAPI/evolution-api/issues/270

**Comment by DavidsonGomes** [comment]
Problema resolvido na issue #292 270
