### ISSUE TITLE
[Feature] Logs de Erro com Timestamp

### ISSUE THREAD

**Issue by stgcompany** [EvolutionAPI/evolution-api#281]
Acredito que seria interessante realizar o registro de erros com timestamp para sabermos o momento exato dos erros, principalmente para metrificar tempo com ou sem erros, downtime e tudo mais.

**Comment by DavidsonGomes** [comment]
Todos os logs tem informação de de quando foi gerado

![image](https://github.com/EvolutionAPI/evolution-api/assets/24706726/77bb0b23-6b04-41ff-8a97-4cbeb21ad54a)

**Comment by stgcompany** [comment]
É que no meu caso estava visualizando os logs de erro gerados no arquivo do pm2. Aí nestes não fica registrado, por isso esse meu desejo. Não sei se é um problema do pm2 em sí.
