### ISSUE TITLE
1.6.1 - Typebot GPT Chat Completion - Duplicating messages

### ISSUE THREAD

**Issue by drauber** [EvolutionAPI/evolution-api#287]
After update Evolution to 1.6.1, Typebot to 2.20 and set the env to use latest version, using a GPT Chat Completion the response is showing duplicated on client whatsapp, like this
![PrintIssue](https://github.com/EvolutionAPI/evolution-api/assets/4416953/67a0ccd1-673e-4800-a0fe-289dff465361)

**Comment by stgcompany** [comment]
Por obséquio... Onde que tá essa 1.6.1? Aqui só tô vendo a 1.6 sendo a mais recente

**Comment by matiasduartee** [comment]
> Por obséquio... Onde que tá essa 1.6.1? Aqui só tô vendo a 1.6 sendo a mais recente

A 1.6.1 é a versão homolog amigo.

**Comment by gabrielpastori1** [comment]
Como isso está configurado no typebot?

**Comment by drauber** [comment]
> Como isso está configurado no typebot?

![ChatSequence](https://github.com/EvolutionAPI/evolution-api/assets/4416953/a26cfe87-c10e-4aad-952c-4185cfc94fb9)
[ExemploTypebotGPT.json](https://github.com/EvolutionAPI/evolution-api/files/13694278/ExemploTypebotGPT.json)


Assim ajuda @gabrielpastori1?

**Comment by DavidsonGomes** [comment]
Consegue me passar o share de api do seu fluxo? vamos analisar como esta o retorno na api para conseguir atualizar isso

**Comment by drauber** [comment]
> Consegue me passar o share de api do seu fluxo? vamos analisar como esta o retorno na api para conseguir atualizar isso

Opa! O fluxo está anexo, logo abaixo do print do fluxo. É isso que vc precisa?
[ExemploTypebotGPT.json](https://github.com/EvolutionAPI/evolution-api/files/13713500/ExemploTypebotGPT.json)

Se for outra coisa, avisa aí que compartilho. 

Obg

**Comment by DavidsonGomes** [comment]
pelos nossos testes esse formato ai ja esta sendo entregue pelo typebot, portanto verifique a sua variavel que esta mandando para resposta, valide pelo preview do proprio typebot

<img width="706" alt="Screenshot 2023-12-19 at 15 47 40" src="https://github.com/EvolutionAPI/evolution-api/assets/24706726/748f240c-a861-457b-8176-53ec64839f8f">

**Comment by drauber** [comment]
> pelos nossos testes esse formato ai ja esta sendo entregue pelo typebot, portanto verifique a sua variavel que esta mandando para resposta, valide pelo preview do proprio typebot
> 
Olha só, no preview do Typebot.. 
![TypeBotExemplo](https://github.com/EvolutionAPI/evolution-api/assets/4416953/a6567aba-e500-43a6-a3c4-86a491b80061)

**Comment by DavidsonGomes** [comment]
Estranho isso, pq na api chega exatamente como a evolution envia a mensagem, acredito que deva abrir uma issue no typebot, mostrando o print da request na api

**Comment by drauber** [comment]
> Estranho isso, pq na api chega exatamente como a evolution envia a mensagem, acredito que deva abrir uma issue no typebot, mostrando o print da request na api

Até pensei nisso, mas acredito que em outros contextos vir todas as mensagens pode ser útil. 
Eu fiz uma pequena adequação no typebot.services para tratar a mensagem quando vier um array. Posso abrir uma PR e vc revisa se acha que dá pra usar ou não. Pode ser?

:D

**Comment by drauber** [comment]
https://docs.typebot.io/breaking-changes
