### ISSUE TITLE
1.6.1- Homolog: Reply to não funciona para PDF (anexos)

### ISSUE THREAD

**Issue by francisbreit** [EvolutionAPI/evolution-api#288]
![Captura de Tela 2023-12-15 às 16 49 19](https://github.com/EvolutionAPI/evolution-api/assets/5285287/a8b1ec30-7094-41b1-b60a-938953fc8e12)
Conforme imagem em anexo. Reply to não está mostrado qual arquivo PDF foi marcado na conversa

**Comment by DavidsonGomes** [comment]
nao entendi bem, ele nao aparece respondido no whatsapp?

**Comment by jaison-x** [comment]
Este é o comportamento de mensagem respondida do chatwoot. A evolution não consegue alterar este comportamento/funcionamento. Esta issue deveria ser aberta no repo do chatwoot.

**Comment by francisbreit** [comment]
> Este é o comportamento de mensagem respondida do chatwoot. A evolution não consegue alterar este comportamento/funcionamento. Esta issue deveria ser aberta no repo do chatwoot.

Bem lembrado. vale levantar uma issue no Chatwoot. Porém é bom estarmos de olho  pois reply to em anexos é muito comum de ocorrerem.
Realmente sao 2 questões uma quando o contato manda PDF marcado para o Chatwoot e outra quando o Chatwoot manda PDF/imagem marcado para o Contato.. Em ambas as situações o receptor da mensagem com anexo marcada não tem link clicável e ele não consegue ver qual é a mensagem anexo que foi referenciada pois não consegue ir até a mensagem original marcada.. Já em mensagem de texto isso funciona! O receptor clica e a tela leva atá a mensagem a original

**Comment by francisbreit** [comment]
> nao entendi bem, ele nao aparece respondido no whatsapp?

O receptor da mensagem com anexo marcada não tem um link clicável e ele não consegue ver qual é a mensagem com anexo que foi referenciada pois não consegue ir até a mensagem original marcada.. Já em mensagem de texto isso funciona! O receptor clica e a tela leva atá a mensagem original

**Comment by jaison-x** [comment]
> > Este é o comportamento de mensagem respondida do chatwoot. A evolution não consegue alterar este comportamento/funcionamento. Esta issue deveria ser aberta no repo do chatwoot.
> 
> Bem lembrado. vale levantar uma issue no Chatwoot. Porém é bom estarmos de olho pois reply to em anexos é muito comum de ocorrerem. Realmente sao 2 questões uma quando o contato manda PDF marcado para o Chatwoot e outra quando o Chatwoot manda PDF/imagem marcado para o Contato.. Em ambas as situações o receptor da mensagem com anexo marcada não tem link clicável e ele não consegue ver qual é a mensagem anexo que foi referenciada pois não consegue ir até a mensagem original marcada.. Já em mensagem de texto isso funciona! O receptor clica e a tela leva atá a mensagem a original

Acho que agora entendi o que você quer dizer. No whatsapp mobile, em mensagens de mídia realmente não aparece a mensagem marcada mas se você olhar no whats web verá que estas mesmas mensagenns estão marcadas normalmente.

Isso provavelmente é um bug da própria baileys, porque a evolution está marcando a mensagem mas no mobile ela não aparece como repondida. Isso acontece com mensagens do tipo de mídia e somente no mobile. Mensagens de texto funciona normal em ambos os ambientes.
