### ISSUE TITLE
Typebot 2.20.0  não reconhece a primeira mensagem quando se usa palavra chave . Evolution 1.6.0 Homolog

### ISSUE THREAD

**Issue by francisbreit** [EvolutionAPI/evolution-api#289]
1) Teste realizado com a Palavra chave  "menu":
![Captura de Tela 2023-12-16 às 11 14 45](https://github.com/EvolutionAPI/evolution-api/assets/5285287/78e143d3-01af-464a-be9e-bd492528bc1b)

2) Usando view, versão web, do Typebot a palavra chave é reconhecida na primeira tentativa:
![Captura de Tela 2023-12-16 às 07 54 35](https://github.com/EvolutionAPI/evolution-api/assets/5285287/2ee85982-a40c-42b4-804c-6f313a2a830c)
 
 3) No WhatsApp , é necessário que se digite a palavra chave uma segunda vez, para que funcione o bot:
 ![Captura de Tela 2023-12-16 às 08 04 57](https://github.com/EvolutionAPI/evolution-api/assets/5285287/4b2c3d8d-a496-4689-b06a-e928be4658fe)

**Comment by matiasduartee** [comment]
Acontece comigo também amigo!

**Comment by muriloorama** [comment]
tbm estou na mesma situação

**Comment by mxyzt** [comment]
I have the same problem

**Comment by francisbreit** [comment]
> > Opa. Acabei de subir a homolog de hoje (19/12/2023) e pelos teste prévios, agora está reconhecendo a palavra chave digitada inicialmente. Vou testar com mais inntancias e dou o aval final aqui, mas aparetemento, problema solucionado. Parabéns!
> 
> A Ultima versão homolog que vejo aqui e de 20 horas atrás, você não usa o Docker ne?
> 
> ![image](https://private-user-images.githubusercontent.com/81826268/291632095-441ee774-3128-4ff9-a40e-e498721cd9ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDE5OTUsIm5iZiI6MTcwMzAwMTY5NSwicGF0aCI6Ii84MTgyNjI2OC8yOTE2MzIwOTUtNDQxZWU3NzQtMzEyOC00ZmY5LWE0MGUtZTQ5ODcyMWNkOWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE2MDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NmVkMjMyYmM3NDQzOGQyODFjMDQ5ZDEyMTc5YWRmOTUyNjUyMjUyZjQwZDMyNGE5YTY5ZDJjYmJiYTk4MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xkplSdrmJp4o5SbAYTT5xc102r9E35DpoJxh4vpdiJs)

Uso docker swarm. a versao de  homolog  de ontem (20 horas atrás) está funcionando aqui sem precisar digitar 2 vezes.. Antes eu usava um Workflow do N8N para corrigir o problema.. Não está mais sendo necessário

**Comment by moanemanuel** [comment]
Companheiros, estou usando as últimas versões e notei que qualquer condição no início do fluxo, continua sem enviar mensagem no WhatsApp com a Evolution. Entretanto, se o inicio estiver diretamente ligado a um texto, ele reconhece a primeira mensagem e envia o texto. 

Percebi a particularidade apenas para quando no inicio, antes de enviar o texto existe uma condição.

**Comment by amandapessoadias** [comment]
Estou com a mesma dificuldade do [moanemanue](https://github.com/moanemanuel):

Companheiros, estou usando as últimas versões e notei que qualquer condição no início do fluxo, continua sem enviar mensagem no WhatsApp com a Evolution. Entretanto, se o inicio estiver diretamente ligado a um texto, ele reconhece a primeira mensagem e envia o texto.

Percebi a particularidade apenas para quando no inicio, antes de enviar o texto existe uma condição.
