### ISSUE TITLE
Falha com bad request e erro 404 ao tentar adicionar/remover novos membros em grupos.

### ISSUE THREAD

**Issue by wesleyhenriques33** [EvolutionAPI/evolution-api#291]
Endpoint para adicionar/remover participantes de grupo não está funcionando.

**Comment by DavidsonGomes** [comment]
Preciso de mais detalhes do erro, mostre como esta a sua requisição e logs da api

**Comment by DavidsonGomes** [comment]
Por falta de resposta estarei fechando a issue, caso precise reabra
