### ISSUE TITLE
Evo 1.6.1 (homolog) com Typebot 2.20.0, não escreve as variáveis em Negrito, Itálico ou Sublinhado

### ISSUE THREAD

**Issue by matiasduartee** [EvolutionAPI/evolution-api#292]
Pessoal, o meu objetivo é encontrar o máximo de bug e estar sempre reportando aqui. 

Se eu tentar deixar uma variável em negro para que aparece em negro na mensagem simplesmente ela não aparece, ao deixa-las normal sem nenhuma formatação a mesma é exibida corretamente. .

Este é o fluxo de exemplo:

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/d777e20b-030c-45b5-a3e1-0423047d9ef8)

Resultado da conversa:

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/54809841-fda2-404c-96a6-86da1cd9575e)

**Comment by francisbreit** [comment]
> Pessoal, o meu objetivo é encontrar o máximo de bug e estar sempre reportando aqui.
> 
> Se eu tentar deixar uma variável em negro para que aparece em negro na mensagem simplesmente ela não aparece, ao deixa-las normal sem nenhuma formatação a mesma é exibida corretamente. .
> 
> Este é o fluxo de exemplo:
> 
> ![image](https://private-user-images.githubusercontent.com/81826268/291065871-d777e20b-030c-45b5-a3e1-0423047d9ef8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MjQyOTQsIm5iZiI6MTcwMjgyMzk5NCwicGF0aCI6Ii84MTgyNjI2OC8yOTEwNjU4NzEtZDc3N2UyMGItMDMwYy00NWI1LWEzZTEtMDQyMzA0N2Q5ZWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDE0Mzk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMDk2OWI5OWQ4OGUzNGZiYWU3MDRjNTdhYzQ4YzRkM2I2ZjQ1ZDA0ZWM2ZTBjY2Q3YTg5Y2VlNmE0MzgzN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jUmhnTo_BirFTHiiCTbusX1jHRIJsN2BffRNBpkoH7s)
> 
> Resultado da conversa:
> 
> ![image](https://private-user-images.githubusercontent.com/81826268/291065960-54809841-fda2-404c-96a6-86da1cd9575e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MjQyOTQsIm5iZiI6MTcwMjgyMzk5NCwicGF0aCI6Ii84MTgyNjI2OC8yOTEwNjU5NjAtNTQ4MDk4NDEtZmRhMi00MDRjLTk2YTYtODZkYTFjZDk1NzVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDE0Mzk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzYzY5OGJmMGExZjU2MGM3ZDk2ODIxMjhmY2YwOGMzYWJiYTZiYjFlZjEzN2I1ZDNlNzM1YmI1N2NmYWJlMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mOAnO-MRMwFhHCxXMqKhStlasMY__xx7p5Tey3wKJcw)

Realmente, se usar o construtor do Typebot, esse problema está ocorrendo. Enquanto não temos a solução na Evolution, estou resolvendo de forma paleativa este problema usando o formato que usamos o próprio WhatsApp para formatar a variável em questão colocando a variável entre asteriscos para negrito ( exemplo: *{{name}}* ),  entre underline para itálico ( exemplo: _{{name}}_ ) , entre til para tachado ( exemplo ˜{{name}}˜ ) , etc
![Captura de Tela 2023-12-17 às 11 39 17](https://github.com/EvolutionAPI/evolution-api/assets/5285287/cd0ca9a3-d2c8-48b3-a01f-744c92713948)

**Comment by DavidsonGomes** [comment]
Ja sera corrigido na versao 1.6.1 que estar em homologação

**Comment by matiasduartee** [comment]
@DavidsonGomes segundo nosso amigo Edison Martins, esse problema ainda está ocorrendo na v1.6.1 com Typebot.
