### ISSUE TITLE
Erro ai listar instancias

### ISSUE THREAD

**Issue by suissa** [EvolutionAPI/evolution-api#294]
Em outra Evolution tá listando corretamente, mas mudo para outra instancia da Evolution me dá erro na listagem das instâncias

{
  "status": 500,
  "error": "Internal Server Error",
  "response": {
  "message": "Cannot read properties of null (reading 'apikey')"
}

A apikey ta adicionada

**Comment by DavidsonGomes** [comment]
Tudo bem, vamos analisar pra resolver, esta usando o mongodb correto?

**Comment by DavidsonGomes** [comment]
Corrigido problema na v1.6.1 atualmente em develop
