### ISSUE TITLE
Erro ao reconectar instancia inativa, não gera o qrcode no manager

### ISSUE THREAD

**Issue by matiasduartee** [EvolutionAPI/evolution-api#295]
Ao deixar uma instancia inativa, e ao tentar reconecta-la o manager não esta gerando o qrcode, para solucionar isso é preciso deletar a instância e recria-la com o mesmo nome para não perder as configurações. 

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/b3b9e86c-03d3-4cb9-828b-75f03facab83)

**Comment by tiefighter** [comment]
Mesmo problema. V1.6.0

**Comment by fabianob1m** [comment]
Aqui não tá nem deixando remover a instância para criar denovo.

{ "status": 400, "error": "Bad Request", "response": { "message": [ "[object Object]" ] } }

Versão 1.6.0 com MongoDB

**Comment by lindenbergp** [comment]
Tópico duplicado. Já tem um com mesmo #271

**Comment by DavidsonGomes** [comment]
Problema ja mencionado na issue #271, iremos analisar a situação
