### ISSUE TITLE
Erro ao tentar reconectar uma instância que foi desconectada

### ISSUE THREAD

**Issue by Daan2022** [EvolutionAPI/evolution-api#296]
Banco de dados usado MongoDB
versão: 1.6.0
Toda vez que desconecto uma instância e depois tento reconectar dá erro.

**Comment by matiasduartee** [comment]
Amigo esse problema ja foi reportado, e bem embaixo desse seu issues. 

Vamos mantar as boas praticas de dar uma pesquisadinha eheheheh. 

@DavidsonGomes finaliza esse issues para nao dar duplicidade. 

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/b1adbf33-0ffd-440c-a3f2-628cc67b1dd0)

**Comment by DavidsonGomes** [comment]
Issue duplicada #295
