### ISSUE TITLE
status: 400, error: 'Bad Request'

### ISSUE THREAD

**Issue by williamzzz1** [EvolutionAPI/evolution-api#297]
A cada 20 minutos acontece esse erro no log que acaba derrubando o contêiner

![image](https://github.com/EvolutionAPI/evolution-api/assets/52936830/1991fac0-3539-4ac0-8ee4-a89b17ddba09)

**Comment by DavidsonGomes** [comment]
tem alguma rotina fazendo verificação de numero?

**Comment by williamzzz1** [comment]
> tem alguma rotina fazendo verificação de numero?

Não. Mas percebi que sempre que acontece o erro tem uma verificação de jid com nome: status@broadcast

**Comment by williamzzz1** [comment]
Problema resolvido após atualizar para a versão 1.6.1
