### ISSUE TITLE
Erro ao enviar ao tentar enviar qualquer tipo de mídia (audio, img, doc, video) pelo chatwoot 3.3.1, utilizando a homolog 1.6.1

### ISSUE THREAD

**Issue by matiasduartee** [EvolutionAPI/evolution-api#298]
Erro ao enviar ao tentar enviar qualquer tipo de mídia (audio, img, doc, video) pelo chatwoot 3.3.1, utilizando a homolog 1.6.1

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/dccb7120-3df5-4b9c-af32-101cce8db971)

Detalhe que do cliente whatsapp e possível enviar img, doc, video.. somente o áudio vindo do cliente whatsapp não chega, erro abaixo. 
![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/154b6288-e3ce-4bb8-b240-856bc4d2af3b)

**Comment by stgcompany** [comment]
Aqui do mesmo jeito, única coisa que consegui foi receber imagens. Mas de resto não vai. Figurinhas, áudios, arquivos e outros.

**Comment by matiasduartee** [comment]
> Aqui do mesmo jeito, única coisa que consegui foi receber imagens. Mas de resto não vai. Figurinhas, áudios, arquivos e outros.

valeu amigo pela ajuda!

**Comment by DavidsonGomes** [comment]
Problema foi corrigido na versao 1.6.1 em develop, por favor testem e mandem um retorno
