### ISSUE TITLE
When run docker.sh

### ISSUE THREAD

**Issue by helioelias** [EvolutionAPI/evolution-api#3]
The last line "docker compose up -d" not work for me on Ubuntu 22.04.2 LTS and Linux Mint 21.1

**Comment by DavidsonGomes** [comment]
Make sure your machine has docker-compose installed and run docker.sh commands manually

docker network create -d bridge evolution-net

docker build -t evolution/api:local

docker-compose up -d

**Comment by DavidsonGomes** [comment]
due to lack of inactivity this issue is being closed, if you still have problems you can reopen
