### ISSUE TITLE
[REPORT] Configuração de sessão CONFIG_SESSION_PHONE_CLIENT

### ISSUE THREAD

**Issue by matiasduartee** [EvolutionAPI/evolution-api#300]
Na versão homolog não está sendo respeitado o nome da sessão de exibição. 

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/9fd73165-2f58-4024-99e2-4b26bf4b4c0b)

o que aparece:
![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/061c0ec5-ee72-4ef4-95cc-fabd82dcc926)

**Comment by DavidsonGomes** [comment]
Foi preciso fazer esse ajuste para voltar a funcionar a conexao com codigo de pareamento, ainda estamos vendo uma forma de contornar isso, mas o problema é na lib Baileys

**Comment by DavidsonGomes** [comment]
Por inatividade essa issue sera fechada, caso necessario reabra
