### ISSUE TITLE
[CHATWOOT] [ERRO AO APAGAR MENSAGEM]

### ISSUE THREAD

**Issue by luizdevoper** [EvolutionAPI/evolution-api#302]
Boa tarde,

Quando escrevo e envio 3 mensagens separadas no Chatwoot e apago a segunda mensagem, no WhatsApp a que é apagada é a 3 e não a 2.

Exemplo:
Mensagem 01: Olá
Mensagem 02: Tudo bem?
Mensagem 03: Como você está?

Apago a Mensagem 02 no Chatwoot , mas a que foi apagada no WhatsApp é a Mensagem 03

**Comment by stgcompany** [comment]
Você está usando o mongodb?

**Comment by viniciusdebruin** [comment]
https://github.com/EvolutionAPI/evolution-api/issues/263

Eu fiz o que o Davidson comentou e resolveu o apagar na parte do chatwoot, mas quando o cliente envia e apaga, ele não notifica no chatwoot que foi apagado.
Fiz o teste igual você falou e usando o mongodb ele apagou a segunda mensagem

**Comment by luizdevoper** [comment]
Vou fazer o teste aqui, valeu
