### ISSUE TITLE
Não recebimento de alguns chats (Chatwoot) - Evolution 1.6.0

### ISSUE THREAD

**Issue by viniciusdebruin** [EvolutionAPI/evolution-api#303]
Estou usando a versão 1.6.0 da evolution e v3.3.1 do chatwoot. Também estou utilizando docker com mongodb.
Teve 1 contato que me mandou recado e eu não recebi no chatwoot, somente no whatsapp, não são todos.
Notei também (Não que isso seja ruim), mas quando é enviado mensagens através de uma lista de transmissão para o meu contato, o chatwoot não lista (Eu não vejo problema nenhum nisso, mas só comentando que não é esse o caso do contato que me enviou o recado). Eu respondi o recado pelo whatsapp e mesmo assim não listou ele no chatwoot.
Porem, quando eu chamei ele pelo chatwoot e ele respondeu, ai voltou a funcionar, mas não listou a conversa anterior que não tinha sido registrada no chatwoot.

-----
Lembrando que ativei conforme orientação do Davidson
DATABASE_SAVE_DATA_INSTANCE=true
DATABASE_SAVE_DATA_NEW_MESSAGE=true

**Comment by luizdevoper** [comment]
Bom dia,
@DavidsonGomes estou com o mesmo problema, o Rabbitmq pode ajudar com esse problema?

**Comment by gabrielpastori1** [comment]
O Rabbitmq não interfere em nada o funcionamento do Chatwoot.

Você consegue enviar os logs ?

**Comment by luizdevoper** [comment]
ERRO AO CARREGAR O LOG


/root/.pm2/logs/ApiEvolution-error.log last 15 lines:
2|ApiEvolu | (node:2544256) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
2|ApiEvolu | 
2|ApiEvolu | Please migrate your code to use AWS SDK for JavaScript (v3).
2|ApiEvolu | For more information, check the migration guide at https://a.co/7PzMCcy
2|ApiEvolu | (Use `node --trace-warnings ...` to show where the warning was created)


MENSAGEM ENVIADA PELO CELULAR:
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [RedisCache]  [string]  writeData: session-553194648939.0 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [WAStartupService]  [string]  Finding settings 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [WAStartupService]  [string]  Getting instance name 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [SettingsRepository]  [string]  finding settings 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [SettingsRepository]  [string]  finding settings in db 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [WAStartupService]  [string]  Settings url: false 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [WAStartupService]  [string]  Settings msg_call:  
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [WAStartupService]  [string]  Settings groups_ignore: true 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [WAStartupService]  [string]  Settings always_online: false 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [WAStartupService]  [string]  Settings read_messages: false 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [WAStartupService]  [string]  Settings read_status: false 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [WAStartupService]  [string]  Listening event: messages.upsert 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [WAStartupService]  [string]  Event received: messages.upsert 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     LOG   [WAStartupService]  [object]   
2|ApiEvolution  | {
2|ApiEvolution  |   key: {
2|ApiEvolution  |     remoteJid: '553194648939@s.whatsapp.net',
2|ApiEvolution  |     fromMe: false,
2|ApiEvolution  |     id: '3AB1AF814FBA26E89F50',
2|ApiEvolution  |     participant: undefined
2|ApiEvolution  |   },
2|ApiEvolution  |   pushName: 'Luiz Felipe',
2|ApiEvolution  |   message: {
2|ApiEvolution  |     extendedTextMessage: ExtendedTextMessage { text: 'Opa', contextInfo: [ContextInfo] },
2|ApiEvolution  |     messageContextInfo: MessageContextInfo {
2|ApiEvolution  |       deviceListMetadata: [DeviceListMetadata],
2|ApiEvolution  |       deviceListMetadataVersion: 2
2|ApiEvolution  |     }
2|ApiEvolution  |   },
2|ApiEvolution  |   messageType: 'extendedTextMessage',
2|ApiEvolution  |   messageTimestamp: 1702999762,
2|ApiEvolution  |   owner: 'WhatsAppTeste',
2|ApiEvolution  |   source: 'ios'
2|ApiEvolution  | } 


ERRO:
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [WAStartupService]  [string]  Chatwoot reopen conversation: true 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [WAStartupService]  [string]  Chatwoot conversation pending: true 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [ChatwootService]  [string]  provider found 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [ChatwootService]  [string]  provider found 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [ChatwootService]  [string]  create client to instance: WhatsAppTeste 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [ChatwootService]  [string]  client created 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [ChatwootService]  [string]  update contact in chatwoot 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [ChatwootService]  [string]  contact updated 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     VERBOSE   [ChatwootService]  [string]  get contact conversations in chatwoot 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:29:22     ERROR   [ChatwootService]  [object]   
2|ApiEvolution  | TypeError: Cannot read properties of undefined (reading 'id')
2|ApiEvolution  |     at ChatwootService.<anonymous> (/home/evolution-api/dist/src/whatsapp/services/chatwoot.service.js:432:62)
2|ApiEvolution  |     at Generator.next (<anonymous>)
2|ApiEvolution  |     at fulfilled (/home/evolution-api/dist/src/whatsapp/services/chatwoot.service.js:5:58)
2|ApiEvolution  |     at runMicrotasks (<anonymous>)
2|ApiEvolution  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by luizdevoper** [comment]
QUANDO ENVIO UMA REAÇÃO TAMBÉM

```
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:02     VERBOSE   [WAStartupService]  [string]  Getting instance name 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:02     VERBOSE   [AuthRepository]  [string]  finding auth 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:02     VERBOSE   [AuthRepository]  [string]  finding auth in db 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [RedisCache]  [string]  writeData: session-553194648939.0 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [WAStartupService]  [string]  Finding settings 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [WAStartupService]  [string]  Getting instance name 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [SettingsRepository]  [string]  finding settings 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [SettingsRepository]  [string]  finding settings in db 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [WAStartupService]  [string]  Settings url: false 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [WAStartupService]  [string]  Settings msg_call:  
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [WAStartupService]  [string]  Settings groups_ignore: true 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [WAStartupService]  [string]  Settings always_online: false 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [WAStartupService]  [string]  Settings read_messages: false 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [WAStartupService]  [string]  Settings read_status: false 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [WAStartupService]  [string]  Listening event: messages.upsert 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [WAStartupService]  [string]  Event received: messages.upsert 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     LOG   [WAStartupService]  [object]   
2|ApiEvolution  | {
2|ApiEvolution  |   key: {
2|ApiEvolution  |     remoteJid: '553194648939@s.whatsapp.net',
2|ApiEvolution  |     fromMe: false,
2|ApiEvolution  |     id: '3A6475906D6DB87FAACC',
2|ApiEvolution  |     participant: undefined
2|ApiEvolution  |   },
2|ApiEvolution  |   pushName: 'Luiz Felipe',
2|ApiEvolution  |   message: {
2|ApiEvolution  |     messageContextInfo: MessageContextInfo {
2|ApiEvolution  |       deviceListMetadata: [DeviceListMetadata],
2|ApiEvolution  |       deviceListMetadataVersion: 2
2|ApiEvolution  |     },
2|ApiEvolution  |     reactionMessage: ReactionMessage {
2|ApiEvolution  |       key: [MessageKey],
2|ApiEvolution  |       text: '👍',
2|ApiEvolution  |       senderTimestampMs: [Long]
2|ApiEvolution  |     }
2|ApiEvolution  |   },
2|ApiEvolution  |   messageType: 'reactionMessage',
2|ApiEvolution  |   messageTimestamp: 1703000046,
2|ApiEvolution  |   owner: 'WhatsAppTeste',
2|ApiEvolution  |   source: 'ios'
2|ApiEvolution  | } 

2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [WAStartupService]  [string]  Chatwoot inbox name: WhatsAppTeste 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [WAStartupService]  [string]  Chatwoot sign msg: true 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [WAStartupService]  [string]  Chatwoot reopen conversation: true 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [WAStartupService]  [string]  Chatwoot conversation pending: true 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [ChatwootService]  [string]  provider found 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [ChatwootService]  [string]  provider found 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [ChatwootService]  [string]  create client to instance: WhatsAppTeste 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [ChatwootService]  [string]  client created 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [ChatwootService]  [string]  update contact in chatwoot 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [ChatwootService]  [string]  contact updated 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     VERBOSE   [ChatwootService]  [string]  get contact conversations in chatwoot 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     ERROR   [ChatwootService]  [object]   
2|ApiEvolution  | TypeError: Cannot read properties of undefined (reading 'id')
2|ApiEvolution  |     at ChatwootService.<anonymous> (/home/evolution-api/dist/src/whatsapp/services/chatwoot.service.js:432:62)
2|ApiEvolution  |     at Generator.next (<anonymous>)
2|ApiEvolution  |     at fulfilled (/home/evolution-api/dist/src/whatsapp/services/chatwoot.service.js:5:58)
2|ApiEvolution  |     at runMicrotasks (<anonymous>)
2|ApiEvolution  |     at processTicksAndRejections (node:internal/process/task_queues:96:5) 
2|ApiEvolution  | [Evolution API]  v1.6.0  2544256   -  Tue Dec 19 2023 12:34:06     WARN   [ChatwootService]  [string]  conversation not found 
```

**Comment by viniciusdebruin** [comment]
Na evolution 1.6.1 tem conversas que ainda não aparecem, tenho que responder pelo celular e algumas dessas depois de algumas interações aparecem, mas outras não. Porem, melhorou bastante a quantidade de mensagens que não apareciam antes, agora ocorre em menor numero
