### ISSUE TITLE
Instalação da API 1.6* com Docker/Portainer/NGINX

### ISSUE THREAD

**Issue by mariocarvalhope25** [EvolutionAPI/evolution-api#305]
Fiz a instalação da API versão 1.6 em ambiente docker com o nginx.
Porém, não consigo o acesso a API sem expor a porta.

Só consigo o acesso quando eu adiciono o "ports: - 8282:8080".

Como eu faço para acessar apenas pelo subdomínio sem a necessidade de export a porta?

Já criei as variáveis abaixo, mas não surtiu efeito:

      - SERVER_TYPE=http
      - SERVER_PORT=8080
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=sub.dominio.com.br
      - LETSENCRYPT_HOST=sub.dominio.com.br
      - LETSENCRYPT_EMAIL=email@gmail.com

Alguém poderia me ajudar?

**Comment by DavidsonGomes** [comment]
Se esta usando o nginx, vc precisa fazer o proxy reverso para a porta aberta no ports do docker

**Comment by DavidsonGomes** [comment]
Por inatividade essa issue sera fechada, caso necessario reabra
