### ISSUE TITLE
Evolution 1.6.1 homolog liberada Dec 19, 2023 at 7:09 pm

### ISSUE THREAD

**Issue by matiasduartee** [EvolutionAPI/evolution-api#311]
Sobre a ultima versão da homolog liberada **_Dec 19, 2023 at 7:09 pm_**, reportando aqui que realizei todos os testes de estabilidade na versão e tudo esta funcionando perfeitamente bem. 

Todos os pontos que acompanhei aqui de problemas nos issues, estão devidamente corrigidos. 

Caso alguém tenha alguma duvida de como estou com o .env configurado pode perguntar aqui. Estou utilizando o Docker Swarm, com Chatwoot 3.3.1, Typebot 2.20.0 e N8N.

Obrigado! @DavidsonGomes, @gabrielpastori1 e a todos da comunidade.

**Comment by DavidsonGomes** [comment]
Excelente, muito obrigado pelo feedback

**Comment by dersonbsb2022** [comment]
@matiasduartee voce conseguiu coletar a variavel pushname? no meu 1.6.1 nao funcionou.

**Comment by matiasduartee** [comment]
> @matiasduartee voce conseguiu coletar a variavel pushname? no meu 1.6.1 nao funcionou.

Consegui sim amigo! esta funcionando normalmente! Se o valor da variável não estiver aparecendo e se estiver em negrito, tenta coloca-lo sem nenhuma formatação de texto.

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/c3186d24-d980-4523-b342-69faeb26ab23)
