### ISSUE TITLE
Problema da issue #271 acontecendo somente com MongoDB ativado - 1.6.1

### ISSUE THREAD

**Issue by stgcompany** [EvolutionAPI/evolution-api#315]
O exato mesmo problema discutido na issue fechada #271 está acontecendo ainda comigo na versão 1.6.1 homologue, porém somente quando ativo o MongoDB.

E o pior é que agora mesmo deletando a instância e criando novamente o mesmo problema continua, criando instância básica ou com chatwoot ainda sim dá problema. Qualquer tentativa de começar a gerar qr codes acaba trazendo um log de warn de logout.

Cheguei a verificar as coleções no mongo e elas estão lá, aparentemente funcionando.

Não sei se é somente comigo, por isto estou criando a issue para saber de vocês.

**Comment by matiasduartee** [comment]
Testa a versão final v1.6.1, onde não tive mais esse problema, mais sim outros rsrsrs, como mencionado no issues #321, #320 e #319.

**Comment by stgcompany** [comment]
Vi aqui que na verdade o problema é com o nome das duas instâncias que eu estava testando, testei agora com uma instância com um nome diferente "abc" e ela não teve esses problemas.

Creio eu que tem algum tipo de "cache" que está armazenando dados sobre essas instâncias de quando eu usava antes de ativar o mongodb e trocar pra 1.6. a questão é que não sei onde está isso para eu fazer um "refresh".

Olhei a pasta `evolution/instances` e não tem nada lá, dei um fetchInstances e nada também, confirmando isto verificando a coleção "authentication" no mongodb.

Cheguei inclusive a apagar o diretório do evo e deletar a tarefa do pm2 e instalar de novo. Mas o interessante é que quando dei o npm run prod ele já iniciou detectando as duas instâncias que eu usava como "closed", o que é muito estranho já que eu havia deletado previamente.

Por enquanto estou na busca aqui para entender e resolver isso

PS.: Estou usando o pm2 e não docker.

**Comment by jaison-x** [comment]
> Vi aqui que na verdade o problema é com o nome das duas instâncias que eu estava testando, testei agora com uma instância com um nome diferente "abc" e ela não teve esses problemas.
> 
> Creio eu que tem algum tipo de "cache" que está armazenando dados sobre essas instâncias de quando eu usava antes de ativar o mongodb e trocar pra 1.6. a questão é que não sei onde está isso para eu fazer um "refresh".
> 
> Olhei a pasta `evolution/instances` e não tem nada lá, dei um fetchInstances e nada também, confirmando isto verificando a coleção "authentication" no mongodb.
> 
> Cheguei inclusive a apagar o diretório do evo e deletar a tarefa do pm2 e instalar de novo. Mas o interessante é que quando dei o npm run prod ele já iniciou detectando as duas instâncias que eu usava como "closed", o que é muito estranho já que eu havia deletado previamente.
> 
> E toda vez que eu dou um `pm2 restart Evo...` ele puxa de volta as duas instâncias como closed, sendo que eles hipoteticamente estavam removidas.
> 
> Por enquanto estou na busca aqui para entender e resolver isso.
> 
> PS.: Estou usando o pm2 e não docker.

Os dados de conexão das instâncias no mongo são salvas em um banco de dados separado. O nome do banco é evolution-instances. Dentro deste banco para cada instância existe uma colection. Estas instâncias devem estar ali. Exclua dali que deve resolver: 

![image](https://github.com/EvolutionAPI/evolution-api/assets/5599142/384b6397-2ef1-42f2-9566-f223bccedbe8)

**Comment by stgcompany** [comment]
Pelo que eu inspecionei no mongo eu não achei este banco.

<details>
<summary>mongo cli:</summary>

```bash
> show dbs
admin                   0.000GB
config                  0.000GB
evolution-whatsapp-api  0.000GB
local                   0.000GB
> use evolution-whatsapp-api
switched to db evolution-whatsapp-api
> show collections
authentication
chamaai
chats
chatwoot
contacts
messageUpdate
messages
proxy
rabbitmq
settings
sqs
typebot
webhook
websocket
```

</details>

**Comment by jaison-x** [comment]
Você está com o redis habilitado? Se tiver, ele tem prioridade com relação ao mongo. Recomendo desabilitar se for este o caso.

Se não estiver, como está definido o seu parâmetro no .env DATABASE: SAVE_DATA: INSTANCE?

![image](https://github.com/EvolutionAPI/evolution-api/assets/5599142/bfe1782e-f18d-45dc-943a-cf4cb225713b)

Se estiver false, os dados das instâncias estão sendo salvos em arquivo.

**Comment by stgcompany** [comment]
> Você está com o redis habilitado?

Desativei o redis e resolveu o problema! Não sabia que o redis armazenava as instâncias, achava que era apenas usado para mensagens. Muito obrigado pela ajuda amigo!
