### ISSUE TITLE
1.6.1 - Variáveis chatwoot 'qrcode' e 'auto_create' não funcionando corretamente

### ISSUE THREAD

**Issue by stgcompany** [EvolutionAPI/evolution-api#316]
Não sei se só é comigo, mas quando crio uma instância com `qrcode` e `auto_create` como false, ainda sim o evolution cria uma nova conversa com o gerador de qr iniciando a geração de qr code. O que no meu entendimento não deveria ocorrer, estou certo?

Enfim, caso não esteja ocorrendo com vocês só falar. Valeus.

**Comment by DavidsonGomes** [comment]
o auto_create tem apenas no set chatwoot e nao na criação, se precisa criar uma instancia sem ir imeadiatamente para o chatwoot, apenas não passar as informações do chatwoot no payload de criação da instancia.

POST > {{baseUrl}}/instance/create
{
    "instanceName": "{{instance}}",
    "token": "{{apikey}}",
    "qrcode": true
}

**Comment by stgcompany** [comment]
Ah ok entendi, mas em relação ao parâmetro qr_code, definindo como falso ele não deveria não iniciar a geração de qr codes automaticamente?

**Comment by DavidsonGomes** [comment]
Não inicia
