### ISSUE TITLE
[PT][BUG] Erro ao enviar mensagem do Chatwoot a grupos do WhatsApp

### ISSUE THREAD

**Issue by matiasduartee** [EvolutionAPI/evolution-api#319]
Foi detectado que ao tentar enviar mensagem pelo Chatwoot para um grupo do Whats além da mensagem não chegar no grupo isso causa um travamento na API, fazendo ela congelar e por alguns instantes. Meu ambiente é em Docker e nesse congelamento **não** é gerando um novo container e nem **logs** na API. 

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/61b85180-4d92-4d95-8d2a-969592db1ba4)

Neste momento o link de acesso a API fica em loading, assim como o manager fica também em processo de carregando. 

Comportamento do manager por exemplo:
![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/d85cf89a-bfcf-49c1-abd2-2624a691def3)

Junto com o nosso amigo Anderson Tomaz @tizum, que pode validar que esse problema também acontece com ele, estamos em ambiente separados e com as mesmas versão da Evolution 1.6.1 e Chatwoot 3.3.1.

#### Ambiente:
- **Servidor:** Ubuntu 20.04
- **Versão da API:** 1.6.1
- **Chatwoot:** 3.3.1

**Comment by DavidsonGomes** [comment]
Acontece que em grupos a depender da quantidade de membros, pode ser gerado um timeout, vou analisar com a Baileys qual a melhor maneira de tratar isso

**Comment by MarcioLacerda** [comment]
Não estou conseguindo enviar msg para grupos grandes pelo chatwoot e pelo que vi nos logs do chatwoot é timeout da api mesmo. Estou usando a img pra linux/arm64 e só configurei redis. Usar MongoDB pode resolver isso? Se sim, é possível migrar os dados?
Não precisam me pegar pela mão pra atravessar a rua, mas luz de o que pesquisar já ajuda bastante. Obrigado.
