### ISSUE TITLE
[PT][BUG] Sobre o Issues #292, formatação de texto com Typebot Evolution v1.6.1

### ISSUE THREAD

**Issue by matiasduartee** [EvolutionAPI/evolution-api#320]
@DavidsonGomes segundo nosso amigo Edison Martins do nosso grupo da Evolution, esse problema ainda está ocorrendo na v1.6.1 com Typebot.

**Comment by matiasduartee** [comment]
Formatações do WhatsApp passadas pelo Typebot funcionam corretamente pra quem quiser corrigir o problema momentaneamente.

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/62c41b77-42c9-4ffd-9ada-6254d3415597)

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/c0282a77-e557-4e7b-bc51-72cdd216f140)

**Comment by suissa** [comment]
eu fiz um PR disso na versão passada
