### ISSUE TITLE
[PT][BUG] - Typebot conectado mas fluxo não inicia

### ISSUE THREAD

**Issue by wolfffelipe** [EvolutionAPI/evolution-api#321]
#### Descrição:
Provavelmente não é um bug por eu ver que da maioria funciona. Conectei minha instância da Evolution API ao Typebot (que está funcionando conforme teste interno no servidor e publicado).

Porém, mesmo o Typebot habilitado, ao enviar mensagem no whatsapp, o fluxo não se inicia.

#### Ambiente:
- **Servidor:** Ubuntu 20.04
- **Versão da API:** 0.4.11
- **Versão do Typebot:** 2.17.0

#### Evidências:

Typebot | Link e nome
![image](https://github.com/EvolutionAPI/evolution-api/assets/6557712/c80fd9d0-bd30-41af-87b7-c38d436e7e95)

---

Typebot | Fluxo funcionando e publicado:
![image](https://github.com/EvolutionAPI/evolution-api/assets/6557712/fe02a4f6-a37e-4733-8b36-229000664d23)

---

Evolution API | Configuração do Typebot
![image](https://github.com/EvolutionAPI/evolution-api/assets/6557712/06f42988-d1f1-420e-9ec0-2835d6fd3569)

---

Whatsapp | Teste
![image](https://github.com/EvolutionAPI/evolution-api/assets/6557712/c858ce73-a3a8-4bad-a299-e084e864397b)

---

Evolution API | Versão
![image](https://github.com/EvolutionAPI/evolution-api/assets/6557712/75369729-2c11-411a-8d9f-b041300a2467)

---

Typebot | Versão
![image](https://github.com/EvolutionAPI/evolution-api/assets/6557712/6f776074-e794-4261-be84-aac3546f6a28)

---

Eu sou novo nessas integrações e talvez eu esteja fazendo algo de errado. Mas fiz tudo seguindo tutoriais no Youtube. Funcionou tudo, só faltou isso rs. 

Única coisa que alterei depois de toda configuração foi adicionar a linha NEXT_AUTH para o nó environment do typebot-viewer (como vi em um vídeo), pois estava dando erro 500, e realmente funcionou..

**Comment by matiasduartee** [comment]
@wolfffelipe você não está fazendo nada de errado, de fato é algo na v1.6.1, pois o mesmo ocorre aqui no meu ambiente de testes. 

Tudo configurado perfeitamente e o fluxo não é iniciado. 

![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/7ada0e17-42d4-4e8f-af6b-baf33ca937c3)

- environment:
       - SERVER_TYPE=http
       - SERVER_PORT=8080
       - TYPEBOT_KEEP_OPEN=true
       - TYPEBOT_API_VERSION=latest

**Comment by matiasduartee** [comment]
@wolfffelipe fazendo uns testes aqui, consegui fazer o fluxo funcionar, porem e algo bem louco. 

O fluxo de teste estava assim:
![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/f630607a-632c-45a7-8c1d-641ee656a7f6)

Com essa condição no inicio, o que fiz foi eliminar essa condição e testei, funcionou corretamente, veja:
![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/d41bcba1-d90b-4135-b652-70b6b65d6c8e)
![image](https://github.com/EvolutionAPI/evolution-api/assets/81826268/87a0f10c-4875-4645-afe1-1ec428284203)

Ao final eu voltei a condição para o inicio de fluxo da forma que estava antes, e continuou funcionando.

**Comment by 7sxnc** [comment]
E como posso voltar a versão pra outra que está funcionando?

**Comment by val-leite** [comment]
![er0](https://github.com/EvolutionAPI/evolution-api/assets/142282814/77af30a6-a78d-48e3-ad7c-de9ef2a3b765)

Todas as configurações estão correta, estava utilizando normalmente, agora está apresentando esse erro:

![er1](https://github.com/EvolutionAPI/evolution-api/assets/142282814/73b95157-9b93-4728-8cad-b1c7a27a7398)

Achei que fosse algo referente a atualização, atualizei o Chatwoot vs.3.3.1, o Typebot para vs.2.20.0 e a API está na sua vs.1.6.0.

Está acontecendo com mais alguém. Preciso de ajuda!

**Comment by wolfffelipe** [comment]
> E como posso voltar a versão pra outra que está funcionando?

Tenho esta dúvida também, não sei como alterar a versão

**Comment by wolfffelipe** [comment]
> @wolfffelipe fazendo uns testes aqui, consegui fazer o fluxo funcionar, porem e algo bem louco.
> 
> O fluxo de teste estava assim: ![image](https://private-user-images.githubusercontent.com/81826268/292683741-f630607a-632c-45a7-8c1d-641ee656a7f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MTA4ODIsIm5iZiI6MTcwMzYxMDU4MiwicGF0aCI6Ii84MTgyNjI2OC8yOTI2ODM3NDEtZjYzMDYwN2EtNjMyYy00NWE3LThjMWQtNjQxZWU2NTZhN2Y2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE3MDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMzA4YmNhZDU0NmVlMWM4OWFhMzA0ODQxYzljYzk4OGU3YmRmNDE3OGZmMjY3YWU3ZWQyZDdiOWMwZTQ0NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bq0F7uOyFvok8yD2CjA6r0PMzt4kBGwJHqNvaheOxf4)
> 
> Com essa condição no inicio, o que fiz foi eliminar essa condição e testei, funcionou corretamente, veja: ![image](https://private-user-images.githubusercontent.com/81826268/292683766-d41bcba1-d90b-4135-b652-70b6b65d6c8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MTA4ODIsIm5iZiI6MTcwMzYxMDU4MiwicGF0aCI6Ii84MTgyNjI2OC8yOTI2ODM3NjYtZDQxYmNiYTEtZDkwYi00MTM1LWI2NTItNzBiNmI2NWQ2YzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE3MDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NzI0YjM2YjViYTYyMWJmOThlNDVkMWI1OWJkMTMwZmFmNmVhZjNmYTAxNjBiNTIyNDk5OTE1ZDk2MWQ2MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tuwYGwv6f2gzLTEx7gYdIN959qYk_KFTdWPpnIdG9Pc) ![image](https://private-user-images.githubusercontent.com/81826268/292683790-87a0f10c-4875-4645-afe1-1ec428284203.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MTA4ODIsIm5iZiI6MTcwMzYxMDU4MiwicGF0aCI6Ii84MTgyNjI2OC8yOTI2ODM3OTAtODdhMGYxMGMtNDg3NS00NjQ1LWFmZTEtMWVjNDI4Mjg0MjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE3MDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YWUwMzFjYjVjNjU1ODg4M2ZjMzkyZGQ1YmI0NGYzNTEwMWU3ZWU0MDE2ZGNhZjc0Mjc3M2FkMGRjN2RmNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z2OQPHg4w0j4bChBXH_nOlaLW4iqZGizGsgDWBpWuyk)
> 
> Ao final eu voltei a condição para o inicio de fluxo da forma que estava antes, e continuou funcionando.

Tentei! Mas não foi rs Exclui o fluxo, recriei, recriei o typebot, testei fluxos prontos e nada. Vou acabar pagando uma consultoria para resolver rs

**Comment by suissa** [comment]
> > @wolfffelipe fazendo uns testes aqui, consegui fazer o fluxo funcionar, porem e algo bem louco.
> > O fluxo de teste estava assim: ![image](https://private-user-images.githubusercontent.com/81826268/292683741-f630607a-632c-45a7-8c1d-641ee656a7f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MTA4ODIsIm5iZiI6MTcwMzYxMDU4MiwicGF0aCI6Ii84MTgyNjI2OC8yOTI2ODM3NDEtZjYzMDYwN2EtNjMyYy00NWE3LThjMWQtNjQxZWU2NTZhN2Y2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE3MDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMzA4YmNhZDU0NmVlMWM4OWFhMzA0ODQxYzljYzk4OGU3YmRmNDE3OGZmMjY3YWU3ZWQyZDdiOWMwZTQ0NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bq0F7uOyFvok8yD2CjA6r0PMzt4kBGwJHqNvaheOxf4)
> > Com essa condição no inicio, o que fiz foi eliminar essa condição e testei, funcionou corretamente, veja: ![image](https://private-user-images.githubusercontent.com/81826268/292683766-d41bcba1-d90b-4135-b652-70b6b65d6c8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MTA4ODIsIm5iZiI6MTcwMzYxMDU4MiwicGF0aCI6Ii84MTgyNjI2OC8yOTI2ODM3NjYtZDQxYmNiYTEtZDkwYi00MTM1LWI2NTItNzBiNmI2NWQ2YzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE3MDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NzI0YjM2YjViYTYyMWJmOThlNDVkMWI1OWJkMTMwZmFmNmVhZjNmYTAxNjBiNTIyNDk5OTE1ZDk2MWQ2MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tuwYGwv6f2gzLTEx7gYdIN959qYk_KFTdWPpnIdG9Pc) ![image](https://private-user-images.githubusercontent.com/81826268/292683790-87a0f10c-4875-4645-afe1-1ec428284203.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MTA4ODIsIm5iZiI6MTcwMzYxMDU4MiwicGF0aCI6Ii84MTgyNjI2OC8yOTI2ODM3OTAtODdhMGYxMGMtNDg3NS00NjQ1LWFmZTEtMWVjNDI4Mjg0MjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE3MDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YWUwMzFjYjVjNjU1ODg4M2ZjMzkyZGQ1YmI0NGYzNTEwMWU3ZWU0MDE2ZGNhZjc0Mjc3M2FkMGRjN2RmNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z2OQPHg4w0j4bChBXH_nOlaLW4iqZGizGsgDWBpWuyk)
> > Ao final eu voltei a condição para o inicio de fluxo da forma que estava antes, e continuou funcionando.
> 
> [matiasduartee](https://github.com/matiasduartee) Tentei! Mas não foi rs Exclui o fluxo, recriei, recriei o typebot, testei fluxos prontos e nada. Vou acabar pagando uma consultoria para resolver rs

Eu já tive esse problema se vc ver nos logs deve estar dando erro 400 pq nao envia os startParams, pelo menos aqui foi isso. Fiquei até de corrigir mas ainda não fiz porque estou criando um sisteminha que usa a Evolution mas quando chegar no Typebot terei que implementar algo.

**Comment by Mapulango1969** [comment]
Boa Noite Galera, estou com o mesmo problema. Cara ja tentei de tudo so falta ir  fazer reza braba, troque fluxo, baixei fluxo, criei fluxo e nada acontece, Alguem conseguiu uma solução. PELO AMOR DE DEUS?

**Comment by 7sxnc** [comment]
> Boa Noite Galera, estou com o mesmo problema. Cara ja tentei de tudo so falta ir fazer reza braba, troque fluxo, baixei fluxo, criei fluxo e nada acontece, Alguem conseguiu uma solução. PELO AMOR DE DEUS?

Só conectando nativamente o Typebot no WhatsApp API, o único problema da Evolution é a questão do WhatsApp, de resto está funcionando corretamente.

**Comment by wolfffelipe** [comment]
Fala, pessoal! Consegui fazer funcionar!!!!! Agora sinceramente não sei exatamente o que foi que fez funcionar mas eu suspeito que tenha sido apenas o item 1 abaixo... vamos lá:

1. Eu estava utilizando SMTP do gmail, alterei para meu e-mail de domínio próprio hospedado pela hostgator. Então coloquei os dados de smtp da hostgator e tal.

2. Fiz a instalação pelo novo instalador da Orion junto a este vídeo que segue abaixo que o Willian, criador da Orion, faz o passo a passo das instalações. O vídeo é grande, mas pode fazer a instalação inicial e depois ir pulando para os tópicos que vocês quiserem, como por exemplo só a Evolution API e o Typebot.
https://www.youtube.com/watch?v=_-Lk68w5lU4&t=231s

Espero que isso ajude vocês também. Qualquer coisa deem o feedback se funcionou. Tmj!

@Mapulango1969 @7sxnc @suissa

**Comment by S1LV4** [comment]
Estou com o mesmo problema, @wolfffelipe utilizo o mesmo smtp da hostgator, porem o erro de não iniciar quando mando mensagem no WhatsApp.

**Comment by ildo19** [comment]
eu to com mesmo problema,  alguem sabe como voltar versão anterior?

**Comment by S1LV4** [comment]
Alguém conseguiu resolver?

**Comment by in5-alassis** [comment]
Meu caso tá estranho, quando um número de WhatsApp chama o bot pela primeira vez, o bot responde, aí depois não mais. 
Alguém sabe dizer o que pode ser ?

**Comment by pbrumoliver** [comment]
Meu typebot estava funcionando normalmente, faz uns 2 dias que parou, mesma questão acima quando um número de WhatsApp chama o bot pela primeira vez, o bot responde, aí depois não mais. Lembrando que criei um fluxo com ia, alguem sabe me dizer oq pode ser?
