### ISSUE TITLE
[PT][BUG] ERRO AO CONECTAR INSTÂNCIA TYPEBOT

### ISSUE THREAD

**Issue by val-leite** [EvolutionAPI/evolution-api#323]
### Título: ERRO AO CONECTAR INSTÂNCIA TYPEBOT

![er0](https://github.com/EvolutionAPI/evolution-api/assets/142282814/bb8bc41c-5da0-4780-b70a-35c11a78a08e)
Todas a configurações estão corretas. Eu estava usando normalmente.

esse é o erro: 
![er1](https://github.com/EvolutionAPI/evolution-api/assets/142282814/44422608-1618-4a9f-87ed-885e00e1a731)

#### Ambiente:
- **Servidor:** [ex: Ubuntu 22.04]
- **Versão da API:** [ex: 1.6.0]

Me ajudem!

**Comment by DavidsonGomes** [comment]
Utilize o manager novo na rota /manager da api e utilize a versão 1.6.1
