### ISSUE TITLE
[PT][BUG] Erro ao atualizar da versão 1.6.0 para 1.6.1

### ISSUE THREAD

**Issue by adrianofreires** [EvolutionAPI/evolution-api#325]
#### Descrição:
Estou usando um servidor Debian 12 e a instalação é feita pelo Dcoker Swarm. A instalação da Evolution API 1.6.0 aconteceu sem problemas. Mas quando tento atualizar, o container não roda. Ao invés disso apresenta esse erro no log:

[Evolution API]  v1.6.1  1   -  Tue Dec 26 2023 13:52:20     INFO   [WA MODULE]  [string]  Module - ON 
node:internal/fs/utils:352
    throw err;
    ^
Error: ENOENT: no such file or directory, open
    at Object.openSync (node:fs:601:3)
    at readFileSync (node:fs:469:35)
    at get https [as https] (/evolution/dist/src/utils/server-up.js:50:41)
    at bootstrap (/evolution/dist/src/main.js:124:40)
    at Object.<anonymous> (/evolution/dist/src/main.js:134:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {

  errno: -2,
  syscall: 'open',
  code: 'ENOENT'
}
Node.js v20.7.0

#### Passos para Reproduzir:
1. Liste os passos necessários para reproduzir o problema.
2. Tente ser o mais específico possível.
3. Se o problema ocorrer em um cenário específico, descreva-o aqui.

#### Comportamento Esperado:
Descreva o que você esperava que acontecesse quando seguisse os passos acima.

#### Comportamento Atual:
Explique o que realmente acontece quando você segue os passos acima.

#### Capturas de Tela/Vídeos:
Se possível, adicione capturas de tela ou vídeos que ilustrem o problema. Isso pode ser extremamente útil para entender o problema.

#### Ambiente:
- **Servidor:** Hetzner Debian 12
- **Versão da API:** 1.6.1
- **Outras Especificações de Hardware/Software:** Portainer 2.19.4

<img width="1100" alt="Captura de Tela 2023-12-23 às 13 08 20" src="https://github.com/EvolutionAPI/evolution-api/assets/38692077/f49c0ddb-583c-4cb7-9059-2062bfd66ee7">
<img width="1096" alt="Captura de Tela 2023-12-23 às 13 09 01" src="https://github.com/EvolutionAPI/evolution-api/assets/38692077/e2d754bc-979c-488c-a32f-ca68f2b7d971">

`version: "3.8"

x-variables:
  &variables
    SUBDOMAIN: evo # This will be the subdomain in which the application will run
    DOMAIN: prodigito.dev
    # Server configs
    SERVER_TYPE: "https"
    SERVER_URL: https://evo.prodigito.dev
    CONFIG_SESSION_PHONE_CLIENT: "Chat Prodigito"
    # ApiKey Config for authentication High Encryption AES 256 from https://acte.ltd/utils/randomkeygen
    AUTHENTICATION_TYPE: apikey
    AUTHENTICATION_API_KEY: apagado
    # Database 
    #DATABASE_ENABLED: "true" 
    #DATABASE_CONNECTION_URI: mongodb://prodigito_db_mongo_docker_swarm:JiTdTy5f6zJzPvSU46579wF@49.12.229.96:27017/?authSource=admin&readPreference=primary&ssl=false&directConnection=true
    #DATABASE_CONNECTION_DB_PREFIX_NAME: evdocker
    # RabbitMQ configs
    RABBITMQ_ENABLED: "true"
    RABBITMQ_URI: amqp://apagado:apagado@rabbitmq:5672/evolution
    # Typebot
    TYPEBOT_API_VERSION: "latest" # old | latest
    TYPEBOT_KEEP_OPEN: "false"

services:
  evolution_api:
    image: atendai/evolution-api:latest
    command: ["node", "./dist/src/main.js"]
    environment:
      <<: *variables
    volumes:
      - evolution_api_instances:/evolution/instances
      - evolution_api_store:/evolution/store
    ports:
    - 8080:8080
    networks:
      # Define a nossa rede padrão do swarm
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          #- node.role == manager
          - "node.hostname==worker-chat"
      resources:
        limits:
          # Define a quantidade de CPU para o Evolution para evitar travamento do Host
          cpus: "1"
          # Define a quantidade de RAM para o Evolution para evitar travamento do Host
          memory: 1024M
      labels:
        # Traefik labels for reverse proxy
        traefik.enable: "true"
        traefik.http.routers.evolution_api.rule: "Host(`evo.prodigito.dev`)"
        traefik.http.routers.evolution_api.entrypoints: "websecure"
        traefik.http.routers.evolution_api.tls.certresolver: "letsencryptresolver" # Some users uses https as a router name
        traefik.http.routers.evolution_api.priority: 1 # prioridade máxima para essa rota (padrão)
        traefik.http.routers.evolution_api.service: "evolution_api"
        traefik.http.services.evolution_api.loadbalancer.server.port: 8080
        traefik.http.services.evolution_api.loadbalancer.passHostHeader: "true"

volumes: 
  evolution_api_instances:
    external: true
    name: evolution_api_instances
  evolution_api_store:
    external: true 
    name: evolution_api_store

networks:
  network_public:
    name: network_public
    external: true`

**Comment by palmeirarocha** [comment]
Como corrigiu?

**Comment by LenoSeibert** [comment]
Tive o mesmo problema. No meu caso uso Docker swarm. O traefik passa a conexão até o serviço com http em vez de https.
Resolvi mudando a variável: SERVER_TYPE: "https" para SERVER_TYPE: "http".

**Comment by elinardo10** [comment]
Cara valeu. Tava com esse mesmo erro. aí mudar para http normal resolveu. [Instalação nova do evolutio v2]

**Comment by AndersonSilvaCavalcante** [comment]
Valeu de mais, passei o dia todo aqui brigando com o ECS, Terraform e etc.  e nada resolvia. Mas o manager continua sem abrir, mas tá rodando rs
