### ISSUE TITLE
Usando Cluster ou Worker na API 1.6.1

### ISSUE THREAD

**Issue by VonJdamian** [EvolutionAPI/evolution-api#327]
Tenho tentado adicionar Worker no código, mas sempre recebo erro no log "Instância do RedisCache destruída".

E quando tento iniciar o PM2 com cluster, ocorre um erro "O script/usr/bin/bash teve muitas reinicializações instáveis ​​(16). Parado. "Erro""

Se eu tentar adicionar o cluster a partir do código, ele funcionará bem, mas há problemas ao tentar instanciar uma sessão do WhatsApp.

Alguém conseguiu usar Cluster ou Worker?

**Comment by DavidsonGomes** [comment]
Redis esta sendo descontinuado
