### ISSUE TITLE
Bloquear o recebimento/envio de áudio, assim como "rejeitar chamadas", na configurações da API

### ISSUE THREAD

**Issue by luiztonucci** [EvolutionAPI/evolution-api#328]
#### Descrição Detalhada:
Inserir a opção de bloquear o recebimento/envio de áudio em mensagens enviadas por parte do cliente. Existe atualmente o bloqueio para não receber ligações na configuração do API, seria a mesma ideia.

#### Racional:
Útil para uso em cenários onde a empresa precisa registrar suas conversas com clientes apenas com texto, usando como prevenção contra possíveis acusações, onde o áudio pode ser questionado se esse é referente aquela conversa ou não. (Questões de LGPD)

#### Exemplos de Uso:
Cenários de uso: Escritórios em geral (advocacia, contabilidade, financeiras, consultórios, etc. ).
Eu trabalho como TI em escritório de contabilidade e tivemos uma situação complicada com um cliente no qual precisamos provar a ele através de conversas, e devido ter áudio no meio da conversa, fomos questionados se era verídico. Infelizmente não pudemos provar referente ao áudio.

#### Possíveis Implementações:
Não consigo ajudar nesse sentido.

#### Impacto no Projeto:
Acredito não ser um impacto, é apenas uma configuração adicional, podendo ser ativado o áudio ou não, ficando a critério de cada empresa.

#### Notas Adicionais:
![image](https://github.com/EvolutionAPI/evolution-api/assets/82972632/34f0414a-3e7c-44de-b307-99d1602c69c3)

**Comment by gabrielpastori1** [comment]
Nesse caso eu acho que seria melhor você usar o webhook junto com n8n (ou similar) para quando receber o áudio ele enviar uma mensagem falando que esse tipo de mensagem não é aceita, ou usar alguma API para transcrever o áudio e enviar a transcrição como uma resposta para o áudio, assim você mantem uma transcrição na conversa e continua podendo usar áudios

**Comment by DavidsonGomes** [comment]
Concordo com a abordagem do gabriel, use o webhook para identificar o tipo de mensagem e responder com oq precisar!
