### ISSUE TITLE
[PT][BUG] FLUXO REINICIANDO SOZINHO NO TYPEBOT

### ISSUE THREAD

**Issue by williamzzz1** [EvolutionAPI/evolution-api#330]
#### Descrição:
Quando o fluxo deveria finalizar, mudar o status para "closed" depois de alguns minutos ele volta a interagir sozinho sem nenhuma interação...

#### Passos para Reproduzir:
Uso Chatwoot 3.3.1 + Typebot 2.20.0 + Evo v1.6.1
Quando estou em conversa com typebot e ele transfere para o chatwoot ou então finaliza com um post mudando o status, depois de alguns minutos o typebot reinicia o fluxo sozinho, sem fazer nenhuma interação...

#### Comportamento Esperado:
O robo deveria pausar, e só retornar quando passasse o periodo estipulado no Manager ou então após uma nova interação...
![image](https://github.com/EvolutionAPI/evolution-api/assets/52936830/8b53169d-dd27-4a64-b3a8-ca7e0eaef100)

Nesse caso abaixo, ele foi transferido para o Chatwoot, e deveria pausar o fluxo. Mas depois de alguns minutos ele reiniciou sozinho.
![image](https://github.com/EvolutionAPI/evolution-api/assets/52936830/db06cbcb-2d67-43cf-b58a-87941e6d6220)

Nesse caso, ele deveria ter finalizado o fluxo através de um POST que tem atualizando o status para "closed", porém depois de alguns minutos ele novamente reiniciou o fluxo sem ter tido nenhuma interação...
![image](https://github.com/EvolutionAPI/evolution-api/assets/52936830/f80cf533-dfb2-46e6-b2c5-0cb9350f5dc7)

#### Ambiente:
- **Servidor:** [Ubuntu 20.04]
- **Versão da API:** [1.6.1]
- **Outras Especificações de Hardware/Software:**

**Comment by DavidsonGomes** [comment]
A variavel no env TYPEBOT_KEEP_OPEN esta como true?

**Comment by williamzzz1** [comment]
> A variavel no env TYPEBOT_KEEP_OPEN esta como true?

Não configurei essa variável no ENV, retornei para V1.5.4 e está funcionando normal...

**Comment by DavidsonGomes** [comment]
O problema é esse, deve configurar o env corretamente, da uma olhada no dev-env e configure o seu
