### ISSUE TITLE
[EN][BUG] `always_online: false` not working 

### ISSUE THREAD

**Issue by stgcompany** [EvolutionAPI/evolution-api#333]
#### Description:
Even with `always_online: false` I've received a lot of complaints from friends and family saying that my number is always online on Whatsapp.

#### Steps to Reproduce:
1. Create or set an instance with `always_online: false`;
2. Ask for other people check your status during the day.

#### Expected Behavior:
The status shouldn't be online following the proper settings.

#### Environment:
- **Server:** Ubuntu 20.04
- **API Version:** 1.6.1
- **Other Hardware/Software Specifications:** Running on PM2

#### Submitting Logs:
There are no logs for this.

**Comment by DavidsonGomes** [comment]
issue already created previously #324

**Comment by diluh** [comment]
https://github.com/WhiskeySockets/Baileys/issues/431#issuecomment-1758057135

@DavidsonGomes  👆 Será que essa opção não poderia corrigir esse problema na Evolution?

**Comment by phtisp** [comment]
Por favor, classifique esta conversa, https://apiv2.xphsolution.com.br/survey/responses/33c9618b-0255-4b10-a16d-52ec6897ad03
