### ISSUE TITLE
[PT][FEAT] Função Wait do Typebot não pausa fluxo

### ISSUE THREAD

**Issue by agencia904** [EvolutionAPI/evolution-api#335]
#### Descrição Detalhada:
Hoje a função WAIT funciona apenas para o primeiro Bubble do Grupo e não dentro do fluxo normal. Além disto, é apenas um delay onde aparece o "digitando...". O ideal seria um WAIT que pausasse o fluxo enquanto estivesse esperando até a próxima ação ou próximo Bubble.

#### Racional:
O meu cenário de melhoria é quando utilizada IA para interpretação de respostas (sem utilização de menu numeral), se um usuário insere duas mensagens na sequência (comportamento humano), a lógica do Typebot vai imediatamente até o próximo INPUT e o WAIT seria o motor ideal para barrar até que o próximo INPUT seja requistado.

#### Exemplos de Uso:
Sistema: Para começarmos digite seu nome
Usuário: Olá, tudo bem?
Usuário: Meu nome é Felipe.

No caso acima o INPUT coletado do nome seria "Olá, tudo bem?"
E o segundo INPUT seria imediatamente acionado com a resposta "Meu nome é Felipe."

Se pelo menos conseguíssemos utilizar o WAIT para interpretar o que o usuário está enviando no primeiro, poderíamos tratar de forma bem mais humanizada este atendimento.

#### Possíveis Implementações:
Nós desenvolvemos um "workaround" enviando uma solicitação para o n8n, armazenando em BD o horário da primeira mensagem e comparando a segunda e depois restartando o typebot. Mas acaba sendo muita gambiarra e exigindo muito do sistema.

#### Impacto no Projeto:
Para quem quer realmente usar IA em seus projetos, eu acho uma ÓTIMA melhoria que humaniza ainda mais o atendimento via WhatsApp + Bot + IA.

#### Notas Adicionais:
Se os desenvolvedores tiverem outras dicas para conseguirmos trazer uma solução robusta e o que eu puder contribuir pro projeto, fico a disposição.

**Comment by suissa** [comment]
Ótima feature, já necessária há tempos.

**Comment by agencia904** [comment]
@DavidsonGomes dá uma mão pra gente nessa Feat 🙏
