### ISSUE TITLE
[PT][FEAT] Listar todos os contatos de uma conexão

### ISSUE THREAD

**Issue by suissa** [EvolutionAPI/evolution-api#337]
#### Descrição Detalhada:
Desejo pegar todos os contatos de um conexão conectada

#### Racional:
Será bem útil ter esse tipo de informação para nutrir as tabelas de contatos dos sistemas que usam a Evolution

#### Exemplos de Uso:
Iniciar uma conexão e mostrar todos os contatos dessa conexão

#### Impacto no Projeto:
Acho que essa funcionalidade não teria um impacto tão grande no código mas teria muito para o uso da Evolution

#### Notas Adicionais:
O Whaticket tem essa funcionalidade

**Comment by w3nder** [comment]
Você pode buscar os conatos da instância conectada utilizando o recurso: `{{baseUrl}}/chat/findContacts/{{instance}}`

**Comment by DavidsonGomes** [comment]
Ja existe essa função como citado acima

**Comment by WalterGit** [comment]
Existe algum limite de requisiçoes? pois, estou fazendo alguns testes e vem a listagem completa de usuarios, com algumas requisiçoes feitas os contatos não vem mais, ai preciso encerrar a estancia e voltar a conectar.

**Comment by wellingtongmota** [comment]
@suissa tive esse problema, no meu caso utilizo Docker, e setei a variável de ambiente DATABASE_SAVE_DATA_CONTACTS: "true", reestartei o Container, e criei uma nova instância.
