### ISSUE TITLE
[PT][BUG] Erro no sendText DDD 81 formatação do número

### ISSUE THREAD

**Issue by willph** [EvolutionAPI/evolution-api#339]
#### Descrição:
Bug no sendText ao tentar enviar mensagem cujo o DDD seja 81 e coloque o numero apenas com o DDD + Número com o 9 digito.

Exemplo 81999998888

#### Passos para Reproduzir:
1. Abra postman, Insomnia ou o de sua preferencia
2. Usar o endpoint **senText** `{{baseUrl}}/message/sendText/{{instance}}`
3. No body na variavel **number** inserir um numero de DDD 81 `"number": "{{remoteJid}}",`
4. Exemplo de numero testado 81999998888

#### Comportamento Esperado:
O comportamento esperado era o envio da mensagem passado pelo filtro existente no codigo e formatando o numero no padrão 
correto para funcionamento da função **sendText**

#### Comportamento Atual:
Ao inserir seguindo o padrão mencionado ele retorna erro de envio e apresenta o numero da seguinte forma +81999998888@s.whatsapp.........

#### Capturas de Tela/Vídeos:
![bug-evolution-sendText](https://github.com/EvolutionAPI/evolution-api/assets/17226802/3f0c969e-4938-4b00-bea0-c371d38a40d0)

#### Ambiente:
- **Servidor:**  Ubuntu 20.04
- **Versão da API:** 1.6.1
- **Outras Especificações de Hardware/Software:** 6 vCPU Cores 16 GB RAM

**Comment by DavidsonGomes** [comment]
Esta errado o formato do numero, faltou colocar o 55 no inicio, o codigo do Brasil

**Comment by willph** [comment]
> Esta errado o formato do numero, faltou colocar o 55 no inicio, o codigo do Brasil

fiz teste com outro DDDs e vai tranquilo. passando no "number": "31999998888". exemplo

**Comment by willph** [comment]
Irei fazer mais teste.

Como sou esquecido, num tinha um filtro que fazia a verificação?

**Comment by willph** [comment]
Eu registrei a issue porque fiz os testes em uma automação no N8N e por incrível que pareça a mensagem vai normalmente 

As fotos abaixo são dos teste que fiz

![image](https://github.com/EvolutionAPI/evolution-api/assets/17226802/b38ab647-7c94-4072-9dc8-4dc40c58d62b)

![image](https://github.com/EvolutionAPI/evolution-api/assets/17226802/c00b5c26-e0b5-45b8-ac23-719a6df4e608)
