### ISSUE TITLE
[PT][BUG] Mensagens estão saindo com Assinatura do admin do Chatwoot

### ISSUE THREAD

**Issue by tiagocordeiro** [EvolutionAPI/evolution-api#340]
#### Descrição:
Depois que atualizei o Evolution para a nova versão 1.6.1 todas as mensagens estão saindo como se fosse o ADMIN da conta enviando e não o atendente. Acho que tem haver com aquele token do usuário. Mas antes não era assim. 

Outro problema que vi agora tentando desativar a assinatura na mensagem enviada, no manager está dando erro quando tento salvar com essa opção de assinatura desativada, ou qualquer mudança que eu faça, não salva.

#### Passos para Reproduzir:
Enviando ou respondendo uma mensagem via chatwoot, as mensagens vão com a assinatura do admin e não do atendente.

Quando enviado via WhatsApp, a mensagem é duplicada, sendo que a segunda mensagem vai com a assinatura do ADMIN e não do atendente.

Se tentar alterar as opções no manager, retorna um erro:
```
{ "status": 400, "error": "Bad Request", "response": { "message": [ [ "account_id is not of a type(s) string" ] ] } }
```

#### Comportamento Esperado:
As mensagens via ChatWoot deveriam ser assinadas pelo atendente e não pelo usuário admin do Chatwoot

nas mensagens enviadas via WhatsApp (celular) não deveria duplicar a mensagem, deveria ser apenas uma, com a assinatura do atendente e não do Admin.

#### Comportamento Atual:
Quando o atendente do chatwoot envia ou responde uma mensagem via chatwoot, as mensagens vão com a assinatura do admin e não do atendente.

Quando enviado via WhatsApp, a mensagem é duplicada, sendo que a segunda mensagem vai com a assinatura do ADMIN e não do atendente.

#### Capturas de Tela/Vídeos:
![Captura de Tela 2024-01-03 às 10 23 50](https://github.com/EvolutionAPI/evolution-api/assets/6535995/4dc817be-fcca-4f04-a0bd-6da6622341ae)
![Captura de Tela 2024-01-03 às 10 45 01](https://github.com/EvolutionAPI/evolution-api/assets/6535995/b1bb97c5-869f-4535-b170-b6d5052a4804)
![Captura de Tela 2024-01-03 às 10 55 13](https://github.com/EvolutionAPI/evolution-api/assets/6535995/1ae774fd-95ea-4982-819c-89a560f10377)
![Captura de Tela 2024-01-03 às 10 07 33](https://github.com/EvolutionAPI/evolution-api/assets/6535995/2d31aa08-4bc6-4dd6-8a0c-a513279d821f)
![Captura de Tela 2024-01-03 às 10 07 05](https://github.com/EvolutionAPI/evolution-api/assets/6535995/2e3e3ed8-b33b-4952-bfd3-beb0626e0079)
![Captura de Tela 2024-01-03 às 10 01 41](https://github.com/EvolutionAPI/evolution-api/assets/6535995/c3506ac5-1159-4a5c-997f-59a39d332434)

#### Ambiente:
- **Servidor:** Debian 12
- **Versão da API:** 1.6.1
- **Outras Especificações de Hardware/Software:** 2 GB Memory / 1 Intel vCPU / 50 GB Disk 

#### Envio de Logs:
Se precisar de logs, posso enviar de modo privado

#### Notas Adicionais:
Fazendo mais alguns testes, reparei que esses comportamentos das mensagens assinadas pelo ADMIN e duplicadas quando enviadas via WhatsApp, só aconteceu no chatwoot v3.4

Na versão 3.3.1 quando enviado via chatwoot a assinatura continua errada, como se fosse o admin. Mas enviando via whatsapp, não duplica nem assina a mensagem.

**Comment by AnxHall** [comment]
RESOLVIDO PARCIAL
Vai em :
/seudiretorio/src/env.yml

acha essa linha ( usa o f3 pra achar pó)

#####
TYPEBOT:
API_VERSION: 'old' # old | latest
#####

!!!!! alterar para" latest" !!!!!

####
TYPEBOT:
API_VERSION: 'latest' # old | latest
####
 
 Depois e só atualizar usando:
 
 pm2 status 
 <(pega o numero da sua id)>
 
 pm2 restart <idaqui> --update-env
<(exemplo pm2 restart 0 --update-env)>

EvolutionAPI 1.6.1
