### ISSUE TITLE
[PT][FEAT] Gerenciamento de Tags / Etiquetas

### ISSUE THREAD

**Issue by MarksEliel** [EvolutionAPI/evolution-api#341]
#### Descrição Detalhada:
Seria muito importante ter na API endpoints para gerenciar etiquetas nas conversas/contatos.

#### Racional:
Hoje através do whatsapp business (mobile) conseguimos criar etiquetas e definir cores para elas, seria interessante algum endpoint para listar as etiquetas criadas (disponível no WhatsApp Web), com a opção de webhook para identificar mudanças nas etiquetas juntamente com exclusão e adição de novas.

**Comment by MarksEliel** [comment]
Na Baileys tem o os eventos de Label:
https://whiskeysockets.github.io/Baileys/index.html#md:handling-events

'labels.association': LabelAssociation
'labels.edit': Label

**Comment by judsonjuniorr** [comment]
@DavidsonGomes esta issue pode ser fechada, foi realizada nas seguintes PR:

https://github.com/EvolutionAPI/evolution-api/pull/409
https://github.com/EvolutionAPI/evolution-api/pull/411

Ainda existem melhorias que podem ser realizadas mas dependem de mudanças no código da baileys
