### ISSUE TITLE
[PT][BUG] Solicitação de Correção: Integração inesperada de mensagens de e-mail no WhatsApp através da Evolution API no Chatwoot

### ISSUE THREAD

**Issue by MolinoDigital** [EvolutionAPI/evolution-api#344]
Olá equipe de desenvolvimento da Evolution API,

Espero que esta mensagem os encontre bem. Recentemente, tenho utilizado a integração da Evolution API em conjunto com o Chatwoot para gerenciar mensagens de e-mail e WhatsApp. Percebi um comportamento inesperado que gostaria de abordar e corrigir.

Problema:
Quando configuramos um canal de e-mail no Chatwoot e enviamos um e-mail para um contato que também possui um número de telefone celular registrado no Chatwoot, a mensagem é enviada automaticamente para o WhatsApp através da Evolution API. Este comportamento não é esperado e pode causar confusões na comunicação com os usuários.

Solicitação de Correção:
Solicito gentilmente uma revisão e correção desse comportamento para garantir que as mensagens de e-mail sejam tratadas de forma independente das mensagens de WhatsApp. Isso garantirá uma experiência consistente para o usuário e evitará possíveis mal-entendidos na comunicação.

Passos para Reproduzir o Problema:

Configurar um canal de e-mail no Chatwoot.
Associar um número de telefone celular a um contato no Chatwoot.
Enviar um e-mail para esse contato.
Observar como a mensagem também é enviada para o WhatsApp através da Evolution API.
Agradeço antecipadamente pela atenção a este problema e pela pronta ação para corrigi-lo. Se precisarem de informações adicionais ou detalhes sobre a minha configuração, estou mais do que disposto a fornecê-los.

Obrigado pelo tempo e esforço dedicados ao desenvolvimento contínuo da Evolution API.

**Comment by dpaes** [comment]
Poderia me informar se continua com o problema? chegou a efetuar o update de versão do chatwoot como também usar a evolution mais atual?

**Comment by dpaes** [comment]
Caso persista o problema e esteja usando uma versão mais atual, estarei reabrindo a issue
