### ISSUE TITLE
[EN][BUG] VERSION 1.6.2 Homolog,  Duplicando mensagem no final de fluxo,

### ISSUE THREAD

**Issue by alekyxander** [EvolutionAPI/evolution-api#349]
Duplicando mensagem no final dos fluxos tanto typebot quanto n8n

#### Description:
notei que no final dos fluxos esta sendo duplicado as mensagens do fluxo, mesmo sendo finalziado, abaixo segue dois exemplos no n8n e no typebot,
Typebot
![image](https://github.com/EvolutionAPI/evolution-api/assets/46962468/7de0e2df-cfa4-4cdf-9b2d-bd156f3ac8a3)

N8n
![image](https://github.com/EvolutionAPI/evolution-api/assets/46962468/f31e7da5-1834-436d-bbf4-3e31423be869)

**Comment by val-leite** [comment]
AQUI TAMBÉM.

**Comment by Daan2022** [comment]
Estou com esse mesmo erro

**Comment by DavidsonGomes** [comment]
Pode enviar o fluxo para testar esse comportamento por favor
