### ISSUE TITLE
[PT][BUG] Mensagem de Conexão bem sucedida 'spamando' no Chatwoot

### ISSUE THREAD

**Issue by stgcompany** [EvolutionAPI/evolution-api#350]
#### Descrição:
A cada algumas horas, pelo que percebi em média três vezes ao dia o contato no Chatwoot fica enviando a mensagem de notificação de conexão bem sucedida, o que para mim é estranho já que foi feita somente uma vez a conexão, mas ao passar dos dias ainda fica aparecendo essa mensagem o que vejo como algo indesejável.

#### Passos para Reproduzir:
1. Conecte-se numa instância do chatwoot
2. E veja o contato no chatwoot ficar notificando durante os dias.

#### Comportamento Esperado:
Mostrar a notificação apenas no primeiro momento em que for realizada a conexão com sucesso. 

#### Comportamento Atual:
Continua enviando a mensagem ao passar dos dias depois de ter sido conectada.

#### Capturas de Tela/Vídeos:
![image](https://github.com/EvolutionAPI/evolution-api/assets/143809393/7b1da149-31a9-4270-aa14-b233f6274f4a)

#### Ambiente:
- **Servidor:** Ubuntu 20.04
- **Versão da API:** 1.6.1
- **Outras Especificações de Hardware/Software:** Rodando no PM2

**Comment by luiztonucci** [comment]
Boa tarde, aqui também acontece isso, não sei se é normal, apenas confirmando a questão relatada acima
