### ISSUE TITLE
BUGS VS 1.6.0 E 1.6.1

### ISSUE THREAD

**Issue by val-leite** [EvolutionAPI/evolution-api#352]
MENSAGENS ESTÃO DUPLICANDO NO WHATSAPP, ESTÁ DANDO ERRO AO INSTALAR A VERSÃO 1.6.1. A VERSÃO 1.6.0 ESTÁ COM PROBLEMA NA INTEGRAÇÃO COM O TYPEBOT.

**Comment by ip2cloud** [comment]
Acredito que esse é o mesmo problema que estou tendo.. e pelo que responderam já está corrigido no 1.6.2 que está em dev.

https://github.com/EvolutionAPI/evolution-api/issues/345

**Comment by DavidsonGomes** [comment]
Issue fechada por nao seguir o padrão de report sugerido ao criar
