### ISSUE TITLE
[PT][BUG] Flag de iniciar como pendente no chatwoot altera o status da conversa aberta

### ISSUE THREAD

**Issue by GustavoGSA** [EvolutionAPI/evolution-api#354]
#### Descrição:
Marquei para iniciar a conversa como pendente na configuração do chatwoot, ao criar a conversa ele cria como pendente mas após abrir a conversa e uma nova interação do usuário com a conversa aberta ela volta para pendente e não deveria pois a conversa ja está criada.

#### Passos para Reproduzir:
1. Marcar flag "Iniciar como pendente na integração com chatwoot"
2. Mandar uma mensagem pelo whatsapp do cliente conversa vai ser criado e ficará como pendente
3. Abrir a conversa no chatwoot
4. Mandar uma nova mensagem pelo whatsapp do cliente
5. A conversa será alterada para pendente novamente

#### Comportamento Esperado:
Quando a conversa já estiver criada ele não deve mais alterar o status para pendente pois a flag é somente na criação da conversa.

#### Comportamento Atual:
A conversa fica como pendente sempre a cada mensagem.

#### Capturas de Tela/Vídeos:
![erro_pendente](https://github.com/EvolutionAPI/evolution-api/assets/5016203/bb34bb46-f305-4117-adea-171d0ee5df7d)

#### Ambiente:
- **Servidor:** Docker
- **Versão da API:** 1.6.1

**Comment by GustavoGSA** [comment]
Acredito que a solução seja simples só remover esse bloco! Pois a conversa já está criada então não deve passar para pendente somente reabrir.

![image](https://github.com/EvolutionAPI/evolution-api/assets/5016203/24fa6a39-7094-49c4-a669-2e8d5977ddf8)

**Comment by DavidsonGomes** [comment]
Veja a logica, se tu disse que quer que inicie como pendente, o sistema vai definir como pendente! retirar isso vai retirar isso, não entendi o problema ai, ta fazendo exatamente oq tu pediu pra fazer

**Comment by GustavoGSA** [comment]
> Veja a logica, se tu disse que quer que inicie como pendente, o sistema vai definir como pendente! retirar isso vai retirar isso, não entendi o problema ai, ta fazendo exatamente oq tu pediu pra fazer

Sim Davidson perdão, está errado mesmo não é para retirar o bloco é só para colocar o filtro de aberta, uma vez aberta a conversa não pode voltar a ficar pendente a cada interação.

![image](https://github.com/EvolutionAPI/evolution-api/assets/5016203/25d4a7a9-cdcc-408d-9b42-65b5d6ab2ddc)

Criei uma imagem pra mim com o código assim e está funcionando.

**Comment by arthurrferroni** [comment]
Estou com o mesmo problema aqui, uma conversa depois de aberta, quando chega um mensagem nova a evolution coloca como pendente novamente.
O correto seria apenas quando a conversa é criada ele definir como pendente e depois de aberta não alterar mais o status

**Comment by idealprint** [comment]
Passei a ter esse problema depois de atualizar o chatwoot para a versão 3.7.0 e a evolution para a versão 1.7.0. O problema é qua atualizei ambos, e não sei se o problema está na evolution ou no chatwoot.

**Comment by vitor-help** [comment]
Vocês resolveram? Estou com esse mesmo problema agora kkkk, estou usando a última versão do chatwoot, vocês sabem qual versão esse problema não acontece? Problema chato esse, o código acima resolveu o problema?

**Comment by GustavoGSA** [comment]
Sim @vitor-help, eu atualizei para a EVO 1.8.2 e msm assim está com problema, o código acima resolve.

**Comment by help-corretora** [comment]
![Sem título](https://github.com/user-attachments/assets/9623fb40-16fe-4c7b-933d-2b75d4ca0145)

Acho que esse erro voltou na versão 2.2.0 do evolution, estou com o exato mesmo erro, só que na versão 2.2.0, com um agravante, fui procurar o arquivo citado aqui e o método para consertar, quem disse que esse caminho existe, alias, quem disse que eu achei esse método no projeto evo na versão 2.2.0 kkkkkk, alguma sugestão, pessoal? Estou quase fazendo um downgrade de versão.

**Comment by vitor-help** [comment]
@help-corretora , eu estava dando uma olhada no código do link abaixo, realmente agora mudaram de lugar essa funcionalidade e agora tem 2 lugares que acredito que seja necessário adicionar a validação conversation.status !== 'open'.
Pesquisa dentro do código if (this.provider.conversationPending) { que ele vai retornar os dois lugares, vou fazer aqui e testar e reporto.

https://github.com/EvolutionAPI/evolution-api/blob/main/src/api/integrations/chatbot/chatwoot/services/chatwoot.service.ts

![image](https://github.com/user-attachments/assets/4f631310-be5e-4fed-a82d-b53b1f6fd2f7)

**Comment by Eliakim-Oliveira** [comment]
Vi em outro post que isso acontece quando tem um bot conectado. Eu removi o bot e funcionou. Mas, o ideal seria que isso não acontecesse com o bot conectado.

[88235501](https://github.com/EvolutionAPI/evolution-api/issues/488#issuecomment-2020630725)
