### ISSUE TITLE
[PT][BUG] Erros de envio e exibição de status de envio de midias no chatwoot

### ISSUE THREAD

**Issue by raphagamendes** [EvolutionAPI/evolution-api#356]
#### Descrição:

Estamos enfrentando alguns problemas relacionados ao envio e exibição de mensagens em PDF no chatwoot. Esses problemas afetam a experiência do usuário e precisam ser resolvidos o mais rápido possível. Abaixo, detalhamos os principais cenários em que os problemas ocorrem:

Timeout ao enviar PDFs: Quando enviamos uma mensagem contendo um PDF, o chatwoot leva alguns segundos para processar e carregar o arquivo. No entanto, em muitos casos, o chatwoot retorna um erro de timeout antes que o processo seja concluído. Isso faz com que a mensagem seja marcada como não enviada, embora o arquivo seja, de fato, entregue com sucesso. Isso causa confusão para o usuário, que vê o PDF no aplicativo móvel, mas o chatwoot indica que a mensagem não foi entregue.

Falha no envio de PDFs com comentário: Quando enviamos um PDF com uma mensagem de acompanhamento, a mensagem não está sendo enviada corretamente para o celular. Isso significa que o usuário não recebe a mensagem.

Erros de status de envio: Às vezes, ao enviar vários PDFs em sequência, a plataforma relata que os arquivos não foram enviados, embora eles tenham sido entregues com sucesso no celular. Isso causa confusão e frustração entre os usuários.

#### Capturas de Tela/Vídeos:
Enviarei assim que possivel.

#### Ambiente:
- **Servidor:** Contabo -  Ubuntu 20.04.6
- **Chatwoot:** -v3.3.1
- **Versão da API:** 1.6.1

**Comment by jaison-x** [comment]
Olá @raphagamendes 

O timeout é do próprio Chatwoot. Pelo que vi a partir da versão 3.4.0 eles colocaram um timeout de 5 segundos para as requisições de webhooks. Infelizmente imagino que a evo não tem muito o que fazer. Se quiser você pode ajustar editando diretamente o Chatwoot: caminho `/lib/webhooks/trigger.rb#29`: 

![image](https://github.com/EvolutionAPI/evolution-api/assets/5599142/fd2199f9-5052-4d7e-ba59-38145892cd0f)

**Comment by raphagamendes** [comment]
Olá @jaison-x  muito obrigado pela dica, resolveu perfeitamente o problema que eu estava enfrentando.

**Comment by raphagamendes** [comment]
Olá @jaison-x  muito obrigado pela dica, resolveu perfeitamente o problema que eu estava enfrentando.
