### ISSUE TITLE
[PT][BUG] Problema de duplicação de contato com contatos com número 9 no celular

### ISSUE THREAD

**Issue by GustavoGSA** [EvolutionAPI/evolution-api#357]
#### Descrição:
Importei para a base do chatwoot os contatos que tenho existentes, porém em número que foram incluídos o número 9 antes mas no WhatsApp está sem o 9 ele não faz o link com esse contato e sim cria um novo ficando contatos duplicados.

#### Passos para Reproduzir:
1. Configure o chatwoot na evolution
2. Importe ou cadastre um contato com o número 9 antes do celular
3. Chame no WhatsApp de um número que no WhatsApp está sem o 9

#### Comportamento Esperado:
Ele não deve criar outro contato sem o 9 e sim pegar o contato existente com o 9 na base do chatwoot

#### Comportamento Atual:
Não encontra o contato com o 9 antes e duplica o contato

#### Ambiente:
- **Servidor:** Docker
- **Versão da API:** 1.6.1

#### Notas Adicionais:
Sugestão para correção do problema.

![image](https://github.com/EvolutionAPI/evolution-api/assets/5016203/6534b084-17fe-4150-920a-de0591bca77e)

**Comment by stgcompany** [comment]
Também estou com o exato mesmo problema.

E pra mim ainda foi pior pois faço uso do typebot junto com o n8n para pausar o chatbot quando abrir novas conversas com o atendimento. E com essa duplicação de contatos acabou que um cliente abriu uma conversa com um contato que foi cadastrado manualmente COM O 9 e até chegou as mensagens, só que quando o contato respondeu, acabou criando um novo contato e uma nova conversa sem o dígito nove e o chatbot interferiu na conversa. Isso causou uma bagunça na conta do meu cliente.

Enfim, descobri isto hoje e vou agora buscar uma forma de evitar isso. Se alguém conseguir resolver faz um PR pra ajudar a gente, que se eu conseguir ajustar a tempo, assim farei também!

**Comment by GustavoGSA** [comment]
> Também estou com o exato mesmo problema.
> 
> E pra mim ainda foi pior pois faço uso do typebot junto com o n8n para pausar o chatbot quando abrir novas conversas com o atendimento. E com essa duplicação de contatos acabou que um cliente abriu uma conversa com um contato que foi cadastrado manualmente COM O 9 e até chegou as mensagens, só que quando o contato respondeu, acabou criando um novo contato e uma nova conversa sem o dígito nove e o chatbot interferiu na conversa. Isso causou uma bagunça na conta do meu cliente.
> 
> Enfim, descobri isto hoje e vou agora buscar uma forma de evitar isso. Se alguém conseguir resolver faz um PR pra ajudar a gente, que se eu conseguir ajustar a tempo, assim farei também!

Sim para quem usa contatos já pré cadastrados vira uma bagunça, eu fiz um "gambiarra" para contornar fiz um webhook na minha api e faço a mesclagem do contato manualmente, sempre que cria um novo contato no chatwoot chama meu webhook e eu verifico se ele ja existe com o 9 se já existir eu copio tudo dele para o novo e excluo o antigo. rs

Resolveu mas não é o ideal, vou alterar direto no código da EVO e testar direitinho, com isso consigo eliminar a gambiarra e faço a PR

**Comment by stgcompany** [comment]
Eu tentei ajustar esse problema pelo lado do chatwoot, adicionando a seguinte condicional considerando erro quando possuir o dígito nove na criação ou edição do número do contato:

![image](https://github.com/EvolutionAPI/evolution-api/assets/143809393/478d0d4d-44e8-44da-a097-687ec048487b)

Também adicionei um aviso sobre a questão do formato do número sem o nove:

![image](https://github.com/EvolutionAPI/evolution-api/assets/143809393/5ccaafea-6ef7-440a-8cde-a4bb4db502f0)

E também removi temporariamente a funcionalidade de importar contatos, que nos meus testes já era meio bugado e confuso na forma correta de importação, visto que também o cliente poderia acabar importando contatos com o dígito nove.

Agora só falta eu ver como vou ajustar os contatos que já foram bagunçados com essa duplicação de com ou sem o nove. Talvez eu vá ajeitar na mão mesmo, visto que isso não mais ocorrerá (assim espero) por conta do filtro que criei.

**Comment by yvescleuder** [comment]
Seria interessante a Evolution considerar o uso do número 9.
Atualmente eu uso Cloud API + Evolution API.
Na API Oficial os numeros ficam salvos com o 9, acaba que quando nós entramos em contato, a mensagem até vai para o cliente, mas quando ele responde, acaba criando uma nova conversa devido ao cliente responder sem o número 9.

**Comment by yvescleuder** [comment]
https://github.com/EvolutionAPI/evolution-api/pull/382

**Comment by GustavoGSA** [comment]
Issue fechada pois o @yvescleuder já fez essa correção na #382. Obrigado.
