### ISSUE TITLE
[PT][FEAT] confirmação de leitura de mensagens no chatwoot

### ISSUE THREAD

**Issue by nestordavalos** [EvolutionAPI/evolution-api#361]
#### Descrição Detalhada:
Descreva claramente e em detalhes a funcionalidade que você deseja que seja implementada. Explique como isso se encaixa no contexto do projeto.

confirmação de leitura de mensagens no chatwoot

#### Racional:
Explique por que essa funcionalidade seria útil para o projeto. Isso ajuda a entender a importância e a prioridade da solicitação.

Para isso é necessário utilizar a API chatwoot que seria a seguinte
{{host}}/public/api/v1/inboxes/{{inbox_identifier}}/contacts/{{contact_identifier}}/conversations/{{conversation_id}}}}/update_last_seen

quando o Whatsapp Evolution retornar o status da mensagem READ envie a solicitação para chatwoot

#### Exemplos de Uso:
Forneça exemplos específicos de como essa funcionalidade poderia ser utilizada. Isso pode incluir cenários ou casos de uso onde a funcionalidade seria particularmente benéfica.

#### Possíveis Implementações:
Se você tem ideias sobre como essa funcionalidade pode ser implementada, por favor, compartilhe-as aqui. Isso não é obrigatório, mas pode ser útil para a equipe de desenvolvimento.

#### Impacto no Projeto:
Discuta como essa nova funcionalidade poderia impactar outras partes do projeto, se aplicável.

#### Notas Adicionais:
Qualquer outra informação que você acredita ser relevante para a sua solicitação.

**Comment by lindenbergp** [comment]
Seria interessante que o chatwoot também enviasse o status de lido para o whatsapp. Ou seja o cliente manda uma mensagem pra minha empresa. Quando o atendente abrir a conversa e ler a mensagem o chatwoot mande a confirmação para o whatsapp do cliente que foi lida. Será se e possível?

**Comment by lindenbergp** [comment]
Esse opção marca automático independente de o atendente abrir a conversa ou não no chatwoot. Não e a opção certa marca que foi lido sem nem ter visto a mensagem lá no chatwoot.

**Comment by DavidsonGomes** [comment]
implementado na nova versao

**Comment by guhweb** [comment]
Qual é esse recurso exatamente? Fiz um teste com as opções disponíveis na versão 2.2.3, mas nenhuma delas marcou a conversa como lida assim que abri a conversa.

A opção de marcar todas como lida funciona, mas ele faz isso quando é "lido" pelo evolution api e antes de chegar no chatwoot! 

Pelo que entendi esse "implementado na nova versao" pelo @DavidsonGomes seria marcar a mensagem como lida assim que uma conversa é aberta, confere?
