### ISSUE TITLE
[PT][BUG] Access to this endpoint is not authorized for bots

### ISSUE THREAD

**Issue by jaison-x** [EvolutionAPI/evolution-api#365]
### Título: Access to this endpoint is not authorized for bots

A versão 3.5.0 do chatwoot não permite uso do token do super usuário para utilizar a API. Caso for usado o token deste usuário irá aparecer a seguinte mensagem de erro: "Access to this endpoint is not authorized for bots". Não sei se isso é um bug ou é o realmente o comportamento esperado.

Até o momento, encontrei duas opções para resolver. Você pode criar um novo usuário sem ser SuperAdmin e usar o novo token na Evolution, ou então, editar um arquivo do chatwoot para permitir SuperAdmin utilizar a API.

O arquivo para editar e permitir o uso do SuperAdmin é o `\app\controllers\concerns\access_token_auth_helper.rb#17`

`Current.user = @resource if [User, AgentBot, SuperAdmin].include?(@resource.class)`

![image](https://github.com/EvolutionAPI/evolution-api/assets/5599142/6d13b3f6-56b3-4a28-ada8-0c7bb4ae9099)

Se alguém souber uma solução melhor, por favor compartilhe.

**Comment by vailtom** [comment]
Um log um pouco mais detalhado que obtive foi:
```
[Evolution API]  v1.6.0  1   -  Tue Jan 16 2024 22:35:11     ERROR   [ChatwootService]  [object]   
ApiError: Unauthorized
    at catchErrorCodes (/evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:226:15)
    at /evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:257:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  url: 'https://chat.kairo.com.br/api/v1/accounts/1/inboxes',
  status: 401,
  statusText: 'Unauthorized',
  body: { error: 'Access to this endpoint is not authorized for bots' },

  request: {
    method: 'GET',
    url: '/api/v1/accounts/{account_id}/inboxes',
    path: { account_id: '1' },
    errors: { '403': 'Access denied', '404': 'Inbox not found' }
  }
} 
```

Tem relação com este código aqui:

<img width="779" alt="Screen Shot 2024-01-16 at 23 00 28" src="https://github.com/EvolutionAPI/evolution-api/assets/4702005/26e3f471-4b56-4d7c-82e3-91df41d4b672">

**Comment by jaison-x** [comment]
> Um log um pouco mais detalhado que obtive foi:
> 
> ```
> [Evolution API]  v1.6.0  1   -  Tue Jan 16 2024 22:35:11     ERROR   [ChatwootService]  [object]   
> ApiError: Unauthorized
>     at catchErrorCodes (/evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:226:15)
>     at /evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:257:17
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   url: 'https://chat.kairo.com.br/api/v1/accounts/1/inboxes',
>   status: 401,
>   statusText: 'Unauthorized',
>   body: { error: 'Access to this endpoint is not authorized for bots' },
> �
>   request: {
>     method: 'GET',
>     url: '/api/v1/accounts/{account_id}/inboxes',
>     path: { account_id: '1' },
>     errors: { '403': 'Access denied', '404': 'Inbox not found' }
>   }
> } 
> ```
> 
> Tem relação com este código aqui:
> 
> <img alt="Screen Shot 2024-01-16 at 23 00 28" width="779" src="https://private-user-images.githubusercontent.com/4702005/297237780-26e3f471-4b56-4d7c-82e3-91df41d4b672.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTM1MzEsIm5iZiI6MTcwNTQ5MzIzMSwicGF0aCI6Ii80NzAyMDA1LzI5NzIzNzc4MC0yNmUzZjQ3MS00YjU2LTRkN2MtODJlMy05MWRmNDFkNGI2NzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTdUMTIwNzExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTM2ZTQwOGM5NTZiNzEzOTA1NjQ2ZmQzNzgxNzc3YThhNTcyNGQ2YzA1M2U3OTE4NzJiZGViNjE0ZDU1YTFkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CpnQllZIiCGjPTim1ZcugUOy6sGc9Cp9en9wSdC5F4Q">

Por agora acredito que a melhor solução é não usar o token de um usuário SuperAdmin na integração. Crie um novo usuário (ou edite o usuário atual) sem ser SuperAdmim e use este token na Evolution.

Deixe este campo `Type` vazio ao criar/editar o usuário.

![image](https://github.com/EvolutionAPI/evolution-api/assets/5599142/e0f82e14-d3c5-4d9d-836f-75659fbe71f7)

Se criou um novo usuário, faça login com este novo usuário, entre na página de perfil e pegue o novo token: 

![image](https://github.com/EvolutionAPI/evolution-api/assets/5599142/bcbca5ef-0d35-4b2d-81a1-aed507ebada9)

Use este novo token na integração.

**Comment by edisoncm-ti** [comment]
> O arquivo para editar e permitir o uso do SuperAdmin é o `\app\controllers\concerns\access_token_auth_helper.rb#17`
> 
> `Current.user = @resource if [User, AgentBot, SuperAdmin].include?(@resource.class)`
> 
> ![image](https://private-user-images.githubusercontent.com/5599142/297186192-6d13b3f6-56b3-4a28-ada8-0c7bb4ae9099.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTgxNTAsIm5iZiI6MTcwNTQ5Nzg1MCwicGF0aCI6Ii81NTk5MTQyLzI5NzE4NjE5Mi02ZDEzYjNmNi01NmIzLTRhMjgtYWRhOC0wYzdiYjRhZTkwOTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTdUMTMyNDEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQzNTdlNDYzOTc1NGFhZDQ3YmRkZGQyOThhZWM0YTQwNDMwMTVmOWRjNWYzMTc0MTRkMmYwZjY2YWRjZDUyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.k2gEGmdSahRz8THY5HGbmg_vOw1TEnWIqzYDWzk5mvI)

Fala @jaison-x, 

Essa solução funcionou perfeitamente, apesar de ser um pouco complicada de implementar pra quem não souber personalizar imagens.

Como no meu caso já tinha um longo histórico de mensagens para o user **SuperAdmin**, não me pareceu razoável criar um outro como **User** e perder essas referências.

Infelizmente como essa é uma codificação feita no próprio ChatWoot, acredito que a solução para a maioria seja logo que instalar o ChatWoot, já criar logo um **User** e manter o **SuperAdmin** apenas para gerenciamento e não como operacional.

Teoricamente, esse até seria o cenário mais correto, pensando em normas e procedimentos, mas sabe como é, né:

_- "Em casa de ferreiro, o espeto é de pau!"_  🫣😉

Abraço...

**Comment by matheusmaiberg** [comment]
Não seria melhor alterar a evo para usar o agent_bot, ja que a solucao e exatamente pra isso, bots em multiplas contas, igual a quepasa faz?

**Comment by jaison-x** [comment]
Resolvido na versão do Chatwoot 3.5.2.

**Comment by Pezhvak** [comment]
my issue was from this:
https://github.com/orgs/chatwoot/discussions/8112
took me a lot to figure out.
