### ISSUE TITLE
[PT][BUG] Webhook não envia evento messages.update READ quando a msg é lida a partir do Whatsapp Web

### ISSUE THREAD

**Issue by up4all-sistemas** [EvolutionAPI/evolution-api#367]
#### Descrição:
Percebi que na versão 1.6.0 que, se envio uma mensagem via api, e a mesma mensagem é lida primeiramente a partir do whatsapp web ou app desktop, o webhook do evento messages.update com o payload de READ não é enviado. Quando o mesmo cenário e feito, mas lendo a mensagem primeiramente pelo app do whatsapp, seja android ou iOS, o evento é gatilhado e enviado pelo webhook normalmente.

#### Passos para Reproduzir:
1. Enviar qualquer mensagem usando a api do Evolution
2. Ler a mensagem de um dispositivo diferente do app whatsapp Android/iOS
3. Verificar se o webhook será chamado com o evento messages.update com payload READ

#### Comportamento Esperado:
Que o webhook fosse chamado para todos os eventos messages.update com payload de READ, independente da plataforma onde foi gerado.

#### Ambiente:
- **Servidor:** Dedicado ColoCrossing 1 x Intel E3 1240 V2 32GB DDR3 1333MHz (Kubernetes)
- **Versão da API:** 1.6.0
- **Outras Especificações de Hardware/Software:** API rodando em Docker/Kubernetes, atrás de NGINX Ingress

**Comment by cirinho** [comment]
estou usando a versão 1.6.0 e o webhook não escuta mensagens enviadas pelo aplicativo whatsapp do windows

**Comment by DavidsonGomes** [comment]
Funcionando normalmente

![Uploading image.png…]()
