### ISSUE TITLE
[PT][BUG] - Não consigo conectar mais de uma instancia (Conflito)

### ISSUE THREAD

**Issue by andersondiaspereira25** [EvolutionAPI/evolution-api#368]
#### Descrição:
Não consigo conectar mais de uma instancia na evolution

#### Envio de Logs:
pid=1 hostname=evolution3zmmrxd node={"tag":"stream:error","attrs":{},"content":[{"tag":"conflict","attrs":{"type":"replaced"}}]} msg=stream errored out

**Comment by GustavoGSA** [comment]
Aqui rolava isso porque estava usando Redis ele foi descontinuado na EVO. Se tiver usando retira ele e refaz toda a instalação da evo e mongo.
Aqui resolveu.

**Comment by shsolutions** [comment]
estou passando por esse erro pid=268 hostname=76c4c6239128 node={"tag":"stream:error","attrs":{"code":"401"},"content":[{"tag":"conflict","attrs":{"type":"device_removed"}}]} msg=stream errored out

instalei ele no docker e uso a versão 2.2.3
