### ISSUE TITLE
Deley chatwoot

### ISSUE THREAD

**Issue by AstraOnlineWeb** [EvolutionAPI/evolution-api#38]
Criar uma requisição para api que permita colocar um delay, no Chatwoot quando enviamos via chatbot um imagem e depois um texto, é enviado primeiro o texto e não a imagem, não respeita a sequência.

Sugestão criar um delay que seja possível enviar via webhook ou algo do tipo para a api. 

Se possível definir o tempo no delay seria interessante também.

Segue exemplos:

![image](https://github.com/EvolutionAPI/evolution-api/assets/140722210/d2ca9ae0-3b16-4a34-bb69-49913d7ed6f8)

**Comment by DavidsonGomes** [comment]
A questao do delay nao conseguiremos implementar, isso deve ser feito do lado do chatwoot
