### ISSUE TITLE
[PT][BUG] TypeBot duplica as respostas quando conectado ao chatwoot 

### ISSUE THREAD

**Issue by mariolandossa** [EvolutionAPI/evolution-api#384]
#### Descrição:
Vestão homolog instalada via docker para testar envio de lista, ao enviar o fluxo a mensagem é repetida uma normal e outra com a identificação do agente logado no chatwoot

#### Passos para Reproduzir:
1. Enviar uma pegunta para o fluxo do typeboot.

#### Comportamento Esperado:
Não deveria duplicar as mensagens do bot

#### Comportamento Atual:
Mensagens duplicadas 

#### Capturas de Tela/Vídeos:
![WhatsApp Image 2024-01-28 at 10 51 18](https://github.com/EvolutionAPI/evolution-api/assets/67331925/bf534168-33f9-43b7-acd1-44a192fb59de)

#### Ambiente:
- **Servidor:Ubuntu 22.04
- **Versão da API:1.6.2
- **Outras Especificações de Hardware/Software:** [ex: CPU, GPU]

#### Envio de Logs:
Por favor, anexe os logs que possam estar relacionados ao problema. Se os logs contiverem informações sensíveis, considere enviá-los de forma privada para um dos mantenedores do projeto.

#### Notas Adicionais:
Inclua aqui qualquer outra informação que você ache que possa ser útil para entender ou resolver o bug.

**Comment by oscarnascimento** [comment]
Isso está acontecend comigo também. Usando Evolution v1.7.0, chatwoot 3.3.1, typebot 2.23.0

**Comment by jaison-x** [comment]
> Isso está acontecend comigo também. Usando Evolution v1.7.0, chatwoot 3.3.1, typebot 2.23.0

Na versão da evo 1.7 precisa usar no mínimo a versão do Chatwoot >= 3.4

**Comment by oscarnascimento** [comment]
É verdade, lembro que isso foi comentado em uma live pelo Davidson. Porém, quando eu atualizo minha versao para 3.5.2, que é a versão que está oficiamente indicada na Release Note, o chatwoot deixa de funcionar.

**Comment by oscarnascimento** [comment]
O pior de tudo é que eu nem sei como ajustar isso, ainda estou tateando as tecnologias.

**Comment by oscarnascimento** [comment]
Voltou a funcionar, porém precisei remover os containers e subir novamente
