### ISSUE TITLE
[PT][BUG] Typebot não inicia o fluxo de atendimento pela EvoApi

### ISSUE THREAD

**Issue by roccianetto** [EvolutionAPI/evolution-api#386]
Estou com problema ao iniciar o fluxo do Typebot na Evolution API, estou utilizando a Evo 1.6.1 e o Typebot 2.21.3, antes de atualizar funcionava normalmente, depois que atualizei parou de funcionar. Todas as configurações estão corretas, alguém já passou por isso ou tem alguma solução?

**Comment by DavidsonGomes** [comment]
Dificil dizer sem saber como esta o fluxo, aqui continua funcionando normalmente

**Comment by AndersonMairnck** [comment]
tambem estou tendo problema , fiz um fluxo simples, so para teste mas nao inicia.

**Comment by AnxHall** [comment]
RESOLVIDO PARCIAL
Vai em :
/seudiretorio/src/env.yml

acha essa linha ( usa o f3 pra achar pó)

TYPEBOT:
API_VERSION: 'old' # old | latest

!!!!! alterar para" latest" !!!!!

TYPEBOT:
API_VERSION: 'latest' # old | latest

Depois e só atualizar usando:

pm2 status
<(pega o numero da sua id)>

pm2 restart --update-env
<(exemplo pm2 restart 0 --update-env)>

EvolutionAPI 1.6.1

**Comment by raphaeloliveirasilva** [comment]
estou com um problema parecido, já testei de varias maneiras, se eu estiver mexendo no aplicativo do whatsapp o fluxo funciona normal, depois de um tempo sem mexer, ele parece que fica suspenso, algumas mensagens de clientes chegam e ele não responde, só voltando a responder quando eu entro no aplicativo do whatsapp e abro a conversa, ai imediatamente o fluxo do typebot ativa, estava usando o whatsapp no aplicativo normal no celular, agora estou tentando usar com o memuplay pra deixar sempre ligado, mas aconteceu novamente, tambem estou com a opção "sempre online" ativada na instancia.

**Comment by raphaeloliveirasilva** [comment]
> RESOLVIDO PARCIAL Vai em : /seudiretorio/src/env.yml
> 
> acha essa linha ( usa o f3 pra achar pó)
> 
> TYPEBOT: API_VERSION: 'old' # old | latest
> 
> !!!!! alterar para" latest" !!!!!
> 
> TYPEBOT: API_VERSION: 'latest' # old | latest
> 
> Depois e só atualizar usando:
> 
> pm2 status <(pega o numero da sua id)>
> 
> pm2 restart --update-env <(exemplo pm2 restart 0 --update-env)>
> 
> EvolutionAPI 1.6.1

o meu aqui está dessa forma, estou usando as mesmas versões da evolution e typebot,

**Comment by pbrumoliver** [comment]
Meu typebot estava funcionando normalmente, faz uns 2 dias que parou, mesma questão acima quando um número de WhatsApp chama o bot pela primeira vez, o bot responde, aí depois não mais. Lembrando que criei um fluxo com ia, alguem sabe me dizer oq pode ser?
