### ISSUE TITLE
[PT][BUG] Instância é excluída ao reiniciar o serviço

### ISSUE THREAD

**Issue by drauber** [EvolutionAPI/evolution-api#388]
#### Descrição:
Toda vez que eu reinicio o serviço e tenho instâncias que não estão conectadas, elas são excluídas.

#### Passos para Reproduzir:
1. Criar 3 instancias.
2. Conectar apenas uma delas.
3. Parar o serviço da Evolution API.
4. Iniciar o serviço da Evolution API.
5. Observar que as instancias que não estavam conectadas foram excluídas.

#### Comportamento Esperado:
Eu gostaria que mesmo as instancias desconectadas permanecessem existindo.

#### Comportamento Atual:
As instancias desconectadas são excluídas na reinicialização da API.

#### Notas Adicionais:
Talvez essa seja uma funcionalidade para a qual eu simplesmente ignoro algum parametro, tentei verificar no env.yml e não consegui identificar nada que impeça esse comportamento, no env.yml tenho DEL_INSTANCE: false

**Comment by DavidsonGomes** [comment]
Sim, comportamento padrão!
