### ISSUE TITLE
Manter sessão criada

### ISSUE THREAD

**Issue by AstraOnlineWeb** [EvolutionAPI/evolution-api#39]
Ao enviar os dados para criar uma nova caixa de entrada é criado uma nova sesão para se conectar.

Após o tempo de geração de QR code a api esta excluindo a sessão. Mesmo enviando o comando para /init para gerar o QR novamente a api não consegue retormar. Neste formato o cliente precisar apagar a caixa e criar novamente. 

Se puder ajustar, obrigado.

**Comment by mssmello** [comment]
Notei o mesmo aqui. Se um número for conectado, os comandos funcionam normalmente, status, desconectar e iniciar ou init para gerar novo QR code.

Se quando desconectado, executar pm2 restart all o comando iniciar não cria mais um novo QR code.

Obrigado.

**Comment by DavidsonGomes** [comment]
Resolvido na versao 1.5.0
