### ISSUE TITLE
[PT][BUG] Timeout em chat/fetchProfile/ quando o número não é whatsapp

### ISSUE THREAD

**Issue by rodrigo-pasini** [EvolutionAPI/evolution-api#403]
#### Descrição:
Estou usando esse endpoint para verificar se alguns números de celular são ou não whatsapp. O que são, o response vem corretamente, mas para os que não são não vem resposta até dar 504 gateway timeout. O recurso de verificar no manager funciona corretamente.
Percebi o problema em uma automação no n8n, mas ele se reproduziu no postman

#### Passos para Reproduzir:
1. Faça uma chamada no endpoit chat/fetchProfile/ com um número que não é whatsapp
Exemplo da chamada que usei:
`curl --location 'https://sub.dominio.dev.br/chat/fetchProfile/MinhaInstancia' \
--header 'apikey: minha_api_key' \
--header 'Content-Type: application/json' \
--data '{
    "number": "553500000000"
}'`

#### Comportamento Esperado:
Esperaria receber um response com os campos indicando que não é um whatsapp, semelhante a quando é.

#### Comportamento Atual:
Timeout

#### Ambiente:
- **Servidor:** Ubuntu 22.04 - Docker e Docker Compose. Nginx, letsEncrypt
- **Versão da API:**  1.6.1 - Instalação nova (06/02/2024) via docker compose

#### Notas Adicionais:
Se houver uma forma melhor de checar se alguns números são whatsapp isso resolve meu problema. Outro ponto a destacar é que via manager built in a feature funciona. Todos os outros recursos da API que testei funcionaram perfeitamente até agora.

**Comment by DavidsonGomes** [comment]
Problema resolvido na nova versao
