### ISSUE TITLE
[PT][FEAT] Voltar typebot após encaminhar para chatwoot

### ISSUE THREAD

**Issue by wagnerdracha** [EvolutionAPI/evolution-api#405]
Bom dia

Tudo bem?

Eu estou utilizando o chatwoot + evolution API + typebot + n8n + minio para fazer as automatizações.

Contudo, tenho um problema que eu gostaria de saber como resolver.

Eu recebo uma mensagem via whatsapp, aonde o typebot encaminha a pessoa pelos menus até chegar a passar para um atendente.

Essa passagem para o atendente é feito dentro do chatwoot, que faz uma automação para verificar se a palavra "estamos te transferindo para ..." está presente na mensagem. Aí o chatwoot vai tranferir para um time.

Só que a partir daí, a pessoa fica presa na conversa com o atendente no chatwoot até ficar 10 minutos sem interação com o whatsapp, aí ele excluir a sessão e o typebot volta.

Contudo, eu não quero esperar 10 minutos sem interação para poder voltar o typebot.

Eu gostaria de mandar uma mensagem, tipo "#terminar" e o chatwoot identificar e chamar uma automatização para terminar a sessão e voltar o typebot.

Alguém já fez isso?

Agradeço desde já.

**Comment by carloshaugusto** [comment]
Estou com o mesmo problema, conseguiu resolver?
