### ISSUE TITLE
Split de nomes de caixas de entrada

### ISSUE THREAD

**Issue by AstraOnlineWeb** [EvolutionAPI/evolution-api#41]
Ao criar uma nova caixa de entrada não pode ser criadas com o mesmo nome, quando feito via formato saas fica inviavel acompanhar o cliente e saber qual o nome da caixa que ele esta criando.

Casa empresa tem seu ambiente, o ideal seria que cada caixa ao ser criada ja tenha sua identificação unica e exclusiva, evitando a duplicidade de sessões.

**Comment by codephix** [comment]
Gostei da da ideia, estarei implementando e irei compartilhar com o pessoal.

**Comment by DavidsonGomes** [comment]
Questão resolvida na versão 1.5.0
