### ISSUE TITLE
[PT][HELP] Obter número do telefone no typebot

### ISSUE THREAD

**Issue by IgorSantRocha** [EvolutionAPI/evolution-api#412]
#### Descrição:
Tenho uma instalação local do Evolution e do Typebot.
Estou tentando, pelo typebot, enviar uma chamada para uma API minha. 
Nessa chamada, eu preciso passar o número de telefone que iniciou a conversa.
Estou a algumas horas pesquisando e não estou achando nenhuma forma de fazer isso.
Alguma sugestão?

**Comment by IgorSantRocha** [comment]
Consegui descobrir como fazer

**Comment by zeroonend** [comment]
como posso puxar o telefone do lead?

**Comment by matheusschreiber** [comment]
Ajudando quem chegar depois aqui.

Para pegar o número ou o nome do contato do whatsapp basta usar o bloco `set variable` e ai você rola para baixo nas opções até achar `Phone Number` ou `Contact Name`

![image](https://github.com/user-attachments/assets/7041592d-3fda-4286-bfaa-4ed704682213)

**Comment by gmunaro** [comment]
Estou fazendo exatamente isso, mas não está funcionando. 

![Image](https://github.com/user-attachments/assets/fd190ec7-0520-4d4a-b7b6-6912857921a2)

![Image](https://github.com/user-attachments/assets/0e5c6883-6f2e-417f-83fa-f875c6bf5741)

**Comment by altomarketing** [comment]
Thats easy ...

Phone = {{={{remoteJid}}.split("@").at(0)=}}

**Comment by andrehneder** [comment]
Hello, just do the same as image

<img width="294" height="372" alt="Image" src="https://github.com/user-attachments/assets/c92a62fb-4800-46fd-a4d0-3a8aa9ef9237" />
