### ISSUE TITLE
[PT][BUG] Webhook sem a opção Webhook em evento, o body chega vazio

### ISSUE THREAD

**Issue by dilneiss** [EvolutionAPI/evolution-api#413]
#### Descrição:
Isso está acontecendo na versão stable

#### Passos para Reproduzir:
1. Desmarcar a opção "Webhook por eventos"
2. Realizar qualquer requisição para o evolution_api realizar um callback
3. Recebo o body completamente vazio

#### Comportamento Esperado:
Receber o body completo

#### Comportamento Atual:
Recebendo body vazio

**Comment by gobeyondpty** [comment]
this bug still exists. why was it closed?
