### ISSUE TITLE
[PT][BUG] Alterar "Ser adicionado a grupos" não está respeitando, ficando sempre "all"

### ISSUE THREAD

**Issue by dilneiss** [EvolutionAPI/evolution-api#414]
#### Descrição:
Estou tentando alterar na privacidade do usuário a opção groupadd, por API retorna que alterou conforme a opção informada, mas se realizar um fetchPrivacySettings vem sempre como "all", sendo que estou enviando "none". O mesmo acontece pelo manager.

#### Comportamento Esperado:
Alterar a opção de privacidade conforme o informado.

#### Comportamento Atual:
Sempre altera para "all"

**Comment by DavidsonGomes** [comment]
Para essa função so pode ser usado all, contacts ou contact_blacklist, o none nao funciona, vou corrigir isso no postman
