### ISSUE TITLE
[PT][BUG] Alterar nome do perfil não está funcionando

### ISSUE THREAD

**Issue by dilneiss** [EvolutionAPI/evolution-api#415]
#### Descrição:
Ao realizar uma requisição via api para alterar o nome, retorna success, via manager também, porém ao realizar um fetch para verificar o nome atual, está sempre desatualizado, ou seja, ele altera de fato no próprio whatsapp, porém se realizar o fetch ou abrir o manager, o nome está desatualizado, como se não tivesse de fato atualizado.

#### Comportamento Esperado:
Atualizar no whatsapp e atualizar no manager e no retorno da api.

#### Comportamento Atual:
Atualiza somente no whatsapp, não está atualizando o que fica salvo no banco de dados do evolution_api

**Comment by ip2cloud** [comment]
Também tive o mesmo desafio

**Comment by DavidsonGomes** [comment]
Esse problema é na propria Baileys, estaremos verificando isso junto a eles
