### ISSUE TITLE
[PT][FEAT] Possibilitar enviar o "digitando" ou o "gravando audio" e já ter um retorno imediato

### ISSUE THREAD

**Issue by dilneiss** [EvolutionAPI/evolution-api#417]
#### Descrição Detalhada:
Estou trabalhando com sistema de filas para enviar as mensagens pra contatos, meu sistema é uma plataforma sass, onde tenho vários clientes e com vários funis em andamento, mas tem uma limitação de envio de mensagens compartilhado com todos os clientes.
Por exemplo, o limite total é de 100, mas cada cliente pode ter no máximo 5 simultâneo.
Vamos supor que todos os clientes enviem audio de 3 a 5 minutos, cada item ficaria travado na fila durante 3 a 5 minutos (conforme seu tempo estipulado), logo então, chegaria um momento que os 100 itens na fila serão facilmente atingidos e "travando" novos envios de outras pessoas.
A idéia aqui, seria quando enviar apenas a presence "gravando audio" ou "digitando...", ter um retorno da api na hora, para que eu possa processar outros itens antes desse tempo acabar e agendar para enviar o texto ou o audio de fato quando der esse tempo total.
Com isso, dificilmente meu servidor atingirá o limite de itens na fila de 100, pois nenhum processo vai levar mais que 1 a 2 segundos.

#### Possíveis Implementações:
Acredito que poderia alterar o endpoint chat/sendPresence, incluindo uma opção nova "wait_end", que por padrão no código ser true que é como é hoje, e se enviar false, a api não espera finalizar o comando e retorna na hora a resposta, mas fica rodando em segundo plano essa requisição.

**Comment by w3nder** [comment]
Você pode fazer isso do seu lado, ao invés de usar o async/await na sua aplicação

**Comment by DavidsonGomes** [comment]
Ja temos a função do digitando independente, o ideal seria fazer o digitando e so ai enviar a mensagem sem delay, não como enviar com digitando no delay e ter o retorno automatico ao mesmo tempo, pois o sistema precisa aplicar o delay.

a sugestão

SendPresence
![image](https://github.com/EvolutionAPI/evolution-api/assets/24706726/96f82277-7799-4e30-8f86-9974884d33ca)

e so ai faz o sendMessage sem delay

**Comment by TiagoGouvea** [comment]
Na versão atual (v2+) não existe mais options, o `delay` e `presence` são na raiz do objeto, ao lado de `number`.
