### ISSUE TITLE
Criar novas empresas automaticamente

### ISSUE THREAD

**Issue by AstraOnlineWeb** [EvolutionAPI/evolution-api#42]
Criei no n8n um fluxo que faz a criação de novas empresas de forma automática, segue em anexo para inspiração. 

Neste formato faço um post a partir do envio de alguns dados via mensagem em um contato em específico, parecido com o que é feito para criação de novas caixas de entrada. 

No fluxo ele trata os dados, cria a nova empresa, cria o usuário inicial e já faz o post inicial criando uma caixa para o usuário. 

O mundo ideal seria conseguir fazer isso já no contato criado pela a api, e já aproveitando a ideia quando realizar o post já enviar as informações básicas, como: quantos usuários o cliente vai poder criar, quantas caixas. 

Assim conseguimos automatizar este processo também.

Muito obrigado... Qualquer dúvida sigo à disposição. 

https://astraonline.com.br/wp-content/uploads/2023/07/chatwoot_evolution_chatwoot2.zip

**Comment by DavidsonGomes** [comment]
Recurso implementado via N8N e fluxos disponibilizados no repositorio
