### ISSUE TITLE
[PT][BUG] Typebot não altera status para CLOSED

### ISSUE THREAD

**Issue by ip2cloud** [EvolutionAPI/evolution-api#422]
#### Descrição:
Não está sendo fechada a conversa com o typebot .

Nem por timeout e nem manual

#### Comportamento Esperado:

Quando executo o comando.

curl --location 'https://alguma.com.br/typebot/changeStatus/insta-teste' \
--header 'Content-Type: application/json' \
--header 'apikey: XXXXXXXX' \
--data-raw '{
    "remoteJid": "XXXXXXXXXX@s.whatsapp.net",
    "status": "closed" 
}'

Retorna como CLOSED

Mas se o usuário manda alguma coisa.. a ultima mensagem enviada pelo evolution é repetida.

#### Ambiente:
- **Servidor: Docker
- **Versão da API: 1.6.2
- Typebot: Versão: 2.22.2

**Comment by stgcompany** [comment]
Talvez você esteja confundindo os status "closed" e "paused", se seu intuito é para o chatbot para um contato em específico você tem que ter uma sessão pausada.

O status closed fecha a sessão, logo, liberando a criação de uma nova sessão assim que o contato enviar uma nova mensagem.

**Comment by DavidsonGomes** [comment]
Esta funciona como deveria, o closed encerra a sessao
