### ISSUE TITLE
[PT][BUG] Não recebendo notificação no Whatsapp Mobile ao conectar instância

### ISSUE THREAD

**Issue by stgcompany** [EvolutionAPI/evolution-api#423]
#### Descrição:
Não sei se posso considerar um bug e se somente acontece comigo, mas quando conecto qualquer número de whatsapp numa instância de qualquer tipo o app do Whatsapp no celular para de enviar notificações, o que é meio frustante para os meus usuários.

Entendo que isso deve-se ao fato da API fazer o uso do whats web o que acaba visualizando as mensagens e dispensando as notificações, mas se for possível dar a opção nas configurações da instância fim de manter ou não as notificações no celular seria interessante.

#### Passos para Reproduzir:
1. Crie e conecte em uma instância qualquer;
2. Veja que não mais receberá notificações no aplicativo mobile do Whatsapp.

#### Comportamento Esperado:
Continuar recebendo notificações no aplicativo do celular mesmo quando conectado em uma instância.

#### Comportamento Atual:
O celular para de receber notificações.

#### Capturas de Tela/Vídeos:
`null`

#### Ambiente:
- **Servidor:** Ubuntu 20.04 LTS
- **Versão da API:** 1.6.1 rodando no PM2

#### Envio de Logs:
`null`

#### Notas Adicionais:
`null`

**Comment by DavidsonGomes** [comment]
Isso acontece pois a api esta monitorando seu whatsapp como se estivesse com ele aberto no web, comportamento normal
