### ISSUE TITLE
[PT][BUG] Texto com undefined

### ISSUE THREAD

**Issue by rjsalgado** [EvolutionAPI/evolution-api#424]
#### Description:
Fiz uma conexão com typebot, Evolution-api, mas as mensagens no WatsApp sair com erro, o que eu notei é após os : fica esse erro mas eu consulto langfuse as mensagem foi enviada correta, veja um exemplo do erro:
Temos os seguintes produtos disponíveis:Refrigerantes:undefinedundefinedundefinedundefinedundefinedundefinedundefinedRefeições:undefinedSanduíches:undefinedundefinedundefinedSucos 400ml:undefinedEnergético / Água:undefinedundefinedundefinedundefinedEste é o cardápio atualizado com os produtos disponíveis.

#### Environment:
Docker - Evolution-API versão: 1.6.1

**Comment by DavidsonGomes** [comment]
Nao entendi muito bem, manda com print do fluxo como esta e como deveria funcionar
