### ISSUE TITLE
[PT][FEAT] TYPEBOT: "Expire" por tempo. sem depender de resposta

### ISSUE THREAD

**Issue by stgcompany** [EvolutionAPI/evolution-api#425]
[PT][FEAT] TYPEBOT: "Expire" por tempo. sem depender de resposta

#### Descrição Detalhada:
Poder definir um tempo de expiração que não dependa de uma resposta do usuário para realizar a lógica da expiração.

#### Racional:
Estou adaptando o recurso de expiração presente na integração com o typebot para ao invés de fechar a sessão, ela na verdade pausar e abrir a conversa no Chatwoot avisando para um administrador que aquela conversa ficou "inativa" pelo tempo que foi passado sem receber uma resposta para o chatbot.

Porém ao fazer esta adaptação percebi o fato de que para realizar a expiração a API depende da espera de uma resposta para acionar o método de acordo. O que vai contra o meu intuito de ter um tempo exato de "timeout" por inatividade.

#### Exemplos de Uso:
Um contato inicia uma conversa com o chatbot (typebot) mas depois de algumas mensagens não respondeu mais e o chatbot ficou lá esperando por uma resposta... Ao passar do tempo de expiração de 10min (exemplo), ou seja, passaram-se esse tempo e não houve uma resposta, então deve-se disparar o devido método de expiração.

#### Possíveis Implementações:
Não sei ao certo como isso pode ser modificado ou implementado a parte, como toda uma nova feature mesmo. Penso se talvez seja necessário algum tipo de serviço de mensageria, mas como não tenho muita noção da arquitetura da API da evolution deixo aqui em aberto para os que têm mais conhecimento.

#### Impacto no Projeto:
Dar maior oportunidade de personalização e dinamicidade na construção de chatbots usando typebot, evolution e outras plataformas open-source.

#### Notas Adicionais:
`null`

**Comment by willph** [comment]
A ideia é bacana, seria interessante se mandasse uma mensagem de retorno como por exemplo, "**chat encerrado por inatividade**"
Mensagem poderia ser configurada no menu do Typebot no Manager da Evolution

**Comment by stgcompany** [comment]
PS.: Eu também instiguei a ideia de ter a mesma funcionalidade, porém pelo lado do Typebot [nesta issue](https://github.com/baptisteArno/typebot.io/issues/1225).
