### ISSUE TITLE
[PT][FEAT] Mensagem automática ao enviar palavra-chave de finalização. (TypetBot)

### ISSUE THREAD

**Issue by willph** [EvolutionAPI/evolution-api#427]
#### Descrição Detalhada:
Pedido de melhoria relativo a função do typebot Chamada de palavras-chave de finalização.
O intuito é que quando enviasse a palavras-chave de finalização ele desse o retorno de uma mensagem automaticamente.

Exemplo: envio a palavra chave **#sair**, com isso desse um retorno de **chat encerrado pelo usuário**, por exemplo.

Na atual versão ao enviar a palavra-chave não se tem o retorno.

#### Racional:
Será útil para que os clientes tenha noção que realmente foi finalizado o seu atendimento.

#### Exemplos de Uso:

Na aba do typebot no manager da evolution, poderia ter algo parecido com o que tem em comportamento, para rejeitar chamadas, onde a pessoa pode configurar uma mensagem para ser enviada automaticamente.
A única diferença é que no menu Typebot estaria atrelado a palavra-chave o disparo da mensagem automática.

**Comment by tiefighter** [comment]
Usando EVO + CW + Typebot, o ideal seria um cenário assim:

Mensagem > Evo > CW 
                                    Se Pendente > Typebot
                                    Se Aberta > permanece no CW
