### ISSUE TITLE
[PT][BUG] Não é possível abrir o manager: Integration not found

### ISSUE THREAD

**Issue by dlc-letelier** [EvolutionAPI/evolution-api#428]
#### Descrição:

Nem no manager nem no Swagger é possível fazer login, pois aparece uma mensagem dizendo: Integration not found".

#### Passos para Reproduzir:
1. Abrir o EvolutionAPI e tentar fazer login.

#### Comportamento Esperado:
Deveria abrir a lista com todas as intâncias

#### Comportamento Atual:
Aparece mensagem de erro, conforme anexo.

#### Ambiente:
- **Servidor:** Debina 12
- **Versão da API:** [ex: 1.6.2]

#### Envio de Logs:
Por favor, anexe os logs que possam estar relacionados ao problema. Se os logs contiverem informações sensíveis, considere enviá-los de forma privada para um dos mantenedores do projeto.

evolution_api    | [Evolution API]  v1.6.2  1   -  Mon Feb 19 2024 13:55:45     VERBOSE   [WAStartupService]  [string]  Integration not found 

![image](https://github.com/EvolutionAPI/evolution-api/assets/60855725/e6934b68-745e-453b-93f8-67da3b2ee254)

**Comment by DavidsonGomes** [comment]
Corrigido ja

**Comment by dlc-letelier** [comment]
Muito obrigado. Atualizei e funciona normalmente.
