### ISSUE TITLE
Evolution API - Instâncias conectadas SOMEM apos reiniciar servidor

### ISSUE THREAD

**Issue by COMPAGNONIS** [EvolutionAPI/evolution-api#429]
As instancias da api conectadas somem apos reiniciar ou desligar droplet do servidor, nao as encontrei em nenhum local salva!

**Comment by DavidsonGomes** [comment]
Verifique se configurou a conexao com mongodb corretamente, se nao tiver usando mongodb verifique se criou os volumes dos arquivos da evolution como manda na documentação

**Comment by michaelvips** [comment]
@DavidsonGomes Por gentileza poderia me tirar uma duvida técnica, tem relação com esse post.

Na documentação é indicado a criar 2 volumes **mongodb_data** e **mongodb_configdb** , quando se usa o mongo DB se não for criado, ao reiniciar / atualizar ele perde os dados de conexão com o mongo DB ?

**Comment by lussandro** [comment]
Eu ia abrir uma nova issue, mas eu fiz o teste, quando conecta a instância elas aparecem no mongo. Enquanto não esta conectada somem. A variavel DEL_INSTANCE esta setada como false no .nev>
![image](https://github.com/EvolutionAPI/evolution-api/assets/12955317/00f1a142-e1fe-4c5c-bf79-5e4ff3231689)

**Comment by michaelvips** [comment]
O erro esta na sintaxe desse codigo quando se usa = e : em env você deve usar entre crases "false"

**Comment by lussandro** [comment]
> @lussandro O erro pode estar na sintaxe desse código quando se usa = e : em env você deve usar entre aspas duplas "false"
> 
> Todas estão usando = ou algumas tem : ?

@michaelvips todos estão usando =  e sem aspas
![image](https://github.com/EvolutionAPI/evolution-api/assets/12955317/60a7cb82-7c5e-4e29-be0c-21c6a2d8f4ae)

**Comment by stgcompany** [comment]
Estou tendo o mesmo problema, tive que reiniciar o meu servidor por um problema e acabou que todas as instâncias que não estavam conectadas, foram deletadas.

**Comment by michaelvips** [comment]
> Estou tendo o mesmo problema, tive que reiniciar o meu servidor por um problema e acabou que todas as instâncias que não estavam conectadas, foram deletadas.

E sobre os volumes ? Voce tem criado os volumes / instances e / store?

**Comment by stgcompany** [comment]
> E sobre os volumes ? Voce tem criado os volumes /evolution/store e /evolution/instances neles que ficam guardadas essas informações de instancias

Eu uso com o PM2 e MongoDB para armazenar as instâncias, e quando reinicia não tá mantendo as instâncias com status 
 `closed`.

**Comment by michaelvips** [comment]
@stgcompany Veja o YML com mongo no manual https://doc.evolution-api.com/docs/docker-installation

![image](https://github.com/EvolutionAPI/evolution-api/assets/21130174/bbbea489-df82-46e4-b80d-6ccefe21343d)

**Comment by stgcompany** [comment]
@michaelvips Amigo você não entendeu, eu não estou usando docker, estou usando pelo gerenciador do PM2

**Comment by michaelvips** [comment]
@stgcompany e quanto a variável DATABASE_SAVE_DATA_INSTANCE=true ? tem ?

**Comment by michaelvips** [comment]
@DavidsonGomes Help us ? Como manter os dados das instancias após reiniciar um servidor / container. usando ou não mongo db.

**Comment by DavidsonGomes** [comment]
Sobre remover as instancias nao conectadas, é um comportamento da api mesmo, se nao conectada ela fica somente em cache, com isso apos reiniciar se perde!

**Comment by michaelvips** [comment]
@COMPAGNONIS creio que com o ultimo comentário do Davidson você pode encerrar essa issue.
