### ISSUE TITLE
[PT][BUG] Erro ao linkar mensagens respondidas

### ISSUE THREAD

**Issue by tiagao86** [EvolutionAPI/evolution-api#430]
#### Descrição:
Ao responder uma mensagem recebida, a resposta acaba sendo linkada a outra mensagem que não a relacionada originalmente

#### Passos para Reproduzir:
1. Receber algumas mensagens em sequencia
2. Responder uma mensagem que não seja a primeira recebida
3. O destinatario recebera a mensage linkada incorretamente

#### Comportamento Esperado:
Notar na imagem que foi respondido em cima da mensagem "linha 2", porem o destinatario recebeu a resposta em cima da mensagem "boa tarde"

#### Capturas de Tela/Vídeos:
![image](https://github.com/EvolutionAPI/evolution-api/assets/46145909/7314af59-e4fc-4ff7-bfbf-9ec15f2ec539)

#### Ambiente:
- **Servidor:** Ubuntu 20.04
- **Versão da API:** 1.6.1
- **Outras Especificações de Hardware/Software:** Chatwoot 3.5.2

**Comment by muriloorama** [comment]
vc esta usando o Mondo DB como banco de dados ?

**Comment by DavidsonGomes** [comment]
Voce precisa usar o mongodb e habilitar para salvar as mensagens, caso contrario nao vai funcionar

**Comment by tiagao86** [comment]
Realmente era isso! Muito obrigado!

**Comment by dilneiss** [comment]
@tiagao86 como você resolveu? pode me descrever os passos aqui? principalmente a parte que você configurou o mongo.. aqui quando instalei o mongo e habilitei assim
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_CHATS=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_MESSAGE_UPDATE=false
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_ENABLED=true

ao tentar criar instância tá dando esse erro:
![image](https://github.com/EvolutionAPI/evolution-api/assets/4564667/5e436a4a-45d3-4a52-99fd-8aea21453470)

**Comment by tiagao86** [comment]
> @tiagao86 como você resolveu? pode me descrever os passos aqui? principalmente a parte que você configurou o mongo.. aqui quando instalei o mongo e habilitei assim - DATABASE_SAVE_DATA_INSTANCE=true - DATABASE_SAVE_DATA_CHATS=true - DATABASE_SAVE_DATA_CONTACTS=true - DATABASE_SAVE_MESSAGE_UPDATE=false - DATABASE_SAVE_DATA_NEW_MESSAGE=true - DATABASE_ENABLED=true
> 
> ao tentar criar instância tá dando esse erro: ![image](https://private-user-images.githubusercontent.com/4564667/306723916-5e436a4a-45d3-4a52-99fd-8aea21453470.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NjE1ODIsIm5iZiI6MTcwODU2MTI4MiwicGF0aCI6Ii80NTY0NjY3LzMwNjcyMzkxNi01ZTQzNmE0YS00NWQzLTRhNTItOTlmZC04YWVhMjE0NTM0NzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMDAyMTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzg0YzZmOWVlNWVhZGJjMDRiMWU5YzUwOTQ2NjI1OTIzMzc1YjY3ZjA2ZDM2ZDgzMWZkZjgwYWM0ZWE5MmViYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.w54BmhfAqgAf-b3qpiswPmrgnD1Ior35FwWDbLi_uiM)

Esse é o modelo do docker-compose.yaml que adaptei pro meu cenario (estou usando nginx como proxy reverso)

version: "3.8"

x-variables:
  &variables
    # Server configs
    #SERVER_TYPE: "https"
    SERVER_URL: https://suaurl.com.br
    CONFIG_SESSION_PHONE_CLIENT: "GVC Telecom"
    # ApiKey Config for authentication High Encryption AES 256 from https://acte.ltd/utils/randomkeygen
    AUTHENTICATION_TYPE: "apikey"
    AUTHENTICATION_API_KEY: "XXXXXXXXXXXXXXXXXXXXXXXXX"
    # Database 
    DATABASE_ENABLED: "true" 
    DATABASE_CONNECTION_URI: "mongodb://root:SENHAMONGO@mongodb:27017/?authSource=admin&readPreference=primary&ssl=false&directConnection=true"
    DATABASE_CONNECTION_DB_PREFIX_NAME: "evdocker"
    # Choose the data you want to save in the application's database or store
    DATABASE_SAVE_DATA_INSTANCE: "true"
    DATABASE_SAVE_DATA_NEW_MESSAGE: "true"
    DATABASE_SAVE_MESSAGE_UPDATE: "true"
    DATABASE_SAVE_DATA_CONTACTS: "true"
    DATABASE_SAVE_DATA_CHATS: "true"
    # RabbitMQ configs
    RABBITMQ_ENABLED: "false"
    RABBITMQ_URI: "amqp://guest:guest@rabbitmq:5672"
    # Typebot
    TYPEBOT_API_VERSION: "latest" # old | latest
    TYPEBOT_KEEP_OPEN: "false"

services:
  evolution:
    image: atendai/evolution-api:latest
    command: ["node", "./dist/src/main.js"]
    environment:
      <<: *variables
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    ports:
    - 8080:8080
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1

  mongodb:
    image: mongo:latest
    # Is not recommended to expose ports unless necessary, use docker internal dns name of the container for connection
    # ports:
    #   - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "SENHAMONGO"
      PUID: "1000"
      PGID: "1000"
    volumes:
      - mongodb_data:/data/db
      - mongodb_configdb:/data/configdb
    networks:
      - internal
  
volumes:
  # Obligatory volumes for mongodb
  mongodb_data:
  mongodb_configdb:
  # Optional volumes for EvolutionAPI
  evolution_instances:
  evolution_store:

networks:
  internal:

**Comment by tiagao86** [comment]
@dilneiss 

> @tiagao86 como você resolveu? pode me descrever os passos aqui? principalmente a parte que você configurou o mongo.. aqui quando instalei o mongo e habilitei assim - DATABASE_SAVE_DATA_INSTANCE=true - DATABASE_SAVE_DATA_CHATS=true - DATABASE_SAVE_DATA_CONTACTS=true - DATABASE_SAVE_MESSAGE_UPDATE=false - DATABASE_SAVE_DATA_NEW_MESSAGE=true - DATABASE_ENABLED=true
> 
> ao tentar criar instância tá dando esse erro: ![image](https://private-user-images.githubusercontent.com/4564667/306723916-5e436a4a-45d3-4a52-99fd-8aea21453470.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NjE1ODIsIm5iZiI6MTcwODU2MTI4MiwicGF0aCI6Ii80NTY0NjY3LzMwNjcyMzkxNi01ZTQzNmE0YS00NWQzLTRhNTItOTlmZC04YWVhMjE0NTM0NzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMDAyMTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzg0YzZmOWVlNWVhZGJjMDRiMWU5YzUwOTQ2NjI1OTIzMzc1YjY3ZjA2ZDM2ZDgzMWZkZjgwYWM0ZWE5MmViYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.w54BmhfAqgAf-b3qpiswPmrgnD1Ior35FwWDbLi_uiM)

Segue docker-compose.yaml anexo. Estou usando nginx como proxy reverso
[docker-compose[1].yaml.txt](https://github.com/EvolutionAPI/evolution-api/files/14366575/docker-compose.1.yaml.txt)

**Comment by dilneiss** [comment]
obrigado @tiagao86 vou testar aqui, valeu!
