### ISSUE TITLE
[PT][FEAT] Endpoint de Bloqueio de contato

### ISSUE THREAD

**Issue by NeritonDias** [EvolutionAPI/evolution-api#431]
#### Descrição Detalhada:
Endpoint de bloqueio contatos e consulta de contatos bloqueados

#### Racional:
Muitas pessoas hoje usam a API para receber mensagens, algumas das vezes aparecem pessoas indesejadas ou que ficam fazendo SPAM no número atrelado a API e com isso a falta de um endpoint de bloqueio de contato faz falta para sanar essa questão.

#### Exemplos de Uso:
Usando em uma plataforma de atendimento como o chatwoot um lead entra em contato e é atendido, mas o mesmo começa a mandar pornografia ou mesmo enviando mensagens indesejadas, hoje só conseguimos bloquear esse número através do WhatsApp no celular, com um endpoint de bloqueio de contato é possível criar uma automação que quando o atendente ativar a automação o número é bloqueado sem a necessidade de bloquear pelo celular.

**Comment by lindenbergp** [comment]
Uma ótima opção e quem vai ser bastante utilizada. o que nao falta e spam.

**Comment by RuanMD** [comment]
realmente faz sentido esse endpoint

**Comment by dilneiss** [comment]
top, vou usar muito se tiver isso

**Comment by oriondesign2015** [comment]
#433
