### ISSUE TITLE
[PT][FEAT] Apagar Conversas/chat

### ISSUE THREAD

**Issue by lindenbergp** [EvolutionAPI/evolution-api#432]
#### Descrição Detalhada:
Implementação da opção de deletar conversas pelo id da conversa/chat.

#### Racional:
As vezes recebo muitas propagandas indesejadas e preciso ficar apagando uma a uma manualmente todas essas conversas.

#### Exemplos de Uso:
Ajudaria a limpar essas conversas indesejadas e tambem conversas que nao tem mais necessidade de ficarem salvas. pois com essa opção na API posso automatizar esse processo. Creio que muitas pessoas tenha essa necessidade.

![exemplo](https://github.com/EvolutionAPI/evolution-api/assets/24882737/271a9899-bbbc-452d-805d-34bfd024ed66)

**Comment by DavidsonGomes** [comment]
Não essa função na Baileys, caso encontre me manda aqui que faremos a implementação!

**Comment by lindenbergp** [comment]
Como nao sou desenvolverdor nao sei se seria isso aqui:

const lastMsgInChat = await getLastMessageInChat('123456@s.whatsapp.net') // implement this on your end
await sock.chatModify({
  delete: true,
  lastMessages: [{ key: lastMsgInChat.key, messageTimestamp: lastMsgInChat.messageTimestamp }]
},
'123456@s.whatsapp.net')

![image](https://github.com/EvolutionAPI/evolution-api/assets/24882737/50b50018-d106-4777-b5be-11c34eb50074)

Achei que era isso.

**Comment by R0DRIG0O** [comment]
a função foi implementada? também gostaria, estou utilizando um chatbot com inteligência artificial e com o passar dos dias o smartphone vai enchendo de mensagens, colocaria uma automação para apagar a cada semana ou mês todas as conversas...
