### ISSUE TITLE
[PT][BUG]endpoint chat/getBase64FromMediaMessage/ não funciona

### ISSUE THREAD

**Issue by DRIMOL** [EvolutionAPI/evolution-api#435]
#### Descrição:
endpoint chat/getBase64FromMediaMessage/ não funciona para recuperar midias de mensagens recuperadas do webhook messages.set onde chegam as mensagens anteriores ao conectar o qrcode.

#### Passos para Reproduzir:

1 - escaneie o qr code de um whatsapp na evolution.
2 - pegue o id de uma mensagem de midia
3 -tente recuperar o base64 com o endpoint chat/getBase64FromMediaMessage/

#### Comportamento Esperado:
recuperar o base64 da midia

#### Comportamento Atual:
{
    "status": 400,
    "error": "Bad Request",
    "response": {
        "message": [
            "Message not found"
        ]
    }
}

#### Ambiente:
- **Versão da API:**  1.6.0

**Comment by DavidsonGomes** [comment]
Não funciona, para funcionar precisa existir a mensagem no mongodb. o messages.set por padrão não salva no mongo ou store files
