### ISSUE TITLE
messageType diferentes

### ISSUE THREAD

**Issue by wilsonjuniorbarros** [EvolutionAPI/evolution-api#436]
messageType diferentes

Os números diferentes iniciarem uma conversa e a API responder com messageType diferentes, veja o exemplo abaixo:

Telefone 1:
"message": {
      "conversation": "oi",
      "messageContextInfo": {
        "deviceListMetadata": {
          "recipientKeyHash": "",
          "recipientTimestamp": ""
        },
        "deviceListMetadataVersion": 2
      }
    },
    "messageType": "conversation",

Telefone 2:
 "message": {
      "extendedTextMessage": {
        "text": "Ola",
        "previewType": "NONE",
        "contextInfo": {},
        "inviteLinkGroupTypeV2": "DEFAULT"
      },
      "messageContextInfo": {
        "deviceListMetadata": {
          "senderKeyHash": "",
          "senderTimestamp": "",
          "recipientKeyHash": "",
          "recipientTimestamp": ""
        },
        "deviceListMetadataVersion": 2
      }
    },
    "messageType": "extendedTextMessage",

Ambos iniciaram uma conversa e a API responde com messageType diferentes!

O telefone 1 iniciou a conversa e a API responde com "messageType": "conversation"
O telefone 2 iniciou a conversa e a API responde com "messageType": "extendedTextMessage"

A estrutura destas messageType são diferentes: 

O que é digitado pelo usuário do Telefone 1 vem na propriedade "conversation": "Oi"
Já o que foi digitado pelo usuário do Telefone 2, vem com a propriedade "Text":"Ola"

**Comment by DavidsonGomes** [comment]
Sim, isso é correto, é o retorno que a Baileys entrega pra gente

**Comment by iaurg** [comment]
> [@DavidsonGomes](https://github.com/DavidsonGomes) Existe algum lugar onde podemos ver todos os possíveis exemplos de "messageType" que existem?

Creio que se for mapeado com a Baileys serão esses: https://baileys.whiskeysockets.io/classes/proto.Message-1.html

**Comment by exvecchio-glitch** [comment]
@elielsan10 https://github.com/WhiskeySockets/Baileys/blob/9a8f19461cda975286597d60faf82451b8fd5d3d/src/Types/Message.ts#L38
