### ISSUE TITLE
[PT][BUG] Não consigo ativar o RabbitMQ - ERRO: Cannot read properties of null (reading 'assertExchange') 

### ISSUE THREAD

**Issue by davidalpa** [EvolutionAPI/evolution-api#437]
#### Descrição:
Não consigo ativar o RabbitMQ, sempre que eu salvo ele dá um erro "Cannot read properties of null (reading 'assertExchange')"
Vi que tem um outro tópico que foi recomendado criar manualmente que resolve. Mas não achei em nenhum lugar na documentação de como que eu crio manualmente no RabbitMQ. Qual é o nome da fila que deve ter pra ele identificar? No código de instalação não conta nada sobre isso também.

#### Passos para Reproduzir:
1. Sempre que eu tento salvar a opção RabbitMQ ele dá o erro

#### Comportamento Esperado:
Conseguir fazer o RabbitMQ funcionar, pois quero jogar para o N8N com o RabbitMQ gerenciando a fila

#### Comportamento Atual:
Dá erro e não funciona o RabbitMQ

#### Capturas de Tela/Vídeos:
![Captura de tela 2024-02-22 233519](https://github.com/EvolutionAPI/evolution-api/assets/146036091/a1fd432a-bfa5-45be-bfbb-d35602efdfed)

#### Ambiente:
- **Servidor: Ubuntu 20.04
- **Versão da API: 1.5.4
- **Outras Especificações de Hardware/Software: Host Hetzner, 4 VCPU (dedicada), 16 GB RAM, 160 GB DISK LOCAL, 0/20TB TRAFFIC OUT 

#### Envio de Logs:
[Evolution API]  v1.5.4  1   -  Thu Feb 22 2024 23:40:04     VERBOSE   [RabbitmqRouter]  [object]   
[Evolution API]  v1.5.4  1   -  Thu Feb 22 2024 23:40:04     VERBOSE   [RabbitmqController]  [string]  requested createRabbitmq from Daniel instance 
[Evolution API]  v1.5.4  1   -  Thu Feb 22 2024 23:40:04     VERBOSE   [RabbitmqController]  [string]  rabbitmq events empty 
[Evolution API]  v1.5.4  1   -  Thu Feb 22 2024 23:40:04     VERBOSE   [RabbitmqService]  [string]  create rabbitmq: Daniel 
[Evolution API]  v1.5.4  1   -  Thu Feb 22 2024 23:40:04     VERBOSE   [WAStartupService]  [string]  Setting rabbitmq 
[Evolution API]  v1.5.4  1   -  Thu Feb 22 2024 23:40:04     VERBOSE   [WAStartupService]  [string]  Getting instance name 
[Evolution API]  v1.5.4  1   -  Thu Feb 22 2024 23:40:04     VERBOSE   [RabbitmqRepository]  [string]  creating rabbitmq 
[Evolution API]  v1.5.4  1   -  Thu Feb 22 2024 23:40:04     VERBOSE   [RabbitmqRepository]  [string]  saving rabbitmq to db 
[Evolution API]  v1.5.4  1   -  Thu Feb 22 2024 23:40:04     VERBOSE   [RabbitmqRepository]  [string]  rabbitmq saved to db: 1 rabbitmq 
[Evolution API]  v1.5.4  1   -  Thu Feb 22 2024 23:40:04     VERBOSE   [WAStartupService]  [string]  Rabbitmq events: APPLICATION_STARTUP,QRCODE_UPDATED,MESSAGES_SET,MESSAGES_UPSERT,MESSAGES_UPDATE,MESSAGES_DELETE,SEND_MESSAGE,CONTACTS_SET,CONTACTS_UPSERT,CONTACTS_UPDATE,PRESENCE_UPDATE,CHATS_SET,CHATS_UPSERT,CHATS_UPDATE,CHATS_DELETE,GROUPS_UPSERT,GROUP_UPDATE,GROUP_PARTICIPANTS_UPDATE,CONNECTION_UPDATE,CALL,NEW_JWT_TOKEN,TYPEBOT_START,TYPEBOT_CHANGE_STATUS,CHAMA_AI_ACTION 
[Evolution API]  v1.5.4  1   -  Thu Feb 22 2024 23:40:04     VERBOSE   [WAStartupService]  [string]  Rabbitmq set 

#### Notas Adicionais:
Gostaria de entender melhor o que eu preciso criar no RabbitMQ pra configurar a fila correta que vai chegar a mensagem da API.

**Comment by matheusmaiberg** [comment]
Manda um print da env do Rabbitmq

**Comment by davidalpa** [comment]
Essa aqui? 

![image](https://github.com/EvolutionAPI/evolution-api/assets/146036091/bdd031ca-cdab-4ff7-a880-94cc13cbaafd)

**Comment by matheusmaiberg** [comment]
Tenta isso: 
Colocar depois do @ assim dessa forma https://filas.zapi.com.br:15672 se nao der certo, coloca o ip

**Comment by costaeder** [comment]
Resolvi a questão colocando / no final da URL, uma vez que o / é o VHOST padrão do rabbit.

Lembrar da env:

  RABBITMQ_DEFAULT_VHOST: "/"

**Comment by davidalpa** [comment]
Que estranho pessoal, eu tentei aqui tudo o que falaram e ainda nada...

- Troquei o VHOST para "/" ou para apenas / . 
- Criei um Virtual Host no RabbitMQ com o nome / 
- Criei uma fila com o nome da instancia, 
- Criei uma fila com o nome /
- Criei uma fila com o nome da instancia (com maiusculo e sem maiusculo)
- Testei colocar o "https://" na URI
- Testei colocar o "http://" na URI
- Testei colocar a "/" no final da URI (com https:// e só o IP)
- Testei apontar direto pro IP do host (verifique se a porta estava liberada no firewall do host e ela está)

Poderiam me confirmar qual é o nome da fila e virtual host rabbitMQ padrão para a Evolution API? 
O Davidson havia falado em outro tópico pra criar manualmente que iria resolver, mas eu ainda não sei o nome que devo criar manualmente no RabbitMQ ou onde devo criar manualmente.

**Comment by matheusmaiberg** [comment]
Usa o ip meu amigo, resolve 100% e é ate melhor pra nao ter que passar por DNS ou seja, menor latencia

**Comment by davidalpa** [comment]
Eu ainda não consegui aqui. Tentei por IP e nada.

**Comment by yagoylc** [comment]
Tenta usar a porta 5672 em vez da 15672, o VHOST tem que estar informado tbm, logo após a porta. Qualquer coisa, me chama no discord que a gente disseca esse problema seu. Tive um parecido e apanhei até entender.
