### ISSUE TITLE
[PT][FEAT] Ignorar grupos de forma mais inteligente

### ISSUE THREAD

**Issue by dilneiss** [EvolutionAPI/evolution-api#438]
#### Descrição Detalhada:
Seria interessante a possibilidade de ignorar os grupos de uma forma mais inteligente.
Por exemplo: Em meu bot, eu crio um grupo de controle, onde nele eu posso mandar comandos e o robo responder naquele grupo, podendo ser qualquer usuário nele ou apenas um específico (Isso eu controlo do meu lado)
Mas quando eu ativo a opção de receber callback de atualização de mensagens, eu recebo notificações também dos grupos, mas eu não quero isso, eu não quero receber notificação de outros grupos.
Então meu caso de uso aqui, seria então uma das sugestões:
Ignorar todas as mensagens de grupos. (já tem hoje)
Ignorar todas as mensagens de grupo, exceto dos grupos: a, b, c (Com isso, eu poderia ter um endpoint para cadastrar os grupos que eu quero receber alteração)
Ignorar todas as mensagens dos seguintes grupos: x, y, z (Com isso eu poderia ter um endpoint para quais os grupos eu quero que ignore)

A idéia principal aqui, é ter menos callback desnecessário sendo requisitado, resultando assim menos tráfego e melhor optimização da plataforma na hora do processamento dos itens

**Comment by judsonjuniorr** [comment]
No meu ponto de vista não acho que essa função seja de responsabilidade da evo, ela precisa fazer a funcionalidade genérica de conexões e webhooks do Whatsapp.
Esse tipo de tratativa precisa ser feito do lado do usuario com a customização de acordo com cada sistema, e a evo ser apenas uma integração com o whatsapp/typebot e chatwoot
