### ISSUE TITLE
[PT][BUG] Bloqueio/Banimento de instância ao enviar algumas mensagens

### ISSUE THREAD

**Issue by aloisoinac** [EvolutionAPI/evolution-api#439]
Estamos enfrentando banimento em nossos números após enviar algumas mensagens, e não é envio massivo de mensagem.

Em recentes testes enviamos mensagens as vezes para 10 contatos, em um chip que foi previamente incluso em grupos que interagiu e enviou mensagens.

No entanto, mesmo assim acaba sofrendo banimento mesmo com um uso tão reduzido de mensagens através da api. Gostaria de saber se há algum macete para evitar o bloqueio ou se enviar mensagens em paralelo mesmo que poucas pessoas pode causar o banimento.

Pra reproduzir basta enviar em paralelo algumas mensagens, no máximo 10 para contatos diferentes, isso provavelmente causará o banimento. então cuidado se for testar

Aos mantedores, caso eu esteja utilizando o canal errado para essa dificuldade me orientem para colocar no canal certo. Obrigado

**Comment by DavidsonGomes** [comment]
Pra esse caso nao tem oq possamos fazer, quando um numero é banido no seu ip ele ja fica com alerta e monitoramento pela meta, recomendo mudar o ip da maquina onde esta rodando a api de whatsapp

**Comment by aloisoinac** [comment]
Entendido, mas será que o banimento não ocorre também pelo domínio?

**Comment by lussandro** [comment]
> Entendido, mas será que o banimento não ocorre também pelo domínio?

O Banimento ocorre por N motivos, mas eis alguns deles: envio em massa de mensagens, envio de mensagens em um intervalo muito pequeno, envio para muitos contatos que não estão na agenda, denuncias de spam, reposta e envio de mensagens em tempo igual (ex: varias mensagens com intervalos iguais), numero novo ativado a pouco e enviando mesngens e por ai vai

**Comment by TiagoGouvea** [comment]
Existe a conta do whatsapp business e a "normal", sabem me dizer se a business é mais "rente", mais fácil de receber um bloqueio?

**Comment by TiagoGouvea** [comment]
Outra pergunta. Quando chega a mudança de status da conexão, quando é banido, sabem me dizer qual o status ou detalhes que posso conferir para saber que foi um bloqueio a razão?

**Comment by hueltonsantos** [comment]
Opa pessoal, a versão da evo 2.2.0 está tendo bloqueio mesmo, atualizei para a versão e com 2 dias depois foi bloqueado, e não fazemos disparo de mensagens e a quantidade  trocada no whatsaap é bem pequena, e aconteceu em dois casos esses bloqueios. Sem nem uma ter quantidade de mesagens exorbitantes trocadas, isso foi do nada em dois casos usando a mesma versão.

**Comment by TiagoGouvea** [comment]
Isso não pode ter a ver com a versão do baileys lá no .env?
