### ISSUE TITLE
O número não chega com a opção de compartilhar contato

### ISSUE THREAD

**Issue by mibarra22** [EvolutionAPI/evolution-api#44]
Olá a todos, como vão, quero relatar isso, acontece que testei com a v1.4.8 e enviei mensagens de um celular android e ios da apple, quando envio do meu celular **android**, o nome e número chega corretamente, mas quando mando do meu celular **apple** não chega o número, só o nome. Também quando mando do whatsapp web também não chega o número, só o nome.
![reportar_compartir](https://github.com/EvolutionAPI/evolution-api/assets/54458108/a965dae9-c0ea-45ba-8234-2c63f027844e)

**Comment by DavidsonGomes** [comment]
Vamos analisar para corrigir, obrigado!
