### ISSUE TITLE
[PT][BUG] Audio gravado não toca 1.5x, 2x no celular

### ISSUE THREAD

**Issue by dilneiss** [EvolutionAPI/evolution-api#440]
#### Descrição:
fiz um teste aqui de enviar audio gravado e foi, mas me deparei com a seguinte situação.
quando escuta o audio enviado no whatsapp web, ele toca 1.5x, 2x normal
mas se for escutar no aparelho celular, ele nunca toca em velocidade diferente de 1x, o que será? bug no whatsapp sei que não é pq já recebi audio de outras pessoas e está tocando mais rápido normal.
sabem o que pode ser?
estou enviando assim: {
	"number": "REMOTEJID",
	"options": {
		"delay": 130000,
		"presence": "recording",
		"encoding": true
	},
	"audioMessage": {
		"audio": "URL"
	}
}

#### Passos para Reproduzir:
1. Enviar um audio previamente gravado informando a url
2. Abrir o celular / whatsapp que enviou a mensagem
3. Tocar o audio
4. Tentar alterar para 1.5x, 2x

#### Comportamento Esperado:
Tocar o audio mais rápido conforme velocidade selecionada

#### Comportamento Atual:
Sempre toca o audio em 1x

**Comment by michaelvips** [comment]
Você usa WhatsApp business ou o normal ?

**Comment by michaelvips** [comment]
Fiz testes e simulações mude o parâmetro do json body para false "encoding": false

**Comment by dilneiss** [comment]
> Você usa WhatsApp business ou o normal ? A sua url informado o audio esta em qual formato .ogg ou .mp3 ?

formato OGG, testei os 2 zaps, a solução do @michaelvips resolveu, valeu mano, tocou certinho audio aqui.. pra que serve o encoding afinal?

**Comment by michaelvips** [comment]
`pra que serve o encoding` Creio que pra transformar o áudio para o formato OGG @dilneiss

**Comment by dilneiss** [comment]
> `pra que serve o encoding` Creio que pra transformar o áudio para o formato OGG @dilneiss

entendi, poxa, isso é um problema então.. temos que garantir o formato correto em ogg do nosso lado antes da ferramenta tentar disparar o audio, vou fazer mais algumas simulações aqui

**Comment by michaelvips** [comment]
Sim, se você enviar um áudio com url e arquivos for .MP3 com o  parametro encoding": false, o áudio vai ficar sem som.

**Comment by DavidsonGomes** [comment]
Estamos cientes do problema, ainda estamos estudando uma solução, para guiar quem queira ajudar

no processo de encoding do audio que é o problema, algumas tentativas que resolveram isso nao funcionava o audio no IOS, seguimos testando essa questao

**Comment by vinhali** [comment]
Quando eu desativo o encoding, e envio um áudio no formato .ogg. Ele funciona perfeitamente em Android e WhatsApp Web, mas não funciona em iOS. O áudio chega, mas não é possível clicar em reproduzir. Existe alguma solução?

**Comment by DavidsonGomes** [comment]
Resolvido na versão 2.0.0
