### ISSUE TITLE
[PT][BUG] `ignore_groups` sempre `true` ao criar instâncias

### ISSUE THREAD

**Issue by stgcompany** [EvolutionAPI/evolution-api#444]
#### Descrição:
Não sei se é somente comigo, mas ao criar uma nova instância ela sempre terá como configurado `ignore_groups` como `true` independente de qual opção você defina na criação, o mesmo ocorre se não declarar esta opção.

#### Passos para Reproduzir:
1. Crie uma instância com a opção `groups_ignore` como `false`;
2. Consulte as configurações desta instância e veja que estará como `true`.

#### Comportamento Esperado:
Que a opção fosse definida como esperado.

#### Comportamento Atual:
Sempre fica `true`.

#### Capturas de Tela/Vídeos:
`null`

#### Ambiente:
- **Servidor:** Ubuntu 20.04 LTS
- **Versão da API:** 1.6.1
- **Outras Especificações de Hardware/Software:** Rodando no PM2

#### Envio de Logs:
`null`

#### Notas Adicionais:
Por este bug, toda vez que crio uma instância, eu tenho que mandar um POST para alterar as `settings` da instância para assim conseguir definir como `false`.

**Comment by lindenbergp** [comment]
> ### Título: [PT][BUG] `ignore_groups` sempre `true` ao criar instâncias
> #### Descrição:
> Não sei se é somente comigo, mas ao criar uma nova instância ela sempre terá como configurado `ignore_groups` como `true` independente de qual opção você defina na criação, o mesmo ocorre se não declarar esta opção.
> 
> #### Passos para Reproduzir:
> 1. Crie uma instância com a opção `groups_ignore` como `false`;
> 2. Consulte as configurações desta instância e veja que estará como `true`.
> 
> #### Comportamento Esperado:
> Que a opção fosse definida como esperado.
> 
> #### Comportamento Atual:
> Sempre fica `true`.
> 
> #### Capturas de Tela/Vídeos:
> `null`
> 
> #### Ambiente:
> * **Servidor:** Ubuntu 20.04 LTS
> * **Versão da API:** 1.6.1
> * **Outras Especificações de Hardware/Software:** Rodando no PM2
> 
> #### Envio de Logs:
> `null`
> 
> #### Notas Adicionais:
> Por este bug, toda vez que crio uma instância, eu tenho que mandar um POST para alterar as `settings` da instância para assim conseguir definir como `false`.

Isso nao e um bug. Foi um pedido da comunidade. O padrão e true. Caso vá usar os grupos ai você ativa.

**Comment by stgcompany** [comment]
Mas você não acha que seria interessante já ter a opção na criação da instância com o Chatwoot? Porque desta forma toda vez que eu criar uma instância vou ter que ir no request pra redefinir as settings.

**Comment by stgcompany** [comment]
Ah ok, então vou tá alterando o código fonte aqui para mim, já que meus clientes fazem gerenciamento dos grupos na plataforma também.
