### ISSUE TITLE
[PT][BUG] API não reconhece números de México (+52)

### ISSUE THREAD

**Issue by dlc-letelier** [EvolutionAPI/evolution-api#447]
#### Descrição:
Ao tentar consultar o número ou fazer um envio no Chatwoot para um número do México, a API responde que o Whatsapp não existe, sendo que, se utilizado o aplicativo, o número sim tem Whatsapp.

#### Passos para Reproduzir:
1. Registrar um número com início +52
2. Tentar enviar uma mensagem

#### Comportamento Esperado:
A mensagem chegar no destinatário

#### Comportamento Atual:
A API disse que não tem Whatsapp registrado nesse número.

#### Capturas de Tela/Vídeos:
<img width="314" alt="image" src="https://github.com/EvolutionAPI/evolution-api/assets/60855725/f5b5278c-5272-499f-ab33-2cec39b1a8c9">

#### Ambiente:
- **Servidor:** Debian Bookworm
- **Versão da API:** [ex: 1.6.2]
- **Outras Especificações de Hardware/Software:** Docker compose

**Comment by dlc-letelier** [comment]
Segue um print do log
<img width="702" alt="image" src="https://github.com/EvolutionAPI/evolution-api/assets/60855725/c83b8421-7fb3-489d-951a-0921470255c2">

**Comment by KelvinBrit0** [comment]
![image](https://github.com/EvolutionAPI/evolution-api/assets/134308552/25c0563c-3592-4c8b-b66b-5ec1952b2738)

**Comment by KelvinBrit0** [comment]
Ele se comportou da seguinte maneira no meu.

API Versão 1.6.0

Resultou em 52**1**557494994 invés de 525574949947

![image](https://github.com/EvolutionAPI/evolution-api/assets/134308552/7926a9d6-68af-42a1-8c75-d8e6c3f9ea8d)

**Comment by KelvinBrit0** [comment]
Nos números de telefone do México (código do país: 52), sempre deve haver o número 1 logo após o código do país, inclusive nos números da Nextel. Fonte: https://faq.whatsapp.com/1294841057948784/?locale=pt_BR#:~:text=Nos%20n%C3%BAmeros%20de%20telefone%20do,inclusive%20nos%20n%C3%BAmeros%20da%20Nextel.

**Comment by dlc-letelier** [comment]
Muito raro... porque mesmo tentanso colocar um '1' , não vai.

<img width="691" alt="image" src="https://github.com/EvolutionAPI/evolution-api/assets/60855725/47925b75-f866-4921-b0e1-308d7cb0e1ef">

**Comment by dlc-letelier** [comment]
PS: Pois o jid fica sem o número. De repente ele ficou salvo na base de dados, e por isso a consulta está pegando o número antigo.
