### ISSUE TITLE
[PT][FEAT]

### ISSUE THREAD

**Issue by PedroReckelEL** [EvolutionAPI/evolution-api#448]
### Retorno do Número do WhatsApp pela API

Olá pessoal,

Tenho uma dúvida relacionada ao projeto, especificamente sobre a evolution-api. Caso não haja essa funcionalidade atualmente, estou disposto a abrir uma nova solicitação de recurso, seguindo os padrões estabelecidos.

Gostaria de saber se a evolution-api possui alguma rota que permita retornar o número de WhatsApp do usuário logado na sessão atual dentro do TypeBot. Pretendo utilizar essa informação da API para evitar que o usuário digite seu próprio número, prevenindo assim a inserção de informações incorretas ou que não pertencem a ele.

Agradeço antecipadamente pela ajuda.

**Comment by DavidsonGomes** [comment]
pode chamar a rota fetch instances passando o nome da sua instancia como exemplifica no postman

**Comment by PedroReckelEL** [comment]
Muito obrigado, Davidson.

Estou utilizando a rota que você me passou mas acho que ainda falta algum parâmetro para que eu consiga ter o retorno esperado.

Poderia dar uma olhada na minha requisição e me falar se estou esquecendo de algo?

![Captura de tela 2024-03-04 154315](https://github.com/EvolutionAPI/evolution-api/assets/155850969/83ebaddb-c839-46a0-a957-bf8ff38b6bdd)

![Captura de tela 2024-03-04 154509](https://github.com/EvolutionAPI/evolution-api/assets/155850969/0f9c47c4-8a87-4a6b-94ee-f54b3f018bf5)

Agradeço o apoio!
