### ISSUE TITLE
[PT][FEAT] Gatilho para pausar o fluxo do Typebot diretamente no chat.

### ISSUE THREAD

**Issue by alicelee4991** [EvolutionAPI/evolution-api#449]
#### Descrição Detalhada:
No ambito do atendimento em massa, seria simplificado apenas digitar um gatilho no próprio whatsapp e assim voltar ao atendimento manual! O gatilho de finalização que já existe, ele reinicia o fluxo! E muitas vezes apenas queremos pausar o fluxo e dar continuidade no atendimento manual.

#### Racional:
Facilitaria o atendimento semiautomatizado. Para pausarmos o fluxo, temos que procurar o numero do cliente, ir la na lista de sessões, procurar o número e então pausar o fluxo.

#### Exemplos de Uso:
Para pausarmos o fluxo, temos que procurar o numero do cliente, ir la na lista de sessões do manager, procurar o número e então pausar o fluxo.

**Comment by 456tgrytry** [comment]
Eu tambem estou pasando por isso
