### ISSUE TITLE
Problema com exibição de foto de perfil para números de telefone com 11 dígitos no endpoint fetchProfilePictureUrl

### ISSUE THREAD

**Issue by alexfrnco** [EvolutionAPI/evolution-api#45]
Atualmente, no endpoint /chat/fetchProfilePictureUrl/INSTANCIA, estamos enfrentando um problema relacionado à exibição de fotos de perfil de contatos que possuem números de telefone com 11 dígitos. Nesse cenário, a foto de perfil não está sendo exibida corretamente para aqueles números de WhatsApp que tem apenas 10 dígitos dependendo do DDD.

**Comment by lindenbergp** [comment]
Aqui na versão 1.4.8 da api esta trazendo certinho a foto de perfil.
![image](https://github.com/EvolutionAPI/evolution-api/assets/24882737/abccbe9e-cb9e-4b87-9235-9ca5f845ddd7)

**Comment by moskoweb** [comment]
Tenta pegar a url a partir do endpoint fetchProfile, lá tem validação de formato do WhatsApp e pega a partir do numero registrado no WhatsApp.

**Comment by alexfrnco** [comment]
> Aqui na versão 1.4.8 da api esta trazendo certinho a foto de perfil. ![image](https://user-images.githubusercontent.com/24882737/256831925-abccbe9e-cb9e-4b87-9235-9ca5f845ddd7.png)

A sim, aqui está dando erros apenas nos DDD acima do 30.

**Comment by alexfrnco** [comment]
> fetchProfile

Tudo bem, irei fazer isso! Obrigado valeu pela dica.

**Comment by alexfrnco** [comment]
> Tenta pegar a url a partir do endpoint fetchProfile, lá tem validação de formato do WhatsApp e pega a partir do numero registrado no WhatsApp.

Por esse endpoint pelo menos por aqui, continuou mesmo erro;
![image](https://github.com/EvolutionAPI/evolution-api/assets/111164863/554a9d4d-f6c5-4afc-a902-ac5a91c9fcaa)

Versao da API:
![image](https://github.com/EvolutionAPI/evolution-api/assets/111164863/f5931d85-8a96-43d3-a0d2-1b2552f11944)

**Comment by lindenbergp** [comment]
Sera se o contato tem foto de perfil?

**Comment by lindenbergp** [comment]
Verdade acabei de testar um com dd 21 que tem o nono digito e deu erro. Os que nao tem o nono digito ta buscando normal a foto.

**Comment by alexfrnco** [comment]
> Sera se o contato tem foto de perfil?

Sim é meu contato.
Sou do DDD 44, ai testei digitando os 11 digitos do numero, não pega, depois testei com 10 dígitos, vai normal.

**Comment by alexfrnco** [comment]
> Verdade acabei de testar um com dd 21 que tem o nono digito e deu erro. Os que nao tem o nono digito ta buscando normal a foto.

Show.

**Comment by alexfrnco** [comment]
> Verdade acabei de testar um com dd 21 que tem o nono digito e deu erro. Os que nao tem o nono digito ta buscando normal a foto.

Na verdade aqui ta alcontrário kkk

Mandando número com DDD abaixo do 30, todos pegam normal.

DDD acima do 30, preciso tirar o número 9 antes, para pegar.

**Comment by moskoweb** [comment]
Pelo que vi você esta passando o numero com espaço e caracteres, passa o numero cru, ou seja só 55309887766. A api limpa, mas o ideal é você já passar o numero certo.

**Comment by lindenbergp** [comment]
> > Verdade acabei de testar um com dd 21 que tem o nono digito e deu erro. Os que nao tem o nono digito ta buscando normal a foto.
> 
> Show.

Deve ser porque nao e obrigatório para números acima do dd 30. To vendo nos grupos que participo que todos os numero acima de 30 nao aparece o 9 digito.

**Comment by alexfrnco** [comment]
Fiz a seguinte alteração, utilizei primeiro o whatsappNumbers, e a resposta dele contendo o número correto eu informo no fetchProfilePictureUrl para buscar a imagem do perfil.

**Comment by moskoweb** [comment]
O fetchProfile já faz isso
