### ISSUE TITLE
[PT][BUG] Send list não funciona na versão 1.6.1

### ISSUE THREAD

**Issue by joaovitorp** [EvolutionAPI/evolution-api#452]
Send list não funciona na versão 1.6.1?

ele retorna 201, mas não envia a mensagem:

![image](https://github.com/EvolutionAPI/evolution-api/assets/19756834/55c05284-6737-4583-b832-903d596f19b1)

**Comment by judsonjuniorr** [comment]
@joaovitorp sendList foi implementado na versão 1.6.2/1.7.0 que está em homolog.

Se olhar no postman, vai ver que para a versão 1.6.1 não existe esse endpoint, pois ele é da nova versão

**Comment by Vagnerking** [comment]
é possível por imagem nos itens dessa lista?

**Comment by judsonjuniorr** [comment]
@Vagnerking somente textos.


@DavidsonGomes acredito que essa issue pode ser fechada
