### ISSUE TITLE
[PT][BUG] mensagem editada no whatsapp não é atualizada no chatwoot

### ISSUE THREAD

**Issue by mariolandossa** [EvolutionAPI/evolution-api#453]
#### Descrição:
Estamos testando o modo lista em um cliente e o mesmo reportou que um contato enviou ma mensagem que não chegou no Chatwoot ao apurar detectamos que a mensagem chegou mais foi editada pelo cliente e somente a original estava no Chatwoot a editada não foi atualizada na mensagem 
#### Passos para Reproduzir:
1. envie uma mensagem a uma instancia do Evolution 1.6.1 ou 1.6.2 e logo em seguida edite a mensagem 
2. a primeira mensagem será enviada a atualização não

#### Comportamento Esperado:
A mensagem deveria ser atualizada

#### Comportamento Atual:
A mensagem não é atualizada

#### Capturas de Tela/Vídeos:
Se possível, adicione capturas de tela ou vídeos que ilustrem o problema. Isso pode ser extremamente útil para entender o problema.

#### Ambiente:
- **Servidor:** Ubuntu 20.04
- **Versão da API:** 1.6.1
- **Outras Especificações de Hardware/Software:** [ex: CPU, GPU]

#### Envio de Logs:
Por favor, anexe os logs que possam estar relacionados ao problema. Se os logs contiverem informações sensíveis, considere enviá-los de forma privada para um dos mantenedores do projeto.

#### Notas Adicionais:
Inclua aqui qualquer outra informação que você ache que possa ser útil para entender ou resolver o bug.

**Comment by jaison-x** [comment]
Pelo que verifiquei um tempo atrás, o Chatwoot não possui endpoint para edição de mensagem. Tem apenas para mensagem vinculadas ao CSAT mas uma mensagem normal não encontrei nada.

**Comment by mariolandossa** [comment]
não é possível reenviar a mensagem atualizada, pois o usuário do ChatWoot fica  sem conseguir visualizar as editadas ?

**Comment by lindenbergp** [comment]
Sera se na hora que uma mensagem fosse editada, nao tinha como apagar a original e enviar a que atualizada?

**Comment by jaison-x** [comment]
Nesta PR #474 foi adicionada a funcionalidade de exibir edições de mensagens no Chatwoot. Por favor teste e nos envie um feedback. No caso respondemos a mensagem editada com o novo conteúdo editado já que não podemos alterar a mensagem original.

![image](https://github.com/EvolutionAPI/evolution-api/assets/5599142/af1e84ec-97f9-44b8-8b5f-bea3cb40f41e)
