### ISSUE TITLE
[PT][FEAT] Retornar número da instância do Evolution Manager;

### ISSUE THREAD

**Issue by PedroReckelEL** [EvolutionAPI/evolution-api#456]
Olá pessoal.

Gostaria de saber se tem alguma rota na API que retorna o número que está cadastrado na instância no Evolution Manager. Já consegui retornar o número do usuário atual na sessão do WhatsApp por meio do remoteJid, porém gostaria de salvar em uma variável do TypeBot o número da instância que está servindo de host para a aplicação.

Algum retorno parecido com esse e que eu pudesse salvar em uma variável dentro do TypeBot.

![image](https://github.com/EvolutionAPI/evolution-api/assets/155850969/12f49fa3-04c0-4004-a7b8-6afd6645f475)

**Comment by PedroReckelEL** [comment]
Obrigado Judson, titulo adicionado.

Até encontroei a rota Fetch Instances porém quando faço uma requisição nela dá um erro de não autorizado. Já conferi o meu apikey e está o mesmo da minha instância cadastrada no Evolution Manager consegue me dar uma ajuda e me falar o que pode estar faltando na minha requisição?

![image](https://github.com/EvolutionAPI/evolution-api/assets/155850969/3ffe36ff-127d-47d1-b985-72f23d3f8e0c)

![image](https://github.com/EvolutionAPI/evolution-api/assets/155850969/487d2fa6-26c8-413b-804b-b66460c2c0d4)

![image](https://github.com/EvolutionAPI/evolution-api/assets/155850969/fce92a65-d859-4ff1-9e74-d2f209c01e1b)

**Comment by judsonjuniorr** [comment]
Como você setou a variável no .env?
