### ISSUE TITLE
Fluxo não está pausando [PT][BUG]

### ISSUE THREAD

**Issue by ClaudiooOliveira** [EvolutionAPI/evolution-api#458]
Fluxo não está pausando [PT][BUG]

Estou utilizando Evo na versão 1.6.1 e Typebot 2.23.0

O fluxo não está pausando usando o POST por Webhook como funcionava antes...
Ele reinicia o fluxo automaticamente assim que chega ao fim, e não fica parado como ficava antes, e só retomava após o prazo de expiração definido dentro da Evolution,

Alguém ai pra dar uma força? Vários fluxos de clientes com esse problema.

**Comment by ClaudiooOliveira** [comment]
> > e não fica parado como ficava antes
> 
> Talvez seja a falta da definição da seguinte variável de âmbiente:
> 
> ![image](https://private-user-images.githubusercontent.com/143809393/310875952-6bf5794a-42ce-4b50-b791-f211c6a8e3d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTY5NTUsIm5iZiI6MTcwOTgxNjY1NSwicGF0aCI6Ii8xNDM4MDkzOTMvMzEwODc1OTUyLTZiZjU3OTRhLTQyY2UtNGI1MC1iNzkxLWYyMTFjNmE4ZTNkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxMzA0MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzY0ZWNmZGI0NTA4ZTc5ZmU0OTBjMjc2NDhkOWU3ZDdhNzBjZTY5YTQ5NjBhMTM2Y2YwNDc2ZjlmYTY3NThiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7BRSJqZUlJY8MHUib-u6tqHS6drKoWHqBbELyuUWG3E)
> 
> Ao definir como true a sessão continua em aberto ao final do fluxo, caso contrário ele fechará a sessão, voltando ao início do fluxo caso envio de nova mensagem pelo contato, iniciando assim uma nova sessão.

Isso dentro da Stack do Typebot ou Evolution? Olhei em ambas e não tenho isso lá não....e antes ele não encerrava o fluxo automaticamente.
Se eu chegasse no fim do fluxo e não adicionasse mais nada nele, ele simplesmente ficava "mudo" até dar o tempo de expiração definido dentro da Evolution.

**Comment by lindenbergp** [comment]
> > > e não fica parado como ficava antes
> > 
> > 
> > Talvez seja a falta da definição da seguinte variável de âmbiente:
> > ![image](https://private-user-images.githubusercontent.com/143809393/310875952-6bf5794a-42ce-4b50-b791-f211c6a8e3d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTY5NTUsIm5iZiI6MTcwOTgxNjY1NSwicGF0aCI6Ii8xNDM4MDkzOTMvMzEwODc1OTUyLTZiZjU3OTRhLTQyY2UtNGI1MC1iNzkxLWYyMTFjNmE4ZTNkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxMzA0MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzY0ZWNmZGI0NTA4ZTc5ZmU0OTBjMjc2NDhkOWU3ZDdhNzBjZTY5YTQ5NjBhMTM2Y2YwNDc2ZjlmYTY3NThiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7BRSJqZUlJY8MHUib-u6tqHS6drKoWHqBbELyuUWG3E)
> > Ao definir como true a sessão continua em aberto ao final do fluxo, caso contrário ele fechará a sessão, voltando ao início do fluxo caso envio de nova mensagem pelo contato, iniciando assim uma nova sessão.
> 
> Isso dentro da Stack do Typebot ou Evolution? Olhei em ambas e não tenho isso lá não....e antes ele não encerrava o fluxo automaticamente. Se eu chegasse no fim do fluxo e não adicionasse mais nada nele, ele simplesmente ficava "mudo" até dar o tempo de expiração definido dentro da Evolution.

No docker na stack da Evolution:
 # Versão da api do typebot old | latest
      - TYPEBOT_API_VERSION=latest
      - TYPEBOT_KEEP_OPEN=false #false ou true

**Comment by ClaudiooOliveira** [comment]
Fluxo continua sem pausar na 1.6.1.....voltei pra ela e testei novamente.

**Comment by cbalbinos** [comment]
@DavidsonGomes 

Por aqui tambem não está pausando como antes, estou usando Evolution 1.6.1 e Typebot 2.23.0

Observei que a sessão permanece pausada pelo tempo de expiração que foi definido

Isso tem relação com a variável TYPEBOT_KEEP_OPEN ? Não encontrei isso na documentação

![Pausado 13h55](https://github.com/EvolutionAPI/evolution-api/assets/91399681/e0ac3ae7-3947-4752-9826-8a1f2e753c5f)

**Comment by stelio-cristovao** [comment]
Aqui também estou com o mesmo problema, usando Evolution 1.6.1 e Typebot 2.23.0.

**Comment by Leandrogri** [comment]
Pessoal, estou com a Evolution 2.23, e o typebot  3.7.1, e não pausa o fluxo repete infinitamente,
usei bloco de pausa,
tentei pelo chatgpt criar um codigo, mas ele trava o fluxo e impede o fncionamento, mas não pausa...
