### ISSUE TITLE
Náo envia Imagen Chatwoot [PT][BUG]

### ISSUE THREAD

**Issue by nerdmail** [EvolutionAPI/evolution-api#463]

**Comment by BlueFolks** [comment]
Mesmo problema aqui, alguma solução?

**Comment by danilocampos** [comment]
mesmo problema

**Comment by humbernieto** [comment]
mismo problema v3.9.0

**Comment by sergionaf** [comment]
Ubuntu 24 
Chatwoot v3.13.0
![Screenshot 2024-09-27 at 10 59 21](https://github.com/user-attachments/assets/3c95feb9-4e6c-457d-b6c2-72f635caaeaa)

Evolution API 1.8.2
Não envia e não recebe mensagens com imagens em anexo, apenas o texto das mensagens é recebido / enviado

**Comment by facilrapido** [comment]
Alguem teve a solução disso ?

**Comment by fCaioRibeiro** [comment]
Mesmo erro aqui, alguém encontrou a solução???

**Comment by higorslawer** [comment]
Estava com mesmo problema, provavelmente é um problema com a configuração de SSL do "FRONTEND_URL". 

Como estou em ambiente de teste, coloquei url http, e "FORCE_SSL" como  "false" e funcionou de boa.

Se está em ambiente de produção, sugiro que verifique o certificado SSL no seu servidor.

**Comment by edsonfast** [comment]
Não consegui resolver, Qualquer mídia que envio pelo chatwoot não abre no WhatsApp nem direito no MinIO, já quando envio pelo WhatsApp abre novamente no chatwoot e MinIO, alguma dica?

**Comment by devtheu** [comment]
mesmo problema aqui mesmo enviando a imagem direto pra o minio chegando no whats fica tudo preto

**Comment by edsonfast** [comment]
Aqui de certo quando defini a variável FRONTEND_URL com meu domínio no ambiente do chatwoot.sidekiq

**Comment by kinhodevjr** [comment]
Aqui consegui resolver desse jeito também, alterei o dominio para o meu propio do chatwoot tanto no sidekiq e no chatwoot, usando o easypanel e voltou

**Comment by barretobruno411** [comment]
Pessoal, onde é que vocês estão fazendo essa configuração exatamente? isso é no chatwoot?

**Comment by kinhodevjr** [comment]
@barretobruno411 eu fiz pelo easypanel, ai entra no terminal e faz essa mudança
