### ISSUE TITLE
[PT][BUG] Não é possível modificar instancias já criadas

### ISSUE THREAD

**Issue by dlc-letelier** [EvolutionAPI/evolution-api#464]
#### Descrição: Após a atualização mais recente de hoje, não é mais possível mexer nas instâncias que já existem. É possível com as novas. Imagino que falta alguma regra para acrescentar essa opção nas instancias antigas.

<img width="827" alt="image" src="https://github.com/EvolutionAPI/evolution-api/assets/60855725/c12fe73f-5514-4179-931d-84365ba22293">

**Comment by lindenbergp** [comment]
#### Esse e referente a nova função que esta em teste na homolog.
- Sincronizar o historico completo
![image](https://github.com/EvolutionAPI/evolution-api/assets/24882737/d7c1f8a7-2362-4062-a9b6-83e40e8e3f3d)

Função de importar o histórico de mensagens pra o chatwoot. Ainda nao ta disponível no manager, quem estiver testando a homolog tem que usar as chamadas manualmente pelo postmam ate que seja lançada uma atualização pro manager.
