### ISSUE TITLE
[PT][BUG] Como descriptografar o arquivo de audio .ENC que recebemos por API?

### ISSUE THREAD

**Issue by davidalpa** [EvolutionAPI/evolution-api#466]
#### Descrição:
Estou tendo dificuldade pra entender como descritografa o arquivo de audio .ENC que recebemos por API. Estou tentando pelo N8N.

**Comment by judsonjuniorr** [comment]
@davidalpa tem um endpoint no postman que você obtém o base64 do arquivo, só enviar o ID da mensagem, da uma procurada la que vai encontrar

**Comment by davidalpa** [comment]
Muito obrigado, não tinha visto !

**Comment by davidalpa** [comment]
Olá, estou sofrendo com erro 400 devido ao mongoDB. Existe uma maneira de eu mandar a URL do arquivo, ao invés de mandar o ID do arquivo de audio?

Pois aqui no N8N havia conseguido fazer funcionar, mas as vezes dá esse erro 400. Tem alguma consiguração no mongo DB?

**Comment by TiagoGouvea** [comment]
@davidalpa @judsonjuniorr olhei no postman o POST mas não consegui reproduzir aqui.. podem me ajudar?

No postman diz:
```
{{baseUrl}}/chat/getBase64FromMediaMessage/{instanceName}
{
  "message": {
    "key": {}
  },
  "convertToMp4": "<boolean>"
} 
```

Mas não estou certo de como deve ir o valor em "key". Enviando `{"message":{"key":"021F8080D2C85E061F...BD"},"convertToMp4":true}` obtenho um `400 - Bad Request`.

Podem me ajudar por favor com esse parametro?

Obrigado!

**Comment by TiagoGouvea** [comment]
Consegui botar pra funcionar... dai pra quem precisar, segue o código:


```
async function audioToText(messageId) {
   const __dirname = path.resolve();
   const filePath = path.join(__dirname, 'audio_'+messageId+'.m4a');
   const msg = { id: messageId, description: messageId };
   const b64 = await getBase64FromMediaMessage(msg);
   saveBase64ToFile(b64.base64, filePath);
   return text;
}


export async function getBase64FromMediaMessage(
   message,
) {
    const url = `${evolutionBaseUrl}/chat/getBase64FromMediaMessage/${instanceName}`;
    const options = {
        method: 'POST',
        headers: {
            accept: 'application/json',
            'content-type': 'application/json',
            apiKey,
        },
        body: JSON.stringify({
            "message": {
                "key": message
            },
            convertToMp4: true,
        }),
    };

    try {
        const response = await fetch(url, options);
        if (response.ok) {
            const data = await response.json();
            return data; 
        } else {
            console.log(`Error with status code: ${response.status}`);
            return false;
        }
    } catch (error) {
        console.log('Error converting message', error);
        return false;
    }
}

export function saveBase64ToFile(base64Data, filePath) {
    const bufferData = Buffer.from(base64Data, 'base64');
    fs.writeFileSync(filePath, bufferData);
}
```

Se tiver alguma dúvida me pergunte ai!

**Comment by otaviolube** [comment]
E como pegar você está pegando o id da mensagem, @TiagoGouvea ?
