### ISSUE TITLE
[PT][BUG] Webhook não envia evento presence.update

### ISSUE THREAD

**Issue by HELIOPOTELICKI** [EvolutionAPI/evolution-api#467]
#### Descrição:
Implementei as rotas para ouvir os webhooks, mas não recebo nada do presence.update.

#### Comportamento Esperado:
Receber um hook de quando a pessoa está (online, digitando, gravando audio, etc)

#### Comportamento Atual:
Não recebo nada

#### Capturas de Tela/Vídeos:
![image](https://github.com/EvolutionAPI/evolution-api/assets/51384974/b496b086-c6d9-4fbf-8fd8-91f9c99639eb)

#### Ambiente:
- **Versão da API:**  1.6.1

**Comment by salomonamiga** [comment]
me pasa lo mismo, alguna sugerencia ?

**Comment by MarksonSolutions** [comment]
conseguiu alguma solução ?

**Comment by HELIOPOTELICKI** [comment]
Corrigido, funcionando perfeitamente!
