### ISSUE TITLE
[PT][FEAT]Editar Mensagem endpoint novo

### ISSUE THREAD

**Issue by marcelo386** [EvolutionAPI/evolution-api#468]
#### Descrição Detalhada:
Preciso desta opção para meu projeto MultAtendimento, está opção evita ter que ficar apagando uma mensagem e enviando a mensagem com a correção.

#### Racional:
Opção muita aguardada que chegou no WhatsApp, muito útil  pra evitar retrabalho de enviar todo texto novamente com pequenas modificações  

#### Impacto no Projeto:
Creio só iria complementar as funcionalidades já existentes

**Comment by jaison-x** [comment]
Nesta PR #474 foi adicionada a funcionalidade de exibir edições de mensagens no Chatwoot. Por favor teste e nos envie um feedback. Sobre alterar diretamente no Chatwoot, o próprio Chatwoot não permite edições de mensagem. Neste caso não tem muito o que a evolution em si fazer.

![image](https://github.com/EvolutionAPI/evolution-api/assets/5599142/af1e84ec-97f9-44b8-8b5f-bea3cb40f41e)
