### ISSUE TITLE
[PT][BUG] API Oficial só recebe mensagens mas não realiza envio

### ISSUE THREAD

**Issue by wigbertojr** [EvolutionAPI/evolution-api#469]
#### Descrição:
Fiz a instancia para rodar a API Oficial do WhatsApp mas ela somente recebe mensagens e não faz envio

#### Passos para Reproduzir:
{
    "number": "55319999999",
    "options": {
        "delay": 1200,
        "presence": "composing",
        "linkPreview": false
    },
    "textMessage": {
        "text": "Plain text me"
    }
}

Resposta:

{
    "status": 400,
    "error": "Bad Request",
    "response": {
        "message": [
            "TypeError: Cannot read properties of undefined (reading '0')"
        ]
    }
}

**Comment by guilhermejansen** [comment]
### Complementar o log do console **_(via docker)_**

'proxy-status': 'http_request_error; e_fb_configversion="AcLRyDRCbQTLN0s_nFwUTQYNRLGv778AFBpg0arpk9CXlBESiVMZlff4u_wa6w"; e_clientaddr="AcInfxRweoA1rLOvUqjIgh08wjFhyJw3mn7N4T232DU14vjOrv52Lqx4vSjvXA4Io8SczHSJOO6a1KXPHtPPNTa01dRt-5nh-AuMoZsk8BD1L9pB6A"; e_fb_vipport="AcIZUQqyVlIHA8LdZmBqZj-N8iI1t14mD836oJ7tCM9H0McdvEnXaNGGNjPo"; e_upip="AcK9NeH5oan-ltag_vy1pBq-lE7Axk6q3iq8nIVqEkdbGkdCcQkSKIx4l8Sd8ezsJhWfkcbyL4jxPd5vaBZDFb67pf7NmuQs"; e_fb_requestsequencenumber="AcKGlf9Xvo-oP4NKRISgH9AuhXbrADs_duc0oVJZTr3JPE_4nX1ZEfnBlcGz"; e_fb_hostheader="AcK880wrwZpAWc5vMl7sMjU-1k6mghLmR3IthG9A8FS8zmoY9z4t6izWfI7-WHRkDrDJVEz4FPfNahlv"; e_fb_vipaddr="AcKo5W13rpnhrIdX7gGzzkpANp8zAzVaD5HpIdQBrGV56djuUUtb-vTWKKlAhn7cwsptlWkHeflXILJ20vcC6vq7tSFv6ng"; e_fb_requesthandler="AcIj6fks6r99s0QNmyhTctT1Kiq7niex6K_MVensxj5QOokHfa3bsQStxn-cTXtrbMXRjzkAtaE"; e_fb_requesttime="AcItpxC3JN9mBWEMRXh6P7qBvj8bP918ov2niJwnjQdHA1Fex5c158Zb0H2SEGdBJ0HD0wYwYQ"; e_fb_builduser="AcJ75Tlny7hXbPNhbJHvHGI4Bpk_OjoqrfAVGsSdX1ERJ4_o_zsf2knE0ni1evsLZ_Q"; e_fb_httpversion="AcIQuyTyikjnwDF4FyUP0YqZuhUMyqz2-h95JT3dOEJVkk7BXBN8EaVujT7Z"; e_fb_binaryversion="AcLh-S2K5VfSE0zrStiQLCYOhBsu4xLYQo1CnPLu2WMdT5J_yikUnHnisii-o9mpqlVTMnytCkXVxkUORxFym5uXH_WWcsO3Dco"; e_proxy="AcIjcqp1w_K02H7D-5S2t9SOIGBh1k8CT_fYNAtHJKEU5lcopPpjcmEKxwa9kaqCNi5bDPCeSjvJ3ed3ajo", http_request_error; e_fb_configversion="AcLVqVy43hER2Hwi7-aHPwfewiVTzmousE34l4ThQkYW-B-zsnwc1qNH_MgLFg"; e_clientaddr="AcI6qbFHCxTjFWk22b8QYwlQlbs5NzZBMMHUWv0plZa4RoLDiHFObFDAuNpkcY0RQ1_AO3hPGDIOdw"; e_fb_vipport="AcLjaTy0oZHYidNa43tMygaICxSZDoF8b-JAqAxpDqqHPZ52icSCFd18sWjD"; e_upip="AcI6uF2Idc9CWMJ4VS_SdkNnWBt593H9Gh1F63NgU8YDVpeBeV2fcJAM1-7dKUuJmbd9zWNkJL04HqyuGEPl0FhS6-Ok1JA"; e_fb_requestsequencenumber="AcL2B_e0NpYRz5AIgOD2mfNlb9Jn3Y3efhuZVXxcBKX0xrQQQYPBcRL4Dw"; e_fb_hostheader="AcLNksf--AObfWu3XNUTvA_zQDBHjD9KbB-A6L-HY2StuzxrB6omx5P6Y0XkrZMJH1zQiOz50Vras2"; e_fb_vipaddr="AcIG2PzHndCU0-de53nmS3DdImsbrehP4RrRx4DBWLYlYWvLvilpvQhbjkljmj_59iURSQ"; e_fb_requesthandler="AcKNLOQH1P0HNxVOommbnphQN9JZH4Uk7K2P0Pryxv5EOtOba-Onegu1xjKR4NU16udFMW4kAY0"; e_fb_requesttime="AcL63w4mtHYiJP7zJk-xaCfAcr166ME66x3YuKlrmolOFNxrJXN0BeSfmJYTEt59tbDi8h7jsA"; e_fb_builduser="AcKYDr82m8afMsw9Qr7o1UCYPX75AiebZbap-l9sLfSR_8CtyYpwcfK_QExeaBkA4wI"; e_fb_httpversion="AcKJYvUauZNvKNJQ6TmdC6C-2gHmqxD5krN7LtMEoBsCZCepLx1IU0b30eK3"; e_fb_binaryversion="AcKNeKCjjNmvTP9WauOZCmbhY3TLrd0ZQ4lQaadq7eosHXnpkPw_ExdI1nF3UkBf8AQMfeTXNvDSQ01xTAkWyw0IIZ0WB9aotBU"; e_proxy="AcKBsjkeTY4a_KQe-vZmxKtmUGXxa8Hv4vCELwpv0z5HZjV8eapfcBgIqUr8Qr2cK3CRXqa_mr5Wjag8"',
      'x-fb-connection-quality': 'EXCELLENT; q=0.9, rtt=26, rtx=0, c=10, mss=1380, tbw=372, tp=-1, tpl=-1, uplat=42, ullat=0',
      'alt-svc': 'h3=":443"; ma=86400',
      connection: 'keep-alive',
      'content-length': '260'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      method: 'post',
      url: 'https://graph.facebook.com/v18.0/5521995721970/messages',
      data: '{"messaging_product":"whatsapp","recipient_type":"individual","type":"text","to":"5521979232690","text":{"body":"Plain text message, sent with the Evolution-API 🚀.","preview_url":false}}'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '191',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [TLSSocket],
      _header: 'POST /v18.0/5521995721970/messages HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, /\r\n' +
        'Content-Type: application/json\r\n' +
        'Authorization: Bearer TOKENOFUSCADO\r\n' +
        'User-Agent: axios/1.6.7\r\n' +
        'Content-Length: 191\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: graph.facebook.com\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/v18.0/5521995721970/messages',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'graph.facebook.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: { error: [Object] }
  }
} 
[Evolution API]  v1.7.0  1   -  Wed Mar 13 2024 14:56:55     ERROR   [WAStartupService]  [object]   
TypeError: Cannot read properties of undefined (reading '0')
    at BusinessStartupService.<anonymous> (/evolution/dist/src/whatsapp/services/whatsapp.business.service.js:692:130)
    at Generator.next (<anonymous>)
    at fulfilled (/evolution/dist/src/whatsapp/services/whatsapp.business.service.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by leandrosroc** [comment]
API oficial realiza envio, após primeiro contato de quem irá receber a mensagem, dentro de 24 horas, ou seja, envia apenas "respondendo", para iniciar conversa, é apenas com Modelo aprovado na Meta

**Comment by guilhermejansen** [comment]
@leandrosroc Exatamente por isso levantei a issue porque já estava aberta a janela de mensagens para o número que testei!

**Comment by guilhermejansen** [comment]
O problema está na construção da instância, já no manager isso foi implementado para orientação da criação da instancia Whatsapp Cloud API. 

{
    "instanceName": "{{instance}}",
    "token": "{{User-Access-Token}}",
    "qrcode": false,
    "number": "{{number}}", ### Aqui deveria estar orientado a colocar o Phone-Number-ID do Whatsapp Cloud API
    "integration": "WHATSAPP-BUSINESS"
}

E o **sendTemplate** não está funcionando corretamente! 

São só pontos de correção, mas está funcionando os envios, ainda não testei todos!

**Comment by LADR0NA** [comment]
estou com o mesmo problema versão 1.7.0, mensagem de escrevendo mas não chega a mensagem para a pessoa! 
erro no log 👇👇👇👇👇
[Evolution API]  v1.7.0  1   -  Sat Apr 13 2024 00:47:19     ERROR   [ChatwootService]  [object]   
{
  status: 400,
  error: 'Bad Request',
  message: [ 'Error: not-acceptable' ]

**Comment by DavidsonGomes** [comment]
Verifica o seu usuario do meta, aqui funciona certinho!

**Comment by tylaig** [comment]
Estou com o mesmo problema, tenho 2 clientes usando a api oficial na mesma instalação da Evo, em um funciona mas quando troco o nome da instancia para enviar mensagem apenas um deles funciona, configurei exatamente igual as duas, e no ChatWoot consigo receber e enviar mensagens
