### ISSUE TITLE
Erro ao buscar os contatos no endpoint /chat/findContacts/{{instance}}

### ISSUE THREAD

**Issue by lindenbergp** [EvolutionAPI/evolution-api#47]
No lugar do nome do contato ta trazendo o nome da instancia.

![image](https://github.com/EvolutionAPI/evolution-api/assets/24882737/a3d39330-d83f-4bab-a830-c1a5de6155ab)

**Comment by DRIMOL** [comment]
vim aqui reportar o mesmo erro, mas, agora esta retornando um objeto vazio quando utiliza o endpoint findcontacts ou findchats

**Comment by DavidsonGomes** [comment]
o campo owner nao é o nome do contato e sim o nome da instancia que esse contato pertence, o nome do contato é citado no campo pushName, se não tiver no objeto quer dizer que a Baileys não entregou o pushName para esse contato!

**Comment by lindenbergp** [comment]
Intendi. Deve ser os contatos que nao coloca nome.
