### ISSUE TITLE
[PT][BUG] Chatwoot totalmente configurado, recebe mensagens, mas não responde.

### ISSUE THREAD

**Issue by tiagoshark** [EvolutionAPI/evolution-api#471]
Chatwoot totalmente configurado, recebe mensagens, mas não responde.

Eu vejo as mensagens que a pessoa envia, porém, quando vou responder no chatwoot, a mensagem fica na cor vermelha com uma exclamação que diz 404 NOT FOUND.

Alguém sabe dizer como resolver?

![image](https://github.com/EvolutionAPI/evolution-api/assets/163490384/904a941f-4353-48d8-b2ea-99ebe1d6bd67)

**Comment by jaison-x** [comment]
@tiagoshark, provavelmente o webhook da sua caixa de entrada no chatwoot está configurado errado. Verfique se pode ser isso.

**Comment by michaelvips** [comment]
Atualmente, tenho notado que certas questões relacionadas à utilização da aplicação estão sendo postadas neste espaço. Gostaria de lembrar que o propósito desta seção é resolver bugs e erros específicos do código da aplicação.

Sugiro encaminhar dúvidas sobre a utilização da aplicação para a comunidade do Discord, onde os usuários podem interagir e ajudar uns aos outros de forma mais adequada. Aqui está o link para o nosso servidor no Discord: [Link para o Discord](https://discord.gg/U66zvhV49B).

Agradeço pela compreensão e colaboração.

**Comment by fagnerdireito** [comment]
Estou com o mesmo problema inclusive aperece digitando mas a mensagem não chega de forma nenhuma.
conforme a imagem abaixo, eu digito no chatwoot para enviar mas a mensagem naão chega no whatsapp.
ele chega a aparecer digitando, mas a mensagem em si não chega.

![image](https://github.com/EvolutionAPI/evolution-api/assets/2683236/6552f63a-71d9-4407-a98a-0933573997d1)

e no chatwoot as vezes fica azul como enviada mas as vezes fica vermelho como nao enviada:

![image](https://github.com/EvolutionAPI/evolution-api/assets/2683236/9beec589-3296-4cb9-9060-6f43b8992c91)
