### ISSUE TITLE
Erro ao alterar o comportamento de uma instancia para escutar grupos[PT][BUG]

### ISSUE THREAD

**Issue by edgardjnr** [EvolutionAPI/evolution-api#476]
#### Descrição:
{ "status": 400, "error": "Bad Request", "response": { "message": [ [ "instance requires property \"sync_full_history\"" ] ] } }

erro ocorreu apos update da versao 1.6.1

#### Passos para Reproduzir:
1. Abrir maneger
2. Tente alterar o status de comportamento da instancia (rejeitar ligação, escutar grupos e etc).
3. Erro ao salvar

#### Capturas de Tela/Vídeos:
<img width="1680" alt="Captura de Tela 2024-03-17 às 20 15 34" src="https://github.com/EvolutionAPI/evolution-api/assets/152132143/a25ce9de-7704-43ff-be2d-8942fef6e650">

#### Ambiente:
- **Servidor:** [ex: Ubuntu 20.04]
- **Versão da API:** [ex: 1.7.0]
- **Outras Especificações de Hardware/Software:** [ex: CPU, GPU]

#### Envio de Logs:
Por favor, anexe os logs que possam estar relacionados ao problema. Se os logs contiverem informações sensíveis, considere enviá-los de forma privada para um dos mantenedores do projeto.

#### Notas Adicionais:
Inclua aqui qualquer outra informação que você ache que possa ser útil para entender ou resolver o bug.

**Comment by dmasciel** [comment]
estou com o mesmo problema. voltei para a versão davidsongomes/evolution-api:v1.6.0 alterei as informações e depois voltei para a versão 1.7.0
