### ISSUE TITLE
[PT][BUG] Não está enviando variáveis capturadas do typebot

### ISSUE THREAD

**Issue by SobPat** [EvolutionAPI/evolution-api#484]
Ao tentar enviar uma mensagem com uma variável do Typebot a variável não é enviada

Descrição:
Quando capturo uma variável no Typebot que o usuário entrou ou o {{pushName}} ou {{remoteJid}} o valor não é repassado para o Whatsapp

Passos para Reproduzir:
1. Capturar uma variável, seja de entrada do usuário seja de remoteJid ou pushName
2. Enviar uma mensagem com essa variável no corpo

Comportamento Esperado:
Que a variável seja enviada junto ao corpo da mensagem

Comportamento Atual:
Não é enviado a variável

Capturas de Tela/Vídeos:
Fluxo typebot
![image](https://github.com/EvolutionAPI/evolution-api/assets/52140246/1b578bcb-d30e-442f-a401-dec943b5a777)
Conversa com o bot no WPP
![image](https://github.com/EvolutionAPI/evolution-api/assets/52140246/6bb3655c-ba7e-4c7a-aa78-7c62027b57bb)

Fiz um teste utilizando a API do typebot e esse é o retorno do endpoint. Não sei como era feito antigamente, já que funcionava normalmente
![image](https://github.com/EvolutionAPI/evolution-api/assets/52140246/feda17a5-00dd-4379-9deb-e47f70b3884b)

 Ambiente:
- Versão da API: 1.7.0

**Comment by SobPat** [comment]
Fiz esse teste e outros, mas não está sendo enviado nenhuma variável, todas são enviadas em branco.

**Comment by marconesns** [comment]
Também estou com o mesmo problema, qualquer variavel retorna vazia, no teste pelo visualizador funciona.

**Comment by SobPat** [comment]
Descobri a correção, no docker compose estava pegando a imagem
image : davidsongomes/evolution-api:latest

Ao substituir para a imagem

image: atendai/evolution-api:latest

 Voltou a funcionar.
