### ISSUE TITLE
[PT-BR]Não recebe as mensagem no chatwoot que são enviadas no aplicativo(WA BUSSINESS[BUG]

### ISSUE THREAD

**Issue by bergpinheiro** [EvolutionAPI/evolution-api#485]
To usando chatwootN 3.6.7 e evolution 1.7.0;

Quando estou conectado com um whatsapp normal funciona.
Agora quando estou com um whatsapp bussines ele nao aparece as mensagens que enviei através do celular no chatwoot.

Log-------------
[Evolution API]  v1.7.0  1   -  Thu Mar 21 2024 13:54:57     ERROR   [ChatwootService]  [object]   
ApiError: Generic Error
    at catchErrorCodes (/evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:229:15)
    at /evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:257:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  url: 'https://minha url/api/v1/accounts/1/contacts/4055',
  status: 422,
  statusText: 'Unprocessable Entity',

{
    message: 'Phone number has already been taken',
    attributes: [ 'phone_number' ]
  },

  request: {
    method: 'PUT',
    url: '/api/v1/accounts/{account_id}/contacts/{id}',
    path: { account_id: '1', id: 4055 },
    body: {
      avatar_url: 'https://pps.whatsapp.net/v/t61.24694-24/260959837_806678954092155_8712517080961772219_n.jpg?ccb=11-4&oh=01_AdS_H7x8MXv4YKIS73uKAA99OG5x6H5SlCQQSQQA7g5x0g&oe=66096696&_nc_sid=e6ed6c&_nc_cat=107'
    },
    errors: { '403': 'Access denied', '404': 'Contact not found' }
  }
} 
[Evolution API]  v1.7.0  1   -  Thu Mar 21 2024 13:55:03     LOG   [WAStartupService]  [object]   
{
  key: {
    remoteJid: '5511953523741@s.whatsapp.net',
    fromMe: false,
    id: 'CC2A34BC85B27E885BE22965C86EB1C8',
    participant: undefined
  },
  pushName: 'Weblooks',

  message: {
    conversation: 'Teste',
    messageContextInfo: MessageContextInfo {
      deviceListMetadata: [DeviceListMetadata],
      deviceListMetadataVersion: 2
    }
  },
  contextInfo: undefined,
  messageType: 'conversation',
  messageTimestamp: 1711040103,
  owner: 'berg',
  source: 'android'
} 
[Evolution API]  v1.7.0  1   -  Thu Mar 21 2024 13:55:03     ERROR   [ChatwootService]  [object]   
ApiError: Generic Error
    at catchErrorCodes (/evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:229:15)
    at /evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:257:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  url: 'https://minha url/api/v1/accounts/1/contacts/4055',
  status: 422,
  statusText: 'Unprocessable Entity',

{
    message: 'Phone number has already been taken',
    attributes: [ 'phone_number' ]
  },

  request: {
    method: 'PUT',
    url: '/api/v1/accounts/{account_id}/contacts/{id}',
    path: { account_id: '1', id: 4055 },
    body: {
      avatar_url: 'https://pps.whatsapp.net/v/t61.24694-24/260959837_806678954092155_8712517080961772219_n.jpg?ccb=11-4&oh=01_AdS_H7x8MXv4YKIS73uKAA99OG5x6H5SlCQQSQQA7g5x0g&oe=66096696&_nc_sid=e6ed6c&_nc_cat=107'
    },
    errors: { '403': 'Access denied', '404': 'Contact not found' }
  }
}

**Comment by jaison-x** [comment]
> To usando chatwootN 3.6.7 e evolution 1.7.0;
> 
> Quando estou conectado com um whatsapp normal funciona. Agora quando estou com um whatsapp bussines ele nao aparece as mensagens que enviei através do celular no chatwoot.
> 
> Log------------- [Evolution API] v1.7.0 1 - Thu Mar 21 2024 13:54:57 ERROR [ChatwootService] [object] ApiError: Generic Error at catchErrorCodes (/evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:229:15) at /evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:257:17 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) { url: 'https://minha url/api/v1/accounts/1/contacts/4055', status: 422, statusText: 'Unprocessable Entity', � { message: 'Phone number has already been taken', attributes: [ 'phone_number' ] }, � request: { method: 'PUT', url: '/api/v1/accounts/{account_id}/contacts/{id}', path: { account_id: '1', id: 4055 }, body: { avatar_url: 'https://pps.whatsapp.net/v/t61.24694-24/260959837_806678954092155_8712517080961772219_n.jpg?ccb=11-4&oh=01_AdS_H7x8MXv4YKIS73uKAA99OG5x6H5SlCQQSQQA7g5x0g&oe=66096696&_nc_sid=e6ed6c&_nc_cat=107' }, errors: { '403': 'Access denied', '404': 'Contact not found' } } } [Evolution API] v1.7.0 1 - Thu Mar 21 2024 13:55:03 LOG [WAStartupService] [object] { key: { remoteJid: '[5511953523741@s.whatsapp.net](mailto:5511953523741@s.whatsapp.net)', fromMe: false, id: 'CC2A34BC85B27E885BE22965C86EB1C8', participant: undefined }, pushName: 'Weblooks', � message: { conversation: 'Teste', messageContextInfo: MessageContextInfo { deviceListMetadata: [DeviceListMetadata], deviceListMetadataVersion: 2 } }, contextInfo: undefined, messageType: 'conversation', messageTimestamp: 1711040103, owner: 'berg', source: 'android' } [Evolution API] v1.7.0 1 - Thu Mar 21 2024 13:55:03 ERROR [ChatwootService] [object] ApiError: Generic Error at catchErrorCodes (/evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:229:15) at /evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:257:17 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) { url: 'https://minha url/api/v1/accounts/1/contacts/4055', status: 422, statusText: 'Unprocessable Entity', � { message: 'Phone number has already been taken', attributes: [ 'phone_number' ] }, � request: { method: 'PUT', url: '/api/v1/accounts/{account_id}/contacts/{id}', path: { account_id: '1', id: 4055 }, body: { avatar_url: 'https://pps.whatsapp.net/v/t61.24694-24/260959837_806678954092155_8712517080961772219_n.jpg?ccb=11-4&oh=01_AdS_H7x8MXv4YKIS73uKAA99OG5x6H5SlCQQSQQA7g5x0g&oe=66096696&_nc_sid=e6ed6c&_nc_cat=107' }, errors: { '403': 'Access denied', '404': 'Contact not found' } } }

Pela sua mensagen de erro, parece ter dois contatos no seu Chatwoot usando o mesmo número, no caso o número 5511953523741.

Tente excluir um destes contatos e verificar se esse log desaparece.

**Comment by bergpinheiro** [comment]
> > To usando chatwootN 3.6.7 e evolution 1.7.0;
> > Quando estou conectado com um whatsapp normal funciona. Agora quando estou com um whatsapp bussines ele nao aparece as mensagens que enviei através do celular no chatwoot.
> > Log------------- [Evolution API] v1.7.0 1 - Thu Mar 21 2024 13:54:57 ERROR [ChatwootService] [object] ApiError: Generic Error at catchErrorCodes (/evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:229:15) at /evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:257:17 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) { url: 'https://minha url/api/v1/accounts/1/contacts/4055', status: 422, statusText: 'Unprocessable Entity', � { message: 'Phone number has already been taken', attributes: [ 'phone_number' ] }, � request: { method: 'PUT', url: '/api/v1/accounts/{account_id}/contacts/{id}', path: { account_id: '1', id: 4055 }, body: { avatar_url: 'https://pps.whatsapp.net/v/t61.24694-24/260959837_806678954092155_8712517080961772219_n.jpg?ccb=11-4&oh=01_AdS_H7x8MXv4YKIS73uKAA99OG5x6H5SlCQQSQQA7g5x0g&oe=66096696&_nc_sid=e6ed6c&_nc_cat=107' }, errors: { '403': 'Access denied', '404': 'Contact not found' } } } [Evolution API] v1.7.0 1 - Thu Mar 21 2024 13:55:03 LOG [WAStartupService] [object] { key: { remoteJid: '[5511953523741@s.whatsapp.net](mailto:5511953523741@s.whatsapp.net)', fromMe: false, id: 'CC2A34BC85B27E885BE22965C86EB1C8', participant: undefined }, pushName: 'Weblooks', � message: { conversation: 'Teste', messageContextInfo: MessageContextInfo { deviceListMetadata: [DeviceListMetadata], deviceListMetadataVersion: 2 } }, contextInfo: undefined, messageType: 'conversation', messageTimestamp: 1711040103, owner: 'berg', source: 'android' } [Evolution API] v1.7.0 1 - Thu Mar 21 2024 13:55:03 ERROR [ChatwootService] [object] ApiError: Generic Error at catchErrorCodes (/evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:229:15) at /evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:257:17 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) { url: 'https://minha url/api/v1/accounts/1/contacts/4055', status: 422, statusText: 'Unprocessable Entity', � { message: 'Phone number has already been taken', attributes: [ 'phone_number' ] }, � request: { method: 'PUT', url: '/api/v1/accounts/{account_id}/contacts/{id}', path: { account_id: '1', id: 4055 }, body: { avatar_url: 'https://pps.whatsapp.net/v/t61.24694-24/260959837_806678954092155_8712517080961772219_n.jpg?ccb=11-4&oh=01_AdS_H7x8MXv4YKIS73uKAA99OG5x6H5SlCQQSQQA7g5x0g&oe=66096696&_nc_sid=e6ed6c&_nc_cat=107' }, errors: { '403': 'Access denied', '404': 'Contact not found' } } }
> 
> Pela sua mensagen de erro, parece ter dois contatos no seu Chatwoot usando o mesmo número, no caso o número 5511953523741.
> 
> Tente excluir um destes contatos e verificar se esse log desaparece.

Exatamente ele ta criando um contato novo.
