### ISSUE TITLE
[PT][BUG] - Recuperação de nomes ao importar histórico de mensagens para o chatwoot

### ISSUE THREAD

**Issue by felipifranco** [EvolutionAPI/evolution-api#486]
Ao usar a importação de mensagens #395 , em uma instalação limpa do chatwoot, reparei que os nomes dos contatos não são recuperados para o chatwoot, aparecendo apenas os números de telefone do mesmo.

![image](https://github.com/EvolutionAPI/evolution-api/assets/33034188/4e46653c-8700-412d-875c-b05c6893018c)

este fato é um bug em minha máquina ou uma possível feature?

Caso o usuário importado entre em contato novamente, seu nome é recuperado.

**Comment by jaison-x** [comment]
A importação importa os contatos sim. Dê uma olhada nos logs para ver se aparece algum erro ou problema. Só lembro que o sistema só vai importar quem estiver cadastrado como um contato no telefone. Se não estiver cadastrado como contato vai aparecer somente número mesmo na conversa. Precisa ter o número cadastrado na agenda do celular. 

Eu já peguei casos onde tive que colocar o parâmetro da instância sync_full_history como true para a baileys enviar o evento com os contatos. Isso parece ser uma questão específica da baileys. Vale a pena você testar neste formato para verificar se pode ser isso.

**Comment by felipifranco** [comment]
Realmente em uma nova tentativa os nomes foram sim importados. Estranho é que em ambas as vezes eu usei a opção sync_full_history como true.
