### ISSUE TITLE
[PT][FEAT] Chatwoot: Em caso de conexão fechada e se agente tentar enviar mensagem do Chatwoot, seria ótimo apresentar erro  de envio ou apresentar a cor vermelha na mensagem enviada sem sucesso

### ISSUE THREAD

**Issue by francisbreit** [EvolutionAPI/evolution-api#489]
### Título: Em caso de conexão fechada e se agente tentar enviar mensagem do Chatwoot, seria ótimo apresentar erro de envio ou apresentar a cor vermelha na mensagem enviada sem sucesso!

Versões utilizadas: Chatwoot 3.6.0 e Evolution 1.7.0

#### Descrição Detalhada:
Apesar de uma mensagem ser enviada ao bot, quando uma conexão cai (exemplo: Status da instância Inbox1: closed)
conforme imagem abaixo, vou sugerir uma faeture que impede um falso positivo para os agentes quando os mesmos enviam mensagens pelo Chatwoot as quais nao chegam ao destino.
![Captura de Tela 2024-03-25 às 09 19 27](https://github.com/EvolutionAPI/evolution-api/assets/5285287/c430ee90-0cc2-4cfd-afb7-8de20eae1060)

Notei que, após a sessão cair, quando um agente envia mensagem, a mesma apresenta falso positivo de sucesso, pois, fica na cor azul, sem nenhum tipo de erro na conversa. Por exemplo, na imagem abaixo, foram enviadas 2 mensagens com a sessão desconectada, e nenhum tipo de mensagem de erro foi apresentada na conversa, transparecendo ao agente que a mensagem foi enviada com sucesso!
![Captura de Tela 2024-03-25 às 09 20 52](https://github.com/EvolutionAPI/evolution-api/assets/5285287/195ad89b-f170-4a3b-aadd-94ba8c6c2cd9)

**Comment by R4T0** [comment]
![image](https://github.com/EvolutionAPI/evolution-api/assets/73944522/e954c4cd-58bb-4678-973a-4a9c0b940b5e)
Creio que esteja falando disso, chatwoot 3.7. Evolution 1.7.0

**Comment by francisbreit** [comment]
> ![image](https://private-user-images.githubusercontent.com/73944522/324451758-e954c4cd-58bb-4678-973a-4a9c0b940b5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MTc1MjIsIm5iZiI6MTcxMzgxNzIyMiwicGF0aCI6Ii83Mzk0NDUyMi8zMjQ0NTE3NTgtZTk1NGM0Y2QtNThiYi00Njc4LTk3M2EtNGE5YzBiOTQwYjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDIwMjAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ZGMzZDI5MDY5YmU4MDJmODg1N2RhYzhmYTg1NzBhMGJhZWE5MzQwNGE5YzhkY2JmNjZkMDg2NjUyNjhhYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UPq6Ugqkq-L0uI-n-YapTvURS1W9Rgcu-Z4s3zjQrbk) Creio que esteja falando disso, chatwoot 3.7. Evolution 1.7.0

Sim, exatamente. Isso evidenciaria que uma mensagem não foi enviada com sucesso!
