### ISSUE TITLE
Nao mostrar QR code

### ISSUE THREAD

**Issue by claudiogruponsc** [EvolutionAPI/evolution-api#49]
estou avaliando a viabilidade de implantacao da ferramenta em nossa empresa. 

em primeiro lugar, parabéns ! 

meu problema é a nao geracao do QRcode. a imagem nao é disponibilizada... ja criei as caixas postais, recebo a mensagem da geracao, mas nao consigo visualizar.

e isso me impede de prosseguir com a analise.

alguma dica ? 

obrigado

**Comment by DavidsonGomes** [comment]
No escuro dificil dizer, preciso saber oq aparece nos logs nesse momento citado. pode ser erro de acesso para envio da imagem ao chatwoot, pode ser erro de permissões internas das pasta store da api, ... enfim, preciso de detalhes para ajudar

**Comment by chadefita** [comment]
> estou avaliando a viabilidade de implantacao da ferramenta em nossa empresa.
> 
> em primeiro lugar, parabéns !
> 
> meu problema é a nao geracao do QRcode. a imagem nao é disponibilizada... ja criei as caixas postais, recebo a mensagem da geracao, mas nao consigo visualizar.
> 
> e isso me impede de prosseguir com a analise.
> 
> alguma dica ?
> 
> obrigado

Fala mano! Tenta dar uma olhada no .env dentro da pasta do chatwoot se lá está configurado o FRONTEND IP. Outra coisa que eu faço é um F12 dentro do navegador e tento pegar o erro que aparece, pra mim ele pegava o IP: 0.0.0.0/ocaminho, troquei na coloquei meu IP no lugar dos 0s e ele me mostrou o QRcode, depois disso fui na unha procurando.

OBS: Não sou programador!

**Comment by montenegromatheus** [comment]
No meu caso, eu usei o easypanel pra configurar via docker, sabe onde eu acho esse FRONTEND IP la?

> > estou avaliando a viabilidade de implantacao da ferramenta em nossa empresa.
> > em primeiro lugar, parabéns !
> > meu problema é a nao geracao do QRcode. a imagem nao é disponibilizada... ja criei as caixas postais, recebo a mensagem da geracao, mas nao consigo visualizar.
> > e isso me impede de prosseguir com a analise.
> > alguma dica ?
> > obrigado
> 
> Fala mano! Tenta dar uma olhada no .env dentro da pasta do chatwoot se lá está configurado o FRONTEND IP. Outra coisa que eu faço é um F12 dentro do navegador e tento pegar o erro que aparece, pra mim ele pegava o IP: 0.0.0.0/ocaminho, troquei na coloquei meu IP no lugar dos 0s e ele me mostrou o QRcode, depois disso fui na unha procurando.
> 
> OBS: Não sou programador!

Oi, no meu caso, eu usei o easypanel pra subir o chatwoot via docker. Sabe como acho essa FRONTEND IP?

**Comment by claudioalberto** [comment]
Fala mano, então no easypanel para ver as variáveis de ambiente (ENV) você pode clicar no serviço do chatwoot e clicar na aba de Environment.

![image](https://github.com/EvolutionAPI/evolution-api/assets/16268397/7e431605-88a4-4383-8256-bad52fda1fbf)

Espero ter ajudado.

**Comment by JoelQuintanaJunior** [comment]
Bom dia ,

Estou tendo o mesmo erro , a caixa de entrada não gerar o QR cod e apresenta este erro alguem consegue ajudar

![image](https://github.com/EvolutionAPI/evolution-api/assets/143043415/b4210bd5-d6e3-40a2-b59a-5d735c4b98e0)


Dentro do Env a configuração esta desta forma 

![image](https://github.com/EvolutionAPI/evolution-api/assets/143043415/abb8f435-1cd2-4435-bc9c-345ea17dc2d4)

**Comment by JoelQuintanaJunior** [comment]
> Boa tarde, seu websocket não está conseguindo se conectar.
> 
> Você ta usando apache ou ngix cmo proxy?
> 
> precisa criar um redirecionamento para o websocket para funcionar.
> 
> No meu caso uso apache, e aí mudei a configuração do meu arquivo de configuração do dominio, exemplo do meu caso:
> 
> /etc/apache2/sites-available/chat.dominio.com.conf
> 
> e deixei dessa forma:
> 
> `<VirtualHost *:80>
> 
> ServerName chat.seudominio.com
> 
> ProxyRequests Off ProxyPreserveHost On ProxyVia Full
> 
> ```
> <Proxy *>
>     Require all granted
> </Proxy>
> 
> ProxyPass /   http://IPDAMAQUINACOMCHATWOOT:3000/ nocanon
> ProxyPassReverse / http://IPDAMAQUINACOMCHATWOOT:3000/   
> ```
> 
> ErrorLog ${APACHE_LOG_DIR}/error_chat.log CustomLog ${APACHE_LOG_DIR}/chat_access.log combined
> 
> <VirtualHost *:443> ServerName chat.seudominio.com
> 
> ```
> ProxyRequests off
> ProxyVia on      
> RewriteEngine On
> 
> 
> 
> LoadModule proxy_module modules/mod_proxy.so
> LoadModule proxy_http_module modules/mod_proxy_http.so
> LoadModule headers_module modules/mod_headers.so
> LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so
> 
> 
> 
> <Proxy *>
>     Require all granted
> </Proxy>
> 
> RewriteEngine On
> RewriteCond %{HTTP:Connection} Upgrade [NC]
> RewriteCond %{HTTP:Upgrade} websocket [NC]
> RewriteRule /(.*) ws://IPDAMAQUINACOMCHATWOOT:3000/$1 [P,L]
> 
> ProxyPreserveHost On
> ProxyPass / http://IPDAMAQUINACOMCHATWOOT:3000/
> ProxyPassReverse / http://IPDAMAQUINACOMCHATWOOT:3000/
> 
> 
> 
> ErrorLog ${APACHE_LOG_DIR}/chat_error.log
> CustomLog ${APACHE_LOG_DIR}/chat_access.log combined
> ```
> 
> `
> No caso, quem faz o redirecionamento do websocker é essa linha: ` RewriteRule /(.*) ws://IPDAMAQUINACOMCHATWOOT:3000/$1 [P,L]`
> 
> Espero que te ajude ai

Minha instalação esta pelo easypanel, localizei pelo SFTP o NGINX porem continua da mesma forma, acredito que eu esteja fazendo algo de errado.
