### ISSUE TITLE
Instancias DESCONECTADO SOZINHAS [PT][BUG]

### ISSUE THREAD

**Issue by COMPAGNONIS** [EvolutionAPI/evolution-api#490]
Estou utilizando atualmente 70 instancias com whatsapp busines vinculadas com typebot, porem umas duas semanas pra ca, comecou a ocorrer diariamente desconectar os whatsapps das instancias, ai tenho q ir la no dispositivo e fazer a conexao novamente,  cpu da evolution esta em : 300%  Memory : 706 mb  network i/o: 100mb/ 65  o que pode estar causando essas desconexoes seria o numero de instancias alto? coomo corrigir isso?

**Comment by dilneiss** [comment]
bom dia irmão, aqui também estou enfrentando o mesmo problema.. só uma dúvida, qual a configação da sua vps atual, onde está localizado e como você tem a instalação feita ai segurando esse nr de clientes? instalou direto na maquina.. docker, swarm? portainer?

**Comment by COMPAGNONIS** [comment]
VPS hetzer : 
8
VCPU
16 GB
RAM
240 GB
DISK LOCAL

**Comment by COMPAGNONIS** [comment]
Instalacao via Easy pannel , uso de 12% da memoria ram apenas, e 17% de disk

**Comment by afonsoogomes** [comment]
Aqui ta acontecendo a mesma coisa, do nada a conexão cai, mas nao aparece como desconectado no manager, as vezes o evolution fica spamando que a conexão foi estabelecida com o chatwoot e acaba que deixa o chatwoot quase parando por isso, a CPU sobe demais. E eu estou utilizando a nova versão, que é a 1.7.0

**Comment by diogodaluz** [comment]
Aqui ta acontecendo a mesma coisa. Alguém tem solução.

Uso Evolution em Easypanel na Hetzner também. 

Será que tem a ver com Hetzner? Apesar que usei na Linode e deu a mesma coisa.

**Comment by claudio-ct** [comment]
OPaaa,
Estamos usando a versao 1.6, ao atualizar para versão recente, sumiu todoas conexoes tendo que recria-las.
Existe alguma forma de manter essas configuraçoes mesmo quando atualizamos?

**Comment by stavososa** [comment]
Mano ta acontecendo comigo, teve alguma solução o seu?

**Comment by ailsonrm** [comment]
aqui estou sendo desconectado a casa 3/4 dias
