### ISSUE TITLE
[PT][BUG] Mensagem errada referenciada na resposta do Chatwoot

### ISSUE THREAD

**Issue by danielfontolan** [EvolutionAPI/evolution-api#491]
#### Descrição:
Quando se responde uma mensagem de um usuário no Chatwoot integrado ao Evolution API, a mensagem que foi respondida no Chatwoot aparece diferente para a pessoa que recebeu a mensagem.

#### Passos para Reproduzir:
1. Responda uma mensagem qualquer de um usuário do Chatwoot.
2. Verifique com o usuário do WhatsApp qual mensagem que aparece para ele como respondida. Deverá ser diferente da escolhida pelo usuário Chatwoot

#### Comportamento Esperado:
Que o usuário do WhatsApp recebesse a mesma informação do usuário Chatwoot de qual mensagem foi respondida.

#### Comportamento Atual:
O usuário do whatsApp que recebeu a mensagem respondida visualiza a mensagem errada como respondida.

#### Capturas de Tela/Vídeos:
<img width="756" alt="image" src="https://github.com/EvolutionAPI/evolution-api/assets/154978143/53a4cbf5-389a-4341-9782-b5db2f61fe15">
<img width="556" alt="image" src="https://github.com/EvolutionAPI/evolution-api/assets/154978143/47de2107-adbf-46c0-903f-485fbc36469d">

#### Ambiente:
- **Servidor:** Ubuntu 22.04
- **Versão da API:** 1.6.1 e 1.7.0
- **Outras Especificações de Hardware/Software:** [ex: CPU, GPU]

#### Envio de Logs:
Por favor, anexe os logs que possam estar relacionados ao problema. Se os logs contiverem informações sensíveis, considere enviá-los de forma privada para um dos mantenedores do projeto.

#### Notas Adicionais:
Inclua aqui qualquer outra informação que você ache que possa ser útil para entender ou resolver o bug.

**Comment by danielfontolan** [comment]
Obrigado pela sugestão, Vinicius. Fiz conforme sugeriu. Apaguei minha instalação anterior da Evolution e fiz uma nova integrada ao MongoDB. Porém, agora quando respondo uma mensagem no Chatwoot quem recebe a mensagem no WhatsApp não identifica qual foi a mensagem respondida.
Seguem prints.
O que pode estar faltando, por favor?


Daniel Fontolan
Diretor
Wizard Capivari
Em 26 de mar. de 2024, 22:35 -0300, Vinicius Cardoso ***@***.***>, escreveu:

**Comment by VinCardoso** [comment]
> Porém, agora quando respondo uma mensagem no Chatwoot quem recebe a mensagem no WhatsApp não identifica qual foi a mensagem respondida.

Eu não entendi o que quis dizer aqui. E nem veio imagem nenhuma.

Sugiro responder direto no Github ao invés de responder por e-mail a issue.

**Comment by danielfontolan** [comment]
Depois que mudei a instalação da Evolution com a integração ao mongoDB a pessoa usando o WhatsApp que recebe a resposta feita no Chatwoot não recebe com a indicação de qual mensagem foi respondida. É como se a pessoa que está no WhatsApp recebesse uma mensagem simples, sem a indicação de que foi uma resposta.

<img width="459" alt="Attachment" src="https://github.com/EvolutionAPI/evolution-api/assets/154978143/07418d1f-95a8-41d1-acb4-54bb8466bbcc">
<img width="542" alt="Attachment-1" src="https://github.com/EvolutionAPI/evolution-api/assets/154978143/511096ce-de9e-4ec0-a089-4a29b090a45c">

**Comment by cakrumen** [comment]
Aqui resolveu com a instalação do mongoDB

**Comment by VinCardoso** [comment]
> Depois que mudei a instalação da Evolution com a integração ao mongoDB a pessoa usando o WhatsApp que recebe a resposta feita no Chatwoot não recebe com a indicação de qual mensagem foi respondida. É como se a pessoa que está no WhatsApp recebesse uma mensagem simples, sem a indicação de que foi uma resposta.
> 
> <img alt="Attachment" width="459" src="https://private-user-images.githubusercontent.com/154978143/317499016-07418d1f-95a8-41d1-acb4-54bb8466bbcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MDg0NDgsIm5iZiI6MTcxMTgwODE0OCwicGF0aCI6Ii8xNTQ5NzgxNDMvMzE3NDk5MDE2LTA3NDE4ZDFmLTk1YTgtNDFkMS1hY2I0LTU0YmI4NDY2YmJjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQxNDE1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNjRhMTkwNmZiN2JjNDgwOTk5MzA5N2RjNjcyZmYxMDcxMjc4NDE5YWI3ZGEyODhiZDE1ZTYxOTNjY2E3MTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pNQ4kwpX8getO7e7Z2cxqJ419NiLMU2HMrMmwPalIIo"> <img alt="Attachment-1" width="542" src="https://private-user-images.githubusercontent.com/154978143/317499049-511096ce-de9e-4ec0-a089-4a29b090a45c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MDg0NDgsIm5iZiI6MTcxMTgwODE0OCwicGF0aCI6Ii8xNTQ5NzgxNDMvMzE3NDk5MDQ5LTUxMTA5NmNlLWRlOWUtNGVjMC1hMDg5LTRhMjliMDkwYTQ1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQxNDE1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmM1NTY4NmUyMGFlNzk1YTUzMWFiNjFmNTY3ZTdhZjJiZTI0YzUxNThmMmFmODYzNTA4NWFlOTAxMDk0MDU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y9XNuCCG64s0YiphInwr2ZGYW9HA6bs7wngqps0V5gY">

Uma dica importante é ver no banco de dados MongoDB se está conectado mesmo, se cada mensagem nova que tu envia vai pra lá, se as conexões novas que tu faz de instâncias no Evolution, aparecem lá e estão atualizadas.

Dá uma verificada nisso, pq se não ta indo/não está funcionando essa parte de referênciar/responder a mensagem correta, está me parecendo que talvez o MongoDB não esteja corretamente conectado a Evolution API.

Por exemplo: Faz conexão com o MongoDB e cria uma nova instância na Evolution e verifica se criou essa instância no banco de dados. Depois conecta, deleta, enfim muda o status da instância e vê se está mudando no Banco de dados também.

E principalmente vê se as mensagens que tu envia ou recebe estão indo para o Mongo também, na listagem de mensagens.

Ah, antes que eu me esqueça, outro ponto que acredito ser importante é que no meu evolution eu mandei sincronizar tudo com o Banco de dados, `DATA_INSTANCE, DATA_NEW_MESSAGE, MESSAGE_UPDATE, DATA_CONTACTS, DATA_CHATS, MESSAGE_DELETE, MESSAGE_READ` então está assim as configurações desses itens no meu Docker:

```
       # Aivar Banco de Dados
      - DATABASE_ENABLED=true
      - DATABASE_CONNECTION_URI=mongodb://[usuario]:[senha]@[local]:27077/?connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1
      - DATABASE_CONNECTION_DB_PREFIX_NAME=evolution-api
      # Escolha o que deseja salvar
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true
      - CHATWOOT_MESSAGE_DELETE=true
      - CHATWOOT_MESSAGE_READ=true
```

Como pode ver a parte de `DATABASE_SAVE` está tudo como `true`, isso acredito que é importante também. Não li se é necessário mas no meu ponto de vista, se ele precisa referenciar as mensagens e ele não está referênciando quando não está no banco de dados, a parte de mensagem `NEW_MESSAGE` e `DATA_CHATS` devem estar como true, para enviar esses dados para o banco. Na dúvida para não ter erro to mandando tudo para o banco.

Como eu comentei, cria o banco e testa a conexão com a URI de conexão no exato formato que tu colocou no Docker File para ver se tu consegue conectar certinho, pq pelo que estás falando aqui parece ser o erro.

Tenha certeza que: ou as duas aplicações estão na mesma rede, ou faz igual eu, libera acesso externo ao banco de dados, ou seja libera o MongoDB para acesso externo e na URI coloca na parte de [local] o endereço de IP do servidor para não ter erro.

Pq eu faço isso, libero o acesso e testo tentando fazer uma conexão ao Mongo direto da minha máquina para o servidor para ver se está acessando certinho o banco, e a URI está toda certinha. Pq qualquer erro na URI ali já não conecta.

Mas o mais importante foi o que eu falei no começo, abre o banco de dados após fazer a instalação e vê se está armazenando as atualizações lá dentro.

É isso, espero ter ajudado, eu não sou uma pessoa técnica, sou apenas curioso, que vai mexendo e fuçando até dar certo. Então talvez não consiga ajudar mais que isso, pois foge do meu conhecimento.

Mas te entendo, pois eu me irrito as vezes que teste e fico as vezes um dia inteiro tentando e não consigo, mas no meu caso geralmente é falta de conhecimento técnico. uhashuas

Espero ter ajudado.

**Comment by danielfontolan** [comment]
Show! Resolvido!!! Muito obrigado Vinicius! Os parâmetros de database na Evolution estavam como false. Coloquei como true e tudo funcionou! Forte abraço!
