### ISSUE TITLE
[PT][BUG] v1.7.0 - Eventos de Webhook "TYPEBOT_START" e "TYPEBOT_CHANGE_STATUS" não são disparados

### ISSUE THREAD

**Issue by aloisoinac** [EvolutionAPI/evolution-api#493]
#### Descrição:
Ao criar o webhook para enviar os Eventos **"TYPEBOT_START"** e **"TYPEBOT_CHANGE_STATUS"**, eles não são disparados para a URL delegada. Os demais eventos como esperados funcionam.

#### Passos para Reproduzir:
Crie um webhook para sua instância com o seguinte payload
`{
  "url": "{{SUA URL PARA RECEPCIONAR EVENTOS}}",
    "webhook_by_events": false,
    "webhook_base64": false,
    "events": [
        "TYPEBOT_START",
        "TYPEBOT_CHANGE_STATUS"
    ]    
}`

Utilizando o Endpoint da API do Evolution
`https://{{SUA EVOLUTION API}}/webhook/{{SUA INSTANCIA}}`

#### Comportamento Esperado:
Ao iniciar o fluxo de mensagens com o Typebot devidamente configurado, o Webhook disparar o evento "TYPEBOT_START" para a URL configurada na criação do fluxo, ao finalizar o fluxo também ser enviado o evento "TYPEBOT_CHANGE_STATUS".

#### Comportamento Atual:
Não são enviados esses eventos pelo gatilho do webhook

#### Capturas de Tela/Vídeos:
N/A

#### Ambiente:
- **Servidor:** [Ubuntu 20.04]
- **Versão da API:** [1.7.0]

#### Notas Adicionais:
O vínculo da instância ao Fluxo do Typebot fora feito utilizando a interface web, Evolution Manager

**Comment by rafaelsupport** [comment]
mesmo problema aqui
evolution na versão 2.2.1
