### ISSUE TITLE
Aleatoriamente ocorre timeout ao receber mídias (fotos, videos, documentos, áudio)

### ISSUE THREAD

**Issue by cakrumen** [EvolutionAPI/evolution-api#497]
Quando chegar uma nova mensagem, algumas mídias ocorre timeout no momento do download para ser convertido base64 conforme print abaixo, pegando a URL do próprio erro é possivel fazer download normalmente, quando gera o erro o sistema não tenta refazer o download ficando dessa forma o chatwoot sem receber a mensagem

#### Ambiente:
- **Servidor:** Ubuntu 22
- **Versão da API:** 1.2.7

**Comment by juliancesar** [comment]
Esse realmente é um problema que estou enfrentando com o ChatWoot 3.9, e ele se agrava quando uso o S3 como storage! E fica ainda pior quando está com o CloudFlare ativado na frente!
