### ISSUE TITLE
[PT][BUG] Essa conexão não é uma instância da evolution-api

### ISSUE THREAD

**Issue by willdotcom** [EvolutionAPI/evolution-api#498]
Olá, instalei a versão 1.7.0 e recebo este erro ao tentar entrar no gerenciador.
Deve-se notar que ainda não modifiquei nada, é uma instalação nova.

![image](https://github.com/EvolutionAPI/evolution-api/assets/9564011/2e0102fe-7871-43b6-83a8-e82c9da96092)

**Comment by VinCardoso** [comment]
Tu usou um Evolution Manager antigo, ou instalou um novo?

Eu quanto testei, assim que eles lançaram deu esse problema mesmo. Porém eles atualizaram para 1.7.0 mas o manager ainda não estava atualizado para suportar essa versão da API. Foi o que eu entendi na live que eles fizeram com o @luizeof que está lá no canal da Promovaweb.

[Link da Live](https://www.youtube.com/watch?v=LKHp90ZVFEs)

Agora acho que já está, mas tens que ter a versão atualizada do Manager.

Eu não sei exatamente como instalar, mas na minha instalação do docker que fiz esses dias usando essa imagem do docker:

[atendai/evolution-api:homolog](https://hub.docker.com/layers/atendai/evolution-api/homolog/images/sha256-8f203e6bbfcdbf5229c0d9bb13b2a6bfc9840661a4e42634e5e8c345b7f81a41?context=explore) 

Ele funcionou.

Ps: To usando a versão de homolog, pq eu to acompanhando com frequência os pull requests e tem já algumas atualizações pós 1.7.0 que eram importantes pra mim principalmente na parte de Chatwoot.

Mas acredito que a imagem do docker da versão 1.7.0 já esteja com o Manager atualizado.

Aqui está um print do meu funcionando:

![Screenshot 2024-03-30 at 12 23 23](https://github.com/EvolutionAPI/evolution-api/assets/5439301/ae4c6dce-c2f5-45d2-a461-11651b12f658)
