### ISSUE TITLE
[PT][FEAT] Identificação de Mensagem "Encaminhada" no Chatwoot

### ISSUE THREAD

**Issue by stgcompany** [EvolutionAPI/evolution-api#501]
#### Descrição Detalhada:
Saber quando uma mensagem enviada foi "encaminhada" / "forwarded" no Chatwoot.

![image](https://github.com/EvolutionAPI/evolution-api/assets/143809393/3fa52809-2c57-4092-a975-b0f2f9d97fa0)

#### Racional:
Saber se o envio de um vídeo por exemplo foi do contato ou ele pegou de uma outra conversa externa. O que tem um contexto bem diferente no qual é importante saber na conversa.

#### Exemplos de Uso:
Alguém envia o seu documento em forma de encaminhado, o que pode gerar desconfiança de possível fraude. Logo o atendente pode levar mais a sério a análise da comprovação daquele documento.

#### Possíveis Implementações:
Não sei se a Baileys já tem essa capacidade, deixo em aberto para os mais experientes.

#### Impacto no Projeto:
Mais um diferencial valioso na evolution.

#### Notas Adicionais:
---

**Comment by DouglasEleuterio** [comment]
Sabe dizer se o chatwoot já aceita essa identificação?

**Comment by stgcompany** [comment]
> Sabe dizer se o chatwoot já aceita essa identificação?

Creio que não, mas isso poderia ser feito simplesmente com um texto prefixo na mensagem "**Encaminhado:**__ ..."
