### ISSUE TITLE
[PT][BUG] - QUEBRA DE FLUXO e REINICIO DO FLUXO - TYPEBOT E WHATSAPP

### ISSUE THREAD

**Issue by zeroonend** [EvolutionAPI/evolution-api#508]
#### Descrição:
Tenho um fluxo que esta conectado a evolution api. que segue direitinho. porem qdo o usuario interage no whatsapp no meio do fluxo, o fluxo é quebrado de jogado para frente. como resolver? obg

#### Comportamento Esperado:
esperava que o usuario pode digitar o que quiser, que o fluxo continuava.

#### Comportamento Atual:
ele esta pulando as mensagens do funil.

Podem ajudar? obg

**Comment by zeroonend** [comment]
analisando melhor...qdo o usuario do zap...manda mensagem..com o funil em andamento..o sistema..reiniciar o funil de novo...

**Comment by zeroonend** [comment]
testei com a versao da evolution api tb..e continua a mesma coisa.

**Comment by zeroonend** [comment]
[typebot-export-meu-typebot-5skpfg2.json](https://github.com/EvolutionAPI/evolution-api/files/14855037/typebot-export-meu-typebot-5skpfg2.json)
Um simples fluxo que nao pede a interacao do cliente, mas, se o cliente digitar uma mensagem ou várias, o fluxo fica doido, reinicia, repete frases..etc... ele nao deveria ter um modo de programarmos somente qdo quisermos receber o que o cliente digita..e nao influenciar no fluxo? obg

**Comment by moanemanuel** [comment]
Estou com o mesmo problema. O bot não freia no fim da etapa/fluxo, fica sempre retornando para o inicio.

**Comment by zeroonend** [comment]
@deivisonrpg @DavidsonGomes Pode nos ajudar? Obg

**Comment by phtisp** [comment]
Por favor, classifique esta conversa, https://apiv2.xphsolution.com.br/survey/responses/4fd3d96f-d5b0-46ed-bb1a-f48a74b7c4a7
