### ISSUE TITLE
Correção de Markdown [PT][BUG]

### ISSUE THREAD

**Issue by 12webmarketing** [EvolutionAPI/evolution-api#509]
#### Descrição:
Markdown na V1.7 nao funciona.

#### Comportamento atual:

Quando recebo um conteudo no Typebot vindo de uma IA ele vem um Markdown e na V1.7 quando é enviado para o Whatsapp ele nao vem sem marcações, vindo tudo em linha unica, suprimindo os Bolets e as listas numeradas.

OBS: isso funciona na V1.5.4

#### Exemplo do comportamento na V1.7

Olá! Na 12WEB Marketing, oferecemos os seguintes serviços:Posso te ajudar com mais informações sobre algum desses serviços? Ou talvez tenha alguma dúvida específica sobre o desenvolvimento web?

#### Exemplo do Comportamento Esperado:

Olá! Na 12WEB Marketing, oferecemos os seguintes serviços:

1. Desenvolvimento de sites
2. Desenvolvimento de landing pages
3. Desenvolvimento de lojas virtuais
4. Campanhas de Marketing
5. Hospedagem de sites

Posso te ajudar com mais informações sobre algum desses serviços? Se sim, qual deles você tem interesse em saber mais?

**Comment by antonioaraujo664** [comment]
nao é so isso... quando surge quebra de linha, ele simplesmente nao exibe o texto
