### ISSUE TITLE
Evento de status de mensagem não retorna informações

### ISSUE THREAD

**Issue by robinhodemorais** [EvolutionAPI/evolution-api#51]
Estou testando o retorno de confirmação de leitura da mensagem e mesmo estando o evento MESSAGES_UPSERT habilitado no events do webhook não está retornando essa informação para o webhook

![WhatsApp Image 2023-07-31 at 20 27 02](https://github.com/EvolutionAPI/evolution-api/assets/13595347/6b159541-937a-4861-98f2-6f847a20ddf5)

no log está retornando assim

![WhatsApp Image 2023-07-31 at 20 28 14](https://github.com/EvolutionAPI/evolution-api/assets/13595347/e1b012cb-52b8-4dbd-8655-b065c00cabd4)

**Comment by DavidsonGomes** [comment]
Ate aqui os testes que fizemos chega tudo normal, verifique se o aparelho conectado nas configurações de segurança se esta ativo a confirmação de leitura, e tambem verifique no whatsapp que esta validando junto, se um dos dois não tiver ativo não recebe a confirmação no webhook!

**Comment by lindenbergp** [comment]
**Ta funcionando. Estou testando em dois aparelhos ambos com a confirmação de leitura ativados!!!**

1. Enviei a mensagem e recebi o webhook; **"event": "messages.upsert"**
![image](https://github.com/EvolutionAPI/evolution-api/assets/24882737/0cb38033-90fa-4816-b644-99457d7dbbd1)

2.  Recebi a confirmação de entrega; **"event": "messages.update"**
![image](https://github.com/EvolutionAPI/evolution-api/assets/24882737/24304b58-728c-44f4-b0fa-02aafa9f324a)

3.  Recebi a confirmação de leitura; **"event": "messages.update"**
![image](https://github.com/EvolutionAPI/evolution-api/assets/24882737/f5729f0e-af6a-4f7e-adc5-2b79b90e9c69)
