### ISSUE TITLE
[PT][BUG]

### ISSUE THREAD

**Issue by Lohuama** [EvolutionAPI/evolution-api#511]
### Título: [Breve Descrição do Bug]
 image davidsongomes/evolution-api:v1.5.4 is not available

#### Descrição:
Descreva detalhadamente o problema que você encontrou. Inclua qualquer contexto relevante que possa ajudar a entender a origem do bug.

I'm trying to put the evolution api in my potainer, but I'm not finding the image

#### Passos para Reproduzir:
1. Liste os passos necessários para reproduzir o problema.
Evolution was working, then I updated it and it stopped

3. Tente ser o mais específico possível.
4. I'm trying to connect the typebot to the evolution api, but the typebot option didn't appear in the evolution , I tried to set it and it gave an error, so I deleted my evolution api in my portainer, I deleted the stack, the containers and the volume and uploaded it again, so when I uploaded the image again gave this error of not finding

6. Se o problema ocorrer em um cenário específico, descreva-o aqui.
portainer and server

#### Comportamento Esperado:
Descreva o que você esperava que acontecesse quando seguisse os passos acima.
Running

#### Comportamento Atual:
Explique o que realmente acontece quando você segue os passos acima.
Reject

#### Capturas de Tela/Vídeos:
Se possível, adicione capturas de tela ou vídeos que ilustrem o problema. Isso pode ser extremamente útil para entender o problema.
![image](https://github.com/EvolutionAPI/evolution-api/assets/91543341/27401748-da0e-452f-b0ec-6d24db35f3dd)

![image](https://github.com/EvolutionAPI/evolution-api/assets/91543341/eab0b930-4716-48e0-b0cb-23cce9766349)

#### Ambiente:
- **Servidor:** [ex: Ubuntu 18.04] - AWS UBUNTU
- **Versão da API:** [ex: 1.5.4] - 22.04
- **Outras Especificações de Hardware/Software:** [ex: CPU, GPU]

#### Envio de Logs:
Por favor, anexe os logs que possam estar relacionados ao problema. Se os logs contiverem informações sensíveis, considere enviá-los de forma privada para um dos mantenedores do projeto.

#### Notas Adicionais:
Inclua aqui qualquer outra informação que você ache que possa ser útil para entender ou resolver o bug.

version: "3.7"

services:
  evolution_astra:
    image: davidsongomes/evolution-api:v1.5.4
    command: ["node", "./dist/src/main.js"]
    networks:
      - chatBus
    volumes:
    - evolution_astra_instances:/evolution/instances
    - evolution_astra_store:/evolution/store
    environment:
      - SERVER_URL=https://evolutionapi.chat.bus2.services
      - DOCKER_ENV=true
      - LOG_LEVEL=ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK,WEBHOOKS
      - DEL_INSTANCE=false
      - CONFIG_SESSION_PHONE_CLIENT=Evolution
      - CONFIG_SESSION_PHONE_NAME=Chrome
      - STORE_MESSAGES=true
      - STORE_MESSAGE_UP=true
      - STORE_CONTACTS=true
      - STORE_CHATS=true
      - CLEAN_STORE_CLEANING_INTERVAL=7200 # seconds === 2h
      - CLEAN_STORE_MESSAGES=true
      - CLEAN_STORE_MESSAGE_UP=true
      - CLEAN_STORE_CONTACTS=true
      - CLEAN_STORE_CHATS=true
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=a27e269003290c3534b530038d73ebeb
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      - QRCODE_LIMIT=30000
      - WEBHOOK_GLOBAL_ENABLED=false
      - WEBHOOK_GLOBAL_URL=https://URL
      - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=false
      - WEBHOOK_EVENTS_APPLICATION_STARTUP=false
      - WEBHOOK_EVENTS_QRCODE_UPDATED=true
      - WEBHOOK_EVENTS_MESSAGES_SET=false
      - WEBHOOK_EVENTS_MESSAGES_UPSERT=true
      - WEBHOOK_EVENTS_MESSAGES_UPDATE=true
      - WEBHOOK_EVENTS_CONTACTS_SET=true
      - WEBHOOK_EVENTS_CONTACTS_UPSERT=true
      - WEBHOOK_EVENTS_CONTACTS_UPDATE=true
      - WEBHOOK_EVENTS_PRESENCE_UPDATE=true
      - WEBHOOK_EVENTS_CHATS_SET=true
      - WEBHOOK_EVENTS_CHATS_UPSERT=true
      - WEBHOOK_EVENTS_CHATS_UPDATE=true
      - WEBHOOK_EVENTS_CHATS_DELETE=true
      - WEBHOOK_EVENTS_GROUPS_UPSERT=true
      - WEBHOOK_EVENTS_GROUPS_UPDATE=true
      - WEBHOOK_EVENTS_GROUP_PARTICIPANTS_UPDATE=true
      - WEBHOOK_EVENTS_CONNECTION_UPDATE=true
      - REDIS_ENABLED=false
      - REDIS_URI=redis://redis:6379
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M
      labels:
        - traefik.enable=true
        - traefik.http.routers.evolution_astra.rule=Host(`evolutionapi.chat.bus2.services`)
        - traefik.http.routers.evolution_astra.entrypoints=websecure
        - traefik.http.routers.evolution_astra.tls.certresolver=letsencryptresolver
        - traefik.http.routers.evolution_astra.priority=1
        - traefik.http.routers.evolution_astra.service=evolution_astra
        - traefik.http.services.evolution_astra.loadbalancer.server.port=8080
        - traefik.http.services.evolution_astra.loadbalancer.passHostHeader=true

volumes:
  evolution_astra_instances:
    external: true
    name: evolution_astra_instances
  evolution_astra_store:
    external: true
    name: evolution_astra_store

networks:
  chatBus:
    name: chatBus
    external: true

**Comment by paginare** [comment]
a imagem mudou:    

 image: atendai/evolution-api:latest

**Comment by phtisp** [comment]
Por favor, classifique esta conversa, https://apiv2.xphsolution.com.br/survey/responses/bf2dbcc5-500c-4cfc-b4f7-444e90c17fc1
