### ISSUE TITLE
[PT][BUG] - SOM DE NOTIFICAÇÕES NÃO FUNCIONAM APÓS CONECTAR SESSÃO.

### ISSUE THREAD

**Issue by diluh** [EvolutionAPI/evolution-api#512]
#### Descrição:
Percebi que quando conectamos uma sessão no Whatsapp ele para de receber o SOM da notificação, por mais que você defina 
    "always_online": **false,**
 O aparelho celular fica sem SOM das notificações, para que o Som das notificações volte ao normal no MANAGER eu vou na sessão no Marco e Desmarco a opção **Sempre Online** e o som das notificações voltam ao normal.
#### Passos para Reproduzir:
1. Quando conecta uma Sessão no Whatsapp ele para de receber o SOM das notificaçoes.
2. Testei no Celular Android e no Iphone Ambos com esse Bug.
3. Após a sessão conectada envie mensagem para o número da sessão tenha certeza que o SOM de Notificações do seu celular esteja ligado você perceberá que o nenhum SOM será emitido. A notificação da mensagem aparece, pórem sem SOM..

#### Comportamento Esperado:
  **"always_online":** **false** Se essa opção estiver difinida como False ela o SOM das notificações do celular deveria ser emitido.

#### Comportamento Atual:
SOM de Notificações do celular ligado, pórem nenhum SOM é emitido ao receber mensagem do WhatsApp

#### Capturas de Tela/Vídeos:
Meu código 
![image](https://github.com/EvolutionAPI/evolution-api/assets/46387591/30ba93bc-7dfa-422b-a91c-e2a09fe06211)

Por padrão minhas sessões no manager mostram **Sempre Online** -  Desmarcada

![fcccf287-50c4-49ec-ba2d-21e469e059a6](https://github.com/EvolutionAPI/evolution-api/assets/46387591/1d76d780-82f0-4769-80b4-13415af4aeb5)

#### Ambiente:
- **Servidor:** [ex: Ubuntu 22.04] -
- **Versão da API:** [161/170/171] - Testei nessas
- **Outras Especificações de Hardware/Software:** [Docker Portainer]

#### Envio de Logs:
Sem Logs de Erros.

#### Notas Adicionais:
**PARA que o Som das notificações voltasse ao normal  eu fiz o seguinte:**
Entrei no MANAGER, vou na sessão em **Comportamento** eu marco a opção **Sempre Online** e salvo.
Em seguida eu **Desmarco** a opção e Salvo. E o SOM das notificações começam a serem emitidos.

**Comment by phtisp** [comment]
Por favor, classifique esta conversa, https://apiv2.xphsolution.com.br/survey/responses/81d6421e-9943-4717-9c1b-06fb08be53bf

**Comment by Erickjonatthan** [comment]
Não sei se ajuda, consegui resolver esse problema ao ver essa issue:
[https://github.com/WhiskeySockets/Baileys/issues/431#issuecomment-1758057135](url)

e colocando sock.sendPresenceUpdate('unavailable') no arquivo src/api/integrations/channel/whatsapp/whatsapp.baileys.service.ts

na função sendMessageWithTyping, antes do return messageRaw;

**Comment by jlenon7** [comment]
Para aqueles que caíram por aqui com esse problema, fiz uma implementação simples nessa classe que o @Erickjonatthan passou. Coloquei um `setInterval()` pra rodar toda vez que um client novo é criado. Logo abaixo de `this.client = makeWASocket(socketConfig);`:

```
# src/api/integrations/channel/whatsapp/whatsapp.baileys.service.ts:695

this.client = makeWASocket(socketConfig);

/**
 * Limpa o intervalo se já existir. Importante para casos 
 * de reconnect ao WhatsApp.
 */
if (this.presenceIntervalId) {
  clearInterval(this.presenceIntervalId);
}

/**
 * Cria um novo intervalo para atualizar a presença
 * a cada 5 minutos.
 */
this.presenceIntervalId = setInterval(() => {
  /**
   * Apenas atualiza a presença se a flag alwaysOnline estiver desabilitada.
   */
  if (!this.localSettings.alwaysOnline) {
    this.setPresence({ presence: 'unavailable' });
  }
}, 300000);
```

Lembrem também de adicionar essa nova propriedade la no topo da classe (`private presenceIntervalId: any = null`). E lembrem também de fazer o build do código para pegar as alterações.

**Comment by sostenesapollo** [comment]
estou usando somente o evolution manager, como resolve ?

**Comment by jilcimar** [comment]
> Para aqueles que caíram por aqui com esse problema, fiz uma implementação simples nessa classe que o [@Erickjonatthan](https://github.com/Erickjonatthan) passou. Coloquei um `setInterval()` pra rodar toda vez que um client novo é criado. Logo abaixo de `this.client = makeWASocket(socketConfig);`:
> 
> ```
> # src/api/integrations/channel/whatsapp/whatsapp.baileys.service.ts:695
> 
> this.client = makeWASocket(socketConfig);
> 
> /**
>  * Limpa o intervalo se já existir. Importante para casos 
>  * de reconnect ao WhatsApp.
>  */
> if (this.presenceIntervalId) {
>   clearInterval(this.presenceIntervalId);
> }
> 
> /**
>  * Cria um novo intervalo para atualizar a presença
>  * a cada 5 minutos.
>  */
> this.presenceIntervalId = setInterval(() => {
>   /**
>    * Apenas atualiza a presença se a flag alwaysOnline estiver desabilitada.
>    */
>   if (!this.localSettings.alwaysOnline) {
>     this.setPresence({ presence: 'unavailable' });
>   }
> }, 300000);
> ```
> 
> Lembrem também de adicionar essa nova propriedade la no topo da classe (`private presenceIntervalId: any = null`). E lembrem também de fazer o build do código para pegar as alterações.

Ainda não consegui alterar, estou com erro para fazer o build. Mas sigo tentando pois o problema está incomodando bastante.

**Comment by jilcimar** [comment]
> Para aqueles que caíram por aqui com esse problema, fiz uma implementação simples nessa classe que o [@Erickjonatthan](https://github.com/Erickjonatthan) passou. Coloquei um `setInterval()` pra rodar toda vez que um client novo é criado. Logo abaixo de `this.client = makeWASocket(socketConfig);`:
> 
> ```
> # src/api/integrations/channel/whatsapp/whatsapp.baileys.service.ts:695
> 
> this.client = makeWASocket(socketConfig);
> 
> /**
>  * Limpa o intervalo se já existir. Importante para casos 
>  * de reconnect ao WhatsApp.
>  */
> if (this.presenceIntervalId) {
>   clearInterval(this.presenceIntervalId);
> }
> 
> /**
>  * Cria um novo intervalo para atualizar a presença
>  * a cada 5 minutos.
>  */
> this.presenceIntervalId = setInterval(() => {
>   /**
>    * Apenas atualiza a presença se a flag alwaysOnline estiver desabilitada.
>    */
>   if (!this.localSettings.alwaysOnline) {
>     this.setPresence({ presence: 'unavailable' });
>   }
> }, 300000);
> ```
> 
> Lembrem também de adicionar essa nova propriedade la no topo da classe (`private presenceIntervalId: any = null`). E lembrem também de fazer o build do código para pegar as alterações.

Consegui resolver o bug mas não foi com essa solucação, aqui o que fiz foi definir o `markOnlineOnConnect: this.localSettings.alwaysOnline` para : 

```js
 markOnlineOnConnect: false,
```

**Comment by jilcimar** [comment]
Galera que está enfrentando esse problema, fiz uma imagem customizada solucionando o problema. 
```bash
jilcimar/evolution-api:v2.3.1-custom
`````

https://hub.docker.com/r/jilcimar/evolution-api/tags. .

Nessa imagem defini essas linhas (454-460)

```js
     // Força presença como unavailable após conexão para evitar mute das notificações
      setTimeout(async () => {
        try {
          await this.client.sendPresenceUpdate('unavailable');
        } catch (error) {
          this.logger.warn('Erro ao definir presença como unavailable');
        }
      }, 2000);
```
<img width="823" height="576" alt="Image" src="https://github.com/user-attachments/assets/b47f3630-21f8-49bb-9b72-d9e627b61cf9" />


Também defini o  `markOnlineOnConnect` sempre como `false` para garantir que essa flag seja marcada como `true` em algum mmomento. 

<img width="1004" height="406" alt="Image" src="https://github.com/user-attachments/assets/865b3697-8159-4db1-86c7-3fb1dca7a801" />

**Comment by NiceFeatures** [comment]
> Galera que está enfrentando esse problema, fiz uma imagem customizada solucionando o problema.
> 
> jilcimar/evolution-api:v2.3.1-custom
> 
> https://hub.docker.com/r/jilcimar/evolution-api/tags. .
> 
> Nessa imagem defini essas linhas (454-460)
> 
>      // Força presença como unavailable após conexão para evitar mute das notificações
>       setTimeout(async () => {
>         try {
>           await this.client.sendPresenceUpdate('unavailable');
>         } catch (error) {
>           this.logger.warn('Erro ao definir presença como unavailable');
>         }
>       }, 2000);
> 
> <img alt="Image" width="823" height="576" src="https://private-user-images.githubusercontent.com/34745276/484552237-b47f3630-21f8-49bb-9b72-d9e627b61cf9.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjgzMzgxMTgsIm5iZiI6MTc2ODMzNzgxOCwicGF0aCI6Ii8zNDc0NTI3Ni80ODQ1NTIyMzctYjQ3ZjM2MzAtMjFmOC00OWJiLTliNzItZDllNjI3YjYxY2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMTEzVDIwNTY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ZGIwNGRhM2ZjZGIyMGQyMTI0MWM4Yzg4YjJmYTQ5NmQ1ZTJiOGIyOGE3NWI3YTczYjBmZTI4OWI1NTRkZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gTiun9S3uBIKWW0NzAMJ_Dl976dKhyaSz-4pGs5Lesk">
> 
> Também defini o `markOnlineOnConnect` sempre como `false` para garantir que essa flag seja marcada como `true` em algum mmomento.
> <img alt="Image" width="1004" height="406" src="https://private-user-images.githubusercontent.com/34745276/484552852-865b3697-8159-4db1-86c7-3fb1dca7a801.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjgzMzgxMTgsIm5iZiI6MTc2ODMzNzgxOCwicGF0aCI6Ii8zNDc0NTI3Ni80ODQ1NTI4NTItODY1YjM2OTctODE1OS00ZGIxLTg2YzctM2ZiMWRjYTdhODAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMTEzVDIwNTY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZDUzY2I3YjdkODY0MTM3NGViNTMzMzdhYTA4MjE0ODYwOWNlYjUxM2M4ZDFhNWQ0MDViMTQ4NjhmZTBhY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cEft3nUfkb64Aqgz2VCuSib2fp5212EYzOScg879fa8">

Você ainda mantém essas correções? Estou com esse problema atualmente.
