### ISSUE TITLE
[PT][BUG] - FORMATO DE ARQUIVO PDF SENDO ENVIADO ERRADO [.BIN]

### ISSUE THREAD

**Issue by diluh** [EvolutionAPI/evolution-api#513]
#### Descrição:
Tenho uma aplicação que envia **faturas em PDF** para os clientes no WhatsApp. Estava usando Evolution Versão 1.6.1 e tudo estava sendo enviado corretamente.

Depois que atualizei para as versões 1.7.0 e 1.7.1 as faturas estão saindo com formato errado, ao invez de irem como PDF estão indo como formato **.bin**

#### Passos para Reproduzir:
1. Apos atualizei Evolution para 1.7.0 e 1.7.1 e o erro ocorreu

#### Comportamento Esperado:
Deveria enviar os arquivos no formato em PDF igual ocorre na versão 1.6.1

#### Comportamento Atual:
Arquivos em PDF estão saindo com formato **BIN** na versão 1.7.0 e 1.7.1

#### Capturas de Tela/Vídeos:

**Evolution 1.6.1**
![c15e60f1-8355-40fa-87a9-d6293f31eb53](https://github.com/EvolutionAPI/evolution-api/assets/46387591/378db354-4c96-414e-bb52-dd3c707af2d4)

**Evolution 1.7.1 e 1.7.1**
![bc1485c5-36c6-48d7-9e15-d7850e9d0296](https://github.com/EvolutionAPI/evolution-api/assets/46387591/333810b5-ce3c-4f6c-9500-1aac4da2fe14)

#### Ambiente:
Servidor: [ex: Ubuntu 22.04] -
Versão da API: [1.7.0/1.7.1] - Testei nessas
Outras Especificações de Hardware/Software: [Docker Portainer]

#### Envio de Logs:
Sem logs de erro

#### Notas Adicionais:

**Comment by jonathanokdas1** [comment]
Volta a versão que resolve, estava com o mesmo problema 
image: atendai/evolution-api:v1.6.1

**Comment by phtisp** [comment]
Por favor, classifique esta conversa, https://apiv2.xphsolution.com.br/survey/responses/4a9700a0-685d-4e1a-8da6-008247c2d9b9

**Comment by betovsp** [comment]
Atualizei até para a 1.7.3 e o erro persiste, só funciona com a 1.6.1 mesmo, tanto para pdf, quanto para arquivo zip,
Entendemos que as atualizações são para melhoria, e venho parabenizar o Davidson e equipe pelo projeto.
Aproveitando, quando será corrigido esse erro de arquivo que apesar das atualizações, somente na versão 1.6.1 funciona?

**Comment by williamblacky** [comment]
Aproveitando seu tópico para perguntar: Por que eu não consigo que arquivos PDFs sejam exibidos nas minhas conversas com o typebot dentro do WhatsApp?
Pelo link do typebot tudo flui normalmente, porém se a conversa ocorre dentro do whatsapp, os arquivos não aparecem e passa para a próxima mensagem. Preciso configurar algo dentro ou fora da API para que isso funcione?

**Comment by oLucasPopov** [comment]
> Aproveitando seu tópico para perguntar: Por que eu não consigo que arquivos PDFs sejam exibidos nas minhas conversas com o typebot dentro do WhatsApp? Pelo link do typebot tudo flui normalmente, porém se a conversa ocorre dentro do whatsapp, os arquivos não aparecem e passa para a próxima mensagem. Preciso configurar algo dentro ou fora da API para que isso funcione?

Conseguiu alguma solução pra isso? Estou com o mesmo problema

**Comment by oLucasPopov** [comment]
> > > Aproveitando seu tópico para perguntar: Por que eu não consigo que arquivos PDFs sejam exibidos nas minhas conversas com o typebot dentro do WhatsApp? Pelo link do typebot tudo flui normalmente, porém se a conversa ocorre dentro do whatsapp, os arquivos não aparecem e passa para a próxima mensagem. Preciso configurar algo dentro ou fora da API para que isso funcione?
> > 
> > 
> > Conseguiu alguma solução pra isso? Estou com o mesmo problema
> 
> eu também queria saber sobre isso

Não consegui resolver. O que eu fiz foi o seguinte:
Hospedei o arquivo PDF na cloudflare, quando há a necessidade de enviar um PDF pra algum usuário, eu envio uma requisição do typebot para a evolutionAPI `https://suaURLaqui/message/sendMedia/{{instanceName}}`.

![Image](https://github.com/user-attachments/assets/ddb678f4-0a0d-49ec-8e6e-62575a96f5cf)

**Comment by tech3br** [comment]
> > > > Aproveitando seu tópico para perguntar: Por que eu não consigo que arquivos PDFs sejam exibidos nas minhas conversas com o typebot dentro do WhatsApp? Pelo link do typebot tudo flui normalmente, porém se a conversa ocorre dentro do whatsapp, os arquivos não aparecem e passa para a próxima mensagem. Preciso configurar algo dentro ou fora da API para que isso funcione?
> > > 
> > > 
> > > Conseguiu alguma solução pra isso? Estou com o mesmo problema
> > 
> > 
> > eu também queria saber sobre isso
> 
> Não consegui resolver. O que eu fiz foi o seguinte: Hospedei o arquivo PDF na cloudflare, quando há a necessidade de enviar um PDF pra algum usuário, eu envio uma requisição do typebot para a evolutionAPI `https://suaURLaqui/message/sendMedia/{{instanceName}}`.
> 
> ![Image](https://github.com/user-attachments/assets/ddb678f4-0a0d-49ec-8e6e-62575a96f5cf)

será que não funciona hospedando o arquivo do drive? normalmente os clientes usam o drive para gerir os pdfs. eles não acessam o S3 da vida... rsrsrs

**Comment by oLucasPopov** [comment]
> > > > > Aproveitando seu tópico para perguntar: Por que eu não consigo que arquivos PDFs sejam exibidos nas minhas conversas com o typebot dentro do WhatsApp? Pelo link do typebot tudo flui normalmente, porém se a conversa ocorre dentro do whatsapp, os arquivos não aparecem e passa para a próxima mensagem. Preciso configurar algo dentro ou fora da API para que isso funcione?
> > > > 
> > > > 
> > > > Conseguiu alguma solução pra isso? Estou com o mesmo problema
> > > 
> > > 
> > > eu também queria saber sobre isso
> > 
> > 
> > Não consegui resolver. O que eu fiz foi o seguinte: Hospedei o arquivo PDF na cloudflare, quando há a necessidade de enviar um PDF pra algum usuário, eu envio uma requisição do typebot para a evolutionAPI `https://suaURLaqui/message/sendMedia/{{instanceName}}`.
> > ![Image](https://github.com/user-attachments/assets/ddb678f4-0a0d-49ec-8e6e-62575a96f5cf)
> 
> será que não funciona hospedando o arquivo do drive? normalmente os clientes usam o drive para gerir os pdfs. eles não acessam o S3 da vida... rsrsrs

Olha.. Não consegui fazer funcionar com o Drive não. Foi uma das minhas primeiras tentativas

Pelo que eu entendi, o drive é uma aplicação a separada que carrega o PDF dentro dela. Não há o retorno do PDF diretamente igual na CloudFlare. Por isso Não funcionou.

Pode ser que eu tenha feito algo errado, mas creio que não funcione mesmo kk
