### ISSUE TITLE
[EN][BUG] Can't send Message

### ISSUE THREAD

**Issue by mdestafadilah** [EvolutionAPI/evolution-api#514]
#### Description:
Everything working, just when hit send message API it's not show result as expecting.

#### Steps to Reproduce:
-

#### Expected Behavior:
it's look like in docs
> https://doc.evolution-api.com/docs/05-Endpoints/00-send-plain-text

#### Current Behavior:
-

#### Screenshots/Videos:
If possible, add screenshots or videos illustrating the problem. This can be extremely helpful in understanding the issue.

![04-04-2024 11-10-30](https://github.com/EvolutionAPI/evolution-api/assets/5575882/595ad214-e9d9-42e0-bf53-270e08a74be4)

#### Environment:
- **Server:** UBUNTU 20.04
- **API Version:** Latest
- **Other Hardware/Software Specifications:** [e.g., CPU, GPU]

#### Submitting Logs:
Please attach logs that may be related to the problem. If the logs contain sensitive information, consider sending them privately to one of the project maintainers.

#### Additional Notes:
Include here any other information that you think might be useful in understanding or resolving the bug.

**Comment by ip2cloud** [comment]
Hi. 

Do you send code country in number?

This erro is json estructure.

**Comment by mdestafadilah** [comment]
> Hi.
> 
> Do you send code country in number?
> 
> This erro is json estructure.

yes, with or without country code it's not working. other API working, just sending message not work. 

json default from documentation, any other structure?

**Comment by grupale** [comment]
try setting in number the cellphonenumber@s.whatsapp.net

![image](https://github.com/EvolutionAPI/evolution-api/assets/10934794/61af8d63-570e-4c88-aba9-35180a0cb849)

**Comment by phtisp** [comment]
Por favor, classifique esta conversa, https://apiv2.xphsolution.com.br/survey/responses/c92b860c-389b-431a-9723-3501ae2c21ba

**Comment by mdestafadilah** [comment]
> try setting in number the [cellphonenumber@s.whatsapp.net](mailto:cellphonenumber@s.whatsapp.net)
> 
> ![image](https://private-user-images.githubusercontent.com/10934794/320094224-61af8d63-570e-4c88-aba9-35180a0cb849.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODUxNDgsIm5iZiI6MTcxMjM4NDg0OCwicGF0aCI6Ii8xMDkzNDc5NC8zMjAwOTQyMjQtNjFhZjhkNjMtNTcwZS00Yzg4LWFiYTktMzUxODBhMGNiODQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA2MjcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNjlkMTA5NDkwZDdjZWVlNzUxNDRlOTM2MjhjMWI5ZmIwYTExMjZmZmQwN2QzZThjNzAyZWViZWFiMjc4MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V2OQ4xbiUmsbwmNCmUvvOtFaIxLwq-eSd5-IKClPEGk)

not luck. :(
