### ISSUE TITLE
[PT][BUG] TYPEBOT/EVOLUTION BOT SEM FREIO, SEMPRE RETORNA PARA O INICIO.

### ISSUE THREAD

**Issue by moanemanuel** [EvolutionAPI/evolution-api#515]
#### Descrição:
Nas versões anteriores, na configuração chamada post funcionava bem, com uma pausa de 40minutos para parar o bot no fim do fluxo:

configuração
"enabled": false,
    "url": "xxx",
    "typebot":  "xxx",
    "expire": 40,
    "keyword_finish": "#SAIR",
    "delay_message": 1000,
    "unknown_message": "",
    "listening_from_me": false

Agora ele ignora o "expire": 40 ou seja, no fim daquela etapa, o bot não para os 40 minutos, retornando para o começo.

#### Comportamento Esperado:
Pausar/frear no o bot no tempo desejado, no exemplo: "expire": 40

**Comment by luiis716** [comment]
o que o @moanemanuel deve ta falando foi que descobrir agora tarde, como mostro do fluxo abaixo simples com 2 etapa
![Imagem do WhatsApp de 2024-04-05 à(s) 15 36 52_966726cc](https://github.com/EvolutionAPI/evolution-api/assets/97978347/3153947d-7362-4509-a98b-36a0714e840c)


no caso e usado o http famoso endpoint para pausa o typebot mais quando chega no grupo 6 como ta acima ele fecha e retorma o fluxo do inicio como ta abaixo

![Imagem do WhatsApp de 2024-04-05 à(s) 15 39 48_b40b3896](https://github.com/EvolutionAPI/evolution-api/assets/97978347/45707db8-e0b1-4726-898d-505cba88375e)

**Comment by phtisp** [comment]
Por favor, classifique esta conversa, https://apiv2.xphsolution.com.br/survey/responses/0ef7488b-b4c8-4433-8365-9873c89695e3
