### ISSUE TITLE
[PT][FEAT] SUGESTÃO: Possibilidade de apresentar botões do typebot como enquetes no whatsapp

### ISSUE THREAD

**Issue by lariguedes98** [EvolutionAPI/evolution-api#516]
### **Possibilidade de apresentar botões do typebot como enquetes no whatsapp**

![Screenshot_292](https://github.com/EvolutionAPI/evolution-api/assets/109113901/bbaa47d4-11cd-4f4c-9e72-8f43d926aa64)

![Screenshot_291](https://github.com/EvolutionAPI/evolution-api/assets/109113901/ba8ccb6a-8e77-4f2d-8349-584f7105162c)

#### Descrição Detalhada:

Sabendo que a opção de utilizar botões no whatsapp trata-se de um recurso pago da api oficial, o que pode acabar pesando contra sua utilização por conta do custo benefício, eu estava buscando alternativas que facilitassem a vida do cliente quanto a forma de como os botões do typebot são apresentados no whatsapp. Penso que digitar a opção é algo simples, mas pode causar certa confusão dependendo do tipo de público que está sendo atendido.

Com isso em mente, estava fazendo testes em uma outra api com base na whatsappweb.js e acabei me deparando com a seguinte função: a possibilidade de apresentar botões do typebot como enquetes no chat do whatsapp (confira nas fotos anexadas).

Assim que a opção na enquete é selecionada, o fluxo segue como se o botão tivesse sido clicado e há ainda a possibilidade da enquete ser apagada (mensagem apagada) logo após a opção ser selecionada para que não seja possível o cliente voltar e selecionar outra opção ali, uma vez que o fluxo já seguiu, evitando possíveis confusões no fluxo.

Seria viável implementar algo assim na Evolution API? Particularmente, achei uma alternativa interessante.

**Comment by calltomillion** [comment]
Muito bom sua ideia, se conseguirmos essa melhoria, vai ser um grande avanço para nós!

**Comment by phtisp** [comment]
Por favor, classifique esta conversa, https://apiv2.xphsolution.com.br/survey/responses/6ae973a3-1207-4c7b-a50b-f17e3c9a8165

**Comment by DevWizarddz** [comment]
Toppp demais, se houver esse aprimoramento será de grande avanço para nós.

Super apoio!

**Comment by ByyteBrewer** [comment]
Muito boa sua ideia

**Comment by AlgorithmAcer** [comment]
Great initiative! Simplifying user interactions on WhatsApp can significantly enhance user experience. Implementing Typebot buttons as polls is a smart approach. Looking forward to seeing how it progresses.
