### ISSUE TITLE
[PT][BUG]  [typebot esta fechando sessões sozinho]

### ISSUE THREAD

**Issue by luiis716** [EvolutionAPI/evolution-api#518]
#### Descrição:
quando fluxo iniciado como mostro abaixo  tem 2 caixa de texto, antis no grupo 6 ele ficava enviando o que coloquei la no caso ali ta imprimindo o meu numero,
![Imagem do WhatsApp de 2024-04-05 à(s) 15 36 52_966726cc](https://github.com/EvolutionAPI/evolution-api/assets/97978347/ee524788-8039-4c1f-b1b5-6eca5093eaa7)

 so que agora ele ta fechando e iniciando do começo. como mostro a baixo:
![Imagem do WhatsApp de 2024-04-05 à(s) 15 39 48_b40b3896](https://github.com/EvolutionAPI/evolution-api/assets/97978347/a4eb76c4-e933-4447-988b-12ba743e4fc1)

#### Ambiente:
- **Servidor:** ubunto 24.0
- **Versão da API:1.7.1

**Comment by phtisp** [comment]
Por favor, classifique esta conversa, https://apiv2.xphsolution.com.br/survey/responses/2c93096b-5acf-4a57-9fbe-7a14abf65341

**Comment by guibarbas** [comment]
Olá @luiis716  boa tarde.

Testou aplicar as opções abaixo?
![image](https://github.com/EvolutionAPI/evolution-api/assets/47323533/c349b534-b67e-4d3f-a59e-1f202292f9ac)

Aqui aconteceu o mesmo comigo, entretanto, ao aplicar 
- TYPEBOT_KEEP_OPEN=true
Resolveu

**Comment by luiis716** [comment]
@guibarbas tou usando a versão web do typebot

**Comment by guibarbas** [comment]
> @guibarbas tou usando a versão web do typebot

Opa mestre, isso deve ser aplicado na sua stack da EvolutionAPI.
Não no Typebot.

Tente realizar o teste, do contrario, envie os logs aqui também. "neste caso, da Evo, já que o Type é o oficial"
Isso ajuda muito à identificar os erros.

**Comment by luiis716** [comment]
no meu stack so tem 

# This events is used with Typebot
WEBHOOK_EVENTS_TYPEBOT_START=false
WEBHOOK_EVENTS_TYPEBOT_CHANGE_STATUS=false
