### ISSUE TITLE
[PT][BUG][Pause the flow do Wait parando fluxo]

### ISSUE THREAD

**Issue by jhonyrsy** [EvolutionAPI/evolution-api#519]
Título: [Pause the flow do Wait parando fluxo]

Descrição:
Quando executamos o fluxo do Typebot na web e habilitamos o Pause the flow do Wait o fluxo ocorre normalmente, porem quando inicio o fluxo pelo WhatsApp com Pause the flow Habilitado o fluxo se encerra e não executa  os demais blocos do Typebot. Na versão web do Typebot ele intende que se o Wait  estiver como 2 segundos ele aguarda e depois continua o fluxo, já no WhatsApp  quando ele chega no Wait  com Pause the flow ele encerra o fluxo e começa do inicio.

![bugWait](https://github.com/EvolutionAPI/evolution-api/assets/90047776/5db99b4b-55c2-4a5e-9a84-aac93cbcca58)

Ambiente:
Servidor: [Ubuntu 20.04]
Versão da API: [1.7.0]

**Comment by AnxHall** [comment]
A função se comporta da seguinte forma

se a opção "Pause the flow" estiver marcada ele ira parar ate que o usuario mande alguma mensagem, no caso como não tem outro bloco ele identifica que finalizou e vai reiniciar no seu caso, separe esse bloco da N8N para que ele continue para essa função

caso queira so aguardar 3 segundos e que a função httprequest rode, desmarca essa opção de pause the flow ...

Simples

**Comment by yagoylc** [comment]
Mesmo problema aqui. Fiz um cenário para exemplificar melhor.

Ubuntu: 22.04.3 
Evo: 1.7.4
Typebot: 2.25.0 
N8N: 1.40.0 
Ambiente: Docker

Fluxo typebot

![image](https://github.com/EvolutionAPI/evolution-api/assets/22221437/a9657c8b-c33d-4bc8-a481-1b1d1926d035)

Requisição sendo feita corretamente por dentro do typebot.

![image](https://github.com/EvolutionAPI/evolution-api/assets/22221437/442c7aaa-de06-4332-9ea7-3f8eef870be2)

Webhook criado no N8N apenas para simulação:

![image](https://github.com/EvolutionAPI/evolution-api/assets/22221437/0430deca-9b5a-4c2b-a9a5-ac9db859e58f)

Resultado na integração da Evolution

![image](https://github.com/EvolutionAPI/evolution-api/assets/22221437/4644dbc5-a663-4a1d-a2f1-9f0805f25e35)

Arquivos de importação dos exemplos

[n8n.json](https://github.com/EvolutionAPI/evolution-api/files/15237236/n8n.json)
[typebot.json](https://github.com/EvolutionAPI/evolution-api/files/15237237/typebot.json)
