### ISSUE TITLE
Docker retorna erro Axios criando instancia chatwoot 1.4.8

### ISSUE THREAD

**Issue by mauriciomagalhaes** [EvolutionAPI/evolution-api#52]
Olá , primeiramente excelente trabalho! 

Instalei em um docker porem ao enviar o post para criar a instancia ele da erro em um objeto
![image](https://github.com/EvolutionAPI/evolution-api/assets/28632649/064abfe9-912f-462f-be42-76ad9d07ad3a)

**Comment by DavidsonGomes** [comment]
Mostra o erro do axios completo, nao da pra saber que erro é

**Comment by mauriciomagalhaes** [comment]
Desculpa, pensei que tinha printado tudo!
![image](https://github.com/EvolutionAPI/evolution-api/assets/28632649/525c3963-f854-4674-968b-0ea6e6514d18)

**Comment by mauriciomagalhaes** [comment]
Instalei Evolution vi npm com o chatwoot e o mesmo problema ocorre. vou tentar uma versao anterior

**Comment by DavidsonGomes** [comment]
Teste utilizar a api do chatwoot via postman para ver se tem o mesmo erro

**Comment by mauriciomagalhaes** [comment]
Estou usando o POSTMAN,  quando uso o parametro JSON "chatwoot_url": "192.168.52.20:3000", dá o erro acima

se colocar "chatwoot_url": "http://192.168.52.20:3000",


[Evolution API]  1   -  Thu Aug 03 2023 19:21:57     ERROR   [unhandledRejection]  [object]   
{
  origin: Promise {
    <rejected> AxiosError: connect EADDRNOTAVAIL ::1:80 - Local (:::0)
        at internalConnect (node:net:1041:16)
        at defaultTriggerAsyncIdScope (node:internal/async_hooks:464:18)
        at node:net:1134:9
        at processTicksAndRejections (node:internal/process/task_queues:78:11) {
      port: 80,
      address: '::1',
      syscall: 'connect',
      code: 'EADDRNOTAVAIL',
      errno: -99,
      config: [Object],
      request: [Writable]
    }
  },
  stderr: 2,
  error: AxiosError: connect EADDRNOTAVAIL ::1:80 - Local (:::0)
      at internalConnect (node:net:1041:16)
      at defaultTriggerAsyncIdScope (node:internal/async_hooks:464:18)
      at node:net:1134:9
      at processTicksAndRejections (node:internal/process/task_queues:78:11) {
    port: 80,
    address: '::1',
    syscall: 'connect',
    code: 'EADDRNOTAVAIL',
    errno: -99,
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object],
      url: 'http//192.168.52.20:3000/api/v1/accounts/1/inboxes',
      method: 'get',
      withCredentials: true,
      cancelToken: [CancelToken],
      data: undefined
    },
    request: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [ClientRequest],
      _currentUrl: 'http//192.168.52.20:3000/api/v1/accounts/1/inboxes',
      [Symbol(kCapture)]: false
    }
  }
} 



PS.: So acontece em docker, instalei no ubuntu 22.04 via NPM, funciona normalmente

**Comment by willsza** [comment]
Acontece esse mesmo erro pra mim verificando nos logs do container... porém recebo 200 no postman informando que a caixa foi cridada com sucesso mas não aparece no Chatwoot.
