### ISSUE TITLE
[PT][BUG] No typebot ele só identifica o messageType uma vez no início da sessão

### ISSUE THREAD

**Issue by juniorgregio** [EvolutionAPI/evolution-api#521]
#### Descrição:
Ao realizar testes na versão 1.7.1 identifiquei que só é possível identificar o messageType no typebot quando o usuário inicia a primeira interação.
Por exemplo:
Usuário envia uma mensagem de texto.
Typebot diz que é messageType conversation.

Usuário inicia uma interação nova, após encerrar a primeira sessão:
Usuário envia uma mensagem de texto e na sequência envia um vídeo, o messageType permanece como conversation

#### Passos para Reproduzir:
1. Crie um fluxo no typebot:
1.1. Coloque no fluxo para capturar no início da interação do usuário qual o {{messageType}} que ele enviou;
1.2. Na continuação do fluxo, você coloca um retorno para ele, exemplo: "Bem vindo, por favor me envie uma imagem, vídeo ou documento";
1.3. Coloque ou um input para capturar o que ele envia ou já coloca antes ou depois o bloco de váriavel setando para capturar o tipo da mensagem {{messageType}}
1.4. Coloque para imprimir o messageType.
1.5. Irá verificar que se o usuário enviou uma mensagem de texto no começo, ficará como conversation mesmo que ele envie depois um arquivo.

#### Comportamento Esperado:
O certo seria ele enviar para o typebot o messageType de toda mensagem.

#### Comportamento Atual:
O primeiro messageType enviado fica com persistência.

#### Capturas de Tela/Vídeos:
![evidencia2](https://github.com/EvolutionAPI/evolution-api/assets/37232274/ebf72e37-3f0c-4c59-9dce-eb684193a802)
![evidencia1](https://github.com/EvolutionAPI/evolution-api/assets/37232274/376dbb81-b2de-404d-9ff5-f8df968d6119)

#### Ambiente:
- **Servidor:** Ubuntu 20.04
- **Versão da API:** 1.7.1
- **Outras Especificações de Hardware/Software:** 2vcpu 8ram 

#### Envio de Logs:
Por favor, anexe os logs que possam estar relacionados ao problema. Se os logs contiverem informações sensíveis, considere enviá-los de forma privada para um dos mantenedores do projeto.

#### Notas Adicionais:
Inclua aqui qualquer outra informação que você ache que possa ser útil para entender ou resolver o bug.

**Comment by rafaelaabreuaq** [comment]
Conseguiu alguma solução para isso?

**Comment by juniorgregio** [comment]
> Conseguiu alguma solução para isso?

Infelizmente não

**Comment by juniorgregio** [comment]
> Conseguiu alguma solução para isso?

Infelizmente não

**Comment by rafaelaabreuaq** [comment]
Fiz essa gambiarra aqui, amigo:

![image](https://github.com/EvolutionAPI/evolution-api/assets/164689589/287a31a0-cdfc-4492-a9df-151f37b20e3d)

Quando tu exibe a mensagem coletada num input de texto [no caso no segundo bloco, o 1msg], ele te apresenta um link encriptado quando a msg se trata de mídias (imagem, vídeo, áudio e gif), esse link aparentemente tem um padrão que se conserva tipo:

Quando se trata de imagem o link contém "up-oil-image-"
Quando se trata de áudio o link contém "t62.7117-"
Quando se trata de vídeo o link contém "t62.7161-"
Quando se trata de um gif o link contém "up-oil-gif-"
Quando se trata de um doc pdf, ele não exibe link nenhum, mas exibe o nome do arquivo.pdf, então é só colocar ".pdf"

Não testei com outros tipos como localização, etc. Mas essa gambiarra já deve servir pra algo xD

**Comment by juniorgregio** [comment]
Interessante! Gostei da dica, vou aplicar

**Comment by juniorgregio** [comment]
> Fiz essa gambiarra aqui, amigo:
> 
> ![image](https://private-user-images.githubusercontent.com/164689589/327970540-287a31a0-cdfc-4492-a9df-151f37b20e3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4ODIwNTMsIm5iZiI6MTcxNDg4MTc1MywicGF0aCI6Ii8xNjQ2ODk1ODkvMzI3OTcwNTQwLTI4N2EzMWEwLWNkZmMtNDQ5Mi1hOWRmLTE1MWYzN2IyMGUzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQwNDAyMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzU2MmIxYWRlZjBlYWFjZWZlYTIwMjE5MmU5ZWFkOTBmZWJhODI1ZmNkMzU4ZTRjNzkwNGE3M2Q0NDUzNTM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ke5Z9bN1Qpwn5Hz0wm2HeBV2iy8I7pvSLyFTRfP4_LM)
> 
> Quando tu exibe a mensagem coletada num input de texto [no caso no segundo bloco, o 1msg], ele te apresenta um link encriptado quando a msg se trata de mídias (imagem, vídeo, áudio e gif), esse link aparentemente tem um padrão que se conserva tipo:
> 
> Quando se trata de imagem o link contém "up-oil-image-" Quando se trata de áudio o link contém "t62.7117-" Quando se trata de vídeo o link contém "t62.7161-" Quando se trata de um gif o link contém "up-oil-gif-" Quando se trata de um doc pdf, ele não exibe link nenhum, mas exibe o nome do arquivo.pdf, então é só colocar ".pdf"
> 
> Não testei com outros tipos como localização, etc. Mas essa gambiarra já deve servir pra algo xD

Obrigado pela dica, vou testar. Espero que façam essa correção pois isso torna gambiarras necessárias e transforma o código complexo
@luizeof @Azzybot @DavidsonGomes
