### ISSUE TITLE
[PT][BUG] Bloco Wait do Typebot não pausa corretamente

### ISSUE THREAD

**Issue by stgcompany** [EvolutionAPI/evolution-api#522]
#### Descrição:
Um cliente precisa de um delay entre um áudio e uma mensagem, mas infelizmente o bloco "Wait" não funciona corretamente com o evolution, o fluxo segue sem a pausa.

#### Passos para Reproduzir:
1. Crie um typebot com um bloco de pausa entre duas mensagens
2. Veja que ele envia ambas as mensagens sem o delay entre elas

#### Comportamento Esperado:
Deveria esperar o tempo para poder seguir com o fluxo e enviar as mensagens após o bloco de espera.

#### Comportamento Atual:
O fluxo continua sem pausa.

#### Capturas de Tela/Vídeos:
---

#### Ambiente:
- **Servidor:** Ubuntu 20.04
- **Versão da API:** 1.6.1
- **Outras Especificações de Hardware/Software:** 8cores 16ram

#### Envio de Logs:
---

#### Notas Adicionais:
Tentei usar o bloco do n8n para pausar o fluxo com um http request, mas também não resolveu o problema

**Comment by gabrielgranado** [comment]
Pelo que entendi do typebot esse é o comportamento esperado, veja o o video na documentação: https://docs.typebot.io/editor/blocks/integrations/webhook

Você tentou setar a opção "pause the flow" disponível no bloco wait? 

De qualquer forma, no meu entendimento, este comportamento é do typebot e não um bug da evo.
