### ISSUE TITLE
[PT][BUG] sendList no Chatwoot enviando dados da requisição ao invés do texto simples.

### ISSUE THREAD

**Issue by guibarbas** [EvolutionAPI/evolution-api#524]
#### Descrição:
Atualmente, estou realizando um teste simples de menu de opções, utilizando o sendList da Evolution dentro do Typebot.
Tudo esta funcionando 90% no Whatsapp (com exceção à formatação que esta gerando um pequeno erro ao qual detalho melhor abaixo). Entretanto, o maior problema esta ocorrendo dentro do Chatwoot.
As mensagens disparadas pelo "bot", estão vindo com informações da construção da lista.
Abaixo vou detalhar melhor, com prints os problemas.

#### Passos para Reproduzir:
1. Crie um modelo no Typebot, que realiza uma requisição do tipo POST na API da Evolution, seguindo os parâmetros estabelecidos pela Evolution no seu Postman.
2. Construa o modelo do sendList com a formatação desejada (negrito, itálico e etc)
3. Conecte a instancia da Evolution ao Typebot e ao Chatwoot e envie uma mensagem de teste.

#### Comportamento Esperado:
O comportamento correto seria o envio do menu de opções, com a formatação desejada, sem falhas no Whatsapp.
Dento do Chatwoot, o ideal seria receber o texto da mensagem exatamente como o é enviado ao Whatsapp.

#### Comportamento Atual:
Dentro do Whatsapp, é possível notar que a pré-visualização da mensagem exibe a formatação do texto, com * _ e etc.
Print: Formatação Whats Preview

Já no Chatwoot, o texto enviado pelo bot, esta sendo carregado com diversas informações da montagem da lista.
Print: Chatwoot bot textos

#### Capturas de Tela/Vídeos:
**Formatação Whats Preview**
![image](https://github.com/EvolutionAPI/evolution-api/assets/47323533/cdcdab59-70f3-4573-8bbe-3ce8f2408c1a)

**Chatwoot bot textos**
![image](https://github.com/EvolutionAPI/evolution-api/assets/47323533/15c0646d-aaad-431e-b4e4-71ee801cb323)
![image](https://github.com/EvolutionAPI/evolution-api/assets/47323533/7165ab09-7063-46f5-a740-c6b53c61c1b0)

#### Ambiente:
- **Servidor:** Debian 12
- **Versão da API:** 1.7.1
- **Versão do Chatwoot:** 3.7.0
- **Versão do Typebot:** 2.24.1

#### Envio de Logs:
Por gentileza, me acionem para que eu possa lhes enviar os Logs diretamente, se forem necessários.

#### Notas Adicionais:
Se precisarem de qualquer informação, basta me informar.
Estou com um ambiente em modo teste, preparado para estes eventos, antes de aplicar em produção.

Este recurso seria fantástico e gostaria de saber se é uma limitação/incompatibilidade ou se é alguma falha ou erro em minha configuração.

Agradeço à todos

**Comment by renansalvador** [comment]
Estou com a mesma situação.
