### ISSUE TITLE
[PT][BUG] API evolution não conecta com o Chatwoot

### ISSUE THREAD

**Issue by PedroReckelEL** [EvolutionAPI/evolution-api#525]
#### Descrição:
Estou tentando conectar a API do evolution no chatwoot porém não estou conseguindo, mesmo seguindo o passo a passo informado dentro do evolution manager.

#### Passos para Reproduzir:
1.  Conectar a conta do chatwoot dentro do evolution manager.
2. Dentro do chatwoot configurar o nome da caixa e o webhook.

#### Comportamento Esperado:
Era esperado que o chatwoot conectasse com a API de evolution.

#### Comportamento Atual:
Após conectar a conta do chatwoot no evolution API o evolution manager dá um erro "{ "status": 422, "error": "Internal Server Error", "response": { "message": "Generic Error" } }" conforme a imagem abaixo:
![image](https://github.com/EvolutionAPI/evolution-api/assets/155850969/1cd44905-0a1d-4d52-a01d-79a8348e05df)

A outra opção que eu segui foi configurar direto no chatwoot a integração conforme passado na sessão "Como configurar o chatwoot?" dentro do Manager. Após terminar a configuração do lado do chatwoot o nome da caixa de entrada que eu cadastrei até aparece, porém não aparece a parte do qrcode ou alguma confirmação que a instancia está conectada.
![image](https://github.com/EvolutionAPI/evolution-api/assets/155850969/c2ca6235-5540-470d-8b7f-42c14b08a0ad)
![image](https://github.com/EvolutionAPI/evolution-api/assets/155850969/42677c92-6b34-4680-ac25-3fa04f355d98)
![image](https://github.com/EvolutionAPI/evolution-api/assets/155850969/ac26176c-df9c-43f8-a734-326e9a5c5e1e)

Quando testei o link do webhook que foi disponibilizado pelo Manager na sessão de "Como configurar o chatwoot?" no meu navegador ele retornou erro 404: {"status":404,"error":"Not Found","response":{"message":["Cannot GET /chatwoot/webhook/PrefeituraTeste_ServicosOnLine"]}}

Fiz então o teste no postman fazendo uma requisição do tipo POST para a URL e esse foi o resultado:
![image](https://github.com/EvolutionAPI/evolution-api/assets/155850969/e769695c-95dd-490d-a721-84c908d663ef)

Após realizar a requisição para essa URL voltei ao chatwoot porém nada tinha acontecido.

Gostaria de saber se os senhores analisando essas informações podem me dizer o que pode estar faltando em minha aplicação.

#### Ambiente:
- **Servidor:** [Ubuntu 22.04.3 LTS]
- **Versão da API:** [v1.7.0]
- **Versão Chatwoot:** [v3.7.0]

#### Envio de Logs:

Logs do meu evolution API:
![image](https://github.com/EvolutionAPI/evolution-api/assets/155850969/1d1fc6c6-dec2-43e5-89c9-9f84a7014609)

Logs do chatwoot:
[_chatwoot-rails-1_logs.txt](https://github.com/EvolutionAPI/evolution-api/files/14919263/_chatwoot-rails-1_logs.txt)

**Comment by pedrotecinf** [comment]
Estou com mesmo erro porém na versão 1.7.1
a evo até cria a caixa no chatwoot porem não conecta a instancia 
Abaixo está o log
![captura tela erro 422 evolution](https://github.com/EvolutionAPI/evolution-api/assets/13740381/76d19618-5845-4346-a22d-85d14e2b1bc0)

**Comment by michaelvips** [comment]
Quando se conecta/cria uma conta do chatwoot no manager do evolution não se pode / precisa configurar dentro do chatwoot o nome da caixa e o webhook, isso é feito automaticamente, pelo manager.

E isso até o momento não é um bug, se é um problema que você tem deve ser tratado na comunidade, seria um bug se todos tivesse com esse erro o que não é o caso logo, ¨ainda¨ não é um bug.

**Comment by PedroReckelEL** [comment]
Sim, Michael. Eu criei um imbox lá no chatwoot para ver se daria certo a comunicação com o evolution, mas primeiramente configurei no evolution manager, porém infelizmente o meu não passa dai, após configurar a conexão com o chatwoot o manager me passa essa mensagem:

![image](https://github.com/EvolutionAPI/evolution-api/assets/155850969/6f672721-405d-40ec-93e2-528a71854bb9)

**Comment by michaelvips** [comment]
O seu chatwoot está nesse dominio https•W8fa77ce52848.ngrok.app ?

**Comment by PedroReckelEL** [comment]
Esse print que te mandei é antigo, agora está no https://165dcc3e0378.ngrok.app/

![image](https://github.com/EvolutionAPI/evolution-api/assets/155850969/ca3e8317-2468-4107-b757-8e83ee74593e)

**Comment by michaelvips** [comment]
Esse é o endpoint pra criar uma caixa de entrada, creio que você esta tentando criar um webhook.

![image](https://github.com/EvolutionAPI/evolution-api/assets/21130174/270b041a-12c1-4ae5-a4af-1d3d95bc1710)

**Comment by jaison-x** [comment]
> Estou com mesmo erro porém na versão 1.7.1 a evo até cria a caixa no chatwoot porem não conecta a instancia Abaixo está o log ![captura tela erro 422 evolution](https://private-user-images.githubusercontent.com/13740381/321527655-76d19618-5845-4346-a22d-85d14e2b1bc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMDEwODMsIm5iZiI6MTcxMzMwMDc4MywicGF0aCI6Ii8xMzc0MDM4MS8zMjE1Mjc2NTUtNzZkMTk2MTgtNTg0NS00MzQ2LWEyMmQtODVkMTRlMmIxYmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDIwNTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZjc1YzRlODA1ZmI2NDZmOTNkZjYzZWI0MzYyYzlmOGQ3ZGZkOWFlMzAwYzAwZjY2OGM5NTE5ZDI4MjJmZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.359Z7X9cd0ceRSEFeNO4mTows4JaaSZ2cEOrN9dJKV4)

Qual versão do CW está usando? Acho que este problema está ocorrendo na versão development. Este problema deve ocorrer na versão 3.8.0 mas ainda não testei ela.

**Comment by tasfw** [comment]
> ### Título: API evolution não conecta com o Chatwoot
> #### Descrição:
> 
> Estou tentando conectar a API do evolution no chatwoot porém não estou conseguindo, mesmo seguindo o passo a passo informado dentro do evolution manager.
> #### Passos para Reproduzir:
> 
>     1. Conectar a conta do chatwoot dentro do evolution manager.
> 
>     2. Dentro do chatwoot configurar o nome da caixa e o webhook.
> 
> 
> #### Comportamento Esperado:
> 
> Era esperado que o chatwoot conectasse com a API de evolution.
> #### Comportamento Atual:
> 
> Após conectar a conta do chatwoot no evolution API o evolution manager dá um erro "{ "status": 422, "error": "Internal Server Error", "response": { "message": "Generic Error" } }" conforme a imagem abaixo: ![image](https://private-user-images.githubusercontent.com/155850969/320858316-1cd44905-0a1d-4d52-a01d-79a8348e05df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDU1ODEsIm5iZiI6MTcxMzQwNTI4MSwicGF0aCI6Ii8xNTU4NTA5NjkvMzIwODU4MzE2LTFjZDQ0OTA1LTBhMWQtNGQ1Mi1hMDFkLTc5YTgzNDhlMDVkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwMTU0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTFhMjg4NzVmYzBhODdjNjUwYWFkMzc5N2Y2YWQ4NWY5NmY2ZjhjOTM2MzFiNmMzMWY3ZTg5Y2M3YjJiZjA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iWNu3uVubMfUgnHkQmzqA8M-BSffzE_tlvI_on_iAAI)
> 
> A outra opção que eu segui foi configurar direto no chatwoot a integração conforme passado na sessão "Como configurar o chatwoot?" dentro do Manager. Após terminar a configuração do lado do chatwoot o nome da caixa de entrada que eu cadastrei até aparece, porém não aparece a parte do qrcode ou alguma confirmação que a instancia está conectada. ![image](https://private-user-images.githubusercontent.com/155850969/320861761-c2ca6235-5540-470d-8b7f-42c14b08a0ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDU1ODEsIm5iZiI6MTcxMzQwNTI4MSwicGF0aCI6Ii8xNTU4NTA5NjkvMzIwODYxNzYxLWMyY2E2MjM1LTU1NDAtNDcwZC04YjdmLTQyYzE0YjA4YTBhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwMTU0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWZhOTlmMWIyYzdlMGE4ODM2M2MxMWQ2ZjliMDA3NTY4MGQwNjk2N2I3NDg3ODZlMzk0ZTYxZTZlNmE3YTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zea56WzTHvQk7CkcQNCNBIYAjE1HGt5PqJ532KAAOaM) ![image](https://private-user-images.githubusercontent.com/155850969/320861895-42677c92-6b34-4680-ac25-3fa04f355d98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDU1ODEsIm5iZiI6MTcxMzQwNTI4MSwicGF0aCI6Ii8xNTU4NTA5NjkvMzIwODYxODk1LTQyNjc3YzkyLTZiMzQtNDY4MC1hYzI1LTNmYTA0ZjM1NWQ5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwMTU0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzUyMjI5MTUyZmM5NzdmYzZmNzY4ZGQ1YThlMTkxNTc1YWVlYTFiMWRjODM4NTQyOGNlY2EzNzkyMzUxMzBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.39aw_mb6J0VaQ2XFm3lLo-7URBCOX4cyjBcY8veQkJM) ![image](https://private-user-images.githubusercontent.com/155850969/320862054-ac26176c-df9c-43f8-a734-326e9a5c5e1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDU1ODEsIm5iZiI6MTcxMzQwNTI4MSwicGF0aCI6Ii8xNTU4NTA5NjkvMzIwODYyMDU0LWFjMjYxNzZjLWRmOWMtNDNmOC1hNzM0LTMyNmU5YTVjNWUxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwMTU0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGM3YzJiMDdhMzIxOTViNzJlOTU2YjEzYTQ2NDgzNGY4YzI0NWEyNzQxMzU2MDMyNmYxMmQ4OTAzNTgyNDkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TQPr_zGS__AeitcCoJ8UzpoJOcTQqfjfvVWupIY55hU)
> 
> Quando testei o link do webhook que foi disponibilizado pelo Manager na sessão de "Como configurar o chatwoot?" no meu navegador ele retornou erro 404: {"status":404,"error":"Not Found","response":{"message":["Cannot GET /chatwoot/webhook/PrefeituraTeste_ServicosOnLine"]}}
> 
> Fiz então o teste no postman fazendo uma requisição do tipo POST para a URL e esse foi o resultado: ![image](https://private-user-images.githubusercontent.com/155850969/320863556-e769695c-95dd-490d-a721-84c908d663ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDU1ODEsIm5iZiI6MTcxMzQwNTI4MSwicGF0aCI6Ii8xNTU4NTA5NjkvMzIwODYzNTU2LWU3Njk2OTVjLTk1ZGQtNDkwZC1hNzIxLTg0YzkwOGQ2NjNlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwMTU0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzFkZjFkZWI0NmIwNTgzMjA2MDY0MjA1NWI5MGY2Nzc3NGFhZDE5MTcxZjM2N2M3NWY2NzMxNjExN2Q3MDgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6mss4Vuf3rj41GBX4MeyS0vj6SSCV2tZ5h7_ys6NZX4)
> 
> Após realizar a requisição para essa URL voltei ao chatwoot porém nada tinha acontecido.
> 
> Gostaria de saber se os senhores analisando essas informações podem me dizer o que pode estar faltando em minha aplicação.
> #### Ambiente:
> 
>     * **Servidor:** [Ubuntu 22.04.3 LTS]
> 
>     * **Versão da API:** [v1.7.0]
> 
>     * **Versão Chatwoot:** [v3.7.0]
> 
> 
> #### Envio de Logs:
> 
> Logs do meu evolution API: ![image](https://private-user-images.githubusercontent.com/155850969/320866697-1d1fc6c6-dec2-43e5-89c9-9f84a7014609.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDU1ODEsIm5iZiI6MTcxMzQwNTI4MSwicGF0aCI6Ii8xNTU4NTA5NjkvMzIwODY2Njk3LTFkMWZjNmM2LWRlYzItNDNlNS04OWM5LTlmODRhNzAxNDYwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwMTU0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGUwMTc5NTVkZTNjZjhiZWM1ZjQxMGM0ZWFkZjg5ZTQzZDg4MmU0OTZkZjlhYWRhM2VmZWRjNDU3MTE1NzQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RNPgrv8UfwD_YCJ6Q6bMIU0tZjj3VkSwCjMW0rWCdbo)
> 
> Logs do chatwoot: [_chatwoot-rails-1_logs.txt](https://github.com/EvolutionAPI/evolution-api/files/14919263/_chatwoot-rails-1_logs.txt)

Só para tentar ajudar,

Você já teve sucesso em outras instâncias ou é a primeira tentativa?

Como está o .env do EV?

Nos meus primeiros testes, o lab apontando somente IP, tudo funcionava.

Quando passei para fqdns, o ambiente só funcionou quando utilizei certificado ssl no EV e CW(Pelo menos no EV, tinha que ter certificado ssl porque se não o CW não conseguia consultar a api EV.

CW 3.6.0
EV 1.6

**Comment by pedrotecinf** [comment]
bug corrigido na versão 1.7.3

**Comment by mentoriaferai** [comment]
Estou na mesma situação...

Versão: Evolution 2.1.0
VPS Ubuntu 20.04

Alguém passando por isso ou sabendo se voltou a dar o mesmo problema?

**Comment by danyllolobo** [comment]
Estava dando erro na versão 2.2.0 da Evolution API.
Encontrei a Solução de uma forma muito simples. Verifiquem as variáveis de ambiente da Evolution API
por padrão a variável CHATWOOT_ENABLED vem como false, altere para true, e tente fazer a conexão novamente. Aqui funcionou.

**Comment by Heyvitor** [comment]
Coloquei a variavel de ambiente 'CHATWOOT_ENABLED=true' e resolveu, valeu @danyllolobo

**Comment by rasbsena** [comment]
estou com o mesmo problema , chatwoot 3,1

**Comment by omladalan** [comment]
Eu tive um problema parecido, quando  o evo cria a caixa o webhook no chatwoot grava o inicio do endereço como http, dai eu adicionei o https e funcionou. Talvez isso salve alguem.

**Comment by alexmonarca** [comment]
Estou com mesmo problema no chatwoot v4.1 e Evolution v2.3.0

**Comment by LucasFidelis** [comment]
@alexmonarca Para resolver esse problema na maioria das vezes é a ausência da variável de ambiente `CHATWOOT_ENABLED`, que por padrão vem como false.
[Link da Documentação](https://doc.evolution-api.com/v2/pt/env#chatwoot)
Faça a alteração para true e reinicie o serviço.
