### ISSUE TITLE
[PT][BUG] MENSAGEM CHEGANDO DUPLICADA NO WHATSAPP

### ISSUE THREAD

**Issue by val-leite** [EvolutionAPI/evolution-api#526]
#### Descrição:
MENSAGEM ESTÁ DUPLICANDO MENSAGEM NO WHATSAPP, MAS NO CHATWOOT SEGUE NORMAL.

#### Ambiente:
- **Servidor:** [ex: Ubuntu 20.04]
- **Versão da API:** [ex: 1.7.0 E 1.7.1]
- **Outras Especificações de Hardware/Software:** [ex: CPU, GPU]

#### Notas Adicionais:
ME AJUDE!

![image](https://github.com/EvolutionAPI/evolution-api/assets/142282814/b21d9e14-849e-40d0-ab9f-a38ae10f4e96)

![image](https://github.com/EvolutionAPI/evolution-api/assets/142282814/81f3d98a-f36b-4acb-bdad-0ba62d607e58)

**Comment by R4T0** [comment]
certifique-se de usar a versão mais recente do chatwoot

**Comment by val-leite** [comment]
![image](https://github.com/EvolutionAPI/evolution-api/assets/142282814/08360e2e-1ab9-4fc7-ba92-dacd3dd18f9d)

Estou usando a mais recente.

**Comment by michaelvips** [comment]
No caso vc enviou a mensagem por onde ? e qual a versão da sua evolution api ?

**Comment by val-leite** [comment]
Enviei diretamente do Chatwoot para o Whatsapp. Minha versão que está rodando da Evo é a 1.7.1. Chatwoot está rodando na última versão também.
