### ISSUE TITLE
Mensagem não é enviada

### ISSUE THREAD

**Issue by R4T0** [EvolutionAPI/evolution-api#529]
Boa tarde..
Evolution 1.7.0 > MongoDB
Chatwoot 3.7.0 

Tem um contato em específico que recebemos a mensagem dele normal no chatwoot integrado com a API.. 
Mas ao enviar a mensagem para ele, não acusa nenhum erro no chatwoot, no whatsapp nem consta que foi enviada, e no log da api
informa alguns erros que não compreedi exatamente.
![image](https://github.com/EvolutionAPI/evolution-api/assets/73944522/50021e22-f4ee-4dfd-bd53-31fdb7e685f7)

**Comment by DavidsonGomes** [comment]
atualize sua conexao!
