### ISSUE TITLE
Lista de Transmissão

### ISSUE THREAD

**Issue by andradeid** [EvolutionAPI/evolution-api#53]
Fazendo uns testes no chatwoot observei que quando envio mensagens em uma lista de transmissão através do celular, o contato da lista aparece como contato novo no chatwoot ou seja a lista aparece lá.

Tentei enviar mensagem para o contato dessa lista pelo chatwoot e não ocorreu, mas acredito que seja só ajustes e aí se isto realmente acontece vai ajudar muita gente.

Se conseguirmos por exemplo criar esses contatos de listas e enviar mensagem pelo chatwoot será muito bom.

Lembrando que eu fiz os envios através do celular que já tem a lista.

**Comment by DavidsonGomes** [comment]
Estaremos analisando a questão muito obrigado
