### ISSUE TITLE
[PT][BUG] - Chatwoot não está enviando mensagem de áudio

### ISSUE THREAD

**Issue by eliasmainetti** [EvolutionAPI/evolution-api#531]
#### Descrição:
Ao tentar responder mensagens em áudio pelo chatwoot, a mensagem parece chegar no destino (até aparece no contato) mas ao tentar reproduzir o áudio no whatsapp, da erro. 

#### Passos para Reproduzir:
1. Responda uma mensagem em áudio pelo Chatwoot
2. Tente Reproduzir a mensagem de áudio enviada pelo Chatwoot no Whatsapp. 
3. A Mensagem: "‎Este áudio não está mais disponível. Peça a xxxxxx para reenviá-lo." irá aparecer no Whatsapp que você tentar reproduzir o áudio enviado. 

#### Comportamento Esperado:
O Áudio deveria ser reproduzido. 

#### Comportamento Atual:
Áudio não é reproduzido. 

#### Capturas de Tela/Vídeos:
<img width="502" alt="image" src="https://github.com/EvolutionAPI/evolution-api/assets/34216013/07fdcf03-23d8-4e4c-9e86-18125956c051">
<img width="554" alt="image" src="https://github.com/EvolutionAPI/evolution-api/assets/34216013/0ae80322-2493-41c6-a2e5-3c529dc14a03">

#### Ambiente:
- **Servidor:** Docker
- **Versão da API:** 1.7.2
- ***Versão do chatwoot: v3.7.0
- **Outras Especificações de Hardware/Software:** [ex: CPU, GPU]

#### Envio de Logs:

<img width="886" alt="image" src="https://github.com/EvolutionAPI/evolution-api/assets/34216013/8df238fc-4d8c-4bd0-8849-c9a018cc0819">

**Comment by danielfontolan** [comment]
Estou com o mesmo problema aqui. Usando Chatwoot 3.7.0. Estava na Evolution 1.7.0, atualizei para 1.7.2 mas o problema persiste.

**Comment by eliasmainetti** [comment]
Conforme orientação do Davidson, fiz o downgrade para a versão 1.7.1 da evolution e o problema parou. Ele comentou na live de hoje no youtube que provavelmente a correção virá na 1.7.3

**Comment by suporteprevermed** [comment]
Alguem sabe se houve a correção na versão 1.7.4?

**Comment by danielfontolan** [comment]
Eu atualizei para a 1.7.4 e está funcionando!

Daniel Fontolan
Diretor
Wizard Capivari
Em 2 de mai. de 2024, 11:39 -0300, suporteprevermed ***@***.***> escreveu:

**Comment by jpa-weels** [comment]
estava com esse problema de não enviar áudio isso resolveu :  
environment:
    - DIRECT_UPLOADS_ENABLED=true

**Comment by daniloarf23** [comment]
@jpa-weels como e onde você adicionou essa linha, estou usando a imagem do Easypanel.
