### ISSUE TITLE
[PT][BUG] Problema na conexão do Chatwoot 3.7.0 com a Evolution 1.7.1 / 1.7.2

### ISSUE THREAD

**Issue by MariaIsabelli** [EvolutionAPI/evolution-api#533]
#### Descrição:
Estou com o seguinte problema, toda vez que tento conectar o chatwoot 3.7.0 com a evolution 1.7.1 ou a 1.7.2 me retorna um erro 500 de servidor, como o abaixo:

{
    "status": 500,
    "error": "Internal Server Error",
    "response": {
        "message": "Internal Server Error"
    }
}
![Screenshot from 2024-04-16 14-21-47](https://github.com/EvolutionAPI/evolution-api/assets/89652212/264e8bd4-a66f-4157-9ca2-3a55f11e5c67)

Fui verificar um logs e tive o seguinte logs da Evolution:

{
  origin: Promise {
    <rejected> TypeError: Cannot read properties of undefined (reading 'host')
        at BaileysStartupService.<anonymous> (/evolution/dist/src/api/services/whatsapp.service.js:527:71)
        at Generator.next (<anonymous>)
        at fulfilled (/evolution/dist/src/api/services/whatsapp.service.js:5:58)
  },

  stderr: 2,
  error: TypeError: Cannot read properties of undefined (reading 'host')
      at BaileysStartupService.<anonymous> (/evolution/dist/src/api/services/whatsapp.service.js:527:71)
      at Generator.next (<anonymous>)
      at fulfilled (/evolution/dist/src/api/services/whatsapp.service.js:5:58)
} 

O erro basicamente diz que o arquivo whatsapp.service.js contém um erro no código, indica que há uma tentativa de acessar a propriedade 'host' de um objeto que é indefinido, resultando em um erro de tipo indefinido,whatsapp.service.js na linha 527.

Estou usando tudo no docker compose, chatwoot e evolution numa kvm.

**Comment by jaison-x** [comment]
Está usando localProxy? Pelo que vi pode ser isso. Se for tente desabilitar para ver se pode ser isso.

**Comment by jaison-x** [comment]
Eu vi que tiveram commits para ajustar isso. Parece ter sido realmente um bugh. Tente usar a versão develop. Deve corrigir este problema.

**Comment by MariaIsabelli** [comment]
@jaison-x okey, obrigada irei tentar sim. ;-)

**Comment by MariaIsabelli** [comment]
GET
![Screenshot from 2024-04-17 11-57-29](https://github.com/EvolutionAPI/evolution-api/assets/89652212/a2333b83-9525-4b1a-9c87-99218713880f)

POST
![Screenshot from 2024-04-17 11-57-56](https://github.com/EvolutionAPI/evolution-api/assets/89652212/15eae8d2-dfc5-4c4b-9cf0-7eeb3cba71a3)

**Comment by MariaIsabelli** [comment]
(node:1) NOTE: The AWS SDK for JavaScript (v2) will enter maintenance mode
on September 8, 2024 and reach end-of-support on September 8, 2025.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check blog post at https://a.co/cUPnyil
(Use `node --trace-warnings ...` to show where the warning was created)
[Evolution API]    v1.7.3  1   -  Thu Apr 18 2024 09:45:06     ERROR   [unhandledRejection]  [object]   
{
  origin: Promise {
    <rejected> TypeError: Cannot read properties of undefined (reading 'forEach')
        at /evolution/dist/src/api/services/whatsapp/whatsapp.baileys.service.js:649:26
  },

  stderr: 2,
  error: TypeError: Cannot read properties of undefined (reading 'forEach')
      at /evolution/dist/src/api/services/whatsapp/whatsapp.baileys.service.js:649:26
} 
[Evolution API]    v1.7.3  1   -  Thu Apr 18 2024 09:45:06     ERROR   [unhandledRejection]  [object]   
{
  origin: Promise {
    <rejected> TypeError: Cannot read properties of undefined (reading 'forEach')
        at /evolution/dist/src/api/services/whatsapp/whatsapp.baileys.service.js:649:26
  },

  stderr: 2,
  error: TypeError: Cannot read properties of undefined (reading 'forEach')
      at /evolution/dist/src/api/services/whatsapp/whatsapp.baileys.service.js:649:26
}

**Comment by MariaIsabelli** [comment]
@SMolizini ainda não consegui resolver, você teve já algum avanço?

**Comment by MariaIsabelli** [comment]
@SMolizini tive esse problema tbm, estou atulizando o evo para 1.7.3 eo CW para 3.8.0 para ver aqui...

**Comment by SMolizini** [comment]
@MariaIsabelli Se conseguir, me avise :)

**Comment by possebon** [comment]
> Também não obtive nenhum progresso, mas estou com um outro erro também: { "status": 401, "error": "Internal Server Error", "response": { "message": "Unauthorized" } }
> 
> > @SMolizini ainda não consegui resolver, você teve já algum avanço?

Está usando o nginx proxy manager ou o nginx como proxy reverso? Se sim, você precisa adicionar na configuração do seu host do Chatwoot:

```
server {
    ...
    location / {
        ...
        underscores_in_headers on;
    }
}
```

**Comment by JuniorArruda** [comment]
> > Também não obtive nenhum progresso, mas estou com um outro erro também: { "status": 401, "error": "Internal Server Error", "response": { "message": "Unauthorized" } }
> > > @SMolizini ainda não consegui resolver, você teve já algum avanço?
> 
> Está usando o nginx proxy manager ou o nginx como proxy reverso? Se sim, você precisa adicionar na configuração do seu host do Chatwoot:
> 
> ```
> server {
>     ...
>     location / {
>         ...
>         underscores_in_headers on;
>     }
> }
> ```

Estava com mesmo problema, essa foi a solução. Uso o nginx com proxy reverso.

Obs. correção do local onde a linha underscores_in_headers on; deve ficar.

`server {
    ...
    location / {
        ...
    }
underscores_in_headers on;
}`

**Comment by osmirpedro99** [comment]
Boa noite pessoa estou utilizando chatwoot na versao 3.16 e o evo na 1.7.3 e o erro ainda persiste alguma novidae sobre ? nesse casou estou utilizando traefik
