### ISSUE TITLE
[PT][BUG] - Mensagem de novo contato para o chatwoot.

### ISSUE THREAD

**Issue by lucianoecunha** [EvolutionAPI/evolution-api#534]
Sempre que um novo contato envia uma mensagem pela api que e entregue ao chatwoot tenho o seguinte erro:

[Evolution API]  v1.7.2  17012   -  Tue Apr 16 2024 16:23:53     VERBOSE   [ChatwootService]  [string]  get client to instance: Mkt
[Evolution API]  v1.7.2  17012   -  Tue Apr 16 2024 16:23:53     VERBOSE   [CacheService]  [string]  cacheservice has key: Mkt:getProvider
[Evolution API]  v1.7.2  17012   -  Tue Apr 16 2024 16:23:53     VERBOSE   [CacheService]  [string]  cacheservice getting key: Mkt:getProvider
[Evolution API]  v1.7.2  17012   -  Tue Apr 16 2024 16:23:53     VERBOSE   [ChatwootService]  [string]  provider found
[Evolution API]  v1.7.2  17012   -  Tue Apr 16 2024 16:23:53     VERBOSE   [ChatwootService]  [string]  create client to instance: Mkt
[Evolution API]  v1.7.2  17012   -  Tue Apr 16 2024 16:23:53     VERBOSE   [ChatwootService]  [string]  client created
[Evolution API]  v1.7.2  17012   -  Tue Apr 16 2024 16:23:53     VERBOSE   [ChatwootService]  [string]  update contact in chatwoot
[Evolution API]  v1.7.2  17012   -  Tue Apr 16 2024 16:23:53     VERBOSE   [ChatwootService]  [string]  contact updated
[Evolution API]  v1.7.2  17012   -  Tue Apr 16 2024 16:23:53     VERBOSE   [ChatwootService]  [string]  get contact conversations in chatwoot
**[Evolution API]  v1.7.2  17012   -  Tue Apr 16 2024 16:23:53     ERROR   [ChatwootService]  [object]
TypeError: Cannot read properties of undefined (reading 'id')
    at ChatwootService.<anonymous> (/home/ti/evolution-api/dist/src/api/integrations/chatwoot/services/chatwoot.service.js:502:62)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ti/evolution-api/dist/src/api/integrations/chatwoot/services/chatwoot.service.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)**

[Evolution API]  v1.7.2  17012   -  Tue Apr 16 2024 16:23:53     WARN   [ChatwootService]  [string]  conversation not found
[Evolution API]  v1.7.2  17012   -  Tue Apr 16 2024 16:23:53     VERBOSE   [WAStartupService]  [string]  Inserting message in database
[Evolution API]  v1.7.2  17012   -  Tue Apr 16 2024 16:23:53     VERBOSE   [MessageRepository]  [string]  inserting messages
[Evolution API]  v1.7.2  17012   -  Tue Apr 16 2024 16:23:53     VERBOSE   [MessageRepository]  [string]  saving messages to store
[Evolution API]  v1.7.2  17012   -  Tue Apr 16 2024 16:23:53     VERBOSE   [MessageRepository]  [string]  saving messages to store
[Evolution API]  v1.7.2  17012   -  Tue Apr 16 2024 16:23:53     VERBOSE   [MessageRepository]  [string]  messages saved to store in path: /home/ti/evolution-api/store/messages/Mkt/860A751E33C480BD6B2462B93FB61DA8

As mensagens não sao entregues no chatwoot mas o contatos sao criados.
Eu sou consigo começar uma conversa se primeiro eu enviar a mensagem do chatwoot.

**Comment by jaison-x** [comment]
Está com o cache ativo? Tente limpar o cache rodando este comando no contato do chatwoot que gerencia a instância: clearcache.

**Comment by lucianoecunha** [comment]
> Está com o cache ativo? Tente limpar o cache rodando este comando no contato do chatwoot que gerencia a instância: clearcache.

Limpei o cache,  fiz dowgrade para 1.7.1, mesmo assim o erro acontece!

0|ApiEvolution  | [Evolution API]  v1.7.1  61544   -  Tue Apr 16 2024 18:33:07     VERBOSE   [ChatwootService]  [string]  contact updated
0|ApiEvolution  | [Evolution API]  v1.7.1  61544   -  Tue Apr 16 2024 18:33:07     VERBOSE   [ChatwootService]  [string]  get contact conversations in chatwoot
0|ApiEvolution  | [Evolution API]  v1.7.1  61544   -  Tue Apr 16 2024 18:33:07     ERROR   [ChatwootService]  [object]
0|ApiEvolution  | TypeError: Cannot read properties of undefined (reading 'id')
0|ApiEvolution  |     at ChatwootService.<anonymous> (/home/ti/evolution-api/dist/src/whatsapp/services/chatwoot.service.js:502:62)
0|ApiEvolution  |     at Generator.next (<anonymous>)
0|ApiEvolution  |     at fulfilled (/home/ti/evolution-api/dist/src/whatsapp/services/chatwoot.service.js:5:58)
0|ApiEvolution  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|ApiEvolution  | [Evolution API]  v1.7.1  61544   -  Tue Apr 16 2024 18:33:07     WARN   [ChatwootService]  [string]  conversation not found

**Comment by lucianoecunha** [comment]
Esse erro so acontece se a opção reabrir conversa estiver marcada na configuração da caixa no chatwoot.
