### ISSUE TITLE
[PT][FEAT] - Possibilidade de identificação da Instancia no Log

### ISSUE THREAD

**Issue by lucianoecunha** [EvolutionAPI/evolution-api#537]
#### Detailed Description:
Seria interessante que o log exibisse de qual instancia é. 
Os pessoas que tem mais de uma instancia poderia usar o grep para tratar questoes especificas por instancia.

#### Possible Implementations:

0|ApiEvolution | Instance=XX  | [Evolution API]  v1.7.1  61544   -  Wed Apr 17 2024 10:39:59     VERBOSE   [ContactRepository]

**Comment by DavidsonGomes** [comment]
ja adicionado isso nas novas versões, obrigado pela sugestão!
