### ISSUE TITLE
Não funciona com o chatbot do dialogflow

### ISSUE THREAD

**Issue by AstraOnlineWeb** [EvolutionAPI/evolution-api#54]
Olá

A API não funciona com o diwlogflow mesmo ativando a opção de mensagens "conversation_pending": true.

**Comment by arthurrferroni** [comment]
Obtive o mesmo problema

**Comment by bmilioli** [comment]
Para mim funcionou tranquilamente. Para passar do Dialogflow para o atendente coloque o seguinte Custom Payload:

{
  "action": "handoff"
}
