### ISSUE TITLE
Outra coisa que percebi, é que mesmo você definindo uma mensagem para enviar antes da lista, ele envia na ordem errada, primeiro processa o webhook, depois a mensagem.

### ISSUE THREAD

**Issue by vsalgueiro7** [EvolutionAPI/evolution-api#540]
Outra coisa que percebi, é que mesmo você definindo uma mensagem para enviar antes da lista, ele envia na ordem errada, primeiro processa o webhook, depois a mensagem.

Alguma forma de contornar isso @fredlisboa

_Originally posted by @MarksEliel in https://github.com/EvolutionAPI/evolution-api/issues/329#issuecomment-1892367112_

**Comment by rafaelaabreuaq** [comment]
Eu resolvi isso fazendo um webhook de sendText, amigo. Pelo que eu entendi, o fluxo sempre dá prioridade pra as requisições HTTP.

**Comment by DavidsonGomes** [comment]
expliquei isso no issue #564

**Comment by widesysc** [comment]
Olá pessoal, estou com EVOLUTION 1.8 e TYPEBOT 2.25.2

Já tentei de tudo mas as requests continuam sendo executadas antes das mensagens do fluxo, alguma abordagem alternativa para contornar isso?

Obrigado

**Comment by gusttavh** [comment]
Alguém conseguiu resolver esse problema do sendlist?

**Comment by dpaes** [comment]
o davidson explicou que no typebot a prioridade é as requisições http, não é um problema ou bug, é o comportamento padrão. Se vc quer contornar use um n8n pra fazer a automação e chamar o bot quando for necessário. Não dá pra fazer tudo só pelo fluxo do bot, seria muita gambiarra, o ideal é usar uma aplicação como make ou n8n que faz automação e chama o typebot. Na v2 é pra ter mais controle e resolver um pouco mais disso sem precisar depender tanto de uma aplicação de automação.
