### ISSUE TITLE
TypeBot Change Session Status na versão 1.7.3 , não funciona [PT][BUG]

### ISSUE THREAD

**Issue by Eduardrj** [EvolutionAPI/evolution-api#541]
Não consigo parar o fluxo da mensagem, fica reniciando, quando o receptor responde algo.
Parece que só funciona na versão 1.5.4

estou usando: 

{{baseUrl}}/typebot/changeStatus/{{instance}}

{
    "remoteJid": ""{{remoteJid}}@s.whatsapp.net",
    "status": "closed" /* opened, paused, closed */
}

**Comment by Lopes-Marcio** [comment]
Nos testes que eu executei, altera para "opened" e "paused". Não alterna para "Closed"
Evo 1.7.2
Typebot 2.24.1

**Comment by psifernandocardoso** [comment]
Mesmo problema aqui também. Só parou de ficar reiniciando na versão 1.6.0. Alguma solução?

**Comment by RodrigoPontara** [comment]
Estou com o mesmo problema, estou usando a verão 1.7.0
