### ISSUE TITLE
[PT][BUG] Cannot read properties of undefined (reading 'host')

### ISSUE THREAD

**Issue by SMolizini** [EvolutionAPI/evolution-api#544]
Cannot read properties of undefined (reading 'host')

Esse erro não me autoriza nem a criar uma instância.

Ocorreu após instalação numa VM limpa no Docker modo Swarm.

Servidor: Ubuntu 20.04
API: 1.7.2 mas testei outras versões. 
Aplicação instalada em uma VM com 16GB RAM, 4vCPUs e 50GB Armazenamento.

Log Inteiro:
[Evolution API]  v1.7.2  1   -  Thu Apr 18 2024 09:31:24     ERROR   [unhandledRejection]  [object]   

{

  origin: Promise {

    <rejected> TypeError: Cannot read properties of undefined (reading 'host')

        at BaileysStartupService.<anonymous> (/evolution/dist/src/api/services/whatsapp.service.js:527:71)

        at Generator.next (<anonymous>)

        at fulfilled (/evolution/dist/src/api/services/whatsapp.service.js:5:58)

        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

  },

Eu poderia formatar a máquina e testar novamente e possivelmente funcionaria, mas queria resolver esse problema.

**Comment by jaison-x** [comment]
Este problema está na versão 1.7.2.

Use a versão develop, ou a versão 1.7.1, ou espere até sair a versão 1.7.3 para trocar de versão.

**Comment by ip2cloud** [comment]
Porque não rodar em docker?

**Comment by SMolizini** [comment]
> Porque não rodar em docker?



> Este problema está na versão 1.7.2.
> 
> Use a versão develop, ou a versão 1.7.1, ou espere até sair a versão 1.7.3 para trocar de versão.
--------------------------------------------------------------------------------------------------------
Mesmo usando versões antigas da EAPI não deu certo.
