### ISSUE TITLE
[PT][BUG] EvoAPI não cria caixa de entrada no Chatwoot.

### ISSUE THREAD

**Issue by SMolizini** [EvolutionAPI/evolution-api#545]
Status: 500, error: Internal Server Error.

Já testei nas versões: 
Chatwoot: 3.6, 3.7 e 3.8
EvolutionAPI: 1.7.2, 1.7.1 e 1.7.0

Ambiente: 
Docker swarm com 3 VMS.
1 - Manager (Onde o NPM está instalado): 32GB RAM, 8vCPUS e 100GB Armazenamento.
2 - Worker01 (onde EvoAPI e CW estão instalados): 16GB RAM, 4vCPUS e 50GB Armazenamento.
3 - Worker02 (onde todos os bancos de dados estão instalados): 16GB RAM, 4vCPUS e 50GB Armazenamento.

Ubuntu 20.04
![Sem título](https://github.com/EvolutionAPI/evolution-api/assets/167435967/c91d63f0-e4d4-4a27-9f74-c18ed7754b5b)

**Comment by antoniosaints** [comment]
por algum motivo, não consegui pelo domínio, tenta usar o ip da máquina com a porta, e alguns casos eu precisei mudar a porta 3000 para outra qualquer

**Comment by FEndo** [comment]
Eu estou com o mesmo problema. 
Com uma pequena diferença, talvez. Porque eu consigo criar a caixa de entrada pela Evolution API no ID de conta #1 do chatwoot. Quando tento criar a caixa de entrada com ID de conta #3 ele encontra este erro 500. 

Evolution API 1.8.0
Chatwoot 3.7.0

não tenho certeza se o erro é da API ou do Chatwoot. 
Pode ser do Chatwoot também.

**Comment by mordocks** [comment]
tambem estou com o mesmo problema.
Evolution API 1.8.0
Chatwoot 3.7.0
mas só tenho um id de conta que é o #2 (não sei porque, instalou assim)

**Comment by FEndo** [comment]
> Eu estou com o mesmo problema. Com uma pequena diferença, talvez. Porque eu consigo criar a caixa de entrada pela Evolution API no ID de conta #1 do chatwoot. Quando tento criar a caixa de entrada com ID de conta #3 ele encontra este erro 500.
> 
> Evolution API 1.8.0 Chatwoot 3.7.0
> 
> não tenho certeza se o erro é da API ou do Chatwoot. Pode ser do Chatwoot também.

este é parte do meu Chatwoot log durate a criação da conexão da Evolution com ele (ID de conta 4) :
----------------------------------------------------------
I, [2024-06-02T14:03:23.800708 #1]  INFO -- : [10ef3756-28a9-4523-8b9f-154a70baa0cc] Processing by Api::V1::Accounts::ConversationsController#create as JSON
I, [2024-06-02T14:03:23.809109 #1]  INFO -- : [10ef3756-28a9-4523-8b9f-154a70baa0cc]   Parameters: {"contact_id"=>"9", "inbox_id"=>"14", "account_id"=>"4", "conversation"=>{"inbox_id"=>"14", "contact_id"=>"9"}}
I, [2024-06-02T14:03:23.887696 #1]  INFO -- : source=rack-timeout id=508d6cf5-716b-421c-a266-62ea1c3869c5 timeout=15000ms state=ready
I, [2024-06-02T14:03:23.888177 #1]  INFO -- : [508d6cf5-716b-421c-a266-62ea1c3869c5] Started GET "/api/v1/accounts/4/inboxes" for 10.0.0.2 at 2024-06-02 14:03:23 +0000
I, [2024-06-02T14:03:23.892889 #1]  INFO -- : [508d6cf5-716b-421c-a266-62ea1c3869c5] Processing by Api::V1::Accounts::InboxesController#index as JSON
I, [2024-06-02T14:03:23.923046 #1]  INFO -- : [508d6cf5-716b-421c-a266-62ea1c3869c5]   Parameters: {"account_id"=>"4"}
I, [2024-06-02T14:03:24.218482 #1]  INFO -- : [508d6cf5-716b-421c-a266-62ea1c3869c5]   Rendered api/v1/accounts/inboxes/index.json.jbuilder (Duration: 179.4ms | Allocations: 3763)
I, [2024-06-02T14:03:24.222829 #1]  INFO -- : [10ef3756-28a9-4523-8b9f-154a70baa0cc] Completed 500 Internal Server Error in 414ms (ActiveRecord: 299.7ms | Allocations: 13710)
F, [2024-06-02T14:03:24.224692 #1] FATAL -- : [10ef3756-28a9-4523-8b9f-154a70baa0cc]   
[10ef3756-28a9-4523-8b9f-154a70baa0cc] NameError (undefined local variable or method `response_sources' for #<Inbox id: 14, channel_id: 14, account_id: 4, name: "WA_Flavio", created_at: "2024-06-02 14:03:23.405512000 +0000", updated_at: "2024-06-02 14:03:23.405512000 +0000", channel_type: "Channel::Api", enable_auto_assignment: true, greeting_enabled: false, greeting_message: nil, email_address: nil, working_hours_enabled: false, out_of_office_message: nil, timezone: "UTC", enable_email_collect: true, csat_survey_enabled: false, allow_messages_after_resolved: true, auto_assignment_config: {}, lock_to_single_conversation: false, portal_id: nil, sender_name_type: "friendly", business_name: nil>):
---------------------

O que achei estranho é que eu não tenho ID de usuário número 9 ("contact_id"=>"9") como está sendo enviado pela evolution. 

Já no log abaixo, estou criando a mesma caixa de entrada na conta de id 1, e que não dá problema. 
Daí ele envia "contact_id"=>"1", e tudo funciona.

---
I, [2024-06-02T14:42:15.105375 #1]  INFO -- : [a4024154-d857-4b31-bcd4-291883ae36f3]   Parameters: {"account_id"=>"1", "contact_id"=>"1"}
I, [2024-06-02T14:42:15.535746 #1]  INFO -- : [a4024154-d857-4b31-bcd4-291883ae36f3]   Rendered api/v1/accounts/contacts/conversations/index.json.jbuilder (Duration: 340.6ms | Allocations: 14107)
I, [2024-06-02T14:42:15.564734 #1]  INFO -- : [a4024154-d857-4b31-bcd4-291883ae36f3] Completed 200 OK in 459ms (Views: 182.3ms | ActiveRecord: 236.4ms | Allocations: 16876)
---
