### ISSUE TITLE
[PT][BUG] Envio de mensagem em Grupo X Individual 

### ISSUE THREAD

**Issue by viniciuslemmos** [EvolutionAPI/evolution-api#546]
#### Descrição:
Depois de diversos testes, ajustes de stack e por ai vai, é perceptível a diferença no Time Out quando é feito um disparo para grupos e quando envia para um número. Dupliquei um fluxo que envia mensagem para um grupo e passei a enviar também para um numero, e ficou mais do que perceptível a diferença que para o número o disparo surpreendeu com um time out de aproximadamente 2,5s quando envia uma imagem, já para o grupo o time out atingiu absurdos 300000ms e retornou como "timeout of 300000ms exceeded". 
Já no envio de mensagem de texto o timeout para o numero também ficou na média de 2s, já para texto em grupo o timeout foi para quase 30s.

#### Passos para Reproduzir:
1. Crie um fluxo de disparo que pode ser no N8N com dois endpoints, um com envio de texto e outro com envio de imagem.
2. Faça dois disparos, um enviando para um número e outro enviando para um grupo.
3. Você vai perceber a diferença no tempo dos disparos, mesmo a imagem sendo em base64.

#### Comportamento Esperado:
O correto seria que o tempo para envio para grupos fosse um pouco maior, mas não chegar ao ponto de estressar um servidor e não obter um retorno de cabeçalho após 300000ms. Seria até concebível um tempo de 10 a 30s.

#### Comportamento Atual:
O timeout no disparo de mensagem em grupo, principalmente usando o endpoint de imagem excede e muito o timeout.

#### Capturas de Tela/Vídeos:
![image](https://github.com/EvolutionAPI/evolution-api/assets/11073394/05eb09d1-6483-4cd4-8af3-413fea5b2999)
No exemplo acima tive que limitar o timeout para 40000ms até para o nó parar e prosseguir o fluxo. Mas se não coloco limite o timeout vai para 300000ms ou mais

#### Ambiente:
- **Servidor:** Ubuntu 23.04
- **Versão da API:** 1.7.2
- **Outras Especificações de Hardware/Software:**
8 núcleos de vCPU
Icon
32 GB de RAM
Icon
400 GB de espaço em disco NVMe
Icon
32 TB de Largura de Banda

**Comment by viniciusdebruin** [comment]
estou fazendo parecido aqui, mas todas as mensagens aparecem assim
![image](https://github.com/EvolutionAPI/evolution-api/assets/39091387/279f0581-5d3c-4ba7-a001-f77cc70e10de)

São alertas de consumos do servidor que criamos para ser alertados.
Em nenhum celular, nem mesmo no que enviou consegue visualizar.
