### ISSUE TITLE
[PT][BUG] connection-update fica em loop de connecting, open e close.

### ISSUE THREAD

**Issue by umcliquedigital** [EvolutionAPI/evolution-api#550]
#### Descrição:
Quando vai conectar uma instancia, depois de uns segundos ela fica enviando a requisição para o webhook como connecting, close e open. Algo como 30-40 requisições de uma vez a cada 10 segundos.

#### Passos para Reproduzir:
1. Conectar o número
2. Fazer um set dos settings (retirar o ignorar grupo e ativar todas as outras)

#### Comportamento Esperado:
Enviasse somente o connect-update como open

#### Comportamento Atual:
Loop de connecting, open e close.

#### Ambiente:
- **Servidor:** Ubuntu 23.1
- **Versão da API:** 1.6.1 e 1.7.1

**Comment by MattCarneiro** [comment]
to com a mesma coisa. Quando faço por QR code ele gera o QR code mas fica 1 minuto escaneando e dá erro no final

**Comment by MattCarneiro** [comment]
Update - Só acontece em telefones android. Por algum motivo, iPhone n acontece

**Comment by hericogimo** [comment]
Tente setar a variável ONFIG_SESSION_PHONE_VERSION para

CONFIG_SESSION_PHONE_VERSION=2.3000.1023337412

É a última versão do whatsapp web, funcionou para min

**Comment by hericogimo** [comment]
Versão 2.2.3 da evoluton
