### ISSUE TITLE
[PT][BUG]

### ISSUE THREAD

**Issue by venturion** [EvolutionAPI/evolution-api#551]
#### Descrição:
Porque aparece a mensagem que o remetente está usando uma versão antiga do whatsapp?

#### Passos para Reproduzir:
1. Basta enviar mensagem com a evolution api.

#### Comportamento Esperado:
Esperava que não aparecesse nenhuma notificação somente a mensagem

#### Comportamento Atual:
Além da mensagem aparece o ícone de exclamação ao lado que ao clicar mostra um balão notificando a mensagem sobre estar usando versão antiga do whatsapp.

#### Capturas de Tela/Vídeos:
Se possível, adicione capturas de tela ou vídeos que ilustrem o problema. Isso pode ser extremamente útil para entender o problema.

#### Ambiente:
- **Servidor:** ubuntu 20

![versão antiga do whatsapp](https://github.com/EvolutionAPI/evolution-api/assets/3776794/29e3b9ae-1d73-4854-81db-a80dc0f24e28)

**Comment by HugoDevGomes** [comment]
Alguém conseguiu resolver ?

**Comment by ZGuilomaker** [comment]
Estou com o mesmo problema, alguem consegui resolver?

**Comment by MattCarneiro** [comment]
@DavidsonGomes mesmo problema

**Comment by joaopereirajp** [comment]
Up

**Comment by Belkior** [comment]
Esse bug tem incomodado bastante, nesse caso apareceu a mensagem vazia tanto no whatsappweb quanto no celular, sendo que o retorno da api foi dado como success. Na sequencia foram enviadas outras mensagens que não apresentaram esse erro, sem desconectar nem nada, algumas vezes entra uma sequencia disso como se fossem retries, porém, sequer teve o comando de enviar mensagem.

![Image](https://github.com/user-attachments/assets/c4f138da-7baa-49f9-a298-2770940b2b85)

**Comment by rodstur** [comment]
Como faz para resolver isso?

**Comment by ZGuilomaker** [comment]
pelos meus teste não e um bug da api ou do whatsapp. Parece que isso ocorre com números novos, Eu fiz um teste com o numero da minha empresa e nele não deu esse problema, pois e um número comercial já usado muito tempo no whatsapp. Já com um número novo ele deu esse erro.

**Comment by martin-neumann-gurus** [comment]
Estou com mesmo problema, e realmente incomoda.

**Comment by lmontelatto** [comment]
mesmo problema aqui

**Comment by Davi-AMF** [comment]
Pessoal, acabei de testar e achei o motivo do "problema".
Isso acontece sempre que a Evolution envia mensagem para uma conversa que está marcada com "mensagens temporárias" do Whatsapp. Para replicar o erro: (Meu ambiente de teste foi Evolution customizada com base na v2.3.4 com atualizações até a 2.3.6, e o Baileys na versão mais recente 7.0.0-rc.9)

- Coloque uma conversa em "mensagens temporárias"
- Envie uma mensagem da Evolution para esta conversa
- Olhe pelo celular (o símbolo as vezes não aparece pelo Whatsapp Web)
- O símbolo estará em todas as mensagens enviadas pela Evolution

Dando uma pesquisada vi que tem um [issue sobre isso](https://github.com/WhiskeySockets/Baileys/issues/1687) aberto no Baileys.

<img width="400" height="500" alt="Image" src="https://github.com/user-attachments/assets/60238811-35c9-41b3-a917-741db0a77252" />
