### ISSUE TITLE
SessionError: No sessions

### ISSUE THREAD

**Issue by R4T0** [EvolutionAPI/evolution-api#554]
Notei que isso acontece após uns 3 a  4 dias de uso ininterrupto.
Evolution 1.7.0
Chatwot 3.7
Mongo 7
Tudo na mesma rede local, cada um em container diferente. Não falta recurson não consegui identificar se o problema é no mongo ou na API.
![image](https://github.com/EvolutionAPI/evolution-api/assets/73944522/b0af3caf-da06-41e4-96d5-40aeec8a808a)
A mensagem é recebida normalmente, mas não envia.
![image](https://github.com/EvolutionAPI/evolution-api/assets/73944522/3045982c-e69e-4c91-a639-2341a50432a2)

**Comment by DavidsonGomes** [comment]
Erro de no session so reiniciar o serviço, teste usar o redis para salvar a instancia.

**Comment by ailsoncgt** [comment]
@DavidsonGomes , já tenho as instancias no mongo e mudei para salvar no redis. Feito isso, as instancias não aparecem no manager. O sistema não devia ver se tem no banco popular o Redis com as instancias existentes ?

**Comment by eduardochaves1** [comment]
> @DavidsonGomes , já tenho as instancias no mongo e mudei para salvar no redis. Feito isso, as instancias não aparecem no manager. O sistema não devia ver se tem no banco popular o Redis com as instancias existentes ?

Conseguiu salvar no redis e ver se isso resolvia o problema?

**Comment by jonathandebrito** [comment]
**O erro continua acontecendo!** 

Pelo que percebi, esse problema ocorre depois de alguns dias de uso contínuo e não afeta todas as instâncias igualmente. Parece que há uma relação com grupos antigos, possivelmente devido a questões de criptografia ou armazenamento da sessão. 

Mesmo com instâncias armazenadas no MongoDB ou Redis, o erro de "No Sessions" persiste. Já foi sugerido reiniciar o serviço, mas isso não resolve o problema de forma definitiva. 

Alguém da equipe tem alguma atualização concreta sobre isso? Ou vamos continuar dependendo dessas soluções temporárias?

**Comment by TiagoGouvea** [comment]
Realmente segue acontecendo até nas versões atuais.. precisamos mesmo achar uma forma de evitar essa falha.

**Comment by jonathandebrito** [comment]
Eu resolvi trocando de api, agora estou usando Z-API, e não tive mais dores de cabeça. Recomendo!

**Comment by gerickt** [comment]
> **O erro continua acontecendo!**
> 
> Pelo que percebi, esse problema ocorre depois de alguns dias de uso contínuo e não afeta todas as instâncias igualmente. Parece que há uma relação com grupos antigos, possivelmente devido a questões de criptografia ou armazenamento da sessão.
> 
> Mesmo com instâncias armazenadas no MongoDB ou Redis, o erro de "No Sessions" persiste. Já foi sugerido reiniciar o serviço, mas isso não resolve o problema de forma definitiva.
> 
> Alguém da equipe tem alguma atualização concreta sobre isso? Ou vamos continuar dependendo dessas soluções temporárias?

Same problem here in v2.2.3

**Comment by morrisseybr** [comment]
Same problem here, any news?

**Comment by eduardoworrel** [comment]
Same here

**Comment by hugorn** [comment]
Comigo também ocorre, testei na 2.2.3 e na  2.3.0

**Comment by TiagoGouvea** [comment]
@hugorn se ainda acontece na 2.3.0 talvez seja melhor abrir uma issue nova com os detalhes, pq essa já tá fechada, ninguem vai vir aqui olhar.
Dai faz referência pra essa também.

**Comment by vilsonnjr** [comment]
Existe uma issue aberta, comentei lá, se conseguirem dar uma força lá, quem ainda tiver com o problema. #1424

**Comment by Edu-Luan** [comment]
I used the image:
evoapicloud/evolution-api:v2.3.4

build and up...

**Comment by renanfukagawa** [comment]
Found the root cause of SessionError: No sessions for LID groups.

The bug is in messages-send.js inside Baileys — the code assumes group 
participants always use @s.whatsapp.net, but accounts with LID architecture 
use @lid. The wrong encoding causes assertSessions to look for non-existent 
sessions.

Fix: detect if participantsList contains @lid entries and use the correct 
server when encoding JIDs in patchMessageBeforeSending and in the 
senderKeyJids loop.

Patch (tested and working): https://gist.github.com/renanfukagawa/6043c92877e9eaca9b230d6a35a44507

Tested on: Evolution API v1.8.2, Baileys v6.7.5, Mac Mini M1 (ARM).
