### ISSUE TITLE
Recuperar mídia antiga

### ISSUE THREAD

**Issue by DRIMOL** [EvolutionAPI/evolution-api#559]
existe alguma forma de recuperar mensagem de midia, que foi enviada antes da conexão do chip?

o webhook que chega com todas mensagens ao conectar, se tento recuperar a midia com base64, não retorna, existe alguma forma ?

Alguma configuração no env ?

**Comment by DavidsonGomes** [comment]
So passar todo o objeto da mensagem no message do getBase64FromMediaMessage, se passar so o id ele vai buscar no banco a mensagem, se mandar o corpo inteiro da mensagem ele funciona certinho!
