### ISSUE TITLE
Exibir mensagens enviadas via API no Chatwoot

### ISSUE THREAD

**Issue by Nilbertocs** [EvolutionAPI/evolution-api#56]
Seria interesante as mensagens enviadas diretamente pela EvolutionAPI serem exibidas no Chatwoot

Por exemplo se meu sistema de faturamente enviar uma mensagem de fatura ou ticket essa mensagem ser exibida no Chatwoot para que o antendente tenha um contexto caso o cliente responda essa mensagem!

**Comment by pedrofnts** [comment]
Use a API do Chatwoot para criar a conversa e, em seguida, a mensagem.

**Comment by DavidsonGomes** [comment]
Resolvido na versao 1.5.1

**Comment by Nilbertocs** [comment]
@DavidsonGomes agradeço pelo feedback, fiz a atualização porém as mensagens continuam sem aparecer no Chatwoot!
É necessário tomar mais alguma ação?
