### ISSUE TITLE
[PT][BUG] "Não autorizado" Não consigo conectar EvolutionAPI com o Chatwoot.

### ISSUE THREAD

**Issue by SMolizini** [EvolutionAPI/evolution-api#560]
![image](https://github.com/EvolutionAPI/evolution-api/assets/167435967/262a4843-be45-40e3-b503-dbc75dcefe51)

Já testei todas as versões, já reinstalei em uma VM limpa, já reinstalei em outra máquina com outro IP, outro DNS, outro domínio...
Alguém pode me ajudar por favor??

- **Servidor:** Ubuntu 20.04
- **Versão da API:** 1.7.3, mas já testei outras versões.
- **Versão do Chatwoot:** 3.8.0 mas já testei outras versões. 

Ambiente Swarm com 1 máquina manager e 3 workers. 

LOGS EVOAPI:
2024/04/24 09:51AM 50 pid=1 hostname=92657be5c6d4 node={"tag":"stream:error","attrs":{},"content":[{"tag":"conflict","attrs":{"type":"replaced"}}]} msg=stream errored out

[Evolution API]    v1.7.3  1   -  Wed Apr 24 2024 10:51:20     ERROR   [ChatwootService]  [object]   

ApiError: Unauthorized

    at catchErrorCodes (/evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:226:15)

    at /evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:257:17

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {

  url: 'https://chatapp.agenciafloresta.com.br/api/v1/accounts/1/contacts/filter',

  status: 401,

  statusText: 'Unauthorized',
  
  LOGS Chatwoot:
  I, [2024-04-24T13:51:48.508576 #1]  INFO -- : source=rack-timeout id=36a4f3cd-bf85-4f34-bd84-289769b2583c timeout=15000ms service=4ms state=completed

I, [2024-04-24T13:51:49.538561 #1]  INFO -- : source=rack-timeout id=d8992546-239a-4650-a278-f3e5507b862d timeout=15000ms state=ready

I, [2024-04-24T13:51:49.538940 #1]  INFO -- : [d8992546-239a-4650-a278-f3e5507b862d] Started POST "/api/v1/accounts/1/contacts/filter" for 10.0.0.2 at 2024-04-24 13:51:49 +0000

I, [2024-04-24T13:51:49.542377 #1]  INFO -- : [d8992546-239a-4650-a278-f3e5507b862d] Processing by Api::V1::Accounts::ContactsController#filter as JSON

I, [2024-04-24T13:51:49.542439 #1]  INFO -- : [d8992546-239a-4650-a278-f3e5507b862d]   Parameters: {"payload"=>[{"attribute_key"=>"[FILTERED]", "filter_operator"=>"equal_to", "values"=>["123456"], "query_operator"=>"OR"}, {"attribute_key"=>"[FILTERED]", "filter_operator"=>"equal_to", "values"=>["123456"], "query_operator"=>nil}], "account_id"=>"1", "contact"=>{}}

I, [2024-04-24T13:51:49.543374 #1]  INFO -- : [d8992546-239a-4650-a278-f3e5507b862d] Filter chain halted as :authenticate_user! rendered or redirected

I, [2024-04-24T13:51:49.543501 #1]  INFO -- : [d8992546-239a-4650-a278-f3e5507b862d] Completed 401 Unauthorized in 1ms (Views: 0.2ms | ActiveRecord: 0.0ms | Allocations: 438)

**Comment by 1ribhdev4** [comment]
Não autorizado normalmente é problema com o token, copiou o token do chatwoot?
