### ISSUE TITLE
[EN][BUG] Quando o atendente marca uma mensagem para comentar, o ChatWoot marca a mensagem incorreta para o usuário/cliente, às vezes nem é uma mensagem daquela conversa

### ISSUE THREAD

**Issue by elizeufranca** [EvolutionAPI/evolution-api#562]
O cliente envia uma mensagem ou o operador envia uma mensagem, depois clica com o botão direito na mensagem que deseja comentar, escreve a nova mensagem e envia.

Eu uso a versão mais recente do Chatwoot disponível para Swarm, v3.8.0.
Também utilizo a API Evolution na ultima versão. 

O operador ChatWoot marca uma mensagem, comenta, mas o usuário/cliente é marcado com outra mensagem aleatória, às vezes marcando uma mensagem que nem é daquela conversa.

![image](https://github.com/EvolutionAPI/evolution-api/assets/139554820/98266527-6491-424d-b971-3842df38f92c)

![image](https://github.com/EvolutionAPI/evolution-api/assets/139554820/5331b3ef-ba1b-4331-be33-8f3df693a105)

![image](https://github.com/EvolutionAPI/evolution-api/assets/139554820/7c36d63f-3a4a-4763-9cac-99f33d7dfd7b)

**Comment by pelinche** [comment]
Tenho notado o mesmo comportamento.
A mensagem "marcada" para responder parece ser sempre a ultima mensagem recebida

**Comment by elizeufranca** [comment]
Complementando, a marcação feita pelo cliente no seu WhatsApp, não aparece marcada no ChatWoot. Não sei ser ser bug da Evolution API ou se não existe implementação para esta marcação vinda do cliente, tanto no ChatWoot quanto na Evolution API

**Comment by cdiegosr** [comment]
Aqui aconteceu a mesma coisa após a atualização para a 1.7.4

A pessoa/cliente também vê dados da "resposta", mesmo não fazendo parte da conversa

**Comment by cdiegosr** [comment]
chatwoot 3.7.0 e evolution api 1.7.2

**Comment by pelinche** [comment]
Realizei diversos testes, analizando código fonte - e descobri que o problema deixa de ocorrer quando é ativada a persistência dos dados.

Definições padrão:
```
# Permanent data storage
DATABASE_ENABLED=false
DATABASE_CONNECTION_URI=mongodb://root:root@mongodb:27017/?authSource=admin&readPreference=primary&ssl=false&directConnection=true
DATABASE_CONNECTION_DB_PREFIX_NAME=evdocker

# Choose the data you want to save in the application's database or store
DATABASE_SAVE_DATA_INSTANCE=false
DATABASE_SAVE_DATA_NEW_MESSAGE=false
DATABASE_SAVE_MESSAGE_UPDATE=false
DATABASE_SAVE_DATA_CONTACTS=false
DATABASE_SAVE_DATA_CHATS=false
```


```
Com as minhas alterações:

# Permanent data storage
DATABASE_ENABLED=true
DATABASE_CONNECTION_URI=mongodb://root:root@mongodb:27017/?authSource=admin&readPreference=primary&ssl=false&directConnection=true
DATABASE_CONNECTION_DB_PREFIX_NAME=evdocker

# Choose the data you want to save in the application's database or store
DATABASE_SAVE_DATA_INSTANCE=false
DATABASE_SAVE_DATA_NEW_MESSAGE=true
DATABASE_SAVE_MESSAGE_UPDATE=true
DATABASE_SAVE_DATA_CONTACTS=true
DATABASE_SAVE_DATA_CHATS=true
```

Iniciei a testar o projeto a uma semana - então sei que o que sugeri como uma solução não é a verdade absoluta. Acredito que exista uma falha quando as mensagens estejam sendo persistidas no diretório store.

**Comment by elizeufranca** [comment]
Desculpe minha ignorância, usando Docker Swarm, onde fica esta configuração? Poderia colocar na stack?

**Comment by elizeufranca** [comment]
Pelo que entendi, podemos usar a Evolution sem o MongoDB ou com o MongoDB.
Hoje utilizo sem o Mongo e uso a Evolution conectada ao ChatWoot, onde as mensagens já são salvas. Estou tentando entender em que me ajudaria usar o Mongo para salvar tambem as mensagens no banco com a Evolution para que este bug nao acontecesse.

**Comment by pelinche** [comment]
@elizeufranca, independente de você usar ou não o MongoDB, as mensagens são persistidas pela EvolutionAPI. Caso não use MongoDB, elas são persistidas localmente, no diretório indicado na configuração (/evolution/store/messages/<nome_da_caixa>)

**Comment by DavidsonGomes** [comment]
Essa função so funciona corretamente com mongodb, como sempre recomendamos!
