### ISSUE TITLE
[EN][BUG] Erro ao criar primeira instância conectando ao chatwoot

### ISSUE THREAD

**Issue by cleisondouglas** [EvolutionAPI/evolution-api#563]
Ao criar a primeira instância, ele gera erro, mas gera o qrcode. 

<img width="627" alt="Screenshot at Apr 25 17-36-32" src="https://github.com/EvolutionAPI/evolution-api/assets/48367374/a49142c5-4545-440d-bcaf-e494261306af">

Ambos na versão mais atual do chatwoot e também do evolution-api.
Já reinstalei duas vezes. 

Uso esse post para criar: 
curl -X POST http://XXXX:8080/instance/create \
  -H "apikey: B6D711FCDE4D4FD5936544120E713976" \
  -H "Content-Type: application/json" \
  -d '{
    "instanceName": "whatsappnovo",
    "token": "",
    "qrcode": true,
    "chatwoot_account_id": 1,
    "chatwoot_token": "XXXX",
    "chatwoot_url": "XXX",
    "chatwoot_sign_msg": true,	
    "chatwoot_reopen_conversation": true,
    "chatwoot_conversation_pending": false
}'

Ele chega a criar o ambiente dentro do chatwoot, mas não aparece o qrcode, é como se não desse liga. Se eu, conectar o qrcode do terminal, ele faz a leitura, mas não manda para o chatwoot. 

Alguém ajuda?

**Comment by marconesns** [comment]
Estou com o mesmo problema, se o usar o json da pasta extra também não funciona.

**Comment by lucianodltec** [comment]
+1

**Comment by 1rodrigops** [comment]
Ola, pra mim esta conctado sem enviar o qrcode pro chatwoot, eu faço tudo pelo evolution-api acessando http://xxxx:8080/manager/ e crio as caixa de entrada manual usando os dados do  evolution-api

**Comment by ltlacerda** [comment]
Estou enfrentando o mesmo problema. Alguma luz?

**Comment by caiomzs** [comment]
Mesmo problema por aqui. Cria a caixa no chatwoot, fica como conectando no manager mas não envia o QRCode no chat. Conectando pelo manager funciona normal, mas entro nessa questão do cliente não ter acesso tbm.

**Comment by lucianodltec** [comment]
foi resolvido na ultima versao atendai/evolution-api:v1.7.5
