### ISSUE TITLE
[PT][BUG] Mensagem é enviada após o Send List no fluxo do Typebot 

### ISSUE THREAD

**Issue by Samuel-Melo** [EvolutionAPI/evolution-api#564]
#### Descrição:
Criei um fluxo no Typebot enviando pelo Evolution API para fazer o pré atendimento da minha empresa. porém na hora de enviar o Send List não segue o fluxo descrito no Typebot.

Estou usando o Typebot na versão 2.24.1 e o Evolution API na versão 1.7.2
VPS Ubuntu 22.04

### Fluxo do Typebot: 
![image](https://github.com/EvolutionAPI/evolution-api/assets/81485692/2b996eb5-443c-48ab-8980-9cb661623b69)

### A ordem que chega no Whatsapp
![image](https://github.com/EvolutionAPI/evolution-api/assets/81485692/caca49be-0174-40e1-a1ff-80ff40dc984d)

**Comment by vsalgueiro7** [comment]
A lista eh envianda antes de qualquer mensagem neh ? , também estou a tempo com mesmo problema e ninguem responde ou ajuda .

**Comment by Samuel-Melo** [comment]
> A lista eh envianda antes de qualquer mensagem neh ? , também estou a tempo com mesmo problema e ninguem responde ou ajuda .

Exato, estou pesquisando de uns dias para ver se acho a solução porém nada também.

**Comment by Samuel-Melo** [comment]
@DavidsonGomes

**Comment by vsalgueiro7** [comment]
A unica coisa que para esse envio e se tiver um campo esperando alguma resposta do usuario.

**Comment by Samuel-Melo** [comment]
> A unica coisa que para esse envio e se tiver um campo esperando alguma resposta do usuario.

Eu percebi a mesma coisa, só se o fluxo estiver esperando uma resposta, tentei colocar temporizador, porém o temporizador espera o tempo e manda o Send List antes da mensagem do mesmo jeito, unica maneira que tem de parar isso no próprio fluxo do Typebot é coletando alguma resposta.

**Comment by vsalgueiro7** [comment]
@DavidsonGomes  ajuda nos por favor

**Comment by Samuel-Melo** [comment]
Sim, colocando como HTTP Request segue o fluxo normalmente, já tinha conseguido solucionar o problema

**Comment by DavidsonGomes** [comment]
Isso não é um BUG, simplesmente voce esta utilizando uma requisição HTTP no typebot e usando a evolution na integração, 

o fluxo é processado no typebot e so ai manda para a evolution processar e enviar as mensagens.

**Comment by widesysc** [comment]
Olá pessoal, estou com EVOLUTION 1.8 e TYPEBOT 2.25.2

Já tentei de tudo mas as requests continuam sendo executadas antes das mensagens do fluxo, alguma abordagem alternativa para contornar isso?

Obrigado

**Comment by and3510** [comment]
é possivel evolution sem vps? colocar no docker no proprio computador e integrar com o typebot para mandar no whatsapp?

**Comment by diegotupini** [comment]
sim é possivel amigo, facil fazer olha no youtube tem tutorial
