### ISSUE TITLE
update profile name nao funciona /chat/updateProfileName/

### ISSUE THREAD

**Issue by leandroavila74** [EvolutionAPI/evolution-api#567]
#### Description:
notei que usando o manager  para alterar nome da instancia nao funcionava... dai resolvi usar o endpoint e tambem nada... 

#### Steps to Reproduce:
1. va no manager e tente alterar o nome da instancia
2. va no endpoint e tente alterar o nome da instancia

#### Environment:
- **Server:** [ e.g., debian 11 (docker) ]
- **API Version:** [1.7.4]

**Comment by DavidsonGomes** [comment]
Aqui esta funcionando, verifica a sua conexao, versão do whatsapp...
