### ISSUE TITLE
[EN][BUG]

### ISSUE THREAD

**Issue by DAVIAMERICO242** [EvolutionAPI/evolution-api#568]
Vazamento de informação no websocket. Tenho um disparador baseado na evolution com 16 usuários, quando múltiplos usuários estão disparando,acontece que a mensagem que um usuário configurou vaza e o outro usuário acaba enviando a mensagem que esse usuário configurou no disparador,  como se as requisições  http não fossem independentes entre clientes.

**Comment by DavidsonGomes** [comment]
Não entendi o problema, o vazamento no websocket ou http?

**Comment by DAVIAMERICO242** [comment]
A chamada http triga o envio de mensagem websocket pelo baileys no final das contas é tudo websocket, usei mutex e parece que resolveu

**Comment by DAVIAMERICO242** [comment]
Se quiser simular ponha 10 usuarios disparando pela evolution a mensagem de disparo deve ser semelhante mas diferente em cada usuario, uma instancia vai enviar mensagem de uma chamada http de outra instancia, nao sei se é problema de cache ou assincronicidade, o problema nasceu no meu disparador ele tinha uns erros tipo variaveis inacessiveis dentro do catch e isso resetava o pm2 mas nao vejo como isso poderia causar o problema, a nao ser que o pm2 tem algum mecanismo de restaurar estado da aplicação mas acho difícil, se quiser olha meu github disparador local prod
