### ISSUE TITLE
[PT][BUG] Integração CloudAPI com Chatwoot - Mídia chega como arquivo 

### ISSUE THREAD

**Issue by ricardocarrer** [EvolutionAPI/evolution-api#569]
#### Descrição:
Qualquer mídia que for enviada para Cloud API é enviada para o chatwoot com o file_type: 'file', isso vale para audio, video e imagem.

#### Passos para Reproduzir:
1. Conectar uma conta na API oficial do Evolution 
2. Integrar com o Chatwoot
3. Enviar uma imagem para o número da API oficial 

#### Comportamento Esperado:
Quando enviado uma imagem, era para aparecer a imagem e não um link para download como se fosse um arquivo.

#### Comportamento Atual:
Quando enviado uma imagem, chega como file no chatwoot

#### Capturas de Tela/Vídeos:
![Captura de Tela 2024-05-01 às 02 17 49](https://github.com/EvolutionAPI/evolution-api/assets/8516820/d1a085ed-307a-4a7f-ab81-ed8c11d38e91)

#### Ambiente:
- **Servidor:** [Ubuntu 18.04]
- **Versão da API:** [1.7.4] (na 1.7.1, .2 e .3 também tem o mesmo comportamento)

#### Envio de Logs:
Log:
Como chega:
 message: {
    imageMessage: {
      **mime_type: 'image/jpeg',**
      sha256: '0RqYGSf3nj5fNXulSKGuH8wH/0ZFCqeaeWORnXVASQM=',
      id: '420851174225050'
    },
    base64: '/9j/4AAQSkZJRgABA....
  },
  messageType: 'imageMessage',
  messageTimestamp: '1714539400',
  owner: 'CloudAPI'

attachments: [
    {

      id: 7,
      message_id: 22,
      **file_type: 'file**',
      account_id: 1,
      extension: null,
      data_url: 'https://app.defyit.com.br/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBFQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--10c150070b1bc04662ecae4cf31350b709da92ff/ezhaio.',
      thumb_url: 'https://app.defyit.com.br/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBFQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--10c150070b1bc04662ecae4cf31350b709da92ff/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lKYW5CbFp3WTZCa1ZVT2hOeVpYTnBlbVZmZEc5ZlptbHNiRnNIYVFINk1BPT0iLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ==--914ac6751326fc91b692e41ce717656bc4b491cb/ezhaio.',
      file_size: 128226,
      width: null,
      height: null
    }
  ],
  event: 'message_created'

**Comment by DavidsonGomes** [comment]
Não é necessariamente um bug, recomendo utilizar a cloud api direto na configuração do chatwoot, a integração feita na evolution é para fins de outros sistema que integram com ela e não tem essa possibilidade
