### ISSUE TITLE
[PT][BUG] - Mensagem editada pelo navegador não dispara webhook

### ISSUE THREAD

**Issue by dudanogueira** [EvolutionAPI/evolution-api#572]
#### Descrição:
Quando edita uma mensagem pelo navegador, ao invés de disparar um webhook da mensagem editada, ele envia:

```
{"event": "contacts.update", "instance": "evolution_instance", "data": [{"id": "XXXXXX@s.whatsapp.net", "profilePictureUrl": "asdasdasd", "owner": "evolution_instance"}], "destination": "http://django:8000/connector/22AA61B8E9074E2C965B", "date_time": "2024-05-01T10:23:23.939Z", "sender": "asdasdasd@s.whatsapp.net", "server_url": "http://localhost:8080", "apikey": "asdasdasdasdasd"}
```
Obs: se editar a mensagem pelo celular, ele dispara o webhook corretamente:

```
{
	"event": "messages.upsert",
	"instance": "evolution_instance",
	"data": {
		"key": {
			"remoteJid": "asdasdasd@s.whatsapp.net",
			"fromMe": false,
			"id": "258317BD26A4EC1Ct5h2GGB22FEDA52A1ED413"
		},
		"pushName": "Duda",
		"message": {
			"messageContextInfo": {
				"deviceListMetadata": {
					"senderKeyHash": "xv2sqZkhyVcy7g==",
					"senderTimestamp": "1713897692",
					"recipientKeyHash": "cKVGH1IW9cycnA==",
					"recipientTimestamp": "1714568027"
				},
				"deviceListMetadataVersion": 2
			},
			"editedMessage": {
....

```
#### Passos para Reproduzir:
1. envie uma mensagem para o número conectado
2. edite essa mensagem pelo whatsapp web
3. o payload disparado não corresponde ao de mensagem editada

#### Comportamento Esperado:
deveria disparar o payload de mensagem editada

#### Comportamento Atual:
dispara um payload contacts.update

#### Capturas de Tela/Vídeos:
Se possível, adicione capturas de tela ou vídeos que ilustrem o problema. Isso pode ser extremamente útil para entender o problema.

#### Ambiente:
- **Servidor:** docker rodando no mac
- **Versão da API:** 1.7.4
- **Outras Especificações de Hardware/Software:** Mac

#### Envio de Logs:
LOG DE QUANDO EDITA PELO NAVEGADOR

> evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Event received: messages.upsert, contacts.update
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Finding settings
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Getting instance name
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [SettingsRepository]  [string]  finding settings
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [SettingsRepository]  [string]  finding settings in store
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Settings url: false
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Settings msg_call:
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Settings groups_ignore: true
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Settings always_online: false
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Settings read_messages: false
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Settings read_status: false
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Settings sync_full_history: undefined
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Listening event: messages.upsert
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Event received: messages.upsert
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Listening event: contacts.update
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Event received: contacts.update
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Verifying if contacts exists in database to update
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  message rejected
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Creating jid with number: TELEFONE-QUE-ENVIOU@s.whatsapp.net
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Number already contains @g.us or @s.whatsapp.net or @lid
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Getting profile picture with jid: TELEFONE-QUE-ENVIOU@s.whatsapp.net
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Getting profile picture url
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Sending data to webhook in event CONTACTS_UPDATE
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Getting instance name
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [AuthRepository]  [string]  finding auth
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [AuthRepository]  [string]  finding auth in store
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ChannelStartupService]  [string]  Updating contacts in database
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ContactRepository]  [string]  updating contacts
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ContactRepository]  [string]  updating contacts in store
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ContactRepository]  [string]  updating contacts in store
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ContactRepository]  [string]  contacts updated in store in path: /evolution/store/contacts/evolution_instance/TELEFONE-QUE-ENVIOU@s.whatsapp.net
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:31:04     VERBOSE   [ContactRepository]  [string]  contacts updated in store: 1 contacts

LOG DE QUANDO EDITA MENSAGEM PELO CELULAR

> evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Event received: messages.upsert, contacts.update
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Finding settings
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Getting instance name
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [SettingsRepository]  [string]  finding settings
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [SettingsRepository]  [string]  finding settings in store
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Settings url: false
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Settings msg_call:
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Settings groups_ignore: true
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Settings always_online: false
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Settings read_messages: false
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Settings read_status: false
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Settings sync_full_history: undefined
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Listening event: messages.upsert
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Event received: messages.upsert
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Listening event: contacts.update
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Event received: contacts.update
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Verifying if contacts exists in database to update
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     LOG   [ChannelStartupService]  [object]
evolution-1  | {
evolution-1  |   key: {
evolution-1  |     remoteJid: 'TELEFONE-QUE-ENVIOU@s.whatsapp.net',
evolution-1  |     fromMe: false,
evolution-1  |     id: 'F38B688FDED90B0FDD1D33CD129A1BAB',
evolution-1  |     participant: undefined
evolution-1  |   },
evolution-1  |   pushName: 'Duda',
evolution-1  |   message: {
evolution-1  |     messageContextInfo: MessageContextInfo {
evolution-1  |       deviceListMetadata: [DeviceListMetadata],
evolution-1  |       deviceListMetadataVersion: 2
evolution-1  |     },
evolution-1  |     editedMessage: FutureProofMessage { message: [Message] }
evolution-1  |   },
evolution-1  |   contextInfo: undefined,
evolution-1  |   messageType: 'editedMessage',
evolution-1  |   messageTimestamp: 1714570538,
evolution-1  |   owner: 'evolution_instance',
evolution-1  |   source: 'android'
evolution-1  | }
evolution-1  |
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Sending data to webhook in event MESSAGES_UPSERT
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Getting instance name
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [AuthRepository]  [string]  finding auth
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [AuthRepository]  [string]  finding auth in store
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Inserting message in database
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [MessageRepository]  [string]  inserting messages
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [MessageRepository]  [string]  saving messages to store
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [MessageRepository]  [string]  saving messages to store
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [MessageRepository]  [string]  messages saved to store in path: /evolution/store/messages/evolution_instance/F38B688FDED90B0FDD1D33CD129A1BAB
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [MessageRepository]  [string]  messages saved to store: 1 messages
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Sending data to webhook local
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Getting remoteJid of instance
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     LOG   [ChannelStartupService]  [object]
evolution-1  | {
evolution-1  |   local: 'ChannelStartupService.sendDataWebhook-local',
evolution-1  |   url: 'http://django:8000/connector/22AA61B8E9074E2C965B',
evolution-1  |   event: 'messages.upsert',
evolution-1  |   instance: 'evolution_instance',
evolution-1  |   data: {
evolution-1  |     key: {
evolution-1  |       remoteJid: 'TELEFONE-QUE-ENVIOU@s.whatsapp.net',
evolution-1  |       fromMe: false,
evolution-1  |       id: 'F38B688FDED90B0FDD1D33CD129A1BAB',
evolution-1  |       participant: undefined
evolution-1  |     },
evolution-1  |     pushName: 'Duda',
evolution-1  |     message: {
evolution-1  |       messageContextInfo: [MessageContextInfo],
evolution-1  |       editedMessage: [FutureProofMessage]
evolution-1  |     },
evolution-1  |     contextInfo: undefined,
evolution-1  |     messageType: 'editedMessage',
evolution-1  |     messageTimestamp: 1714570538,
evolution-1  |     owner: 'evolution_instance',
evolution-1  |     source: 'android'
evolution-1  |   },
evolution-1  |   destination: 'http://django:8000/connector/22AA61B8E9074E2C965B',
evolution-1  |   date_time: '2024-05-01T10:35:38.223Z',
evolution-1  |   sender: 'TELEFONE-CONECTADO@s.whatsapp.net',
evolution-1  |   server_url: 'http://localhost:8080',
evolution-1  |   apikey: '08115657-45F1-42B0-9E1A-F5E468A8A0DB'
evolution-1  | }
evolution-1  |
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Getting remoteJid of instance
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Verifying contact from message
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ContactRepository]  [string]  finding contacts
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ContactRepository]  [string]  finding contacts in store
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ContactRepository]  [string]  finding contacts in store by id
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ContactRepository]  [string]  contacts found in store: 1 contacts
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Creating jid with number: TELEFONE-QUE-ENVIOU@s.whatsapp.net
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Number already contains @g.us or @s.whatsapp.net or @lid
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Getting profile picture with jid: TELEFONE-QUE-ENVIOU@s.whatsapp.net
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Getting profile picture url
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Creating jid with number: TELEFONE-QUE-ENVIOU@s.whatsapp.net
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Number already contains @g.us or @s.whatsapp.net or @lid
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Getting profile picture with jid: TELEFONE-QUE-ENVIOU@s.whatsapp.net
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Getting profile picture url
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Sending data to webhook in event CONTACTS_UPDATE
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Getting instance name
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [AuthRepository]  [string]  finding auth
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [AuthRepository]  [string]  finding auth in store
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Updating contacts in database
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ContactRepository]  [string]  updating contacts
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ContactRepository]  [string]  updating contacts in store
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ContactRepository]  [string]  updating contacts in store
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ContactRepository]  [string]  contacts updated in store in path: /evolution/store/contacts/evolution_instance/TELEFONE-QUE-ENVIOU@s.whatsapp.net
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ContactRepository]  [string]  contacts updated in store: 1 contacts
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Contact found in database
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Creating jid with number: TELEFONE-QUE-ENVIOU@s.whatsapp.net
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Number already contains @g.us or @s.whatsapp.net or @lid
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Getting profile picture with jid: TELEFONE-QUE-ENVIOU@s.whatsapp.net
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Getting profile picture url
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Sending data to webhook in event CONTACTS_UPDATE
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Getting instance name
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [AuthRepository]  [string]  finding auth
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [AuthRepository]  [string]  finding auth in store
evolution-1  | [Evolution API]  [evolution_instance]  v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ChannelStartupService]  [string]  Updating contact in database
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ContactRepository]  [string]  updating contacts
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ContactRepository]  [string]  updating contacts in store
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ContactRepository]  [string]  updating contacts in store
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ContactRepository]  [string]  contacts updated in store in path: /evolution/store/contacts/evolution_instance/TELEFONE-QUE-ENVIOU@s.whatsapp.net
evolution-1  | [Evolution API]    v1.7.4  1   -  Wed May 01 2024 10:35:38     VERBOSE   [ContactRepository]  [string]  contacts updated in store: 1 contacts

#### Notas Adicionais:
Obs: desenvolvo a integração open source Rocket.Connect que integra whatsapp com o Rocket.Chat: https://github.com/dudanogueira/rocket.connect

**Comment by wcsouza** [comment]
To com o mesmo problema...

**Comment by wcsouza** [comment]
Estou testando a versão 1.8.1 e o problema continua, não está enviando evento ao editar uma mensagem pelo whats web

**Comment by rolfottenfels** [comment]
Estou com o problema de não enviar nenhuma mensagem para o webhook informado. Ele atualiza o set presence.. mas não envia eventos quando uma mensagem é recebida no whatsapp.
