### ISSUE TITLE
[PT][BUG] Erro no endpoint Status/Stories

### ISSUE THREAD

**Issue by guns317** [EvolutionAPI/evolution-api#573]
#### Descrição:
Estou usando a versão 1.7.4 da Evolution API, segui exatamente a documentação postada no [postman](https://www.postman.com/agenciadgcode/workspace/evolution-api/request/26869335-51c74dd8-561a-4637-adac-44c1e6297033) da Evolution API, porém da erro quando eu seto o **allContacts** como **true** o erro abaixo acontece:

`{
	"status": 400,
	"error": "Bad Request",
	"response": {
		"message": [
			"SessionError: No sessions"
		]
	}
}`

O nome da instância e apikey estão corretos, quanto que quando eu mudo para false ele executa normalmente, porem apenas para os contatos setados na **"statusJidList"**.

 

#### Endpoints Usados:
{{baseUrl}}/message/sendStatus/{{instance}}

#### Capturas de Tela/Vídeos:
![Captura de tela 2024-05-02 154534](https://github.com/EvolutionAPI/evolution-api/assets/15690036/e3d0d9aa-8113-4de0-b174-3921ce079746)

#### Ambiente:
- **Servidor:** Ubuntu 22.04
- **Versão da API:** 1.7.4
- **Memória RAM:** 10240 MB
- **Núcleos vCpu:** 4
- **Armazenamento:** 40GB

**Comment by DavidsonGomes** [comment]
Erro de no sessions, recomento reiniciar o serviço e tentar novamente, para evitar esse erro use o redis ou mongodb para salvar a instancias de conexao
