### ISSUE TITLE
Suposto erro na integração com baileys

### ISSUE THREAD

**Issue by michaelvips** [EvolutionAPI/evolution-api#574]
#### Descrição:
Utilizo a plataforma easypanel para criar uma instancia da evolution e nos logs vejo um erro.

#### Capturas de Tela/Vídeos:
![image](https://github.com/EvolutionAPI/evolution-api/assets/21130174/5adf3836-b7a2-445b-bb3e-32997616ddcc)

#### Ambiente:
- **Servidor:** Ubuntu 22.04
- **Versão da API:** 1.7.4
- **Outras Especificações de Hardware/Software:**  4CPU 16GB Ram

#### Envio de Logs:
https://github.com/EvolutionAPI/evolution-api/files/15195679/log-error.json

#### Notas Adicionais:
Sempre usei esse sistema com outras versões e não tive esses erros nos logs

**Comment by Fagner-lourenco** [comment]
Aqui também
