### ISSUE TITLE
[PT][BUG] Evolution usando Manager padrão mesmo com URL alterada em /views

### ISSUE THREAD

**Issue by dgsmiley18** [EvolutionAPI/evolution-api#576]
#### Descrição:
Fiz a troca da URL do manager na pasta views/manager.hbs, reiniciei o container porém continua indo para a página padrão 

#### Passos para Reproduzir:
Trocar o link no views/manager.hbs para qualquer link

#### Comportamento Esperado:
a página do /manager ser redirecionado para a minha página do appsmith

#### Comportamento Atual:
Evolution ainda está utilizando o /manager padrão

#### Capturas de Tela/Vídeos:
![chrome_Lur4tEiJuY](https://github.com/EvolutionAPI/evolution-api/assets/38007632/f3735f98-d7dd-4a11-b65f-d7bfdb6b38bf)

#### Ambiente:
- **Servidor:** Docker
- **Versão da API:** 1.7.4

**Comment by DavidsonGomes** [comment]
Nao utilizamos mais esse manager interno a evolution, se quiser usar seu appsmith utilize no seu dominio fora da api
