### ISSUE TITLE
[PT][FEAT] Continuar fluxo com input vazio

### ISSUE THREAD

**Issue by rafaelaabreuaq** [EvolutionAPI/evolution-api#578]
#### Descrição Detalhada:
Estou construindo um fluxo no typebot + whatsapp e gostaria de implementar a seguinte função: que fosse possível avançar no fluxo após um tempo determinado mesmo que o input não fosse respondido pelo usuário.

**Um exemplo:**
Quando o fluxo perguntar "Qual seu nome?", se o usuário responder, o nome é armazenado numa variável 'nome' e em seguida é exibido "Prazer, {{nome}}!". Se o usuário não responder em 15 minutos, o fluxo continuaria mesmo com o input da variável 'nome' vazio e exibiria um "Prazer, {{pushName}}!".

É possível fazer isso? Se sim, como eu poderia fazer?

Acredito que esta seria uma função muito interessante para utilizar em fluxos de venda!

**Comment by michaelvips** [comment]
@rafaelaabreuaq isso não é uma issue, indico a você através da comunidade do discord achar uma solução para sua situação.
