### ISSUE TITLE
[PT][BUG] Typebot reinicia não importa o que se faça

### ISSUE THREAD

**Issue by psifernandocardoso** [EvolutionAPI/evolution-api#579]
### Título: Typebot reinicia não importa o que se faça

Já tentei de diversas formas diferentes parar o fluxo quando se chega ao final, mas não importa o que faça, sempre reinicia. Isso está sendo terrível, confunde demais os clientes e fica em um loop infinito.

**Comment by michaelvips** [comment]
@psifernandocardoso isso não é um bug, indico a você encerrar essa issue, isso é uma condição normal de funcionamento do typebot, acesse a comunidade do discord e encontre outras soluções.

**Comment by psifernandocardoso** [comment]
Desculpe, mas isso não acontecia nas versões anteriores a 1.7. Existe uma infinidade de reclamações de todos que utilizam o tybebot junto com a Evolution API sobre este bug após esta atualização. Existem outras issues aqui sobre a mesma temática e sem resposta alguma.  Comentários em vídeos no youtube. E nenhuma resposta com relação a esta problemática. 

Já tentei parar o fluxo com diversas soluções presentes dentro do próprio typebot. Esta condição é tanto um bug que só acontece no ambiente do whatsapp com a api da evolution. Em ambiente web o fluxo para quando chega ao final e não se repete. Já testei outra api e também encerra o fluxo ao seu final.

A condição normal do fluxo no typebot é ser encerrado ao seu final, não retornar ao início quando se chega ao fim do fluxo. Atualmente não tem como encerrar um chamado ou uma conversa com um cliente pelo typebot, pois sempre após a última mensagem do fluxo quando o cliente responde qualquer coisa o fluxo reinicia, independente se foi transferido pro chatwoot, se a conversa foi encerrada, não importa o que aconteça, sempre reinicia. E como informei, isso não acontecia em versões anteriores a 1.7.

**Comment by michaelvips** [comment]
@psifernandocardoso acontecia sim, quem reinicia o fluxo é o typebot e não a evolution.

**Comment by michaelvips** [comment]
@psifernandocardoso no caso deixa ver se eu entendi, ao final do fluxo mesmo sem o cliente enviar algo que o fluxo se reinicia ? ou se ele mandar algo ?

**Comment by psifernandocardoso** [comment]
Não, acontecia. Tanto que se eu retornar para a versão 1.6 o typebot não reinicia. Só passou a reiniciar na versão 1.7.

Esta é outra issue que trata do mesmo assunto:
https://github.com/EvolutionAPI/evolution-api/issues/541

Ex: Quando chega no final do fluxo e o atendimento é transferido para o chatwoot o typebot reinicia.

No manager tem a opção de "tempo de expiração". Sempre deixei em 60 minutos para exatamente este problema não acontecer. Mas a partir da versão 1.7 o tempo de expiração não funciona mais.

**Comment by psifernandocardoso** [comment]
![imagem_2024-05-08_172353728](https://github.com/EvolutionAPI/evolution-api/assets/160556058/4b0a633d-160e-4e06-b98d-f843ae9491c9)

Link para referência aos comentários da imagem acima:
https://www.youtube.com/watch?v=NFq4yX_1myg&t=31s

**Comment by michaelvips** [comment]
Ahh então no caso não é quando chega no final do fluxo, seria quando o atendimento é transferido ?

**Comment by psifernandocardoso** [comment]
Não importa qual seja o cenário. O fluxo sempre reinicia, independente do que aconteça no final do fluxo.

**Comment by michaelvips** [comment]
Entendo, porém no meu caso aqui, esta funcionando normal o fluxo so reinicia se houver o envio de uma nova mensagem.

**Comment by psifernandocardoso** [comment]
Mas não é para reiniciar quando é adicionado o tempo de expiração. A função do tempo de expiração é manter a sessão aberta até um determinado tempo sem reiniciar o fluxo. Geralmente eu mantenho o tempo de expiração de 60 minutos, tempo suficiente para atender um cliente caso precise de intervenção humana e reiniciar em um próximo contato.

**Comment by michaelvips** [comment]
Você esta usando o bloco Wait ?

**Comment by psifernandocardoso** [comment]
No final do fluxo o bloco Wait é ignorado e reinicia de qualquer forma.

**Comment by psifernandocardoso** [comment]
Sim.

**Comment by psifernandocardoso** [comment]
Não importa o que se faça, se houver qualquer interação do cliente o fluxo reinicia.

**Comment by psifernandocardoso** [comment]
Só aí? Você ainda não entendeu que existe um bug de infinity loop no fluxo? Eu já experimentei diversas soluções diferentes. Não importa o que se faça, na versão 1.7 o fluxo sempre reinicia.

**Comment by michaelvips** [comment]
https://github.com/EvolutionAPI/evolution-api/assets/21130174/4e763fc0-f7b8-468c-bfdf-bb02dbf28157

Realmente há um erro @DavidsonGomes olha o exemplo, com o pause de 20 segundos ele reiniciou o bot.

**Comment by michaelvips** [comment]
https://github.com/EvolutionAPI/evolution-api/assets/21130174/642cbd64-e379-4270-9408-1bd6398d3b16

**Comment by michaelvips** [comment]
@psifernandocardoso uma solução é enviar uma solicitação http através do endpoint Change Session Status e setar para paused

**Comment by psifernandocardoso** [comment]
Estou quebrando um galho assim via n8n. Mas é muito chato isso. E já tem muito tempo que esse bug vem sendo relatado. Desde o lançamento da versão 1.7.0

**Comment by psifernandocardoso** [comment]
Consegue ajudar aqui  @DavidsonGomes

**Comment by aldruei** [comment]
Olá pessoal, encontrei a solução para o problema, e é bem simples.
Antes, para explicar a causa, a Evolution API encerra a sessão quando não há mais blocos a serem atendidos, isso faz com que qualquer mensagem nova seja uma nova sessão, reiniciando assim o fluxo.
A solução consiste em apenas adicionar uma variável (TYPEBOT_KEEP_OPEN=true) na enviroment da Evolution api.

A solução na íntegra está aqui https://github.com/EvolutionAPI/evolution-api/issues/273
