### ISSUE TITLE
Quando Mensagem é Iniciada pelo Agente, status da Mensagem é iniciada como Aberta e logo depois é modificada para Pendente pelo admim, sem interação do Agente ou do admin..

### ISSUE THREAD

**Issue by talkwaycombr** [EvolutionAPI/evolution-api#58]
Quando o Operador inicia uma mensagem, enviando pelo cadastro do contato, a conversa é iniciada normalmente com status ABERTA. Porém logo após o contato responder, automaticamente o chatwoot modifica o status para PENDENTE, como se o administrador da conta tivesse feito esta alteracao.

Settings do Canal:
	    "sign_msg": true,
	    "reopen_conversation": true,
	    "conversation_pending": true

**Versão Evolution-API v.1.4.8**

![semnome](https://github.com/EvolutionAPI/evolution-api/assets/139575566/be642ff5-ef7e-4598-b22a-52f3ff10fce9)

**Comment by DavidsonGomes** [comment]
Sim, esse comportamento é devido a combinação das configurações reopen_conversation e conversation_pending
