### ISSUE TITLE
[PT][BUG] Chatwoot 3.8 API evolution 1.7.4 não recebe mensagens de grupos

### ISSUE THREAD

**Issue by robertarez** [EvolutionAPI/evolution-api#588]
Descrição: Desde a penúltima atualização do chatwoot, não recebe e nem envia mensagens para grupos de whatsapp. Já fizemos testes de desconexão e reconexão, sem sucesso.

Ambiente: 
cloud.digitalocean 8 GB Memory / 4 Intel vCPUs / 240 GB Disk / SFO3 - Ubuntu 22.04 (LTS) x64

**Comment by JNNelson** [comment]
Aproveitando o topico, eu estou testando esta api com estas mesmas versoes e nao consigo receber o qrcode.
Em testes localhost ja percebi que a mensagem nem ia, entao criei um tunel com o ngrok e agora a mensagem é enviada, mas nao retorna o qrcode. No manager entretanto o qrcode é gerado.
