### ISSUE TITLE
Não deleta mensagem!

### ISSUE THREAD

**Issue by qualimagem** [EvolutionAPI/evolution-api#592]
Não deleta mensagem.

Resposta do http request: The service was not able to process your request

metodo: delete    

/chat/deleteMessageForEveryone/minha instancia

estou usando n8n
É um chatbot de grupo de whatapp, ele recebe todas as mensagens por um webhook, se a mensagem contiver conteudo proibido, é enviada uma mensagem de alerta no grupo e outra no pv de quem postou a mensagem e logo em seguida após um delay a mensagem deveria ser apagada, mas não apaga. Os passos anteriores funcionam bem, mas a mensagem não é deletada.
Segui certinho que consta no postman.

 Ambiente:
- **Servidor: Ubuntu 20.04
- **Versão da API:  1.7.4

Envio de Logs:
{
  "errorMessage": "The service was not able to process your request",
  "errorDetails": {
    "rawErrorMessage": [
      "500 - \"{\\\"status\\\":500,\\\"error\\\":\\\"Internal Server Error\\\",\\\"response\\\":{\\\"message\\\":[\\\"Error while deleting message for everyone\\\",\\\"TypeError: Cannot destructure property 'user' of '(0 , WABinary_1.jidDecode)(...)' as it is undefined.\\\"]}}\""
    ],
    "httpCode": "500"
  },
  "n8nDetails": {
    "nodeName": "del_palavrão",
    "nodeType": "n8n-nodes-base.httpRequest",
    "nodeVersion": 4.2,
    "itemIndex": 0,
    "time": "11/05/2024, 08:20:33",
    "n8nVersion": "1.36.4 (Self Hosted)",
    "binaryDataMode": "default",
    "stackTrace": [
      "NodeApiError: The service was not able to process your request",
      "    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/HttpRequest/V3/HttpRequestV3.node.js:1571:35)",
      "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
      "    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:728:19)",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:660:53",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1062:20"
    ]
  }
}

![Captura de tela de 2024-05-11 08-53-11](https://github.com/EvolutionAPI/evolution-api/assets/162237105/d25d3373-022f-4d9f-bf47-10bfb4c12978)
![Captura de tela de 2024-05-11 08-58-35](https://github.com/EvolutionAPI/evolution-api/assets/162237105/b04c3607-480a-49d7-835a-fcb04766fa9d)

**Comment by neonabuko** [comment]
Eu repliquei o bug que vc descreveu aqui, e ele ocorre pq o remoteJid não remete a nenhum usuário.
Vc precisa associar um número de wpp ao remoteJid, por exemplo:

```
{
	"id": "id",
	"fromMe": true,
	"remoteJid": "5519999999999@s.whatsapp.net"
}
```
Resposta:

```
{
	"key": {
		"remoteJid": "551999999999@s.whatsapp.net",
		"fromMe": true,
		"id": "BAE56F8BF7A73772"
	},
	"message": {
		"protocolMessage": {
			"key": {
				"remoteJid": "5519999999999@s.whatsapp.net",
				"fromMe": true,
				"id": "id"
			},
			"type": "REVOKE"
		}
	},
	"messageTimestamp": "1715522917",
	"status": "PENDING"
}
```

**Comment by qualimagem** [comment]
Muito obrigado pela ajuda, ajudou d+, valeu.

**Comment by diegomustafamarino** [comment]
ta funcionando ainda? to fazendo uns testes, tentei dessa forma ai, ele retorna realmente como se tivesse funcionado mas não apaga

**Comment by diegomustafamarino** [comment]
@qualimagem @neonabuko tá funcionando deletar mensagens de grupos? como?

**Comment by neonabuko** [comment]
@diegomustafamarino Pra mim ta funcionando. Vc manda esse json no http://localhost:8080/chat/deleteMessageForEveryone/{nomeDaInstancia}

{
	"id": "id da mensagem que vc quer deletar",
	"fromMe": true,
	"remoteJid": "id do grupo"
}

Só precisa saber o id da mensagem a ser deletada e do grupo onde quer enviar

**Comment by neonabuko** [comment]
@diegomustafamarino se vc quiser mandar o erro aqui eu dou uma olhada

**Comment by diegomustafamarino** [comment]
> @diegomustafamarino se vc quiser mandar o erro aqui eu dou uma olhada

Eu abri uma issue, da uma olhada lá.

**Comment by diegomustafamarino** [comment]
> @diegomustafamarino Pra mim ta funcionando. Vc manda esse json no http://localhost:8080/chat/deleteMessageForEveryone/{nomeDaInstancia}
> 
> {
> 	"id": "id da mensagem que vc quer deletar",
> 	"fromMe": true,
> 	"remoteJid": "id do grupo"
> }
> 
> Só precisa saber o id da mensagem a ser deletada e do grupo onde quer enviar

Qual versão você está usando?

**Comment by diegomustafamarino** [comment]
> > @diegomustafamarino Pra mim ta funcionando. Vc manda esse json no http://localhost:8080/chat/deleteMessageForEveryone/{nomeDaInstancia}
> > 
> > {
> > 	"id": "id da mensagem que vc quer deletar",
> > 	"fromMe": true,
> > 	"remoteJid": "id do grupo"
> > }
> > 
> > Só precisa saber o id da mensagem a ser deletada e do grupo onde quer enviar
> 
> Qual versão você está usando?

Fiz desse jeito aí, ele retornou mas não apagou a mensagem. O id da mensagem é data.key.id mesmo?

**Comment by diegomustafamarino** [comment]
Cara esquece, tá funcionando, valeu a ajuda! Tmj

**Comment by Claudi0-Oliveira** [comment]
Aqui até agora não normalizou...Evo 2.1.0

Recebo o seguinte erro:

```
The service was not able to process your request
Internal Server Error
```

`500 - "{\"status\":500,\"error\":\"Internal Server Error\",\"response\":{\"message\":[\"Error while deleting message for everyone\",\"TypeError: Cannot read properties of undefined (reading 'updateGroupMetadataCache')\"]}}"`

**Comment by GitNicksWeb** [comment]
Estou utilizando a Evolution API em conjunto com o n8n para realizar a exclusão de mensagens em grupos do WhatsApp. A rota usada é:

https://sub.domain.com/chat/deleteMessageForEveryone/instance

No meu fluxo, o comando parece funcionar corretamente, pois a mensagem é excluída no meu lado, e também é exibido quem deletou a mensagem, indicando que a solicitação foi processada.

No entanto, observei um comportamento inesperado: quando verifico o lado do usuário que enviou a mensagem ou dos outros participantes do grupo, a mensagem não foi realmente deletada. Isso sugere que a exclusão não está sendo propagada corretamente para todos os membros do grupo.

Versão: 2.2.0

Alguém sabe como resolver?

**Comment by neonabuko** [comment]
> Estou utilizando a Evolution API em conjunto com o n8n para realizar a exclusão de mensagens em grupos do WhatsApp. A rota usada é:
> 
> https://sub.domain.com/chat/deleteMessageForEveryone/instance
> 
> No meu fluxo, o comando parece funcionar corretamente, pois a mensagem é excluída no meu lado, e também é exibido quem deletou a mensagem, indicando que a solicitação foi processada.
> 
> No entanto, observei um comportamento inesperado: quando verifico o lado do usuário que enviou a mensagem ou dos outros participantes do grupo, a mensagem não foi realmente deletada. Isso sugere que a exclusão não está sendo propagada corretamente para todos os membros do grupo.
> 
> Versão: 2.2.0
> 
> Alguém sabe como resolver? 

Oi tudo bem? Pode mandar a resposta do request? Pra eu dar uma olhada

**Comment by GitNicksWeb** [comment]
[
  {
    "key": {
      "remoteJid": "120363380313340698@g.us",
      "fromMe": true,
      "id": "3EB06640C85D76D5F33728"
    },
    "message": {
      "protocolMessage": {
        "key": {
          "remoteJid": "120363380313340698@g.us",
          "fromMe": true,
          "id": "3FA0BF7DB38FAC80144B"
        },
        "type": "REVOKE"
      }
    },
    "messageTimestamp": "1734903097",
    "status": "PENDING",
    "participant": "556993107167:59@s.whatsapp.net"
  }
]

**Comment by neonabuko** [comment]
tenta adicionar o "participant" no body do request, tipo

{
	"id": id da mensagem,
	"fromMe": false, -> false pois nao foi o admin que mandou a mensagem
	"remoteJid": id do grupo,
	"participant": remoteJid do participante que enviou a mensagem
}

no meu deu certo, me fala se foi no seu tbm

**Comment by GitNicksWeb** [comment]
Continua não funcionando 
![image](https://github.com/user-attachments/assets/761a4de5-8984-4b8a-a786-c5542e5f7362)

O chat de cima e do whatsapp teste e o de baixo é do administrador
