### ISSUE TITLE
[PT][BUG] - Mensagens duplicadas no aplicativo do Whatsapp quando for enviado pelo próprio App

### ISSUE THREAD

**Issue by ailsoncgt** [EvolutionAPI/evolution-api#596]
#### Descrição:
Tenho o evolution(v1.7.4) integrado com o chatwoot e até agora só consegui encontrar esse erro em específico:
Quando envio uma mensagem a partir do chatwoot, ela chega sem problemas e não repete a mensagem, porém, quando uso o aplicativo do whatsapp com a conta connectado no evolution e envio qualquer mensagem, ela é duplicada no aplicativo do whatsapp(vejo a imagem abaixo), mas não duplica no chatwoot. E sim, o usuário final também recebe a mensagem duplicada, ela só não duplica no chatwoot. É como se a mensagem foi enviada 2x vezes quando uso o próprio aplicativo do whatsapp.

#### Passos para Reproduzir:

1. Conecte sua conta evolution ao Chatwoot
2. Envie mensagem direto do aplicativo do whatsapp para um outro contato

#### Comportamento Esperado:
Mensagem enviada sem estar duplicada no aplicativo do whatsapp.

#### Comportamento Atual:
A mensagem enviada pelo app do whatsapp está sendo duplicada no app.

#### Capturas de Tela/Vídeos:
![captura-de-tela](https://github.com/EvolutionAPI/evolution-api/assets/18018868/3a991bdb-47c4-494a-94ea-28511c4e7262)

#### Ambiente:
- **Servidor:** Amazon Linux 2023
- **Versão da API:** 1.7.4

#### Envio de Logs:
Durante esse comportamento não identifiquei nenhum log especial. na verdade não tem nenhum log no momento.

**Comment by MattCarneiro** [comment]
to com a mesma coisa

**Comment by ailsoncgt** [comment]
@DavidsonGomes , alguma ideia do que pode estar acontecendo aqui e/ou o que posso fazer para solucionar? É um problema conhecido ?

**Comment by MattCarneiro** [comment]
@DavidsonGomes deu closed, mas o bug continua na versão 1.8.1

**Comment by ailsoncgt** [comment]
@DavidsonGomes , poderia, por favor pelo menos informar se esse erro é causada por alguma má configuração ou algo do tipo? Tentei caçar algo aqui nas envs e na documentação e não achei nada.
Ou se pelo menos tem alguma ideia do que pode ser já ajudaria bastante aqui 🙏🏾
