### ISSUE TITLE
A foto do perfil não aparece no chatwoot com números de telefone do México [PT][BUG]

### ISSUE THREAD

**Issue by ismael7** [EvolutionAPI/evolution-api#597]
#### Descrição:
As fotos do perfil não aparecem com números de telefone do México (+52)

#### Passos para Reproduzir:
1.- Conecte a API de evolução com chatwoot
2.- Enviar mensagem de um telefone no México

#### Comportamento Esperado:
Você deve mostrar a foto do perfil da pessoa, se a tiver disponível.

#### Comportamento Atual:
A foto do perfil não aparece

#### Capturas de Tela/Vídeos:
Se possível, adicione capturas de tela ou vídeos que ilustrem o problema. Isso pode ser extremamente útil para entender o problema.

#### Ambiente:
- **Servidor:** [ex: Ubuntu 20.04]
- **Versão da API:** 1.7.4
<img width="411" alt="Screenshot 2024-05-14 at 11 19 42 a m" src="https://github.com/EvolutionAPI/evolution-api/assets/32073211/a1930d1a-a1af-4a85-963f-7d49275d80c5">

**Comment by michaelvips** [comment]
Apenas com números de telefone do México ? E do brasil ?

**Comment by ismael7** [comment]
Se antes era mostrada a foto do perfil dos telefones que são do México e agora não funciona no chatwoot

**Comment by eliezerazevedo** [comment]
Olá também estou com esse problema v1.8.1, consultando dentro do MongoDB a foto vem como nill.

![image](https://github.com/user-attachments/assets/3c28ea80-3240-4bd6-bb83-92f942ac6f1b)
