### ISSUE TITLE
FALA GALERA! AJUDA! [BUG]

### ISSUE THREAD

**Issue by val-leite** [EvolutionAPI/evolution-api#598]
#### Description:

Ao interagir com o Fluxo do Typebot tudo o corre normalmente, exceto que a informação chega incompleta no whatsapp.

Informação sendo gerada normalmente no Typebot:
![image](https://github.com/EvolutionAPI/evolution-api/assets/142282814/a9b51983-720c-429e-8b8c-1bdfd7f39eed)

Informação chegando incompleta no whatsapp:
![image](https://github.com/EvolutionAPI/evolution-api/assets/142282814/1a1d7302-c1e8-4350-9672-df2b2efdfe5e)

Se observarmos o corpo da resposta não veio por completo (que seria por exemplo os passos de como emitir manifesto, observar os dois pontos que a seta aponta).

![image](https://github.com/EvolutionAPI/evolution-api/assets/142282814/80e51f0b-e114-4b71-8bdc-b02192e27cac)

Gratidão!

**Comment by michaelvips** [comment]
Pelo que entendi, essa texto que funciona bem no typebot não ira ser enviado pelo WhatsApp devido a formatação, não está em um formato que é aceito, precisa ser alterado.

**Comment by antonioaraujo664** [comment]
é a quebra de linha, o Evolution-api nao suporta strings como /n 
Ta dando trabalho, tem que ajustar o prompt para imprimir sem quebra de linha

Alguem tem uma solucao alternatitiva?

**Comment by val-leite** [comment]
Poderia trabalhar isso na próxima atualização. Nosso querido @deivisonrpg poderia ver sobre...

**Comment by antonioaraujo664** [comment]
acho que foi resolvido, olha esse commit 
https://github.com/EvolutionAPI/evolution-api/commit/e4b6f4ff0d49416e8dd70c7b6239576d15068407
