### ISSUE TITLE
Evolution Api Falha com os telefones do México, adicionando um número a mais no terceiro caractere do número do WhatsApp

### ISSUE THREAD

**Issue by ismael7** [EvolutionAPI/evolution-api#6]
Os telefones do México possuem 12 caracteres, e quando se utiliza o WhatsApp no celular, sempre registra 12 caracteres do número. Porém, quando utilizado o WhatsApp Web, registra 13 dígitos, o que está incorreto

Poderia ser resolvido com algo como isso.

if (number.startsWith("52") && number.length === 13) {
  // Remove o terceiro dígito
  number = number.substring(0, 2) + number.substring(3);
}

**Comment by DavidsonGomes** [comment]
> Os telefones do México possuem 12 caracteres, e quando se utiliza o WhatsApp no celular, sempre registra 12 caracteres do número. Porém, quando utilizado o WhatsApp Web, registra 13 dígitos, o que está incorreto
> 
> Poderia ser resolvido com algo como isso.
> 
> if (number.startsWith("52") && number.length === 13) { // Remove o terceiro dígito number = number.substring(0, 2) + number.substring(3); }

We are already correcting this issue, testing with Argentine and Mexican numbers, it will come out in the next version, thanks for the feedback
