### ISSUE TITLE
chatwoot v2.18.0 and evolutoinApi v1.4.8, messages sent to groups fail,

### ISSUE THREAD

**Issue by MarceloFloriano** [EvolutionAPI/evolution-api#60]
when sending messages using chatwoot v2.18.0 and evolutoinApi v1.4.8, messages sent to groups fail, they do not reach the recipient groups.
In chatwoot there are no errors, it is as if the message had been sent correctly, but in the whatsapp group it does not arrive.

**Comment by unilogica** [comment]
`[Evolution API]  v1.5.0  26   -  Fri Aug 18 2023 12:24:35     VERBOSE   [ChatwootRouter]  [object]   
{
  account: { id: 1, name: 'Teste' },
  additional_attributes: {},
  content_attributes: {},
  content_type: 'text',
  content: '**de Paula**\n\nAAAAAAA',
  conversation: {
    additional_attributes: {},
    can_reply: true,
    channel: 'Channel::Api',
    contact_inbox: {
      id: 8,
      contact_id: 2,
      inbox_id: 5,
      source_id: '4e***fa48-7b04-42de-a378-3c6***a4eaa4',
      created_at: '2023-08-18T12:09:57.299Z',
      updated_at: '2023-08-18T12:09:57.299Z',
      hmac_verified: false,
      pubsub_token: 'Yoar8V4eo******kAjH4JxD'
    },
    id: 7,
    inbox_id: 5,
    messages: [ [Object] ],
    labels: [],
    meta: {
      sender: [Object],
      assignee: [Object],
      team: null,
      hmac_verified: false
    },
    status: 'open',
    custom_attributes: {},
    snoozed_until: null,
    unread_count: 1,
    first_reply_created_at: '2023-08-18T12:10:08.153Z',
    priority: null,
    agent_last_seen_at: 1692361438,
    contact_last_seen_at: 0,
    timestamp: 1692361474,
    created_at: 1692360597
  },
  created_at: '2023-08-18T12:24:34.575Z',
  id: 44,
  inbox: { id: 5, name: '1_30_55******2148' },
  message_type: 'incoming',
  private: false,
  sender: {
    account: { id: 1, name: 'Teste' },
    additional_attributes: {},
    avatar: '',
    custom_attributes: {},
    email: null,
    id: 2,
    identifier: '12036******8479421@g.us',
    name: 'Teste (GROUP)',
    phone_number: null,
    thumbnail: ''
  },
  source_id: null,
  event: 'message_created'
} 
`

`
[Evolution API]  v1.5.0  26   -  Fri Aug 18 2023 12:24:52     ERROR   [ChatwootService]  [object]   
{ status: 400, error: 'Bad Request', message: [ 'Group not found' ] } 
`

**Comment by unilogica** [comment]
I found that in my case it happened with a single instance. I checked carefully and realized that I set the webhooks swapped.
