### ISSUE TITLE
[EN][BUG] Phone logout after scanning

### ISSUE THREAD

**Issue by sidd82** [EvolutionAPI/evolution-api#600]
Whenever I scan QR code my phone logout after scanning WhatsApp from android.
Error:
{"level":50,"time":1715854708031,"pid":3663,"hostname":"whatsapp-evo","node":{"tag":"stream:error","attrs":{"code":"401"},"content":[{"tag":"conflict","attrs":{"type":"device_removed"}}]},"msg":"stream errored out"}

**Comment by DAVIAMERICO242** [comment]
You should persist until you getting it, if you still cant manage so you may use proxy (the schema in docs is wrong you should to see in source code)

**Comment by yvescleuder** [comment]
I have a problem with the same error, but my scenario is different.
I'm using a webhook for n8n, this workflow is connected to an AI that returns a text to EvolutionAPI.
This error occurs and I don't know why.
I have other numbers using EvolutionAPI, but I don't use automation, it's for chatwoot and this doesn't happen.
![WhatsApp Image 2024-09-24 at 21 34 40](https://github.com/user-attachments/assets/8e2f3dd9-f576-4b36-9cfc-f3d57196c14c)

**Comment by brjorgedavid** [comment]
> I have a problem with the same error, but my scenario is different. I'm using a webhook for n8n, this workflow is connected to an AI that returns a text to EvolutionAPI. This error occurs and I don't know why. I have other numbers using EvolutionAPI, but I don't use automation, it's for chatwoot and this doesn't happen. ![WhatsApp Image 2024-09-24 at 21 34 40](https://github.com/user-attachments/assets/8e2f3dd9-f576-4b36-9cfc-f3d57196c14c)

Did you fix the issue?
