### ISSUE TITLE
endpoint Sendpoll (enquete) [PT][BUG]

### ISSUE THREAD

**Issue by DRIMOL** [EvolutionAPI/evolution-api#601]
### Título: [Breve Descrição do Bug]
endpoint Sendpoll (enquete), não amostra no celular do owner se for Android.

#### Descrição:
No aparelho que recebe a enquete visualiza e funciona tudo perfeitamente, Android ou Iphone, mas, se for enviado de um numero que esta logado em um android não mostra na tela do celular.

#### Passos para Reproduzir:
1. envie um sendpoll por uma instancia que o chip esta em um celular android
2. Veja na tela.

#### Comportamento Esperado:
Descreva o que você esperava que acontecesse quando seguisse os passos acima.

#### Comportamento Atual:
Explique o que realmente acontece quando você segue os passos acima.

#### Capturas de Tela/Vídeos:
Se possível, adicione capturas de tela ou vídeos que ilustrem o problema. Isso pode ser extremamente útil para entender o problema.

#### Ambiente:
- **Versão da API:** 1.7.4

**Comment by dpaes** [comment]
Caso esteja com o problema e esteja usando uma versão atual (v2) reabrirei a issue para analise, do contrario estarei fechando a issue pelo fato da versão 1 não estar mais recebendo atualizações de correções.
