### ISSUE TITLE
[PT][BUG] Evolution 1.6.1 e Chatwoot 3.1.1 não recebe mensagens, mas consegue enviar

### ISSUE THREAD

**Issue by filipi2601** [EvolutionAPI/evolution-api#602]
#### Descrição:
Descreva detalhadamente o problema que você encontrou. Inclua qualquer contexto relevante que possa ajudar a entender a origem do bug.

#### Passos para Reproduzir:
Receber uma mensagem do WhatsApp não cria uma nova conversa nem nada relacionado, simplesmente não acontece nada no ChatWoot. 
Se pesquisar um contato no Chatwoot e mandar uma mensagem, a mensagem é enviada normalmente.

#### Comportamento Esperado:
Receber mensagem e criar a conversa.

#### Comportamento Atual:
Não recebo nenhuma mensagem.

#### Ambiente:
- **Servidor:** [ex: Ubuntu 20.04]
- **Versão da API:** [ex:3.1.1]

#### Envio de Logs:
Não recebo erro algum, nem no container do Docker.

**Comment by Diglee147** [comment]
isso acontece até a versão atual quando tem muito fluxo de mensagens, por exemplo se fizer envio em massa, a caixa de entrada funciona até certo ponto, depois para de receber, só envia mensagens, não é no chatwoot.

**Comment by filipi2601** [comment]
será que pode ser alguma configuração no mongo que instalei pro evolution?... não to recebendo muito fluxo de mensagem

**Comment by filipi2601** [comment]
atualizei a versão do chatwoot e funcionou normalmente...
