### ISSUE TITLE
[PT][BUG] Evolution API v1.7.4 não está funcionando com ChatWoot 3.9.0 e 3.8.0

### ISSUE THREAD

**Issue by VinCardoso** [EvolutionAPI/evolution-api#605]
#### Descrição:
Não consegui fazer a conexão do Chatwoot 3.9.0 e 3.8.0 com a Evolution API v1.7.4

Aparentemente teve troca de várias coisas da versão 3.8.0 e 3.9.0 do Chatwoot que acredito que tenha quebrado a integração com a Evolution.

#### Passos para Reproduzir:
1. Após Instalado o Chatwoot e a Evolution API usando Docker/Portainer e tento 

#### Comportamento Esperado:
Que assim que configurado uma nova instância na Evolution que seja para Chatwoot ele já gere esse novo canal no Chatwoot e inicie a conversa com a Evolution com init e em sequência envie a imagem do QR code para escanear.

#### Comportamento Atual:
Hoje após criar a instância de Chatwoot na evolution é criado uma nova conversa e canal dentro do Chatwoot e abre a primeira conversa com o Bot da Evolution API dentro do Chatwoot com o Init como primeira mensagem, mas depois não tem nenhuma resposta.

E nos logs da Evolution aparece o erro do log abaixo.

#### Ambiente:
- **Servidor:** Debian 12
- **Versão da API:** Evolution API v1.7.4 // Chatwoot 3.9.0
- **Outras Especificações de Hardware/Software:** [ex: CPU, GPU]

#### Envio de Logs:

```
[Evolution API]    v1.7.4  1   -  Sun May 19 2024 09:11:17     ERROR   [ChatwootService]  [object]   
ApiError: Generic Error
    at catchErrorCodes (/evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:229:15)
    at /evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:257:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  url: 'https://suporte.[removido].com.br/api/v1/accounts/2/conversations/filter',
  status: 422,
  statusText: 'Unprocessable Entity',

{
    error: 'Chave de atributo inválido - [contact_id]. A chave deve ser uma das [status,assignee_id,inbox_id,team_id,priority,display_id,campaign_id,labels,browser_language,conversation_language,country_code,referer,created_at,last_activity_at,mail_subject] ou um atributo personalizado definido na conta.'
  },

  request: {
    method: 'POST',
    url: '/api/v1/accounts/{account_id}/conversations/filter',
    path: { account_id: '2' },
    query: { page: undefined },
    body: { payload: [Array] },
    errors: { '400': 'Bad Request Error' }
  }
}
```

**Comment by OtrisX** [comment]
Mesmo problema aqui, sabe qual versão do chatwoot para resolver isso com downgrade?

**Comment by juliancesar** [comment]
Tive que voltar para a versão 3.7.0 do CW!

**Comment by VinCardoso** [comment]
Fiz a mesma coisa aqui, voltei para o 3.7.0 porém tem ainda algumas coisas que não funciona, como trazer as conversas que foram mandado enquanto estava desconectado.

**Comment by juliancesar** [comment]
Hoje lançaram a versão *v1.7.5* da Evolution API, mas ainda continua com o problema com a versão v3.8 do CW!

**Comment by psifernandocardoso** [comment]
Aqui está funcionando normal. Estou utilizando a versão 1.7.4 da Evolution e a versão 3.9 do Chatwoot. O que acontece quando aí quando atualiza o chatwoot? Está atualizando o banco de dados após a atualização do chatwoot?

**Comment by juliancesar** [comment]
Depois de muitos testes acredito que o problema esteja relacionado a 2 coisas:

1. configuração do Chat Woot para utilizar o S3 em vez de local, aparentemente por causa da demora de alguns ms a mais ele deixa de carregar a imagem, mas se acessar depois ela pegando pelo console/network do navegador ela funciona
2. dependendo da configuração da comunicação entre o Evolution e o Chatwoot parace que também dá problema, se usar tudo passando pela internet, exemplo chatwoot.meumdominio.com e evolution.meudominio.com é mais fácil de funcionar, já se colocar os endereços/ips internos como por exemplo http://chatwoot.local:3000 e http://evolution.local:8080 ocorrem mais problemas apesar de ser muito mais rápido

Estes 2 pontos foi o que encontrei, mas aparentemente se colocar tudo em uma máquina só usando storage local no Chatwoot deve funcionar.

**Comment by Fagner-lourenco** [comment]
Aqui o mesmo problema...... 

`[Evolution API]    v1.7.5  1   -  Mon May 27 2024 22:47:35     WARN   [ChatwootService]  [string]  conversation not found 
[Evolution API]    v1.7.5  1   -  Mon May 27 2024 22:49:12     ERROR   [ChatwootService]  [object]   
ApiError: Unauthorized
    at catchErrorCodes (/evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:226:15)
    at /evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:257:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  url: 'https://atendimento.corujagpt.ai/api/v1/accounts/1/inboxes',
  status: 401,
  statusText: 'Unauthorized',

{
    errors: [ 'Você precisa entrar ou se cadastrar antes de continuar.' ]
  },

  request: {
    method: 'GET',
    url: '/api/v1/accounts/{account_id}/inboxes',
    path: { account_id: '1' },
    errors: { '403': 'Access denied', '404': 'Inbox not found' }`

**Comment by Fagner-lourenco** [comment]
Evolution API v1.7.4

**Comment by Fagner-lourenco** [comment]
nem com o down para chatwoot:v3.7.0

**Comment by OtrisX** [comment]
> nem com o down para chatwoot:v3.7.0

nessa versão ta funcionando aqui

**Comment by devloadingbr** [comment]
após fazer toda a integração padrão tive o mesmo problema, mas consegui resolver aqui.


eu consegui resolver, na configuração da url do webhook, na configuração do canal no chatwoot a url estava com erro de digitação

errado: https://evolution.teste.com.br//chatwoot/webhook/CSM_whatsapp_suporte

certo: https://evolution.teste.com.br/chatwoot/webhook/CSM_whatsapp_suporte

estava com "//" após o dominio, arrumei isso e funcionou na hora

chatwood 3.12.0 evolution 1.8.2

**Comment by danyllolobo** [comment]
Encontrei a Solução de uma forma muito simples. Verifiquem as variáveis de ambiente da Evolution API
por padrão a variável CHATWOOT_ENABLED vem como false, altere para true, e tente fazer a conexão novamente. Aqui funcionou.
