### ISSUE TITLE
[PT][BUG] Webhook - payload de documento com legenda

### ISSUE THREAD

**Issue by wcsouza** [EvolutionAPI/evolution-api#606]
#### Descrição:
Payload do webhook de documento com legenda esta fora do padrão dos demais e não está incluindo o base64, imagens abaixo mostrando a diferença entre payload de documento com e sem legenda

#### Passos para Reproduzir:
- Ativar o webhook com base64
- Enviar um documento com legenda

#### Comportamento Esperado:
Comportamento esperado é que o payload contenha o base64 e tenha o mesmo padrão dos outros tipos de mensagem. Não vejo necessidade de existir um tipo 'documentWithCaptionMessage'.

#### Comportamento Atual:
Conforme imagens abaixo, o payload de documento com legenda fora do padrão e não inclui o base64

#### Capturas de Tela/Vídeos:
![image](https://github.com/EvolutionAPI/evolution-api/assets/30270590/c0a26806-73d9-4c48-af5c-0ff2f040c56d)
Payload com legenda: Não tem base64 e com estrutura fora do padrão

![image](https://github.com/EvolutionAPI/evolution-api/assets/30270590/cedda52c-fa79-4454-b47c-18c26981ba32)
Payload sem legenda: Tem o base64 e segue o padrão os outros payloads.

#### Ambiente:
- **Servidor:** rodando imagem do docker
- **Versão da API: 1.7.4

**Comment by dpaes** [comment]
sugiro efetuar o mesmo teste em uma instalação com a versão 2 da api, já que para essa versão que está utilizando não está mais sendo feito correções. Caso o erro persista na versão mais atual, reabrirei a issue.
