### ISSUE TITLE
[PT][BUG] merge_brazil_contacts false SEMPRE COMO FALSE MESMO APÓS REQUERIR COMO TRUE- gh pr checkout 587 

### ISSUE THREAD

**Issue by guilhermejansen** [EvolutionAPI/evolution-api#610]
#### Descrição:
Adicionei dentro do payload de criar instancia e mesmo assim não ficou como true.

![image](https://github.com/EvolutionAPI/evolution-api/assets/52773109/1a15e67d-4885-4bfa-9627-204a1c15a41a)

**Comment by bergpinheiro** [comment]
Aqui ta funcionando na versão v1.7.5
![WhatsApp Image 2024-05-23 at 09 21 41](https://github.com/EvolutionAPI/evolution-api/assets/24882737/0bac1921-c651-4480-8ae8-fb3ec5712013)

**Comment by guilhermejansen** [comment]
> Aqui ta funcionando na versão v1.7.5 ![WhatsApp Image 2024-05-23 at 09 21 41](https://private-user-images.githubusercontent.com/24882737/333179793-0bac1921-c651-4480-8ae8-fb3ec5712013.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0OTYzNTQsIm5iZiI6MTcxNjQ5NjA1NCwicGF0aCI6Ii8yNDg4MjczNy8zMzMxNzk3OTMtMGJhYzE5MjEtYzY1MS00NDgwLThhZTgtZmIzZWM1NzEyMDEzLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QyMDI3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzRhYzgxM2NhMDVhNTA0NTA5ZDhlOWUzYWM5NDBkY2Q4MWQ4MDhiMjBmYjAxNTc1NGY5MjI2NzEyOTA3ZjA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YphYWfOziS9hkEQp0V5Z3JAHszIsTz3jPbj9QxQhUY4)

Só funciona se você setar com 

POST
{{baseUrl}}/settings/set/{{instance}}

no 

POST
{{baseUrl}}/instance/create 

não está validando.

**Comment by deivisonrpg** [comment]
Verifique o payload correto pra {{baseUrl}}/instance/create
O correto é passar com nome chatwoot_merge_brazil_contacts

https://www.postman.com/agenciadgcode/workspace/evolution-api/request/26869335-4beb6f83-dd99-4923-ac66-19cd2a5a3bfc?tab=body



Já para {{baseUrl}}/chatwoot/set/{{instance}}
Correto merge_brazil_contacts

https://www.postman.com/agenciadgcode/workspace/evolution-api/request/26869335-dc71dd1d-00ad-4560-96ee-27359d544512


Tenta ai e posta o resultado se não der eu tiro um tempo aqui pra olhar direitinho

**Comment by guilhermejansen** [comment]
> Verifique o payload correto pra {{baseUrl}}/instance/create O correto é passar com nome chatwoot_merge_brazil_contacts
> 
> https://www.postman.com/agenciadgcode/workspace/evolution-api/request/26869335-4beb6f83-dd99-4923-ac66-19cd2a5a3bfc?tab=body
> 
> Já para {{baseUrl}}/chatwoot/set/{{instance}} Correto merge_brazil_contacts
> 
> https://www.postman.com/agenciadgcode/workspace/evolution-api/request/26869335-dc71dd1d-00ad-4560-96ee-27359d544512
> 
> Tenta ai e posta o resultado se não der eu tiro um tempo aqui pra olhar direitinho

Tudo certo por aqui obrigado, realmente faltava o "chatwoot_"
