### ISSUE TITLE
Após reiniciar o servidor VPS as instâncias que estão desconectadas somem, alguma informação sobre?[EN][BUG]

### ISSUE THREAD

**Issue by wilsonjuniorbarros** [EvolutionAPI/evolution-api#612]
As instancias desconectadas somem do mongo e do manager, alguma informação ?

**Comment by cakrumen** [comment]
Olá, resolvi este problema utilizando o mongoDB na versão 1.7.1, porem se utilizar o mongo e redis junto da problema, optei por manter somente o mongo

**Comment by member3541** [comment]
estou com esse erro tambem quando reincia a vps desconecta todos

**Comment by member3541** [comment]
alguem esta com problemas no WEBSOCKET ?
