### ISSUE TITLE
[PT][FEAT] Melhora na troca de dados de mensagens multimedia no TypeBot

### ISSUE THREAD

**Issue by denilsonalexandre** [EvolutionAPI/evolution-api#616]
#### Descrição Detalhada:
Atualmente as mensagens multimedias enviadas para o Typebot, apenas contemplam em sua maioria das vezes, a URL da imagem, sem seus metadatos e de dificil acesso.

#### Racional:
Flexibilidade no uso para recursos avançados de conversação.

#### Exemplos de Uso:
Usuário que envia as mensagens, pode enviar multimedia para ser trabalhada pelo Typebot em automações melhores

#### Possíveis Implementações:
Enviar todo o payload do JSON para ser tratado, ou enviar o ID de identificação da mensagem para que seja recuperado pela API em uma função GET separada, por exemplo:

https://api-evolution/GetMessageMetadata/{{messageId}}
https://api-evolution/GetMessageContent/{{messageId}}
https://api-evolution/GetMessageContentBase64/{{messageId}}

Retornaria todos os dados, inclusive no caso de multimedia, a possibildade de realizar o download do Base64 de alguns conteudos, mas também permitiria o recebimento de dados de localização, em estruturas mais simples (sem o Base64)

**Comment by DavidsonGomes** [comment]
Resolvido na v2
