### ISSUE TITLE
[PT][BUG] Duplicação de envio de mensagens no Chatwoot + WhatsApp, versão 1.7.0 até 1.8.0

### ISSUE THREAD

**Issue by MattCarneiro** [EvolutionAPI/evolution-api#619]
Quando mensagens são enviadas via HTTP Request (API), quando está conectado ao Chatwoot ele duplica a mensage. Se a assinatura tiver ligada, ele assina e reeenvia a mesma mensagem. Quando a mensagem é enviada direto do WhatsApp, ele faz a mesma coisa. Só não faz isso se for enviada pelo Chatwoot. 

#### Capturas de Tela/Vídeos:
Se possível, adicione capturas de tela ou vídeos que ilustrem o problema. Isso pode ser extremamente útil para entender o problema.
![image](https://github.com/EvolutionAPI/evolution-api/assets/121469830/b8474d69-a626-4c4e-9b4f-dac9c695fb78)

#### Ambiente:
 ubuntu 22.04
 1.70 até 1.8.0

No print, eu fiz o downgrade pra versão 1.6.1, ai parou de duplicar.

**Comment by MattCarneiro** [comment]
@DavidsonGomes eae

**Comment by dpaes** [comment]
tenho de vez em quando esse problema no chatwoot em uma caixa de entrada por vez, porém no banco de dados está correto, tanto que ao reiniciar a página no chatwoot volta ao normal. Como volta ao normal, não corri atrás de abrir issue, usando versão 1.8.1 do evolution
