### ISSUE TITLE
Consumindo API Anthropic e OpenAI 

### ISSUE THREAD

**Issue by alissonryan** [EvolutionAPI/evolution-api#62]
Olá time.

Estou a consumir a API da Anthropic `https://docs.anthropic.com/claude/reference/getting-started-with-the-api`

Utilizando tanto o n8n ou o Typebot para enviar as mensagens para o meu WhatsApp, porém ele não envia. Deve ser por conta que a resposta que vem sem o \n

Com isso a evolution api não consegue enviar. Já tentei alterar via n8n porém sem chance. 

Essa é como a resposta vem da API:
![Screenshot 2023-08-14 at 15 41 47](https://github.com/EvolutionAPI/evolution-api/assets/40619781/b1c3ea11-ab57-49f9-b41c-fafd1ead1359)

**Comment by DavidsonGomes** [comment]
Questão fora do contexto da Evolution API

**Comment by alissonryan** [comment]
Só queria entender se é possível tirar o \n como pular linha? 

Anteriormente utilizava o codechat e migrei para a API de vocês.
