### ISSUE TITLE
 sending the automation is not complete

### ISSUE THREAD

**Issue by brunojfnet** [EvolutionAPI/evolution-api#623]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Need!
- Send message to all contacts who get in touch using automation (created conversation) within chatwoot

When creating a simple automation (to be executed with each conversation created) that contains text and an image, an error occurs that is not sent in full to the contact when the conversation starts!

### What did you expect?

I would like an adjustment so that the automation created within Chatwoot (about the conversation created) could send the text with its formatting plus the attached image.

### What did you observe instead of what you expected?

observed that at certain times only the image is sent and the text is ignored and at certain times only the text is sent and an error appears when trying to send the image

### Screenshots/Videos

![automacao_chatwoot](https://github.com/EvolutionAPI/evolution-api/assets/11096446/9629f088-b131-43f1-8be7-1316d89600eb)
![aviso_erro](https://github.com/EvolutionAPI/evolution-api/assets/11096446/37030ba6-eded-4af7-87fb-f2bf7e22f840)
![mensagem_recebida](https://github.com/EvolutionAPI/evolution-api/assets/11096446/d7a2d9ba-9317-4bcc-b9a8-4f265f1599f1)

### Which version of the API are you using?

Used evolution version 1.8.0

Used chatwoot-N version 3.9.5

both systems in docker swanr

### What is your environment?

Docker

### Other environment specifications

VPS on hetnezer 8core 16ram using mongodb

### If applicable, paste the log output

[_chatwoot_admin_chatwoot_app.1.ysrxse2qwy0hobu6tig37wc3b_logs.txt](https://github.com/EvolutionAPI/evolution-api/files/15488979/_chatwoot_admin_chatwoot_app.1.ysrxse2qwy0hobu6tig37wc3b_logs.txt)

### Additional Notes

the use of automation (conversation created) and so that with each new conversation the customer can be notified about any promotion or information relevant to their service

Note: an attempt was made to use a greeting but at the moment it ignores the _italics_ provided in the text for proper formatting and does not allow sending an image

**Comment by DeividMs** [comment]
I am facing the same error!

**Comment by anderson-longara-souchat** [comment]
estou enfrentando o mesmo erro na v2.0.7

**Comment by dpaes** [comment]
I suggest testing on an installation with the most recent version of evolution and also with a more updated version of chatwoot, remembering that we validated the integration with an installation of the official chatwoot and not the nestor one shown in the screenshots. In the meantime, I will be leaving the issue closed until I can demonstrate that the problem persists in the most current version.
