### ISSUE TITLE
Salvar o input de imagem de um usuário para uso no n8n

### ISSUE THREAD

**Issue by BlueFolks** [EvolutionAPI/evolution-api#627]
### Bem-vindo!

- [X] Sim, pesquisei solicitações semelhantes no [GitHub](https://github.com/code-chat-br/whatsapp-api/issues) e não encontrei nenhum.

### Qual tipo de recurso?

Funcionalidade

### Qual a motivação para a solicitação?

![image](https://github.com/EvolutionAPI/evolution-api/assets/126990885/dd4fcfeb-4a03-442f-ae25-087fc736179e)

Como na imagem acima, quero pegar um input de imagem do usuário, conectado a EvoApi... porém só retorna um arquivo .enc
E também não vem com o ID da mensagem pra fazer um request pro getBase64FromMediaMessage...
Logo fica inviável fazer uma automação que reconhece o conteúdo da imagem pra fazer alguma outra ação.

**Comment by oriondesign2015** [comment]
Duas opções que seria interessante (se tivesse) é ao invez de mandar o .enc mandar o id da mensagem (tendo o mongo acho que já seria possível) ou ter uma variável chamada de `{{ messageId }}` para pegar o id da mensagem (tipo um {{ messageType }}, assim poderíamos colocar um "set variables" de `{{ messageId }} = {{messageId }}` para conseguir pegar o id e enviar para o n8n. Independente de qual desses fosse escolhido (e eu gosto muito da primeira ideia) seria incrível.

**Comment by juniorgregio** [comment]
Muito útil!! Espero que entre

**Comment by NeritonDias** [comment]
Muito útil!

**Comment by Lsmelo80** [comment]
Realmente uma boa sugestão!

**Comment by otaviolube** [comment]
Concordo plenamente. Incluir um messageId seria muito útil!

**Comment by tizum** [comment]
Muito bom, seria ótimo usar o {{ messageId }} para fazer outras automações inclusive enviar uma reação para a mensagem

**Comment by DavidsonGomes** [comment]
Isso foi feito na v2
