### ISSUE TITLE
[PT] Configuração para uso da CloudAPI

### ISSUE THREAD

**Issue by jhonathas** [EvolutionAPI/evolution-api#630]
Olá, pessoal. 

Estou configurando aqui a API oficial do Whatsapp mas não achei um local documentado sobre qual URL eu uso na configuração de Webhook na meta. Alguem poderia me informar? Pois só dessa forma eu consigo receber mensagem.

**Comment by michaelvips** [comment]
De um Fetch Instances via api, no body ira ter o webhook_wa_business

![image](https://github.com/EvolutionAPI/evolution-api/assets/21130174/b9786ba6-02eb-405b-9b95-f758414afd83)

**Comment by jhonathas** [comment]
Vou testar e aviso aqui, Muito obrigado :)

**Comment by jhonathas** [comment]
@michaelvips obrigado pela resposta :) 

Consegui pegar os dados de acesso, mas uma coisa que está acontecendo é que ao colocar os dados no facebook meta, tá dando um erro lá. 


![image](https://github.com/EvolutionAPI/evolution-api/assets/28179/451dabe8-4f79-4d1d-aa6f-4064aa20e6a6)


Vc sabe o que poderia estar causando?

**Comment by michaelvips** [comment]
Vc criou essa instancia por onde? manager ou api ?

**Comment by jhonathas** [comment]
Criei via Manager. Vale a pena excluir e fazer via API né?

**Comment by michaelvips** [comment]
Na hora da criação colocou Cloud Meta ?

![image](https://github.com/EvolutionAPI/evolution-api/assets/21130174/d1888eb7-badb-4f75-9ab6-0c6cedbac993)

**Comment by jhonathas** [comment]
Sim, exatamente isso. 

Quando pediu o token, coloquei o Token que foi gerado na meta. E o número eu coloquei a Identificação do número de telefone que tem lá na meta. Eu consigo enviar mensagem, só nao consigo receber.

**Comment by michaelvips** [comment]
Não O token não é o gerado na meta.

________________________________
De: Jhonathas ***@***.***>
Enviado: Wednesday, June 5, 2024 11:17:54 AM
Para: EvolutionAPI/evolution-api ***@***.***>
Cc: Michael lima ***@***.***>; Mention ***@***.***>
Assunto: Re: [EvolutionAPI/evolution-api] [PT] Configuração para uso da CloudAPI (Issue #630)


Sim, exatamente isso.

Quando pediu o token, coloquei o Token que foi gerado na meta. E o número eu coloquei a Identificação do número de telefone que tem lá na meta. Eu consigo enviar mensagem, só nao consigo receber.

**Comment by michaelvips** [comment]
O token do meta é usado pra enviar as mensagens, na hora do webhook la deve usar o token da evolution

**Comment by jhonathas** [comment]
Sim sim. Na hora de criar a instancia eu usei o token da meta. Na hora de cadastrar o link do webhook eu estou colocando o token da instancia (o mesmo que aparece na api de fetchInstances do evolution)

**Comment by michaelvips** [comment]
Vamos criar juntos, me chama discord @michaelvips

**Comment by jhonathas** [comment]
Posso te chamar por volta das 13:50? Estou levando meu filho na escola e logo estarei de volta.

**Comment by TiagoGouvea** [comment]
@jhonathas @michaelvips  podem me dar uma luz de como fazer isso nas versões atuais?

Qualquer coisa que informo ao criar a instancia Cloud, ela diz que tá conectada.. não tô sacando qual é da sequência correta.

**Comment by michaelvips** [comment]
> [@jhonathas](https://github.com/jhonathas) [@michaelvips](https://github.com/michaelvips) podem me dar uma luz de como fazer isso nas versões atuais?
> 
> Qualquer coisa que informo ao criar a instancia Cloud, ela diz que tá conectada.. não tô sacando qual é da sequência correta.

me chama no discord

**Comment by GustavoSouza07** [comment]
oii, @michaelvips você ainda consegue ajudar via discord ?
