### ISSUE TITLE
Não lista as conversas nem os contatos da instancia

### ISSUE THREAD

**Issue by suissa** [EvolutionAPI/evolution-api#634]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

nem via manager está sendo listado as Conversas nem os Contatos, apenas os Grupos. Não sei o porquê.

Rodei o Docker/evolution-api-all-services, está rodando tudo corretamente, dá para acessar o MongoDb via MongoExpress e acessar a Evolution via manager, mas não faz as ações que deveria.

O enviar mensagem só lista os grupos e não está enviando mensagem, dá erro 400. Mas eu estou com a instancia conectada.

Não está dando nenhum erro no terminal.

### What did you expect?

Ver minhas mensagens e meus contatos e enviar mensagens

### What did you observe instead of what you expected?

Não lista nada nem envia as mensagens

### Screenshots/Videos

![Screenshot 2024-06-08 at 19 07 15](https://github.com/EvolutionAPI/evolution-api/assets/75607/d9d9e3d9-9d3d-43ba-b043-82e74f8bcaa3)
![Screenshot 2024-06-08 at 19 11 43](https://github.com/EvolutionAPI/evolution-api/assets/75607/d1692e92-dc1d-408a-968e-235065bd1c99)
![Screenshot 2024-06-08 at 19 19 40](https://github.com/EvolutionAPI/evolution-api/assets/75607/7742d93a-3893-446e-bb13-07d4bf043bc0)

### Which version of the API are you using?

1.8.0

### What is your environment?

Mac

### Other environment specifications

1,4 GHz Quad-Core Intel Core i5
8GB RAM

**Comment by dpaes** [comment]
Pelo fato dessa issue ser referente a versão da v1 na qual não terá mais correções, sugiro testar usando a versão mais atual da v2 no qual estaremos efetuando atualizações constantemente, caso este mesmo problema esteja acontecendo, comente que reabrirei a issue.
