### ISSUE TITLE
No Chatwoot,  importação de contatos, criação automática de marcador e tag nos contatos importados com o número do WhatsApp Origem

### ISSUE THREAD

**Issue by francisbreit** [EvolutionAPI/evolution-api#636]
Tipo de recurso: Funcionalidade

Notei que, quando possuímos (no Chatwwot) mais de uma caixa de entrada com a Evolution e, consequentemente, mais de um número WhatsApp (Instância), quando as diferentes instâncias eram setadas  para o modo de importação automática de contatos, os mesmos eram importados dos diferentes números e entravam no Chatwoot sem qualquer identificação a que número WhatsApp os contatos pertenciam.
Na importação  automática de Contatos seria perfeito se fosse criado um marcador e taguear todos os contatos importados com o marcador/ettiqueta essa que poderia ser o  número  respectivo do próprio WhatsApp Conectado (Origem da importação). 
Isto seria perfeito, por exemplo, nos casos em que forem realizadas eventuais campanhas e disparos de mensagens para os contatos, pois para os disparo de mensagens seria usado o remetente correto (dono dos contatos), isto é,  do qual os contatos foram originalmente importados, diminuido riscos de erros/banimentos no WhatsApp.

### Sugestões de implementação automática do marcador e tagueamento ao importar os contatos

![Captura de Tela 2024-06-09 às 10 30 51](https://github.com/EvolutionAPI/evolution-api/assets/5285287/764204f0-3e76-44b4-b004-3e2d51c83315)
No exemplo da imagem veja a sugestão de como seria o marcador (com o número origem) do qual os contatos são importados

![Captura de Tela 2024-06-09 às 10 34 54](https://github.com/EvolutionAPI/evolution-api/assets/5285287/fdd5c64f-cbcd-4f7c-8834-1ca55e950da8)
Na imagem acima veja como ficaria mais simples filtrar (via tag) os contatos pertencentes ao número ao qual pertencem.

**Comment by tizum** [comment]
faz sentido, bem importante poder identificar a origem da conexão do contato no chatwoot

**Comment by RaFaeL-Cunha** [comment]
Cara se tiver isso vai ser muito top por que hoje não sabemos de qual caixa de entrada vem o contato e fazendo as tags vai ser muito bom e facilitar muito sabendo a origem do contato.

**Comment by jucylenemelo** [comment]
Muito bom, eu sou a favor.

**Comment by ericocesar** [comment]
Perfeito. Importante demais essa feature.

**Comment by francisbreit** [comment]
Estou tentando criar essa funcionalidade e, caso eu tenha sucsso, subirei uma Pull Request!

**Comment by DavidsonGomes** [comment]
Olha ai!

<img width="901" alt="Captura de Tela 2024-06-12 às 15 01 34" src="https://github.com/EvolutionAPI/evolution-api/assets/24706726/9334232a-1eb3-4e04-9c03-7913edec3978">

**Comment by DavidsonGomes** [comment]
adicionado na v2 ja

**Comment by RaFaeL-Cunha** [comment]
cara vc é foda Davidson
