### ISSUE TITLE
A foto do perfil não aparece no chatwoot com números de telefone mexicanos

### ISSUE THREAD

**Issue by ismael7** [EvolutionAPI/evolution-api#637]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Fotos de perfil com números de telefone mexicanos (+52) não aparecem no chatwoot

### What did you expect?

Você deveria olhar as fotos do perfil no chatwoot, mas elas não aparecem

### What did you observe instead of what you expected?

1.- Conecte a API de evolução com chatwoot
2.- Enviar mensagem de um telefone no México

### Screenshots/Videos

<img width="411" alt="330534418-a1930d1a-a1af-4a85-963f-7d49275d80c5" src="https://github.com/EvolutionAPI/evolution-api/assets/32073211/bab4fea9-0cb3-4fcf-8d4f-0e53e1e67ad7">

### Which version of the API are you using?

1.8.1

### What is your environment?

Linux

### Other environment specifications

UBUNTU

**Comment by AudiXP** [comment]
Isto também está a acontecer com qualquer número. Não está a importar a foto do contacto do WhatsApp para o Chatwoot.
Além disso, o nome que importa é o do perfil, que muitas vezes não é o nome que está guardado no contacto telefónico. Consegui marcar "Importar contactos" e não basta extrair o nome do contacto.

![firefox_NBodHYrOxH](https://github.com/user-attachments/assets/d42daf1c-15b3-4544-8c5a-753bfd0bc85d)
![chrome_jmewYrMnXv](https://github.com/user-attachments/assets/3b8c65f6-f818-40fb-841f-bfb1f6161f23)

**Comment by ismael7** [comment]
Com telefones do Brasil ou dos Estados Unidos se mostrar a imagem do perfil
![Screenshot 2024-07-11 at 8 29 38 p m](https://github.com/user-attachments/assets/ba652544-c738-49a8-ade4-5df4c1e00952)
![Screenshot 2024-07-11 at 8 29 58 p m](https://github.com/user-attachments/assets/7f55b36a-24f9-4e81-baec-55ce559687b5)
![Screenshot 2024-07-11 at 8 32 05 p m](https://github.com/user-attachments/assets/97f5ce4f-e79f-4ec3-82ee-c97382f20929)

**Comment by eliezerazevedo** [comment]
eu também estou com esse problema no meu mongodb esta retornando todos os contatos como null.
![image](https://github.com/user-attachments/assets/95ec57d1-995f-455a-8e58-663c5c075fbd)

**Comment by pedrocfg** [comment]
Pelo que entendo, a API do WhatsApp não permite ver a foto de perfil dos contatos. Portanto, é impossível que essas imagens apareçam no ChatWoot, a menos que sejam carregadas manualmente.

**Comment by ismael7** [comment]
Se a foto deve aparecer, por exemplo com telefones dos EUA você olha a foto, ou mesmo do Brasil Aparentemente o problema é que é adicionado um número 1 no terceiro caractere e por isso falha, não deveria ter 1, ou seja, +52 (1 não deveria aparecer esse número) XXX XXXX

**Comment by ismael7** [comment]
Aqui está um exemplo de como funciona esse telefone mexicano só porque não vem com 1 no terceiro dígito.
![Screenshot 2024-09-27 at 9 29 02 a m](https://github.com/user-attachments/assets/eed5107a-ed60-44cb-8414-2ac3b97fb9ce)

**Comment by dpaes** [comment]
Pelo fato da issue ser baseada em uma versão que não recebe mais correções, sugiro subir uma instalação com evolution com versão mais atual e testar se persiste este problema. Caso persista, envie que reabrirei a issue

**Comment by mazierovictor** [comment]
Eu uso a versão 2.2.0 e tenho o mesmo problema!

**Comment by dpaes** [comment]
@mazierovictor abra uma issue com a versão 2.2.0, pois essa issue é com base em uma versão que não receberá novas correções.
@lmdrezende if ur problem its with the same version, will no longer have new fix, only if the problem is in an latest version, like 2.2.0
so confirm to me here or create another issue. This issue will gona still closed
