### ISSUE TITLE
Criar logs separados por instância

### ISSUE THREAD

**Issue by drauber** [EvolutionAPI/evolution-api#639]
### Bem-vindo!

- [X] Sim, pesquisei solicitações semelhantes no [GitHub](https://github.com/code-chat-br/whatsapp-api/issues) e não encontrei nenhum.

### Qual tipo de recurso?

Outro

### Qual a motivação para a solicitação?

Permitir a criação de logs individuais por instância. 
Tenho a Evo em produção com uns quarenta números conectados. Quando há algum problema é extremamente difícil encontrar o problema no meio de todos logs. Seria bom se houvesse a possibilidade de gerar os logs em arquivos individuais por instância.

Obrigado.

### Como o recurso deve ser desenvolvido?

Poderia ser criado no .env um parametro para criar arquivos de log por instância, e esses logs serem alimentados conforme opção.

**Comment by DavidsonGomes** [comment]
Cara então, na evolution ja tem o nome da instancia no log gerado, se der erro apresenta o nome da instancia no proprio log, recomendo desativar o VERBOSE na variavel de ambiente de logs

<img width="951" alt="Captura de Tela 2024-06-11 às 18 07 11" src="https://github.com/EvolutionAPI/evolution-api/assets/24706726/791bc430-cc05-42d0-9776-f0c154f2f351">

**Comment by drauber** [comment]
Bom dia!
Você rem razão @DavidsonGomes, mas algumas linhas, principalmente aqueles que aparecem com a tag [ChatwootService] ou [ChatwootRepository] não indicam referente a qual Insatância estão "trabalhando". Talvez manter no mesmo log seria uma hipótese melhor que a minha sugestão. _No meu caso era isso que eu estava rastreando, pois algumas caixas no Chatwoot não estavam recebendo as msgs_

Outros registros que aparecem aos montes na minha instância são esses, que eu não sei o que significam, tampouco atrelados a qual instância estão. Detalhe importante que no env.yml eu tenho Redis enabled=false.
![image](https://github.com/EvolutionAPI/evolution-api/assets/4416953/25e57e66-bfe9-4f41-9b39-4e47b8802a6d)

Valeu, muito obrigado

**Comment by drauber** [comment]
Para complementar, observe a primeira linha do print:
![image](https://github.com/EvolutionAPI/evolution-api/assets/4416953/bdc63c58-d97f-4d73-9f39-98a02c24ae50)

Nesse caso eu sei que tenho uma conta do CW que está suspensa. Mas, não consigo saber qual é a instancia da Evo que disparou a mensagem.

Valeu

**Comment by DavidsonGomes** [comment]
Corrigido na v2
