### ISSUE TITLE
Envio de mensagem em lote

### ISSUE THREAD

**Issue by FilSantos** [EvolutionAPI/evolution-api#641]
### Bem-vindo!

- [X] Sim, pesquisei solicitações semelhantes no [GitHub](https://github.com/code-chat-br/whatsapp-api/issues) e não encontrei nenhum.

### Qual tipo de recurso?

Funcionalidade

### Qual a motivação para a solicitação?

Imaginando que alguns clientes podem querer fazer o envio da mesma mensagem para os clientes sobre uma promoção(imagino isso para todos os metodos como mensagem, imagem, video e audio) mas sempre agrupados por tipo, imagino que fazer uma requisição do mesmo texto, e informar no array somente os telefones, com isso ira gerar um ganho de trafego de rede de entrada e consequentemente um uso de memoria da instancia menor

**Comment by DavidsonGomes** [comment]
Solicitação dessa feature vai contra a proposta da api, esse tipo de coisa deve ser feito do seu lado e usar a api para enviar as mensagens!
