### ISSUE TITLE
[Typebot] Sessão para conversa ativa

### ISSUE THREAD

**Issue by deivisonrpg** [EvolutionAPI/evolution-api#642]
### Bem-vindo!

- [X] Sim, pesquisei solicitações semelhantes no [GitHub](https://github.com/code-chat-br/whatsapp-api/issues) e não encontrei nenhum.

### Qual tipo de recurso?

Funcionalidade

### Qual a motivação para a solicitação?

Iniciar um fluxo do typebot em contato ativo.

### Exemplos de Uso

Um exemplo seria, via api enviar uma chamada de inicio de sessão para a evolution e ela colocar esse contato em um fluxo do typebot.

Ex:
Envio de lembrete de agendamento, com opções para confirmar, remarcar, falar com um atendente.

### Como o recurso deve ser desenvolvido?

Criar um endpoint de inicio de sessão ativa da evolution.

Seria enviado para esse endpoint um payload com o numero do contato e a identificação do fluxo do typebot, e a evolution iniciaria uma sessão e iniciaria o fluxo do typebot. Assim a conversa seria iniciada pelo typebot e seguiria por ali.

**Comment by DavidsonGomes** [comment]
Ja temos isso, no endpoint startTypebot
