### ISSUE TITLE
Bug Midia com Falha ( não abre ) Chatwoot Easypanel

### ISSUE THREAD

**Issue by cwmkthubconnect** [EvolutionAPI/evolution-api#648]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Quando envio Midia do Chatwoot para Whatsapp corrompido, na abertura

Mensagem 

 erro
 Falha ao carregar documento PDF

### What did you expect?

Abrir arquivo

### What did you observe instead of what you expected?

Esta dando bug

### Screenshots/Videos

![WhatsApp Image 2024-06-15 at 11 12 10](https://github.com/EvolutionAPI/evolution-api/assets/91642837/164a7f68-736f-4b94-9037-cbe3c04ab11e)
![WhatsApp Image 2024-06-15 at 10 38 57 (1)](https://github.com/EvolutionAPI/evolution-api/assets/91642837/b386452d-a014-42fc-9225-11b08600c4ce)
![WhatsApp Image 2024-06-15 at 11 12 20](https://github.com/EvolutionAPI/evolution-api/assets/91642837/94394520-5dff-4be1-ae6a-229eca8b6684)

### Which version of the API are you using?

Versão Evolution 1.8.1
CHatwoot Versão chatwoot:v3.9.0

### What is your environment?

Windows

### Other environment specifications

Usando Easypanel

### If applicable, paste the log output

Não possui log  arquivo chega só chega corrompido

**Comment by TrolljanO** [comment]
Irmão, eu não sei ainda como resolver o erro
Mas pelo que entendi analisando alguns logs, possivelmente são os bancos de dados postgres e redis que cria automatico no easypanel.
Eu estou com praticamente o mesmo problema, mas não recebo nenhuma mensagem.... nem texto.
Se conseguir algo, me avisa...

**Comment by cwmkthubconnect** [comment]
\Solução e apenas adicionar URL na variável do Sidekiq

FRONTEND_URL=https://www.meu.com.br

**Comment by edsonfast** [comment]
Meu está dessa forma aqui:
 FRONTEND_URL=https://$(PRIMARY_DOMAIN)

Mas continua com mesmo problema.

Mais alguma dica?

**Comment by masterkachu** [comment]
ESta com esse mesmo problema, na verdade era o dominio proprio que eu configurei, por algum bug ele continua buscando o anexo no endereço padrão que estava no momento da instalação.
Eu fiz o seguinte, em configuração de dominio do chatwoot, deixei os dos dominios, o original de instalação e o meu que eu configurei.

<img width="1221" height="761" alt="Image" src="https://github.com/user-attachments/assets/26132c90-8003-40ad-8d53-d674e899088f" />
