### ISSUE TITLE
Evo 2.0 + Api Oficial + Chatwoot

### ISSUE THREAD

**Issue by brunopinto123** [EvolutionAPI/evolution-api#650]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Fiz a integração da Evo 2.0 + Api Oficial + Chatwoot

Consigo enviar e receber mensagens de texto no Chatwoot
Não consigo enviar ou receber audio ou fotos no Chatwoot.

Este problema já acontecia na Evo 1.8

### What did you expect?

Minha expectativa é enviar e receber não apenas textos porém fotos e videos no chatwoot usando evo + api oficial + chatwoot.

### What did you observe instead of what you expected?

Consigo enviar e receber mensagens de texto no Chatwoot
Não consigo enviar ou receber audio ou fotos no Chatwoot.

### Which version of the API are you using?

evo 2.0 + chatwoot nestor 3.9.0 + api oficial whatsapp

### What is your environment?

Windows

**Comment by michaelvips** [comment]
Evo 2.0 ainda é alpha amigo, não é pra usar ainda.

**Comment by brunopinto123** [comment]
> Evo 2.0 ainda é alpha amigo, não é pra usar ainda.

é alpha justamente para usar e reportar os bugs encontrados, amigão...

**Comment by dpaes** [comment]
viu se não seria certificado ssl o problema? @brunopinto123  pq eu tava com problema de ouvir audio e enviar e o problema era certificado ssl.

**Comment by dpaes** [comment]
persiste o erro @brunopinto123 ?

**Comment by dpaes** [comment]
Fechando a issue até o autor @brunopinto123 confirmar se persiste o problema
