### ISSUE TITLE
Redis not working

### ISSUE THREAD

**Issue by rodrigocabraln** [EvolutionAPI/evolution-api#652]
### Bem-vido!

- [X] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

Once the .env is configured as the documentation shows to activate Redis, it is not possible to create an instance from the api or from evolutionManager

https://doc.evolution-api.com/pt/optional-resources/redis

### O que você esperava?

Activate redis as the documentation shows

### O que vc observou ao invés do que esperava?

EvolutionApi not working and always loading 

### Qual versão da API você está usando?

1.8.1

### Qual é o seu ambiente?

Linux

### Outras expecificações do ambiente

AWS Instance

### Se aplicável, cole a saída do log

[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:21     VERBOSE   [Redis]  [string]  connecting new redis client 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:21     VERBOSE   [Redis]  [string]  connected to new redis client 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:21     INFO   [Redis]  [string]  RedisCache initialized for groups 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:21     VERBOSE   [CacheService]  [string]  cacheservice created using cache engine: RedisCache 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:21     VERBOSE   [RepositoryBroker]  [string]  initializing repository without db 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:21     VERBOSE   [RepositoryBroker]  [string]  creating store path: /evolution/store 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:21     INFO   [Redis]  [string]  RedisCache initialized for instance 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:21     VERBOSE   [CacheService]  [string]  cacheservice created using cache engine: RedisCache 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:21     INFO   [Redis]  [string]  RedisCache initialized for ChatwootService 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:21     VERBOSE   [CacheService]  [string]  cacheservice created using cache engine: RedisCache 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:21     INFO   [Redis]  [string]  RedisCache initialized for baileys 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:21     VERBOSE   [CacheService]  [string]  cacheservice created using cache engine: RedisCache 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:21     VERBOSE   [WAMonitoringService]  [string]  instance created 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:21     VERBOSE   [WAMonitoringService]  [string]  checking instances without connection 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:21     INFO   [WA MODULE]  [string]  Module - ON 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:21     VERBOSE   [WAMonitoringService]  [string]  Loading instances 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:21     VERBOSE   [WAMonitoringService]  [string]  Redis enabled 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:21     VERBOSE   [CacheService]  [string]  cacheservice getting all keys 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:21     LOG   [SERVER]  [string]  HTTP - ON: 8080 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:24     VERBOSE   [InstanceRouter]  [string]  request received in fetchInstances 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:24     VERBOSE   [InstanceRouter]  [string]  request body:  
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:24     VERBOSE   [InstanceRouter]  [object]   
{} 

[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:24     VERBOSE   [InstanceRouter]  [string]  request query:  
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:24     VERBOSE   [InstanceRouter]  [object]   
{} 

[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:24     VERBOSE   [InstanceController]  [string]  requested fetchInstances (all instances) 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:24     VERBOSE   [WAMonitoringService]  [string]  get instance info 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:24     VERBOSE   [WAMonitoringService]  [string]  return instance info: 0 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:26     ERROR   [Redis]  [string]  redis disconnected 
[Evolution API]    v1.8.1  1   -  Mon Jun 17 2024 16:02:28     VERBOSE   [CacheService]  [string]  cacheservice has key: grggfdgdf

**Comment by eduardo-eller** [comment]
Estou com o mesmo problema

**Comment by NandoScout** [comment]
Eu tive o mesmo problema. Configurei para usar um servidor Redis e o erro parou de aparecer. (traduzido do espanhol)

**Comment by eduardochaves1** [comment]
mesmo problema aqui na 1.8.1

**Comment by andersonmenezesm** [comment]
> mesmo problema aqui na 1.8.1, no meu caso ele fica apenas spammando o `ERROR [Redis] [string] redis disconnected`

O meu está com esse mesmo problema, como vocês resolveram este problema do redis?

**Comment by JefersonBatistaSouza** [comment]
Eu Consegui resolver adicionando as variáveis de ambiente do redis, adicionei e tudo certo...

Agora o problema é que a mensagem do whatsapp chega no log, mas o bot não inicia...mas acho que e questão de configurar o webhook na evolutivon-api

**Comment by dpaes** [comment]
persiste o problema @rodrigocabraln ?

**Comment by dpaes** [comment]
pelo fato

**Comment by edgarleite** [comment]
In your .env file replace localhost to redis

CACHE_REDIS_URI=redis://redis:6379/6

**Comment by matsnascimento** [comment]
> In your .env file replace localhost to redis
> 
> CACHE_REDIS_URI=redis://redis:6379/6

Perfeito, aqui funcionou! Obrigado

**Comment by Victor-Almeida-Amorim** [comment]
> In your .env file replace localhost to redis
> 
> CACHE_REDIS_URI=redis://redis:6379/6

THAAAAAAAAAAAAAAAAANKSSSSSSSSSS

**Comment by ogvieira100** [comment]
Thanks Man @edgarleite

**Comment by rafariaeng** [comment]
THAAANKS @edgarleite
