### ISSUE TITLE
findMessages where clausule

### ISSUE THREAD

**Issue by danqr** [EvolutionAPI/evolution-api#653]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

A cláusula where para a chave "fromMe" funciona apenas com o valor true, com o falor false ela é ignorada.
{
    "where": {
        "key": {
            "fromMe": false
        }
    }
}

### What did you expect?

Ao inserir o valor false, apenas as mensagens que foram enviadas por mim devem aparecer.

### What did you observe instead of what you expected?

Todas as mensagens estão vindo sem filtrar as mensagens que não foram enviadas por mim

### Which version of the API are you using?

v2.0.0

### What is your environment?

Docker

**Comment by mzramna** [comment]
na versão 1.8.2 essa query funciona

**Comment by dpaes** [comment]
saberia me dizer qual versão especificamente você está usando da v2? E se também puder passar prints da tentativa e do que foi retornado.
