### ISSUE TITLE
Set Webhook for instance

### ISSUE THREAD

**Issue by danqr** [EvolutionAPI/evolution-api#655]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Erro ao modificar webhook de instância. 
O webhook permanece inalterado. Mesmo parando ou reiniciando a instância.

### What did you expect?

Ao enviar o post com o novo host, a instância deve atualizar com a nova url

### What did you observe instead of what you expected?

Ao fazer um post em {{baseUrl}}/webhook/set/{{instance}}, a resposta é satisfatória, porém, ao dar um {{baseUrl}}/webhook/find/{{instance}}, a url antiga permanece.

### Which version of the API are you using?

v2.0.0

### What is your environment?

Docker

### Other environment specifications

      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      
      - CACHE_REDIS_ENABLED=false

**Comment by guigagb** [comment]
Problema no prisma que dá um create ao chamar o endpoint
![image](https://github.com/EvolutionAPI/evolution-api/assets/42628942/519fe2c3-f9b6-4a0d-9b75-b043dd11c7e9)

**Comment by francisbreit** [comment]
Mesmo erro aqui
