### ISSUE TITLE
Evolution 2.0 alpha- Não atualiza quando, com typebot/update, deseja-se mudar um typebot previamente criado com palavra-chave (triggerType = keyword) para (triggerType = all)

### ISSUE THREAD

**Issue by francisbreit** [EvolutionAPI/evolution-api#656]
Foi criado um typebot com palavra-chave e ao tentar reverter (update) para aceitar qualquer palavra , não foi possível. 

### O que era esperado

alteração de um typebot com palavra-chave para sem palavra chave

### Observações

O response retorna em branco e a alteração  da variável triggerType não ocorre.

Versão Evolution V2.0 alpha
Linux

**Comment by dpaes** [comment]
Ainda persiste @francisbreit ? tentou usar uma versão mais atual?
