### ISSUE TITLE
EVO 2.0 - Criação de instância (Token already exists)

### ISSUE THREAD

**Issue by guigagb** [EvolutionAPI/evolution-api#657]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Ao tentar criar mais de uma instância sem passar token dá erro a partir da segunda instância: 
![image](https://github.com/EvolutionAPI/evolution-api/assets/42628942/ade20c18-37f4-4180-b590-e7cce329b7b0)

Ao que parece o token não tá sendo gerado automaticamente conforme informa a documentação:
![image](https://github.com/EvolutionAPI/evolution-api/assets/42628942/d42d9208-70ba-4190-b45c-357b8bcf0861)

Endpoint: POST Instance/create

### What did you expect?

Cria mais de uma instância sem fornecer token no payload.

### What did you observe instead of what you expected?

Erro: Token already exists

### Screenshots/Videos

![image](https://github.com/EvolutionAPI/evolution-api/assets/42628942/70e5d17d-3071-4471-a061-09b61c65aeb9)

### Which version of the API are you using?

2.0.0

### What is your environment?

Linux

**Comment by rjblancos** [comment]
Tengo el mismo problema. Lo has solucionado?. Gracias.

**Comment by dpaes** [comment]
A principio quando vc cria pelo manager, ele apresenta o token, quando vc cria via api, você precisa passar um token (a sua escolha). Sabe dizer se tentou efetuar esse teste em uma versão mais atual da v2?
