### ISSUE TITLE
remoteJid não está funcionando

### ISSUE THREAD

**Issue by EdimilsonMurer** [EvolutionAPI/evolution-api#659]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

remoteJid não está funcionando
remoteJid = {{remoteJid}}

### What did you expect?

Era para mostrar o numero do whatsapp com remoteJid

### What did you observe instead of what you expected?

váriável fica em branco

### Which version of the API are you using?

evolution 1.8.1
typebot 2.26.1

### What is your environment?

Linux

**Comment by Casmei** [comment]
Poderia me explicar melhor como você está implementando a captura desse remoteJid? Eu realizei um teste no typebot aqui, e aparentemente, está tudo ok!

<img width="698" alt="image" src="https://github.com/EvolutionAPI/evolution-api/assets/68354933/b1ee08d4-6ed8-4d85-a9d1-d5a853b1349d">

É importante saber, que essa variável só está disponível em conversas dentro do whatsapp, as vezes você pode estar testando a implementação web do typebot

Esperto ter ajudado!

**Comment by abcdefabio** [comment]
Galera, depois de adaptar a evolution api para chamar um endpoint que chama lá no n8n, consegui ver o envio da evolution api para o typebot e agora ele envia o json nesse formato abaixo, então para pegar o número do whatsapp e Nome do usuário no whats precisa incluir {{={{prefilledVariables.remoteJid}}=}}. Aqui foi de boa agora..espero ter ajudado.
{
        "prefilledVariables": {
          "remoteJid": "5511988883333@s.whatsapp.net",
          "pushName": "Fabio XXXXXXX",
          "instanceName": "BLABLABLANEWS",
          "serverUrl": "https://api.blablabla.com.br",
          "apiKey": "29438d08cbasdasgasb2794faserass32ad",
          "ownerJid": null
        }
