### ISSUE TITLE
Session fechada

### ISSUE THREAD

**Issue by calebetec** [EvolutionAPI/evolution-api#66]
Na minha evolution com typebot, percebo que quando um novo contato manda uma mensagem pra meu numero vinculado ao bot, ele ainda não tem session aberta, dessa forma a sessao é aberta, mas a mensagem que ele mandou o bot ainda fica em silencia. Quando ele manda uma segunda mensagem, ai sim o bot reage. Como tratar isto?

**Comment by rafaelcw8** [comment]
Estou com o mesmo problema, conseguiu alguma solução?

**Comment by DavidsonGomes** [comment]
Nao entendi muito bem, demonstre o ocorrido e mostre os logs e configurações realizado no typebot

**Comment by DavidsonGomes** [comment]
Fechado por falta de interação
