### ISSUE TITLE
EVO 2.0 - Não lista instâncias no manager e não conecta na instância.

### ISSUE THREAD

**Issue by triatochat** [EvolutionAPI/evolution-api#660]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Consigo listar as instâncias criadas no postman, no entanto não são exibidas no manager. Também não foi possível conectar a instância utilizando a API.

### What did you expect?

Listar a instância no manager e conectar e também através da API

### What did you observe instead of what you expected?

Tela em branco, mesmo existindo instanicas criadas. Ao tentar conectar através da API informa que a instância não existe.

### Which version of the API are you using?

2.0.0

### What is your environment?

Linux

**Comment by rafacpti23** [comment]
Tambem está acontencendo comigo, desisti por enquanto

**Comment by gabrielcmachado** [comment]
Isso é moleza, é que ele esqueceu de mudar o nome do objeto, era instanceName e ele mudou no retorno para name. Como não mudou no front não carrega a página. corrigi no meu aqui mas o ideal é subir uma atualização no git.

**Comment by dpaes** [comment]
Poderia informar se ainda está ocorrendo o problema? caso esteja, poderia tentar usar uma versão mais atual?

**Comment by flaviabanchieri** [comment]
Comigo está acontecendo também, não achei solução até agora

**Comment by dpaes** [comment]
@flaviabanchieri ja tentou usar uma versão como o 2.1.2 do evolution? como vc está subindo o evolution, via docker ou pm2?
