### ISSUE TITLE
Arquivo enviado no WhatsApp, não aparece no Chatwoot

### ISSUE THREAD

**Issue by 1ribhdev4** [EvolutionAPI/evolution-api#663]
### Bem-vido!

- [X] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

Estou usando a versão 1.8.0 do evolution e a versão 3.8.0 do chatwoot, está tudo funcionando normalmente, mas percebi que chegou um arquivo no WhatsApp, e no Chatwoot não.

### O que você esperava?

Que o arquivo enviado no WhatsApp aparecesse no Chatwoot

### O que vc observou ao invés do que esperava?

O Arquivo não apareceu

### Capturas de Tela/Vídeos
![fb46d055-203f-4b5b-8a9a-eb9fb44f9b4e](https://github.com/EvolutionAPI/evolution-api/assets/151800136/5bceddcd-9d1f-43c7-bcd5-f549e686d05c)

![1ea975bc-edb2-4869-a7c6-261539a55704](https://github.com/EvolutionAPI/evolution-api/assets/151800136/4480e5ae-e767-4083-8f6a-980fdc6bf32c)

### Qual versão da API você está usando?

1.8.0

### Qual é o seu ambiente?

Windows

### Outras expecificações do ambiente

Versão do Chatwoot: 3.8.0
Hospedado com Docker

**Comment by elberrd** [comment]
1ribhdev4 - você conseguiu resolver de alguma forma? O Chatwoot 3.10.2 e Evolution 1.8.1 não chega nenhuma mídia no chat do Chatwoot. Estou usando com o MINIO. Eu Chatwoot envia as mídias corretamente para o mínio, mas não chega no chat. As configurações de acesso no Minio estão corretas - fiz até um teste de deixat tudo publico só para ver se era um bug neste sentido, mas não consegui achar o problema

**Comment by 1ribhdev4** [comment]
> 1ribhdev4 - você conseguiu resolver de alguma forma? O Chatwoot 3.10.2 e Evolution 1.8.1 não chega nenhuma mídia no chat do Chatwoot. Estou usando com o MINIO. Eu Chatwoot envia as mídias corretamente para o mínio, mas não chega no chat. As configurações de acesso no Minio estão corretas - fiz até um teste de deixat tudo publico só para ver se era um bug neste sentido, mas não consegui achar o problema

Até então, aconteceu apenas uma vez, a mídia foi enviada no WhatsApp, e não aparecia no Chatwoot, mesmo após o mesmo contato enviar novamente, quando a mesma mídia foi enviada por outro contato apareceu normalmente. Acredito que foi algum bug com o dispositivo da pessoa.

**Comment by elberrd** [comment]
> > 1ribhdev4 - você conseguiu resolver de alguma forma? O Chatwoot 3.10.2 e Evolution 1.8.1 não chega nenhuma mídia no chat do Chatwoot. Estou usando com o MINIO. Eu Chatwoot envia as mídias corretamente para o mínio, mas não chega no chat. As configurações de acesso no Minio estão corretas - fiz até um teste de deixat tudo publico só para ver se era um bug neste sentido, mas não consegui achar o problema
> 
> Até então, aconteceu apenas uma vez, a mídia foi enviada no WhatsApp, e não aparecia no Chatwoot, mesmo após o mesmo contato enviar novamente, quando a mesma mídia foi enviada por outro contato apareceu normalmente. Acredito que foi algum bug com o dispositivo da pessoa.

Qual versão do Chatwoot e Evolution você está usando? - só para eu testar a mesma. Valeu

**Comment by 1ribhdev4** [comment]
> > > 1ribhdev4 - você conseguiu resolver de alguma forma? O Chatwoot 3.10.2 e Evolution 1.8.1 não chega nenhuma mídia no chat do Chatwoot. Estou usando com o MINIO. Eu Chatwoot envia as mídias corretamente para o mínio, mas não chega no chat. As configurações de acesso no Minio estão corretas - fiz até um teste de deixat tudo publico só para ver se era um bug neste sentido, mas não consegui achar o problema
> > 
> > 
> > Até então, aconteceu apenas uma vez, a mídia foi enviada no WhatsApp, e não aparecia no Chatwoot, mesmo após o mesmo contato enviar novamente, quando a mesma mídia foi enviada por outro contato apareceu normalmente. Acredito que foi algum bug com o dispositivo da pessoa.
> 
> Qual versão do Chatwoot e Evolution você está usando? - só para eu testar a mesma. Valeu

Chatwoot na 3.8.0 usando a instalação de VM
Evolution na 1.8.0 com docker

**Comment by dpaes** [comment]
estarei fechando essa issue pelo fato da evolution não estar mais corrigindo bugs na versão "1.8.0". Caso esteja com o problema na v2, trabalharemos para corrigir.
