### ISSUE TITLE
Evolution Api + Chatwoot: Problema com resposta de mensagem no chatwoot

### ISSUE THREAD

**Issue by hereck** [EvolutionAPI/evolution-api#664]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Estou usando a versão 1.8.1 mas tbm testei na 1.7.5

Quando respondemos uma mensagem diretamente pelo chatwoot, no chatwoot parece que esta tudo certo, mas no whatsapp ele responde referente a uma mensagem de outra conversa.
Não esta respondendo a mensagem correta e do mesmo contato.

### What did you expect?

Esperava que as respostas no chatwoot fosse refletido no whatsapp

### What did you observe instead of what you expected?

Observei que ele responde referente a ultima mensagem de outra conversa, e não referente a mensagem e conversa em questão.

### Which version of the API are you using?

Resposta no Chatwoot
![image](https://github.com/EvolutionAPI/evolution-api/assets/945739/b5b0aecf-9dcd-4202-82ec-0b2062d6f6b9)

Resposta no WhatsApp
![image](https://github.com/EvolutionAPI/evolution-api/assets/945739/d673bba1-1af3-441a-9ff4-7ce2d1067aff)

### What is your environment?

Linux

**Comment by hereck** [comment]
Estou com latest do chatwoot e com o evolution 1.8.2.
Mas o problema é o mesmo na versão 1.8.1.

Li algo sobre precisar persistir as mensagens com mongDB, mas ainda estou tentando descobrir em como fazer isso sem precisar de uma nova instalação.

**Comment by dpaes** [comment]
ja tentou testar com a evolution 2.0 beta em que o banco de dados passa a ser o postgres? quem sabe assim mudando o banco funcione. Mas sugiro fazer isso em um ambiente de testes e não no seu de produção se for o caso.

**Comment by pedrocfg** [comment]
Eu testei com Chatwoot v3.10.2 e Evolution 1.8.0
E com Chatwoot v3.11 e Evolution 1.8.2

E acontece o mesmo em ambos os lados =X

**Comment by dpaes** [comment]
teria q testar no 2.0 e usando postgres no lugar pra ver se o problema n seria no mongo msm.

**Comment by freebeans** [comment]
Estou tendo o mesmo problema. Vou investigar essa questão do mongoDB e testar o Evolution 2.0, se der algum resultado eu reporto aqui pra vocês.

**Comment by dpaes** [comment]
Estou fechando essa issue pelo fato do problema ser na v1 na qual não haverá novas correções, caso o erro persista na v2, trabalharemos para corrigir o mesmo.
