### ISSUE TITLE
Webhook não reconhece envio e recebimento de mensagens (MESSAGES_UPSERT)

### ISSUE THREAD

**Issue by lariguedes98** [EvolutionAPI/evolution-api#665]
Olá, algumas instâncias da minha evolution estão apresentando o seguinte problema: os eventos de envio e recebimento de mensagens no número não são reconhecidos (MESSAGES_UPSERT).

Assim que leio o QR code, tudo funciona normalmente. Mas uma meia hora/uma hora depois o webhook simplesmente deixa de captar as mensagens que são recebidas e enviadas. Em meio a alguns testes que fiz aqui, percebi que outros eventos continuam funcionando e chegando normalmente, mas os eventos de envio e recebimento de mensagem simplesmente deixam de ser captados.

Alguém já passou por algo assim? Há alguma solução?

Colocarei abaixo algumas imagens:

![image](https://github.com/EvolutionAPI/evolution-api/assets/109113901/e29da4f5-7370-4f77-a49c-6d92b735b53b)

![image](https://github.com/EvolutionAPI/evolution-api/assets/109113901/bad2b728-f8cb-4bc9-b50b-fb4f4b0ad9cc)

![image](https://github.com/EvolutionAPI/evolution-api/assets/109113901/811f46d7-16f0-4907-b405-612e0c31ccbc)

![image](https://github.com/EvolutionAPI/evolution-api/assets/109113901/d5976927-8643-4fcc-b847-414e31f2c019)

![image](https://github.com/EvolutionAPI/evolution-api/assets/109113901/1286d7a4-bcc5-45c1-b97f-b58368791570)

Testei nas versões: 1.81, 1.8.0 e 1.7.4

Todas apresentaram o mesmo problema.

Estou usando uma vps ubuntu 22.04 com 2 núcleos e 4gb de ram

**Comment by alissoncdarosa** [comment]
Acredito que a opção "Webhook por eventos" deva ser desmarcado para testar no cenário que você criou no N8n, com a opção marcada, cada tipo de evento cria um endpoint especifico. 

Confira na sessão Exemplos https://doc.evolution-api.com/pt/configuration/webhooks

Tenho o cenário que descrevi funcionando.

**Comment by matheus-pessoa16** [comment]
Também estou com mesmo problema. Meu webhook não funciona. Instalei via portainer com o Caddy fazendo reverse proxy... consigo enviar mensagens. O webhook está assim
![image](https://github.com/user-attachments/assets/9bca7aae-15ee-430f-b5f3-8effe3902d6a)

**Comment by GanchoDigital** [comment]
Olá! Conseguiu resolver?

**Comment by dpaes** [comment]
Estarei fechando a issue pelo fato de ocorrer em versões da v1, caso o erro persista ao utilizar o evolution v2, estaremos trabalhando para corrigir.
