### ISSUE TITLE
Instancia Desconectando 

### ISSUE THREAD

**Issue by Suporte4Mrk** [EvolutionAPI/evolution-api#67]
Ao Configurar uma Instancia dentro da promova web e conectar Com o WhatsApp após um longo tempo ele perde a conexão com a Instancia , não envia e nem receber as conversas dentro do Chat woot. então refazemos a Conexão com o QR code Novamente ele volta a funcionar.

**Comment by Suporte4Mrk** [comment]
![image](https://github.com/EvolutionAPI/evolution-api/assets/142536176/da331605-2b9e-4076-a04b-612330c2687a)

**Comment by mistercheff** [comment]
Esta acontecendo comigo, vc conseguiu uma solução?

**Comment by Suporte4Mrk** [comment]
Infelizmente Ainda não Encontramos , Estamos testando mas nada até então

**Comment by DavidsonGomes** [comment]
De acordo com testes internos e em clientes esse comportamento depende da maquina em que esta instalado a api, região e configurações

**Comment by DavidsonGomes** [comment]
Fechado por falta de interação
