### ISSUE TITLE
Função de ignorar grupo não funciona para fluxo typebot

### ISSUE THREAD

**Issue by filiperochalopes** [EvolutionAPI/evolution-api#670]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Marquei no `/manager` na minha instância a opção de ignorar grupos, porém o fluxo do typebot está sendo deflagrado ao registrar as palavras chaves dentro dos grupos também.

### What did you expect?

Que ao ignorar grupo, nenhuma mensagem de grupos fosse encaminhada na integração typebot

### What did you observe instead of what you expected?

Observei que as mensagens enviadas no grupo disparam fluxo no typebot

### Screenshots/Videos

![image](https://github.com/EvolutionAPI/evolution-api/assets/34348097/5498de54-92ca-4cb3-b7e4-a5eec49722b7)

![image](https://github.com/EvolutionAPI/evolution-api/assets/34348097/54742656-46a6-47c1-b0ec-c76b94ec2252)

![image](https://github.com/EvolutionAPI/evolution-api/assets/34348097/a4b9db58-f351-471f-ad45-c087e3495d81)

### Which version of the API are you using?

1.8.1

### What is your environment?

Docker

**Comment by filiperochalopes** [comment]
Pelo visto só acontece em alguns grupos, testei em outro grupo e rodou como esperado:

![image](https://github.com/EvolutionAPI/evolution-api/assets/34348097/551a2cab-d651-4df0-9826-ce8661d68097)

Existe algum bug conhecido sobre isso?

**Comment by dpaes** [comment]
Estarei fechando essa issue pelo fato de ser em uma versão que não terá novas correções, caso o erro persista em uma nova instalação usando a v2, trabalharemos para corrigir o mesmo.
