### ISSUE TITLE
[Comunidade] Não estou recebendo o convite para participar da comunidade

### ISSUE THREAD

**Issue by Casmei** [EvolutionAPI/evolution-api#671]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Eu entrei no link presente no repositório ([evolution-api.com](https://evolution-api.com/)), respondi o formulário com meus dados e cliquei para participar da comundiade.

### What did you expect?

Ao enviar o form, é retornado a seguinte mensagem "Você receberá uma mensagem no seu WhatsApp e no seu Email com o link para entrar na comunidade!". 

Eu esperava ter recebido uma mensagem em meu whatsapp ou um e-mail.

### What did you observe instead of what you expected?

Não recebi a mensagem pelo whatsapp e nem o e-mail, e eu gostaria muito de poder participar do comunidade!

### Which version of the API are you using?

Não se aplica

### What is your environment?

Windows

### Other environment specifications

Não se aplica

**Comment by dpaes** [comment]
ainda não conseguiu participar @Casmei ?

**Comment by Casmei** [comment]
O projeto tem um link do discord quebrado: https://discord.com/invite/NMZANQDXPk

<img width="1629" alt="image" src="https://github.com/user-attachments/assets/dbd43397-ef38-4f5d-89ea-5d2e6455c0c9" />
