### ISSUE TITLE
evolution-manager bug contatos versão 1.8.2

### ISSUE THREAD

**Issue by eliasmainetti** [EvolutionAPI/evolution-api#674]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Ao atualizar para a versão  1.8.2 da evolution, o manager passou a não importar os contatos e apresentar o seguinte erro:
![image](https://github.com/EvolutionAPI/evolution-api/assets/34216013/00239376-ecc3-4f8a-acb0-45030646404a)

### What did you expect?

Os contatos devem ser carregados e o manager deixar de apresentar o problema.

### What did you observe instead of what you expected?

Os contatos não são carregados

### Screenshots/Videos

![image](https://github.com/EvolutionAPI/evolution-api/assets/34216013/1fd98f76-67ab-4bf2-9049-cb9f68156811)

### Which version of the API are you using?

docker 1.8.2

### What is your environment?

Docker

### Other environment specifications

2GB 2 vCPU debian 11

**Comment by dpaes** [comment]
estou com o mesmo problema! to tentando mudar a versão do evolution para uma anterior ou duas pra ver se persiste, mas o problema começou esses dias, pq antes não tinha.

**Comment by dpaes** [comment]
Estou fechando essa issue pelo fato do erro ocorrer em uma versão que não terá novas correções, caso o problema persista em uma versão mais recente da v2 do evolution, trabalharemos para corrigir o quanto antes.
