### ISSUE TITLE
[Update] profilePicturePhoto precisa de atualização

### ISSUE THREAD

**Issue by pedrofarbo** [EvolutionAPI/evolution-api#677]
Fala time, 

Tivemos uma atualização na Baileys API especificamente na parte de busca da photo de profile pelo JID e precisamos atualizar aqui na evolution o consumo dessa API, pois quebrou o endpoint  fetchProfilePictureUrl e agora só trás a imagem do perfil do número owner da instancia e pro restante retorna null. 

Segue Pull Request da alteração: 
https://github.com/WhiskeySockets/Baileys/pull/901

**Comment by DavidsonGomes** [comment]
Ja esta na ultima versão

**Comment by viniciusverasdossantos** [comment]
A versão 2.0.4 esta retornando null 
{"wuid":"55210000000000@s.whatsapp.net","profilePictureUrl":null}

**Comment by viniciusverasdossantos** [comment]
> A versão 2.0.4 esta retornando null
> {"wuid":"[55210000000000@s.whatsapp.net](mailto:55210000000000@s.whatsapp.net)","profilePictureUrl":null}

A versão 2.0.4 esta retornando null
{"wuid":"[55210000000000@s.whatsapp.net](mailto:55210000000000@s.whatsapp.net)","profilePictureUrl":null}

**Comment by viniciusverasdossantos** [comment]
> Ja esta na ultima versão

A versão 2.0.4 esta retornando null
{"wuid":"[55210000000000@s.whatsapp.net](mailto:55210000000000@s.whatsapp.net)","profilePictureUrl":null}
