### ISSUE TITLE
O profileStatus nao esta retornando na versão v1.8.2

### ISSUE THREAD

**Issue by bergpinheiro** [EvolutionAPI/evolution-api#678]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Na nova versao v1.8.2 nao esta retonando o "profileStatus": do numero conectado

### What did you expect?

Exemplo do retono na v1.8.1:
![v181](https://github.com/EvolutionAPI/evolution-api/assets/24882737/d1269520-b712-40f2-a5cb-ccd48f377f2a)

### What did you observe instead of what you expected?

O que ta retonando na v1.8.2:
![v182](https://github.com/EvolutionAPI/evolution-api/assets/24882737/fd3b2e34-b111-4b28-840d-9fe975d09be1)

### Which version of the API are you using?

Teste na v1.8.2

### What is your environment?

Linux

**Comment by dpaes** [comment]
Estarei fechando a issue por conta da versão em que ocorre o problema não receberá novas correções, caso o problema persista em uma versão mais recente do evolution, trabalharemos o quanto antes para resolver.
