### ISSUE TITLE
send status stories text pending

### ISSUE THREAD

**Issue by grandaldeveloper** [EvolutionAPI/evolution-api#679]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Estou tentando enviar um texto story no status mas não aparece no status do whatsapp no qual tenho a sessão.

### What did you expect?

Esperava que aparecesse no storie do status do whatsapp.

### What did you observe instead of what you expected?

Observei que no resultado o status está pendente e talvez seja por isso que não foi enviado efetivamente.

### Screenshots/Videos

![image](https://github.com/EvolutionAPI/evolution-api/assets/57141235/8ea96ce0-f6b7-4a5c-9f71-99a93c894c36)

### Which version of the API are you using?

v1.8.2

### What is your environment?

Linux

### Other environment specifications

512 MB Memory / 10 GB Disk / SFO3 - Debian 12 x64

### Additional Notes

Não sei dizer se isso é realmente um bug ou se o whatsapp está impedindo de enviar para o status.

**Comment by EliasPereirah** [comment]
Mesmo aqui. Interessante é que no meu caso  o status é atualizado embora apareça como PENDING, mas não aparece nem para mim nem para os meus contatos que estão usando o WhatsApp no smartphone, mas para os contatos que estão no WhatsApp Web sim.

**Comment by grandaldeveloper** [comment]
Será que minha sessão precisa estar no Whatsapp Bussiness pra funcionar?

**Comment by silinhas** [comment]
Aqui estou com o mesmo problema!

**Comment by viniciusdebruin** [comment]
estou usando a evo 2.2.1 e nao consigo enviar nem texto, nem imagem quando o allContacts é true, somente quando é false e tem poucos contatos no "statusJidList", caso contratio da erro. 
Já no WhatsappWeb aparece essa mensagem quando envio o allContactos como true

![Captura de tela 2024-11-18 143950](https://github.com/user-attachments/assets/96c487f8-2466-4edd-9214-d9302a17c47e)

A verdade é que desde a versão 1.8 eu nunca consegui usar e agora apareceu uma oportunidade de integrar isso no meu sistema!
Já abri issues aqui a respeito, mas não localizei e tambem não vi resposta

**Comment by dpaes** [comment]
@viniciusdebruin abra uma issue como bug se não está tendo o comportamento devido

**Comment by dpaes** [comment]
Estarei fechando esta issue pelo fato da versão mencionada na mesma não estar recebendo novas correções. Caso o problema persista nas versões mais recentes (v2) estaremos trabalhando para resolver o mais breve possivel.

**Comment by clikalogo** [comment]
Olá @grandaldeveloper , tudo bem?
Também estou testando o envio de Status/Stories "/message/sendStatus/{{instance}}", e encontrei algumas inconsistências utilizando a EVO v2.2.0, queria confirmar algumas informações:

1.Na minha instância/número de teste, consigo postar(texto/imagem/video/audio) para todos os contatos ("allContacts": true) ou para os selecionados ("allContacts": false);
2. Os contatos recebem o status com sucesso. (instancia teste com 16 contatos);
3. Não testei Whatsapp web;
**4. A minha instância/número de teste, que fez a postagem do Status/Stories, não consegue visualizar o que postou;**

**A sua instância que posta o status, consegue visualizar o status que postou?**

Observações:
1. No manager, verifique se a sua instância/Número que irá enviar o status tem contatos ou está listando/reconhecendo os contatos;
2. No ENV verificar se DATABASE_SAVE_DATA_CONTACTS=true.

**Comment by efedezeta** [comment]
Mesmo problema EVO v2.2.3

**Comment by conext-noc** [comment]
Estou com o mesmo problema, também estou usando a versão v2.2.3 da Evolution API. O envio de texto funciona perfeitamente, mas, ao enviar botões, ele permanece pendente e não envia nada.

**Comment by BYMSA-DEX** [comment]
> Estou com o mesmo problema, também estou usando a versão v2.2.3 da Evolution API. O envio de texto funciona perfeitamente, mas, ao enviar botões, ele permanece pendente e não envia nada.

¿Cómo puedes enviar mensajes? A mí no me llega ninguno. Todos se quedan en estado «PENDING», es decir, en espera. ¿Has podido resolver este problema?
