### ISSUE TITLE
Relatório de Bug: Erro 400 ao Mencionar normal ou Fantasma com Grupos com Mais de 10 Usuários em Mensagens de Grupo

### ISSUE THREAD

**Issue by jmtechnologysp** [EvolutionAPI/evolution-api#683]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Ao enviar uma mensagem para um grupo com menções habilitadas, se o grupo tiver mais de 10 usuários, a API retorna um erro 400 Bad Request.

Passos para Reproduzir:

Use a API Evolution para enviar uma mensagem com menções em um grupo.
Certifique-se de que o grupo tem mais de 10 usuários.
Observe o erro 400 Bad Request.
Comportamento Esperado: A mensagem deve ser enviada com sucesso, mencionando todos os usuários no grupo.

Comportamento Real: A API retorna um erro 400 Bad Request.

Informações Adicionais:

Endpoint: /message/sendText
Delay: 1200 ms
Presence: composing
Mention: everyOne definido como true
Versão da API: Evolution API v1.7.1
Ferramentas Testadas: N8N, Typebot, Postman
Observação: A API consegue recuperar a lista de grupos e os IDs, mas não envia mensagens em grupos com mais de 10 usuários.

`{
  "number": "120363049259226458@g.us",
  "options": {
    "delay": 1200,
    "presence": "composing",
    "mentions": {
      "everyOne": true
    }
  },
  "textMessage": {
    "text": "{{MSG}}"
  }
}
`

### What did you expect?

A mensagem deve ser enviada com sucesso, mencionando todos os usuários no grupo como no mesmo numero porém com exito.
![grupo4pessoas](https://github.com/EvolutionAPI/evolution-api/assets/145302275/ea1d0812-804b-4afa-a96e-bdf0fdfeea3a)

### What did you observe instead of what you expected?

Ao enviar uma mensagem para um grupo com menções habilitadas, se o grupo tiver mais de 10 usuários, a API retorna um erro 400 Bad Request.

`    }
    },
    "timeout": {}
  },
  "response": {
    "statusCode": 400,
    "data": {
      "status": 400,
      "error": "Bad Request",
      "response": {
        "message": [
          "SessionError: No sessions"
        ]
      }
    }
  }
}

deu esse erro` no typebot
![grupocom46'11](https://github.com/EvolutionAPI/evolution-api/assets/145302275/1de84768-db77-4a9e-b34c-9e29a62eb6ae)
![grupocom46'1](https://github.com/EvolutionAPI/evolution-api/assets/145302275/ada87550-3096-44ec-b1fd-d16e10585bdb)
![grupocom46](https://github.com/EvolutionAPI/evolution-api/assets/145302275/b0968c8b-6c86-4f4b-bb47-b953d6a29514)

### Which version of the API are you using?

1.7.1

### What is your environment?

Windows

**Comment by jmtechnologysp** [comment]
O erro 400 ocorre devido a "No session" ao enviar mensagens em grupos maiores que 10 usuários via API Evolution (v1.7.1). Nem a marcação fantasma nem a normal funcionam, testado via N8N, Typebot e Postman.

**Comment by dpaes** [comment]
ja tentou usar uma versão mais atual @jmtechnologysp? por exemplo 1.8.1 da evolution-api?

**Comment by eduardochaves1** [comment]
![image](https://github.com/user-attachments/assets/842ef2fc-3d6a-4fbd-8ba7-e6727ef27bc8)

Eu percebi que quando dá o erro de No Sessions na instância, esses documentos aparecem no registro dessa instância do mongo

**Comment by eduardochaves1** [comment]
Uma dúvida, vocês estão com o redis ativado para salvar instâncias?

**Comment by dpaes** [comment]
Estou fechando a issue pelo fato da versão mencionada não estar mais recebendo novas correções. Caso o problema persista em uma versão mais recente (v2), estaremos trabalhando para corrigir o quanto antes.
