### ISSUE TITLE
vínculo meta cloud api + evolution api

### ISSUE THREAD

**Issue by arturritzel** [EvolutionAPI/evolution-api#684]
### Bem-vido!

- [X] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

estou tentando vincular um numero oficial da meta com o evolution, mas não tive sucesso. pesquisei e encontrei essa issue aqui: https://github.com/EvolutionAPI/evolution-api/issues/630 que não foi resolvida diretamente aqui no github, mas apresenta um problema que eu acredito ser igual ao meu. achei que nessa requisição estaria o url + token para definição do webhook lá nas configurações no developers.facebook.com mas não funciona com esse token

![image](https://github.com/EvolutionAPI/evolution-api/assets/70031851/7920c6a0-5225-400a-a0e1-466d28131e54)
![image](https://github.com/EvolutionAPI/evolution-api/assets/70031851/e88e83bf-7be3-4f48-ade6-75f21a469af8)

### O que você esperava?

vincular meu número oficial da meta com o evolution

### O que vc observou ao invés do que esperava?

![image](https://github.com/EvolutionAPI/evolution-api/assets/70031851/b0d2a5b7-8a18-46f8-b915-337ab8f4e7f5)

### Qual versão da API você está usando?

v1.8.2

### Qual é o seu ambiente?

Docker

**Comment by drauber** [comment]
![image](https://github.com/user-attachments/assets/d3722e38-1f6e-4476-87e0-2acb9df4f6ba)
No campo 1 coloque o seu id de telefone da meta.
No campo 2 coloque o seu token da meta. O mesmo que vc pega aqui 
![image](https://github.com/user-attachments/assets/8e878953-1671-4498-b04b-52096427b394)
ou o token permanente.
No seu env, verifique o que está presente no TOKEN_WEBHOOK 
![image](https://github.com/user-attachments/assets/fe614251-1d8d-4834-a93e-2b2570d52aa7)
![image](https://github.com/user-attachments/assets/973a100c-e10f-4690-89d7-724ea10b2441)

Espero ter ajudado

**Comment by arturritzel** [comment]
obrigado!

**Comment by TiagoGouvea** [comment]
Pode me ajudar @drauber? Como está esse fluxo para a versão atual?

Incluindo via interface ele pede dois dados, o token já vem digitado.

<img width="775" alt="Image" src="https://github.com/user-attachments/assets/8bc36a76-bf79-48dd-8d41-47609475d9d0" />

Lá no facebook tem o id do numero e do business, imagino que sejam os dois dados pedidos. Mas, é estranho, no Evolution o numero do telefone não é obrigatório..

Enfim, já fiz algumas combinações, e mesmo se eu só colocar uns números aleatórios, no evolution ele sempre mostra como se tivesse ativo/conetado.

Consegue me dar uma luz?

**Comment by drauber** [comment]
Olá @TiagoGouvea 
Tenho andado um pouco afastado desse projeto, mas me parece que vc está usando o token gerado pela Evo, não é esse que deve ser usado nessa janela.

![Image](https://github.com/user-attachments/assets/6aebbffd-4823-41dd-b4ae-8408ad0cd1c4)

Quanto a aparecer sempre conectado, é porque não há uma conexão "verdadeira", quando você define os parametros a caixa fica imediatamente disponível para uso e só vai ser acionada quando houver chamadas, não é igual ao espelhamento que precisa estabelecer uma conexão permanente com o websocket.
Observe que na configuração do APP na Meta
![Image](https://github.com/user-attachments/assets/ce881f21-4886-4c06-a049-fb0f65c9d7f1)

E o token esperado é o que consta no .env da sua instancia da evolution
![Image](https://github.com/user-attachments/assets/48072181-3c22-4507-9a77-4987cfeda31e)

Espero ter ajudado. 

Boa sorte

**Comment by TiagoGouvea** [comment]
Excelente!

Deu certo. Muito obrigado pela atenção @drauber !
