### ISSUE TITLE
Banimento constante de uma semana para cá 

### ISSUE THREAD

**Issue by wprime2018** [EvolutionAPI/evolution-api#687]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Estou sofrendo banimentos constante, mesmo mudando de número de telefone, quando ativo o servido de envio das mensagens o número acaba sendo banido em menos de 24h de ativação.

Tem algum conselho para que isso não ocorra mas...

Eu mudei o IP da minha hospedagem e começarei a testar a partir de amanhã, mas tem alguma regra para seguirmos?

### What did you expect?

asdfsdfsd

### What did you observe instead of what you expected?

afsdfsdf

### Which version of the API are you using?

1.8.1

### What is your environment?

Docker

### Other environment specifications

Hospedagem pela 4GB 3CPUs

**Comment by DavidsonGomes** [comment]
Recomendo o uso de proxy na sua operação

**Comment by wprime2018** [comment]
> Recomendo o uso de proxy na sua operação

Recomenda proxys do Brasil ou posso usar de outros países?

**Comment by jeronimo99** [comment]
Se enviar mensagens para vários números que não possuem o seu contato adicionado, o próprio whatsapp identifica como spam e bane o número.

**Comment by joaoanzolim** [comment]
> Boa tarde, tenho uma aplicação que basicamente é um gestor de agendamentos. Eu queria que meu cliente pudesse enviar uma mensagem para o cliente dele 1 hora antes do agendamento, é recomendado o uso dessa aplicação nesse caso? Meu cliente corre o risco de tomar banimento no telefone dele?

Acredito que não mestre, porque a mensagem que você irá enviar já é "esperada", então a probabilidade de você ser denunciado é extremamente baixa, diferentemente de quando o usuário dispara mensagens para diversos leads que nunca teve contato previamente.

**Comment by dpaes** [comment]
Estou fechando a issue pelo fato de não se tratar de um bug e sim de um risco que se tem ao usar api não oficial.
