### ISSUE TITLE
Erro no manager envio mensagem: l.map is not a function

### ISSUE THREAD

**Issue by 38ca** [EvolutionAPI/evolution-api#689]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Fiz update da versão 1.8.1 para 1.8.2.

### What did you expect?

Tive problema no envio de mensagem pelo manager, que geralmente uso pra testar após subir a aplicação.
Esperava listar os contatos e enviar uma mensagem de teste.

### What did you observe instead of what you expected?

Ao clicar na aba de mensagem retorna o erro: "l.map is not a function"

### Which version of the API are you using?

1.8.2

### What is your environment?

Linux

### Other environment specifications

2CPU - 6GB

**Comment by dpaes** [comment]
no 1.8.1 n tem esse problema, tive o mesmo problema q vc, dai dei o downgrade

**Comment by dpaes** [comment]
Estou fechando a issue pelo fato da versão mencionada não estar mais recebendo novas correções. Caso o problema persista em uma versão mais recente (v2), estaremos trabalhando para corrigir o quanto antes.
