### ISSUE TITLE
Envio de inumeras mensagem vazias em fila.

### ISSUE THREAD

**Issue by qualimagem** [EvolutionAPI/evolution-api#690]
### Welcome!

- [x] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

apenas menssage_upsert esta habilitada. Acontece em grupo.

### What did you expect?

nao enviar mensagens aleatorias, sem permissão.

### What did you observe instead of what you expected?

bug intermitente.

### Screenshots/Videos

nemhum.

### Which version of the API are you using?

1.8.2

### What is your environment?

Windows

### Other environment specifications

usando easypanel.

### If applicable, paste the log output

nenhum.

### Additional Notes

nenhum.

**Comment by dpaes** [comment]
Estou fechando a issue pelo fato da versão mencionada não estar mais recebendo novas correções. Caso o problema persista em uma versão mais recente (v2), estaremos trabalhando para corrigir o quanto antes.
