### ISSUE TITLE
Áudio não está sendo enviado

### ISSUE THREAD

**Issue by murilofernandesbr** [EvolutionAPI/evolution-api#692]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Áudio gravados no chatwoot não estão sendo enviados. Outros tipos de arquivo, como imagens, são enviados. Já verifiquei e a url está disponível, no log do container da Evolution existe a chamada, que é apresentada sem erros. 

### What did you expect?

Esperava que os áudios fossem enviados

### What did you observe instead of what you expected?

Observei que o áudio não está sendo enviado

### Which version of the API are you using?

Evolution API - v1.8.2
Chatwoot - v3.9.0

### What is your environment?

Windows

### Other environment specifications

Ubuntu 22.0.4 - VPS Hetzner
4 CPU - 8GB ram

**Comment by dpaes** [comment]
vc está emitindo corretamente o certificado SSL? se não, pode ser um impedimento por parte do navegador (já tive esse problema, depois de emitido corretamente o certificado voltou a funcionar)

**Comment by murilofernandesbr** [comment]
estou emitindo com lets encrypt via traefik
