### ISSUE TITLE
Endpoint `instance/restart/{$instanceName}` close the session

### ISSUE THREAD

**Issue by dnl4** [EvolutionAPI/evolution-api#693]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Called the endpoint `instance/restart/{$instanceName}`

### What did you expect?

Restart the instance

### What did you observe instead of what you expected?

The instance restarted and tried to auto connect again and sent 28 webhooks alternating the status `connecting`, `open`, `close` before stop

### Screenshots/Videos

<img width="531" alt="image" src="https://github.com/user-attachments/assets/ece89973-641a-4036-9fe8-52ec6b729b7f">

### Which version of the API are you using?

1.8.2

### What is your environment?

Mac

**Comment by dpaes** [comment]
Estou fechando a issue pelo fato da versão mencionada não estar mais recebendo novas correções. Caso o problema persista em uma versão mais recente (v2), estaremos trabalhando para corrigir o quanto antes.
