### ISSUE TITLE
archiveChat endpoint not working

### ISSUE THREAD

**Issue by salomonamiga** [EvolutionAPI/evolution-api#695]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

archiveChat endpoint is not working 
![WhatsApp Image 2024-07-14 at 2 09 33 p m](https://github.com/user-attachments/assets/c2f99e00-6f2e-4c98-a13b-e26d2c2281b6)

### What did you expect?

archive chats

### What did you observe instead of what you expected?

{
    "status": 500,
    "error": "Internal Server Error",
    "response": {
        "message": [
            {
                "archived": false,
                "message": [
                    "An error occurred while archiving the chat. Open a calling.",
                    "Error: Expected not from me message to have participant"
                ]
            }
        ]
    }
}

### Which version of the API are you using?

1.8.2

### What is your environment?

Windows

**Comment by salomonamiga** [comment]
if I change the "From me"
<img width="798" alt="SCR-20240714-mthr" src="https://github.com/user-attachments/assets/f197d6d9-e577-413c-b92c-ea2b45fd2874">

**Comment by dpaes** [comment]
Estou fechando a issue pelo fato da versão mencionada não estar mais recebendo novas correções. Caso o problema persista em uma versão mais recente (v2), estaremos trabalhando para corrigir o quanto antes.
