### ISSUE TITLE
fetchAllGroups não esta retornando os grupos

### ISSUE THREAD

**Issue by Shinaiders** [EvolutionAPI/evolution-api#696]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

estou tentando obter todos os grupos pela rota fetchAllGroups porem só esta vindo statuscode 200 e body vazio

### What did you expect?

esperava que viesse os grupos que participo

### What did you observe instead of what you expected?

venho um body vazio com statuscode 200

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/ccbae0f9-7e62-43ca-a0fe-5a1c4a6dee14)

### Which version of the API are you using?

![image](https://github.com/user-attachments/assets/b9f267e0-2c89-4992-bbd0-1672ca47dd82)

### What is your environment?

Windows

**Comment by dpaes** [comment]
vc precisa dar mais informações amigo, tem cada um dessas especificações exatamente para ser preenchida para quem for te dar suporte não precisar perguntar @Shinaiders. Por exemplo qual sua maquina virtual, linux, windows? Localhost ou Vps? qual versão do Evolution Api vc está usando? tudo que é pedido é importante.

**Comment by Shinaiders** [comment]
estou usando a que esta no print acima  'atendai/evolution-api:homolog'

estou usando um Ubuntu server 24.04

**Comment by oismaelash** [comment]
Estou com o mesmo problema **(status 200, retorno vazio),** 

Usando a imagem oficial dentro do AppRunner

[public.ecr.aws/inxptech/evolution-api:latest](https://gallery.ecr.aws/inxptech/evolution-api)

**Comment by Shinaiders** [comment]
nao teria uma solução?

**Comment by dpaes** [comment]
recomendaria usar uma versão mais estável @Shinaiders, n sei se vc está usando em produção, mas caso não esteja, use o 1.8.1 do evolution, pq a de homolog senão me engano é instável.

**Comment by tiagoandrepro** [comment]
Estou com o mesmo problema (status 200, retorno vazio)

**Comment by dpaes** [comment]
Estou fechando a issue pelo fato da versão mencionada não estar mais recebendo novas correções. Caso o problema persista em uma versão mais recente (v2), estaremos trabalhando para corrigir o quanto antes.
