### ISSUE TITLE
Imagem (e giphy) enviada pelo fluxo do Typebot só chega no Whatsapp Web

### ISSUE THREAD

**Issue by matheusfterra** [EvolutionAPI/evolution-api#70]
Olá pessoal, estou usando a API versão 1.5.0, que possui integração com o typebot.

Quando insiro uma imagem ou um giphy no fluxo do typebot, a mensagem é enviada corretamente e chega no whatsapp web, porém a imagem não chega no whatsapp do celular, alguém saberia o porque?

**Comment by matheusfterra** [comment]
Olá pessoal, descobri um fator relevante. 

Quando dentro do typebot é colocada a url da imagem terminando com sua extensão, por exemplo .png ou .jpg, a Evolution API envia corretamente. Porém se o seu Typebot está integrado com S3 para armazenar os arquivos, o link para a mídia não possui a extensão da imagem, e aí quando a API faz o envio, por algum motivo apenas no WhatsApp Web a mídia chega (inclusve se você pegar esse link da imagem armazenada no S3 e tentar enviar pela API via postman, apenas o Wpp Web recebe a imagem).

Mas se por exemplo, você fizer upload da imagem em algum servidor e ter acesso ao link da imagem com a extensão, e colocar esse link no typebot (ou mesmo enviando pela API via postman) a imagem é enviada para o celular também.

**Comment by matheusfterra** [comment]
Olá pessoal, descobri um fator relevante. 

Quando dentro do typebot é colocada a url da imagem terminando com sua extensão, por exemplo .png ou .jpg, a Evolution API envia corretamente. Porém se o seu Typebot está integrado com S3 para armazenar os arquivos, o link para a mídia não possui a extensão da imagem, e aí quando a API faz o envio, por algum motivo apenas no WhatsApp Web a mídia chega (inclusve se você pegar esse link da imagem armazenada no S3 e tentar enviar pela API via postman, apenas o Wpp Web recebe a imagem).

Mas se por exemplo, você fizer upload da imagem em algum servidor e ter acesso ao link da imagem com a extensão, e colocar esse link no typebot (ou mesmo enviando pela API via postman) a imagem é enviada para o celular também.

**Comment by DavidsonGomes** [comment]
Para resolver o problema com o s3, o link da imagem precisa ser publico
