### ISSUE TITLE
route /chat/fetchProfilePictureUrl/{{instance}} not-authorized at assertNodeErrorFree

### ISSUE THREAD

**Issue by joaosouz4dev** [EvolutionAPI/evolution-api#700]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

it is always returning this in some numbers
`
error =>  Error: not-authorized
    at assertNodeErrorFree (C:\workspace\whatsflow\evolution-api\node_modules\baileys\lib\WABinary\generic-utils.js:56:15)
    at query (C:\workspace\whatsflow\evolution-api\node_modules\baileys\lib\Socket\socket.js:145:48)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.profilePictureUrl (C:\workspace\whatsflow\evolution-api\node_modules\baileys\lib\Socket\chats.js:444:24) {
  data: 401,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}
`
`
  public async profilePicture(number: string) {
    const jid = this.createJid(number);

    try {
      return {
        wuid: jid,
        profilePictureUrl: await this.client.profilePictureUrl(jid, 'image'),
      };
    } catch (error) {
      console.log(error) // <<==
      return {
        wuid: jid,
        profilePictureUrl: null,
      };
    }
  }
`

### What did you expect?

the picture

### What did you observe instead of what you expected?

null

### Which version of the API are you using?

1.8.2

### What is your environment?

Docker

**Comment by dpaes** [comment]
Estou fechando a issue pelo fato da versão mencionada não estar mais recebendo novas correções. Caso o problema persista em uma versão mais recente (v2), estaremos trabalhando para corrigir o quanto antes.
