### ISSUE TITLE
Falta poder definir o S3 Region

### ISSUE THREAD

**Issue by madbuild3r** [EvolutionAPI/evolution-api#701]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Estou tentando utilizar o S3 da AWS e falta a opção para informar a região.
Ao executar a aplicação temos o erro no client do minio, pois está faltando passar a variável para ele.

### What did you expect?

Poder definir a região do s3 na aws

### What did you observe instead of what you expected?

amzBucketRegion: undefined

### Which version of the API are you using?

2.0.2

### What is your environment?

Docker

**Comment by DavidsonGomes** [comment]
Passa no endpoint

S3_ENDPOINT=s3.amazonaws.com # region: s3.eu-west-3.amazonaws.com
