### ISSUE TITLE
Boot para cada numero

### ISSUE THREAD

**Issue by tiagocaus** [EvolutionAPI/evolution-api#702]
### Bem-vindo!

- [X] Sim, pesquisei solicitações semelhantes no [GitHub](https://github.com/code-chat-br/whatsapp-api/issues) e não encontrei nenhum.

### Qual tipo de recurso?

Funcionalidade

### Qual a motivação para a solicitação?

Vincular um boot (Typebot, Flowwise, ...) para cada numero whatsapp.

### Exemplos de Uso

Cada numero conectado, possibilitar vincular um boot a ele. 

### Como o recurso deve ser desenvolvido?

Ter um crud para poder vincular a URL do boot (Typebot, Flowwise, ...) ao numero whatsapp.

**Comment by arturritzel** [comment]
Tenho 3 números linkados no evolution; cada um vinculado a um bot diferente no typebot. Não consegues fazer o mesmo? Peço perdão se entendi o post erroneamente

**Comment by tiagocaus** [comment]
@arturritzel, bom dia Artur, show, ainda não instalei, era uma dúvida que tinha. Obrigado pelo feedback.
