### ISSUE TITLE
Erro Argument `messageType` is missing. no prisma

### ISSUE THREAD

**Issue by jtapeg** [EvolutionAPI/evolution-api#703]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Erro Argument `messageType` is missing. no prisma
![Screenshot_6](https://github.com/user-attachments/assets/bc4f4132-260b-4f8e-a1e4-aef9cdab34fd)

### What did you expect?

Not error

### What did you observe instead of what you expected?

Not error

### Which version of the API are you using?

2.0.0

### What is your environment?

Linux

### Other environment specifications

CPU

**Comment by dpaes** [comment]
Poderia informar se ainda está tendo o problema e se já tentou em uma versão mais recente para ver se persiste o mesmo?
