### ISSUE TITLE
Evolution 2.0.2-beta: Start Typebot funciona apenas quando variável startSession=false, quando igual a true retorna Erro 500

### ISSUE THREAD

**Issue by francisbreit** [EvolutionAPI/evolution-api#704]
## Procedimentos realizados:

Criei um chatbot no Typebot e, como o mesmo é interativo, criei alguns inputs para coleta de informações.

## O que era esperado:

Enviar o Chatbot com o endpoint: {{baseUrl}}/typebot/start/{{instance}}, setando a variável startSession = true.

## Erro encontrado:

Retornou o erro 500, conforme informações que se seguem:

### Body utilizado:

{
    "url": "https://chat2.manualnegocioonline.com.br",
    "typebot": "chatbot1-xdnpx50",
    "remoteJid": "5517988460294@s.whatsapp.net",
    "startSession": true,
    "variables": [
        {
            "name": "pushName",
            "value": "Davidson Gomes"
        }
    ]
}

### Erro na resposta:

{
    "status": 500,
    "error": "Internal Server Error",
    "response": {
        "message": "\nInvalid `this.prismaRepository.typebot.create()` invocation in\n/evolution/dist/src/api/integrations/typebot/services/typebot.service.js:682:71\n\n  679     },\n  680 });\n  681 if (!findTypebot) {\n→ 682     findTypebot = yield this.prismaRepository.typebot.create({\n            data: {\n              enabled: true,\n              url: \"https://chat2.manualnegocioonline.com.br\",\n              typebot: \"chatbot1-xdnpx50\",\n              expire: 20,\n              keywordFinish: \"#SAIR\",\n              delayMessage: 1000,\n              unknownMessage: \"Mensagem não reconhecida\",\n              listeningFromMe: false,\n              stopBotFromMe: false,\n              keepOpen: false,\n              instanceId: undefined,\n          +   Instance: {\n          +     create: InstanceCreateWithoutTypebotInput | InstanceUncheckedCreateWithoutTypebotInput,\n          +     connectOrCreate: InstanceCreateOrConnectWithoutTypebotInput,\n          +     connect: InstanceWhereUniqueInput\n          +   }\n            }\n          })\n\nArgument `Instance` is missing."
    }
}

### Ao tentar enviar novamente, com o endpoint: {{baseUrl}}/typebot/start/{{instance}} , ocorreu o erro abaixo

{
    "status": 500,
    "error": "Internal Server Error",
    "response": {
        "message": "Cannot read properties of undefined (reading 'sessionId')"
    }
}

## Versão:

Evolution 2.0.2-beta

## Ambiente:

Linux

**Comment by agedigital1** [comment]
up. Também preciso dessa funcionalidade.

**Comment by HermesMacedo** [comment]
Up. @DavidsonGomes nunca pedi nada..hoje.. Man da uma força

**Comment by Jaya-Braga** [comment]
Opa! API 2.0, ficou top, só tem alguns detalhes, também estou precisando dessa correção para ficar 100%.

**Comment by suporteflowchatt** [comment]
opa. usava isso na versao anterior, se rolar nessa vai ser muito top

**Comment by midimagic2** [comment]
Na versão beta não está funcionando isso? Estou  usando a 1.8.2 e aqui está normal! Vou aguardar a correção e aí vou pensar em usar a versão oficial da Evolution 2 , quando sair

**Comment by laianeramos** [comment]
up 🆙

**Comment by joaoanzolim** [comment]
up

**Comment by dpaes** [comment]
up

**Comment by champsbrazil** [comment]
up . Muito importante que essa funcionalidade esteja ok

**Comment by egejo** [comment]
Up. Igual error aqui

**Comment by dpaes** [comment]
@francisbreit ainda persiste o erro? chegou a tentar em uma versão mais atual da v2?
