### ISSUE TITLE
l.map is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by nrsf** [EvolutionAPI/evolution-api#705]
### What did you do?

No MANAGER (1.8.2) -> Enviar Mensagem -> erro: l.map is not a function or its return value is not iterable

Não é possível enviar mensagem por aqui! 

![image](https://github.com/user-attachments/assets/f8602715-21e0-4174-bfed-590585b49117)

### What did you expect?

Enviar mensagem pelo MANAGER

### What did you observe instead of what you expected?

Impossível enviar mensagem pelo MANAGER

### Which version of the API are you using?

1.8.2

### What is your environment?

Docker

**Comment by buqmisz** [comment]
me too I face same issue. hope soon some expert help us

**Comment by outboxtecnologia** [comment]
I also face the same problem. Furthermore, it does not list the groups

**Comment by antonio-abrantes** [comment]
Downgrade to version v1.8.1, if you are using docker, replace latest with the tag 'atendai/evolution-api:v1.8.1'

**Comment by codsec** [comment]
any fix?

**Comment by nrsf** [comment]
None

Em ter., 27 de ago. de 2024 22:33, codsec ***@***.***>
escreveu:

**Comment by dpaes** [comment]
its a problem in v1.8.2, downgrade to 1.8.1 or wait for 1.8.3 version release (hoping this issue be solve)

**Comment by dpaes** [comment]
Estou fechando a issue pelo fato da versão mencionada não estar mais recebendo novas correções. Caso o problema persista em uma versão mais recente (v2), estaremos trabalhando para corrigir o quanto antes.

**Comment by guilherme-demarchi** [comment]
Boa noite. Tive esse erro usando o Manager, ao tentar usar a funcionalidade de enviar mensagens. Na lista de contatos não apareceu nenhum contato e foi mostrado o texto do erro (l.map is not a function), mas no botão Meus Contatos eles apareceram, então presumo que seja algo relacionado.

Utilizei a versão 1.8.5 via docker
