### ISSUE TITLE
Erro ao receber muitas mensagens ao mesmo tempo (como encaminhamento)

### ISSUE THREAD

**Issue by rafaeldf** [EvolutionAPI/evolution-api#707]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

O Evolution não está conseguindo processar quando recebe várias mensagens ao mesmo tempo. Para simular, estou encaminhando 7 mensagem para o Whatsapp integrado com o Evolution e recebo apenas algumas no Chatwoot ou no Webhook (n8n)

### What did you expect?

Receber todas as mensagens

### What did you observe instead of what you expected?

...

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/b9abe4c3-f6b2-4844-a0f8-3cb14513600f)

![image](https://github.com/user-attachments/assets/3c7b213d-c41d-4707-9f75-def126fa0b2d)

![image](https://github.com/user-attachments/assets/b59b1ff9-0784-4a43-8379-ae1323486cad)

### Which version of the API are you using?

1.8.2

### What is your environment?

Linux

### Additional Notes

Já habilitei o RabbitMQ e o erro persiste

**Comment by laianeramos** [comment]
Não sei se vai ser o seu caso, mas eu tive um problema parecido com o instagram e facebook no chatwoot: se eu mandasse várias mensagens em um curto espaço de tempo elas demoravam chegar e/ou não chegavam na ordem certa, mas era um problema de processamento das tarefas. Estava acontecendo o mesmo com outras pessoas em relação a outros canais, talvez seja o seu caso também. 

Eu resolvi alterando a prioridade das tarefas relacionadas aos webhooks do instagram e facebook (estavam como default e eu alterei para high ou medium), você pode testar e ver se resolve pra vc tbm.

Os arquivos ficam nesse caminho: /var/lib/docker/volumes/chatwoot_nestor/_data/app/jobs

Veja essa issue, aqui falei como resolvi e o pessoal do chatwoot deu outra sugestão (aumentar o número de containers do chatwoot).
https://github.com/chatwoot/chatwoot/issues/9728

**Comment by rafaeldf** [comment]
Olá @laianeramos obrigado por responder.

O pior que o webhook ta configurado direto no Evolution, justamente para ver se estaria enviando todas as mensagens. E o erro é exatamente o mesmo, como se ele recebesse apenas umas mensagens. E ainda é aleatório quais mensagens ele recebe.

**Comment by dpaes** [comment]
Estou fechando a issue pelo fato da versão mencionada não estar mais recebendo novas correções. Caso o problema persista em uma versão mais recente (v2), estaremos trabalhando para corrigir o quanto antes.
