### ISSUE TITLE
Mensagens de visualização única não chegam na Api e no chatwoot

### ISSUE THREAD

**Issue by laianeramos** [EvolutionAPI/evolution-api#708]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Ao receber uma mensagem de visualização única, nada é recebido na API e no chatwoot.

### What did you expect?

Que fosse recebido um aviso informando que é uma mensagem de visualização única e que só pode ser aberta no celular, igual acontece no whatsapp web/dispositivo conectado.

![image](https://github.com/user-attachments/assets/cd66c8b3-a2ff-4f7b-b997-fa02b93a074e)

![image](https://github.com/user-attachments/assets/2768ab4e-3bd8-47a7-b3cd-d468edb4b62e)

### What did you observe instead of what you expected?

Nada é informado, como se nada tivesse sido enviado, o que pode atrapalhar a comunicação e causar ruídos.

### Which version of the API are you using?

v1.8.2, mas o mesmo comportamento também foi observado na v2.0.2 Beta

### What is your environment?

Docker

**Comment by DavidsonGomes** [comment]
Comportamento do whatsapp web, não tem o que fazer

**Comment by laianeramos** [comment]
O comportamento do WhatsApp web é informar que tem a mensagem, sem mostrar o conteúdo. Isso não pode ser feito pelo API?

**Não estou falando de receber o conteúdo da mensagem**, mas apenas um aviso informando que chegou uma mensagem que só pode ser aberta no celular, exatamente igual acontece no WhatsApp web.

**Comment by laianeramos** [comment]
Consegui fazer uma automação no n8n.

![image](https://github.com/user-attachments/assets/acb33c75-b4b5-4035-a210-d8c7ddd973a0)

![image](https://github.com/user-attachments/assets/89ffe317-5f31-4194-91a3-45dbff4c7846)

**Comment by simpsss** [comment]
Boa tarde,

Algum jeito de receber no webhook quando tiver uma mensagem "viewonce" na versao atual? a ideia nao é ver o conteudo, mas precisamos apenas saber que teve uma mensagem do tipo viewonce.

Obrigado.

**Comment by jdgabriel** [comment]
> Consegui fazer uma automação no n8n.
> 
> ![image](https://github.com/user-attachments/assets/acb33c75-b4b5-4035-a210-d8c7ddd973a0)
> 
> ![image](https://github.com/user-attachments/assets/89ffe317-5f31-4194-91a3-45dbff4c7846)

Quais parametros vc está utilizando para verificar se a mensagem é `viewOnce`?
Pode me explicar sua config do n8n ?

**Comment by laianeramos** [comment]
> > Consegui fazer uma automação no n8n.
> > 
> > ![image](https://github.com/user-attachments/assets/acb33c75-b4b5-4035-a210-d8c7ddd973a0)
> > 
> > ![image](https://github.com/user-attachments/assets/89ffe317-5f31-4194-91a3-45dbff4c7846)
> 
> Quais parametros vc está utilizando para verificar se a mensagem é `viewOnce`?
> Pode me explicar sua config do n8n ?


Não sei se ainda vem assim no webhook, pq tem um tempinho que não uso a evolution. Mas eu havia feito dessa forma aqui. Quando é mensagem de visualização única, ele vem com esse paramento " viewOnce" no messageType, e também a extensão  indicado o tipo de mídia. 

![image](https://github.com/user-attachments/assets/014ac060-d067-4d0d-b4c5-0e9eb44cc603)

![image](https://github.com/user-attachments/assets/69eac4dd-1362-48f2-8ef6-899d2f6db283)

**Comment by laianeramos** [comment]
> > Consegui fazer uma automação no n8n.
> > 
> > ![image](https://github.com/user-attachments/assets/acb33c75-b4b5-4035-a210-d8c7ddd973a0)
> > 
> > ![image](https://github.com/user-attachments/assets/89ffe317-5f31-4194-91a3-45dbff4c7846)
> 
> Quais parametros vc está utilizando para verificar se a mensagem é `viewOnce`?
> Pode me explicar sua config do n8n ?

@jdgabriel Eu havia feito usando o messageType pra verificar se era viewOnce e, sendo viewOnce, qual a extensão pra identificar o tipo de mídia enviada. Tirei print pelo celular mesmo 😅 não sei se ainda funciona assim pq tem um tempinho que não uso a evolution api

![image](https://github.com/user-attachments/assets/d5904b79-5006-4c06-8106-6ef1f0e1b212)

![image](https://github.com/user-attachments/assets/236c39eb-1935-43f3-a79d-e688adf22f0a)
