### ISSUE TITLE
Quando mensagem do Número (remetente) é enviada , fluxo do Typebot interage como se fosse o contato!

### ISSUE THREAD

**Issue by francisbreit** [EvolutionAPI/evolution-api#71]
Testando Typebot, Evolution  (1.5.0) e Chatwoot v3.0.0, no inicio ou no meio do fluxo de um bot ativo, se vc manda uma mensagem do sender, o bot considera como interação. Seria interessante o bot escutar apenas  as mensagens do contato (incoming message) e nao do sender (outgoing message).

**Comment by DavidsonGomes** [comment]
Corrigido na versao 1.5.1
