### ISSUE TITLE
Sessões duplicadas no Typebot via API ao mudar status de sessão

### ISSUE THREAD

**Issue by hnmendes** [EvolutionAPI/evolution-api#710]
### Bem-vido!

- [X] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

O problema acontece quando tento pausar uma instância do typebot via api. 

Testei pela interface e funcionou como esperado, não foi criada uma nova sessão, apenas a sessão existente foi pausada.

### O que você esperava?

Quando pausar uma sessão do typebot via api (evolution) - ou a sessão seja mantida pausada, ou apagar as sessões antigas e criar uma nova seção pausada apenas.

### O que vc observou ao invés do que esperava?

Ao pausar uma sessão do typebot via api (evolution) - é mantida a sessão anterior aberta e criada uma nova sessão pausada.

### Navegando pela interface manager

Observa-se que uma nova sessão foi criada:

![image](https://github.com/user-attachments/assets/ab083af6-9969-42fe-b583-29dd47f2295a)

Após clicar em pausa e clicar em refresh:

![image](https://github.com/user-attachments/assets/dd55cb02-b417-4d7a-b9fa-b733c8931600)

Continua pausado:

![image](https://github.com/user-attachments/assets/c9bc5f55-6d99-4344-8bc4-9fc73ee73478)

E na API só possui uma única sessão - como exemplo da imagem abaixo após fazer uma requisição em {{baseUrl}}/typebot/find/{{instance}}:

```
{
    "enabled": true,
    "url": "https://mytypebotdomain.com.br",
    "typebot": "mytypebotid",
    "expire": 0,
    "keyword_finish": "#SAIR",
    "delay_message": 0,
    "unknown_message": "",
    "listening_from_me": false,
    "sessions": [
        {
            "prefilledVariables": {
                "remoteJid": "<usernumber>@s.whatsapp.net",
                "pushName": "UserName"
            },
            "remoteJid": "<usernumber>@s.whatsapp.net",
            "sessionId": "5775721186-clyyzatxk001x1nsbl8rvf55a",
            "status": "paused",
            "createdAt": 1721773187354,
            "updateAt": 1721773187354,
            "_id": "66a02c836bc147ab29f9a0a9"
        }
    ]
}

```

### Via API

![image](https://github.com/user-attachments/assets/443934b1-b014-4b7b-8c94-e94a2994da73)

Agora faço uma requisição em {{baseUrl}}/typebot/changeStatus/{{instance}}:

Request Body:
```
{
    "remoteJid": "<usernumber>@s.whatsapp.net",
    "status": "paused" /* opened, paused, closed */
}
```

Response Body:

```
{
    "typebot": {
        "instanceName": "<InstanceName>",
        "typebot": {
            "enabled": true,
            "url": "https://mytypebotdomain.com.br",
            "typebot": "mytypebotid",
            "expire": 0,
            "keyword_finish": "#SAIR",
            "delay_message": 0,
            "unknown_message": "",
            "listening_from_me": false,
            "sessions": [
                {
                    "prefilledVariables": {
                        "remoteJid": "<usernumber>@s.whatsapp.net",
                        "pushName": "UserName"
                    },
                    "remoteJid": "<usernumber>@s.whatsapp.net",
                    "sessionId": "9289568040-clyyzmntr00221nsb814q441p",
                    "status": "opened",
                    "createdAt": 1721773739315,
                    "updateAt": 1721773739315,
                    "_id": "66a02eab6bc147ab29f9a0f3"
                },
                {
                    "remoteJid": "<usernumber>@s.whatsapp.net",
                    "sessionId": "1529887655",
                    "status": "paused",
                    "createdAt": 1721773869024,
                    "updateAt": 1721773869024,
                    "prefilledVariables": {
                        "remoteJid": "<usernumber>@s.whatsapp.net",
                        "pushName": ""
                    },
                    "_id": "66a02f2d6bc147ab29f9a123"
                }
            ]
        }
    }
}
```

Atualizando na interface:

![image](https://github.com/user-attachments/assets/cbcf6dff-836b-49e3-9ba9-ed65bfb60a9f)

Duas sessões abertas, uma opened e outra paused:

![image](https://github.com/user-attachments/assets/f68c18b9-0c5d-4f42-b694-a7b286da5edb)

### Qual versão da API você está usando?

1.8.2

### Qual é o seu ambiente?

Linux

### Notas Adicionais

Dei uma vasculhada no código e vi que após o else nesse arquivo 

https://github.com/EvolutionAPI/evolution-api/blob/309d101b329f42cba538abc1dc2f067b870cb9f1/src/api/integrations/typebot/services/typebot.service.ts#L212

**Para o meu caso,** poderia ter a seguinte linha de código:

`await this.clearSessions(instance, remoteJid);`

Eu não sei se estou errado, mas o ideal seria que não fosse criada uma nova sessão e sim reutilizada uma já existente.

**Comment by patrickmarques** [comment]
Também estou tendo esse caso aqui. Existe alguma solução?

**Comment by dpaes** [comment]
creio que no 2.0 já está sendo resolvido isso, chegou a testar o evolution-api 2.0 beta? a principio mudou muita coisa e também com o typebot promete ser melhor em varios quesitos.

**Comment by oRafael07** [comment]
> creio que no 2.0 já está sendo resolvido isso, chegou a testar o evolution-api 2.0 beta? a principio mudou muita coisa e também com o typebot promete ser melhor em varios quesitos.

Estou na 2.0 beta e ainda não foi corrigido

**Comment by dpaes** [comment]
Estou fechando a issue pelo fato da versão mencionada não estar mais recebendo novas correções. Caso o problema persista em uma versão mais recente (v2), estaremos trabalhando para corrigir o quanto antes.
