### ISSUE TITLE
Erro Envio de Mensagem em Grupo

### ISSUE THREAD

**Issue by moskoweb** [EvolutionAPI/evolution-api#712]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Quando tenta enviar uma mensagem em um grupo, retorna erro de ID não identificado, mesmo sendo passado, na versão 1.8.1 estava funcionando.

### What did you expect?

Que a mensagem fosse enviada.

### What did you observe instead of what you expected?

```Cannot read properties of undefined (reading 'id')```

### Which version of the API are you using?

1.8.2

### What is your environment?

Docker

**Comment by dpaes** [comment]
tive varios problemas na 1.8.2, por isso hoje uso na 1.8.1 até a 2.0 ficar boa. Quem sabe na 1.8.3 seja corrigido esses pequenos erros.

**Comment by fabianob1m** [comment]
Aqui também ocorrendo o mesmo, tanto na 1.8.1 quanto na 1.8.2

**Comment by JuanxCursed** [comment]
Mesmo erro aqui tbm, alguem conseguiu resolver?

**Comment by JuanxCursed** [comment]
O erro acontece pela própria collection da EvolutionApi no postman tbm:
Basta setar o groupjId que o erro acontece.
<img width="1018" alt="image" src="https://github.com/user-attachments/assets/a3705bd8-434a-4cad-96ba-ddaa7bd23194">

**Comment by behappier-app** [comment]
mesmo problema......alguem testou algo diferente?

**Comment by manojsitapara** [comment]
@JuanxCursed I am getting same error in v2.1.0

**Comment by dpaes** [comment]
Estou fechando a issue pelo fato da versão mencionada não estar mais recebendo novas correções. Caso o problema persista em uma versão mais recente (v2), estaremos trabalhando para corrigir o quanto antes.
