### ISSUE TITLE
[Bug]: Modificar perfil da instância pelo manager

### ISSUE THREAD

**Issue by HELIOPOTELICKI** [EvolutionAPI/evolution-api#714]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Ao tentar modificar as informações do perfil da instância (Foto, Mensagem de apresentação, Nome), ocorre um bug que faz com que a instância fique em estado de "conectando" indefinidamente. Não é possível reconectar a essa instância, e ao tentar gerar um novo QR code, o mesmo não é gerado. A única solução encontrada é apagar a instância e recriá-la.

Steps to Reproduce:

- Modificar a foto, mensagem de apresentação ou nome do perfil de uma instância conectada.
- Observar que a instância entra em estado de "conectando". 

(Não é sempre que acontece, as vezes alterar a imagem funciona, nome/mensagem sempre da o erro)

![image](https://github.com/user-attachments/assets/9fe14c6a-743b-4b61-b56d-b57c297a5f78)

### What did you expect?

A instância deveria permitir a modificação do perfil sem entrar em estado de "conectando" indefinidamente e sem a necessidade de ser apagada e recriada.

### What did you observe instead of what you expected?

A instância entra em estado de "conectando" indefinidamente e não permite reconexão ou geração de novo QR code.

### Screenshots/Videos

https://github.com/user-attachments/assets/cb43cc03-837a-40f0-ba4e-5ef8ad15bcc8

### Which version of the API are you using?

EvolutionAPI: 1.8.2

### What is your environment?

Windows

**Comment by dpaes** [comment]
Por conta da versão mencionada ser 1.8.2 e ela não estar mais recebendo novas correções, estarei fechando esta issue. Atualmente só estamos trabalhando com a versão 2 do evolution para frente.
