### ISSUE TITLE
CRON Trigger para Typebot e Open AI

### ISSUE THREAD

**Issue by eliasmainetti** [EvolutionAPI/evolution-api#715]
### Welcome!

- [X] Yes, I have searched for similar requests on [GitHub](https://github.com/code-chat-br/whatsapp-api/issues) and found none.

### What type of feature?

Functionality

### What is the motivation for the request?

Permitir que o typebot e Open AI sejam acionados a partir de trigger de CRON. 

Atualmente a V2 permite trigger do bot baseado em palavras ou função regex. A ideia é adicionar mais uma função de trigger baseado em CRON. 

### Usage Examples

O cliente deseja iniciar o bot somente fora do horário comercial e nos finais de semana. 

### How should the feature be developed?

A feature poderia ser implementada a partir de um trigger CRON. 

### Additional Notes

Seria interessante que as funções de trigger de palavras tivessem a função AND e OR com o trigger de CRON

**Comment by DavidsonGomes** [comment]
Isso não é proposta da api, deve ser feito do seu lado
