### ISSUE TITLE
Envio de mensagem longa usando o curl não funciona

### ISSUE THREAD

**Issue by AXYONSOFTWARE** [EvolutionAPI/evolution-api#716]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Tenho uma automação rodando no n8n e toda vez que ela termina ela manda uma msg gerada pelo chatgpt para o evolution enviar como mensagem normal. Sendo que toda vez que a mensagem é muito grande. O evolution retorna um erro dizendo que o json não é válido e não envia a mensagem. Estou na versão 1.8.2, rodando ele na vps.

### What did you expect?

Esperava enviar a mensagem normalmente como ta funcionando com mensagens mais curtas

### What did you observe instead of what you expected?

Apenas o tamanho que influencia no envio. Quando a mensagem é curta ele roda normalmente.

### Which version of the API are you using?

1.8.2

### What is your environment?

Linux

### If applicable, paste the log output

NodeOperationError: JSON parameter need to be an valid JSON
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/HttpRequest/V3/HttpRequestV3.node.js:1083:35)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:655:42)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:596:68

**Comment by DavidsonGomes** [comment]
Esse erro nao é na evolution, realmente tem algum problema com a formação do seu json que ta sendo enviado no payload presta atenção se não tem algum quebra de linha em vez de usar o \n

**Comment by FEndo** [comment]
aqui o que funciona para mim é \\n
isso mesmo.. com duas barras.

**Comment by dpaes** [comment]
Estarei fechando esta issue pelo fato de a versão mencionada ser uma que não terá novas correções e sendo também que foi informado pelo desenvolvedor que não é um problema na evolution
