### ISSUE TITLE
FLUXO DE N8N EM MODO TESTE FUNCIONA NORMAL, QUANDO MUDA PRA PRODUTION NAO VAI NEM COM REZA

### ISSUE THREAD

**Issue by m4rcss-new** [EvolutionAPI/evolution-api#717]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Ola boa noite, de ontem pra ca começou a dar esse bug de nao funcionar quando mudo a url para prodution do n8n dentro do webhook da evolution, o que sera que pode ser?

### What did you expect?

ok

### What did you observe instead of what you expected?

ok

### Which version of the API are you using?

1.8.2

### What is your environment?

Windows

### Other environment specifications

vps

**Comment by DavidsonGomes** [comment]
Dificil saber sem informações de logs da evolution

**Comment by gabrielmedsantos** [comment]
> ### Welcome!
> * [x]  Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.
> 
> ### What did you do?
> Ola boa noite, de ontem pra ca começou a dar esse bug de nao funcionar quando mudo a url para prodution do n8n dentro do webhook da evolution, o que sera que pode ser?
> 
> ### What did you expect?
> ok
> 
> ### What did you observe instead of what you expected?
> ok
> 
> ### Screenshots/Videos
> _No response_
> 
> ### Which version of the API are you using?
> 1.8.2
> 
> ### What is your environment?
> Windows
> 
> ### Other environment specifications
> vps
> 
> ### If applicable, paste the log output
> _No response_
> 
> ### Additional Notes
> _No response_

Conseguiu resolver? Estou com o mesmo problema

**Comment by dpaes** [comment]
Estarei fechando esta issue pelo fato da versão mencionada não estar mais recebendo novas correções, estaremos concentrando nossos esforços apenas na v2 do evolution em diante.
