### ISSUE TITLE
Whatsapp business keeps disconnecting.

### ISSUE THREAD

**Issue by doryashar** [EvolutionAPI/evolution-api#718]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

i have whatsapp business app on my phone. i have installed the evolution api and successfully attached it with my own private number and chatwoot.
now i wish to connect the office number as well. i am using a phone with whatsapp business installed on it.
whenever i connect this number (link the device to evolution) - it succeed and i am able to send message from chatwoot out. but whenever i receive a message the evolution gets unlinked.

tried to link from both iphone and android.

### What did you expect?

i would expect the connection to remain and be able to see messages on chatwoot

### What did you observe instead of what you expected?

disconnection and no messages

### Which version of the API are you using?

Versão: 0.4.13

### What is your environment?

Docker

### Other environment specifications

caprover

**Comment by dpaes** [comment]
As the mentioned version is no longer receiving fixes and we are focusing our efforts only on evolution v2 and any later. I will be closing this issue for that reason.
