### ISSUE TITLE
Versão 1.5 Não gera conversa

### ISSUE THREAD

**Issue by R4T0** [EvolutionAPI/evolution-api#72]
Boa galera, estou testando a  API e resolvi fazer um upgrade da 1.4 para 1.5. Rodei o mesmo curl para criar instância, gerar a inbox e criar o QRcode. Todas essas etapas são efetuadas, porém ele não está criando o Qrcode.

curl -X POST http://172.16.1.12:8080/instance/create \
  -H "apikey: B6D711FCDE4D4FD5936544120E713976" \
  -H "Content-Type: application/json" \
  -d '{
    "instanceName": "05whats",
    "token": "",
    "qrcode": true,
    "chatwoot_account_id": 1,
    "chatwoot_token": "CNieqJZJy2f6FDFoqDSKKKKK",
    "chatwoot_url": "http://172.16.1.12:3000",
    "chatwoot_sign_msg": true,
    "chatwoot_reopen_conversation": true,
    "chatwoot_conversation_pending": false
}'

![image](https://github.com/EvolutionAPI/evolution-api/assets/73944522/1104ca05-35a5-4cf7-9f85-e871ffffde71)
![image](https://github.com/EvolutionAPI/evolution-api/assets/73944522/c5a3afad-eba2-4c32-9f19-9c0fb937517f)
![image](https://github.com/EvolutionAPI/evolution-api/assets/73944522/b939732b-3f9b-4138-824d-5f6378987c13)
Além disso, não consigo criar pelo manager também. Tanto por IP interno quando por IP externo
![image](https://github.com/EvolutionAPI/evolution-api/assets/73944522/0659c565-ab57-4632-afc3-a0ac1af95ea9)

**Comment by rnfrafael** [comment]
Você deve ter colocado a GlobalApi incorreta, checa o valor dela

**Comment by R4T0** [comment]
pra resolver precisei reinstalar a API, e utilizar o certificado ssl... Caso contrário não deu
