### ISSUE TITLE
Duplicated conversations

### ISSUE THREAD

**Issue by matisidler** [EvolutionAPI/evolution-api#720]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

I'm running a Chatwoot + Evolution instance. Everything was working fine until last week. I don't know why, but some conversations are duplicated. For example:
Conversation 1:
<img width="854" alt="image" src="https://github.com/user-attachments/assets/65d13538-1379-4734-aa1b-025a9a7f8bcf">
Conversation 2:
<img width="839" alt="image" src="https://github.com/user-attachments/assets/7d73fbc7-94e3-4d41-8fc6-e001d76601c8">

It's the same phone number, WhatsApp ID, etc. But it appears like two different conversations. The customer only sent one message.
<img width="423" alt="image" src="https://github.com/user-attachments/assets/3e57d111-7201-450d-8826-d5d2290a31c8">

By the way, I only have one inbox and one connected phone number. That's it.

### What did you expect?

If a person is sending a single message from a single phone number, I expect to see only one new conversation in my Chatwoot instance, instead of two.

### What did you observe instead of what you expected?

Mentioned above :)

### Which version of the API are you using?

1.8.1

### What is your environment?

Docker

### Additional Notes

This started about a week ago. Before, it was working fine. I haven't changed anything. If more info is needed, I'm more than happy to collaborate to solve this issue!

**Comment by dpaes** [comment]
already occur that with me, but its one or two times, and in tests. In production never seen something like that.

**Comment by matisidler** [comment]
@dpaes have you found a way to solve this? It's currently happening in production and I'm kind of desperate haha

**Comment by dpaes** [comment]
no, only occur in test, and the users never said to me if still with this problem, only occur with me in tests.

**Comment by dpaes** [comment]
whats ur chatwoot version? and in instances of evolution, how u config in chatwoot integration and behavior of instance in evolution? Using the /manager u can see this

**Comment by dpaes** [comment]
i'm closing this issue because the mentioned version in ur post its 1.8.1, that version of evolution its not receiving any fix, so i will close because of that.
