### ISSUE TITLE
Envio aleatorio de mensagens vazias

### ISSUE THREAD

**Issue by qualimagem** [EvolutionAPI/evolution-api#721]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Aleatoriamente a api envia varias mensagens vazias em fila. Apenas o evento "MENSAGES_UPSERT" está selecionado. 

### What did you expect?

Eu espero não receber nenhuma mensagem vazia.

### What did you observe instead of what you expected?

acontece as vezes 2 ou 3x por dia.

### Screenshots/Videos

![Captura de tela de 2024-07-28 21-11-13](https://github.com/user-attachments/assets/a4ea3afe-386f-4026-9c33-1ecf9e71de1e)

### Which version of the API are you using?

1.8.2

### What is your environment?

Linux

### Other environment specifications

uso ubuntu e railway, mas tbm acontece do eeasypanel.

**Comment by dpaes** [comment]
ja tentou usar a versão 1.8.1 pra ver se persiste?

**Comment by qualimagem** [comment]
persiste a varias versões...


Em qui., 1 de ago. de 2024 às 14:53, Daniel Paes ***@***.***>
escreveu:

**Comment by dpaes** [comment]
Fechando esta issue pelo fato da versão mencionada não estar mais recebendo novas correções. Caso precise de ajuda com a nova versão, nos chame nos foruns do discord, whatsapp ou outro meio no qual a comunidade do evolution estiver inserida.
