### ISSUE TITLE
Bug ao postar status/stories no WhatsApp

### ISSUE THREAD

**Issue by trxsistemas** [EvolutionAPI/evolution-api#722]
### Bem-vido!

- [X] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

Decidi usar o endpoint para postar status/stories no WhatsApp e percebi algumas diferenças no comportamento entre o WhatsApp "normal" e o WhatsApp Business. Quando você posta um status no WhatsApp "normal", ele só aparece no WhatsApp Web e apenas para os contatos que foram selecionados para visualizá-lo. Se você definir para mostrar para todos, o status não aparece para ninguém e também não fica visível para quem o postou. Por outro lado, ao usar o WhatsApp Business, o status/stories aparece tanto para todos os contatos selecionados quanto para todos os contatos se a opção de exibição para todos estiver ativada. No WhatsApp Business, o status é visível tanto no WhatsApp Web quanto no celular, mas não fica visível para a pessoa que postou o status/stories.

### O que você esperava?

Esperava que o status/stories fosse exibido tanto no WhatsApp Web quanto no celular e que a pessoa que postou também pudesse visualizá-lo.

### O que vc observou ao invés do que esperava?

Diferenças no comportamento entre o WhatsApp normal e o WhatsApp Business, com ambos apresentando alguns bugs. No entanto, parece que o WhatsApp normal está com mais problemas nessa funcionalidade de postar status/stories.

### Qual versão da API você está usando?

1.8.1

### Qual é o seu ambiente?

Linux

**Comment by dpaes** [comment]
@DAVIAMERICO242 não é porque é paga que funciona. Já vi várias pagas que dão mais problema que as open source. Mas respondendo a respeito de stories, creio que na v2 em diante a ideia é funcionar qualquer tipo de rede social incluindo whatsapp no evolution.

**Comment by dpaes** [comment]
Estarei fechando essa issue pelo fato da versão mencionada não estar mais recebendo correções. Estaremos focados em corrigir versões mais atuais a partir da v2 do evolution.
