### ISSUE TITLE
Bug Evolution Webhok

### ISSUE THREAD

**Issue by eliezerazevedo** [EvolutionAPI/evolution-api#726]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you observe instead of what you expected?

Pelo que percebi o usuário que esta constado no disparo da mensagem, é o usuário que eu usei a Key de autenticação do Chatwoot.
![image](https://github.com/user-attachments/assets/2c8823b1-beb8-4192-acda-e130f9dfa97e)

### Which version of the API are you using?

V1.8.2

### What is your environment?

Linux

### Other environment specifications

VPS Hetzner usando Cloudflare Zero Trust para fazer a publicação e acesso externo via domínio.

**Comment by dpaes** [comment]
isso é normal, vc so sabe que foi uma pessoa diferente pelo agente do chatwoot mesmo, como vc é o Admin no chatwoot e vc está usando sempre a sua key, é assim mesmo que vai se comportar, nada fora da normalidade.

**Comment by dpaes** [comment]
Estarei fechando esta issue pelo fato da versão mencionada não estar mais recebendo novas correções. Estaremos focados na v2, caso precise de alguma ajuda a respeito, nos comunique nos foruns conhecidos sobre evolution.
