### ISSUE TITLE
Instancias apagadas ao reiniciar a API por conta do Instance Logout que remove o registro da instância 

### ISSUE THREAD

**Issue by eduardochaves1** [EvolutionAPI/evolution-api#728]
### Bem-vido!

- [X] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

Instancias apagadas ao reiniciar a API por conta do Instance Logout que remove o registro da instância. Mesmo com a ENV `DEL_TEMP_INSTANCES=false`, algumas closed são perdidas.

### O que você esperava?

Que ao reiniciar a API todas as instâncias permanecessem.

### O que vc observou ao invés do que esperava?

Que as instâncias que passaram por um evento de logout acabavam sendo excluídas no mongodb, e que por isso, ao reiniciar acabava perdendo a instância por não estar mais registrada.

### Qual versão da API você está usando?

1.8.1

### Qual é o seu ambiente?

Docker

### Outras expecificações do ambiente

Linux Ubuntu 20.04 LTS com Docker, MongoDB. 16gb ram, 4 núcleos

### Notas Adicionais

Cheguei a comentar a função que realiza a remoção (cleanUp) ao ter um evento de logout, o que resolveu essa questão:

`monitor.service.ts` linha 483:
```ts
    this.eventEmitter.on('logout.instance', async (instanceName: string) => {
      this.logger.verbose('logout instance: ' + instanceName);
      try {
        this.waInstances[instanceName]?.clearCacheChatwoot();
        // this.logger.verbose('request cleaning up instance: ' + instanceName);
        // this.cleaningUp(instanceName);
      } finally {
        this.logger.warn(`Instance "${instanceName}" - LOGOUT`);
      }
    });
```

Mas isso acabou gerando um outro bug ao tentar usar o endpoint connect, onde gerava apenas um qrcode e logo depois um evento de logout aparecia.

**Comment by dpaes** [comment]
Estarei fechando esta issue pelo fato da versão mencionada não estar mais recebendo correções, estaremos nos concentrando na v2 do evolution em diante.
