### ISSUE TITLE
Typebot (Evolution v2.0.0) - Erro na primeira mensagem

### ISSUE THREAD

**Issue by edervalois** [EvolutionAPI/evolution-api#729]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Ao enviar a primeira mensagem o bot não responde. 

### What did you expect?

O bot responder normalmente

### What did you observe instead of what you expected?

O bot só responde a partir da segunda mensagem

### Which version of the API are you using?

v2.0.0

### What is your environment?

Linux

### If applicable, paste the log output

`[Evolution API]    v2.0.4-rc  573410   -  Thu Aug 01 2024 14:36:39     ERROR   [TypebotService]  [object]   
0|ApiEvolution  | TypeError: Cannot read properties of undefined (reading 'mediaUrl')
0|ApiEvolution  |     at TypebotService.getTypeMessage (/home/evolution/evolution-api/dist/src/api/integrations/typebot/services/typebot.service.js:848:35)
0|ApiEvolution  |     at TypebotService.getConversationMessage (/home/evolution/evolution-api/dist/src/api/integrations/typebot/services/typebot.service.js:878:28)
0|ApiEvolution  |     at TypebotService.<anonymous> (/home/evolution/evolution-api/dist/src/api/integrations/typebot/services/typebot.service.js:1400:46)
0|ApiEvolution  |     at Generator.next (<anonymous>)
0|ApiEvolution  |     at fulfilled (/home/evolution/evolution-api/dist/src/api/integrations/typebot/services/typebot.service.js:5:58) `

**Comment by adrielov** [comment]
Estou com o mesmo problema :(

**Comment by edervalois** [comment]
este erro parou ao desativar o minio, no entanto, surgiu um novo erro na primeira mensagem:

`[Evolution API]    v2.0.9-rc  120   -  Sun Aug 11 2024 11:15:26     ERROR   [TypebotService]  [object]   
TypeError: Cannot read properties of undefined (reading 'id')
    at TypebotService.getTypeMessage (/evolution/dist/src/api/integrations/typebot/services/typebot.service.js:860:31)
    at TypebotService.getConversationMessage (/evolution/dist/src/api/integrations/typebot/services/typebot.service.js:892:28)
    at TypebotService.<anonymous> (/evolution/dist/src/api/integrations/typebot/services/typebot.service.js:1412:46)
    at Generator.next (<anonymous>)
    at fulfilled (/evolution/dist/src/api/integrations/typebot/services/typebot.service.js:5:58) `

**Comment by dpaes** [comment]
Poderiam informar se persiste o erro? já tentaram usar uma versão mais atual do evolution, como a 2.1.2?
