### ISSUE TITLE
Bug: v1.5.0 - Typebot messages messages aren't displayed in chatwoot

### ISSUE THREAD

**Issue by franciscoeymardneto** [EvolutionAPI/evolution-api#73]
The visibility of Typebot messages within the Chatwoot platform. Currently, messages sent by the Typebot are not being displayed within Chatwoot, creating a disconnect in the conversation history.

![Captura de Tela 2023-08-23 às 10 03 26](https://github.com/EvolutionAPI/evolution-api/assets/78768690/82298218-4b60-4032-a0eb-398a9be9d3a7)

**Comment by DavidsonGomes** [comment]
corrigido na versao 1.5.1
