### ISSUE TITLE
Erro 403 ao receber stickerMessage ao tentar enviar para S3. Não gera mediaUrl

### ISSUE THREAD

**Issue by viniciusverasdossantos** [EvolutionAPI/evolution-api#731]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

nao ta gerando mediaUrl de stickerMessage.
no log da api esta dando 403 ao fazer download do servidor do whatsapp

### What did you expect?

Deveria Gerar mediaUrl. 

### What did you observe instead of what you expected?

 esta dando 403 ao fazer download do servidor do whatsapp

### Which version of the API are you using?

2.0.4

### What is your environment?

Windows

**Comment by dpaes** [comment]
Ainda persiste o problema @viniciusverasdossantos? poderia informar se chegou a testar alguma outra versão mais atual como a 2.1.2 do evolution?
