### ISSUE TITLE
Erro ao enviar \n do n8n para API EVO

### ISSUE THREAD

**Issue by tiagocaus** [EvolutionAPI/evolution-api#732]
### Bem-vido!

- [X] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

Passei uma mensagem definida pelo n8n para depois ser enviada a EVO.

### O que você esperava?

Quebra de linha usando \n

### O que vc observou ao invés do que esperava?

Erro no http request do n8n no momento do envio para api evo

### Capturas de Tela/Vídeos

![image](https://github.com/user-attachments/assets/56508832-851f-49db-8a01-6be2d9ee1466)

### Qual versão da API você está usando?

v2.0.6-rc

### Qual é o seu ambiente?

Docker

### Outras expecificações do ambiente

Servidor dedicado 2cpu/4gb

### Se aplicável, cole a saída do log

Output
JSON parameter need to be an valid JSON [item 0]
Error details

 Other info
Item Index

0

Node type

n8n-nodes-base.httpRequest

Node version

4.2 (Latest)

n8n version

1.53.0 (Self Hosted)

Time

03/08/2024, 13:38:12

Stack trace

NodeOperationError: JSON parameter need to be an valid JSON at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/HttpRequest/V3/HttpRequestV3.node.js:1353:35) at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:728:42) at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:673:66 at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1086:20

### Notas Adicionais

o n8n está enviado em algum formato que a EVO não entende. Pois sei que ela aceita \n

**Comment by ZapiBots** [comment]
Eu consegui resolver apenas adicionando mais uma contrabarra antes do contrabarra n.  Era assim \n, ficou assim \\n.

**Comment by marcelovjr** [comment]
Olá tudo bem?

Conseguiu resolver? estou com o mesmo problema.
![image](https://github.com/user-attachments/assets/757efc5c-531a-4fe8-adcc-2e2fbf88ef82)


> ### Bem-vido!
> * [x]  Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.
> 
> ### O que você fez?
> Passei uma mensagem definida pelo n8n para depois ser enviada a EVO.
> 
> ### O que você esperava?
> Quebra de linha usando \n
> 
> ### O que vc observou ao invés do que esperava?
> Erro no http request do n8n no momento do envio para api evo
> 
> ### Capturas de Tela/Vídeos
> ![image](https://private-user-images.githubusercontent.com/11445757/354817474-56508832-851f-49db-8a01-6be2d9ee1466.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4OTA2MDYsIm5iZiI6MTczMjg5MDMwNiwicGF0aCI6Ii8xMTQ0NTc1Ny8zNTQ4MTc0NzQtNTY1MDg4MzItODUxZi00OWRiLThhMDEtNmJlMmQ5ZWUxNDY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDE0MjUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNWMwODc1OTAzZmMxZjAyZDQ3YThiODFkM2RmMjk3Y2FiMDdlODZkYTM3MjEwOTYxOTUwYTFjNmIxYjg4MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.smOdAMbxWEtKAzisIq3m8O1J8hYX_y-nEE9fXUH6Xas)
> 
> ### Qual versão da API você está usando?
> v2.0.6-rc
> 
> ### Qual é o seu ambiente?
> Docker
> 
> ### Outras expecificações do ambiente
> Servidor dedicado 2cpu/4gb
> 
> ### Se aplicável, cole a saída do log
> Output JSON parameter need to be an valid JSON [item 0] Error details
> 
> Other info Item Index
> 
> 0
> 
> Node type
> 
> n8n-nodes-base.httpRequest
> 
> Node version
> 
> 4.2 (Latest)
> 
> n8n version
> 
> 1.53.0 (Self Hosted)
> 
> Time
> 
> 03/08/2024, 13:38:12
> 
> Stack trace
> 
> NodeOperationError: JSON parameter need to be an valid JSON at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/HttpRequest/V3/HttpRequestV3.node.js:1353:35) at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:728:42) at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:673:66 at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1086:20
> 
> ### Notas Adicionais
> o n8n está enviado em algum formato que a EVO não entende. Pois sei que ela aceita \n

**Comment by dpaes** [comment]
Esse problema não é na evo e sim algo relacionado ao n8n. Sugiro você ver uma forma dele passar o \n corretamente conforme foi passado a dica do @ZapiBots

**Comment by ThiagoEliSilva** [comment]
aqui a solução que funcionou foi essa output..replace(/\n/g, '\ ')
