### ISSUE TITLE
Envio de imagem falha usando S3 Bucket. 

### ISSUE THREAD

**Issue by GilmarBastos** [EvolutionAPI/evolution-api#738]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Envio de imagem falha usando S3 Bucket, realizei testes com  Cloudflare , Vultr
Estando o agente do chatwoot logado ele consegue receber as imagens, entretanto ao anexar uma imagem , dá erro 
![Screenshot_1](https://github.com/user-attachments/assets/c2968b1d-1849-4f70-af30-7a8b7ca128e8)
[log_evolution.txt](https://github.com/user-attachments/files/16500933/log_evolution.txt)

### What did you expect?

Enviar e  receber imagem e ou arquivos anexados.

### What did you observe instead of what you expected?

Api , só está recebendo imagens, mas não está enviando

### Screenshots/Videos

![Screenshot_1](https://github.com/user-attachments/assets/330870b4-0615-4d85-a44b-3a42299f2246)

### Which version of the API are you using?

image: atendai/evolution-api:v2.0.7-rc

### What is your environment?

Windows

### Additional Notes

Em testes realizados com a image: atendai/evolution-api:v2.0.6-rc

Tanto o envio como recebimento estavam funcionando !!

**Comment by GilmarBastos** [comment]
Observei que esse problema está acontecendo somente com o **Superadmin** do chatwoot , se você criar outra conta ( como se fosse cliente) e criar o administrador desta conta , o envio e recebimento de arquivos (imagens, documentos)  com a Evolution v2.0.7-rc e a anterior funcionaram para mim.
Tanto com S3 Bucket como com local storage...

**Comment by tiagocaus** [comment]
Se o problema é realmente com o Superadmin então deve ter alguma permissão a ser feita?...

**Comment by dpaes** [comment]
@GilmarBastos Já tentou testar usando uma versão mais atual do evolution e ver se persiste o erro?
