### ISSUE TITLE
Erro 400 ao tentar enviar mensagem via chatwoot

### ISSUE THREAD

**Issue by anderson-longara-souchat** [EvolutionAPI/evolution-api#742]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Esta gerando este erro no log ao tentar enviar mensagem com integração via chatwoot na api v2.0.7, abaixo logo de erro

[Evolution API]  [Souchat1]  v2.0.7-rc  124   -  Tue Aug 06 2024 14:40:42     ERROR   [ChannelStartupService]  [object]   
SessionError: No sessions
    at 5511983279714.31 [as awaitable] (/evolution/node_modules/libsignal/src/session_cipher.js:71:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _asyncQueueExecutor (/evolution/node_modules/libsignal/src/queue_job.js:20:29) 
[Evolution API]    v2.0.7-rc  124   -  Tue Aug 06 2024 14:40:42     ERROR   [ChatwootService]  [object]   
{
  status: 400,
  error: 'Bad Request',
  message: [ 'SessionError: No sessions' ]

### What did you expect?

Enviar mensagem sem dar erro

### What did you observe instead of what you expected?

Enviar mensagem sem erro

### Screenshots/Videos

![Screenshot 2024-08-06 144505](https://github.com/user-attachments/assets/22eb353d-a4d9-43bb-94f6-4b8ceb49c237)

### Which version of the API are you using?

V2.0.7

### What is your environment?

Linux

**Comment by GilmarBastos** [comment]
Eu comentei em : https://github.com/EvolutionAPI/evolution-api/issues/738
veja se lhe ajuda ...

**Comment by igr123c** [comment]
Olaa, tudo bem?
Instalei pelo setup Orion e esta na V2.0.5rc na minha nao esta funcionando Dify nem Credenciais openAi, a sua esta?

Como que atualizo a evo2.0?

**Comment by eduardochaves1** [comment]
![image](https://github.com/user-attachments/assets/842ef2fc-3d6a-4fbd-8ba7-e6727ef27bc8)

Eu percebi que quando dá o erro de No Sessions na instância, esses documentos aparecem no registro dessa instância do mongo

**Comment by eduardochaves1** [comment]
Uma dúvida, vocês estão com o redis ativado para salvar instâncias?

**Comment by dpaes** [comment]
@anderson-longara-souchat chegou a testar em uma versão do evolution mais recente? poderia informar se ainda está tendo o problema acima?
