### ISSUE TITLE
Texto plano para o grupo "Announcements" da comunidade do WhatsApp

### ISSUE THREAD

**Issue by Juanmi18** [EvolutionAPI/evolution-api#743]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Obrigado à comunidade por criar esta API, já a utilizo há muito tempo e funciona muito bem. Desculpe se escrevi errado o português, estou escrevendo para você da Espanha e não sei se o tradutor dirá algo errado

Estou tentando enviar uma mensagem da Evolution API con n8n para o **grupo "Announcements" da comunidade do WhatsApp** e eu não posso fazer isso, esses são os resultados:

**Grupo normal de uma comunidade:** 120363321189350974@g.us
**Grupo normal:** 34679352103-1411377110@g.us
**Grupo de avisos "announcements" de uma comunidade:** 120363297929284618@g.us

_Evapi (homolog, latest, 2.0.2-beta, 2.0.3-beta y 2.0.7-rc):_ 
**OK** Grupo normal comunidad de uma comunidade
**OK** Grupo normal
**KO** Grupo de avisos "announcements" de uma comunidade

### What did you expect?

Crie uma comunidade WhatsApp

Descubra o groupJid com o link de convite

Envie a mensagem de texto simples com o número de telefone do gerente da comunidade para o grupo

### What did you observe instead of what you expected?

n8n marca a mensagem como enviada e a mensagem não chega ao grupo de notificação da comunidade.

O número de telefone que envia a mensagem é o do criador da comunidade, ou seja, possui permissões.

Se eu enviar a mensagem do smartphone, funciona perfeitamente

### Which version of the API are you using?

ALL

I try with all of this: 

homolog
latest
2.0.2-beta
2.0.3-beta
2.0.7-rc

### What is your environment?

Docker

**Comment by dpaes** [comment]
@Juanmi18 poderia informar se ainda está com o erro acima em uma versão mais recente do evolution?

**Comment by Juanmi18** [comment]
Olá! Reabro o tópico, encontrei o problema e deixo aqui a solução:

**Problema:** Se você busca o ID do grupo de notificação de uma comunidade pelo Código Convite, o ID que ele retorna não permite o envio de mensagens, tudo parece correto mas não aparece no grupo.

**Solução:** Depois de configurarmos a API Evolution e criarmos a instância, abrimos o log da API Evolution, do nosso celular escrevemos uma mensagem no grupo de avisos da comunidade e copiamos o remoteJid. Se enviarmos para este grupo funciona corretamente

Continuei investigando, se você pesquisar os dados desse novo grupo encontrado no log, uma nova variável chamada _linkedParent_ mostra uma informação interessante, que curiosamente é o mesmo ID que é retornado se você pesquisar o grupo por convite link.

Não encontrei uma maneira de descobrir essa boa identificação.
