### ISSUE TITLE
bug de modulo faltante.

### ISSUE THREAD

**Issue by mateheww** [EvolutionAPI/evolution-api#745]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Realizei o passo a passo da documentação e recebi esse erro ao iniciar usando o comando "npm run start:prod"

### What did you expect?

Funcionar

### What did you observe instead of what you expected?

Error: Cannot find module '/www/wwwroot/node/evolution-api/dist/src/main'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.10.0

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/e2d5aa78-121b-403f-9445-8c46eca885a5)

### Which version of the API are you using?

a mais recente v2

### What is your environment?

Linux

### Other environment specifications

versão mais recente do ubuntu

**Comment by juniormelo26** [comment]
@mateheww conseguiu resolver seu problema? vi que ninguem te deu atenção/orientação.

**Comment by RuanAyram** [comment]
Execute o comando npm run build em seguida já pode rodar o ➜ npm run start:prod

**Comment by juniormelo26** [comment]
@RuanAyram agora esta funcionando e ja foi ate atualizado na doc. conforme vc falou aqui. Obrigado!

**Comment by RuanAyram** [comment]
> @RuanAyram agora esta funcionando e ja foi ate atualizado na doc. conforme vc falou aqui. Obrigado!

De nada!!

**Comment by dpaes** [comment]
Fechando a issue pelo fato de ter sido corrigido o bug após a criação da mesma, caso esteja tendo o problema ainda @mateheww, informe aqui para podermos auxilia-lo

**Comment by johnnybs2** [comment]
Estou com esse problema e não sei o que fazer.

**Comment by marcelomontoni** [comment]
mesmo problema aqui

**Comment by dpaes** [comment]
confiram a versão do evolution que estão usando, esse bug tinha sido corrigido em versões posteriores a essa data da issue
