### ISSUE TITLE
versão v2.0.9-rc não envia nem recebe mensagem de grupo

### ISSUE THREAD

**Issue by kabaweb** [EvolutionAPI/evolution-api#748]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

ao tenta enviar mensagem de texto para grupo da erro e não envia mensagem nem recebe

### What did you expect?

que fosse enviado a mensagem

### What did you observe instead of what you expected?

.

### Which version of the API are you using?

v2.0.9-rc

### What is your environment?

Windows

### Other environment specifications

docker swarm

**Comment by kabaweb** [comment]
não

**Comment by dpaes** [comment]
@kabaweb poderia informar se já tentou usar uma versão mais recente da v2 e observar se persiste o erro mencionado?
