### ISSUE TITLE
Mensagens enviadas duplicadas pela integração Evolution + Chatwoot

### ISSUE THREAD

**Issue by matheusfterra** [EvolutionAPI/evolution-api#75]
Olá pessoal, minha instância do Evolution 1.5.0 está conectado ao Chatwoot 3 (acontecia o mesmo cenario com o 2.18).

Quando envio mensagem, eventualmente ela é enviada em duplicidade.

Toda vez que envio mídia ou áudio é enviado em duplicidade também.

Creio que seja por conta da integraçao com o chatwoot, porque o aúdio duplicado é enviado sem o desenho de onda (semelhante ao player de quando o audio é enviado pelo chatwoot).

Alguém também passando por isso?

**Comment by Suporte4Mrk** [comment]
Mesmo Coisa Aqui , mas testando na API  1.4.8 parace que vai normal , Recomendo voltar para 1.48  e testar

**Comment by deivisonrpg** [comment]
Sim exatamente a mesma situação aqui.

**Comment by fabiohenriquen** [comment]
Mesma coisa por aqui. Rodando via docker no modo swarm.

**Comment by DavidsonGomes** [comment]
resolvido na versao 1.5.1
