### ISSUE TITLE
Evolution v2.0.9rc - Conversa reaberta no Chatwoot mesmo com a opção desabilitada nas configurações da API

### ISSUE THREAD

**Issue by httpmerak** [EvolutionAPI/evolution-api#751]
### Bem-vido!

- [x] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

Ao utilizar a versão Evolution v2.0.9rc com integração ao Chatwoot, observei que as conversas estão sendo reabertas automaticamente, mesmo quando a opção para reabertura de conversas está desabilitada nas configurações da API. Isso está causando problemas no fluxo de trabalho da equipe de atendimento ao cliente, já que conversas que deveriam permanecer encerradas são reabertas sem necessidade.

---

### **Passo a passo para repetir o problema?**
1. **Acesso às Configurações:** Navegue até as configurações da API no Evolution v2.0.9rc.
2. **Desabilitação de Opção:** Desative a opção "**Reabrir Conversa**" nas configurações.
3. **Encerramento de Conversa:** No Chatwoot, encerrei manualmente uma conversa ativa, seguindo o fluxo padrão de encerramento, marquei ela como resolvida.
4. **Envio de Nova Mensagem:** Para testar o comportamento, enviei uma nova mensagem para a conversa que havia sido encerrada.
5. **Observação do Comportamento:** Mesmo com a opção de reabertura desativada, a conversa foi reaberta automaticamente, o que não estava de acordo com o esperado.
6. **Repetição dos passos:** Repeti os passos 3 e 4 com intervalos diferentes e obtive o mesmo problema.

### O que você esperava?

Eu esperava que, ao desabilitar a opção "Reabrir Conversas" nas configurações da API, as conversas encerradas no Chatwoot permanecessem encerradas, mesmo que uma nova mensagem fosse recebida.

### O que vc observou ao invés do que esperava?

Mesmo após desabilitar a opção "**Reabrir Conversas**" nas configurações, as conversas ainda estão sendo reabertas automaticamente no Chatwoot sempre que uma nova mensagem é recebida, o que vai contra a configuração feita.

No entanto, se eu ativar a opção "**Reabrir Conversa**", salvar a configuração e, em seguida, desativá-la novamente, o comportamento esperado (de não reabrir conversas automaticamente) é atingido.

### Capturas de Tela/Vídeos

![image](https://github.com/user-attachments/assets/cf117fe6-861c-4536-8e54-16a19ef8c3b0)
![image](https://github.com/user-attachments/assets/911be09b-e5ce-4720-8696-1366cb3e02b3)

### Qual versão da API você está usando?

v2.0.9-rc

### Qual é o seu ambiente?

Linux

**Comment by dpaes** [comment]
Poderia informar se persiste o problema? Caso esteja persistindo, chegou a tentar uma versão mais atual do evolution, por exemplo a 2.1.2?

**Comment by gilsonwindsoft** [comment]
> Poderia informar se persiste o problema? Caso esteja persistindo, chegou a tentar uma versão mais atual do evolution, por exemplo a 2.1.2?

No meu ambiente o problema persiste

**Comment by markinhok2** [comment]
No meu ambiente isso ocorre para algumas conversas apenas, estou utilizando a versão 2.2.3.
Não consegui identificar um padrão, porém em algumas conversas isso ocorre e outras não.

**Comment by israelvcb** [comment]
+1 ainda continua assim
