### ISSUE TITLE
Dify is disabled

### ISSUE THREAD

**Issue by tiagocaus** [EvolutionAPI/evolution-api#752]
### Bem-vido!

- [X] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

Tentei adicionar o dify via api e manager.

### O que você esperava?

Conexão do dify.

### O que vc observou ao invés do que esperava?

```
{
    "status": 400,
    "error": "Bad Request",
    "response": {
        "message": [
            "Dify is disabled"
        ]
    }
}
```

### Qual versão da API você está usando?

2.0.9-rc

### Qual é o seu ambiente?

Windows

**Comment by judsonjuniorr** [comment]
@tiagocaus habilitou no .env?

![CleanShot 2024-08-12 at 09 40 45](https://github.com/user-attachments/assets/797700bc-5c73-4b28-9676-baec273128a9)

**Comment by tiagocaus** [comment]
Depois descobrir que tinha que adicionar isso. Obrigado @judsonjuniorr

**Comment by edubezerra123** [comment]
estou com esse mesmo problema, porém tem pouca experiência. Poderia me ajudar como acesso o arquivo .env para modificar esse parametro?

**Comment by xumal** [comment]
Habilitei no .env e to com o mesmo problema ainda.
