### ISSUE TITLE
Erro de Mensagens não lidas enviadas por mim. 

### ISSUE THREAD

**Issue by HermesMacedo** [EvolutionAPI/evolution-api#754]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Quando envio uma mensagem pelo Chatwoot a mensagem chega como não lido no App e WhatsWeb.

### What did you expect?

O Correto é se envio pelo chatwoot a mensagem, ela não tem que entrar como não lida, pois eu que enviei.

### What did you observe instead of what you expected?

ao enviar a mensagem pelo chatwoot tem que ficar sem ser como não lida.

### Which version of the API are you using?

Evolution v2.0.9rc   

### What is your environment?

Windows

### Other environment specifications

windows 11

### If applicable, paste the log output

servidor debian 12

### Additional Notes

heztner

**Comment by dpaes** [comment]
Poderia informar se ainda persiste o problema? Se sim, chegou a testar com outra versão do evolution, como a 2.1.2 para ver se persiste este erro?
