### ISSUE TITLE
Always stays in "Connecting" to WhatsApp: version 2.0.9-rc

### ISSUE THREAD

**Issue by gustotc** [EvolutionAPI/evolution-api#756]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

After updating to version 2.0.9-rc, when trying to add a new connection number to WhatsApp, the message "Connecting" appears, but the integration works.

### What did you expect?

Change Status to "Connected".

### What did you observe instead of what you expected?

After upgrading from version 2.0.5 to 2.0.9

### Screenshots/Videos

![2024-08-12_16-44-15](https://github.com/user-attachments/assets/2011b31f-3e1a-44d8-8e4b-41c69369a61a)

### Which version of the API are you using?

2.0.9-rc

### What is your environment?

Linux

### Other environment specifications

Hetzner Dedicated Server 4VCPU 16GB RAM
Ubuntu 20.04
Evolution 2.0.9 rc Image of Docker Hub, Docker Swarm Installation with Portainer 2.20.1

### If applicable, paste the log output

no log

### Additional Notes

After upgrading from version 2.0.5 to 2.0.9

**Comment by willph** [comment]
Como é sua instalação?

Docker + Nginx?
Docker + Traefik?

**Comment by juliancesar** [comment]
@gustotc , como vc resolveu?

**Comment by 1kpas** [comment]
Aqui ficava conectando pq o whatsapp estava sem foto depois que coloquei foto funcionou perfeitamente
