### ISSUE TITLE
Não consigo enviar mensagens usando o n8n

### ISSUE THREAD

**Issue by Leandro-Dalla-Nora** [EvolutionAPI/evolution-api#757]
### Bem-vido!

- [X] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

Eu fiz um http request para enviar uma mensagem do n8n, usando a Evolution API, em que ambos estão rodando em um docker container, usando o seguinte curl:

`curl --request POST \\n  --url http://localhost:8080/message/sendText/MVP_chatbot \\n  --header 'Content-Type: application/json' \\n  --header 'apikey: xxxxxxxxxxxx' \\n  --data '{\n  "number": "xxxxxxxxxxxx",\n  "textMessage": {\n    "text": "teste"\n  }\n}'`

### O que você esperava?

Buenas! 

Eu esperava que a mensagem fosse enviada

### O que vc observou ao invés do que esperava?

Eu obtive o seguinte erro: "The service refused the connection - perhaps it is offline", porém a Evolution API está rodando corretamente. 

### Capturas de Tela/Vídeos

![image](https://github.com/user-attachments/assets/e4b2b99e-8375-43a3-ac88-85ab9a4c8c74)
![image](https://github.com/user-attachments/assets/1b3b2c62-4293-47f5-9bd7-2b0bcc7ce55c)
![image](https://github.com/user-attachments/assets/1fb4dcd2-8522-44a1-aa47-ecd14b5a5bfa)

### Qual versão da API você está usando?

v2.0.9-rc

### Qual é o seu ambiente?

Docker

### Se aplicável, cole a saída do log

`{
  "errorMessage": "The service refused the connection - perhaps it is offline",
  "errorDetails": {
    "rawErrorMessage": [
      "connect ECONNREFUSED 127.0.0.1:8080",
      "connect ECONNREFUSED 127.0.0.1:8080"
    ],
    "httpCode": "ECONNREFUSED"
  },
  "n8nDetails": {
    "nodeName": "HTTP Request - send message",
    "nodeType": "n8n-nodes-base.httpRequest",
    "nodeVersion": 4.2,
    "itemIndex": 0,
    "time": "12/08/2024, 22:50:14",
    "n8nVersion": "1.53.2 (Self Hosted)",
    "binaryDataMode": "default",
    "stackTrace": [
      "NodeApiError: The service refused the connection - perhaps it is offline",
      "    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/HttpRequest/V3/HttpRequestV3.node.js:1650:33)",
      "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
      "    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:728:19)",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:673:51",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1086:20"
    ]
  }
}`

`Item Index 0
Node type n8n-nodes-base.httpRequest
Node version 4.2 (Latest)
n8n version 1.53.2 (Self Hosted)
Time 12/08/2024, 22:50:14
Stack trace
NodeApiError: The service refused the connection - perhaps it is offline at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/HttpRequest/V3/HttpRequestV3.node.js:1650:33) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:728:19) at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:673:51 at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1086:20`

### Notas Adicionais

- Quando o container da Evoluiton API estava de pé, eu consegui enviar mensagens do meu terminal, o que indica que a API está funcionando corretamente, mas não consegui enviar com o n8n. Eu testei o n8n tanto em um container, quanto no servidor do n8n e não consegui enviar nenhuma mensagem
- Eu estou usando o compose fornecido na documentação tanto da Evolution, quando do n8n. A única alteração que fiz foi criar uma rede interna entre os dois containers
- Não tenho firewall na minha rede, nem em minha máquina
- Ao realizar esse http request, não aparece nenhum log de erro de que o n8n não consiga acessar o container da Evo
- Não há conflitos na porta 8080

Dese já, quero agradecer pela ajuda, por todo o desenvolvimento deste trabalho, pela dedicação de cada um dos membros :smile:

**Comment by imarkes** [comment]
Eu tambem estou com o mesmo problema. Alguem poderia ajudar por favor?

**Comment by georgeallan** [comment]
Mesmo problema

**Comment by sy-carolinne** [comment]
Mais uma para a lista, porém o meu está aparecendo esse erro aqui.
![image](https://github.com/user-attachments/assets/939c3581-58a9-4ca5-87a6-51fbe6a50cde)

**Comment by dpaes** [comment]
Certo, pelo que percebi nos prints do autor @Leandro-Dalla-Nora ele está tentando em localhost, no qual se o seu evolution ou o n8n está em localhost, não tem como um conhecer o outro pelo fato de não estarem expostos na rede, a não ser que vc tenha feito um tunnel com ngrok ou algo do genero pra expor seu localhost na web com um dominio, porém segundo seu print ou você não expos ou não configurou no n8n corretamente para funcionar. Então recomendo que veja a config do seu n8n que deve ser aonde está o problema

**Comment by dpaes** [comment]
@sy-carolinne bad request é corpo da requisição ou metodo sendo usado errado

**Comment by sy-carolinne** [comment]
Consegui solucionar colocando o Body Content Type para Json . 

Estava utilizando os campos e nesse formata estava dando o erro acima. Depois de trocar para Json, deu certo e está indo do jeito que queria com as formatações de negrito, emotion... 
![image](https://github.com/user-attachments/assets/16322abd-28f4-48a7-b229-13bf17109f7b)

**Comment by sy-carolinne** [comment]
@dpaes o erro estava dando pelo formatado que estava colocando na parte do texto, e estava usando o método de campo e ele não reconhecia a formatação. 

Depois que troquei para Json, rodou bonito.

![Screenshot_8](https://github.com/user-attachments/assets/c4881da4-863a-42ab-a029-4c0a94fdc38a)

**Comment by dpaes** [comment]
Ainda está com o problema @Leandro-Dalla-Nora?

**Comment by Mesheo** [comment]
to com o mesmo problema descrito pelo autor do post

**Comment by allexerckmann** [comment]
to com o mesmo problema descrito pelo autor do post

**Comment by satellasoft** [comment]
Verifique se o serviço que está tentando acessar está fora do container, em caso positivo, ou invés de usar localhost, utilize o IP do seu PC com a porta, exemplo: http://192.168.3.50:1111.

Você também pode testar com o http://host.docker.internal:1111.

Alguns serviços requer o header de agente, max-age, crossorigin...verifique o servidor de destino.

**Comment by elioenaiancelmo** [comment]
Pessoal eu estou com o mesmo problema. Estou tentando fazer uma requisição da evolution api no n8n e estou com esse erro. ![FB_IMG_1743854888522.jpg](https://github.com/user-attachments/assets/ce850f23-06ad-4c36-9b61-6feab5c4105a)

![FB_IMG_1743854899066.jpg](https://github.com/user-attachments/assets/2ddf31e0-5a6f-497f-b215-f7c8633ba82c)

![FB_IMG_1743854904285.jpg](https://github.com/user-attachments/assets/f3270c02-00ed-4309-ac46-a6566b76dc34)

![FB_IMG_1743854910424.jpg](https://github.com/user-attachments/assets/3464afcc-fa1d-406a-9f0c-42096ba13560)

Será se alguém conseguiu resolver ? Ou sabe como resolver ?

**Comment by JOESTAR117** [comment]
![Image](https://github.com/user-attachments/assets/c328d3f9-ef62-4f31-bed4-4c123553795b) , alguem sabe como resolver e sempre esse erro

**Comment by henriquemanduca** [comment]
Também estou com esse problema. Mesmo a conexão ter dado certo, os componentes do pacote Evolution não parecem montar as urls de destino corretamente.
![Image](https://github.com/user-attachments/assets/4ca042cf-6fbc-49bb-a98b-938890b242ad)

**Comment by henriquemanduca** [comment]
@JOESTAR117 , verifica nas sua configuração de credencial do Evolution, e remove da url a parte "/manager". Vc tem que conseguir cadastrar apenas com a url base.

**Comment by KelvesPires** [comment]
estou com o mesmo problema, e ja tente de todas as sugestoes aqui

**Comment by algsavi** [comment]
alguem saberia informar sobre esse erro? 

![Image](https://github.com/user-attachments/assets/5987e837-d4ad-4a10-8ce3-1ff415e6cdbc)

![Image](https://github.com/user-attachments/assets/40939faf-388c-4403-829a-5c1c5eeef791)

Consigo integrar com a API, ela valida o TOKEN, consegue obter as instâncias, mas não consigo enviar mensagem de jeito nenhum!

![Image](https://github.com/user-attachments/assets/b5d16cb7-1f06-4832-a485-ec40cda328b4)

**Comment by frcdouglas** [comment]
É preciso expor a url local do n8n a rede utilizando o ngrok. Caso contrário, a url local não será valida

**Comment by frcdouglas** [comment]
podem ver o passo a passo aqui: https://github.com/zaniniii/n8n-evoapi-ngrok

**Comment by JhonesSena** [comment]
Uma outra sugestão para  causa do erro 500 Internal Server Error: Connection Closed (e o contêiner estar com exited - code 1) é que o servidor da Evolution API está ficando sem memória RAM (JavaScript heap out of memory).

Como a Evolution API roda em Node.js, precisamos aumentar o limite de memória alocado para esse processo.

🛠️ A Solução é no docker-compose.yml
A maneira correta de corrigir isso é editando o arquivo de configuração do Docker (docker-compose.yml ou o arquivo de stack que você usa no Portainer).

Você precisa adicionar o parâmetro NODE_OPTIONS na seção de variáveis de ambiente (environment) do serviço da Evolution API.

Passo 1: Localizar e Editar o Arquivo
Acesse o Portainer.

Vá para Stacks (Pilha) ou Containers (Contêineres) e encontre o serviço da Evolution API.

Edite o arquivo docker-compose.yml (se estiver no Portainer, geralmente clicando em "Editor" ou "Editar").

Passo 2: Inserir a Configuração de Memória
Procure a seção do serviço Evolution API (pode estar como evolution_api, api, ou o nome que você deu) e adicione (ou edite) a seção environment com o parâmetro --max-old-space-size.

Exemplo de Como Deve Ficar:

YAML

services:
  # Nome do seu serviço principal da Evolution API
  evolution_api: 
    image: evoapicloud/evolution-api:latest
    # ... outras configurações
    environment:
      # Aumenta o limite de memória HEAP para 4096 MB (4 GB).
      # Ajuste este valor se o servidor tiver menos RAM.
      - NODE_OPTIONS=--max-old-space-size=4096 
    # ... outras configurações
Passo 3: Aplicar e Reiniciar
Salve as alterações no docker-compose.yml.

Redeploy: Faça o Redeploy (ou recriação forçada) da sua Stack/Pilha no Portainer. Isso forçará o Docker a recriar o contêiner, mas desta vez, com o novo limite de memória.

⚠️ Atenção
O valor 4096 (4GB) deve ser menor que a RAM total do seu servidor. Se o servidor só tem 2GB de RAM, use um valor como 1536 ou 2048.

Após o redeploy, verifique se os contêineres da Evolution API voltaram a ficar no estado running.

Se isso não funcionar, o servidor realmente não tem RAM suficiente, e o único jeito é fazer um upgrade no VPS!

**Comment by AleDias** [comment]
@satellasoft deu certo, brigado!!
