### ISSUE TITLE
Bug em sincronizar mensagens na 2.0.9 rc (chatwoot e evo)

### ISSUE THREAD

**Issue by dpaes** [EvolutionAPI/evolution-api#763]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Se é utilizado a feature de mudar o nome da caixa de entrada, o nome da organização e a logo, ele não sincroniza por algum motivo. Dai testei sem mudar o nome da caixa de entrada, nome da organização e logo, dai ele sincroniza ao passar o QR Code dentro do chatwoot após integrar com evolution api. Porém achei outro bug, depois que ele sincroniza, ele fica apresentando o CacheService sem parar toda vez que tento excluir a caixa de entrada via chatwoot, ou até clicar para desativar a integração com chatwoot via evolution manager. E outra coisa, mesmo excluindo a instancia para ele parar de sincronizar, ele continua criando a caixa de entrada do lado do chatwoot e usa o init na conversa com a EvolutionAPI e continua sincronizando. Tentei excluir a caixa de entrada diversas vezes, mas ele recriava sozinho e no evolution api manager já nem existia mais aquela instancia.

### What did you expect?

Esperava a sincronização do meu numero de whatsapp que estou usando para testes que segundo o painel possui muitas mensagens e chats.

### What did you observe instead of what you expected?

conforme a imagem abaixo, é o que retorna, no print do meu teste na 2.0.9 rc com postgres (banco de dados) e redis (cache somente), porém tenho o mesmo resultado na 1.8.1 com mongodb (banco de dados) e redis (cache apenas).
Também tenho experienciado conforme outra issue que abri, a duplicação de conversas, porém essa issue que abri é dedicada a mostrar que nao consigo sincronizar as mensagens de uma instancia que estou usando para teste.

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/43619a50-3b24-4696-8027-e824aedfb2d5)
esse é os logs bizarros que não param de vir, vou até derrubar o container pra ver se para de usar esse Cache Service e Redis

### Which version of the API are you using?

2.0.9 rc

### What is your environment?

Linux

### Other environment specifications

VPS com evolution 2.0.9 rc em uma VM da hetzner de 4vCPU 16GB com ubuntu 20.04
ambas uso docker swarm com portainer para subir a stack do evolution, com postgres, redis, traefik 2.11 para proxy reverso. Se precisar de mais informações posso passar

**Comment by dpaes** [comment]
Só pra atualizar o feedback, ele sincronizou, porém não está excluindo a caixa de entrada no chatwoot seja manualmente (ele recria pelo redis), e quando deleta a instancia, ele mesmo sem achar a instancia, ele recria a caixa de entrada no chatwoot e no log aparece o Cache Service e o Redis trazendo a caixa de volta com todas as mensagens (então oq antes era o problema de sincronizar, agora ta sincronizando direto pelo cache, até quando não quero)

**Comment by dpaes** [comment]
fiz um teste com o chatwoot do nestor e com o chatwoot oficial, ele repete o comportamento nos 2. (estou usando o mesmo database para os 2 pra ver o comportamento)

**Comment by dpaes** [comment]
então @JuanxCursed, compartilhe seu .env (sem mostrar os dados sensiveis), so pra ver como vc deixou a parte do redis e postgres, outra coisa pra sincronizar as mensagens vc tem que seguir certos passos (se estiver usando chatwoot).ter selecionado o comportamento como sincronização completa

**Comment by JuanxCursed** [comment]
Fala grande mestre @dpaes , obrigado pela resposta.
As envs e conexões estão ok, mas desisti de usar o chatwoot.
Vi diversos reports sobre problemas relacionados a sincronização por conta do Chatwoot (inclusives iguais ao meu), principalmente de mensagens se perdendo.
Estou usando uma abordagem mais custom construindo algo mais manual usando a API da Meta para o insta/face e a Evo para o Whatsapp.
A fila do Rabbit e o webhook já foi o bastante para eu conseguir fazer o que precisava aqui

**Comment by lucaspfigueira** [comment]
Boa noite @dpaes , estou com um problema parecido, utilizo Evo 2.3.0 e ChatWoot 4.2.0, a integração feita no Evolution, as mensagens criadas pelo ChatWoot, são enviadas normalmente pelo Evo, porém quando o cliente lê a mensagem ela altera a data de criação da mensagem enviada no chatwoot e bagunça toda a ordem cronológica da conversa, no WhatsApp Web, tudo normal, mas no chat do ChetWoot, não tem como se entender, já aconteceu algo parecido? Alguma luz?

![Image](https://github.com/user-attachments/assets/c381a75c-9b09-4ea6-a8fe-d9e4153c3f05)

**Comment by lucaspfigueira** [comment]
Ele altera sempre 3 horas para menos após a leitura do cliente:

![Image](https://github.com/user-attachments/assets/51bbdfe0-33f1-4b29-810e-35420a24af6d)

**Comment by rjsandim** [comment]
> Ele altera sempre 3 horas para menos após a leitura do cliente:
> 
> ![Image](https://github.com/user-attachments/assets/51bbdfe0-33f1-4b29-810e-35420a24af6d)

Isso é servidor ou aplicação configurado no fusohorário  UTC.
