### ISSUE TITLE
Mensagens enviadas pelo Atendente ficam como Não Lidas

### ISSUE THREAD

**Issue by HermesMacedo** [EvolutionAPI/evolution-api#77]
Cenário: API 1.5 CW 2.18

Quando o atendente envia mensagem pelo Celular ou WhatsWeb a conversa no ChatWoot fica como uma mensagem não lida (bolinha verde) e vice versa, quando envia pelo chatwoot no celular fica como uma mensagem não lida (bolinha verde).

Como resolver isso?

**Comment by DavidsonGomes** [comment]
A unica forma de nao aparece como lida é chamar o endpoint read_messages ou deixando ativo o read_messages em settings
