### ISSUE TITLE
[BUG] v2.0.9 rc - Não recebe mensagem devido foto do perfil

### ISSUE THREAD

**Issue by dnl4** [EvolutionAPI/evolution-api#771]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Conectei o evolution api ao chatwoot, mas eu não conseguia receber mensagem de um contato em específico, no chatwoot. Apesar de conseguir enviar mensagem para ele. 
Constatei que o bug aconteceu pois o contato usa a opção de só exibir a foto do perfil para contatos que estejam salvos na agenda dele. Após salvar o número que estava na evolution na lista de contatos, a foto do perfil apareceu e foi possível receber mensagens desse contato.

### What did you expect?

Receber mensagem no chatwoot

### What did you observe instead of what you expected?

O evolution apresentou um erro de not-authorized, pelo que entendi, isso ocorre pois o número que está no evolution não está salvo na agenda do contato que está enviando mensagem, que tem essa opção de privacidade ativa.

```
[Evolution API]  [66bcdb994d33c]  v2.0.9-rc  134   -  Wed Aug 14 2024 14:05:51     ERROR   [ChannelStartupService]  [object]   
Error: not-authorized
    at assertNodeErrorFree (/evolution/node_modules/baileys/lib/WABinary/generic-utils.js:56:15)
    at query (/evolution/node_modules/baileys/lib/Socket/socket.js:145:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.profilePictureUrl (/evolution/node_modules/baileys/lib/Socket/chats.js:445:24) {
  data: 401,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
} 
```

### Which version of the API are you using?

 v2.0.9 rc 

### What is your environment?

Docker

**Comment by sosnoski** [comment]
same here

**Comment by NexteraAnalytica** [comment]
Estou com o mesmo problema aqui e parece que o padrão se repete para grupos que não tem foto.

**Comment by ElterAguiari** [comment]
Mesma coisa aqui.

**Comment by ElterAguiari** [comment]
@dnl4 Ola, teve algum avanço em descobrir a solução?
Aqui o problema identificado:
Não recebe mensagens de perfis sem foto, perfis que estão com privações como não exibir informações para quem não faz parte dos seus contatos.

**Comment by laianeramos** [comment]
alguma solução?

**Comment by ElterAguiari** [comment]
[Evolution API]  [Pani_Whats]  v2.0.9  162   -  Fri Aug 16 2024 11:34:47     ERROR   [ChannelStartupService]  [object]   
Error: item-not-found
    at assertNodeErrorFree (/evolution/node_modules/baileys/lib/WABinary/generic-utils.js:56:15)
    at query (/evolution/node_modules/baileys/lib/Socket/socket.js:145:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.profilePictureUrl (/evolution/node_modules/baileys/lib/Socket/chats.js:453:24)
    at async it.profilePicture (/evolution/dist/main.js:180:4975)
    at async messages.upsert (/evolution/dist/main.js:171:14035) {

  data: 404,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}

**Comment by TheEmanuelSampaio** [comment]
Up!
Mesmo coisa aqui...

**Comment by TheEmanuelSampaio** [comment]
Corrigido na 2.0.10!!!! :D

**Comment by dpaes** [comment]
Sugiro usarem uma versão mais recente da evolution, conforme o amigo acima, foi corrigido em uma versão posterior.
