### ISSUE TITLE
Só trás array vazio no endpoint fetchContacts no chatController

### ISSUE THREAD

**Issue by pedrofarbo** [EvolutionAPI/evolution-api#772]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Não ta trazendo nenhum resultado quando faço a busca de contacts através do endpoint fetchContacts no chatController e já fazem algumas semanas. 

### What did you expect?

Deveria trazer os contatos do whatsapp que está integrado na instância. 

### What did you observe instead of what you expected?

O resultado está vindo um array vazio.

### Screenshots/Videos

![nextrack-print-fetchcontacts](https://github.com/user-attachments/assets/5f79c3ea-c245-45a9-aea8-7c6233de6cc5)

### Which version of the API are you using?

1.8.2

### What is your environment?

Linux

**Comment by dpaes** [comment]
Estarei fechando esta issue pelo fato da versão mencionada não estar mais recebendo novas correções. Estamos focando apenas na versão 2 do evolution em diante, caso este erro persista em alguma versão mais atual da v2, nos informe que logo iremos ajustar.
