### ISSUE TITLE
Excluindo mensagens indevidamente - chatwoot

### ISSUE THREAD

**Issue by sosnoski** [EvolutionAPI/evolution-api#775]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Conectei a evolution api ao chatwoot, conforme instruções da documentação. Em uma conversa qualquer criada na caixa de entrada correspondente à evolution, ao excluir alguma mensagem enviada pelo agente, ele exclui também outras mensagens da conversa. ver imagem abaixo

### What did you expect?

ao solicitar exclusão de mensagens, somente aquelas solcitadas devem ser excluídas.

### What did you observe instead of what you expected?

a operação de excluir mensagens está executando outras vezes de forma não intencional, inviabilizando seu uso no chatwoot

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/3b1d8b14-ff37-4a62-acfa-731c152c89d7)

![image](https://github.com/user-attachments/assets/eaaa4594-0388-432d-b833-d09d73fed90b)

![image](https://github.com/user-attachments/assets/4ba0a048-cd6a-4c31-871f-9fac5b654a53)

### Which version of the API are you using?

v2.0.9 rc

### What is your environment?

Docker

**Comment by sosnoski** [comment]
Descobrimos que é um problema de configuração no chatwoot.

Não é um bug na evolution-api

**Comment by dpaes** [comment]
Sugiro que teste em uma versão mais recente do evolution para atestar se ainda persiste o problema, por enquanto fecharei a issue
