### ISSUE TITLE
Dify não está entendendo áudio

### ISSUE THREAD

**Issue by adelimateus** [EvolutionAPI/evolution-api#776]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Ao usar a integração do Dify e receber um áudio pelo WhatsApp, não está entendendo/transcrevendo o áudio.

### What did you expect?

A API deve usar o endpoint /audio-to-text para enviar para a LLM interpretar

### What did you observe instead of what you expected?

Ao perguntar a LLM o que eu falei ela não soubre responder.

### Which version of the API are you using?

v2.0.9-rc

### What is your environment?

Linux

**Comment by adelimateus** [comment]
Acredito que o problema está no formato de arquivo que o whatsapp envia (acc?) pois o dify só aceita os seguintes:
['mp3', 'mp4', 'mpeg', 'mpga', 'm4a', 'wav', 'webm']

A meu ver teria que converter o áudio antes de enviar para o dify poder interpretar.

**Comment by carloshaugusto** [comment]
Conseguiu resolver? Estou tentando aqui também.

**Comment by IADOZERO** [comment]
Olá pessoal, alguém conseguiu?

**Comment by dpaes** [comment]
Acredito que em versões mais recentes esse problema foi solucionado, se conseguir testar seja na 2.1.2 ou 2.2.0 e responder aqui. Por enquanto estarei fechando a issue até segunda ordem.

**Comment by edersonselvati** [comment]
Estou com a 2.2.0 e ao enviar um audio para o dify, este nao é interpretado

**Comment by gabrielbuarque** [comment]
> Acredito que em versões mais recentes esse problema foi solucionado, se conseguir testar seja na 2.1.2 ou 2.2.0 e responder aqui. Por enquanto estarei fechando a issue até segunda ordem.


Ainda não foi solucionado nas versões mais recentes.
o audio é enviado pro dify como: audioMessage|0A0019B09E0A6A494CF66AE5B91B463

**Comment by edneymatias** [comment]
Eu resolvi ativando o MinIO na Evolution. Assim, ele envia um link para o Dify no formato audioMessage|https://...
Com o link, eu baixo o áudio num fluxo de trabalho e chamo um LLM para transcrever.

**Comment by acauaferreira** [comment]
EU RESOLVI do meu bot dify entender audios   adicionando uma apikey da openAI e ativando o speech to text la nas configs da openai dentro dessa instacia da EVO
E tbm tenho o s3 minio ativado e configurado.

Tbm ativei o speech to text dentro do meu agente do dify, mas nao sei o qto influenciou essa ultima config, o vital foi a apikey da openai + ativar speechto text nas configs da mesma

**Comment by Clebio2030** [comment]
Ainda não consegui @edneymatias e @acauaferreira com as sugestões de vocês.

1- Como faço pra baixar o audio dentro do fluxo no dify? @edneymatias 
2- Como faço pra a pikey entender o audio, muitas vezes ela não entende, tentei colocar na LLM e ela não consegui compreender @acauaferreira
