### ISSUE TITLE
Proxy não atualiza nenhum dado e nem desativa

### ISSUE THREAD

**Issue by rafaWPP** [EvolutionAPI/evolution-api#782]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Proxy não atualiza nenhum dado e nem desativa
para desativar so desconectando da api e reconectando

### What did you expect?

quando criar o proxy precisa poder desativar sem precisar remover os dados o proxy

### What did you observe instead of what you expected?

ele da mensagem de sucesso ao atualizar o proxy mas nao atualiza

### Which version of the API are you using?

2.0.9

### What is your environment?

Linux

**Comment by dpaes** [comment]
Poderia informar se persiste o erro? Caso sim, por favor tente testar a versão 2.1.2 do evolution se persiste, caso sim, nos informe nos comentarios e trabalharemos o quanto antes para corrigir.

**Comment by rafaWPP** [comment]
Erro já não existe mais

Em qui., 28 de nov. de 2024, 14:04, Daniel Paes ***@***.***>
escreveu:
