### ISSUE TITLE
Não Conecta v2.0.9

### ISSUE THREAD

**Issue by redechatsabers** [EvolutionAPI/evolution-api#783]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

quando leio o Qrcode ele le e no celular conecta normal, mas na evolution fica como conectando.

[Evolution API]    v2.0.9  158   -  Thu Aug 15 2024 21:27:21     ERROR   [unhandledRejection]  [object]   
{
  origin: Promise {
    <rejected> Error: Timed Out
        at /evolution/node_modules/baileys/lib/Utils/generics.js:145:32 {
      data: [Object],
      isBoom: true,
      isServer: false,
      output: [Object]
    }
  },

  stderr: 2,
  error: Error: Timed Out
      at /evolution/node_modules/baileys/lib/Utils/generics.js:145:32 {
    data: {
      stack: 'Error\n' +
        '    at promiseTimeout (/evolution/node_modules/baileys/lib/Utils/generics.js:140:19)\n' +
        '    at waitForMessage (/evolution/node_modules/baileys/lib/Socket/socket.js:119:53)\n' +
        '    at query (/evolution/node_modules/baileys/lib/Socket/socket.js:141:22)\n' +
        '    at Object.profilePictureUrl (/evolution/node_modules/baileys/lib/Socket/chats.js:453:30)\n' +
        '    at it.profilePicture (/evolution/dist/main.js:180:4993)\n' +
        '    at contacts.update (/evolution/dist/main.js:171:7411)'
    },
    isBoom: true,
    isServer: false,
    output: { statusCode: 408, payload: [Object], headers: {} }
  }
} 

### What did you expect?

conectar a bailyes

### What did you observe instead of what you expected?

não conecta

### Which version of the API are you using?

v2.0.9

### What is your environment?

Linux

**Comment by sosnoski** [comment]
duplicada #756

mesmo problema por aqui. optamos por voltar para a 2.0.8

**Comment by redechatsabers** [comment]
usa a vwersao?? v2.0.8-rc

**Comment by sosnoski** [comment]
Sim. a v2.0.8-rc nao apresentou este problema aqui

**Comment by redechatsabers** [comment]
aqui deu certo

**Comment by HELIOPOTELICKI** [comment]
Estou recebendo o mesmo erro da issue:

```bash
[Evolution API]  184 - Sat Feb 22 2025 03:41:11   ERROR  [unhandledRejection] [object] {

  origin: Promise {

    <rejected> Error: Timed Out

        at /evolution/node_modules/baileys/lib/Utils/generics.js:170:32 {

      data: [Object],

      isBoom: true,

      isServer: false,

      output: [Object]

    }

  },

  stderr: 2

}

[Evolution API]  184 - Sat Feb 22 2025 03:41:11   ERROR  [unhandledRejection] [object] Error: Timed Out

    at /evolution/node_modules/baileys/lib/Utils/generics.js:170:32 {



{

    stack: 'Error\n' +

      '    at promiseTimeout (/evolution/node_modules/baileys/lib/Utils/generics.js:165:19)\n' +

      '    at waitForMessage (/evolution/node_modules/baileys/lib/Socket/socket.js:117:53)\n' +

      '    at query (/evolution/node_modules/baileys/lib/Socket/socket.js:139:22)\n' +

      '    at Object.executeUSyncQuery (/evolution/node_modules/baileys/lib/Socket/usync.js:62:30)\n' +

      '    at Object.onWhatsApp (/evolution/node_modules/baileys/lib/Socket/chats.js:122:36)\n' +

      '    at Rs.whatsappNumber (/evolution/dist/main.js:251:1191)\n' +

      '    at async Kt.whatsappNumber (/evolution/dist/main.js:2:7165)\n' +

      '    at async Ui.dataValidate (/evolution/dist/main.js:286:62716)\n' +

      '    at async /evolution/dist/main.js:286:115236'

  },

  isBoom: true,

  isServer: false,

  output: {

    statusCode: 408,

    payload: {

      statusCode: 408,

      error: 'Request Time-out',

      message: 'Timed Out'

    },

    headers: {}

  }

}
```

Meu ambiente:

EvolutionAPI: v2.2.3 (latest)

E é um comportamento bem estranho, Eu criei um agente (basicamente uma api em flask, que recebe webhooks da evo e os processa pra jogar para um agente)

Caso eu rode minha api localmente e a evolution_api na vm em prod- Funciona

**Comment by dpaes** [comment]
se localmente funciona e em prod não, tem algo ai... o que tem de diferente no local que no de prod não tem? @HELIOPOTELICKI

**Comment by jonathandebrito** [comment]
Estou com o mesmo erro que começou da noite pro dia:

`[Evolution API]    v2.2.3  212   -  Wed Feb 26 2025 16:01:25     ERROR   [unhandledRejection]  [object]   

{

  origin: Promise {

    <rejected> Error: Timed Out

        at /evolution/node_modules/baileys/lib/Utils/generics.js:170:32 {

      data: [Object],

      isBoom: true,

      isServer: false,

      output: [Object]

    }

  },

  stderr: 2

} 

[Evolution API]    v2.2.3  212   -  Wed Feb 26 2025 16:01:25     ERROR   [unhandledRejection]  [object]   

Error: Timed Out

    at /evolution/node_modules/baileys/lib/Utils/generics.js:170:32 {



{

    stack: 'Error\n' +

      '    at promiseTimeout (/evolution/node_modules/baileys/lib/Utils/generics.js:165:19)\n' +

      '    at waitForMessage (/evolution/node_modules/baileys/lib/Socket/socket.js:117:53)\n' +

      '    at query (/evolution/node_modules/baileys/lib/Socket/socket.js:139:22)\n' +

      '    at groupQuery (/evolution/node_modules/baileys/lib/Socket/groups.js:12:55)\n' +

      '    at Object.groupMetadata (/evolution/node_modules/baileys/lib/Socket/groups.js:22:30)\n' +

      '    at Rs.findGroup (/evolution/dist/main.js:251:12210)\n' +

      '    at /evolution/dist/main.js:251:824\n' +

      '    at Array.map (<anonymous>)\n' +

      '    at Rs.whatsappNumber (/evolution/dist/main.js:251:777)\n' +

      '    at Rs.sendMessageWithTyping (/evolution/dist/main.js:239:8926)'

  },

  isBoom: true,

  isServer: false,

  output: {

    statusCode: 408,

    payload: {

      statusCode: 408,

      error: 'Request Time-out',

      message: 'Timed Out'

    },

    headers: {}

  }

} `

**Comment by iqueroman** [comment]
@HELIOPOTELICKI @jonathandebrito conseguiram resolver? Acontecendo aqui:

> [Evolution API]    v2.2.3  183   -  Thu Jul 24 2025 07:37:49     ERROR   [unhandledRejection]  [object]   
> 
> Error: Timed Out
> 
>     at /evolution/node_modules/baileys/lib/Utils/generics.js:170:32 {
> 
> {
> 
>     stack: 'Error\n' +
> 
>       '    at promiseTimeout (/evolution/node_modules/baileys/lib/Utils/generics.js:165:19)\n' +
> 
>       '    at waitForMessage (/evolution/node_modules/baileys/lib/Socket/socket.js:117:53)\n' +
> 
>       '    at query (/evolution/node_modules/baileys/lib/Socket/socket.js:139:22)\n' +
> 
>       '    at Object.executeUSyncQuery (/evolution/node_modules/baileys/lib/Socket/usync.js:62:30)\n' +
> 
>       '    at Object.onWhatsApp (/evolution/node_modules/baileys/lib/Socket/chats.js:122:36)\n' +
> 
>       '    at Rs.whatsappNumber (/evolution/dist/main.js:251:1191)\n' +
> 
>       '    at async Kt.whatsappNumber (/evolution/dist/main.js:2:7165)\n' +
> 
>       '    at async Ui.dataValidate (/evolution/dist/main.js:286:62716)\n' +
> 
>       '    at async /evolution/dist/main.js:286:115236'
> 
>   },
> 
>   isBoom: true,
> 
>   isServer: false,
> 
>   output: {
> 
>     statusCode: 408,
> 
>     payload: {
> 
>       statusCode: 408,
> 
>       error: 'Request Time-out',
> 
>       message: 'Timed Out'
> 
>     },
> 
>     headers: {}
> 
>   }
> 
> }
