### ISSUE TITLE
TypeBot Closed Session

### ISSUE THREAD

**Issue by tomsilva** [EvolutionAPI/evolution-api#784]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Na versao 1.8.2 quando eu dava um closed pela api da evo ela era fechada, e eliminada.

na versao 2.0.9 isso nao acontece.. ela fica no estado closed e nao e eliminada.

### What did you expect?

criar o metodo deleted nas opcoes do changestatus do typebot ou eliminar a sessao quando enviar o closed

### What did you observe instead of what you expected?

Uso Chatwoot com Evo 
Para a versao 1.8.2 criei uma automacao 
Quando resolve a conversa ele chama o n8n e fechava a sessao para inicar o bot quando o usuario volver a escrever

na versao 2.0.9 isso nao acontece fica em fechada e nao elimina

### Screenshots/Videos

nao tenho 

### Which version of the API are you using?

V2.0.9

### What is your environment?

Linux

### Other environment specifications

8CPU / 25 RAM

### If applicable, paste the log output

.

### Additional Notes

.

**Comment by xiribitarp** [comment]
tambem reparei que quando selecionamos manter o bot aberto, o fluxo automaticamente fica como closed.

**Comment by pedrotecinf** [comment]
Para o bot ser eliminado ele tem que estar com a função manter o bot desativado

**Comment by xiribitarp** [comment]
o que estou falando é que está mudando para closed, mesmo com o manter bot aberto.. na v1, o status ficava como paused, agora está ficando como closed..

**Comment by dpaes** [comment]
Sugiro testarem em uma versão mais recente do evolution para atestarem se o problema persiste. Estarei fechando esta issue até segunda ordem
