### ISSUE TITLE
Problemas de Reconexão ao Usar Redis

### ISSUE THREAD

**Issue by estevanrezende** [EvolutionAPI/evolution-api#79]
Durante testes envolvendo desconexões e reinicializações de containers, identifiquei um problema relacionado ao uso do Redis. Quando ocorre um logout e, posteriormente, tenta-se reconectar, enfrentamos um de dois problemas: ou o novo QRCode gerado não estabelece a conexão, ou ele simplesmente não é gerado.

Notei que ao remover o registro associado no Redis, a funcionalidade volta ao normal. Portanto, sugiro verificar se, após um logout, o registro correspondente no Redis é deletado ou modificado para garantir a correta geração e funcionamento do QRCode em tentativas de reconexão.

Vale ressaltar que, ao configurar minha instância sem o uso do Redis, tudo funciona de maneira adequada, sem a necessidade de qualquer intervenção manual.

Estou usando a versão 1.5

**Comment by DavidsonGomes** [comment]
Redis será descontinuado, recomendamos o uso do mongodb
