### ISSUE TITLE
Dify is disabled

### ISSUE THREAD

**Issue by edubezerra123** [EvolutionAPI/evolution-api#794]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Tentei adicionar o dify via api e manager. E não conecta aparece esse erro "Dify is disable"

### What did you expect?

Conexão do Dify, para uso de chatbot

### What did you observe instead of what you expected?

"Dify is disabled"

### Which version of the API are you using?

2.0.10

### What is your environment?

Windows

**Comment by rogeriosims** [comment]
@edubezerra123 confirma na sua stack se o dify está habilitado no .env
DIFY_ENABLED=false

**Comment by edubezerra123** [comment]
> @edubezerra123 confirma na sua stack se o dify está habilitado no .env DIFY_ENABLED=false

Poderia me ajudar, como faço esse procedimento.

**Comment by marioalexandreantunes** [comment]
@edubezerra123 a sua instalação é em docker - Portainer? se sim : 
1 - Dashboard do **portainer**
2 - Menu lado esquerdo -> **Stack**
3 - No centro do ecrã -> **evolution** 
4 - No centro EDITOR (aba)
está no docker compose verifica ai DIFY_ENABLED=false
Colocar **DIFY_ENABLED=true**
5 - Scroll para baixo até encontrar **Prune services** clicar para ficar azul
6 - **Actions** -> **Update de stack**

**Comment by edubezerra123** [comment]
> @edubezerra123 a sua instalação é em docker - Portainer? se sim : 1 - Dashboard do **portainer** 2 - Menu lado esquerdo -> **Stack** 3 - No centro do ecrã -> **evolution** 4 - No centro EDITOR (aba) está no docker compose verifica ai DIFY_ENABLED=false Colocar **DIFY_ENABLED=true** 5 - Scroll para baixo até encontrar **Prune services** clicar para ficar azul 6 - **Actions** -> **Update de stack**

Instalei pelo easypanel, não consigo seguir esses passos por aqui. Teria outra forma?

**Comment by edubezerra123** [comment]
Consegui! Inseri aqui no Environment Variables, fiquei em dúvida pois não aparecia o Dify. Obrigado a todos pela ajuda

**Comment by edubezerra123** [comment]
Obrigado a todos pela ajuda
