### ISSUE TITLE
Não reconhece quando é enviado um contato

### ISSUE THREAD

**Issue by hereck** [EvolutionAPI/evolution-api#8]
![image](https://github.com/EvolutionAPI/evolution-api/assets/945739/e1553a43-0a28-4bbc-ae15-3bc444bb83d5)
![image](https://github.com/EvolutionAPI/evolution-api/assets/945739/3d49f2c1-9aaa-4c62-b4e7-0bb69b40e4b9)

A Api não reconhece quando um contato é enviado.
Será que seria possível reconhecer, ou ao menos enviar uma mensagem avisando que não suporta esse recurso?

**Comment by DavidsonGomes** [comment]
> ![image](https://user-images.githubusercontent.com/945739/254586148-e1553a43-0a28-4bbc-ae15-3bc444bb83d5.png) ![image](https://user-images.githubusercontent.com/945739/254586276-3d49f2c1-9aaa-4c62-b4e7-0bb69b40e4b9.png)
> 
> A Api não reconhece quando um contato é enviado. Será que seria possível reconhecer, ou ao menos enviar uma mensagem avisando que não suporta esse recurso?

Ja foi corrigido nessa versao

**Comment by hereck** [comment]
<img width="181" alt="image" src="https://github.com/EvolutionAPI/evolution-api/assets/945739/20b32c0f-bc38-4b0f-a384-9fbe2e8e92a3">

Nos meus testes o contato chega assim, a ideia é chegar o telefone também ou somente o nome?

**Comment by calebetec** [comment]
no meu chaga assim:
**Contact:**
**name**: Cassio Saraiva

Aug 17, 8:20 AM

**Comment by DavidsonGomes** [comment]
issue closed if the problem still occurs open a new issue
