### ISSUE TITLE
Coletar informação do número que está entrando em contato

### ISSUE THREAD

**Issue by dev-luizf** [EvolutionAPI/evolution-api#80]
Utilizando a evolution api com o typebot, existe alguma forma de pegar a informação do número que está entrando em contato?

Sei que por parte do typebot há a possibilidade de acessar um bot passando parâmetros na url que podem ser coletados dentro do fluxo, talvez seja interessante algum tipo de configuração do tipo, onde seja possível coletar o número da pessoa que está interagindo com o bot.

O meu caso de uso aqui é o seguinte: Quero fazer um fluxo onde o cliente que está entrando em contato possa gerar automaticamente um teste do serviço. E para evitar que alguém abuse disso utilizando o mesmo número para gerar diversos testes, gostaria de ter a possibilidade de coletar a informação do número de whatsapp da pessoa.

**Comment by dev-luizf** [comment]
Descobri que a API manda o nome configurado no número pelo parâmetro pushName e o número pelo parâmetro remoteJid. Então basta coletar essas duas variáveis no Typebot.

**Comment by montenegromatheus** [comment]
Oi, poderia explicar melhor? onde fica esse parametro pushName? Qual é o endpoint?

**Comment by dev-luizf** [comment]
> Oi, poderia explicar melhor? onde fica esse parametro pushName? Qual é o endpoint?

O parâmetro já está sendo passado pela API, então você pode simplesmente criar uma variável com o mesmo nome no typebot e usá-la:

https://i.imgur.com/3aZvTT2.png
