### ISSUE TITLE
Typebot nao ativa quando criado via api

### ISSUE THREAD

**Issue by JeandersonR2** [EvolutionAPI/evolution-api#804]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Percebido que quando é criado um Typebot via API alem de nao preencher o campo descrição do Typebot ele nao ativa o bot como padrao, e depois quando vai no manager para alterar e preencher o campo, mesmo salvando quando atualiza a pagina a info nao esta mais la, conforme prints em anexo.

o que tambem foi visto é referente aos gatilhos, que passamos "none" e quando altera a instancia esta la como palavra.
![Imagem do WhatsApp de 2024-08-21 à(s) 15 51 53_5d7ae3a1](https://github.com/user-attachments/assets/c35beb37-c2b7-41db-81a3-fa874b776884)
![Imagem do WhatsApp de 2024-08-21 à(s) 15 51 27_e4c31468](https://github.com/user-attachments/assets/69eae14d-e00f-400b-b33a-a67f3c83f8d9)

### What did you expect?

O Correto funcionamento mesmo quando criado via api, acredito que esteja faltando o parametro da descricao do typebot

### What did you observe instead of what you expected?

Não Adiciona um bot padrao (nao salva assim como a descricao)
Não salva a descricao depois de criado via api
e gatilhos sao preenchidos conforme eles quiserem ser preenchidos kkk nao respeitando oque passei

### Which version of the API are you using?

2.0.10

### What is your environment?

Windows

**Comment by JeandersonR2** [comment]
[screen-capture (8).webm](https://github.com/user-attachments/assets/7b97fe53-1050-4583-9546-18323c9f5026)

**Comment by dpaes** [comment]
Já testou usar uma versão mais recente do evolution para validar se persiste o erro? Estarei fechando a issue no momento até segunda ordem
