### ISSUE TITLE
API Instance Connect / Connection State - Gerando mesmo resultado (atendai/evolution-api:v2.0.10) - Impossibilita pegar QRCODE

### ISSUE THREAD

**Issue by xcaledigital** [EvolutionAPI/evolution-api#805]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Ao executar os endpoints para obter o QRCODE percebi que ambas geram o mesmo resultado.

### What did you expect?

As informações contidas no endpoint descrito.

### What did you observe instead of what you expected?

Resultados Iguais.

### Screenshots/Videos

![Connection States - Imagem 1](https://github.com/user-attachments/assets/583d3323-1fc4-440e-bc4c-37fe866e52e5)
![Connection States - Imagem 2-1](https://github.com/user-attachments/assets/f849ca74-60fa-4f98-b8c6-9cc6ef9ddd3a)
![Connection - Imagem 3](https://github.com/user-attachments/assets/490e857f-4f31-42d2-b00d-bd4ece9ebcb4)
![Connection - Imagem 3-2](https://github.com/user-attachments/assets/9d43b76b-076e-40ff-b6d2-ac5d1feb81b1)

### Which version of the API are you using?

2.0.10

### What is your environment?

Windows

### Other environment specifications

VPS 2 - Hostinger

**Comment by Cazula** [comment]
Estou tendo o mesmo problema. 
Eu uso com o chatwoot ele desconectou tudo e não gera mais QRCode

**Comment by andercrist** [comment]
Estou tendo o mesmo problema, parou de gerar o QRcode na versão 2.0.10.

**Comment by alancriaxyz** [comment]
Estou com mesmo problema na imagem: atendai/evolution-api:v2.0.9-rc

**Comment by JonathanMenezesdev** [comment]
Estou com o mesmo problema. Do nada minha instância sumiu e agora não deixa eu gerar um qrcode pra conectar em uma instância nova.

**Comment by xcaledigital** [comment]
**PESSOAL, PARA O MEU CASO** - **RESOLVIDO AQUI**
Eu estava no CREATE INSTANCE passando um BODY Incompleto logo ao executar o **INSTANCE CONNECT** ou **CONNECT STATES** eles não geravam as informações corretas. Após ajustar **RESOLVIDO**.

Para o erro de não gerar o **QRCODE**, percebi a mudança do **WHATSAPP** e coloquei o valor informado lá no **DISCORD** e funcionou. Estou finalizando o chamado.

**Comment by dpaes** [comment]
se mudaram a SESSION-PHONE na variavel de ambiente pra 2.3xxxx vai funcionar

**Comment by xcaledigital** [comment]
Esse foi um dos problemas... Vlwww
Eu estava com problema para gerar p code e Paring Code tbm... Mas RESOLVIDO !
