### ISSUE TITLE
Reabrir conversa desabilitada nao funciona

### ISSUE THREAD

**Issue by AndersonLongara** [EvolutionAPI/evolution-api#809]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Ao configurar a a integracao da api com o chatwoot para abrir uma nova conversa quando a mesma estiver resolvida e nao funciona

### What did you expect?

espero que seja aberta a nova se a atual estiver resolvida

### What did you observe instead of what you expected?

nada.

### Which version of the API are you using?

1.7.5 e ja testei nas mais atuais

### What is your environment?

Linux

**Comment by dpaes** [comment]
Quando vc diz as mais atuais (versões do evolution). Você diz a v2? Pois da 1.7.5 até a 1.8.2 funcionam de forma semelhante. Porém a estrutura de dados e banco de dados da v2 é totalmente diferente, logo para testar você precisaria de uma nova instalação. Poderia informar se o erro persiste e em qual versão você está usando atualmente?
