### ISSUE TITLE
[BUG] Evo 2.0.10 Credenciais OPENAI cadastradas  não carregam na hora do registro de um NOVO OPENAI BOT 

### ISSUE THREAD

**Issue by okubobarros** [EvolutionAPI/evolution-api#813]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Na versão 2.0.10, não é possível registrar um novo bot OPENAI, pq a credencial cadastrada não aparece no form para registro do NOVO OPENAI BOT, o que impossibilita de seguir com cadastro do bot.

### What did you expect?

no form Novo Openai Bot aparecesse a credencial registrada.

### What did you observe instead of what you expected?

Não aparece nenhuma opção de credencial para selecionar, mesmo as já cadastradas

### Which version of the API are you using?

2.0.10

### What is your environment?

Windows

**Comment by dpaes** [comment]
Poderia informar se permanece com esse erro? Caso seja sim, já tentou usar outra versão do evolution api, como o 2.1.2? Nos responda nos comentarios caso seja sim para as duas perguntas.
