### ISSUE TITLE
Chatwoot não conecta na versão 2.1.0-homolog

### ISSUE THREAD

**Issue by alissonduck** [EvolutionAPI/evolution-api#816]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Ao tentar conectar o Chatwoot a uma instância na Evolution **utilizando o Evolution Manager**, depois de preencher os dados do formulário para importar as mensagens e clicar e salvar, acusa o seguinte erro no console:

[Evolution API]    v2.1.0  162   -  Sat Aug 24 2024 15:46:53     ERROR   [Validate]  [object]   
[ 'daysLimitImportMessages is not of a type(s) number' ] 

Tentei alterar o número de dias para importação de mensagens e mesmo assim não salva.

### What did you expect?

Esperava que eu pudesse importar as mensagens antigas do WhatsApp e conectar no Chatwoot.

### What did you observe instead of what you expected?

O problema está nos types da propriedade "daysLimitImportMessages".

### Screenshots/Videos

<img width="940" alt="erro" src="https://github.com/user-attachments/assets/2fc706bd-d2fa-41d4-bcb5-3772671ca64f">

### Which version of the API are you using?

2.1.0-homolog que subiu no docker hub aproximadamente às 15h10 do dia 24/08.

### What is your environment?

Linux

### Other environment specifications

Kubernetes.

### If applicable, paste the log output

[Evolution API]    v2.1.0  162   -  Sat Aug 24 2024 15:46:53     ERROR   [Validate]  [object]   
[ 'daysLimitImportMessages is not of a type(s) number' ]

**Comment by dpaes** [comment]
tentou via api pra ver se mudando no corpo da requisição o daysLimitImportMessages pra number pra ver se funciona?

**Comment by dpaes** [comment]
testei aqui e funcionou (deixei o que estava setado que era 7 dias)

**Comment by dpaes** [comment]
acabei de testar colocando algo diferente do que já estava setado (7) e realmente não cria a caixa de entrada, então o bug é o fato de não poder mudar a quantidade de dias, pois ao mudar ele sai de tipo number para tipo string.

**Comment by alissonduck** [comment]
> acabei de testar colocando algo diferente do que já estava setado (7) e realmente não cria a caixa de entrada, então o bug é o fato de não poder mudar a quantidade de dias, pois ao mudar ele sai de tipo number para tipo string.

antes do último update que rolou na image 2.1.0-homolog, nem isso estava funcionando. Mesmo mantendo 7 dias estava quebrando.

agora está rolando manter em 7 dias, mesmo. O bug agora está no número de dias, se alterar para outro valor que não seja 7, ele entende como string ao invés de number.

**Comment by drauber** [comment]
Fiz o teste baixando o repositório do Github, não está funcional.

**Comment by magdielcardoso** [comment]
Alguem conseguiu resolver?

**Comment by dpaes** [comment]
so vai resolver quando fizerem uma PR ou o davidson ver o trecho que resolve isso mesmo. talvez um merge future resolva isso

**Comment by ferrivitor** [comment]
Mesmo problema por aqui ato o momento

**Comment by lianr7** [comment]
Mesmo problema aqui ainda. Deve ser algo simples de resolver, não? Enquanto não resolver, pra mim não faz sentido, pois preciso puxar histórico mais longo. Espero que consigam neste mês, vai ajudar bastante

**Comment by dpaes** [comment]
Testem uma versão mais recente, pois já está funcionando.
