### ISSUE TITLE
[BUG] Botão de manter bot aberto não funciona na v2

### ISSUE THREAD

**Issue by xiribitarp** [EvolutionAPI/evolution-api#817]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Mesmo quando deixo a opção "Manter bot aberto" ativo, o mesmo está ficando como closed quando chega no final do fluxo do typebot.

Na versão 1.8.2, quando esta opção está habilitada, o mesmo fica como paused, fazendo com que eu consiga finalizar o bot pela automação do n8n.
Neste caso, na v2, não consigo fazer nada, pois quando está closed, não consigo excluir pois não tem endpoint para isso e tenho que colocar um tempo de expiração aproximado, pois caso coloque pouco tempo e o cliente estiver falando com o atendente, o bot volta a ser apresentado.
Ou seja, atualmente, para esta opção habilitada ou não, está com a mesma função.

### What did you expect?

Quando a opção "manter bot ativo" estiver habilitada, quando chegar no final do fluxo do typebot, deveria ficar como paused.

### What did you observe instead of what you expected?

n/a

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/29cd71de-1e57-4cb7-a2d7-1a8982817301)

![image](https://github.com/user-attachments/assets/c39e1fab-9364-4cac-9cfc-2de919f58788)

### Which version of the API are you using?

v2.1.0-homolog

### What is your environment?

Linux

### Other environment specifications

n/a

### If applicable, paste the log output

n/a

### Additional Notes

N/A

**Comment by dpaes** [comment]
Poderia informar se persiste o erro @xiribitarp? caso seja sim, já tentou testar usando o evolution 2.1.2? Nos responda nos comentarios se conseguiu resolver ou não usando outra versão ou se ainda está com esse problema.
