### ISSUE TITLE
Mensagens não são mais recebidas após trocar o domínio do Chatwoot

### ISSUE THREAD

**Issue by pedrofnts** [EvolutionAPI/evolution-api#82]
Alterei o domínio do meu Chatwoot, fiz a alteração em cada instância na API. Continuo conseguindo enviar mensagens normalmente, mas não consigo mais receber. Também não consigo criar mais instâncias no Chatwoot pelo painel (consigo criar, mas não sincroniza no Chatwoot). Como resolver?

**Comment by DavidsonGomes** [comment]
Precisa verificar as configurações na evolution api e no webhook do chatwoot
