### ISSUE TITLE
Após update para versão 1.8.2 da Evolution API, minhas instâncias sumiram.

### ISSUE THREAD

**Issue by tihorti** [EvolutionAPI/evolution-api#822]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Após update para versão 1.8.2 da Evolution API, minhas instâncias sumiram.

### What did you expect?

Fiz o update conforme é pedido no manual, no entanto, as instâncias da API Evolution sumiram.

### What did you observe instead of what you expected?

Não consegui mais instanciar novos números e as minhas instâncias não aparecem mais.

### Which version of the API are you using?

1.8.2

### What is your environment?

Windows

### If applicable, paste the log output

 TypeError: Cannot read properties of undefined (reading 'ENABLED')

origin: 'uncaughtException',
stderr: 2,
 error: Error: listen EADDRINUSE: address already in use :::8080
 code: 'EADDRINUSE',
 errno: -98,
 syscall: 'listen',
 address: '::',
 port: 8080

**Comment by dpaes** [comment]
Então @tihorti, se vc não está usando mongoDB de banco de dados, realmente tem esse perigo de perder as instancias. Como a versão que você mencionou não terá novas correções, estarei fechando essa issue. Estaremos focando apenas na versão 2 em diante do evolution. Caso tenha algum problema com a versão 2, poderemos corrigir nas proximas atualizações.
