### ISSUE TITLE
Falha ao conectar o servidor

### ISSUE THREAD

**Issue by eldoncosta1** [EvolutionAPI/evolution-api#827]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Quando rodo um npm start ta dando o seguinte erro:
'Failed to connect to the file server',
  'connect ECONNREFUSED 127.0.0.1:5656',
  'Error: connect ECONNREFUSED [127.0.0.1:5656\](javascript:void(0);)n' +

### What did you expect?

que o servidor conecte na porta 5656

### What did you observe instead of what you expected?

que da falha ao tentar conectar

### Which version of the API are you using?

1.8.2

### What is your environment?

Linux

**Comment by dpaes** [comment]
está usando vps ou é localhost?

**Comment by eldoncosta1** [comment]
localhost

**Comment by dpaes** [comment]
tente usar ngrook

**Comment by GuilhermeAssmann** [comment]
@eldoncosta1 estava com um problema parecido rodando um container tentando integrar chatwoot com a evo, o problema era de network, os containers não se enxergavam, podes informar pra gente o que você está tentando fazer? se está usando docker ou algo do tipo.

**Comment by eldoncosta1** [comment]
oi @GuilhermeAssmann , tava tentando rodar tudo dockerizado

**Comment by GuilhermeAssmann** [comment]
@eldoncosta1 amigo, verifica como está sua rede interna do docker, importante estar tudo em bridge, verifica também se os containers tem comunicação entre si, não encontrei o erro em nenhum lugar, foi na base do teste e chatgpt hehee.

**Comment by braiaagency** [comment]
Conseguiu resolver esse erro? estou com o mesmo problema

**Comment by arthurilha** [comment]
Conseguiram resolver isso? estou tendo dificuldade de fazer essa conexão no localhost, utilizando o docker.

**Comment by eldoncosta1** [comment]
ainda não testei a sugestão do @GuilhermeAssmann, vcs testaram?

**Comment by dpaes** [comment]
Estarei fechando a issue pelo fato da versão mencionada não estar recebendo novas correções. Estaremos trabalhando apenas na v2 de agora em diante, se precisar de ajuda, temos os foruns disponíveis na comunidade do discord, whatsapp e etc.
