### ISSUE TITLE
Integration Flowise and Typebot Does Not Work with Audio Evo 2.1

### ISSUE THREAD

**Issue by Witroch4** [EvolutionAPI/evolution-api#828]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

When I send an audio message, the payload is sent with the metadata of the message instead of the actual audio itself. For example, the input extracted from Langflow looks like this:

{  
    "input": "audioMessage|3AE5AA6C4D1B685E692A, Meu nome é Witalo Rocha."  
}  
As a result, the AI agent or the Typebot interprets the message as audioMessage|3AE5AA6C4D1B685E692A, leading to incoherent responses, such as:

{  
    "output": "<function=chain_atendimento_humano>{\"input\": \"Witalo Rocha needs human assistance to discuss additional questions about the disability retirement case.\"}<function>"  
}  
This issue arises because the audio message's metadata is being processed incorrectly, causing the system to respond based on the textual part of the metadata instead of the content of the audio message itself.

### What did you expect?

Ideally, the payload sent should contain only the audio, allowing the AI agent or the Typebot to analyze the content of the audio message and generate a coherent response based on what was said. If it is not possible to send the audio content, then no message should be sent at all.

### What did you observe instead of what you expected?

Make all integrations for Flowise in version 2.1, send a message, and you will notice that it works normally. However, if you send audio, you will see the error occur.

### Screenshots/Videos

<img width="659" alt="Sem título" src="https://github.com/user-attachments/assets/0a809896-34ca-4362-91a2-bb105825992e">

### Which version of the API are you using?

2.1

### What is your environment?

Docker

**Comment by dpaes** [comment]
@Witroch4 are u still with this problem? If its a yes, please try to use another version of evolution api, like 2.1.2 e see if resolve the problem. if still with the problem, please answer in this topic
