### ISSUE TITLE
Anexos não são enviados na integração com Chatwoot utilizando S3 (v2.1.0)

### ISSUE THREAD

**Issue by rodrigosilvafelipe** [EvolutionAPI/evolution-api#833]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Quando um anexo é enviado pelo chatwoot, a mensagem não é enviada pela evolution. Isso utilizando a amazon S3 pra salvar os anexos no chatwoot. Nos logs da evolution aparece o status 404 ao buscar o anexo no link da S3, como se o anexo não existisse. Consegui resolver isso colocando o N8N no meio do caminho, pra fazer uma espera curta antes de enviar pra evolution, assim o anexo é encontrado. Parece que quando a evolution busca o anexo na S3 o link ainda não está disponível, por isso ocorre a falha. Anexos leves não geram esse problema, isso ocorre com anexos maiores, nos meus testes ocorreu com áudio, pasta compactada com mais de 9mb.

### What did you expect?

Enviar anexos com o chatwoot integrado à S3.

### What did you observe instead of what you expected?

O link buscado pela evolution na S3 ainda não está disponível no momento da busca.

### Which version of the API are you using?

2.1.0

### What is your environment?

Docker

**Comment by juliancesar** [comment]
@rodrigosilvafelipe, este é um problema do Chatwoot! Eu tive que resolver alterando o componente do chatwoot para tentar 3 vezes antes de dar o 404! É estranho, mas aparentemente são poucas pessoas tem esse erro ou não sabem que existe!

Estou usando a versão 3.11.1 do chatwoot.

**Comment by rodrigosilvafelipe** [comment]
Entendi @juliancesar , vou manter meu fluxo no N8N pra tratar isso aqui, obrigado!

**Comment by coffeverton** [comment]
> [@rodrigosilvafelipe](https://github.com/rodrigosilvafelipe), este é um problema do Chatwoot! Eu tive que resolver alterando o componente do chatwoot para tentar 3 vezes antes de dar o 404! É estranho, mas aparentemente são poucas pessoas tem esse erro ou não sabem que existe!
> 
> Outro detalhe é que mesmo sem usar S3 no Evolution o problema ocorre para mim, mas utilizo S3 no Chatwoot e acredito que o problema está neste ponto Chatwoot + S3.
> 
> Estou usando a versão 3.11.1 do Chatwoot.

Olá, você poderia dar mais detalhes de como corrigiu esse problema? O que você quer dizer com "alterando o componente do chatwoot"? A correção foi feita no código do Chatwoot ou do EvolutionApi?
