### ISSUE TITLE
Chatwoot - Não envia imagem

### ISSUE THREAD

**Issue by tiagocaus** [EvolutionAPI/evolution-api#837]
Porque não é possível enviar imagem do chatwoot? Ele recebe imagem, mas não envia. Uso o MINIO.

https://i.imgur.com/j5p6vgN.png
![image](https://github.com/user-attachments/assets/964b500f-cc51-414d-b39e-610aae0f3beb)

**Comment by dpaes** [comment]
falta descrever mais informações amigo, versão do evolution api(v1,v2), ambiente OS utilizado(windows,linux,mac), tipo de instalação(docker,nvm), versão do chatwoot(3.9, 3.10, 3.11, 3.12), se está usando banco de dados e entre outras informações que podem explicar o motivo de não estar funcionando. Variaveis de ambiente também podem ser o motivo (ou a falta delas).

**Comment by MathRibera** [comment]
Resolveu?
