### ISSUE TITLE
Bug Typebot interagindo na hora errada.

### ISSUE THREAD

**Issue by MarcosBrendonDePaula** [EvolutionAPI/evolution-api#84]
Aqui onde trabalho estamos tendo um problema quando nos iniciamos uma conversar com o cliente através do **CHATWOOT** a mensagem vai sem o bot da forma correta, mas quando o cliente responde a essa mensagem o typeboot inicia seu fluxo e começa a interceptar a conversa entre nos e o cliente.

Para esse problema eu tenho uma ideia de solução que foi implementada e testada, mas devido a meu pouco conhecimento da estrutura do projeto ficou bem desorganizado, então venho aqui descrever a ideia.

O problema ocorre devido a não existir ainda uma instância do typeboot no momento em que eu envio uma mensagem pelo **CHATWOOT** me impossibilitando de pausar "pois ainda nem existe".

A minha ideia de solução consiste em criar essa instancia independentemente se é uma mensagem de entrada ou de saída informando na hora da criação se é uma instância criada por mim ou se é uma instância criada a partir do contato do cliente onde essa informação é passada para o typeboot onde posso agora realizar um controle interno com apenas um "IF" se o bot deve ou não ser usado. 

Essa solução também ajuda a obter um controle melhor do typeboot onde não fica dependente do conector para tomar essa decisão proporcionando um aumento de controles.

Sei que é possível chegar no resultado utilizando algum método de armazenamento externo e utilizar uma "API" para se obter esse resultado, mas ainda acho pouco eficiente se comparado a esse modo que descrevi.

Se for necessário posso compartilhar o código está desorganizado, se nescessario compartilho mesmo assim.

**Comment by Suporte4Mrk** [comment]
Oi Amigo Boa Tarde, Estou com esse mesmo problema, conseguiu alguma solução que possa ajudar?

**Comment by Kleitonprudente** [comment]
> Aqui onde trabalho estamos tendo um problema quando nos iniciamos uma conversar com o cliente através do **CHATWOOT** a mensagem vai sem o bot da forma correta, mas quando o cliente responde a essa mensagem o typeboot inicia seu fluxo e começa a interceptar a conversa entre nos e o cliente.
> 
> Para esse problema eu tenho uma ideia de solução que foi implementada e testada, mas devido a meu pouco conhecimento da estrutura do projeto ficou bem desorganizado, então venho aqui descrever a ideia.
> 
> O problema ocorre devido a não existir ainda uma instância do typeboot no momento em que eu envio uma mensagem pelo **CHATWOOT** me impossibilitando de pausar "pois ainda nem existe".
> 
> A minha ideia de solução consiste em criar essa instancia independentemente se é uma mensagem de entrada ou de saída informando na hora da criação se é uma instância criada por mim ou se é uma instância criada a partir do contato do cliente onde essa informação é passada para o typeboot onde posso agora realizar um controle interno com apenas um "IF" se o bot deve ou não ser usado.
> 
> Essa solução também ajuda a obter um controle melhor do typeboot onde não fica dependente do conector para tomar essa decisão proporcionando um aumento de controles.
> 
> Sei que é possível chegar no resultado utilizando algum método de armazenamento externo e utilizar uma "API" para se obter esse resultado, mas ainda acho pouco eficiente se comparado a esse modo que descrevi.
> 
> Se for necessário posso compartilhar o código está desorganizado, se nescessario compartilho mesmo assim.

Achei interessante essa ideia, e mais pratica do que esperar o cliente responder para depois eu pegar a sessão no type e pausar!
E ai pessoal da @dgcode-tec @DavidsonGomes o que vcs acham dessa ideia?

**Comment by fabiohenriquen** [comment]
Acho que esse problema do bot interceptar a conversa é uma reclamação recorrente. Vi algumas ferramentas solucionarem essa questão com uma função de pausar o bot para um determinado número de forma nativa. 

Aqui eu uso o n8n para mudar o status da sessão para paused. 

Tem que tomar cuidado somente pq se vencer o prazo da janela de interação definido na criação da instancia, o bot reinicia.

**Comment by DavidsonGomes** [comment]
Corrigido na versao 1.5.1

**Comment by pronovaes** [comment]
SOLUÇÃO:
Utilizo chatwoot com Evolution e Typebot. O bot também estava interagindo na hora errada e interrompendo o atendimento humano. 

A solução vc aplica no fluxo do seu typebot da seguinte forma:

**Em todas as extremidades (conteiners) que o bot deveria sair do jogo e parar de agir:**
a) Crie um novo conteiner e inclua um elemento T (Colect)
b) Ainda nesse elemento **T(Colect**) onde está escrito "Save answer in a variable" digite **#sair**
c) Conecte o seu conteiner de saida (aquele onde o bot para de agir)  no novo conteiner onde está o Colect #sair
d) Crie um novo conteiner e nele inclua um elemento "Webhook"
e) Em "Paste webhook url" inclua o url da Evo: Ex: http://seuip:8080/typebot/set/whatsapp
f) Method é POST
g) Em headers no campo Key, escreva: apikey
h) Em value coloque a key da evo
i) Em body selecione custom body e inclua o cód abaixo:
{
    "remoteJid": "{{remoteJid}}",
    "status": "closed" /* opened, paused, closed */
}
J) Conecte o conteiner #sair no conteiner que está o webhook.

Pronto.
