### ISSUE TITLE
[BUG] Falha ao importar histórico de mensagens

### ISSUE THREAD

**Issue by dnl4** [EvolutionAPI/evolution-api#843]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Ao criar uma instância, escanear integrado ao chatwoot, as mensagens não foram importadas

### What did you expect?

Importar todas as mensagens para o chatwoot

### What did you observe instead of what you expected?

Apesar de não importar para o chatwoot, foi importado para o banco de dados do evolution, tanto que aparece no manager:

### Screenshots/Videos

<img width="455" alt="image" src="https://github.com/user-attachments/assets/7819741f-7a17-49d7-8734-2762f746c26c">

### Which version of the API are you using?

v2.1.0

### What is your environment?

Windows

### Other environment specifications

ubuntu, docker

### If applicable, paste the log output

recv 30 chats, 21 contacts, 4937 msgs (is latest: false, progress: undefined%), type: undefined
recv 21 chats, 12 contacts, 4938 msgs (is latest: false, progress: undefined%), type: undefined
recv 20 chats, 14 contacts, 4950 msgs (is latest: false, progress: undefined%), type: undefined
recv 20 chats, 14 contacts, 4942 msgs (is latest: false, progress: undefined%), type: undefined
recv 10 chats, 6 contacts, 4955 msgs (is latest: false, progress: undefined%), type: undefined
recv 24 chats, 15 contacts, 4960 msgs (is latest: false, progress: undefined%), type: undefined
recv 20 chats, 15 contacts, 4997 msgs (is latest: false, progress: undefined%), type: undefined
recv 15 chats, 8 contacts, 3770 msgs (is latest: false, progress: undefined%), type: undefined
[Evolution API]    v2.1.0  169   -  Thu Aug 29 2024 15:53:47     WARN   [ChatwootService]  [string]  conversation not found 
[Evolution API]    v2.1.0  169   -  Thu Aug 29 2024 15:53:47     ERROR   [ChatwootImport]  [string]  Error on import history contacts: error: ON CONFLICT DO UPDATE command cannot affect row a second time 
[Evolution API]    v2.1.0  169   -  Thu Aug 29 2024 15:53:48     WARN   [ChatwootService]  [string]  conversation not found

**Comment by dpaes** [comment]
vc scaneou dentro do chatwoot ou no evolution? pq eu so consigo importar se scaneio dentro do chatwoot. Por exemplo, vc cria a instancia, seta o comportamento que quiser mas coloca sincronizar completo e salva. Depois vai na integração do chatwoot e configura certinho e salva (selecionando pra criar automaticamente a caixa de entrada no chatwoot). Dai lá no chatwoot vc vai ter uma conversa na caixa de entrada com o evolution e nela vai ser passado um QR Code, ao passar, depois de 1 minuto ele vai sincronizar as mensagens (porém por enquanto ele não importa imagens da sincronização, só texto).

**Comment by adrianomirandaa** [comment]
@dnl4 o seu ambiente está em Docker? Estou com o mesmo problema e no meu caso vejo mensagens de erro no log da aplicação e do Postgres informando que a tabela "messages" não existe. Pelo que vi no banco não existe de fato esta tabela "messages" e sim a tabela "Message" e no caso do Postgres acredito que seja case sensitive. 

ERROR:  relation "messages" does not exist
