### ISSUE TITLE
Serviço restartando em loop ao criar uma nova instancia

### ISSUE THREAD

**Issue by alessandrosales** [EvolutionAPI/evolution-api#848]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

`evolution_api  | {"level":30,"time":1725128819762,"pid":184,"hostname":"a167e20b4859","trace":"Error: WebSocket Error ()\n    at WebSocketClient.<anonymous> (/evolution/node_modules/baileys/lib/Socket/socket.js:617:17)\n    at WebSocketClient.emit (node:events:519:28)\n    at WebSocketClient.emit (node:domain:488:12)\n    at WebSocket.<anonymous> (/evolution/node_modules/baileys/lib/Socket/Client/web-socket-client.js:46:100)\n    at WebSocket.emit (node:events:519:28)\n    at WebSocket.emit (node:domain:488:12)\n    at emitErrorAndClose (/evolution/node_modules/ws/lib/websocket.js:1041:13)\n    at ClientRequest.<anonymous> (/evolution/node_modules/ws/lib/websocket.js:881:5)\n    at ClientRequest.emit (node:events:519:28)\n    at ClientRequest.emit (node:domain:488:12)","msg":"connection errored"}
^Ccanceled`

### What did you expect?

Eu apenas esperava que o código funcionasse de acordo com a documentação

### What did you observe instead of what you expected?

Eu testei em várias versões da imagem, por fim tentei executar com essa buildando localmente, mas sem sucesso

### Screenshots/Videos

<img width="1215" alt="image" src="https://github.com/user-attachments/assets/1a32151a-c10a-40d6-8164-04234f64e823">

### Which version of the API are you using?

<img width="782" alt="image" src="https://github.com/user-attachments/assets/b3fef0a5-6c6b-4399-8c70-ac9169676143">

### What is your environment?

Windows

**Comment by alessandrosales** [comment]
Eu observei que depois de algumas horas ele começou a gerar o QRCode, alguém já teve esse comportamento?

**Comment by dpaes** [comment]
Certo, não entendi que versão vc está usando, a imagem ali parece ser customizada. sugiro testar em uma versão como 2.1.2 ou 2.2.0. E de preferencia não ser em localhost e pm2, pois existe outras complicações e necessidades para o pleno funcionamento. A forma mais otimizada e garantida de funcionar é via docker compose file, que tem no repositorio do evo os .yml de exemplo. Normalmente a geração do QR Code também está diretamente proporcional a versão do CONFIG_SESSION_PHONE_VERSION, se estiver setado uma versão expirada ou não estiver setado nada, ele vai usar o que estiver na dependencia da baileys, que dependendo da versão do evolution, já estará uma versão expirada.
