### ISSUE TITLE
esta dando bug MESSAGES_UPSERT para n8n versão 1.5

### ISSUE THREAD

**Issue by jucenir-code** [EvolutionAPI/evolution-api#86]
![Captura de Tela 2023-08-29 às 06 48 38](https://github.com/EvolutionAPI/evolution-api/assets/6982452/7109238e-6348-480a-954e-0cb0479d4435)

**Comment by emersonbock** [comment]
Amigo, deixe a configuração do Host: localhost e reinicie, isso aconteceu comigo. Versão 1.48. e 1.5.0

**Comment by jucenir-code** [comment]
Obrigado! Deu certo.
