### ISSUE TITLE
não é possível alterar campos da integração chatwoot no manager (v2.1.1-homolog)

### ISSUE THREAD

**Issue by dpaes** [EvolutionAPI/evolution-api#860]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

atualizei a stack da v2 pra testar a integração com chatwoot e ver as melhorias. Porém não foi possível preencher os campos, o css ou o html do manager não permitem inserir dados, logo não consegui fazer a integração via manager

### What did you expect?

Esperava que pudesse preencher os campos e salvar a integração como de costume na versão anterior v2.1.0

### What did you observe instead of what you expected?

impossibilitado de preencher os campos do chatwoot integration

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/eb604872-f49a-43bc-8f58-1dcb04142f11)

![image](https://github.com/user-attachments/assets/baa7b14c-8714-4768-b7f7-dbf9c077f1c1)
não sei se ajuda esse print

### Which version of the API are you using?

v2.1.1-homolog

### What is your environment?

Docker

**Comment by michaelvips** [comment]
Já tentou em outro navegador ? não seria algum erro de cache ?

**Comment by WilliamAlmeida** [comment]
Aconteceu comigo tbm, estava testando agora pouco e não consigo alterar nada

**Comment by dpaes** [comment]
não @michaelvips, testei em 3 navegadores diferentes. creio ser problema na versão mesmo. Foi feito alguma alteração que ocorreu isso. porque uma versão antes os mesmos campos funcionam normal. (fiz esse teste)

**Comment by WilliamAlmeida** [comment]
Testei aqui ultimo deploy atendai/evolution-api:v2.1.1-homolog e voltou a liberar os campos, esse problema não tem mais pessoal.

**Comment by dpaes** [comment]
vou testar aqui antes de fechar a issue @WilliamAlmeida

**Comment by dfares1987** [comment]
boa tarde consigo acessar e editar os campos porem nao salva e nao cria a caixa de entrada no chatwoot

**Comment by dpaes** [comment]
é realmente não está funcionando nessa ultima versão 2.1.1-homolog, parece que foi arrumado o problema de não preencher os campos, mas não está criando automaticamente a caixa de entrada, preenchi tudo e não teve nenhuma ação ao salvar.

**Comment by WilliamAlmeida** [comment]
Aqui funcionou certinho, me passa algum contato que te ajudo

**Comment by dpaes** [comment]
realmente erro persiste, é como se fosse nem feito o fetch

**Comment by dpaes** [comment]
resolvido nas ultimas atualizações da v2.1.1
