### ISSUE TITLE
Build Falhando - isOnWhatsapp

### ISSUE THREAD

**Issue by drauber** [EvolutionAPI/evolution-api#863]
### Bem-vido!

- [X] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

Após clonar o projeto, executar npm install e tentar rodar um npm run build, recebo o erro conforme print:

![image](https://github.com/user-attachments/assets/3d19a5ed-df81-44e5-a0de-e5c2a21e0e78)

### O que você esperava?

Que o Build rodasse normalmente.

### O que vc observou ao invés do que esperava?

![image](https://github.com/user-attachments/assets/292faaf0-7fd4-41aa-a6c2-7b0f994d231a)

### Qual versão da API você está usando?

V2.0

### Qual é o seu ambiente?

Windows

**Comment by deivisonrpg** [comment]
Como teve alteração de schema tem que ser feito o db:generate antes.

npm install
npm run db:generate
npm run build

**Comment by drauber** [comment]
> npm run db:generate

Puts, achei que o db:generate fosse recriar a base. Valeu mesmo.
