### ISSUE TITLE
OpenAI enviando mensagem duplicada

### ISSUE THREAD

**Issue by vitorcherulli** [EvolutionAPI/evolution-api#870]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Olá tudo bem?
Alguém sabe como resolver esse erro quando conectado a OpenAI?
Está enviando uma ou duas mensagens extras, e sempre com um anexo.
Esse erro acontece principalmente quando enviamos áudios e textos.
Obrigado e Aguardo

### What did you expect?

Enviar somente uma mensagem

### What did you observe instead of what you expected?

Não sei nada sobre o erro

### Screenshots/Videos

![Captura_de_tela_2024-09-07_173250](https://github.com/user-attachments/assets/946dc60d-979d-4106-bb47-df148e464c12)

### Which version of the API are you using?

2.0

### What is your environment?

Windows

### Other environment specifications

Chatwoot and Evolution 2.0

**Comment by dpaes** [comment]
Qual versão especificamente da v2 do evolution? Pois existem varias. Ainda persiste o problema?

**Comment by vitorcherulli** [comment]
Esse problema parou na ultima versão da evolution!

Tem outros problemas como, o bot da open ai não pausar.

**Comment by dpaes** [comment]
certo @vitorcherulli, sugiro que abra outra issue pra esse caso q vc comentou, estarei fechando a issue
