### ISSUE TITLE
Dify para de responder a integração após algumas mensagens

### ISSUE THREAD

**Issue by luccamrofc** [EvolutionAPI/evolution-api#872]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Realizo a conexão nativa do Manager da Evolution 2.1.0 e seleciono o fluxo(chatbot no meu caso), conecto as chaves de API e configuro os debounce. Tudo funciona perfeitamente por alguns minutos, mas após uma quantidade 'x' de mensagens, a IA simplesmente para de responder, inclusive o dify, nos logs, não atualiza o item da conversa, ou seja, acredito que para de chegar ao Dify.

Não existe uma regra, mas não passei de 10 mensagens antes desse erro ocorrer.

### What did you expect?

Conectar as chaves de API, realizar a conexão e manter sempre o atendimento funcional, seguindo o tempo que determinei nas configurações para expirar.

### What did you observe instead of what you expected?

Um encerramento abrupto da conversa sem motivo.

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/5f5bcbba-d878-46b8-98aa-9493c3c7872e)
![image](https://github.com/user-attachments/assets/d0b7b53a-a0eb-46df-85a2-3cfde82fe5ad)

### Which version of the API are you using?

2.1.0

### What is your environment?

Docker

**Comment by luccamrofc** [comment]
> Estou tendo o mesmo problema por aqui. Qual versão do whatsapp você está usando na config do evolution?

Não entendi muito bem a pergunta irmão, mas no caso vou citar tudo(provavelmente 1 deles é o que vc quis dizer): Eu utilizo o Wpp Business no IOS na versão mais recente, na API conecto pelo Baileys. 

Aliás, uma informação que acabei vendo no log da Evo, não sei se por algum motivo seria esse o erro, mas ele tenta puxar ou enviar algum link na mensagem, e esse link gera algum erro interno que desconheço(sem mais infos no log), que interrompem a conversa.

![image](https://github.com/user-attachments/assets/a18630b2-d091-452b-9c9a-e72d7415ba34)

**Comment by ttibau** [comment]
Existe uma variável de ambiente chamada `CONFIG_SESSION_PHONE_VERSION` Ela é a versão do wpp que a evolution utiliza. No meu caso está a `2.3000.1015901307`

**Comment by luccamrofc** [comment]
> Existe uma variável de ambiente chamada `CONFIG_SESSION_PHONE_VERSION` Ela é a versão do wpp que a evolution utiliza. No meu caso está a `2.3000.1015901307`
> 
> Quando entramos em https://web.whatsapp.com/check-update?version=0&platform=web
> 
> A versão atual é a `2.2413.51`
> 
> Pode ser que seja isso, devemos aguardar alguém que manje mais do assunto pra dar a certeza.

Ah sim, estou nessa config:

      - CONFIG_SESSION_PHONE_VERSION=2.3000.1015901307

**Comment by Unescopi** [comment]
Amigos estou com o mesmo problema a dias, ia até abrir um issue, mas vou aproveitar o gancho. O que aconteceu aqui no meu: 
Após várias mensagens o bot simplesmente perde a conexão com a dify, nas logs a api do evo recebe a mensagem mas não retorna a resposta da dify.
Outra coisa que vi que aconteceu várias vezes, quando algum número manda uma foto na conversa ele também para de responder, igualmente no erro anterior. 

O que tenho feito para voltar único jeito após várias tentativas, excluir a config do dify no evo, excluir a chave api do bot na dify e cadastrar tudo novamente. 
(estou usando gemini 1.5 flash como agente)

**Comment by louisfds** [comment]
Mesmo problema por aqui, 80% das conversas vão certinho, mas o restante... tá um combo dos bugs relatados acima, as vezes para de responder do nada, as vezes não responde nem a primeira, as vezes a resposta quebra pela metada e ai para, as vezes recebe uma imagem e para.

No meu caso, pra resolver, tenho que excluir a sessão do contato :(

**Comment by SystemmaxRefra** [comment]
Estou com o mesmo problema, também estou utilizando a mesma versão do whatsapp bussines citado acima por vocês, e estou com a versão 2.1.0, oq esta acontecendo comigo é que as vezes quando mando uma primeira mensagem  a resposta nao vem, após isso em uma segunda tentativa ela vem porem a mensagem nunca vem completa, esta comendo varias palavras da resposta que deveria vir da dify, e no log do agent na dify, tudo esta funcionando perfeitamente

**Comment by SystemmaxRefra** [comment]
Pessoal boa noite, olha eu aqui novamente, vim trazer umas observações para vocês, primeira delas é NÃO ATUALIZE PARA VERSÃO MAIS NOVA DO WHATS BUSSINES, com essa versão a Evolution não esta gerando os QRcode para conexão, então até que tenha uma correção, mantenha a versão atual, outra observação importante, os problemas de perder conexão e ou cortar mensagens depois de fazer diversos teste, percebi que so acontece com AGENTES DO DIFY ou seja com Chat ou Chatflow esse problema não acontece, pelo que andei verificando os AGENTES trabalha com uma forma aleatória de envio dos textos que a Evolution ainda não consegue tratar e acaba gerando esses erros, ai fica a pergunta mais se não posso utilizar agente como vou usar o melhor beneficio que é invocar ferramentas.

Para fazer isso você pode criar um chatbot do tipo chatflow dentro do flow você consegue invocar as ferramentas e utiliza-las no fluxo e na conversa, da um pouco mais de trabalho mais funciona perfeitamente pois quando vai conectar com a instancia da Eolution você vai criar um bot do tipo chatbot pois se trata de um chatflow, sendo assim a conexão funciona perfeitamente!

**Comment by louisfds** [comment]
> Pessoal boa noite, olha eu aqui novamente, vim trazer umas observações para vocês, primeira delas é NÃO ATUALIZE PARA VERSÃO MAIS NOVA DO WHATS BUSSINES, com essa versão a Evolution não esta gerando os QRcode para conexão, então até que tenha uma correção, mantenha a versão atual, outra observação importante, os problemas de perder conexão e ou cortar mensagens depois de fazer diversos teste, percebi que so acontece com AGENTES DO DIFY ou seja com Chat ou Chatflow esse problema não acontece, pelo que andei verificando os AGENTES trabalha com uma forma aleatória de envio dos textos que a Evolution ainda não consegue tratar e acaba gerando esses erros, ai fica a pergunta mais se não posso utilizar agente como vou usar o melhor beneficio que é invocar ferramentas.
> 
> Para fazer isso você pode criar um chatbot do tipo chatflow dentro do flow você consegue invocar as ferramentas e utiliza-las no fluxo e na conversa, da um pouco mais de trabalho mais funciona perfeitamente pois quando vai conectar com a instancia da Eolution você vai criar um bot do tipo chatbot pois se trata de um chatflow, sendo assim a conexão funciona perfeitamente!

Então, estou tendo problema tanto com agente quanto com chatbot infelizmente... uma coisa que notei foi que os agentes as vezes comem umas letras, espaços e tals e o chatbot não, mas os 2 da problema de parar de responder

**Comment by izichtl** [comment]
Boas tardes, dêem uma olhada aqui 

https://github.com/EvolutionAPI/evolution-api/pull/825#issuecomment-2359603549
Parece que ele resolveu o problema dos espaços e caracteres, falta o subir uma versão na image. 

mas se usar a ultima homolog que tem no DockerHub, esse problema está resolvido. 

atendai/evolution-api:v2.1.1-homolog

**Comment by clebercardoso123** [comment]
Estou com esse problema na Evolution 2.2.0. Alguém sabe como resolver?

**Comment by acauaferreira** [comment]
MEEESMO PROBLEMA AQUI, BOT PARANDO DO NADA  V2.3.3  
e DIFY CLOUD  V1.1.2
