### ISSUE TITLE
Typebot interrompe atendente

### ISSUE THREAD

**Issue by singulativo** [EvolutionAPI/evolution-api#873]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Sempre que envio uma mensagem para um contato e ele me responde, o Typebot inicia um fluxo, mesmo que eu já estivesse na conversa desde o início, pois fui eu quem entrou em contato primeiro.

### What did you expect?

Preciso que ele não seja iniciado quando eu envio uma mensagem para o contato.

### What did you observe instead of what you expected?

Observei que, quando envio uma mensagem para um contato, nenhuma sessão é iniciada; a sessão só é criada quando o contato responde.

### Which version of the API are you using?

Typebot: Version: 2.28.2
Evo: Testado na 2.1.0 e 2.1.1

### What is your environment?

Other

### Other environment specifications

Ubuntu 24.04

**Comment by dpaes** [comment]
Você precisa fazer uma tratativa no lado do typebot também, para caso o fromMe seja true, ele ignore. Mesmo do lado do evolution ter opção para em caso do atendente responder, ele deveria ignorar. Tente a versão 2.1.2 e veja se persiste o problema
