### ISSUE TITLE
API fica tentando fazer conexões após erro

### ISSUE THREAD

**Issue by matheustcw4** [EvolutionAPI/evolution-api#875]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Configurei a Evolution no meu ambiente local e ela funcionou normalmente durante horas, porém após um período de funcionamento ela apresentou o erro abaixo:
{"level":50,"time":1725891020874,"pid":4108,"hostname":"meuhost","node":{"tag":"stream:error","attrs":{"code":"503"}},"msg":"stream errored out"}. E após isso começou a ter o comportamento conforme a imagem
![WhatsApp Image 2024-09-09 at 15 34 47](https://github.com/user-attachments/assets/2c2ca666-8022-46ff-97b3-82e37ceb9aa8)

E ficou dessa forma até meu número ser Banido do WhatsApp, alguém poderia me ajudar por favor ? Estou usando a versão 1.8.2

### What did you expect?

Que funcionasse normalmente

### What did you observe instead of what you expected?

Que deu problema

### Which version of the API are you using?

1.8.2

### What is your environment?

Windows

### Other environment specifications

Windows 20GB RAM
Intel Xeon
Windows Server 2012 R2

**Comment by dpaes** [comment]
Esta versão não está mais recebendo correções, sugiro que você crie uma nova instalação usando a v2, especificamente a 2.1.2 que creio ser mais estável. Lembrando que na v2 o banco de dados é postgres e o uso do redis é indispensável. Estarei fechando a issue pelo fato de se tratar de uma versão que não receberá mais correções.
