### ISSUE TITLE
Expirar em minutos nas versões da V2 não funciona integrado com o Dify

### ISSUE THREAD

**Issue by AxiusBrasil** [EvolutionAPI/evolution-api#877]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Pessoal, já testei todas as versões da V2 mas quando faço a integração nativa do Dify com a Evo, coloco um tempo para expirar essa função não está funcionando. Testei com o a integração do Typebot e funcionou normal.

Só essa questão que tá pegando para eu colocar em produção.

### What did you expect?

Que o bot voltasse a ser acionado quando o tempo de expirar terminasse.

### What did you observe instead of what you expected?

Ele simplesmente não aciona o bot novamente.

### Which version of the API are you using?

v2.1.1

### What is your environment?

Mac

**Comment by RastaSenpai** [comment]
Mesma coisa aqui.

**Comment by dersonbsb2022** [comment]
Fiz este questionamento no discord onte, mesmo problema que detectei e apos o tempo expirar, tem que entrar e excluir a sessao manualmente para que o bot volte a funcionar.

Trecho que consegui capturar do log

_keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/v1/chat-messages',
    _ended: false,
    res: [Circular *2],
    aborted: false,
    timeoutCb: [Function: emitRequestTimeout],
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'dify.dev.tmcplus.com.br',
    protocol: 'https:',
    _redirectable: Writable {
      _events: [Object],
      _writableState: [WritableState],
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 1,
      _redirects: [],
      _requestBodyLength: 289,
      _requestBodyBuffers: [],
      _eventsCount: 3,
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *3],
      _currentUrl: 'https://dify.xxxxxxxcom.br/v1/chat-messages',
      _isRedirect: true,
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false
    },
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      authorization: [Array],
      'user-agent': [Array],
      'content-length': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 16384,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  _eventsCount: 4,
  responseUrl: 'https://dify.xxxxxxcom.br/v1/chat-messages',
  redirects: [],
  [Symbol(shapeMode)]: true,
  [Symbol(kCapture)]: false,
  [Symbol(kHeaders)]: {
    'access-control-allow-origin': '*',
    'content-length': '56',
    'content-type': 'application/json',
    date: 'Sun, 15 Sep 2024 19:40:57 GMT',
    server: 'nginx/1.27.1',
    'set-cookie': [
      'remember_token=; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Path=/'
    ],
    'x-env': 'PRODUCTION',
    'x-version': '0.8.2'
  },
  [Symbol(kHeadersCount)]: 16,
  [Symbol(kTrailers)]: null,
  [Symbol(kTrailersCount)]:

**Comment by AxiusBrasil** [comment]
Mas ai entrar na sessão pra excluir não é a solução mais viável!

**Comment by AxiusBrasil** [comment]
Se tiver alguma alternativa compartilha qui comigo, please 🙏🏼

**Comment by AxiusBrasil** [comment]
> Sem condições, ate pensei em fazer um cron no n8n, pra limpar, mas eu sei que ele vai acabar matando sessao válida, nao vai funcionar direito.

Se conseguir alguma alternativa e puder compartilhar 🙏🏼

**Comment by louisfds** [comment]
Mesmo problema aqui

**Comment by dersonbsb2022** [comment]
Log completo do erro.

[log.txt](https://github.com/user-attachments/files/17042355/log.txt)

**Comment by dersonbsb2022** [comment]
<img width="945" alt="Captura de Tela 2024-09-18 às 07 21 38" src="https://github.com/user-attachments/assets/a24d0f28-8177-49c6-b5be-833e0ba04701">

<img width="951" alt="Captura de Tela 2024-09-18 às 07 24 37" src="https://github.com/user-attachments/assets/a7040b35-42d9-4307-8fb4-224232baaef9">

O que eu descobri é que depois que expira o tempo, a session id recebe o valor do remoteJid, nao sei se isto é um comportamento normal e qual a finalidade, ai ele tenta procurar uma conversar no dify com esta session que tem o remoteJid e da o erro.

**Comment by jesulo** [comment]
Alguém conseguiu resolver? Ou criar uma automação com o n8n? Abraços.

**Comment by AxiusBrasil** [comment]
Criamos uma automação no n8n que ativa e desativa com um marcador dentro do Chatwoot.

**Comment by jesulo** [comment]
> Criamos uma automação no n8n que ativa e desativa com um marcador dentro do Chatwoot.

Olá. Você poderia compartilhar o script m8n?

**Comment by dersonbsb2022** [comment]
Acho que o problema de nao expirar foi resolvido na versao 2.1.1.

Ate o momento mais de 24h de testes e esta ok.

**Comment by jesulo** [comment]
Thanks you @dersonbsb2022

**Comment by AxiusBrasil** [comment]
@dersonbsb2022 vamos lá... cliente entrou em contato, seu dify entrou em ação (bot ativo), seu atendente assumiu a conversa (bot pausado), deixou o tempo expirar e o bot voltou a ficar ativo de novo? Foi assim que testou? Pq aqui comigo não está funcionando.

**Comment by jesulo** [comment]
> @dersonbsb2022 vamos lá... cliente entrou em contato, seu dify entrou em ação (bot ativo), seu atendente assumiu a conversa (bot pausado), deixou o tempo expirar e o bot voltou a ficar ativo de novo? Foi assim que testou? Pq aqui comigo não está funcionando.

Como você ativa conversas para o agente após difunto? Uma ferramenta que ativa um stream n8n? Você poderia mostrar o script amigo? Saudações

**Comment by psifernandocardoso** [comment]
> @AxiusBrasilmeu problema era diferente do seu. o meu bot do dify apos expirar não responder mais, aparecia escrevendo e não chegava nada, eu tinha que entrar no manager e apagar a sessão. Depois disso funcionou. Este problema agora não está apostando mais.

Isso continua acontecendo aqui comigo mesmo atualizando para a 2.1.1

Alguém tem alguma solução? Acontece exatamente a mesma coisa. Após expirar se mandar mensagem fica aparecendo digitando por um tempo e não envia nada. Só após apagar a sessão manualmente.

**Comment by AxiusBrasil** [comment]
Consigo disponibilizar o scrit N8N por R$99, quem tiver interesse manda um email para: suporte@axiusbr.com com assunto ATIVAR IA CHATWOOT.

**Comment by psifernandocardoso** [comment]
Consegui criar uma integração entre chatwoot, n8n e dify onde cada vez que uma conversa altera o status para resolvido a sessão do dify é fechada. Além de também todas as sessões serem fechadas em um determinado horário do dia.

Não sei se posso anexar aqui. Mas quem tiver interesse pode me mandar um email que envio o fluxo do n8n de graça.

**Comment by caswork** [comment]
Opa, bom dia.

Tenho interesse sim, por favor mande no ***@***.******@***.***>

Obrigado!

From: psifernandocardoso ***@***.***>
Date: Monday, 7 October 2024 at 02:16
To: EvolutionAPI/evolution-api ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [EvolutionAPI/evolution-api] Expirar em minutos nas versões da V2 não funciona integrado com o Dify (Issue #877)

Consegui criar uma integração entre chatwoot, n8n e dify onde cada vez que uma conversa altera o status para resolvido a sessão do dify é fechada. Além de também todas as sessões serem fechadas em um determinado horário do dia.

Não sei se posso anexar aqui. Mas quem tiver interesse pode me mandar um email que envio o fluxo do n8n de graça.

**Comment by dpaes** [comment]
Poderiam informar se ainda persistem com o erro em uma versão mais recente como 2.1.2 ou 2.2.0? Caso contrario estarei fechando esta issue

**Comment by dersonbsb2022** [comment]
Comigo pelo menos nao apresenta mais o comportamento.
