### ISSUE TITLE
remotejid sendo enviado ao chatwoot incorretamente quando rejeita ligações

### ISSUE THREAD

**Issue by mbap-dev** [EvolutionAPI/evolution-api#890]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

N/A 

### What did you expect?

Não está funcionando corretamente.

### What did you observe instead of what you expected?

![image](https://github.com/user-attachments/assets/7371332f-3bea-4949-937d-6661da4cd0c8)
o Jid do meu número está indo errado para requisição ao Chatwoot. Aparentemente é somente aos números que já tem o novo digito no whatsapp.

### Screenshots/Videos

N/A 

### Which version of the API are you using?

v2.1.0

### What is your environment?

Windows

### Other environment specifications

N/A 

### If applicable, paste the log output

N/A 

### Additional Notes

N/A

**Comment by dpaes** [comment]
Poderia informar se ainda está tendo o seguinte problema? Já tentou usar outra versão mais recente do evolution, como a 2.1.2?
