### ISSUE TITLE
profilePicture apenas funcionando para grupos

### ISSUE THREAD

**Issue by eduardochaves1** [EvolutionAPI/evolution-api#893]
### Bem-vido!

- [X] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

A função `profilePicture` no baileys.service.ts está apenas retornando a foto de perfil quando se trata de grupos, descobri isso pois no Chatwoot não aparecia a foto de contatos. E quando tentei pela API vi que realmente só retorna foto quando se trata de grupos, ou do próprio contato conectado à instância.

### O que você esperava?

Que retornasse a foto de perfil de contatos assim como de grupos.

### O que vc observou ao invés do que esperava?

Que aparentemente por um erro da baileys ele retorna um bad request quando busca pela foto de perfil de contatos.

### Qual versão da API você está usando?

1.8.1

### Qual é o seu ambiente?

Docker

### Se aplicável, cole a saída do log

Erro ao buscar foto de perfil de contatos:

```log
Error: bad-request
    at assertNodeErrorFree (/evolution-api/node_modules/@whiskeysockets/baileys/lib/WABinary/generic-utils.js:56:15)
    at query (/evolution-api/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:145:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.profilePictureUrl (/evolution-api/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:442:24) {
  data: 400,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}
```

**Comment by rafamar9806** [comment]
conseguiu resolver?

**Comment by eduardochaves1** [comment]
Consegui sim, até esqueci de avisar nessa issue. Expliquei como resolvi nas issues #898 e #734
