### ISSUE TITLE
findContacts endpoint allways returning the hole list of contacts

### ISSUE THREAD

**Issue by gitzome** [EvolutionAPI/evolution-api#896]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Using the chat/findContacts endpoint, with the body with where clause, the endpoint retrieves the hole list of contacts instead of just the one i am searching.

### What did you expect?

Just retrive the found contact

### What did you observe instead of what you expected?

 The hole list of contacts

### Which version of the API are you using?

Version: 2.1.0

### What is your environment?

Windows

**Comment by dpaes** [comment]
u still with the same problem? have tryied 2.1.2 of evolution version to test?

**Comment by yairoman** [comment]
I have the same problem with the version 2.2.0
