### ISSUE TITLE
Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by maisSistemasDev** [EvolutionAPI/evolution-api#897]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Eu vi um report parecido, dizendo que era erro no Baileys. Até ontem estava funcionando normalmente. Hoje, mesmo não tendo feito nenhuma alteração, não estava enviando mensagens em grupos. Fiz um teste via Postman e obtive esse retorno:
{
    "status": 500,
    "error": "Internal Server Error",
    "response": {
        "message": "Cannot read properties of undefined (reading 'id')"
    }
}

Estou usando Portainer. Minha stack esta configurada conforme o exemplo (docker-compose.yaml.example.dockerhub).

### What did you expect?

{
    "key": {
        "remoteJid": "123456.....@g.us",
        "fromMe": true,
        "id": "1234678463486..."
    },
    "message": {
        "extendedTextMessage": {
            "text": "Plain text message, sent with the *Evolution-API* 🚀.\n\nHere you can send texts in *bold*, _italic_, ~strikethrough~ and ```monospaced```.\n\nYou can also use any available emoticon on WhatsApp, like these examples below:\n\n😉🤣🤩🤝👏👍🙏"
        }
    },
    "messageTimestamp": "1726843419",
    "status": "PENDING"

### What did you observe instead of what you expected?

{
    "status": 500,
    "error": "Internal Server Error",
    "response": {
        "message": "Cannot read properties of undefined (reading 'id')"
    }
}

### Which version of the API are you using?

1.8.2

### What is your environment?

Docker

**Comment by 38ca** [comment]
Mesmo erro aqui para enviar mensagens em Grupos. A versão 1.8.1 esta dando pau aqui pra mim, não da pra fazer downgrade.

**Comment by joaom00** [comment]
Mesma coisa aqui na versão 1.7.0

**Comment by rafamenezesvr** [comment]
estou a pensar q o erro está em alguma mudança no whatsapp, aqui parou no dia 19 na parte da noite

**Comment by maisSistemasDev** [comment]
Consegui resolver! 

Eu refiz build da imagem sem cache e funcionou. Fui no Github do Baileys e verifiquei que teve atualização. Como o package.json do projeto trabalha com a última versão do Baileys, bastou refazer a imagem (uso Docker + Portainer) para funcionar.

Verifiquem também se a opção **Ignorar Grupos** não esta marcada.

![image](https://github.com/user-attachments/assets/79f1809e-25af-487f-85e5-92538591a56a)

**Comment by Thiagle** [comment]
Galera, pra mim foi só desmarcar essa opção que parou de dar esse erro:

![image](https://github.com/user-attachments/assets/12cfb61c-e569-45bf-ae51-012f6e30317f)
