### ISSUE TITLE
Does not send messages to certain numbers such as: 5562985247925

### ISSUE THREAD

**Issue by mariofragamiranda** [EvolutionAPI/evolution-api#907]
### Bem-vido!

- [X] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

<img width="448" alt="image" src="https://github.com/user-attachments/assets/ed21382f-2e77-4aff-9584-69dd254e2bdd">

### O que você esperava?

Send a mensage/

### O que vc observou ao invés do que esperava?

Does not send messages to certain numbers such as: 5562985247925

### Capturas de Tela/Vídeos

<img width="448" alt="image" src="https://github.com/user-attachments/assets/cd869d37-ad16-45f0-9d75-520f0cc6dfa1">

### Qual versão da API você está usando?

1.8.0

### Qual é o seu ambiente?

Docker

### Outras expecificações do ambiente

-

### Se aplicável, cole a saída do log

-----------

### Notas Adicionais

---------

**Comment by dpaes** [comment]
quando é no session, vc precisa deletar a instancia e criar novamente com o mesmo nome. é o que tenho feito pra resolver

**Comment by dpaes** [comment]
Estarei fechando essa issue pelo fato da versão mencionada não estar recebendo novas correções. Prosseguiremos dando atenção as versões da v2 mais recentes e corrigindo quaisquer erros.
