### ISSUE TITLE
duplicação de conversas e msgs ao sincronizar (integração chatwoot + evo 2.1)

### ISSUE THREAD

**Issue by dpaes** [EvolutionAPI/evolution-api#908]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Acabei de subir um container pra testar nova release da 2.1 e está retornando imagens ao sincronizar (que era o problema antes na 2.0 que não vinha imagens, apenas uma tag <ImageMessage>), porém não está colocando as msgs de forma unica (acaba duplicando) e também está criando conversas duplicadas em alguns momentos, como se não estivesse relacionando as msgs sendo da mesma conversa, tendo uma interação inicial porém segunda mensagem está em outra conversa com a mesma pessoa.

### What did you expect?

Esperava o pleno funcionamento

### What did you observe instead of what you expected?

Percebi que a sincronização está ocorrendo bem por trás dos panos porém quando tem integração com chatwoot não está se comportando como deveria.

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/0c57f7b0-3c04-4846-b2ed-56c453edd112)
exemplo de duplicação de conversas

![image](https://github.com/user-attachments/assets/80e97d00-91c5-413a-b26c-45b1e7c03baf)
duplicação de msg dentro da conversa

![image](https://github.com/user-attachments/assets/6e2678b6-1244-4b58-8c9f-3ddf6d2f233b)
![image](https://github.com/user-attachments/assets/baea1bca-5f77-437b-acb2-7b79ca73fc64)
ao sincronizar não apresentou algumas mensagens minhas na conversa

### Which version of the API are you using?

v2.1.1, ultima release atualizada no docker hub 22/09/24

### What is your environment?

Windows

### Other environment specifications

vps 4vCPU 16GB, docker swarm + portainer, traefik 2.11 proxy reverso, evo 2.1.1, chatwoot 3.12, redis 7, postgres 16, minIO latest

### If applicable, paste the log output

[log_evo2.txt](https://github.com/user-attachments/files/17097690/log_evo2.txt)

### Additional Notes

esse log foi o momento que subi o evo e sincronizou 7 dias apenas no chatwoot. Se vc perceber aonde duplicou estava com uma notação após o numero e antes do @s.whatsapp.com, um tal de :88 e depois :87 parecendo que por isso ele criou outra conversa pra uma mensagem que deveria ter permanecido na mesma conversa. Então acho que tem algum problema ai e um trecho que fala sobre > err={"type":"MessageCounterError","message":"Key used already or never filled","stack":"MessageCounterError: Key used already or never filled\n    at SessionCipher.doDecryptWhisperMessage (/evolution/node_modules/libsignal/src/session_cipher.js:236:19)\n    at 556281009000.0 [as awaitable] (/evolution/node_modules/libsignal/src/session_cipher.js:207:42)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async _asyncQueueExecutor (/evolution/node_modules/libsignal/src/queue_job.js:20:29)","name":"MessageCounterError"} msg=failed to decrypt message, 
se precisar de mais informações posso passar

**Comment by dpaes** [comment]
up

**Comment by FelipePPJ** [comment]
Olá, chegou a alguma conclusão?

**Comment by souheliojunior** [comment]
por aqui ainda acontece isso com chatwoot alguém encontrou solução ?

**Comment by dlc-letelier** [comment]
Conferiu se o número do contato está sem o 9?

**Comment by jfholanda** [comment]
@dpaes Encontrou solução para o problema? Poderia compartilhar?
