### ISSUE TITLE
campo "message" está vindo vazio no webhook

### ISSUE THREAD

**Issue by emersonbock** [EvolutionAPI/evolution-api#91]
Estou tendo problemas para receber mensagens via webhook da EvolutionApi

Após criar uma instancia ela funciona perfeitamente durante 1hr ou 2hr no máximo, após um tempo o webhook passa enviar o campo "message" vazio no evento"messages.upsert"

{'event': 'messages.upsert', 'instance': 'chatbotteste', 'data': {'key': {'remoteJid': '556699995635@s.whatsapp.net', 'fromMe': False, 'id': '3EB0946F0C4651173802D6'}, 'pushName': 'Emerson', 'message': {}, 'messageTimestamp': 1693425465, 'owner': 'chatbotteste', 'source': 'android'}, 'destination': 'https://hook-teste.-----', 'server_url': 'localhost', 'apikey': '751B23B6-----'}

Após começar a enfrentar esse problema, fiz vários testes instalando sempre api usando Docker nas versões 1.4.3, 1.4.8, e 1.5.0 e em todos os casos aconteceu a mesma coisa. Também fiz teste nas configurações mudando algumas coisas como por exemplo desabilitar a limpeza do store, mas não resolveu. Também rodei algumas vezes a api com todas as configurações padrões do github, alterando somente o webhook e a porta da api. E não consegui resolver esse problema. Também monitorei os logs em tempo real e não encontrei nada fora do normal. Nenhum erro consta nos logs que vejo pelo terminal. Também testei versão bussiness e normal do app do WhatsApp e acontece nas duas.

Após isso acontecer com um número, passa a acontecer com todos os números que enviarem mensagem, e todos as requisições começam a chegar ao webhook com campo 'message' vazio.

Caso tiverem sugestões para que eu possa testar uma possivel solução... estou a disposição.

**Comment by emersonbock** [comment]
Em teste da versão Homolog via Docker: rodando desde ontem (30/08/2023) as 21h obteve um resultado melhor, rodando por várias horas sem nenhum problema, mas agora a pouco o problema voltou a aparecer, dessa vez com apenas 2 numeros, teste que consegui fazer recebi mensagens nessa instância de cerca de 20 numeros diferentes. Apenas 2 vem com o campo message vazio o restante troca mensagens sem problemas.

**Comment by HermesMacedo** [comment]
mesmo erro aqui tbm. vou enviar o json . e o boy da mensagem;

event:messages.upsert
instance:NomeMeu
data
key
remoteJid:5519XXXXXXXXXX@s.whatsapp.net
fromMe:false
id:3XXXXXXXXXXXXXXXXX99
pushName:Carol Santiago 🌊⚓️🌸
message:[empty object]
messageTimestamp:1693734539
owner:WCCCCCCCCSSSSSSl
source:ios
destination:https://XXXXX.XXXXXXXXXXX.com/webhook/msgcarol
date_time:2023-09-03T06:48:59.965Z
sender:551XXXXXXXXXXXX2@s.whatsapp.net
server_url:https://XXXXXX.CCCCCCCCCk.com
apikey:Whatsdracarol473890

[
{
"headers":
{
"host":
"meusitesubdominio.com",
"user-agent":
"axios/1.5.0",
"content-length":
"519",
"accept":
"application/json, text/plain, */*",
"accept-encoding":
"gzip, compress, deflate, br",
"content-type":
"application/json",
"x-forwarded-for":
"172.18.0.1",
"x-forwarded-host":
"meusitesubdominio.com",
"x-forwarded-port":
"443",
"x-forwarded-proto":
"https",
"x-forwarded-server":
"4e846efc1a4d",
"x-real-ip":
"172.18.0.1"
},
"params":
{
},
"query":
{
},
"body":
{
"event":
"messages.upsert",
"instance":
"Whatsdracarol",
"data":
{
"key":
{
"remoteJid":
"5519XXXXXXXXXXX@s.whatsapp.net",
"fromMe":
false,
"id":
"3A22335573B7FC204899"
},
"pushName":
"Carol Santiago 🌊⚓️🌸",
"message":
{
},
"messageTimestamp":
1693734539,
"owner":
"NomedaInstancia",
"source":
"ios"
},
"destination":
"meusitesubdominio.com/webhook/msgcxl",
"date_time":
"2023-09-03T06:48:59.965Z",
"sender":
"5519xxxxxxxxx@s.whatsapp.net",
"server_url":
"meusitesubdominio.com",
"apikey":
"WhatsCX473890"
}
}
]

**Comment by sjollenbeck** [comment]
> mesmo erro aqui tbm. vou enviar o json . e o boy da mensagem; EVO 1.5.1 homolog CW 3.0 sem erros no log. o json da mensagem chegou assim. Estou com 5 mensagens desse jeito
> 
> event:messages.upsert instance:NomeMeu data key remoteJid:[5519XXXXXXXXXX@s.whatsapp.net](mailto:5519XXXXXXXXXX@s.whatsapp.net) fromMe:false id:3XXXXXXXXXXXXXXXXX99 pushName:Carol Santiago 🌊⚓️🌸 message:[empty object] messageTimestamp:1693734539 owner:WCCCCCCCCSSSSSSl source:ios destination:https://XXXXX.XXXXXXXXXXX.com/webhook/msgcarol date_time:2023-09-03T06:48:59.965Z sender:[551XXXXXXXXXXXX2@s.whatsapp.net](mailto:551XXXXXXXXXXXX2@s.whatsapp.net) server_url:https://XXXXXX.CCCCCCCCCk.com apikey:Whatsdracarol473890
> 
> [ { "headers": { "host": "meusitesubdominio.com", "user-agent": "axios/1.5.0", "content-length": "519", "accept": "application/json, text/plain, _/_", "accept-encoding": "gzip, compress, deflate, br", "content-type": "application/json", "x-forwarded-for": "172.18.0.1", "x-forwarded-host": "meusitesubdominio.com", "x-forwarded-port": "443", "x-forwarded-proto": "https", "x-forwarded-server": "4e846efc1a4d", "x-real-ip": "172.18.0.1" }, "params": { }, "query": { }, "body": { "event": "messages.upsert", "instance": "Whatsdracarol", "data": { "key": { "remoteJid": "[5519XXXXXXXXXXX@s.whatsapp.net](mailto:5519XXXXXXXXXXX@s.whatsapp.net)", "fromMe": false, "id": "3A22335573B7FC204899" }, "pushName": "Carol Santiago 🌊⚓️🌸", "message": { }, "messageTimestamp": 1693734539, "owner": "NomedaInstancia", "source": "ios" }, "destination": "meusitesubdominio.com/webhook/msgcxl", "date_time": "2023-09-03T06:48:59.965Z", "sender": "[5519xxxxxxxxx@s.whatsapp.net](mailto:5519xxxxxxxxx@s.whatsapp.net)", "server_url": "meusitesubdominio.com", "apikey": "WhatsCX473890" } } ]

vc pode compartilhar sua config config comigo ? recebo e evento no WebHook, mas não recebo o body.

**Comment by MattCarneiro** [comment]
Na verdade o que está acontecendo é o seguinte. Quando você ativa qualquer webhook, o status está sendo enviado dezenas de vezes. Ou seja, envia o webhook de mensagem 5 vezes, uma delas vem o campo vazio e outras não. etc

**Comment by HermesMacedo** [comment]
> > mesmo erro aqui tbm. vou enviar o json . e o boy da mensagem; EVO 1.5.1 homolog CW 3.0 sem erros no log. o json da mensagem chegou assim. Estou com 5 mensagens desse jeito
> > event:messages.upsert instance:NomeMeu data key remoteJid:[5519XXXXXXXXXX@s.whatsapp.net](mailto:5519XXXXXXXXXX@s.whatsapp.net) fromMe:false id:3XXXXXXXXXXXXXXXXX99 pushName:Carol Santiago 🌊⚓️🌸 message:[empty object] messageTimestamp:1693734539 owner:WCCCCCCCCSSSSSSl source:ios destination:https://XXXXX.XXXXXXXXXXX.com/webhook/msgcarol date_time:2023-09-03T06:48:59.965Z sender:[551XXXXXXXXXXXX2@s.whatsapp.net](mailto:551XXXXXXXXXXXX2@s.whatsapp.net) server_url:https://XXXXXX.CCCCCCCCCk.com apikey:Whatsdracarol473890
> > [ { "headers": { "host": "meusitesubdominio.com", "user-agent": "axios/1.5.0", "content-length": "519", "accept": "application/json, text/plain, _/_", "accept-encoding": "gzip, compress, deflate, br", "content-type": "application/json", "x-forwarded-for": "172.18.0.1", "x-forwarded-host": "meusitesubdominio.com", "x-forwarded-port": "443", "x-forwarded-proto": "https", "x-forwarded-server": "4e846efc1a4d", "x-real-ip": "172.18.0.1" }, "params": { }, "query": { }, "body": { "event": "messages.upsert", "instance": "Whatsdracarol", "data": { "key": { "remoteJid": "[5519XXXXXXXXXXX@s.whatsapp.net](mailto:5519XXXXXXXXXXX@s.whatsapp.net)", "fromMe": false, "id": "3A22335573B7FC204899" }, "pushName": "Carol Santiago 🌊⚓️🌸", "message": { }, "messageTimestamp": 1693734539, "owner": "NomedaInstancia", "source": "ios" }, "destination": "meusitesubdominio.com/webhook/msgcxl", "date_time": "2023-09-03T06:48:59.965Z", "sender": "[5519xxxxxxxxx@s.whatsapp.net](mailto:5519xxxxxxxxx@s.whatsapp.net)", "server_url": "meusitesubdominio.com", "apikey": "WhatsCX473890" } } ]
> 
> vc pode compartilhar sua config config comigo ? recebo e evento no WebHook, mas não recebo o body.

quais CONFIG vc precisa?

**Comment by DavidsonGomes** [comment]
corrigido na versao 1.5.1
