### ISSUE TITLE
Grupos e mensagens não aparecem na Evolution 2.1.1

### ISSUE THREAD

**Issue by mecatronicabruno** [EvolutionAPI/evolution-api#910]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Criei um grupo e adicionei o número sincronizado com a Evolution 2.0.

Ao adicionar o grupo não aparece mesmo com mensagens sendo enviadas no grupo.

Também tentei mencionar o whatsapp vinculado à caixa de entrada nas mensagens enviadas e também nada aconteceu.

### What did you expect?

Enviar e receber mensagens de grupos

### What did you observe instead of what you expected?

Verificando os logs do meu container recebo este erro:

[Evolution API]    v2.1.1  184   -  Mon Sep 23 2024 10:54:56     ERROR   [ChatwootService]  [object]   

ApiError: Internal Server Error

    at catchErrorCodes (/evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:226:15)

    at /evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:257:17

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {

  url: 'https://app.brasilchat.net/api/v1/accounts/2/conversations',

  status: 500,

  statusText: 'Internal Server Error',

  body: { status: 500, error: 'Internal Server Error' },


  request: {

    method: 'POST',

    url: '/api/v1/accounts/{account_id}/conversations',

    path: { account_id: '2' },

    body: { contact_id: '249', inbox_id: '21' },

    errors: { '403': 'Access denied' }

  }

} 

### Which version of the API are you using?

Versão 2.1.1

### What is your environment?

Linux

**Comment by dpaes** [comment]
ta aparecendo acesso negado, vc deve estar colocando ou o id da conta errado na integração com chatwoot ou vc ta passando o token errado

**Comment by mecatronicabruno** [comment]
Opa! Pessoal consegui resolver agora há pouco apagando a conta inteira da empresa e recriando. Só resolveu assim.

Não sei o porque do erro.

Sobre a questão da V1, realmente o endpoint está para a V1 mas so tenho a v2.0 instalada. Seria impossível a aplicação apontar para outra API pois não tenho outra versão instalada.
