### ISSUE TITLE
Erro na API quando usando com o Chatwoot

### ISSUE THREAD

**Issue by braiaagency** [EvolutionAPI/evolution-api#911]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Quando tentando instalar o Evolution-API com o Chatwoot, ao tentar acessar o localhost:8080, ele me da o erro de:  "ERR_CONNECTION_REFUSED"

Estou usando o grok e ele me diz que o agente esta funcionando, porém ele me diz: "ERR_NGROK_8012
Traffic was successfully tunneled to the ngrok agent, but the agent failed to establish a connection to the upstream web service at http://localhost:8080/. The error encountered was:

dial tcp [::1]:8080: connectex: Nenhuma conexÃ£o pÃ´de ser feita porque a mÃ¡quina de destino as recusou ativamente."

este é o erro que eu recebo quando eu uso npm install no Git CMD:

[Evolution API]    v1.8.2  9468   -  Mon Sep 23 2024 11:23:26     ERROR   [ProviderFiles]  [object]
[
  'Failed to connect to the file server',
  'connect ECONNREFUSED 127.0.0.1:5656',
  'Error: connect ECONNREFUSED 127.0.0.1:5656\n' +
    '    at Function.AxiosError.from (C:\\Users\\BlackGames-StageM\\Desktop\\crm_local\\evolution-api\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n' +
    '    at RedirectableRequest.handleRequestError (C:\\Users\\BlackGames-StageM\\Desktop\\crm_local\\evolution-api\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n' +
    '    at RedirectableRequest.emit (node:events:519:28)\n' +
    '    at RedirectableRequest.emit (node:domain:488:12)\n' +
    '    at ClientRequest.eventHandlers.<computed> (C:\\Users\\BlackGames-StageM\\Desktop\\crm_local\\evolution-api\\node_modules\\follow-redirects\\index.js:49:24)\n' +
    '    at ClientRequest.emit (node:events:519:28)\n' +
    '    at ClientRequest.emit (node:domain:488:12)\n' +
    '    at emitErrorEvent (node:_http_client:108:11)\n' +
    '    at Socket.socketErrorListener (node:_http_client:511:5)\n' +
    '    at Socket.emit (node:events:519:28)\n' +
    '    at Axios.request (C:\\Users\\BlackGames-StageM\\Desktop\\crm_local\\evolution-api\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)'
    
    Aqui está o tutorial que eu usei como referencia: https://www.youtube.com/watch?v=uRWJSTBKsuY&ab_channel=ComunidadeZDG

### What did you expect?

Que funcionasse

### What did you observe instead of what you expected?

um erro na Evolution API

### Which version of the API are you using?

A mais recente

### What is your environment?

Windows

### Other environment specifications

Docker

### If applicable, paste the log output

no Docker o log é simplesmente: 2024-09-23 11:17:59 Switch to inspect mode.

**Comment by dpaes** [comment]
possívelmente já existe algo nessa porta sendo usada

**Comment by braiaagency** [comment]
> possívelmente já existe algo nessa porta sendo usada

Como eu posso alterar a porta?

**Comment by hdjonathan** [comment]
no meu ocorreu um erro parecido porém foi pq o meu servidor estava configurado com ipv6. Parece ser o seu caso tb por causa disso: tcp [::1]:8080

**Comment by braiaagency** [comment]
> no meu ocorreu um erro parecido porém foi pq o meu servidor estava configurado com ipv6. Parece ser o seu caso tb por causa disso: tcp [::1]:8080

O que vc fez para mudar?

**Comment by hdjonathan** [comment]
> > no meu ocorreu um erro parecido porém foi pq o meu servidor estava configurado com ipv6. Parece ser o seu caso tb por causa disso: tcp [::1]:8080
> 
> O que vc fez para mudar?

no meu caso do problema com o ipv6 eu usei dns e criei um proxy reverso para a porta que eu queria(eu estava no linux), porém penso que uma solução tb seria desabilitar o ipv6 no windows (https://tecnoblog.net/responde/como-desativar-o-ipv6-windows-macos-e-no-roteador/). 

Tente tb verificar se a porta em questão está em uso, como o amigo acima sugeriu:

netstat -ano | findstr :8080

**Comment by braiaagency** [comment]
> > > no meu ocorreu um erro parecido porém foi pq o meu servidor estava configurado com ipv6. Parece ser o seu caso tb por causa disso: tcp [::1]:8080
> > 
> > 
> > O que vc fez para mudar?
> 
> no meu caso do problema com o ipv6 eu usei dns e criei um proxy reverso para a porta que eu queria(eu estava no linux), porém penso que uma solução tb seria desabilitar o ipv6 no windows (https://tecnoblog.net/responde/como-desativar-o-ipv6-windows-macos-e-no-roteador/).
> 
> Tente tb verificar se a porta em questão está em uso, como o amigo acima sugeriu:
> 
> netstat -ano | findstr :8080

pelo o que eu entendi se nenhuma linha voltar, significa que a porta n está em uso, ent o meu 8080 não está sendo usado atualmente. 

Eu tbm desativei o ipv6 mas nada mudou

**Comment by hdjonathan** [comment]
desculpe, na vdd a porta que vc precisa consultar é a porta 5656

**Comment by braiaagency** [comment]
> desculpe, na vdd a porta que vc precisa consultar é a porta 5656

mesma coisa

**Comment by dpaes** [comment]
Pelo fato da versão mencionada ser a 1.8.2 e ela não estar recebendo novas correções, estarei fechando essa issue. Estaremos trabalhando na v2.

**Comment by runawaydevil** [comment]
> ### Welcome!
> * [x]  Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.
> 
> ### What did you do?
> Quando tentando instalar o Evolution-API com o Chatwoot, ao tentar acessar o localhost:8080, ele me da o erro de: "ERR_CONNECTION_REFUSED"
> 
> Estou usando o grok e ele me diz que o agente esta funcionando, porém ele me diz: "ERR_NGROK_8012 Traffic was successfully tunneled to the ngrok agent, but the agent failed to establish a connection to the upstream web service at http://localhost:8080/. The error encountered was:
> 
> dial tcp [::1]:8080: connectex: Nenhuma conexÃ£o pÃ´de ser feita porque a mÃ¡quina de destino as recusou ativamente."
> 
> este é o erro que eu recebo quando eu uso npm install no Git CMD:
> 
> [Evolution API] v1.8.2 9468 - Mon Sep 23 2024 11:23:26 ERROR [ProviderFiles] [object] [ 'Failed to connect to the file server', 'connect ECONNREFUSED 127.0.0.1:5656', 'Error: connect ECONNREFUSED 127.0.0.1:5656\n' + ' at Function.AxiosError.from (C:\Users\BlackGames-StageM\Desktop\crm_local\evolution-api\node_modules\axios\lib\core\AxiosError.js:92:14)\n' + ' at RedirectableRequest.handleRequestError (C:\Users\BlackGames-StageM\Desktop\crm_local\evolution-api\node_modules\axios\lib\adapters\http.js:620:25)\n' + ' at RedirectableRequest.emit (node:events:519:28)\n' + ' at RedirectableRequest.emit (node:domain:488:12)\n' + ' at ClientRequest.eventHandlers. (C:\Users\BlackGames-StageM\Desktop\crm_local\evolution-api\node_modules\follow-redirects\index.js:49:24)\n' + ' at ClientRequest.emit (node:events:519:28)\n' + ' at ClientRequest.emit (node:domain:488:12)\n' + ' at emitErrorEvent (node:_http_client:108:11)\n' + ' at Socket.socketErrorListener (node:_http_client:511:5)\n' + ' at Socket.emit (node:events:519:28)\n' + ' at Axios.request (C:\Users\BlackGames-StageM\Desktop\crm_local\evolution-api\node_modules\axios\lib\core\Axios.js:45:41)\n' + ' at processTicksAndRejections (node:internal/process/task_queues:95:5)'
> 
> ```
> Aqui está o tutorial que eu usei como referencia: https://www.youtube.com/watch?v=uRWJSTBKsuY&ab_channel=ComunidadeZDG
> ```
> 
> ### What did you expect?
> Que funcionasse
> 
> ### What did you observe instead of what you expected?
> um erro na Evolution API
> 
> ### Screenshots/Videos
> _No response_
> 
> ### Which version of the API are you using?
> A mais recente
> 
> ### What is your environment?
> Windows
> 
> ### Other environment specifications
> Docker
> 
> ### If applicable, paste the log output
> no Docker o log é simplesmente: 2024-09-23 11:17:59 Switch to inspect mode.
> 
> ### Additional Notes
> _No response_

Salve, conseguiu resolver isso? Estou com o mesmo problema aqui.

Tentei mudar o .env
Tentei mudar o docker-compose
Nada adiantou.
Então tentei construir minha imagem com o Dockerfile
E não adiantou, parece estar "hard coded"... minha última opção agora é fuçar nos .js
Mas não estou avançando, se tiver conseguido, me conte hehe
