### ISSUE TITLE
Chatwoot 3.9 Envia mensagens mas não recebe. Evolution 2.1.1

### ISSUE THREAD

**Issue by viniciusbtu** [EvolutionAPI/evolution-api#912]
### Bem-vido!

- [X] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

Consigo fazer o envio das mensagens através do Chatwoot mas nenhuma mensagem é recebida.

### O que você esperava?

A troca de mensagens

### O que vc observou ao invés do que esperava?

A mensagem não é recebida

### Capturas de Tela/Vídeos

![001](https://github.com/user-attachments/assets/70948623-72d7-44d1-8bd4-4be1ec601525)
![002](https://github.com/user-attachments/assets/87517744-9509-4c71-a1cd-d75ce3f7b053)

### Qual versão da API você está usando?

2.1.1

### Qual é o seu ambiente?

Linux

### Se aplicável, cole a saída do log

[Evolution API]    v2.1.1  171   -  Mon Sep 23 2024 18:40:53     VERBOSE   [CacheEngine]  [string]  RedisCache initialized for he 
[Evolution API]    v2.1.1  171   -  Mon Sep 23 2024 18:40:53     VERBOSE   [CacheService]  [string]  cacheservice created using cache engine: Vt 
[Evolution API]  [Atendimento]  v2.1.1  171   -  Mon Sep 23 2024 18:40:54     VERBOSE   [ChannelStartupService]  [string]  Sending message to (XXXXXXXXXX)@s.whatsapp.net 
[Evolution API]  [Atendimento]  v2.1.1  171   -  Mon Sep 23 2024 18:40:54     VERBOSE   [ChannelStartupService]  [string]  Typing for 1200ms to  (XXXXXXXXXX)@s.whatsapp.net 
[Evolution API]  [Atendimento]  v2.1.1  171   -  Mon Sep 23 2024 18:40:55     LOG   [ChannelStartupService]  [object]   
{
  key: MessageKey {
    remoteJid: ' (XXXXXXXXXX)@s.whatsapp.net',
    fromMe: true,
    id: '3EB023FB24952694E428DE92AA2EA6011E0CFCFC'
  },
  pushName: '',
  message: { conversation: 'olá\n' },
  contextInfo: null,
  messageType: 'conversation',
  messageTimestamp: 1727127655,
  instanceId: '90296833-7cc3-4aea-b4cb-eff2e39b36a9',
  source: 'unknown'
} 
[Evolution API]  [Atendimento]  v2.1.1  171   -  Mon Sep 23 2024 18:41:42     LOG   [ChannelStartupService]  [object]   
{
  key: {
    remoteJid: ' (XXXXXXXXXX)@s.whatsapp.net',
    fromMe: false,
    id: '3EB0A15AA7A327A0ED2BAD',
    participant: undefined
  },
  pushName: 'Vinicius',

  message: {
    conversation: 'Essa mensagem nao é recebida no chatwoot',
    messageContextInfo: MessageContextInfo {
      deviceListMetadata: [DeviceListMetadata],
      deviceListMetadataVersion: 2,
      messageSecret: [Uint8Array]
    }
  },
  contextInfo: undefined,
  messageType: 'conversation',
  messageTimestamp: 1727127702,
  instanceId: '90296833-7cc3-4aea-b4cb-eff2e39b36a9',
  source: 'web'
}

**Comment by frycrosoft** [comment]
I have the similar error and have more logs:

[Evolution API]    v2.1.1  198   -  Tue Sep 24 2024 08:25:45     ERROR   [ChatwootImport]  [string]  Error on getChatwootUser: Error: getaddrinfo ENOTFOUND host 
[Evolution API]    v2.1.1  198   -  Tue Sep 24 2024 08:25:45     ERROR   [ChatwootImport]  [string]  Error on import history messages: Error: User not found to import messages. 
[Evolution API]    v2.1.1  198   -  Tue Sep 24 2024 08:25:45     ERROR   [ChatwootImport]  [string]  Error on get recent conversations: Error: getaddrinfo ENOTFOUND host 
[Evolution API]    v2.1.1  198   -  Tue Sep 24 2024 08:25:45     ERROR   [ChatwootService]  [string]  Error on update avatar in recent conversations: TypeError: Cannot read properties of undefined (reading 'map') 
[Evolution API]    v2.1.1  198   -  Tue Sep 24 2024 08:25:46     ERROR   [ChatwootImport]  [string]  Error on getChatwootUser: Error: getaddrinfo ENOTFOUND host 
[Evolution API]    v2.1.1  198   -  Tue Sep 24 2024 08:25:46     ERROR   [ChatwootImport]  [string]  Error on import history messages: Error: User not found to import messages. 
[Evolution API]    v2.1.1  198   -  Tue Sep 24 2024 08:25:46     VERBOSE   [CacheService]  [string]  cacheservice disabled 
[Evolution API]    v2.1.1  198   -  Tue Sep 24 2024 08:25:46     ERROR   [ChatwootImport]  [string]  Error on get recent conversations: Error: getaddrinfo ENOTFOUND host 
[Evolution API]    v2.1.1  198   -  Tue Sep 24 2024 08:25:46     ERROR   [ChatwootService]  [string]  Error on update avatar in recent conversations: TypeError: Cannot read properties of undefined (reading 'map')

**Comment by gabrielcmachado** [comment]
O problema está no Host, você migrou de que versão para a 2.1?

**Comment by frycrosoft** [comment]
We have the new installation 2.1 
What's worth looking at? Maybe we missed something.

**Comment by dpaes** [comment]
ja tentou atualizar o chatwoot?

**Comment by viniciusbtu** [comment]
> O problema está no Host, você migrou de que versão para a 2.1?

Eu nao migrei, fiz uma instalação do 0, tudo novinho.

**Comment by viniciusbtu** [comment]
> ja tentou atualizar o chatwoot? @viniciusbtu

Para qual versão ? Não fiz isso ainda.

**Comment by dpaes** [comment]
pra mais recente

**Comment by gabrielgranado** [comment]
eu estou com o mesmo erro @viniciusbtu . Os logs estão do mesmo jeito. Eu apaguei os volumes e os bancos de dados. Instalei evo e chatwoot do zero novamente. O erro persiste. 

> O problema está no Host, você migrou de que versão para a 2.1?

O que você quer dizer como problema está no host? que tipo de problema?

**Comment by idealprint** [comment]
Você colocou a url do chatwoot, token, id da empresa certinho?

**Comment by brunoguedes** [comment]
Tendo o mesmo problema com chatwoot:v3.13.0 + evolution-api:v2.1.2

**Comment by hugorn** [comment]
Mesmo problema
chatwoot:v3.13.0 + evolution-api:v2.1.2 e 2.1.1
Tudo criado do zero.

**Comment by brunoguedes** [comment]
Depois de desinstalar e reinstalar tudo umas 10 vezes descobri que era so habilitar o primeiro switch nas configuracoes do chatwoot na instancia no evolution manager. Como tava SQS, achei que era pra usar SQS.

Enabled
Enable or disable the sqs

**Comment by hugorn** [comment]
> Depois de desinstalar e reinstalar tudo umas 10 vezes descobri que era so habilitar o primeiro switch nas configuracoes do chatwoot na instancia no evolution manager. Como tava SQS, achei que era pra usar SQS.
> 
> Enabled Enable or disable the sqs

Aqui funcionou corretamente também após marcar a opção, não tinha marcado pela mesma causa que você, a descrição está confusa.

**Comment by viniciusbtu** [comment]
> Depois de desinstalar e reinstalar tudo umas 10 vezes descobri que era so habilitar o primeiro switch nas configuracoes do chatwoot na instancia no evolution manager. Como tava SQS, achei que era pra usar SQS.
> 
> Enabled Enable or disable the sqs

Gênio !!!!!!!!!!!!! Aqui pra mim voltou a funcionar depois que eu habilitei essa opção ! MUITO OBRIGADO

**Comment by idealprint** [comment]
onde tem essa opção SQS? Tem como enviar um print?

**Comment by TrolljanO** [comment]
Pessoal, to com o mesmo problema!

Mas identifiquei algumas variantes que podem ser importantes pra identificar o problema.


Ao tentar criar a "inbox" pelo manager do Evo, se eu marcar a opçãr auto-create, retorna 401 - Unauthorized.

Se eu deixar desmarcado, Retorna 201 - Created.

Mas mesmo criando manualmente a 'inbox' pelo Chatwoot, eu só consigo enviar mensagens, nao recebo nada.


Já mexi no Nginx colocando o atributo do underscore_headers, a opção Chatwoot Enable or disable the sqs, também está ativada.
![image](https://github.com/user-attachments/assets/4f4d2029-24b4-41cc-bd38-ecc173cb7027)
![image](https://github.com/user-attachments/assets/19fba34b-0d68-4511-801f-026dacd69760)

**Comment by gustavornunes** [comment]
> Depois de desinstalar e reinstalar tudo umas 10 vezes descobri que era so habilitar o primeiro switch nas configuracoes do chatwoot na instancia no evolution manager. Como tava SQS, achei que era pra usar SQS.
> 
> Enabled Enable or disable the sqs

Boa, só que no meu caso estava habilitado. Desabilitei, salvei. Habilitei novamente, salvei. 
Desta forma funcionou

**Comment by dpaes** [comment]
atualizem para 2.1.2 caso esteja em uma versão inferior. Para mais alguém persiste esse erro?

**Comment by JulioMarkiss** [comment]
> Depois de desinstalar e reinstalar tudo umas 10 vezes descobri que era so habilitar o primeiro switch nas configuracoes do chatwoot na instancia no evolution manager. Como tava SQS, achei que era pra usar SQS.
> 
> Enabled Enable or disable the sqs

Isso aqui funcionou em parte. Os grupos, ainda não estão recebendo mensagens. Envio as mensagens normalmente, mas não recebo as mensagens dos grupos de volta. Já verifiquei a configuração de ignorar grupos, e ela está desmarcada. 

![image](https://github.com/user-attachments/assets/7ae601d0-5568-42ae-8a36-61a5be2d13e8)
![image](https://github.com/user-attachments/assets/1f376d7a-39e4-4c0a-9f53-a6fc55115d84)

**Comment by guhweb** [comment]
> Depois de desinstalar e reinstalar tudo umas 10 vezes descobri que era so habilitar o primeiro switch nas configuracoes do chatwoot na instancia no evolution manager. Como tava SQS, achei que era pra usar SQS.
> 
> Enabled Enable or disable the sqs

DISSSSGRAAAAÇAAAAAAAAAAAAAAAA!

Um dia inteiro batendo cabeça... Eu não to usando SQS, então obviamente eu deixei desabilitado!

To me sentindo um retardado hahahahahahaahah

**Comment by joaopdalferth** [comment]
Pessoal não estou achando esse switch que foi mencionado nas configurações do chatwoot, alguém pode me enviar uma print de onde fica isso?

**Comment by faganello** [comment]
Mesmo problema por aqui, mas no meu caso e em uma segunda instancia. A primeira eu fiz com meu número e com a primeira conta criada no Chatwoot auto hospedado e funcionou tranquilamente. Fui criar outra conta no Chatwoot e consequentemente, outra instancia. Ela conecta, cria a caixa de entrada e **está enviando mensagens mas não está recebendo.** 

Evolution: 2.2.3
Chatwoot: 4.0.1

O primeiro switch, como mencionado, está ativado igual na minha instancia. E faço das palavras do @guhweb as minhas kkkkk

**Comment by matheusleite** [comment]
Pessoal, continuo com esse problema
Alguém encontrou uma solução?

Aqui estou na versão 3.15.7 do Chatwoot Nestor e 2.2.3 do Evolution
