### ISSUE TITLE
erro implementação chatwoot

### ISSUE THREAD

**Issue by guizaodev** [EvolutionAPI/evolution-api#919]
### Bem-vido!

- [X] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

Ao tentar adicionar a integração do chatwoot é mostrado o erro Unauthorized 401.

![image](https://github.com/user-attachments/assets/a405788f-d7c6-40d6-9040-c98d28fc5ebd)

![image](https://github.com/user-attachments/assets/c4d725e4-6d21-4c32-8bed-ad5edab16e81)

### O que você esperava?

Que a integração fosse bem sucedida.

### O que vc observou ao invés do que esperava?

Error 401

### Qual versão da API você está usando?

evolution: 2.1.1
chatwoot: 3.13.0

### Qual é o seu ambiente?

Docker

### Se aplicável, cole a saída do log

```json
{
    "message": "Request failed with status code 401",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 401\n    at G_ (https://evo2.meudominio.com/assets/index-Do1bGWiz.js:71:1034)\n    at XMLHttpRequest.p (https://evo2.meudominio.com/assets/index-Do1bGWiz.js:71:5881)\n    at di.request (https://evo2.meudominio.com/assets/index-Do1bGWiz.js:73:1965)\n    at async Object.zZ [as mutationFn] (https://evo2.meudominio.com/assets/index-Do1bGWiz.js:360:72071)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http",
            "fetch"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 30000,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json",
            "apikey": "TOKEN-EVO"
        },
        "method": "post",
        "url": "/chatwoot/set/NOME_INSTANCIA_EVO",
        "data": "{\"enabled\":true,\"accountId\":\"1\",\"token\":\"TOKEN_CHATWOOT\",\"url\":\"https://chatwoot.meudominio.com\",\"signMsg\":true,\"signDelimiter\":\"\\\\n\",\"nameInbox\":\"teste\",\"organization\":\"teste\",\"logo\":\"\",\"reopenConversation\":true,\"conversationPending\":false,\"mergeBrazilContacts\":false,\"importContacts\":true,\"importMessages\":true,\"daysLimitImportMessages\":7,\"autoCreate\":true,\"ignoreJids\":[]}",
        "baseURL": "https://evo2.meudominio.com"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 401
}
```

### Notas Adicionais

apaguei e recriei varias instancias, durante os teste, e teve uma hora que veio um erro diferente de inbox id not found, algo assim.

**Comment by vmanara** [comment]
idem

**Comment by rino3lucas** [comment]
Tive o mesmo erro e após ver o log do container no docker aparecia esse erro 401 com a mensagem no body "Você precisa entrar ou se cadastrar antes de continuar.".

Aparentemente o erro é causado por conta de uma configuração do nginx, como explicado no print abaixo:

![Captura de tela_27-9-2024_155441_www chatwoot com](https://github.com/user-attachments/assets/85b646af-6d09-4991-b419-9af15464a724)

URL da página descrevendo o problema: https://www.chatwoot.com/docs/self-hosted/deployment/caprover/#api-requests-failing-with-you-need-to-sign-in-or-sign-up-before-continuing

Para resolver basta adicionar essa opção no nginx.conf: `underscores_in_headers on;`

**Comment by guizaodev** [comment]
> Para resolver basta adicionar essa opção no nginx.conf: `underscores_in_headers on;`

Resolvido! Obrigado.

**Comment by j4mesmorais** [comment]
Estou tendo o mesmo problema! Como eu aplico essa solução para  o Nginx Proxy Manager (NPM) rodando via Docker Compose, ja tentei usar, underscores_in_headers on, no host especifico em Custom Nginx Configuration e não tenho obtido o resultado.

**Comment by marcosviniciuscl** [comment]
@j4mesmorais você conseguiu sucesso?

**Comment by marcosviniciuscl** [comment]
Aqui funcionou perfeitamente @j4mesmorais 
![Image](https://github.com/user-attachments/assets/dfb325e2-d0f6-49e6-82c0-d7e6f8b785e2)

**Comment by KevennyJS** [comment]
> > Para resolver basta adicionar essa opção no nginx.conf: `underscores_in_headers on;`
> 
> Resolvido! Obrigado.

Resolveu pra mim

**Comment by ifribeiro** [comment]
> Tive o mesmo erro e após ver o log do container no docker aparecia esse erro 401 com a mensagem no body "Você precisa entrar ou se cadastrar antes de continuar.".
> 
> Aparentemente o erro é causado por conta de uma configuração do nginx, como explicado no print abaixo:
> 
> ![Captura de tela_27-9-2024_155441_www chatwoot com](https://github.com/user-attachments/assets/85b646af-6d09-4991-b419-9af15464a724)
> 
> URL da página descrevendo o problema: https://www.chatwoot.com/docs/self-hosted/deployment/caprover/#api-requests-failing-with-you-need-to-sign-in-or-sign-up-before-continuing
> 
> Para resolver basta adicionar essa opção no nginx.conf: `underscores_in_headers on;`

Resolveu pra mim também.

**Comment by lucasffa** [comment]
exatamente. fiz o mesmo ajuste no nginx e funcionou.

**Comment by j4mesmorais** [comment]
Resolveu pra mim também! Obrigado pela força!

**Comment by OpenSysTecnologia** [comment]
Krl mano! O que eu procurei nao ta no gibi! Inteligencia artificial nenhuma me deu essa dica ai!

**Comment by renatojuniordw** [comment]
A solução do amigo funcionou direitinho, a correção foi simples: habilitei `underscores_in_headers on;` no `nginx.conf`, **apenas no server que realmente precisava**, sem mexer no restante da configuração. Depois disso, as requisições passaram a funcionar normalmente.

Trecho de exemplo de onde foi aplicado:

```nginx
server {
  server_name chatwoot.site.app.br;

  underscores_in_headers on;

  location / {
    ...
  }
}
```

Após recarregar o Nginx, o erro deixou de ocorrer e a integração com o Chatwoot passou a responder corretamente.

Obrigado!



> Tive o mesmo erro e após ver o log do container no docker aparecia esse erro 401 com a mensagem no body "Você precisa entrar ou se cadastrar antes de continuar.".
> 
> Aparentemente o erro é causado por conta de uma configuração do nginx, como explicado no print abaixo:
> 
> ![Captura de tela_27-9-2024_155441_www chatwoot com](https://github.com/user-attachments/assets/85b646af-6d09-4991-b419-9af15464a724)
> 
> URL da página descrevendo o problema: https://www.chatwoot.com/docs/self-hosted/deployment/caprover/#api-requests-failing-with-you-need-to-sign-in-or-sign-up-before-continuing
> 
> Para resolver basta adicionar essa opção no nginx.conf: `underscores_in_headers on;`
