### ISSUE TITLE
EVO respondendo para outra pessoa

### ISSUE THREAD

**Issue by tiagocaus** [EvolutionAPI/evolution-api#922]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Ao responder de forma comentada, no chatwoot mostra que está respondendo corretamente, mas no whatsapp aparece o numero de outra pessoa comentando outro mensagem.

### What did you expect?

Que seja para pessoa correta

### What did you observe instead of what you expected?

Que a mensagem vai para outra pessoa.

### Screenshots/Videos

# Fiz a resposta para uma pessoa:

![image](https://github.com/user-attachments/assets/3d5007a0-3e47-4512-a9a1-f7ba69c32555)

# E foi para outra:

![image](https://github.com/user-attachments/assets/ddb0f577-618a-4c13-9609-ba4c3300d45e)

### Which version of the API are you using?

2.1.1

### What is your environment?

Linux

### Additional Notes

# Isso é um erro crítico, pois envolve questão de privacidade.

**Comment by dpaes** [comment]
chegou a usar uma versão mais recente do evolution @tiagocaus pra validar se persiste o seu erro?
