### ISSUE TITLE
Endpoints "instance-create" e "instance-fetchInstances" ficam mais lentos na medida que novas instâncias são criadas.

### ISSUE THREAD

**Issue by leoneroli** [EvolutionAPI/evolution-api#94]
Observei que na medida que novas instâncias são criadas ou consultadas, os endpoints "instance-create" e "instance-fetchInstances" ficam cada vez mais lentos para retornarem o resultado da requisição.

Vi que ambos usam o método instanceInfo do monitor.service.ts. Existe um loop (for await) neste método que itera com todas as instâncias existentes. Quanto mais instâncias existir na VPS, mais lento vai ficando o processamento da requisição.

Atualmente meu projeto possui 220 instâncias conectadas. O tempo de resposta está passando de 30 segundos para ambos os endpoints, chegadno a causar timeout em alguns casos (o timeout do Postman Web é de 30s).

Poderiam verificar a possibilidade de otimização do algoritmo, para melhoria da performance destes endpoints?

Desde já agradeço a ajuda.

(versão 1.5.0)

**Comment by DavidsonGomes** [comment]
Aplicado na versao 1.5.1
