### ISSUE TITLE
EVO 2.1.1 with Dify 0.9.1 - Error communicating via webhook

### ISSUE THREAD

**Issue by wilsonfe** [EvolutionAPI/evolution-api#943]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

I found a bug in Dify version 0.9.1 with Evo 2.1.1. When communicating with Dify via webhook, the flow in Dify (from the agent) is always starting from the beginning and not from the point (steps) where it stopped. This occurs in this version of Dify, in version 0.8.3 this problem does not occur.

I am not using Evo's native connection or Chatflow, but the Agent with webhook.

It is certainly a library problem in Evo 2.1.1 with this new version of Dify.

### What did you expect?

That the flow does not start during interactions.

### What did you observe instead of what you expected?

Whenever you start a new message during the conversation, the agent flow starts without continuing the conversation where it left off.

### Which version of the API are you using?

2.1.1

### What is your environment?

Linux

### If applicable, paste the log output

Use an agent and connect dify using webhook with n8n. Start the conversation and see that the agent conversation always restarts.

**Comment by inbtec** [comment]
I'm also having these problems, the communication is restarting

**Comment by ip2cloud** [comment]
I'm also having these problems, the communication is restarting

**Comment by wilsonfe** [comment]
The problem is in Dify, in version 0.9.1 and 0.9.0. They are already aware and possibly a fix will come. I will close this issue because it is not a problem in Evolution.

**Comment by ip2cloud** [comment]
Do you have a problem being able to follow there?

**Comment by ip2cloud** [comment]
fixed in version  dify-web:release-0.9.2
