### ISSUE TITLE
Bug on the Start TypeBot Endpoint in v2.1.2

### ISSUE THREAD

**Issue by admdanielspalma** [EvolutionAPI/evolution-api#955]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

I was testing the Typebot integration using the startTypebot endpoint with the parameter startsession = true.

### What did you expect?

I expected the session to start regardless of the exact format of the JID, whether the number included the ninth digit or if it was missing the suffix @s.whatsapp.net.

### What did you observe instead of what you expected?

If the JID is not written exactly (e.g., the number includes the ninth digit or lacks the @s.whatsapp.net suffix), the flow initiates but the session does not start. I believe that once the flow begins, the session should also be initiated, but that does not happen unless the JID is perfectly formatted.

### Which version of the API are you using?

2.1.2

### What is your environment?

Linux

### Other environment specifications

Ubuntu Server - Docker Install

### Additional Notes

While the issue with startsession=true was initially addressed in v2.1.2, it seems that the problem persists under certain conditions when the JID is not written exactly.

**Comment by dpaes** [comment]
still the problem @admdanielspalma ? can confirm it?

**Comment by admdanielspalma** [comment]
Problem solved, thanks
