### ISSUE TITLE
Adicionar possibilidade do endpoint "Start Typebot" criar uma sessão

### ISSUE THREAD

**Issue by matheuskshn** [EvolutionAPI/evolution-api#97]
### **Descrição**

Olá, equipe.

Recentemente, enquanto interagia com a Evolution API nas versões 1.5.0 e 1.5.1 (versão de desenvolvimento), especificamente durante a integração com o Typebot, notei que, ao utilizar o endpoint "Start Typebot", a sessionID não parece ser gerada ou associada de forma adequada durante a primeira interação entre a Evolution API e o Typebot. No entanto, a partir da primeira resposta do usuário, a sessionID é devidamente criada e associada.

Adicionalmente, percebi que ao usar o endpoint "Change Session Status" para verificar o status das sessões ativas, a sessão que foi iniciada através do "Start Typebot" não é visível até que ocorra a primeira interação do usuário com o Typebot. Isso resulta em uma reinicialização do bot durante esta primeira interação, levando ao reenvio de mensagens já transmitidas anteriormente.

### **Sugestão de Aprimoramento**

Seria benéfico adicionar a possibilidade do endpoint "Start Typebot" criar uma sessão, facilitando uma geração e associação de sessionID desde o início da interação entre a Evolution API e o Typebot. Este aprimoramento poderia prevenir a reinicialização do bot que acontece após a primeira resposta do usuário no WhatsApp, garantindo uma experiência mais fluida e sem interrupções quando a interação parte do bot.

### **Passos para Observação atual**

1. Início um bot usando o endpoint "Start Typebot";
2. A mensagem é enviada corretamente para o WhatsApp, mas não há criação/associação da sessionID durante a primeira interação com o Typebot;
3. Uso o "Change Session Status" para verificar o status das sessões abertas, constatando que a sessão iniciada não é identificada inicialmente;
4. Observo que, durante a primeira resposta do usuário no WhatsApp ao interagir com o Typebot, ocorre uma reinicialização da automação do bot. Após esse ponto, a sessionID é corretamente exibida nas respostas do "Change Session Status".

### **Passos sugeridos no aprimoramento**

1. Início um bot usando o endpoint "Start Typebot", a sessão é criada nesse momento (pode ser configurável para criar ou não a sessão);
2. A mensagem é enviada corretamente para o WhatsApp e como já está dentro de uma sessão, a interação do usuário continua com o fluxo do bot.

Agradeço a atenção de vocês e estou disponível para fornecer mais detalhes, se necessário.

Obrigado!

**Comment by DavidsonGomes** [comment]
Opa tudo bem, o Start Typebot não foi feito para criar uma sessão, apenas para rodar um fluxo de forma isolada, pensando como um template para envio apenas

**Comment by matheuskshn** [comment]
Tudo bem, e você Davidson?

Entendo, então não é bug. Mas não acha que seria uma boa ideia se Start Typebot pudesse criar uma sessão?

**Comment by matheuskshn** [comment]
> Opa tudo bem, o Start Typebot não foi feito para criar uma sessão, apenas para rodar um fluxo de forma isolada, pensando como um template para envio apenas

@DavidsonGomes, modifiquei o "issue" para não parecer que é um bug, mais sim uma sugestão de melhoria, agradeço pelo feedback.

**Comment by MarcosBrendonDePaula** [comment]
Sua sugestão é bem parecida com essa #84, só que nessa a ideia é fazer o próprio evolutivo iniciar independente de quem veio ou mandou a mensagem informando um parâmetro para o typebot indicando em que ação foi criado.

**Comment by matheuskshn** [comment]
Será corrigido e aberto em um novo
