### ISSUE TITLE
[PT] - [BUG] - Grupo do whatsapp sem receber mensagem via chatwoot

### ISSUE THREAD

**Issue by Saimonexk** [EvolutionAPI/evolution-api#984]
### Bem-vido!

- [X] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

Tentei enviar uma mensagem para um grupo do WhatsApp por meio da integração Chatwoot com a Evolution API. A mensagem deveria ser entregue no grupo, mas falhou e resultou em um erro.

Contexto
Utilizo a integração entre o Chatwoot e a Evolution API para comunicação em grupos do WhatsApp. O problema ocorreu ao tentar enviar mensagens diretamente para um grupo que tem apenas 2 contatos, o que é uma funcionalidade importante para minha operação. Estou no ambiente do easypanel com as versões Evolution 2.1.0, Chatwoot 3.13.0, Redis 7.4.0 e PostGres 12

### O que você esperava?

Esperava que a mensagem fosse entregue corretamente no grupo do WhatsApp e que o envio ocorresse sem falhas.

### O que vc observou ao invés do que esperava?

Ao tentar enviar a mensagem, ocorreu o seguinte problema:

A mensagem não chegou ao grupo do WhatsApp.
O Chatwoot exibiu o erro "The message could not be sent. Please check your connection. [object Object]".

### Capturas de Tela/Vídeos

Erro:
![image](https://github.com/user-attachments/assets/13fd4f6a-1830-400d-8636-0a7497165e0e)

Enviroment ChatWoot (censurei a parte sensivel):
![image](https://github.com/user-attachments/assets/63cae838-0ef6-4533-be8e-64359d557459)

### Qual versão da API você está usando?

Evolution 2.1.0 
Chatwoot 3.13.0
Redis 7.4.0 
PostGres 12

### Qual é o seu ambiente?

Linux

### Se aplicável, cole a saída do log

Substitui a parte sensível por uma ficticia

I, [2024-10-16T11:12:33.846602 #1] INFO -- : source=rack-timeout id=def45678-1234-abcd-5678-abcdef123456 timeout=15000ms state=ready
I, [2024-10-16T11:12:33.847061 #1] INFO -- : [def45678-1234-abcd-5678-abcdef123456] Started POST "//api/v1/accounts/1/conversations/522/messages" for 172.69.114.24 at 2024-10-16 11:12:33 +0000
I, [2024-10-16T11:12:33.851411 #1] INFO -- : [def45678-1234-abcd-5678-abcdef123456] Processing by Api::V1::Accounts::Conversations::MessagesController#create as JSON
I, [2024-10-16T11:12:33.851467 #1] INFO -- : [def45678-1234-abcd-5678-abcdef123456] Parameters: {"content"=>"🚨 The message could not be sent. Please check your connection. _[object Object]_", "message_type"=>"outgoing", "private"=>"[FILTERED]", "account_id"=>"1", "conversation_id"=>"522"}
I, [2024-10-16T11:12:33.884572 #1] INFO -- : [def45678-1234-abcd-5678-abcdef123456] [ActiveJob] Enqueued ActionCableBroadcastJob (Job ID: 9876abcd-1234-5678-9abc-abcdef123456) to Sidekiq(critical) with arguments: ["randomString2"], "message.created", {:id=>3741, :content=>"🚨 The message could not be sent. Please check your connection. _[object Object]_", :account_id=>1, :inbox_id=>12, :conversation_id=>522, :message_type=>1, :created_at=>1729077153, :updated_at=>Wed, 16 Oct 2024 11:12:33.868341909 UTC +00:00, :private=>true, :status=>"sent", :source_id=>nil, :content_type=>"text", :content_attributes=>{}, :sender_type=>"User", :sender_id=>1, :external_source_ids=>{}, :additional_attributes=>{}, :processed_message_content=>"🚨 The message could not be sent. Please check your connection. _[object Object]_", :sentiment=>{}, :conversation=>{:assignee_id=>nil, :unread_count=>0, :last_activity_at=>1729077153, :contact_inbox=>{:source_id=>"bfb332e3-0605-4323-aac5-c730e3ff661b"}}, :sender=>{:id=>1, :name=>"John Doe", :available_name=>"John Doe - Web Dev", :avatar_url=>"", :type=>"user", :availability_status=>"online", :thumbnail=>""}, :performer=>{:id=>1, :name=>"John Doe", :available_name=>"John Doe - Web Dev", :avatar_url=>"", :type=>"user", :availability_status=>"online", :thumbnail=>""}}
I, [2024-10-16T11:12:33.887921 #1] INFO -- : [def45678-1234-abcd-5678-abcdef123456] [ActiveJob] Enqueued EventDispatcherJob (Job ID: 3456abcd-7890-1234-5678-abcdef9876) to Sidekiq(critical) with arguments: "message.created", Wed, 16 Oct 2024 11:12:33.873945247 UTC +00:00, {:message=>#<GlobalID:0x00007cd64b6e7168 @uri=#<URI::GID gid://chatwoot/Message/3741>>, :performed_by=>nil}
I, [2024-10-16T11:12:33.890763 #1] INFO -- : [def45678-1234-abcd-5678-abcdef123456] [ActiveJob] Enqueued SendReplyJob (Job ID: 4321abcd-5678-9abc-1234-abcdef6789) to Sidekiq(high) with arguments: 3741
I, [2024-10-16T11:12:33.899068 #1] INFO -- : [def45678-1234-abcd-5678-abcdef123456] Rendered api/v1/accounts/conversations/messages/create.json.jbuilder (Duration: 1.8ms | Allocations: 363)
I, [2024-10-16T11:12:33.902094 #1] INFO -- : [def45678-1234-abcd-5678-abcdef123456] Completed 200 OK in 51ms (Views: 2.8ms | ActiveRecord: 12.6ms | Allocations: 10009)
I, [2024-10-16T11:12:33.902394 #1] INFO -- : source=rack-timeout id=def45678-1234-abcd-5678-abcdef123456 timeout=15000ms service=56ms state=completed
I, [2024-10-16T11:12:33.919374 #1] INFO -- : source=rack-timeout id=9876abcd-5678-9abc-1234-abcd56789efg timeout=15000ms state=ready
I, [2024-10-16T11:12:33.919802 #1] INFO -- : [9876abcd-5678-9abc-1234-abcd56789efg] Started POST "/api/v1/accounts/1/conversations/522/update_last_seen" for 172.68.14.218 at 2024-10-16 11:12:33 +0000
I, [2024-10-16T11:12:33.925786 #1] INFO -- : [9876abcd-5678-9abc-1234-abcd56789efg] Processing by Api::V1::Accounts::ConversationsController#update_last_seen as JSON
I, [2024-10-16T11:12:33.925851 #1] INFO -- : [9876abcd-5678-9abc-1234-abcd56789efg] Parameters: {"account_id"=>"1", "id"=>"522"}
I, [2024-10-16T11:12:33.960400 #1] INFO -- : [9876abcd-5678-9abc-1234-abcd56789efg] Rendered api/v1/accounts/conversations/update_last_seen.json.jbuilder (Duration: 21.7ms | Allocations: 6536)
I, [2024-10-16T11:12:33.962670 #1] INFO -- : [9876abcd-5678-9abc-1234-abcd56789efg] Completed 200 OK in 37ms (Views: 18.8ms | ActiveRecord: 8.7ms | Allocations: 10137)
I, [2024-10-16T11:12:33.964393 #1] INFO -- : source=rack-timeout id=9876abcd-5678-9abc-1234-abcd56789efg timeout=15000ms service=45ms state=completed

### Notas Adicionais

Até encontrei problemas semelhantes nos #315, #321, #320 e #319 que até utilizavam a v1.6.1. Era comentado coisas como o problema com mongoDB ativado, então fiquei um pouco perdido no que eu deveria de fato utilizar. Desativei o mongo, deixei apenas com o Redis e dava o erro de qualquer maneira, mesmo apagando tudo e fazendo a reeinstalação da evolution e do chatwoot. 

Sinceramente só queria uma luz sobre como resolver isso. O fato de não poder mandar mensagens em grupos do whatsapp, mesmo que tenha apenas 2 contatos nele, via chatwoot.

**Comment by Saimonexk** [comment]
Atualização, conseguir resolver esse problema tirando o mongoDB.

Observei que no meu enviroment estava com o CACHE_REDIS_ENABLED=false. Passei a deixar true.

Bom é isso, era só eu ter pensado um pouco e batido a cabeça

**Comment by rafaelruch** [comment]
Conseguiu resolver o problema?

**Comment by pedroramosuerj** [comment]
> Atualização, conseguir resolver esse problema tirando o mongoDB.
> 
> Observei que no meu enviroment estava com o CACHE_REDIS_ENABLED=false. Passei a deixar true.
> 
> Bom é isso, era só eu ter pensado um pouco e batido a cabeça

Sabe como posso fazer isso via easypanel?

**Comment by r0drigocarvalho** [comment]
alguem conseguiu resolver?

**Comment by adfastltda** [comment]
@pedroramosuerj via env 

CACHE_REDIS_ENABLED=true
CACHE_REDIS_URI=redis://default:password@cache_redis:6379
CACHE_REDIS_TTL=604800
CACHE_REDIS_PREFIX_KEY=evolution
CACHE_REDIS_SAVE_INSTANCES=false

**Comment by Lmagalhaesz** [comment]
Pessoal, estou com o mesmo problema.. Adicionei as variáveis que vocês indicaram, porém continua a não enviar mensagens em grupo... Teriam alguma ideia do que pode ser feito de diferente?

**Comment by josimarsant** [comment]
Também estou com este problema, um grupo de duas pessoas não envia mensagem

<img width="916" height="666" alt="Image" src="https://github.com/user-attachments/assets/036e7bf4-2759-45cd-b73e-374638a76be7" />
