### ISSUE TITLE
Typebot is disabled

### ISSUE THREAD

**Issue by lucahttp** [EvolutionAPI/evolution-api#997]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

try to create a typebot instance

```bash
curl --location 'https://evo2.asdasdqwedasf/typebot/create/TEST2' \
--header 'accept: application/json, text/plain, */*' \
--header 'content-type: application/json' \
--data '{
    "enabled": true,
    "description": "retsdg",
    "url": "https://xxxxxxxxxxxxx",
    "typebot": "lead-generation-ro17juu",
    "triggerType": "keyword",
    "triggerOperator": "contains",
    "triggerValue": "",
    "expire": 0,
    "keywordFinish": "",
    "delayMessage": 0,
    "unknownMessage": "",
    "listeningFromMe": false,
    "stopBotFromMe": false,
    "keepOpen": false,
    "debounceTime": 0
}'
```

### What did you expect?

have it created

### What did you observe instead of what you expected?

an error

```json
{
    "status": 400,
    "error": "Bad Request",
    "response": {
        "message": [
            "Typebot is disabled"
        ]
    }
}
```

![image](https://github.com/user-attachments/assets/082b1f5c-2476-45c4-83dd-2b2a70fb1138)

### Which version of the API are you using?

v2.1.1

### What is your environment?

Windows

### Other environment specifications

Docker Compose, using traefik, cloudflare
Ubuntu VPS

**Comment by adfastltda** [comment]
here too. Installed in easypanel

**Comment by yagoylc** [comment]
Confiram as variaveis de ambiente:
    - TYPEBOT_ENABLED=true
    - TYPEBOT_API_VERSION=latest

**Comment by lucahttp** [comment]
obrigado, now is working

**Comment by harleycorreia** [comment]
> Confiram as variaveis de ambiente: - TYPEBOT_ENABLED=true - TYPEBOT_API_VERSION=latest

Instalei usando easypanel. Onde coloco essas variáveis? No typebot-builder ?

**Comment by llepe** [comment]
> Confiram as variaveis de ambiente: - TYPEBOT_ENABLED=true - TYPEBOT_API_VERSION=latest

It's working now, but the configuration it's not in the documentation

**Comment by RhaysonMuchiutti** [comment]
Já fiz tudo que foi citado acima e ainda estou com o mesmo problema, alguem pode me ajudar por favor

**Comment by adfastltda** [comment]
> Confiram as variaveis de ambiente: - TYPEBOT_ENABLED=true - TYPEBOT_API_VERSION=latest

that worked

**Comment by VHUIS** [comment]
> Confiram as variaveis de ambiente: - TYPEBOT_ENABLED=true - TYPEBOT_API_VERSION=latest

Aqui deu certo assim, tinha olhado a documentação toda, o Enabled não estava mesmo

**Comment by DiegoVenancioVieira** [comment]
> Já fiz tudo que foi citado acima e ainda estou com o mesmo problema, alguem pode me ajudar por favor

Conseguiu resolver, estou com o mesmo problema já há dias.

**Comment by jonatansouza2k11** [comment]
Eu ainda não consegui :/

**Comment by gabrieldiapiso** [comment]
Obrigado, para mim deu certo!

**Comment by gianfrancoropel** [comment]
en mi caso, docker estaba leyendo una version anterior de mi .env

para solucionarlo:

1:

`docker-compose down`

2: 

`docker-compose up -d`

**Comment by AdminMicael** [comment]
> Confiram as variaveis de ambiente: - TYPEBOT_ENABLED=true - TYPEBOT_API_VERSION=latest

deu certo tbm aqui pra mim! \0/

**Comment by carlosdanielmirandadelima-blip** [comment]
Consegui resolver também, só que agora eu adiciono o bot e ele não está funcionando no WhatsApp, como eu arrumo?
